WITH
SQ_medical_bill_service AS (
	SELECT medical_bill_service.med_bill_serv_id, medical_bill_service.med_bill_serv_ak_id, medical_bill_service.serv_seq_num, medical_bill_service.serv_from_date, medical_bill_service.serv_to_date, medical_bill_service.serv_place_code, medical_bill_service.serv_type_code, medical_bill_service.bill_review_adjusted_code1, medical_bill_service.bill_review_adjusted_code2, medical_bill_service.modified_proc_code1, medical_bill_service.modified_proc_descript, medical_bill_service.modified_proc_code2, medical_bill_service.modified_proc_descript2, medical_bill_service.serv_minutes, medical_bill_service.serv_units, medical_bill_service.drug_qty_dispensed, medical_bill_service.drug_qty_allowed, medical_bill_service.drug_actual_wholesale_price, medical_bill_service.proc_drug_revenue_type_ind, medical_bill_service.proc_drug_revenue_code, medical_bill_service.proc_drug_revenue_descript, medical_bill_service.serv_charge, medical_bill_service.serv_bill_review_red, medical_bill_service.serv_network_red, medical_bill_service.serv_recommend_pay, medical_bill_service.serv_review_comment, medical_bill_service.diagnose_cross_ref 
	FROM
	@{pipeline().parameters.SOURCE_TABLE_OWNER}.medical_bill_service
	WHERE
	CREATED_DATE >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_AUDIT AS (
	SELECT
	med_bill_serv_id,
	med_bill_serv_ak_id,
	serv_seq_num,
	serv_from_date,
	serv_to_date,
	serv_place_code,
	serv_type_code,
	bill_review_adjusted_code1,
	bill_review_adjusted_code2,
	modified_proc_code1,
	modified_proc_descript,
	modified_proc_code2,
	modified_proc_descript2,
	serv_minutes,
	serv_units,
	drug_qty_dispensed,
	drug_qty_allowed,
	drug_actual_wholesale_price,
	proc_drug_revenue_type_ind,
	proc_drug_revenue_code,
	proc_drug_revenue_descript,
	serv_charge,
	serv_bill_review_red,
	serv_network_red,
	serv_recommend_pay,
	serv_review_comment,
	diagnose_cross_ref,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS audit_id,
	1 AS crrnt_snpsht_flag,
	-- *INF*: to_date('01/01/1800 01:00:00','MM/DD/YYYY HH24:MI:SS')
	to_date('01/01/1800 01:00:00', 'MM/DD/YYYY HH24:MI:SS') AS eff_from_date,
	-- *INF*: to_date('12/31/2100 23:59:59','MM/DD/YYYY HH24:MI:SS')
	to_date('12/31/2100 23:59:59', 'MM/DD/YYYY HH24:MI:SS') AS eff_to_date,
	sysdate AS created_date,
	sysdate AS modified_date
	FROM SQ_medical_bill_service
),
LKP_Medical_Bill_Serv_Exists AS (
	SELECT
	med_bill_serv_dim_id,
	edw_med_bill_serv_pk_id,
	edw_med_bill_serv_ak_id,
	serv_seq_num,
	serv_from_date,
	serv_to_date,
	serv_place_code,
	serv_type_code,
	bill_review_adjusted_code1,
	bill_review_adjusted_code2,
	modified_proc_code1,
	modified_proc_descript,
	modified_proc_code2,
	modified_proc_descript2,
	serv_minutes,
	serv_units,
	drug_qty_dispensed,
	drug_qty_allowed,
	drug_actual_wholesale_price,
	proc_drug_revenue_type_ind,
	proc_drug_revenue_code,
	proc_drug_revenue_descript,
	serv_charge,
	serv_bill_review_red,
	serv_network_red,
	serv_recommend_pay,
	serv_review_comment,
	diagnose_cross_ref,
	crrnt_snpsht_flag,
	audit_id,
	eff_from_date,
	eff_to_date,
	created_date,
	modified_date,
	med_bill_serv_ak_id,
	serv_seq_num1,
	serv_units1,
	proc_drug_revenue_descript1,
	serv_charge1,
	serv_bill_review_red1,
	serv_network_red1,
	serv_recommend_pay1,
	serv_review_comment1
	FROM (
		SELECT 
			med_bill_serv_dim_id,
			edw_med_bill_serv_pk_id,
			edw_med_bill_serv_ak_id,
			serv_seq_num,
			serv_from_date,
			serv_to_date,
			serv_place_code,
			serv_type_code,
			bill_review_adjusted_code1,
			bill_review_adjusted_code2,
			modified_proc_code1,
			modified_proc_descript,
			modified_proc_code2,
			modified_proc_descript2,
			serv_minutes,
			serv_units,
			drug_qty_dispensed,
			drug_qty_allowed,
			drug_actual_wholesale_price,
			proc_drug_revenue_type_ind,
			proc_drug_revenue_code,
			proc_drug_revenue_descript,
			serv_charge,
			serv_bill_review_red,
			serv_network_red,
			serv_recommend_pay,
			serv_review_comment,
			diagnose_cross_ref,
			crrnt_snpsht_flag,
			audit_id,
			eff_from_date,
			eff_to_date,
			created_date,
			modified_date,
			med_bill_serv_ak_id,
			serv_seq_num1,
			serv_units1,
			proc_drug_revenue_descript1,
			serv_charge1,
			serv_bill_review_red1,
			serv_network_red1,
			serv_recommend_pay1,
			serv_review_comment1
		FROM medical_bill_service_dim
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY edw_med_bill_serv_ak_id,serv_seq_num,serv_units,proc_drug_revenue_descript,serv_charge,serv_bill_review_red,serv_network_red,serv_recommend_pay,serv_review_comment ORDER BY med_bill_serv_dim_id) = 1
),
RTR_INS_UPD AS (
	SELECT
	LKP_Medical_Bill_Serv_Exists.med_bill_serv_dim_id,
	EXP_AUDIT.med_bill_serv_id,
	EXP_AUDIT.med_bill_serv_ak_id,
	EXP_AUDIT.serv_seq_num,
	EXP_AUDIT.serv_from_date,
	EXP_AUDIT.serv_to_date,
	EXP_AUDIT.serv_place_code,
	EXP_AUDIT.serv_type_code,
	EXP_AUDIT.bill_review_adjusted_code1,
	EXP_AUDIT.bill_review_adjusted_code2,
	EXP_AUDIT.modified_proc_code1,
	EXP_AUDIT.modified_proc_descript,
	EXP_AUDIT.modified_proc_code2,
	EXP_AUDIT.modified_proc_descript2,
	EXP_AUDIT.serv_minutes,
	EXP_AUDIT.serv_units,
	EXP_AUDIT.drug_qty_dispensed,
	EXP_AUDIT.drug_qty_allowed,
	EXP_AUDIT.drug_actual_wholesale_price,
	EXP_AUDIT.proc_drug_revenue_type_ind,
	EXP_AUDIT.proc_drug_revenue_code,
	EXP_AUDIT.proc_drug_revenue_descript,
	EXP_AUDIT.serv_charge,
	EXP_AUDIT.serv_bill_review_red,
	EXP_AUDIT.serv_network_red,
	EXP_AUDIT.serv_recommend_pay,
	EXP_AUDIT.serv_review_comment,
	EXP_AUDIT.diagnose_cross_ref,
	EXP_AUDIT.audit_id,
	EXP_AUDIT.crrnt_snpsht_flag,
	EXP_AUDIT.eff_from_date,
	EXP_AUDIT.eff_to_date,
	EXP_AUDIT.created_date,
	EXP_AUDIT.modified_date
	FROM EXP_AUDIT
	LEFT JOIN LKP_Medical_Bill_Serv_Exists
	ON LKP_Medical_Bill_Serv_Exists.edw_med_bill_serv_ak_id = EXP_AUDIT.med_bill_serv_ak_id AND LKP_Medical_Bill_Serv_Exists.serv_seq_num = EXP_AUDIT.serv_seq_num AND LKP_Medical_Bill_Serv_Exists.serv_units = EXP_AUDIT.serv_units AND LKP_Medical_Bill_Serv_Exists.proc_drug_revenue_descript = EXP_AUDIT.proc_drug_revenue_descript AND LKP_Medical_Bill_Serv_Exists.serv_charge = EXP_AUDIT.serv_charge AND LKP_Medical_Bill_Serv_Exists.serv_bill_review_red = EXP_AUDIT.serv_bill_review_red AND LKP_Medical_Bill_Serv_Exists.serv_network_red = EXP_AUDIT.serv_network_red AND LKP_Medical_Bill_Serv_Exists.serv_recommend_pay = EXP_AUDIT.serv_recommend_pay AND LKP_Medical_Bill_Serv_Exists.serv_review_comment = EXP_AUDIT.serv_review_comment
),
RTR_INS_UPD_insert AS (SELECT * FROM RTR_INS_UPD WHERE isnull(med_bill_serv_dim_id)),
RTR_INS_UPD_DEFAULT1 AS (SELECT * FROM RTR_INS_UPD WHERE NOT ( (isnull(med_bill_serv_dim_id)) )),
UPD_Med_Bill_Serv_Dim_U AS (
	SELECT
	med_bill_serv_dim_id AS med_bill_serv_dim_id2, 
	med_bill_serv_id AS med_bill_serv_id2, 
	med_bill_serv_ak_id AS med_bill_serv_ak_id2, 
	serv_seq_num AS serv_seq_num2, 
	serv_from_date AS serv_from_date2, 
	serv_to_date AS serv_to_date2, 
	serv_place_code AS serv_place_code2, 
	serv_type_code AS serv_type_code2, 
	bill_review_adjusted_code1 AS bill_review_adjusted_code12, 
	bill_review_adjusted_code AS bill_review_adjusted_code22, 
	modified_proc_code1 AS modified_proc_code12, 
	modified_proc_descript3, 
	modified_proc_code AS modified_proc_code22, 
	modified_proc_descript AS modified_proc_descript22, 
	serv_minutes AS serv_minutes2, 
	serv_units AS serv_units2, 
	drug_qty_dispensed AS drug_qty_dispensed2, 
	drug_qty_allowed AS drug_qty_allowed2, 
	drug_actual_wholesale_price AS drug_actual_wholesale_price2, 
	proc_drug_revenue_type_ind AS proc_drug_revenue_type_ind2, 
	proc_drug_revenue_code AS proc_drug_revenue_code2, 
	proc_drug_revenue_descript AS proc_drug_revenue_descript2, 
	serv_charge AS serv_charge2, 
	serv_bill_review_red AS serv_bill_review_red2, 
	serv_network_red AS serv_network_red2, 
	serv_recommend_pay AS serv_recommend_pay2, 
	serv_review_comment AS serv_review_comment2, 
	diagnose_cross_ref AS diagnose_cross_ref2, 
	audit_id AS audit_id2, 
	crrnt_snpsht_flag AS crrnt_snpsht_flag2, 
	eff_from_date AS eff_from_date2, 
	eff_to_date AS eff_to_date2, 
	created_date AS created_date2, 
	modified_date AS modified_date2
	FROM RTR_INS_UPD_DEFAULT1
),
medical_bill_service_dim_upd AS (
	MERGE INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.medical_bill_service_dim AS T
	USING UPD_Med_Bill_Serv_Dim_U AS S
	ON T.med_bill_serv_dim_id = S.med_bill_serv_dim_id2
	WHEN MATCHED BY TARGET THEN
	UPDATE SET T.edw_med_bill_serv_pk_id = S.med_bill_serv_id2, T.edw_med_bill_serv_ak_id = S.med_bill_serv_ak_id2, T.serv_seq_num = S.serv_seq_num2, T.serv_from_date = S.serv_from_date2, T.serv_to_date = S.serv_to_date2, T.serv_place_code = S.serv_place_code2, T.serv_type_code = S.serv_type_code2, T.bill_review_adjusted_code1 = S.bill_review_adjusted_code12, T.bill_review_adjusted_code2 = S.bill_review_adjusted_code22, T.modified_proc_code1 = S.modified_proc_code12, T.modified_proc_descript = S.modified_proc_descript3, T.modified_proc_code2 = S.modified_proc_code22, T.modified_proc_descript2 = S.modified_proc_descript22, T.serv_minutes = S.serv_minutes2, T.serv_units = S.serv_units2, T.drug_qty_dispensed = S.drug_qty_dispensed2, T.drug_qty_allowed = S.drug_qty_allowed2, T.drug_actual_wholesale_price = S.drug_actual_wholesale_price2, T.proc_drug_revenue_type_ind = S.proc_drug_revenue_type_ind2, T.proc_drug_revenue_code = S.proc_drug_revenue_code2, T.proc_drug_revenue_descript = S.proc_drug_revenue_descript2, T.serv_charge = S.serv_charge2, T.serv_bill_review_red = S.serv_bill_review_red2, T.serv_network_red = S.serv_network_red2, T.serv_recommend_pay = S.serv_recommend_pay2, T.serv_review_comment = S.serv_review_comment2, T.diagnose_cross_ref = S.diagnose_cross_ref2, T.audit_id = S.audit_id2, T.modified_date = S.modified_date2
),
medical_bill_service_dim_ins AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.medical_bill_service_dim
	(edw_med_bill_serv_pk_id, edw_med_bill_serv_ak_id, serv_seq_num, serv_from_date, serv_to_date, serv_place_code, serv_type_code, bill_review_adjusted_code1, bill_review_adjusted_code2, modified_proc_code1, modified_proc_descript, modified_proc_code2, modified_proc_descript2, serv_minutes, serv_units, drug_qty_dispensed, drug_qty_allowed, drug_actual_wholesale_price, proc_drug_revenue_type_ind, proc_drug_revenue_code, proc_drug_revenue_descript, serv_charge, serv_bill_review_red, serv_network_red, serv_recommend_pay, serv_review_comment, diagnose_cross_ref, crrnt_snpsht_flag, audit_id, eff_from_date, eff_to_date, created_date, modified_date)
	SELECT 
	med_bill_serv_id AS EDW_MED_BILL_SERV_PK_ID, 
	med_bill_serv_ak_id AS EDW_MED_BILL_SERV_AK_ID, 
	SERV_SEQ_NUM, 
	SERV_FROM_DATE, 
	SERV_TO_DATE, 
	SERV_PLACE_CODE, 
	SERV_TYPE_CODE, 
	bill_review_adjusted_code AS BILL_REVIEW_ADJUSTED_CODE1, 
	BILL_REVIEW_ADJUSTED_CODE2, 
	modified_proc_code AS MODIFIED_PROC_CODE1, 
	MODIFIED_PROC_DESCRIPT, 
	MODIFIED_PROC_CODE2, 
	MODIFIED_PROC_DESCRIPT2, 
	SERV_MINUTES, 
	SERV_UNITS, 
	DRUG_QTY_DISPENSED, 
	DRUG_QTY_ALLOWED, 
	DRUG_ACTUAL_WHOLESALE_PRICE, 
	PROC_DRUG_REVENUE_TYPE_IND, 
	PROC_DRUG_REVENUE_CODE, 
	PROC_DRUG_REVENUE_DESCRIPT, 
	SERV_CHARGE, 
	SERV_BILL_REVIEW_RED, 
	SERV_NETWORK_RED, 
	SERV_RECOMMEND_PAY, 
	SERV_REVIEW_COMMENT, 
	DIAGNOSE_CROSS_REF, 
	CRRNT_SNPSHT_FLAG, 
	AUDIT_ID, 
	EFF_FROM_DATE, 
	EFF_TO_DATE, 
	CREATED_DATE, 
	MODIFIED_DATE
	FROM RTR_INS_UPD_insert
),