WITH
SQ_Agency AS (
	SELECT
		AgencyID,
		SourceSystemID,
		HashKey,
		ModifiedUserID,
		ModifiedDate,
		AgencyCode,
		LegalName,
		DoingBusinessAsName,
		PrimaryPhoneNumber,
		PrimaryFaxNumber,
		PrimaryEmailAddress,
		StatusCode,
		StatusDescription,
		AppointedDate,
		TerminatedDate,
		CustomerCareStatus,
		FederalTaxId,
		LicensedIndicator,
		ProfitSharingGuaranteeFlag,
		AbbreviatedName,
		AssignedStateCode,
		ClosedDate
	FROM Agency
),
EXP_Add_MetaDataFields AS (
	SELECT
	AgencyID,
	SourceSystemID,
	HashKey,
	ModifiedUserID,
	ModifiedDate,
	AgencyCode,
	LegalName,
	DoingBusinessAsName,
	PrimaryPhoneNumber,
	PrimaryFaxNumber,
	PrimaryEmailAddress,
	StatusCode,
	StatusDescription,
	AppointedDate,
	TerminatedDate,
	CustomerCareStatus,
	FederalTaxId,
	LicensedIndicator,
	ProfitSharingGuaranteeFlag,
	AbbreviatedName,
	AssignedStateCode,
	ClosedDate,
	sysdate AS Extract_Date,
	sysdate AS As_of_Date,
	1 AS Record_Count,
	@{pipeline().parameters.SOURCESYSTEMID} AS Source_System_ID
	FROM SQ_Agency
),
AgencyODSStage AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.AgencyODSStage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.AgencyODSStage
	(AgencyODSSourceSystemID, HashKey, ModifiedUserID, ModifiedDate, AgencyID, AgencyCode, LegalName, DoingBusinessAsName, PrimaryPhoneNumber, PrimaryFaxNumber, PrimaryEmailAddress, StatusCode, StatusDescription, AppointedDate, TerminatedDate, CustomerCareStatus, FederalTaxID, ExtractDate, AsOfDate, RecordCount, SourceSystemID, ProfitSharingGuaranteeFlag, LicensedIndicator, AbbreviatedName, AssignedStateCode, ClosedDate)
	SELECT 
	SourceSystemID AS AGENCYODSSOURCESYSTEMID, 
	HASHKEY, 
	MODIFIEDUSERID, 
	MODIFIEDDATE, 
	AGENCYID, 
	AGENCYCODE, 
	LEGALNAME, 
	DOINGBUSINESSASNAME, 
	PRIMARYPHONENUMBER, 
	PRIMARYFAXNUMBER, 
	PRIMARYEMAILADDRESS, 
	STATUSCODE, 
	STATUSDESCRIPTION, 
	APPOINTEDDATE, 
	TERMINATEDDATE, 
	CUSTOMERCARESTATUS, 
	FederalTaxId AS FEDERALTAXID, 
	Extract_Date AS EXTRACTDATE, 
	As_of_Date AS ASOFDATE, 
	Record_Count AS RECORDCOUNT, 
	Source_System_ID AS SOURCESYSTEMID, 
	PROFITSHARINGGUARANTEEFLAG, 
	LICENSEDINDICATOR, 
	ABBREVIATEDNAME, 
	ASSIGNEDSTATECODE, 
	CLOSEDDATE
	FROM EXP_Add_MetaDataFields
),