WITH
SQ_RSM_stage AS (
	SELECT
		RSM_stage_id,
		RSM_ID,
		RSM_FIRST_NAME,
		RSM_MIDDLE_NAME,
		RSM_LAST_NAME,
		RSM_SUFFIX,
		RSM_EMAIL,
		EMP_ID,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM RSM_stage
),
EXP_AGY_ARCH_Insert_RSM AS (
	SELECT
	RSM_stage_id,
	RSM_ID,
	RSM_FIRST_NAME,
	RSM_MIDDLE_NAME,
	RSM_LAST_NAME,
	RSM_SUFFIX,
	RSM_EMAIL,
	EMP_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS OUT_AUDIT_ID
	FROM SQ_RSM_stage
),
TGT_Arch_RSM_stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.arch_RSM_stage
	(RSM_stage_id, RSM_ID, RSM_FIRST_NAME, RSM_MIDDLE_NAME, RSM_LAST_NAME, RSM_SUFFIX, RSM_EMAIL, EMP_ID, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, audit_id)
	SELECT 
	RSM_STAGE_ID, 
	RSM_ID, 
	RSM_FIRST_NAME, 
	RSM_MIDDLE_NAME, 
	RSM_LAST_NAME, 
	RSM_SUFFIX, 
	RSM_EMAIL, 
	EMP_ID, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	OUT_AUDIT_ID AS AUDIT_ID
	FROM EXP_AGY_ARCH_Insert_RSM
),