WITH
SQ_agency_address_Stage AS (
	SELECT
		agency_address_stage_id AS agency_address_id,
		STATE_CODE,
		AGENCY_NUM,
		ADDRESS_TYPE,
		ADDRESS_LINE_1,
		ADDRESS_LINE_2,
		ADDRESS_LINE_3,
		CITY,
		POSTAL_CODE,
		ZIP_PLUS_4,
		COUNTY,
		STATE_ABBREV,
		COUNTRY,
		AGENCY_CODE,
		COUNTY_LOCATION,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM Agency_Address_Stage
),
exp_AGY_Insert_Arch_Agy_Addrs AS (
	SELECT
	agency_address_id,
	STATE_CODE,
	AGENCY_NUM,
	ADDRESS_TYPE,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	ADDRESS_LINE_3,
	CITY,
	POSTAL_CODE,
	ZIP_PLUS_4,
	COUNTY,
	STATE_ABBREV,
	COUNTRY,
	AGENCY_CODE,
	COUNTY_LOCATION,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS OUT_AUDIT_ID
	FROM SQ_agency_address_Stage
),
TGT_arch_agency_address_Stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.arch_agency_address_Stage
	(agency_address_stage_id, STATE_CODE, AGENCY_NUM, ADDRESS_TYPE, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, CITY, POSTAL_CODE, ZIP_PLUS_4, COUNTY, STATE_ABBREV, COUNTRY, AGENCY_CODE, COUNTY_LOCATION, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, audit_id)
	SELECT 
	agency_address_id AS AGENCY_ADDRESS_STAGE_ID, 
	STATE_CODE, 
	AGENCY_NUM, 
	ADDRESS_TYPE, 
	ADDRESS_LINE_1, 
	ADDRESS_LINE_2, 
	ADDRESS_LINE_3, 
	CITY, 
	POSTAL_CODE, 
	ZIP_PLUS_4, 
	COUNTY, 
	STATE_ABBREV, 
	COUNTRY, 
	AGENCY_CODE, 
	COUNTY_LOCATION, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	OUT_AUDIT_ID AS AUDIT_ID
	FROM exp_AGY_Insert_Arch_Agy_Addrs
),