WITH
SQ_CLM_LOG_NOTES_STAGE AS (
	SELECT CLM_LOG_NOTES_STAGE.CLM_LOG_NOTES_ID, CLM_LOG_NOTES_STAGE.CLAIM_NBR, CLM_LOG_NOTES_STAGE.NOTE_ID, CLM_LOG_NOTES_STAGE.CLIENT_ID, CLM_LOG_NOTES_STAGE.AUTHOR_USER_ID, CLM_LOG_NOTES_STAGE.AUTHOR_NAME, CLM_LOG_NOTES_STAGE.DELETED_USER_NAME, CLM_LOG_NOTES_STAGE.NOTE_TEXT, CLM_LOG_NOTES_STAGE.CREATE_DATE, CLM_LOG_NOTES_STAGE.DELETED_DATE, CLM_LOG_NOTES_STAGE.DELETED_USER_ID, CLM_LOG_NOTES_STAGE.VIEWABLE_FLAG, CLM_LOG_NOTES_STAGE.NOTIFY_UW, CLM_LOG_NOTES_STAGE.NOTE_TYPE, CLM_LOG_NOTES_STAGE.NOTIFY_SIU, CLM_LOG_NOTES_STAGE.NOTIFY_COLLECTION, CLM_LOG_NOTES_STAGE.EXTRACT_DATE, CLM_LOG_NOTES_STAGE.AS_OF_DATE, CLM_LOG_NOTES_STAGE.RECORD_COUNT, CLM_LOG_NOTES_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLM_LOG_NOTES_STAGE
	WHERE
	CLM_LOG_NOTES_STAGE.CREATE_DATE >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	CLM_LOG_NOTES_STAGE.DELETED_DATE >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLM_LOG_NOTES_STAGE AS (
	SELECT
	CLM_LOG_NOTES_ID,
	CLAIM_NBR,
	NOTE_ID,
	CLIENT_ID,
	AUTHOR_USER_ID,
	AUTHOR_NAME,
	DELETED_USER_NAME,
	NOTE_TEXT,
	CREATE_DATE,
	DELETED_DATE,
	DELETED_USER_ID,
	VIEWABLE_FLAG,
	NOTIFY_UW,
	NOTE_TYPE,
	NOTIFY_SIU,
	NOTIFY_COLLECTION,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLM_LOG_NOTES_STAGE
),
ARCH_CLM_LOG_NOTES_STAGE AS (
	INSERT INTO ARCH_CLM_LOG_NOTES_STAGE
	(clm_log_notes_id, claim_nbr, note_id, client_id, author_user_id, author_name, deleted_user_name, note_text, create_date, deleted_date, deleted_user_id, viewable_flag, notify_uw, note_type, notify_siu, notify_collection, extract_date, as_of_date, record_count, source_system_id, audit_id)
	SELECT 
	CLM_LOG_NOTES_ID AS CLM_LOG_NOTES_ID, 
	CLAIM_NBR AS CLAIM_NBR, 
	NOTE_ID AS NOTE_ID, 
	CLIENT_ID AS CLIENT_ID, 
	AUTHOR_USER_ID AS AUTHOR_USER_ID, 
	AUTHOR_NAME AS AUTHOR_NAME, 
	DELETED_USER_NAME AS DELETED_USER_NAME, 
	NOTE_TEXT AS NOTE_TEXT, 
	CREATE_DATE AS CREATE_DATE, 
	DELETED_DATE AS DELETED_DATE, 
	DELETED_USER_ID AS DELETED_USER_ID, 
	VIEWABLE_FLAG AS VIEWABLE_FLAG, 
	NOTIFY_UW AS NOTIFY_UW, 
	NOTE_TYPE AS NOTE_TYPE, 
	NOTIFY_SIU AS NOTIFY_SIU, 
	NOTIFY_COLLECTION AS NOTIFY_COLLECTION, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLM_LOG_NOTES_STAGE
),