WITH
SQ_ClaimStoryStage AS (
	SELECT
		ClaimStoryStageId,
		TCH_CLAIM_NBR,
		CREATED_TS,
		CLAIM_TYPE_CATEGORY,
		CAUSE_ID,
		PHYSICAL_ITEM_INVOLVED_ID,
		RESULTING_DAMAGE_ID,
		ITEM_DAMAGED_ID,
		USER_ID,
		ExtractDate,
		SourceSystemId
	FROM ClaimStoryStage
),
EXPTRANS AS (
	SELECT
	ClaimStoryStageId,
	TCH_CLAIM_NBR,
	CREATED_TS,
	CLAIM_TYPE_CATEGORY,
	CAUSE_ID,
	PHYSICAL_ITEM_INVOLVED_ID,
	RESULTING_DAMAGE_ID,
	ITEM_DAMAGED_ID,
	USER_ID,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AuditID
	FROM SQ_ClaimStoryStage
),
ArchClaimStoryStage AS (
	INSERT INTO ArchClaimStoryStage
	(ClaimStoryStageId, TCH_CLAIM_NBR, CREATED_TS, CLAIM_TYPE_CATEGORY, CAUSE_ID, PHYSICAL_ITEM_INVOLVED_ID, RESULTING_DAMAGE_ID, ITEM_DAMAGED_ID, USER_ID, ExtractDate, SourceSystemId, AuditId)
	SELECT 
	CLAIMSTORYSTAGEID, 
	TCH_CLAIM_NBR, 
	CREATED_TS, 
	CLAIM_TYPE_CATEGORY, 
	CAUSE_ID, 
	PHYSICAL_ITEM_INVOLVED_ID, 
	RESULTING_DAMAGE_ID, 
	ITEM_DAMAGED_ID, 
	USER_ID, 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	AuditID AS AUDITID
	FROM EXPTRANS
),