WITH
SQ_CLAIM_DRAFT_STAGE1 AS (
	SELECT
		claim_draft_id AS CLAIM_DRAFT_ID,
		dft_draft_nbr AS DFT_DRAFT_NBR,
		dft_bank_nm_id AS DFT_BANK_NM_ID,
		dft_bank_nbr AS DFT_BANK_NBR,
		dft_draft_ctl_seq AS DFT_DRAFT_CTL_SEQ,
		dft_mail_to_nm_id AS DFT_MAIL_TO_NM_ID,
		dft_memo_phr_des AS DFT_MEMO_PHR_DES,
		dft_mail_to_adr_1 AS DFT_MAIL_TO_ADR_1,
		dft_mail_to_adr_2 AS DFT_MAIL_TO_ADR_2,
		dft_payee_nm_id_1 AS DFT_PAYEE_NM_ID_1,
		dft_payee_nm_id_2 AS DFT_PAYEE_NM_ID_2,
		dft_payee_nm_id_3 AS DFT_PAYEE_NM_ID_3,
		dft_tax_id_nbr AS DFT_TAX_ID_NBR,
		dft_trs_amt AS DFT_TRS_AMT,
		dft_update_opr_id AS DFT_UPDATE_OPR_ID,
		dft_pmsd_ts AS DFT_PMSD_TS,
		dft_upd_ts AS DFT_UPD_TS,
		dft_mail_to_zip_cd AS DFT_MAIL_TO_ZIP_CD,
		dft_payee_phr_des AS DFT_PAYEE_PHR_DES,
		dft_ck_draft_ind AS DFT_CK_DRAFT_IND,
		dft_producer_nm_id AS DFT_PRODUCER_NM_ID,
		dft_dft_ck_typ_cd AS DFT_DFT_CK_TYP_CD,
		dft_sch_of_nbr AS DFT_SCH_OF_NBR,
		dft_sch_seq_nbr AS DFT_SCH_SEQ_NBR,
		dft_report_to_irs AS DFT_REPORT_TO_IRS,
		dft_tax_id_type_cd AS DFT_TAX_ID_TYPE_CD,
		dft_entry_opr_id AS DFT_ENTRY_OPR_ID,
		dft_create_ts AS DFT_CREATE_TS,
		ck_dft_apv_ind AS CK_DFT_APV_IND,
		dft_aut_by_id AS DFT_AUT_BY_ID,
		dft_micrp_ecd_nbr AS DFT_MICRP_ECD_NBR,
		dft_mmo_phr_cmt_id AS DFT_MMO_PHR_CMT_ID,
		dft_clt_seq_nbr_1 AS DFT_CLT_SEQ_NBR_1,
		dft_clt_seq_nbr_2 AS DFT_CLT_SEQ_NBR_2,
		dft_clt_seq_nbr_3 AS DFT_CLT_SEQ_NBR_3,
		dft_adjuster_id AS DFT_ADJUSTER_ID,
		dft_city_nm AS DFT_CITY_NM,
		dft_mail_to_st_cd AS DFT_MAIL_TO_ST_CD,
		dft_mail_to_ctr_cd AS DFT_MAIL_TO_CTR_CD,
		dft_mail_to_cty_nm AS DFT_MAIL_TO_CTY_NM,
		dft_claim_nbr AS DFT_CLAIM_NBR,
		dft_dbs_status_cd AS DFT_DBS_STATUS_CD,
		dft_dbs_dt AS DFT_DBS_DT,
		dft_invoice_nbr AS DFT_INVOICE_NBR,
		dft_service_frm_dt AS DFT_SERVICE_FRM_DT,
		dft_service_to_dt AS DFT_SERVICE_TO_DT,
		dft_dsb_loc_cd AS DFT_DSB_LOC_CD,
		dft_pye_phr_cmt_id AS DFT_PYE_PHR_CMT_ID,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		dft_pay_to_nm_cmt_id,
		dft_mail_to_nm_cmt_id,
		payment_system
	FROM CLAIM_DRAFT_STAGE
),
EXP_CLAIM_DRAFT_STAGE AS (
	SELECT
	CLAIM_DRAFT_ID,
	DFT_DRAFT_NBR,
	DFT_BANK_NM_ID,
	DFT_BANK_NBR,
	DFT_DRAFT_CTL_SEQ,
	DFT_MAIL_TO_NM_ID,
	DFT_MEMO_PHR_DES,
	DFT_MAIL_TO_ADR_1,
	DFT_MAIL_TO_ADR_2,
	DFT_PAYEE_NM_ID_1,
	DFT_PAYEE_NM_ID_2,
	DFT_PAYEE_NM_ID_3,
	DFT_TAX_ID_NBR,
	DFT_TRS_AMT,
	DFT_UPDATE_OPR_ID,
	DFT_PMSD_TS,
	DFT_UPD_TS,
	DFT_MAIL_TO_ZIP_CD,
	DFT_PAYEE_PHR_DES,
	DFT_CK_DRAFT_IND,
	DFT_PRODUCER_NM_ID,
	DFT_DFT_CK_TYP_CD,
	DFT_SCH_OF_NBR,
	DFT_SCH_SEQ_NBR,
	DFT_REPORT_TO_IRS,
	DFT_TAX_ID_TYPE_CD,
	DFT_ENTRY_OPR_ID,
	DFT_CREATE_TS,
	CK_DFT_APV_IND,
	DFT_AUT_BY_ID,
	DFT_MICRP_ECD_NBR,
	DFT_MMO_PHR_CMT_ID,
	DFT_CLT_SEQ_NBR_1,
	DFT_CLT_SEQ_NBR_2,
	DFT_CLT_SEQ_NBR_3,
	DFT_ADJUSTER_ID,
	DFT_CITY_NM,
	DFT_MAIL_TO_ST_CD,
	DFT_MAIL_TO_CTR_CD,
	DFT_MAIL_TO_CTY_NM,
	DFT_CLAIM_NBR,
	DFT_DBS_STATUS_CD,
	DFT_DBS_DT,
	DFT_INVOICE_NBR,
	DFT_SERVICE_FRM_DT,
	DFT_SERVICE_TO_DT,
	DFT_DSB_LOC_CD,
	DFT_PYE_PHR_CMT_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP,
	dft_pay_to_nm_cmt_id,
	dft_mail_to_nm_cmt_id,
	payment_system
	FROM SQ_CLAIM_DRAFT_STAGE1
),
ARCH_CLAIM_DRAFT_STAGE AS (
	INSERT INTO ARCH_CLAIM_DRAFT_STAGE
	(claim_draft_id, dft_draft_nbr, dft_bank_nm_id, dft_bank_nbr, dft_draft_ctl_seq, dft_mail_to_nm_id, dft_memo_phr_des, dft_mail_to_adr_1, dft_mail_to_adr_2, dft_payee_nm_id_1, dft_payee_nm_id_2, dft_payee_nm_id_3, dft_tax_id_nbr, dft_trs_amt, dft_update_opr_id, dft_pmsd_ts, dft_upd_ts, dft_mail_to_zip_cd, dft_payee_phr_des, dft_ck_draft_ind, dft_producer_nm_id, dft_dft_ck_typ_cd, dft_sch_of_nbr, dft_sch_seq_nbr, dft_report_to_irs, dft_tax_id_type_cd, dft_entry_opr_id, dft_create_ts, ck_dft_apv_ind, dft_aut_by_id, dft_micrp_ecd_nbr, dft_mmo_phr_cmt_id, dft_clt_seq_nbr_1, dft_clt_seq_nbr_2, dft_clt_seq_nbr_3, dft_adjuster_id, dft_city_nm, dft_mail_to_st_cd, dft_mail_to_ctr_cd, dft_mail_to_cty_nm, dft_claim_nbr, dft_dbs_status_cd, dft_dbs_dt, dft_invoice_nbr, dft_service_frm_dt, dft_service_to_dt, dft_dsb_loc_cd, dft_pye_phr_cmt_id, extract_date, as_of_date, record_count, source_system_id, audit_id, dft_pay_to_nm_cmt_id, dft_mail_to_nm_cmt_id, payment_system)
	SELECT 
	CLAIM_DRAFT_ID AS CLAIM_DRAFT_ID, 
	DFT_DRAFT_NBR AS DFT_DRAFT_NBR, 
	DFT_BANK_NM_ID AS DFT_BANK_NM_ID, 
	DFT_BANK_NBR AS DFT_BANK_NBR, 
	DFT_DRAFT_CTL_SEQ AS DFT_DRAFT_CTL_SEQ, 
	DFT_MAIL_TO_NM_ID AS DFT_MAIL_TO_NM_ID, 
	DFT_MEMO_PHR_DES AS DFT_MEMO_PHR_DES, 
	DFT_MAIL_TO_ADR_1 AS DFT_MAIL_TO_ADR_1, 
	DFT_MAIL_TO_ADR_2 AS DFT_MAIL_TO_ADR_2, 
	DFT_PAYEE_NM_ID_1 AS DFT_PAYEE_NM_ID_1, 
	DFT_PAYEE_NM_ID_2 AS DFT_PAYEE_NM_ID_2, 
	DFT_PAYEE_NM_ID_3 AS DFT_PAYEE_NM_ID_3, 
	DFT_TAX_ID_NBR AS DFT_TAX_ID_NBR, 
	DFT_TRS_AMT AS DFT_TRS_AMT, 
	DFT_UPDATE_OPR_ID AS DFT_UPDATE_OPR_ID, 
	DFT_PMSD_TS AS DFT_PMSD_TS, 
	DFT_UPD_TS AS DFT_UPD_TS, 
	DFT_MAIL_TO_ZIP_CD AS DFT_MAIL_TO_ZIP_CD, 
	DFT_PAYEE_PHR_DES AS DFT_PAYEE_PHR_DES, 
	DFT_CK_DRAFT_IND AS DFT_CK_DRAFT_IND, 
	DFT_PRODUCER_NM_ID AS DFT_PRODUCER_NM_ID, 
	DFT_DFT_CK_TYP_CD AS DFT_DFT_CK_TYP_CD, 
	DFT_SCH_OF_NBR AS DFT_SCH_OF_NBR, 
	DFT_SCH_SEQ_NBR AS DFT_SCH_SEQ_NBR, 
	DFT_REPORT_TO_IRS AS DFT_REPORT_TO_IRS, 
	DFT_TAX_ID_TYPE_CD AS DFT_TAX_ID_TYPE_CD, 
	DFT_ENTRY_OPR_ID AS DFT_ENTRY_OPR_ID, 
	DFT_CREATE_TS AS DFT_CREATE_TS, 
	CK_DFT_APV_IND AS CK_DFT_APV_IND, 
	DFT_AUT_BY_ID AS DFT_AUT_BY_ID, 
	DFT_MICRP_ECD_NBR AS DFT_MICRP_ECD_NBR, 
	DFT_MMO_PHR_CMT_ID AS DFT_MMO_PHR_CMT_ID, 
	DFT_CLT_SEQ_NBR_1 AS DFT_CLT_SEQ_NBR_1, 
	DFT_CLT_SEQ_NBR_2 AS DFT_CLT_SEQ_NBR_2, 
	DFT_CLT_SEQ_NBR_3 AS DFT_CLT_SEQ_NBR_3, 
	DFT_ADJUSTER_ID AS DFT_ADJUSTER_ID, 
	DFT_CITY_NM AS DFT_CITY_NM, 
	DFT_MAIL_TO_ST_CD AS DFT_MAIL_TO_ST_CD, 
	DFT_MAIL_TO_CTR_CD AS DFT_MAIL_TO_CTR_CD, 
	DFT_MAIL_TO_CTY_NM AS DFT_MAIL_TO_CTY_NM, 
	DFT_CLAIM_NBR AS DFT_CLAIM_NBR, 
	DFT_DBS_STATUS_CD AS DFT_DBS_STATUS_CD, 
	DFT_DBS_DT AS DFT_DBS_DT, 
	DFT_INVOICE_NBR AS DFT_INVOICE_NBR, 
	DFT_SERVICE_FRM_DT AS DFT_SERVICE_FRM_DT, 
	DFT_SERVICE_TO_DT AS DFT_SERVICE_TO_DT, 
	DFT_DSB_LOC_CD AS DFT_DSB_LOC_CD, 
	DFT_PYE_PHR_CMT_ID AS DFT_PYE_PHR_CMT_ID, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	DFT_PAY_TO_NM_CMT_ID, 
	DFT_MAIL_TO_NM_CMT_ID, 
	PAYMENT_SYSTEM
	FROM EXP_CLAIM_DRAFT_STAGE
),