WITH
SQ_GTAM_tc26_stage AS (
	SELECT
		tc26_stage_id AS TC26_stage_ID,
		table_fld AS TABLE_FLD,
		key_len AS KEY_LEN,
		location AS LOCATION,
		master_company_number AS MASTER_COMPANY_NUMBER,
		line_of_business AS LINE_OF_BUSINESS,
		loss_disability_code AS LOSS_DISABILITY_CODE,
		data_len AS DATA_LEN,
		loss_disability_code_element AS LOSS_DISABILITY_CODE_ELEMENT,
		loss_disability_literal AS LOSS_DISABILITY_LITERAL,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID
	FROM GTAM_tc26_stage
),
EXP_arch_GTAM_tc26_stage AS (
	SELECT
	TC26_stage_ID,
	TABLE_FLD,
	KEY_LEN,
	LOCATION,
	MASTER_COMPANY_NUMBER,
	LINE_OF_BUSINESS,
	LOSS_DISABILITY_CODE,
	DATA_LEN,
	LOSS_DISABILITY_CODE_ELEMENT,
	LOSS_DISABILITY_LITERAL,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_GTAM_tc26_stage
),
arch_GTAM_tc26_stage AS (
	INSERT INTO arch_GTAM_tc26_stage
	(TC26_stage_ID, TABLE_FLD, KEY_LEN, LOCATION, MASTER_COMPANY_NUMBER, LINE_OF_BUSINESS, LOSS_DISABILITY_CODE, DATA_LEN, LOSS_DISABILITY_CODE_ELEMENT, LOSS_DISABILITY_LITERAL, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, audit_id)
	SELECT 
	TC26_STAGE_ID, 
	TABLE_FLD, 
	KEY_LEN, 
	LOCATION, 
	MASTER_COMPANY_NUMBER, 
	LINE_OF_BUSINESS, 
	LOSS_DISABILITY_CODE, 
	DATA_LEN, 
	LOSS_DISABILITY_CODE_ELEMENT, 
	LOSS_DISABILITY_LITERAL, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_arch_GTAM_tc26_stage
),