WITH
SQ_medical_bill AS (
	SELECT medical_bill.med_bill_id, medical_bill.med_bill_ak_id, medical_bill.med_bill_key, medical_bill.vendor_bill_num, medical_bill.patient_acct_num, medical_bill.patient_full_name, medical_bill.patient_last_name, medical_bill.patient_first_name, medical_bill.patient_mid_name, medical_bill.patient_addr, medical_bill.patient_city, medical_bill.patient_state, medical_bill.patient_zip_code, medical_bill.patient_birthdate, medical_bill.patient_gndr, medical_bill.patient_ssn, medical_bill.patient_inj_date, medical_bill.refer_physician, medical_bill.inpatient_outpatient_ind, medical_bill.bill_issued_date, medical_bill.bill_rcvd_date, medical_bill.bus_rcvd_date, medical_bill.bill_process_date, medical_bill.patient_admit_date, medical_bill.patient_discharge_date, medical_bill.bill_cover_from_date, medical_bill.bill_cover_to_date, medical_bill.daily_hospital_rate, medical_bill.bill_review_cost, medical_bill.total_bill_charge, medical_bill.total_bill_review_red, medical_bill.total_network_red, medical_bill.total_recommend_pay, medical_bill.total_addtional_charge, medical_bill.bill_type, medical_bill.bill_status_code, medical_bill.fee_sched_code, medical_bill.network_name, medical_bill.network_num, medical_bill.serv_line_num, medical_bill.deleted_ind, medical_bill.emplyr, medical_bill.acct_id, medical_bill.bill_review_vendor_code, medical_bill.med_bill_vendor_ak_id
	, medical_bill.med_bill_review_code 
	, medical_bill.autopay_ind
	,medical_bill.eor_rcvd_date
	, medical_bill.OriginalVendorBillNumber
	, medical_bill.AutoAdjudicatedIndicator
	FROM	@{pipeline().parameters.SOURCE_TABLE_OWNER}.medical_bill
	WHERE	created_date >= '@{pipeline().parameters.SELECTION_START_TS}'
	AND		crrnt_snpsht_flag = 1
),
EXP_PASS_THROUGH AS (
	SELECT
	med_bill_id,
	med_bill_ak_id,
	med_bill_key,
	med_bill_vendor_ak_id,
	vendor_bill_num,
	patient_acct_num,
	patient_full_name,
	patient_last_name,
	patient_first_name,
	patient_mid_name,
	patient_addr,
	patient_city,
	patient_state,
	patient_zip_code,
	patient_birthdate,
	patient_gndr,
	patient_ssn,
	patient_inj_date,
	refer_physician,
	inpatient_outpatient_ind,
	bill_issued_date,
	bill_rcvd_date,
	bus_rcvd_date,
	bill_process_date,
	patient_admit_date,
	patient_discharge_date,
	bill_cover_from_date,
	bill_cover_to_date,
	daily_hospital_rate,
	bill_review_cost,
	total_bill_charge,
	total_bill_review_red,
	total_network_red,
	total_recommend_pay,
	total_addtional_charge,
	bill_type,
	bill_status_code,
	fee_sched_code,
	network_name,
	network_num,
	serv_line_num,
	deleted_ind,
	emplyr,
	acct_id,
	bill_review_vendor_code,
	med_bill_review_code AS in_med_bill_review_code,
	-- *INF*: iif(isnull(in_med_bill_review_code),'N/A',in_med_bill_review_code)
	IFF(in_med_bill_review_code IS NULL,
		'N/A',
		in_med_bill_review_code
	) AS med_bill_review_code,
	autopay_ind AS in_autopay_ind,
	-- *INF*: iif(isnull(in_autopay_ind),'N/A',in_autopay_ind)
	IFF(in_autopay_ind IS NULL,
		'N/A',
		in_autopay_ind
	) AS autopay_ind,
	eor_rcvd_date,
	OriginalVendorBillNumber,
	AutoAdjudicatedIndicator
	FROM SQ_medical_bill
),
LKP_Provider_Group AS (
	SELECT
	med_provider_id,
	med_provider_ak_id,
	in_med_bill_ak_id,
	med_bill_ak_id,
	provider_type_code,
	bus_name,
	full_name,
	last_name,
	first_name,
	mid_name,
	prfx,
	sfx,
	title,
	specialty_code,
	addr,
	city,
	state,
	zip,
	tax_id
	FROM (
		SELECT 
		medical_provider.med_provider_id as med_provider_id, 
		medical_provider.med_provider_ak_id as med_provider_ak_id, 
		medical_provider.provider_type_code as provider_type_code, 
		medical_provider.bus_name as bus_name, 
		medical_provider.full_name as full_name, 
		medical_provider.last_name as last_name, 
		medical_provider.first_name as first_name, 
		medical_provider.mid_name as mid_name, 
		medical_provider.prfx as prfx, 
		medical_provider.sfx as sfx, 
		medical_provider.title as title, 
		medical_provider.specialty_code as specialty_code, 
		medical_provider.addr as addr, 
		medical_provider.city as city, 
		medical_provider.state as state, 
		medical_provider.zip as zip, 
		medical_provider.tax_id as tax_id, 
		medical_provider.med_bill_ak_id as med_bill_ak_id 
		FROM 
		@{pipeline().parameters.SOURCE_TABLE_OWNER}.medical_provider medical_provider
		WHERE provider_type_code = 'GROUP' and crrnt_snpsht_flag = 1
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY med_bill_ak_id ORDER BY med_provider_id) = 1
),
LKP_Provider_Individual AS (
	SELECT
	med_provider_id,
	med_provider_ak_id,
	in_med_bill_ak_id,
	med_bill_ak_id,
	provider_type_code,
	bus_name,
	full_name,
	last_name,
	first_name,
	mid_name,
	prfx,
	sfx,
	title,
	specialty_code,
	addr,
	city,
	state,
	zip,
	tax_id
	FROM (
		SELECT 
		medical_provider.med_provider_id as med_provider_id, 
		medical_provider.med_provider_ak_id as med_provider_ak_id, 
		medical_provider.provider_type_code as provider_type_code, 
		medical_provider.bus_name as bus_name, 
		medical_provider.full_name as full_name, 
		medical_provider.last_name as last_name, 
		medical_provider.first_name as first_name, 
		medical_provider.mid_name as mid_name, 
		medical_provider.prfx as prfx, 
		medical_provider.sfx as sfx, 
		medical_provider.title as title, 
		medical_provider.specialty_code as specialty_code, 
		medical_provider.addr as addr, 
		medical_provider.city as city, 
		medical_provider.state as state, 
		medical_provider.zip as zip, 
		medical_provider.tax_id as tax_id, 
		medical_provider.med_bill_ak_id as med_bill_ak_id 
		FROM 
		@{pipeline().parameters.SOURCE_TABLE_OWNER}.medical_provider medical_provider
		WHERE provider_type_code = 'INDIV'
		and crrnt_snpsht_flag = 1
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY med_bill_ak_id ORDER BY med_provider_id) = 1
),
LKP_medical_bill_vendor AS (
	SELECT
	med_bill_vendor_ak_id,
	vendor_code,
	vendor_name,
	vendor_addr,
	vendor_city,
	vendor_state,
	vendor_zip,
	vendor_ph,
	vendor_fax
	FROM (
		SELECT 
			med_bill_vendor_ak_id,
			vendor_code,
			vendor_name,
			vendor_addr,
			vendor_city,
			vendor_state,
			vendor_zip,
			vendor_ph,
			vendor_fax
		FROM medical_bill_vendor
		WHERE crrnt_snpsht_flag = 1
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY med_bill_vendor_ak_id ORDER BY med_bill_vendor_ak_id) = 1
),
LKP_sup_claim_medical_bill_review_code AS (
	SELECT
	med_bill_review_code_descript,
	in_med_bill_review_code,
	med_bill_review_code
	FROM (
		SELECT	med_bill_review_code_descript	as med_bill_review_code_descript
		,		med_bill_review_code			as med_bill_review_code 
		FROM	sup_claim_medical_bill_review_code
		WHERE	crrnt_snpsht_flag = 1
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY med_bill_review_code ORDER BY med_bill_review_code_descript) = 1
),
EXPTRANS AS (
	SELECT
	EXP_PASS_THROUGH.med_bill_id,
	EXP_PASS_THROUGH.med_bill_ak_id,
	EXP_PASS_THROUGH.med_bill_key,
	EXP_PASS_THROUGH.vendor_bill_num,
	EXP_PASS_THROUGH.patient_acct_num,
	EXP_PASS_THROUGH.patient_full_name,
	EXP_PASS_THROUGH.patient_last_name,
	EXP_PASS_THROUGH.patient_first_name,
	EXP_PASS_THROUGH.patient_mid_name,
	EXP_PASS_THROUGH.patient_addr,
	EXP_PASS_THROUGH.patient_city,
	EXP_PASS_THROUGH.patient_state,
	EXP_PASS_THROUGH.patient_zip_code,
	EXP_PASS_THROUGH.patient_birthdate,
	EXP_PASS_THROUGH.patient_gndr,
	EXP_PASS_THROUGH.patient_ssn,
	EXP_PASS_THROUGH.patient_inj_date,
	EXP_PASS_THROUGH.refer_physician,
	EXP_PASS_THROUGH.inpatient_outpatient_ind,
	EXP_PASS_THROUGH.bill_issued_date,
	EXP_PASS_THROUGH.bill_rcvd_date,
	EXP_PASS_THROUGH.bus_rcvd_date,
	EXP_PASS_THROUGH.bill_process_date,
	EXP_PASS_THROUGH.patient_admit_date,
	EXP_PASS_THROUGH.patient_discharge_date,
	EXP_PASS_THROUGH.bill_cover_from_date,
	EXP_PASS_THROUGH.bill_cover_to_date,
	EXP_PASS_THROUGH.daily_hospital_rate,
	EXP_PASS_THROUGH.bill_review_cost,
	EXP_PASS_THROUGH.total_bill_charge,
	EXP_PASS_THROUGH.total_bill_review_red,
	EXP_PASS_THROUGH.total_network_red,
	EXP_PASS_THROUGH.total_recommend_pay,
	EXP_PASS_THROUGH.total_addtional_charge,
	EXP_PASS_THROUGH.bill_type,
	EXP_PASS_THROUGH.bill_status_code,
	EXP_PASS_THROUGH.fee_sched_code,
	EXP_PASS_THROUGH.network_name,
	EXP_PASS_THROUGH.network_num,
	EXP_PASS_THROUGH.serv_line_num,
	EXP_PASS_THROUGH.deleted_ind,
	EXP_PASS_THROUGH.emplyr,
	EXP_PASS_THROUGH.acct_id,
	EXP_PASS_THROUGH.bill_review_vendor_code,
	LKP_Provider_Group.bus_name AS group_bus_name,
	LKP_Provider_Group.full_name AS group_full_name,
	LKP_Provider_Group.last_name AS group_last_name,
	LKP_Provider_Group.first_name AS group_first_name,
	LKP_Provider_Group.mid_name AS group_mid_name,
	LKP_Provider_Group.prfx AS group_prfx,
	LKP_Provider_Group.sfx AS group_sfx,
	LKP_Provider_Group.title AS group_title,
	LKP_Provider_Group.specialty_code AS group_specialty_code,
	LKP_Provider_Group.addr AS group_addr,
	LKP_Provider_Group.city AS group_city,
	LKP_Provider_Group.state AS group_state,
	LKP_Provider_Group.zip AS group_zip,
	LKP_Provider_Group.tax_id AS group_tax_id,
	LKP_Provider_Individual.full_name AS individual_full_name,
	LKP_Provider_Individual.last_name AS individual_last_name,
	LKP_Provider_Individual.first_name AS individual_first_name,
	LKP_Provider_Individual.mid_name AS individual_mid_name,
	LKP_Provider_Individual.prfx AS individual_prfx,
	LKP_Provider_Individual.sfx AS individual_sfx,
	LKP_Provider_Individual.title AS individual_title,
	LKP_Provider_Individual.specialty_code AS individual_specialty_code,
	LKP_Provider_Individual.addr AS individual_addr,
	LKP_Provider_Individual.city AS individual_city,
	LKP_Provider_Individual.state AS individual_state,
	LKP_Provider_Individual.zip AS individual_zip,
	LKP_Provider_Individual.tax_id AS individual_tax_id,
	1 AS crrnt_snpsht_flag,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS audit_id,
	-- *INF*: TO_DATE('01/01/1800 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
	TO_DATE('01/01/1800 00:00:00', 'MM/DD/YYYY HH24:MI:SS'
	) AS eff_from_date,
	-- *INF*: TO_DATE('12/31/2100 23:59:59', 'MM/DD/YYYY HH24:MI:SS')
	TO_DATE('12/31/2100 23:59:59', 'MM/DD/YYYY HH24:MI:SS'
	) AS eff_to_date,
	sysdate AS created_date,
	sysdate AS modified_date,
	LKP_medical_bill_vendor.vendor_code,
	LKP_medical_bill_vendor.vendor_name,
	LKP_medical_bill_vendor.vendor_addr,
	LKP_medical_bill_vendor.vendor_city,
	LKP_medical_bill_vendor.vendor_state,
	LKP_medical_bill_vendor.vendor_zip,
	LKP_medical_bill_vendor.vendor_ph,
	LKP_medical_bill_vendor.vendor_fax,
	LKP_sup_claim_medical_bill_review_code.in_med_bill_review_code AS med_bill_review_code,
	LKP_sup_claim_medical_bill_review_code.med_bill_review_code_descript AS in_med_bill_review_code_descript,
	-- *INF*: iif(isnull(in_med_bill_review_code_descript),'Not Applicable',in_med_bill_review_code_descript)
	IFF(in_med_bill_review_code_descript IS NULL,
		'Not Applicable',
		in_med_bill_review_code_descript
	) AS med_bill_review_code_descript,
	EXP_PASS_THROUGH.autopay_ind,
	EXP_PASS_THROUGH.eor_rcvd_date,
	EXP_PASS_THROUGH.OriginalVendorBillNumber,
	EXP_PASS_THROUGH.AutoAdjudicatedIndicator
	FROM EXP_PASS_THROUGH
	LEFT JOIN LKP_Provider_Group
	ON LKP_Provider_Group.med_bill_ak_id = EXP_PASS_THROUGH.med_bill_ak_id
	LEFT JOIN LKP_Provider_Individual
	ON LKP_Provider_Individual.med_bill_ak_id = EXP_PASS_THROUGH.med_bill_ak_id
	LEFT JOIN LKP_medical_bill_vendor
	ON LKP_medical_bill_vendor.med_bill_vendor_ak_id = EXP_PASS_THROUGH.med_bill_vendor_ak_id
	LEFT JOIN LKP_sup_claim_medical_bill_review_code
	ON LKP_sup_claim_medical_bill_review_code.med_bill_review_code = EXP_PASS_THROUGH.med_bill_review_code
),
LKP_MED_BILL_DIM_Exists AS (
	SELECT
	med_bill_dim_id,
	edw_med_bill_ak_id,
	edw_med_bill_ak_id1
	FROM (
		SELECT 
			med_bill_dim_id,
			edw_med_bill_ak_id,
			edw_med_bill_ak_id1
		FROM medical_bill_dim
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY edw_med_bill_ak_id ORDER BY med_bill_dim_id) = 1
),
RTRTRANS AS (
	SELECT
	EXPTRANS.med_bill_id,
	EXPTRANS.med_bill_ak_id,
	EXPTRANS.med_bill_key,
	EXPTRANS.vendor_bill_num,
	EXPTRANS.patient_acct_num,
	EXPTRANS.patient_full_name,
	EXPTRANS.patient_last_name,
	EXPTRANS.patient_first_name,
	EXPTRANS.patient_mid_name,
	EXPTRANS.patient_addr,
	EXPTRANS.patient_city,
	EXPTRANS.patient_state,
	EXPTRANS.patient_zip_code,
	EXPTRANS.patient_birthdate,
	EXPTRANS.patient_gndr,
	EXPTRANS.patient_ssn,
	EXPTRANS.patient_inj_date,
	EXPTRANS.refer_physician,
	EXPTRANS.inpatient_outpatient_ind,
	EXPTRANS.bill_issued_date,
	EXPTRANS.bill_rcvd_date,
	EXPTRANS.bus_rcvd_date,
	EXPTRANS.bill_process_date,
	EXPTRANS.patient_admit_date,
	EXPTRANS.patient_discharge_date,
	EXPTRANS.bill_cover_from_date,
	EXPTRANS.bill_cover_to_date,
	EXPTRANS.daily_hospital_rate,
	EXPTRANS.bill_review_cost,
	EXPTRANS.total_bill_charge,
	EXPTRANS.total_bill_review_red,
	EXPTRANS.total_network_red,
	EXPTRANS.total_recommend_pay,
	EXPTRANS.total_addtional_charge,
	EXPTRANS.bill_type,
	EXPTRANS.bill_status_code,
	EXPTRANS.fee_sched_code,
	EXPTRANS.network_name,
	EXPTRANS.network_num,
	EXPTRANS.serv_line_num,
	EXPTRANS.deleted_ind,
	EXPTRANS.emplyr,
	EXPTRANS.acct_id,
	EXPTRANS.bill_review_vendor_code,
	EXPTRANS.group_bus_name,
	EXPTRANS.group_full_name,
	EXPTRANS.group_last_name,
	EXPTRANS.group_first_name,
	EXPTRANS.group_mid_name,
	EXPTRANS.group_prfx,
	EXPTRANS.group_sfx,
	EXPTRANS.group_title,
	EXPTRANS.group_specialty_code,
	EXPTRANS.group_addr,
	EXPTRANS.group_city,
	EXPTRANS.group_state,
	EXPTRANS.group_zip,
	EXPTRANS.group_tax_id,
	EXPTRANS.individual_full_name,
	EXPTRANS.individual_last_name,
	EXPTRANS.individual_first_name,
	EXPTRANS.individual_mid_name,
	EXPTRANS.individual_prfx,
	EXPTRANS.individual_sfx,
	EXPTRANS.individual_title,
	EXPTRANS.individual_specialty_code,
	EXPTRANS.individual_addr,
	EXPTRANS.individual_city,
	EXPTRANS.individual_state,
	EXPTRANS.individual_zip,
	EXPTRANS.individual_tax_id,
	EXPTRANS.crrnt_snpsht_flag,
	EXPTRANS.audit_id,
	EXPTRANS.eff_from_date,
	EXPTRANS.eff_to_date,
	EXPTRANS.created_date,
	EXPTRANS.modified_date,
	LKP_MED_BILL_DIM_Exists.med_bill_dim_id,
	EXPTRANS.vendor_code,
	EXPTRANS.vendor_name,
	EXPTRANS.vendor_addr,
	EXPTRANS.vendor_city,
	EXPTRANS.vendor_state,
	EXPTRANS.vendor_zip,
	EXPTRANS.vendor_ph,
	EXPTRANS.vendor_fax,
	EXPTRANS.med_bill_review_code,
	EXPTRANS.med_bill_review_code_descript,
	EXPTRANS.autopay_ind,
	EXPTRANS.eor_rcvd_date AS eor_rcv_date,
	EXPTRANS.OriginalVendorBillNumber,
	EXPTRANS.AutoAdjudicatedIndicator
	FROM EXPTRANS
	LEFT JOIN LKP_MED_BILL_DIM_Exists
	ON LKP_MED_BILL_DIM_Exists.edw_med_bill_ak_id = EXPTRANS.med_bill_ak_id
),
RTRTRANS_update AS (SELECT * FROM RTRTRANS WHERE not isnull(med_bill_dim_id)),
RTRTRANS_DEFAULT1 AS (SELECT * FROM RTRTRANS WHERE NOT ( (not isnull(med_bill_dim_id)) )),
medical_bill_dim_insert AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.medical_bill_dim
	(edw_med_bill_pk_id, edw_med_bill_ak_id, med_bill_key, vendor_bill_num, patient_acct_num, patient_full_name, patient_last_name, patient_first_name, patient_mid_name, patient_addr, patient_city, patient_state, patient_zip_code, patient_birthdate, patient_gndr, patient_ssn, patient_inj_date, refer_physician, inpatient_outpatient_ind, bill_issued_date, bill_rcvd_date, bus_rcvd_date, bill_process_date, patient_admit_date, patient_discharge_date, bill_cover_from_date, bill_cover_to_date, daily_hospital_rate, bill_review_cost, total_bill_review_red, total_addtional_charge, bill_type, bill_status_code, fee_sched_code, network_name, network_num, serv_line_num, deleted_ind, emplyr, acct_id, bill_review_vendor_code, bus_name, group_provider_full_name, group_provider_last_name, group_provider_first_name, group_provider_mid_name, group_provider_prfx, group_provider_sfx, group_provider_title, group_provider_specialty_code, group_provider_addr, group_provider_city, group_provider_state, group_provider_zip, group_provider_tax_id, individual_provider_full_name, individual_provider_last_name, individual_provider_first_name, individual_provider_mid_name, individual_provider_prfx, individual_provider_sfx, individual_provider_title, individual_provider_specialty_code, individual_provider_addr, individual_provider_city, individual_provider_state, individual_provider_zip, individual_provider_tax_id, crrnt_snpsht_flag, audit_id, eff_from_date, eff_to_date, created_date, modified_date, bill_review_vendor_name, bill_review_vendor_addr, bill_review_vendor_city, bill_review_vendor_state, bill_review_vendor_zip, bill_review_vendor_ph, bill_review_vendor_fax, med_bill_review_code, med_bill_review_code_descript, autopay_ind, eor_rcvd_date, OriginalVendorBillNumber, AutoAdjudicatedIndicator)
	SELECT 
	med_bill_id AS EDW_MED_BILL_PK_ID, 
	med_bill_ak_id AS EDW_MED_BILL_AK_ID, 
	MED_BILL_KEY, 
	VENDOR_BILL_NUM, 
	PATIENT_ACCT_NUM, 
	PATIENT_FULL_NAME, 
	PATIENT_LAST_NAME, 
	PATIENT_FIRST_NAME, 
	PATIENT_MID_NAME, 
	PATIENT_ADDR, 
	PATIENT_CITY, 
	PATIENT_STATE, 
	PATIENT_ZIP_CODE, 
	PATIENT_BIRTHDATE, 
	PATIENT_GNDR, 
	PATIENT_SSN, 
	PATIENT_INJ_DATE, 
	REFER_PHYSICIAN, 
	INPATIENT_OUTPATIENT_IND, 
	BILL_ISSUED_DATE, 
	BILL_RCVD_DATE, 
	BUS_RCVD_DATE, 
	BILL_PROCESS_DATE, 
	PATIENT_ADMIT_DATE, 
	PATIENT_DISCHARGE_DATE, 
	BILL_COVER_FROM_DATE, 
	BILL_COVER_TO_DATE, 
	DAILY_HOSPITAL_RATE, 
	BILL_REVIEW_COST, 
	TOTAL_BILL_REVIEW_RED, 
	TOTAL_ADDTIONAL_CHARGE, 
	BILL_TYPE, 
	BILL_STATUS_CODE, 
	FEE_SCHED_CODE, 
	NETWORK_NAME, 
	NETWORK_NUM, 
	SERV_LINE_NUM, 
	DELETED_IND, 
	EMPLYR, 
	ACCT_ID, 
	BILL_REVIEW_VENDOR_CODE, 
	group_bus_name AS BUS_NAME, 
	group_full_name AS GROUP_PROVIDER_FULL_NAME, 
	group_last_name AS GROUP_PROVIDER_LAST_NAME, 
	group_first_name AS GROUP_PROVIDER_FIRST_NAME, 
	group_mid_name AS GROUP_PROVIDER_MID_NAME, 
	group_prfx AS GROUP_PROVIDER_PRFX, 
	group_sfx AS GROUP_PROVIDER_SFX, 
	group_title AS GROUP_PROVIDER_TITLE, 
	group_specialty_code AS GROUP_PROVIDER_SPECIALTY_CODE, 
	group_addr AS GROUP_PROVIDER_ADDR, 
	group_city AS GROUP_PROVIDER_CITY, 
	group_state AS GROUP_PROVIDER_STATE, 
	group_zip AS GROUP_PROVIDER_ZIP, 
	group_tax_id AS GROUP_PROVIDER_TAX_ID, 
	individual_full_name AS INDIVIDUAL_PROVIDER_FULL_NAME, 
	individual_last_name AS INDIVIDUAL_PROVIDER_LAST_NAME, 
	individual_first_name AS INDIVIDUAL_PROVIDER_FIRST_NAME, 
	individual_mid_name AS INDIVIDUAL_PROVIDER_MID_NAME, 
	individual_prfx AS INDIVIDUAL_PROVIDER_PRFX, 
	individual_sfx AS INDIVIDUAL_PROVIDER_SFX, 
	individual_title AS INDIVIDUAL_PROVIDER_TITLE, 
	individual_specialty_code AS INDIVIDUAL_PROVIDER_SPECIALTY_CODE, 
	individual_addr AS INDIVIDUAL_PROVIDER_ADDR, 
	individual_city AS INDIVIDUAL_PROVIDER_CITY, 
	individual_state AS INDIVIDUAL_PROVIDER_STATE, 
	individual_zip AS INDIVIDUAL_PROVIDER_ZIP, 
	individual_tax_id AS INDIVIDUAL_PROVIDER_TAX_ID, 
	CRRNT_SNPSHT_FLAG, 
	AUDIT_ID, 
	EFF_FROM_DATE, 
	EFF_TO_DATE, 
	CREATED_DATE, 
	MODIFIED_DATE, 
	vendor_name AS BILL_REVIEW_VENDOR_NAME, 
	vendor_addr AS BILL_REVIEW_VENDOR_ADDR, 
	vendor_city AS BILL_REVIEW_VENDOR_CITY, 
	vendor_state AS BILL_REVIEW_VENDOR_STATE, 
	vendor_zip AS BILL_REVIEW_VENDOR_ZIP, 
	vendor_ph AS BILL_REVIEW_VENDOR_PH, 
	vendor_fax AS BILL_REVIEW_VENDOR_FAX, 
	MED_BILL_REVIEW_CODE, 
	MED_BILL_REVIEW_CODE_DESCRIPT, 
	AUTOPAY_IND, 
	eor_rcv_date AS EOR_RCVD_DATE, 
	ORIGINALVENDORBILLNUMBER, 
	AUTOADJUDICATEDINDICATOR
	FROM RTRTRANS_DEFAULT1
),
UPD_Medical_Bill_Dim_U AS (
	SELECT
	med_bill_id, 
	med_bill_ak_id, 
	med_bill_key, 
	vendor_bill_num, 
	patient_acct_num, 
	patient_full_name, 
	patient_last_name, 
	patient_first_name, 
	patient_mid_name, 
	patient_addr, 
	patient_city, 
	patient_state, 
	patient_zip_code, 
	patient_birthdate, 
	patient_gndr, 
	patient_ssn, 
	patient_inj_date, 
	refer_physician, 
	inpatient_outpatient_ind, 
	bill_issued_date, 
	bill_rcvd_date, 
	bus_rcvd_date, 
	bill_process_date, 
	patient_admit_date, 
	patient_discharge_date, 
	bill_cover_from_date, 
	bill_cover_to_date, 
	daily_hospital_rate, 
	bill_review_cost, 
	total_bill_charge, 
	total_bill_review_red, 
	total_network_red, 
	total_recommend_pay, 
	total_addtional_charge, 
	bill_type, 
	bill_status_code, 
	fee_sched_code, 
	network_name, 
	network_num, 
	serv_line_num, 
	deleted_ind, 
	emplyr, 
	acct_id, 
	bill_review_vendor_code, 
	group_bus_name, 
	group_full_name, 
	group_last_name, 
	group_first_name, 
	group_mid_name, 
	group_prfx, 
	group_sfx, 
	group_title, 
	group_specialty_code, 
	group_addr, 
	group_city, 
	group_state, 
	group_zip, 
	group_tax_id, 
	individual_full_name, 
	individual_last_name, 
	individual_first_name, 
	individual_mid_name, 
	individual_prfx, 
	individual_sfx, 
	individual_title, 
	individual_specialty_code, 
	individual_addr, 
	individual_city, 
	individual_state, 
	individual_zip, 
	individual_tax_id, 
	crrnt_snpsht_flag, 
	audit_id, 
	modified_date, 
	med_bill_dim_id AS med_bill_dim_id1, 
	vendor_code, 
	vendor_name, 
	vendor_addr, 
	vendor_city, 
	vendor_state, 
	vendor_zip, 
	vendor_ph, 
	vendor_fax, 
	med_bill_review_code, 
	med_bill_review_code_descript, 
	autopay_ind, 
	eor_rcv_date AS eor_rcv_date1, 
	OriginalVendorBillNumber AS OriginalVendorBillNumber1, 
	AutoAdjudicatedIndicator AS AutoAdjudicatedIndicator1
	FROM RTRTRANS_update
),
medical_bill_dim_update AS (
	MERGE INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.medical_bill_dim AS T
	USING UPD_Medical_Bill_Dim_U AS S
	ON T.med_bill_dim_id = S.med_bill_dim_id1
	WHEN MATCHED BY TARGET THEN
	UPDATE SET T.edw_med_bill_pk_id = S.med_bill_id, T.edw_med_bill_ak_id = S.med_bill_ak_id, T.med_bill_key = S.med_bill_key, T.vendor_bill_num = S.vendor_bill_num, T.patient_acct_num = S.patient_acct_num, T.patient_full_name = S.patient_full_name, T.patient_last_name = S.patient_last_name, T.patient_first_name = S.patient_first_name, T.patient_mid_name = S.patient_mid_name, T.patient_addr = S.patient_addr, T.patient_city = S.patient_city, T.patient_state = S.patient_state, T.patient_zip_code = S.patient_zip_code, T.patient_birthdate = S.patient_birthdate, T.patient_gndr = S.patient_gndr, T.patient_ssn = S.patient_ssn, T.patient_inj_date = S.patient_inj_date, T.refer_physician = S.refer_physician, T.inpatient_outpatient_ind = S.inpatient_outpatient_ind, T.bill_issued_date = S.bill_issued_date, T.bill_rcvd_date = S.bill_rcvd_date, T.bus_rcvd_date = S.bus_rcvd_date, T.bill_process_date = S.bill_process_date, T.patient_admit_date = S.patient_admit_date, T.patient_discharge_date = S.patient_discharge_date, T.bill_cover_from_date = S.bill_cover_from_date, T.bill_cover_to_date = S.bill_cover_to_date, T.daily_hospital_rate = S.daily_hospital_rate, T.bill_review_cost = S.bill_review_cost, T.total_bill_review_red = S.total_bill_review_red, T.total_addtional_charge = S.total_addtional_charge, T.bill_type = S.bill_type, T.bill_status_code = S.bill_status_code, T.fee_sched_code = S.fee_sched_code, T.network_name = S.network_name, T.network_num = S.network_num, T.serv_line_num = S.serv_line_num, T.deleted_ind = S.deleted_ind, T.emplyr = S.emplyr, T.acct_id = S.acct_id, T.bill_review_vendor_code = S.bill_review_vendor_code, T.bus_name = S.group_bus_name, T.group_provider_full_name = S.group_full_name, T.group_provider_last_name = S.group_last_name, T.group_provider_first_name = S.group_first_name, T.group_provider_mid_name = S.group_mid_name, T.group_provider_prfx = S.group_prfx, T.group_provider_sfx = S.group_sfx, T.group_provider_title = S.group_title, T.group_provider_specialty_code = S.group_specialty_code, T.group_provider_addr = S.group_addr, T.group_provider_city = S.group_city, T.group_provider_state = S.group_state, T.group_provider_zip = S.group_zip, T.group_provider_tax_id = S.group_tax_id, T.individual_provider_full_name = S.individual_full_name, T.individual_provider_last_name = S.individual_last_name, T.individual_provider_first_name = S.individual_first_name, T.individual_provider_mid_name = S.individual_mid_name, T.individual_provider_prfx = S.individual_prfx, T.individual_provider_sfx = S.individual_sfx, T.individual_provider_title = S.individual_title, T.individual_provider_specialty_code = S.individual_specialty_code, T.individual_provider_addr = S.individual_addr, T.individual_provider_city = S.individual_city, T.individual_provider_state = S.individual_state, T.individual_provider_zip = S.individual_zip, T.individual_provider_tax_id = S.individual_tax_id, T.crrnt_snpsht_flag = S.crrnt_snpsht_flag, T.audit_id = S.audit_id, T.modified_date = S.modified_date, T.bill_review_vendor_name = S.vendor_name, T.bill_review_vendor_addr = S.vendor_addr, T.bill_review_vendor_city = S.vendor_city, T.bill_review_vendor_state = S.vendor_state, T.bill_review_vendor_zip = S.vendor_zip, T.bill_review_vendor_ph = S.vendor_ph, T.bill_review_vendor_fax = S.vendor_fax, T.med_bill_review_code = S.med_bill_review_code, T.med_bill_review_code_descript = S.med_bill_review_code_descript, T.autopay_ind = S.autopay_ind, T.eor_rcvd_date = S.eor_rcv_date1, T.OriginalVendorBillNumber = S.OriginalVendorBillNumber1, T.AutoAdjudicatedIndicator = S.AutoAdjudicatedIndicator1
),