WITH
LKP_client_phone_stage AS (
	SELECT
	ciph_phn_nbr,
	client_id,
	phn_typ_cd
	FROM (
		SELECT 
			LTRIM(RTRIM(client_phone_stage.ciph_phn_nbr)) as ciph_phn_nbr, 
			LTRIM(RTRIM(client_phone_stage.client_id)) as client_id, 
			LTRIM(RTRIM(client_phone_stage.phn_typ_cd)) as phn_typ_cd 
		FROM 
			client_phone_stage
		WHERE
			CIPH_EXP_DT= '9999-12-31'
		ORDER BY 
			CIPH_PHN_SEQ_NBR, CIPH_EFF_ACY_TS --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY client_id,phn_typ_cd ORDER BY ciph_phn_nbr DESC) = 1
),
LKP_CLT_ADR_RELATION_STAGE AS (
	SELECT
	ADR_ID,
	CLIENT_ID,
	ADR_TYP_CD
	FROM (
		SELECT 
		a.ADR_ID as ADR_ID, 
		LTRIM(RTRIM(a.CLIENT_ID)) as CLIENT_ID, 
		LTRIM(RTRIM(a.ADR_TYP_CD)) as ADR_TYP_CD 
		FROM 
		@{pipeline().parameters.SOURCE_TABLE_OWNER}.CLT_ADR_RELATION_STAGE a
		WHERE
		a.CIAR_EXP_DT= '9999-12-31'
		ORDER BY a.ADR_SEQ_NBR --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY CLIENT_ID,ADR_TYP_CD ORDER BY ADR_ID DESC) = 1
),
LKP_CLIENT_TAX_STAGE AS (
	SELECT
	citx_tax_id,
	client_id,
	tax_type_cd
	FROM (
		SELECT 
		ltrim(rtrim(a.citx_tax_id)) as citx_tax_id, 	
		a.client_id as client_id, 
		rtrim(a.tax_type_cd) as tax_type_cd 
		FROM @{pipeline().parameters.SOURCE_TABLE_OWNER}.client_tax_stage a
		WHERE expiration_acy_ts = '9999-12-31'
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY client_id,tax_type_cd ORDER BY citx_tax_id) = 1
),
SQ_CLIENT_TAB_STAGE AS (
	SELECT 
	CLIENT_TAB_STAGE.CLIENT_ID, 
	CLIENT_TAB_STAGE.CICL_FST_NM,
	CLIENT_TAB_STAGE.CICL_LST_NM,
	CLIENT_TAB_STAGE.CICL_MDL_NM,
	CLIENT_TAB_STAGE.NM_PFX,
	CLIENT_TAB_STAGE.NM_SFX,
	CLIENT_TAB_STAGE.LEG_ENT_CD,
	CLIENT_TAB_STAGE.CICL_DOB_DT, 
	CLIENT_TAB_STAGE.GENDER_CD, 
	CLIENT_TAB_STAGE.CICL_EFF_ACY_TS,
	LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CLIENT_TAB_STAGE.CICL_LNG_NM,'$',''),'?',''),'.',''),',',''),'_',''),'/','')))
	FROM
	@{pipeline().parameters.SOURCE_TABLE_OWNER}.CLIENT_TAB_STAGE
	WHERE
	  CICL_EXP_DT = '9999-12-31'
	
	--SELECT 
	--CLIENT_TAB_STAGE.CLIENT_ID, 
	--CLIENT_TAB_STAGE.CICL_FST_NM,
	--CLIENT_TAB_STAGE.CICL_LST_NM,
	--CLIENT_TAB_STAGE.CICL_MDL_NM,
	--CLIENT_TAB_STAGE.NM_PFX,
	--CLIENT_TAB_STAGE.NM_SFX,
	--CLIENT_TAB_STAGE.LEG_ENT_CD,
	--CLIENT_TAB_STAGE.CICL_DOB_DT, 
	--CLIENT_TAB_STAGE.GENDER_CD, 
	--CLIENT_TAB_STAGE.CICL_EFF_ACY_TS,
	--LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(replace(CLIENT_TAB_STAGE.CICL_LNG_NM,'+',''),'-',''),'$',''),'?',''),'.',''),',',''),'_',''),',',''),'/','')))
	--FROM
	--@{pipeline().parameters.SOURCE_TABLE_OWNER}.CLIENT_TAB_STAGE
	--WHERE
	-- CICL_EXP_DT = '9999-12-31'
),
EXP_Values AS (
	SELECT
	CLIENT_ID,
	CICL_FST_NM,
	CICL_LST_NM,
	CICL_MDL_NM,
	NM_PFX,
	NM_SFX,
	CICL_LNG_NM,
	CICL_DOB_DT,
	GENDER_CD,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'INHM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHM.ADR_ID AS ADR_ID_INHM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'BSM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSM.ADR_ID AS ADR_ID_BSM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'ALM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALM.ADR_ID AS ADR_ID_ALM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'ALL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALL.ADR_ID AS ADR_ID_ALL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'BSL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSL.ADR_ID AS ADR_ID_BSL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'MAL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_MAL.ADR_ID AS ADR_ID_MAL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'CLM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLM.ADR_ID AS ADR_ID_CLM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'LOC')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LOC.ADR_ID AS ADR_ID_LOC,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'BLM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLM.ADR_ID AS ADR_ID_BLM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PPL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PPL.ADR_ID AS ADR_ID_PPL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'BLRT')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLRT.ADR_ID AS ADR_ID_BLRT,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'BSS')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSS.ADR_ID AS ADR_ID_BSS,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'GL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_GL.ADR_ID AS ADR_ID_GL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'CLL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLL.ADR_ID AS ADR_ID_CLL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'HHA')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_HHA.ADR_ID AS ADR_ID_HHA,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'INHA')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHA.ADR_ID AS ADR_ID_INHA,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'LPE')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPE.ADR_ID AS ADR_ID_LPE,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PMF')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PMF.ADR_ID AS ADR_ID_PMF,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'INHL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHL.ADR_ID AS ADR_ID_INHL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PLG')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLG.ADR_ID AS ADR_ID_PLG,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'TMPM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_TMPM.ADR_ID AS ADR_ID_TMPM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'INWL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWL.ADR_ID AS ADR_ID_INWL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'INWM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWM.ADR_ID AS ADR_ID_INWM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'LPA')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPA.ADR_ID AS ADR_ID_LPA,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PLB')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLB.ADR_ID AS ADR_ID_PLB,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PLL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLL.ADR_ID AS ADR_ID_PLL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PLM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLM.ADR_ID AS ADR_ID_PLM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'PRAD')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PRAD.ADR_ID AS ADR_ID_PRAD,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'SPL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_SPL.ADR_ID AS ADR_ID_SPL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'VCL')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCL.ADR_ID AS ADR_ID_VCL,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'VCM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCM.ADR_ID AS ADR_ID_VCM,
	-- *INF*: :LKP.LKP_CLT_ADR_RELATION_STAGE(CLIENT_ID, 'COM')
	LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_COM.ADR_ID AS ADR_ID_COM,
	LEG_ENT_CD,
	CICL_EFF_ACY_TS
	FROM SQ_CLIENT_TAB_STAGE
	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHM.ADR_TYP_CD = 'INHM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSM.ADR_TYP_CD = 'BSM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALM.ADR_TYP_CD = 'ALM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_ALL.ADR_TYP_CD = 'ALL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSL.ADR_TYP_CD = 'BSL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_MAL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_MAL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_MAL.ADR_TYP_CD = 'MAL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLM.ADR_TYP_CD = 'CLM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LOC
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LOC.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LOC.ADR_TYP_CD = 'LOC'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLM.ADR_TYP_CD = 'BLM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PPL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PPL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PPL.ADR_TYP_CD = 'PPL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLRT
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLRT.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BLRT.ADR_TYP_CD = 'BLRT'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSS
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSS.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_BSS.ADR_TYP_CD = 'BSS'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_GL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_GL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_GL.ADR_TYP_CD = 'GL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_CLL.ADR_TYP_CD = 'CLL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_HHA
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_HHA.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_HHA.ADR_TYP_CD = 'HHA'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHA
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHA.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHA.ADR_TYP_CD = 'INHA'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPE
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPE.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPE.ADR_TYP_CD = 'LPE'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PMF
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PMF.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PMF.ADR_TYP_CD = 'PMF'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INHL.ADR_TYP_CD = 'INHL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLG
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLG.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLG.ADR_TYP_CD = 'PLG'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_TMPM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_TMPM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_TMPM.ADR_TYP_CD = 'TMPM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWL.ADR_TYP_CD = 'INWL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_INWM.ADR_TYP_CD = 'INWM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPA
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPA.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_LPA.ADR_TYP_CD = 'LPA'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLB
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLB.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLB.ADR_TYP_CD = 'PLB'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLL.ADR_TYP_CD = 'PLL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PLM.ADR_TYP_CD = 'PLM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PRAD
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PRAD.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_PRAD.ADR_TYP_CD = 'PRAD'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_SPL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_SPL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_SPL.ADR_TYP_CD = 'SPL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCL
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCL.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCL.ADR_TYP_CD = 'VCL'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_VCM.ADR_TYP_CD = 'VCM'

	LEFT JOIN LKP_CLT_ADR_RELATION_STAGE LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_COM
	ON LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_COM.CLIENT_ID = CLIENT_ID
	AND LKP_CLT_ADR_RELATION_STAGE_CLIENT_ID_COM.ADR_TYP_CD = 'COM'

),
LKP_client_phone_stage_by_priority AS (
	SELECT
	ciph_phn_nbr,
	phn_typ_cd,
	ciph_phn_seq_nbr,
	client_id
	FROM (
		SELECT 
			LTRIM(RTRIM(client_phone_stage.ciph_phn_nbr)) as ciph_phn_nbr, 
			LTRIM(RTRIM(client_phone_stage.phn_typ_cd)) as phn_typ_cd,
			case phn_typ_cd
				when 'IH' then 1 -- HOME		
				when 'BS' then 2 -- Business
				when 'IW' then 3 -- WORK
				when 'ML' then 4 -- MOBILE		
				when 'CP' then 5 -- Contac
				when 'HH' then 6 -- HOUSEHOLD
				when 'FX' then 7 -- FAX
				when 'TF' then 8 -- TOLL FREE
				when 'MS' then 9 -- MESSAGES		
				when 'IV' then 10 -- VACATION
				when 'PG' then 11 -- PAGER
				when 'MO' then 12 -- MODEM
				when 'EM' then 13 -- Emergency
				when 'SS' then 14 -- SHIP-TO-SHORE
				when 'AL' then 15 -- not valid for exceed
				else 99
			end as ciph_phn_seq_nbr,
			LTRIM(RTRIM(client_phone_stage.client_id)) as client_id
		FROM 
			client_phone_stage
		WHERE
			CIPH_EXP_DT= '9999-12-31' 
		ORDER BY 
		ciph_phn_seq_nbr --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY client_id ORDER BY ciph_phn_nbr) = 1
),
EXP_phone AS (
	SELECT
	ciph_phn_nbr,
	phn_typ_cd,
	-- *INF*: IIF(isnull(ciph_phn_nbr),'N/A',rtrim(ltrim(ciph_phn_nbr)))
	-- 
	-- 
	IFF(ciph_phn_nbr IS NULL,
		'N/A',
		rtrim(ltrim(ciph_phn_nbr
			)
		)
	) AS v_Phone_Num,
	-- *INF*: IIF(isnull(phn_typ_cd),'N/A',phn_typ_cd)
	IFF(phn_typ_cd IS NULL,
		'N/A',
		phn_typ_cd
	) AS v_Phone_Type,
	-- *INF*: IIF(ISNULL(v_Phone_Num),'N/A',
	-- REPLACECHR(FALSE,REPLACECHR(FALSE,REPLACECHR(FALSE,v_Phone_Num,'-',''),')',''),'(','')
	-- )
	-- 
	-- 
	-- ---Replace ( ) and - in phone number with blanks so (320)259-0824EXT becomes 3202590824EXT
	-- 
	-- 
	IFF(v_Phone_Num IS NULL,
		'N/A',
		REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(v_Phone_Num,'-',''),')',''),'(','')
	) AS v_Phone,
	ciph_phn_seq_nbr,
	-- *INF*: IIF(v_Phone = 'N/A', 'N/A',SUBSTR(v_Phone,1,10))
	-- 
	-- --take value before EXT
	IFF(v_Phone = 'N/A',
		'N/A',
		SUBSTR(v_Phone, 1, 10
		)
	) AS Phone,
	-- *INF*: IIF(v_Phone = 'N/A', 'N/A',IIF(LENGTH(SUBSTR(v_Phone,12,7))=0,'N/A', SUBSTR(v_Phone,12,7)))
	-- 
	-- //Take value after X
	-- 
	-- 
	-- //Changed to code above do to DAP-399
	-- //IIF(v_Phone = 'N/A', 'N/A',IIF(LENGTH(SUBSTR(v_Phone,14,5))=0,'N/A', SUBSTR(v_Phone,14,5)))
	-- ----Take value after EXT
	IFF(v_Phone = 'N/A',
		'N/A',
		IFF(LENGTH(SUBSTR(v_Phone, 12, 7
				)
			) = 0,
			'N/A',
			SUBSTR(v_Phone, 12, 7
			)
		)
	) AS Phone_Extn,
	-- *INF*: IIF(ISNULL(v_Phone_Type),'N/A',v_Phone_Type)
	IFF(v_Phone_Type IS NULL,
		'N/A',
		v_Phone_Type
	) AS Phone_Type
	FROM LKP_client_phone_stage_by_priority
),
LKP_CLIENT_ADDRESS_STAGE_ALL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_ALM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_BLM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_BLRT AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_BSL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_BSM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_BSS AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_CLL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_CLM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_COM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_GL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_HHA AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_INHA AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_INHL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_INHM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_INWL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_INWM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_LOC AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_LPA AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_LPE AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_MAL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PLB AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PLG AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PLL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PLM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PMF AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PPL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_PRAD AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_SPL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_TMPM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_VCL AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_CLIENT_ADDRESS_STAGE_VCM AS (
	SELECT
	CICA_PST_CD,
	ST_CD,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	ADR_ID
	FROM (
		SELECT 
			CICA_PST_CD,
			ST_CD,
			CICA_ADR_1,
			CICA_ADR_2,
			CICA_CIT_NM,
			CICA_CTY,
			ADR_ID
		FROM CLIENT_ADDRESS_STAGE
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY ADR_ID ORDER BY CICA_PST_CD) = 1
),
LKP_IndividualClientStage AS (
	SELECT
	CIID_DTH_DT,
	CLIENT_ID
	FROM (
		SELECT CLIENT_ID as CLIENT_ID,
			CIID_DTH_DT as CIID_DTH_DT, 
			CIID_EFF_ACY_TS as CIID_EFF_ACY_TS 
		FROM dbo.IndividualClientStage
		WHERE CIID_EXP_DT = '9999-12-31'
		ORDER BY CIID_EFF_ACY_TS
		--
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY CLIENT_ID ORDER BY CIID_DTH_DT DESC) = 1
),
mplt_split_client_tab_long_name AS (WITH
	INPUT_long_name AS (
		
	),
	EXP_accept_input AS (
		SELECT
		long_name
		FROM INPUT_long_name
	),
	EXP_split_name AS (
		SELECT
		long_name,
		-- *INF*: instr(long_name,'+',1,1,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 1 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 1, 0
		) AS v_prefix,
		-- *INF*: instr(long_name,'+',1,2,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 2 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 2, 0
		) AS v_first,
		-- *INF*: instr(long_name,'+',1,3,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 3 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 3, 0
		) AS v_middle,
		-- *INF*: instr(long_name,'+',1,4,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 4 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 4, 0
		) AS v_last,
		-- *INF*: instr(long_name,'+',1,5,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 5 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 5, 0
		) AS v_suffix,
		-- *INF*: instr(long_name,'+',1,6,0)
		-- -- we are using instr to find the value "+" starting at position 1 and occurrence 6 not case sensitive
		REGEXP_INSTR(long_name, '+', 1, 6, 0
		) AS v_end,
		-- *INF*: ltrim(rtrim(replacestr(0,substr(long_name,v_prefix,v_first - v_prefix),'+','')))
		-- --we use substring to find the characters in long_name starting at the position v_prefix for a length of v_first - v_prefix.  Then we replace the "+" which will be the leading character with an empty string and finally we trim it
		ltrim(rtrim(REGEXP_REPLACE(substr(long_name, v_prefix, v_first - v_prefix
				),'+','','i')
			)
		) AS prefix,
		-- *INF*: ltrim(rtrim(replacestr(0,substr(long_name,v_first,v_middle - v_first),'+','')))
		-- --we use substring to find the characters in long_name starting at the position v_first for a length of v_middle - v_first.  Then we replace the "+" which will be the leading character with an empty string and finally we trim it
		ltrim(rtrim(REGEXP_REPLACE(substr(long_name, v_first, v_middle - v_first
				),'+','','i')
			)
		) AS first_name,
		-- *INF*: ltrim(rtrim(replacestr(0,substr(long_name,v_middle,v_last - v_middle),'+','')))
		-- --we use substring to find the characters in long_name starting at the position v_middle for a length of v_last - v_middle.  Then we replace the "+" which will be the leading character with an empty string and finally we trim it
		ltrim(rtrim(REGEXP_REPLACE(substr(long_name, v_middle, v_last - v_middle
				),'+','','i')
			)
		) AS middle_name,
		-- *INF*: ltrim(rtrim(replacestr(0,substr(long_name,v_last,v_suffix - v_last),'+','')))
		-- --we use substring to find the characters in long_name starting at the position v_last for a length of v_suffix - v_last.  Then we replace the "+" which will be the leading character with an empty string and finally we trim it
		ltrim(rtrim(REGEXP_REPLACE(substr(long_name, v_last, v_suffix - v_last
				),'+','','i')
			)
		) AS last_name,
		-- *INF*: ltrim(rtrim(replacestr(0,substr(long_name,v_suffix,v_end - v_suffix),'+','')))
		-- --we use substring to find the characters in long_name starting at the position v_suffix for a length of v_end - v_suffix.  Then we replace the "+" which will be the leading character with an empty string and finally we trim it
		ltrim(rtrim(REGEXP_REPLACE(substr(long_name, v_suffix, v_end - v_suffix
				),'+','','i')
			)
		) AS suffix
		FROM EXP_accept_input
	),
	EXP_build_full_name AS (
		SELECT
		prefix,
		first_name,
		middle_name,
		last_name,
		suffix,
		-- *INF*: rtrim(ltrim(
		-- IIF(length(prefix)>0,prefix || ' ','')
		-- ||
		-- IIF(length(first_name)>0,first_name || ' ','')
		-- ||
		-- IIF(length(middle_name)>0,middle_name || ' ','')
		-- ||
		-- IIF(length(last_name)>0,last_name || ' ','')
		-- ||
		-- IIF(length(suffix)>0,suffix || ' ','')
		-- )
		-- )
		rtrim(ltrim(IFF(length(prefix
					) > 0,
					prefix || ' ',
					''
				) || IFF(length(first_name
					) > 0,
					first_name || ' ',
					''
				) || IFF(length(middle_name
					) > 0,
					middle_name || ' ',
					''
				) || IFF(length(last_name
					) > 0,
					last_name || ' ',
					''
				) || IFF(length(suffix
					) > 0,
					suffix || ' ',
					''
				)
			)
		) AS full_name
		FROM EXP_split_name
	),
	EXP_accept_output AS (
		SELECT
		prefix,
		first_name,
		middle_name,
		last_name,
		suffix,
		full_name
		FROM EXP_build_full_name
	),
	OUTPUT_split_name AS (
		SELECT
		prefix, 
		first_name, 
		middle_name, 
		last_name, 
		suffix, 
		full_name
		FROM EXP_accept_output
	),
),
EXP_Lkp_Values AS (
	SELECT
	EXP_Values.CLIENT_ID,
	EXP_Values.CICL_FST_NM AS in_CICL_FST_NM,
	-- *INF*: iif(isnull(in_CICL_FST_NM),'N/A',
	--    iif(is_spaces(in_CICL_FST_NM),'N/A',
	--     rtrim(in_CICL_FST_NM)))
	-- 
	-- 
	IFF(in_CICL_FST_NM IS NULL,
		'N/A',
		IFF(LENGTH(in_CICL_FST_NM)>0 AND TRIM(in_CICL_FST_NM)='',
			'N/A',
			rtrim(in_CICL_FST_NM
			)
		)
	) AS CICL_FST_NM,
	EXP_Values.CICL_LST_NM AS in_CICL_LST_NM,
	-- *INF*: iif(isnull(in_CICL_LST_NM),'N/A',
	--    iif(is_spaces(in_CICL_LST_NM),'N/A',
	--     rtrim(in_CICL_LST_NM)))
	IFF(in_CICL_LST_NM IS NULL,
		'N/A',
		IFF(LENGTH(in_CICL_LST_NM)>0 AND TRIM(in_CICL_LST_NM)='',
			'N/A',
			rtrim(in_CICL_LST_NM
			)
		)
	) AS CICL_LST_NM,
	EXP_Values.CICL_MDL_NM AS in_CICL_MDL_NM,
	-- *INF*: iif(isnull(in_CICL_MDL_NM),'N/A',
	--    iif(is_spaces(in_CICL_MDL_NM),'N/A',
	--     rtrim(in_CICL_MDL_NM)))
	IFF(in_CICL_MDL_NM IS NULL,
		'N/A',
		IFF(LENGTH(in_CICL_MDL_NM)>0 AND TRIM(in_CICL_MDL_NM)='',
			'N/A',
			rtrim(in_CICL_MDL_NM
			)
		)
	) AS CICL_MDL_NM,
	EXP_Values.NM_PFX AS in_NM_PFX,
	-- *INF*: iif(isnull(in_NM_PFX),'N/A',
	--    iif(is_spaces(in_NM_PFX),'N/A',
	--     rtrim(in_NM_PFX)))
	-- 
	-- 
	IFF(in_NM_PFX IS NULL,
		'N/A',
		IFF(LENGTH(in_NM_PFX)>0 AND TRIM(in_NM_PFX)='',
			'N/A',
			rtrim(in_NM_PFX
			)
		)
	) AS NM_PFX,
	EXP_Values.NM_SFX AS in_NM_SFX,
	-- *INF*: iif(isnull(in_NM_SFX),'N/A',
	--    iif(is_spaces(in_NM_SFX),'N/A',
	--     rtrim(in_NM_SFX)))
	IFF(in_NM_SFX IS NULL,
		'N/A',
		IFF(LENGTH(in_NM_SFX)>0 AND TRIM(in_NM_SFX)='',
			'N/A',
			rtrim(in_NM_SFX
			)
		)
	) AS NM_SFX,
	EXP_Values.CICL_LNG_NM AS in_CICL_LNG_NM,
	-- *INF*: iif(isnull(in_CICL_LNG_NM),'N/A',
	--    iif(is_spaces(in_CICL_LNG_NM),'N/A',
	--     rtrim(in_CICL_LNG_NM)))
	IFF(in_CICL_LNG_NM IS NULL,
		'N/A',
		IFF(LENGTH(in_CICL_LNG_NM)>0 AND TRIM(in_CICL_LNG_NM)='',
			'N/A',
			rtrim(in_CICL_LNG_NM
			)
		)
	) AS CICL_LNG_NM,
	EXP_Values.CICL_DOB_DT AS in_CICL_DOB_DT,
	-- *INF*: iif(isnull(in_CICL_DOB_DT),
	--    TO_DATE('12/31/2100','MM/DD/YYYY'),
	--     in_CICL_DOB_DT)
	IFF(in_CICL_DOB_DT IS NULL,
		TO_DATE('12/31/2100', 'MM/DD/YYYY'
		),
		in_CICL_DOB_DT
	) AS CICL_DOB_DT,
	EXP_Values.GENDER_CD AS in_GENDER_CD,
	-- *INF*: iif(isnull(in_GENDER_CD),'N/A',
	--    iif(is_spaces(in_GENDER_CD),'N/A',
	--     in_GENDER_CD))
	IFF(in_GENDER_CD IS NULL,
		'N/A',
		IFF(LENGTH(in_GENDER_CD)>0 AND TRIM(in_GENDER_CD)='',
			'N/A',
			in_GENDER_CD
		)
	) AS GENDER_CD,
	LKP_CLIENT_ADDRESS_STAGE_INHM.CICA_PST_CD AS CICA_PST_CD_INHM,
	LKP_CLIENT_ADDRESS_STAGE_INHM.ST_CD AS ST_CD_INHM,
	LKP_CLIENT_ADDRESS_STAGE_INHM.CICA_ADR_1 AS CICA_ADR_1_INHM,
	LKP_CLIENT_ADDRESS_STAGE_INHM.CICA_ADR_2 AS CICA_ADR_2_INHM,
	LKP_CLIENT_ADDRESS_STAGE_INHM.CICA_CIT_NM AS CICA_CIT_NM_INHM,
	LKP_CLIENT_ADDRESS_STAGE_INHM.CICA_CTY AS CICA_CTY_INHM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.CICA_PST_CD AS CICA_PST_CD_BSM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.ST_CD AS ST_CD_BSM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.CICA_ADR_1 AS CICA_ADR_1_BSM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.CICA_ADR_2 AS CICA_ADR_2_BSM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.CICA_CIT_NM AS CICA_CIT_NM_BSM,
	LKP_CLIENT_ADDRESS_STAGE_BSM.CICA_CTY AS CICA_CTY_BSM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.CICA_PST_CD AS CICA_PST_CD_CLM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.ST_CD AS ST_CD_CLM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.CICA_ADR_1 AS CICA_ADR_1_CLM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.CICA_ADR_2 AS CICA_ADR_2_CLM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.CICA_CIT_NM AS CICA_CIT_NM_CLM,
	LKP_CLIENT_ADDRESS_STAGE_CLM.CICA_CTY AS CICA_CTY_CLM,
	LKP_CLIENT_ADDRESS_STAGE_LOC.CICA_PST_CD AS CICA_PST_CD_LOC,
	LKP_CLIENT_ADDRESS_STAGE_LOC.ST_CD AS ST_CD_LOC,
	LKP_CLIENT_ADDRESS_STAGE_LOC.CICA_ADR_1 AS CICA_ADR_1_LOC,
	LKP_CLIENT_ADDRESS_STAGE_LOC.CICA_ADR_2 AS CICA_ADR_2_LOC,
	LKP_CLIENT_ADDRESS_STAGE_LOC.CICA_CIT_NM AS CICA_CIT_NM_LOC,
	LKP_CLIENT_ADDRESS_STAGE_LOC.CICA_CTY AS CICA_CTY_LOC,
	LKP_CLIENT_ADDRESS_STAGE_BLM.CICA_PST_CD AS CICA_PST_CD_BLM,
	LKP_CLIENT_ADDRESS_STAGE_BLM.ST_CD AS ST_CD_BLM,
	LKP_CLIENT_ADDRESS_STAGE_BLM.CICA_ADR_1 AS CICA_ADR_1_BLM,
	LKP_CLIENT_ADDRESS_STAGE_BLM.CICA_ADR_2 AS CICA_ADR_2_BLM,
	LKP_CLIENT_ADDRESS_STAGE_BLM.CICA_CIT_NM AS CICA_CIT_NM_BLM,
	LKP_CLIENT_ADDRESS_STAGE_BLM.CICA_CTY AS CICA_CTY_BLM,
	LKP_CLIENT_ADDRESS_STAGE_PPL.CICA_PST_CD AS CICA_PST_CD_PPL,
	LKP_CLIENT_ADDRESS_STAGE_PPL.ST_CD AS ST_CD_PPL,
	LKP_CLIENT_ADDRESS_STAGE_PPL.CICA_ADR_1 AS CICA_ADR_1_PPL,
	LKP_CLIENT_ADDRESS_STAGE_PPL.CICA_ADR_2 AS CICA_ADR_2_PPL,
	LKP_CLIENT_ADDRESS_STAGE_PPL.CICA_CIT_NM AS CICA_CIT_NM_PPL,
	LKP_CLIENT_ADDRESS_STAGE_PPL.CICA_CTY AS CICA_CTY_PPL,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.CICA_PST_CD AS CICA_PST_CD_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.ST_CD AS ST_CD_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.CICA_ADR_1 AS CICA_ADR_1_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.CICA_ADR_2 AS CICA_ADR_2_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.CICA_CIT_NM AS CICA_CIT_NM_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BLRT.CICA_CTY AS CICA_CTY_BLRT,
	LKP_CLIENT_ADDRESS_STAGE_BSS.CICA_PST_CD AS CICA_PST_CD_BSS,
	LKP_CLIENT_ADDRESS_STAGE_BSS.ST_CD AS ST_CD_BSS,
	LKP_CLIENT_ADDRESS_STAGE_BSS.CICA_ADR_1 AS CICA_ADR_1_BSS,
	LKP_CLIENT_ADDRESS_STAGE_BSS.CICA_ADR_2 AS CICA_ADR_2_BSS,
	LKP_CLIENT_ADDRESS_STAGE_BSS.CICA_CIT_NM AS CICA_CIT_NM_BSS,
	LKP_CLIENT_ADDRESS_STAGE_BSS.CICA_CTY AS CICA_CTY_BSS,
	LKP_CLIENT_ADDRESS_STAGE_GL.CICA_PST_CD AS CICA_PST_CD_GL,
	LKP_CLIENT_ADDRESS_STAGE_GL.ST_CD AS ST_CD_GL,
	LKP_CLIENT_ADDRESS_STAGE_GL.CICA_ADR_1 AS CICA_ADR_1_GL,
	LKP_CLIENT_ADDRESS_STAGE_GL.CICA_ADR_2 AS CICA_ADR_2_GL,
	LKP_CLIENT_ADDRESS_STAGE_GL.CICA_CIT_NM AS CICA_CIT_NM_GL,
	LKP_CLIENT_ADDRESS_STAGE_GL.CICA_CTY AS CICA_CTY_GL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.CICA_PST_CD AS CICA_PST_CD_CLL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.ST_CD AS ST_CD_CLL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.CICA_ADR_1 AS CICA_ADR_1_CLL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.CICA_ADR_2 AS CICA_ADR_2_CLL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.CICA_CIT_NM AS CICA_CIT_NM_CLL,
	LKP_CLIENT_ADDRESS_STAGE_CLL.CICA_CTY AS CICA_CTY_CLL,
	LKP_CLIENT_ADDRESS_STAGE_HHA.CICA_PST_CD AS CICA_PST_CD_HHA,
	LKP_CLIENT_ADDRESS_STAGE_HHA.ST_CD AS ST_CD_HHA,
	LKP_CLIENT_ADDRESS_STAGE_HHA.CICA_ADR_1 AS CICA_ADR_1_HHA,
	LKP_CLIENT_ADDRESS_STAGE_HHA.CICA_ADR_2 AS CICA_ADR_2_HHA,
	LKP_CLIENT_ADDRESS_STAGE_HHA.CICA_CIT_NM AS CICA_CIT_NM_HHA,
	LKP_CLIENT_ADDRESS_STAGE_HHA.CICA_CTY AS CICA_CTY_HHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.CICA_PST_CD AS CICA_PST_CD_INHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.ST_CD AS ST_CD_INHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.CICA_ADR_1 AS CICA_ADR_1_INHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.CICA_ADR_2 AS CICA_ADR_2_INHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.CICA_CIT_NM AS CICA_CIT_NM_INHA,
	LKP_CLIENT_ADDRESS_STAGE_INHA.CICA_CTY AS CICA_CTY_INHA,
	LKP_CLIENT_ADDRESS_STAGE_LPE.CICA_PST_CD AS CICA_PST_CD_LPE,
	LKP_CLIENT_ADDRESS_STAGE_LPE.ST_CD AS ST_CD_LPE,
	LKP_CLIENT_ADDRESS_STAGE_LPE.CICA_ADR_1 AS CICA_ADR_1_LPE,
	LKP_CLIENT_ADDRESS_STAGE_LPE.CICA_ADR_2 AS CICA_ADR_2_LPE,
	LKP_CLIENT_ADDRESS_STAGE_LPE.CICA_CIT_NM AS CICA_CIT_NM_LPE,
	LKP_CLIENT_ADDRESS_STAGE_LPE.CICA_CTY AS CICA_CTY_LPE,
	LKP_CLIENT_ADDRESS_STAGE_PMF.CICA_PST_CD AS CICA_PST_CD_PMF,
	LKP_CLIENT_ADDRESS_STAGE_PMF.ST_CD AS ST_CD_PMF,
	LKP_CLIENT_ADDRESS_STAGE_PMF.CICA_ADR_1 AS CICA_ADR_1_PMF,
	LKP_CLIENT_ADDRESS_STAGE_PMF.CICA_ADR_2 AS CICA_ADR_2_PMF,
	LKP_CLIENT_ADDRESS_STAGE_PMF.CICA_CIT_NM AS CICA_CIT_NM_PMF,
	LKP_CLIENT_ADDRESS_STAGE_PMF.CICA_CTY AS CICA_CTY_PMF,
	LKP_CLIENT_ADDRESS_STAGE_INHL.CICA_PST_CD AS CICA_PST_CD_INHL,
	LKP_CLIENT_ADDRESS_STAGE_INHL.ST_CD AS ST_CD_INHL,
	LKP_CLIENT_ADDRESS_STAGE_INHL.CICA_ADR_1 AS CICA_ADR_1_INHL,
	LKP_CLIENT_ADDRESS_STAGE_INHL.CICA_ADR_2 AS CICA_ADR_2_INHL,
	LKP_CLIENT_ADDRESS_STAGE_INHL.CICA_CIT_NM AS CICA_CIT_NM_INHL,
	LKP_CLIENT_ADDRESS_STAGE_INHL.CICA_CTY AS CICA_CTY_INHL,
	LKP_CLIENT_ADDRESS_STAGE_PLG.CICA_PST_CD AS CICA_PST_CD_PLG,
	LKP_CLIENT_ADDRESS_STAGE_PLG.ST_CD AS ST_CD_PLG,
	LKP_CLIENT_ADDRESS_STAGE_PLG.CICA_ADR_1 AS CICA_ADR_1_PLG,
	LKP_CLIENT_ADDRESS_STAGE_PLG.CICA_ADR_2 AS CICA_ADR_2_PLG,
	LKP_CLIENT_ADDRESS_STAGE_PLG.CICA_CIT_NM AS CICA_CIT_NM_PLG,
	LKP_CLIENT_ADDRESS_STAGE_PLG.CICA_CTY AS CICA_CTY_PLG,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.CICA_PST_CD AS CICA_PST_CD_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.ST_CD AS ST_CD_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.CICA_ADR_1 AS CICA_ADR_1_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.CICA_ADR_2 AS CICA_ADR_2_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.CICA_CIT_NM AS CICA_CIT_NM_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_TMPM.CICA_CTY AS CICA_CTY_TMPM,
	LKP_CLIENT_ADDRESS_STAGE_INWL.CICA_PST_CD AS CICA_PST_CD_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWL.ST_CD AS ST_CD_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWL.CICA_ADR_1 AS CICA_ADR_1_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWL.CICA_ADR_2 AS CICA_ADR_2_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWL.CICA_CIT_NM AS CICA_CIT_NM_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWL.CICA_CTY AS CICA_CTY_INWL,
	LKP_CLIENT_ADDRESS_STAGE_INWM.CICA_PST_CD AS CICA_PST_CD_INWM,
	LKP_CLIENT_ADDRESS_STAGE_INWM.ST_CD AS ST_CD_INWM,
	LKP_CLIENT_ADDRESS_STAGE_INWM.CICA_ADR_1 AS CICA_ADR_1_INWM,
	LKP_CLIENT_ADDRESS_STAGE_INWM.CICA_ADR_2 AS CICA_ADR_2_INWM,
	LKP_CLIENT_ADDRESS_STAGE_INWM.CICA_CIT_NM AS CICA_CIT_NM_INWM,
	LKP_CLIENT_ADDRESS_STAGE_INWM.CICA_CTY AS CICA_CTY_INWM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.CICA_PST_CD AS CICA_PST_CD_ALM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.ST_CD AS ST_CD_ALM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.CICA_ADR_1 AS CICA_ADR_1_ALM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.CICA_ADR_2 AS CICA_ADR_2_ALM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.CICA_CIT_NM AS CICA_CIT_NM_ALM,
	LKP_CLIENT_ADDRESS_STAGE_ALM.CICA_CTY AS CICA_CTY_ALM,
	LKP_CLIENT_ADDRESS_STAGE_COM.CICA_PST_CD AS CICA_PST_CD_COM,
	LKP_CLIENT_ADDRESS_STAGE_COM.ST_CD AS ST_CD_COM,
	LKP_CLIENT_ADDRESS_STAGE_COM.CICA_ADR_1 AS CICA_ADR_1_COM,
	LKP_CLIENT_ADDRESS_STAGE_COM.CICA_ADR_2 AS CICA_ADR_2_COM,
	LKP_CLIENT_ADDRESS_STAGE_COM.CICA_CIT_NM AS CICA_CIT_NM_COM,
	LKP_CLIENT_ADDRESS_STAGE_COM.CICA_CTY AS CICA_CTY_COM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.CICA_PST_CD AS CICA_PST_CD_VCM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.ST_CD AS ST_CD_VCM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.CICA_ADR_1 AS CICA_ADR_1_VCM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.CICA_ADR_2 AS CICA_ADR_2_VCM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.CICA_CIT_NM AS CICA_CIT_NM_VCM,
	LKP_CLIENT_ADDRESS_STAGE_VCM.CICA_CTY AS CICA_CTY_VCM,
	LKP_CLIENT_ADDRESS_STAGE_LPA.CICA_PST_CD AS CICA_PST_CD_LPA,
	LKP_CLIENT_ADDRESS_STAGE_LPA.ST_CD AS ST_CD_LPA,
	LKP_CLIENT_ADDRESS_STAGE_LPA.CICA_ADR_1 AS CICA_ADR_1_LPA,
	LKP_CLIENT_ADDRESS_STAGE_LPA.CICA_ADR_2 AS CICA_ADR_2_LPA,
	LKP_CLIENT_ADDRESS_STAGE_LPA.CICA_CIT_NM AS CICA_CIT_NM_LPA,
	LKP_CLIENT_ADDRESS_STAGE_LPA.CICA_CTY AS CICA_CTY_LPA,
	LKP_CLIENT_ADDRESS_STAGE_VCL.CICA_PST_CD AS CICA_PST_CD_VCL,
	LKP_CLIENT_ADDRESS_STAGE_VCL.ST_CD AS ST_CD_VCL,
	LKP_CLIENT_ADDRESS_STAGE_VCL.CICA_ADR_1 AS CICA_ADR_1_VCL,
	LKP_CLIENT_ADDRESS_STAGE_VCL.CICA_ADR_2 AS CICA_ADR_2_VCL,
	LKP_CLIENT_ADDRESS_STAGE_VCL.CICA_CIT_NM AS CICA_CIT_NM_VCL,
	LKP_CLIENT_ADDRESS_STAGE_VCL.CICA_CTY AS CICA_CTY_VCL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.CICA_PST_CD AS CICA_PST_CD_SPL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.ST_CD AS ST_CD_SPL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.CICA_ADR_1 AS CICA_ADR_1_SPL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.CICA_ADR_2 AS CICA_ADR_2_SPL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.CICA_CIT_NM AS CICA_CIT_NM_SPL,
	LKP_CLIENT_ADDRESS_STAGE_SPL.CICA_CTY AS CICA_CTY_SPL,
	LKP_CLIENT_ADDRESS_STAGE_PLM.CICA_PST_CD AS CICA_PST_CD_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLM.ST_CD AS ST_CD_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLM.CICA_ADR_1 AS CICA_ADR_1_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLM.CICA_ADR_2 AS CICA_ADR_2_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLM.CICA_CIT_NM AS CICA_CIT_NM_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLM.CICA_CTY AS CICA_CTY_PLM,
	LKP_CLIENT_ADDRESS_STAGE_PLB.CICA_PST_CD AS CICA_PST_CD_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLB.ST_CD AS ST_CD_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLB.CICA_ADR_1 AS CICA_ADR_1_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLB.CICA_ADR_2 AS CICA_ADR_2_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLB.CICA_CIT_NM AS CICA_CIT_NM_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLB.CICA_CTY AS CICA_CTY_PLB,
	LKP_CLIENT_ADDRESS_STAGE_PLL.CICA_PST_CD AS CICA_PST_CD_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PLL.ST_CD AS ST_CD_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PLL.CICA_ADR_1 AS CICA_ADR_1_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PLL.CICA_ADR_2 AS CICA_ADR_2_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PLL.CICA_CIT_NM AS CICA_CIT_NM_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PLL.CICA_CTY AS CICA_CTY_PLL,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.CICA_PST_CD AS CICA_PST_CD_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.ST_CD AS ST_CD_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.CICA_ADR_1 AS CICA_ADR_1_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.CICA_ADR_2 AS CICA_ADR_2_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.CICA_CIT_NM AS CICA_CIT_NM_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_PRAD.CICA_CTY AS CICA_CTY_PRAD,
	LKP_CLIENT_ADDRESS_STAGE_ALL.CICA_PST_CD AS CICA_PST_CD_ALL,
	LKP_CLIENT_ADDRESS_STAGE_ALL.ST_CD AS ST_CD_ALL,
	LKP_CLIENT_ADDRESS_STAGE_ALL.CICA_ADR_1 AS CICA_ADR_1_ALL,
	LKP_CLIENT_ADDRESS_STAGE_ALL.CICA_ADR_2 AS CICA_ADR_2_ALL,
	LKP_CLIENT_ADDRESS_STAGE_ALL.CICA_CIT_NM AS CICA_CIT_NM_ALL,
	LKP_CLIENT_ADDRESS_STAGE_ALL.CICA_CTY AS CICA_CTY_ALL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.CICA_PST_CD AS CICA_PST_CD_MAL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.ST_CD AS ST_CD_MAL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.CICA_ADR_1 AS CICA_ADR_1_MAL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.CICA_ADR_2 AS CICA_ADR_2_MAL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.CICA_CIT_NM AS CICA_CIT_NM_MAL,
	LKP_CLIENT_ADDRESS_STAGE_MAL.CICA_CTY AS CICA_CTY_MAL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.CICA_PST_CD AS CICA_PST_CD_BSL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.ST_CD AS ST_CD_BSL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.CICA_ADR_1 AS CICA_ADR_1_BSL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.CICA_ADR_2 AS CICA_ADR_2_BSL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.CICA_CIT_NM AS CICA_CIT_NM_BSL,
	LKP_CLIENT_ADDRESS_STAGE_BSL.CICA_CTY AS CICA_CTY_BSL,
	-- *INF*: IIF(
	-- ISNULL(ltrim(rtrim(CICA_ADR_1_INHM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_BSM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_ALM ))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_ALM )))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_ALL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_ALL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_BSL ))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSL )))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_MAL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_MAL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_CLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_CLM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_LOC))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LOC)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_BLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BLM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PPL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PPL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_BLRT))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BLRT)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_BSS))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSS)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_GL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_GL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_CLL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_CLL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_HHA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_HHA)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_INHA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHA)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_LPE))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LPE)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PMF))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PMF)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_INHL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PLG))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLG)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_TMPM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_TMPM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_INWL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INWL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_INWM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INWM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_LPA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LPA)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PLB))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLB)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PLL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_PRAD))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PRAD)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_SPL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_SPL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_VCL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_VCL)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_VCM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_VCM)))
	-- AND ISNULL(ltrim(rtrim(CICA_ADR_1_COM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_COM)))
	-- ,'N/A'
	-- ,DECODE(TRUE
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_INHM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHM)))),'INHM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_BSM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSM)))),'BSM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_ALL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_ALL)))),'ALL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_BSL ))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSL )))),'BSL' 
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_MAL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_MAL)))),'MAL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_CLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_CLM)))),'CLM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_LOC))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LOC)))),'LOC'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_BLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BLM)))),'BLM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PPL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PPL)))),'PPL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_BLRT))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BLRT)))),'BLRT'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_BSS))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_BSS)))),'BSS'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_GL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_GL)))),'GL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_CLL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_CLL)))),'CLL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_HHA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_HHA)))),'HHA'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_INHA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHA)))),'INHA'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_LPE))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LPE)))),'LPE'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PMF))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PMF)))),'PMF'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_INHL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INHL)))),'INHL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PLG))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLG)))),'PLG'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_TMPM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_TMPM)))),'TMPM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_INWL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INWL)))),'INWL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_INWM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_INWM)))),'INWM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_LPA))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_LPA)))),'LPA'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PLB))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLB)))),'PLB'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PLL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLL)))),'PLL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PLM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PLM)))),'PLM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_PRAD))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_PRAD)))),'PRAD'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_SPL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_SPL)))),'SPL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_VCL))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_VCL)))),'VCL'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_VCM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_VCM)))),'VCM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_COM))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_COM)))),'COM'
	-- ,NOT (ISNULL(ltrim(rtrim(CICA_ADR_1_ALM ))) AND ISNULL(ltrim(rtrim(CICA_ADR_2_ALM) ))),'ALM '
	-- ,'N/A')
	-- )
	IFF(ltrim(rtrim(CICA_ADR_1_INHM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_INHM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_BSM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_BSM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_ALM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_ALM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_ALL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_ALL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_BSL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_BSL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_MAL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_MAL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_CLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_CLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_LOC
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_LOC
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_BLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_BLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PPL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PPL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_BLRT
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_BLRT
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_BSS
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_BSS
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_GL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_GL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_CLL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_CLL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_HHA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_HHA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_INHA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_INHA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_LPE
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_LPE
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PMF
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PMF
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_INHL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_INHL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PLG
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PLG
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_TMPM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_TMPM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_INWL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_INWL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_INWM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_INWM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_LPA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_LPA
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PLB
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PLB
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PLL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PLL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PLM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_PRAD
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_PRAD
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_SPL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_SPL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_VCL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_VCL
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_VCM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_VCM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_1_COM
			)
		) IS NULL 
		AND ltrim(rtrim(CICA_ADR_2_COM
			)
		) IS NULL,
		'N/A',
		DECODE(TRUE,
		NOT ( ltrim(rtrim(CICA_ADR_1_INHM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_INHM
					)
				) IS NULL 
			), 'INHM',
		NOT ( ltrim(rtrim(CICA_ADR_1_BSM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_BSM
					)
				) IS NULL 
			), 'BSM',
		NOT ( ltrim(rtrim(CICA_ADR_1_ALL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_ALL
					)
				) IS NULL 
			), 'ALL',
		NOT ( ltrim(rtrim(CICA_ADR_1_BSL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_BSL
					)
				) IS NULL 
			), 'BSL',
		NOT ( ltrim(rtrim(CICA_ADR_1_MAL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_MAL
					)
				) IS NULL 
			), 'MAL',
		NOT ( ltrim(rtrim(CICA_ADR_1_CLM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_CLM
					)
				) IS NULL 
			), 'CLM',
		NOT ( ltrim(rtrim(CICA_ADR_1_LOC
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_LOC
					)
				) IS NULL 
			), 'LOC',
		NOT ( ltrim(rtrim(CICA_ADR_1_BLM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_BLM
					)
				) IS NULL 
			), 'BLM',
		NOT ( ltrim(rtrim(CICA_ADR_1_PPL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PPL
					)
				) IS NULL 
			), 'PPL',
		NOT ( ltrim(rtrim(CICA_ADR_1_BLRT
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_BLRT
					)
				) IS NULL 
			), 'BLRT',
		NOT ( ltrim(rtrim(CICA_ADR_1_BSS
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_BSS
					)
				) IS NULL 
			), 'BSS',
		NOT ( ltrim(rtrim(CICA_ADR_1_GL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_GL
					)
				) IS NULL 
			), 'GL',
		NOT ( ltrim(rtrim(CICA_ADR_1_CLL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_CLL
					)
				) IS NULL 
			), 'CLL',
		NOT ( ltrim(rtrim(CICA_ADR_1_HHA
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_HHA
					)
				) IS NULL 
			), 'HHA',
		NOT ( ltrim(rtrim(CICA_ADR_1_INHA
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_INHA
					)
				) IS NULL 
			), 'INHA',
		NOT ( ltrim(rtrim(CICA_ADR_1_LPE
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_LPE
					)
				) IS NULL 
			), 'LPE',
		NOT ( ltrim(rtrim(CICA_ADR_1_PMF
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PMF
					)
				) IS NULL 
			), 'PMF',
		NOT ( ltrim(rtrim(CICA_ADR_1_INHL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_INHL
					)
				) IS NULL 
			), 'INHL',
		NOT ( ltrim(rtrim(CICA_ADR_1_PLG
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PLG
					)
				) IS NULL 
			), 'PLG',
		NOT ( ltrim(rtrim(CICA_ADR_1_TMPM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_TMPM
					)
				) IS NULL 
			), 'TMPM',
		NOT ( ltrim(rtrim(CICA_ADR_1_INWL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_INWL
					)
				) IS NULL 
			), 'INWL',
		NOT ( ltrim(rtrim(CICA_ADR_1_INWM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_INWM
					)
				) IS NULL 
			), 'INWM',
		NOT ( ltrim(rtrim(CICA_ADR_1_LPA
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_LPA
					)
				) IS NULL 
			), 'LPA',
		NOT ( ltrim(rtrim(CICA_ADR_1_PLB
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PLB
					)
				) IS NULL 
			), 'PLB',
		NOT ( ltrim(rtrim(CICA_ADR_1_PLL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PLL
					)
				) IS NULL 
			), 'PLL',
		NOT ( ltrim(rtrim(CICA_ADR_1_PLM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PLM
					)
				) IS NULL 
			), 'PLM',
		NOT ( ltrim(rtrim(CICA_ADR_1_PRAD
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_PRAD
					)
				) IS NULL 
			), 'PRAD',
		NOT ( ltrim(rtrim(CICA_ADR_1_SPL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_SPL
					)
				) IS NULL 
			), 'SPL',
		NOT ( ltrim(rtrim(CICA_ADR_1_VCL
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_VCL
					)
				) IS NULL 
			), 'VCL',
		NOT ( ltrim(rtrim(CICA_ADR_1_VCM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_VCM
					)
				) IS NULL 
			), 'VCM',
		NOT ( ltrim(rtrim(CICA_ADR_1_COM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_COM
					)
				) IS NULL 
			), 'COM',
		NOT ( ltrim(rtrim(CICA_ADR_1_ALM
					)
				) IS NULL 
				AND ltrim(rtrim(CICA_ADR_2_ALM
					)
				) IS NULL 
			), 'ALM ',
		'N/A'
		)
	) AS v_ADR_TYP_CD,
	-- *INF*: iif(isnull(v_ADR_TYP_CD),'N/A',
	--    iif(is_spaces(v_ADR_TYP_CD),'N/A',
	--     rtrim(v_ADR_TYP_CD)))
	IFF(v_ADR_TYP_CD IS NULL,
		'N/A',
		IFF(LENGTH(v_ADR_TYP_CD)>0 AND TRIM(v_ADR_TYP_CD)='',
			'N/A',
			rtrim(v_ADR_TYP_CD
			)
		)
	) AS ADR_TYP_CD,
	-- *INF*: DECODE( v_ADR_TYP_CD,
	-- 'INHM',CICA_ADR_1_INHM || CICA_ADR_2_INHM,
	-- 'BSM',CICA_ADR_1_BSM || CICA_ADR_2_BSM,
	-- 'ALM',CICA_ADR_1_ALM  || CICA_ADR_2_ALM ,
	-- 'ALL',CICA_ADR_1_ALL || CICA_ADR_2_ALL,
	-- 'BSL',CICA_ADR_1_BSL  || CICA_ADR_2_BSL ,
	-- 'MAL',CICA_ADR_1_MAL || CICA_ADR_2_MAL,
	-- 'CLM',CICA_ADR_1_CLM || CICA_ADR_2_CLM,
	-- 'LOC',CICA_ADR_1_LOC || CICA_ADR_2_LOC,
	-- 'BLM',CICA_ADR_1_BLM || CICA_ADR_2_BLM,
	-- 'PPL',CICA_ADR_1_PPL || CICA_ADR_2_PPL,
	-- 'BLRT',CICA_ADR_1_BLRT || CICA_ADR_2_BLRT,
	-- 'BSS',CICA_ADR_1_BSS || CICA_ADR_2_BSS,
	-- 'GL',CICA_ADR_1_GL || CICA_ADR_2_GL,
	-- 'CLL',CICA_ADR_1_CLL || CICA_ADR_2_CLL,
	-- 'HHA',CICA_ADR_1_HHA || CICA_ADR_2_HHA,
	-- 'INHA',CICA_ADR_1_INHA || CICA_ADR_2_INHA,
	-- 'LPE',CICA_ADR_1_LPE || CICA_ADR_2_LPE,
	-- 'PMF',CICA_ADR_1_PMF || CICA_ADR_2_PMF,
	-- 'INHL',CICA_ADR_1_INHL || CICA_ADR_2_INHL,
	-- 'PLG',CICA_ADR_1_PLG || CICA_ADR_2_PLG,
	-- 'TMPM',CICA_ADR_1_TMPM || CICA_ADR_2_TMPM,
	-- 'INWL',CICA_ADR_1_INWL || CICA_ADR_2_INWL,
	-- 'INWM',CICA_ADR_1_INWM || CICA_ADR_2_INWM,
	-- 'LPA',CICA_ADR_1_LPA || CICA_ADR_2_LPA,
	-- 'PLB',CICA_ADR_1_PLB || CICA_ADR_2_PLB,
	-- 'PLL',CICA_ADR_1_PLL || CICA_ADR_2_PLL,
	-- 'PLM',CICA_ADR_1_PLM || CICA_ADR_2_PLM,
	-- 'PRAD',CICA_ADR_1_PRAD || CICA_ADR_2_PRAD,
	-- 'SPL',CICA_ADR_1_SPL || CICA_ADR_2_SPL,
	-- 'VCL',CICA_ADR_1_VCL || CICA_ADR_2_VCL,
	-- 'VCM',CICA_ADR_1_VCM || CICA_ADR_2_VCM,
	-- 'COM',CICA_ADR_1_COM || CICA_ADR_2_COM)
	DECODE(v_ADR_TYP_CD,
		'INHM', CICA_ADR_1_INHM || CICA_ADR_2_INHM,
		'BSM', CICA_ADR_1_BSM || CICA_ADR_2_BSM,
		'ALM', CICA_ADR_1_ALM || CICA_ADR_2_ALM,
		'ALL', CICA_ADR_1_ALL || CICA_ADR_2_ALL,
		'BSL', CICA_ADR_1_BSL || CICA_ADR_2_BSL,
		'MAL', CICA_ADR_1_MAL || CICA_ADR_2_MAL,
		'CLM', CICA_ADR_1_CLM || CICA_ADR_2_CLM,
		'LOC', CICA_ADR_1_LOC || CICA_ADR_2_LOC,
		'BLM', CICA_ADR_1_BLM || CICA_ADR_2_BLM,
		'PPL', CICA_ADR_1_PPL || CICA_ADR_2_PPL,
		'BLRT', CICA_ADR_1_BLRT || CICA_ADR_2_BLRT,
		'BSS', CICA_ADR_1_BSS || CICA_ADR_2_BSS,
		'GL', CICA_ADR_1_GL || CICA_ADR_2_GL,
		'CLL', CICA_ADR_1_CLL || CICA_ADR_2_CLL,
		'HHA', CICA_ADR_1_HHA || CICA_ADR_2_HHA,
		'INHA', CICA_ADR_1_INHA || CICA_ADR_2_INHA,
		'LPE', CICA_ADR_1_LPE || CICA_ADR_2_LPE,
		'PMF', CICA_ADR_1_PMF || CICA_ADR_2_PMF,
		'INHL', CICA_ADR_1_INHL || CICA_ADR_2_INHL,
		'PLG', CICA_ADR_1_PLG || CICA_ADR_2_PLG,
		'TMPM', CICA_ADR_1_TMPM || CICA_ADR_2_TMPM,
		'INWL', CICA_ADR_1_INWL || CICA_ADR_2_INWL,
		'INWM', CICA_ADR_1_INWM || CICA_ADR_2_INWM,
		'LPA', CICA_ADR_1_LPA || CICA_ADR_2_LPA,
		'PLB', CICA_ADR_1_PLB || CICA_ADR_2_PLB,
		'PLL', CICA_ADR_1_PLL || CICA_ADR_2_PLL,
		'PLM', CICA_ADR_1_PLM || CICA_ADR_2_PLM,
		'PRAD', CICA_ADR_1_PRAD || CICA_ADR_2_PRAD,
		'SPL', CICA_ADR_1_SPL || CICA_ADR_2_SPL,
		'VCL', CICA_ADR_1_VCL || CICA_ADR_2_VCL,
		'VCM', CICA_ADR_1_VCM || CICA_ADR_2_VCM,
		'COM', CICA_ADR_1_COM || CICA_ADR_2_COM
	) AS v_CICA_ADR,
	-- *INF*: iif(isnull(v_CICA_ADR),'N/A',
	--    iif(is_spaces(v_CICA_ADR),'N/A',
	--     rtrim(v_CICA_ADR)))
	IFF(v_CICA_ADR IS NULL,
		'N/A',
		IFF(LENGTH(v_CICA_ADR)>0 AND TRIM(v_CICA_ADR)='',
			'N/A',
			rtrim(v_CICA_ADR
			)
		)
	) AS CICA_ADR,
	-- *INF*: DECODE( v_ADR_TYP_CD,
	-- 'INHM',CICA_CIT_NM_INHM,
	-- 'BSM',CICA_CIT_NM_BSM,
	-- 'ALM',CICA_CIT_NM_ALM ,
	-- 'ALL',CICA_CIT_NM_ALL,
	-- 'BSL',CICA_CIT_NM_BSL ,
	-- 'MAL',CICA_CIT_NM_MAL,
	-- 'CLM',CICA_CIT_NM_CLM,
	-- 'LOC',CICA_CIT_NM_LOC,
	-- 'BLM',CICA_CIT_NM_BLM,
	-- 'PPL',CICA_CIT_NM_PPL,
	-- 'BLRT',CICA_CIT_NM_BLRT,
	-- 'BSS',CICA_CIT_NM_BSS,
	-- 'GL',CICA_CIT_NM_GL,
	-- 'CLL',CICA_CIT_NM_CLL,
	-- 'HHA',CICA_CIT_NM_HHA,
	-- 'INHA',CICA_CIT_NM_INHA,
	-- 'LPE',CICA_CIT_NM_LPE,
	-- 'PMF',CICA_CIT_NM_PMF,
	-- 'INHL',CICA_CIT_NM_INHL,
	-- 'PLG',CICA_CIT_NM_PLG,
	-- 'TMPM',CICA_CIT_NM_TMPM,
	-- 'INWL',CICA_CIT_NM_INWL,
	-- 'INWM',CICA_CIT_NM_INWM,
	-- 'LPA',CICA_CIT_NM_LPA,
	-- 'PLB',CICA_CIT_NM_PLB,
	-- 'PLL',CICA_CIT_NM_PLL,
	-- 'PLM',CICA_CIT_NM_PLM,
	-- 'PRAD',CICA_CIT_NM_PRAD,
	-- 'SPL',CICA_CIT_NM_SPL,
	-- 'VCL',CICA_CIT_NM_VCL,
	-- 'VCM',CICA_CIT_NM_VCM,
	-- 'COM',CICA_CIT_NM_COM)
	DECODE(v_ADR_TYP_CD,
		'INHM', CICA_CIT_NM_INHM,
		'BSM', CICA_CIT_NM_BSM,
		'ALM', CICA_CIT_NM_ALM,
		'ALL', CICA_CIT_NM_ALL,
		'BSL', CICA_CIT_NM_BSL,
		'MAL', CICA_CIT_NM_MAL,
		'CLM', CICA_CIT_NM_CLM,
		'LOC', CICA_CIT_NM_LOC,
		'BLM', CICA_CIT_NM_BLM,
		'PPL', CICA_CIT_NM_PPL,
		'BLRT', CICA_CIT_NM_BLRT,
		'BSS', CICA_CIT_NM_BSS,
		'GL', CICA_CIT_NM_GL,
		'CLL', CICA_CIT_NM_CLL,
		'HHA', CICA_CIT_NM_HHA,
		'INHA', CICA_CIT_NM_INHA,
		'LPE', CICA_CIT_NM_LPE,
		'PMF', CICA_CIT_NM_PMF,
		'INHL', CICA_CIT_NM_INHL,
		'PLG', CICA_CIT_NM_PLG,
		'TMPM', CICA_CIT_NM_TMPM,
		'INWL', CICA_CIT_NM_INWL,
		'INWM', CICA_CIT_NM_INWM,
		'LPA', CICA_CIT_NM_LPA,
		'PLB', CICA_CIT_NM_PLB,
		'PLL', CICA_CIT_NM_PLL,
		'PLM', CICA_CIT_NM_PLM,
		'PRAD', CICA_CIT_NM_PRAD,
		'SPL', CICA_CIT_NM_SPL,
		'VCL', CICA_CIT_NM_VCL,
		'VCM', CICA_CIT_NM_VCM,
		'COM', CICA_CIT_NM_COM
	) AS v_CICA_CIT_NM,
	-- *INF*: IIF(isnull(v_CICA_CIT_NM),'N/A', 
	-- IIF(is_spaces(v_CICA_CIT_NM),'N/A', 
	--  rtrim(v_CICA_CIT_NM)))
	IFF(v_CICA_CIT_NM IS NULL,
		'N/A',
		IFF(LENGTH(v_CICA_CIT_NM)>0 AND TRIM(v_CICA_CIT_NM)='',
			'N/A',
			rtrim(v_CICA_CIT_NM
			)
		)
	) AS CICA_CIT_NM,
	-- *INF*: DECODE( v_ADR_TYP_CD,
	-- 'INHM',CICA_CTY_INHM,
	-- 'BSM',CICA_CTY_BSM,
	-- 'ALM',CICA_CTY_ALM ,
	-- 'ALL',CICA_CTY_ALL,
	-- 'BSL',CICA_CTY_BSL ,
	-- 'MAL',CICA_CTY_MAL,
	-- 'CLM',CICA_CTY_CLM,
	-- 'LOC',CICA_CTY_LOC,
	-- 'BLM',CICA_CTY_BLM,
	-- 'PPL',CICA_CTY_PPL,
	-- 'BLRT',CICA_CTY_BLRT,
	-- 'BSS',CICA_CTY_BSS,
	-- 'GL',CICA_CTY_GL,
	-- 'CLL',CICA_CTY_CLL,
	-- 'HHA',CICA_CTY_HHA,
	-- 'INHA',CICA_CTY_INHA,
	-- 'LPE',CICA_CTY_LPE,
	-- 'PMF',CICA_CTY_PMF,
	-- 'INHL',CICA_CTY_INHL,
	-- 'PLG',CICA_CTY_PLG,
	-- 'TMPM',CICA_CTY_TMPM,
	-- 'INWL',CICA_CTY_INWL,
	-- 'INWM',CICA_CTY_INWM,
	-- 'LPA',CICA_CTY_LPA,
	-- 'PLB',CICA_CTY_PLB,
	-- 'PLL',CICA_CTY_PLL,
	-- 'PLM',CICA_CTY_PLM,
	-- 'PRAD',CICA_CTY_PRAD,
	-- 'SPL',CICA_CTY_SPL,
	-- 'VCL',CICA_CTY_VCL,
	-- 'VCM',CICA_CTY_VCM,
	-- 'COM',CICA_CTY_COM)
	DECODE(v_ADR_TYP_CD,
		'INHM', CICA_CTY_INHM,
		'BSM', CICA_CTY_BSM,
		'ALM', CICA_CTY_ALM,
		'ALL', CICA_CTY_ALL,
		'BSL', CICA_CTY_BSL,
		'MAL', CICA_CTY_MAL,
		'CLM', CICA_CTY_CLM,
		'LOC', CICA_CTY_LOC,
		'BLM', CICA_CTY_BLM,
		'PPL', CICA_CTY_PPL,
		'BLRT', CICA_CTY_BLRT,
		'BSS', CICA_CTY_BSS,
		'GL', CICA_CTY_GL,
		'CLL', CICA_CTY_CLL,
		'HHA', CICA_CTY_HHA,
		'INHA', CICA_CTY_INHA,
		'LPE', CICA_CTY_LPE,
		'PMF', CICA_CTY_PMF,
		'INHL', CICA_CTY_INHL,
		'PLG', CICA_CTY_PLG,
		'TMPM', CICA_CTY_TMPM,
		'INWL', CICA_CTY_INWL,
		'INWM', CICA_CTY_INWM,
		'LPA', CICA_CTY_LPA,
		'PLB', CICA_CTY_PLB,
		'PLL', CICA_CTY_PLL,
		'PLM', CICA_CTY_PLM,
		'PRAD', CICA_CTY_PRAD,
		'SPL', CICA_CTY_SPL,
		'VCL', CICA_CTY_VCL,
		'VCM', CICA_CTY_VCM,
		'COM', CICA_CTY_COM
	) AS v_CICA_CTY,
	-- *INF*: iif(isnull(rtrim(v_CICA_CTY)),'N/A',
	--    iif(is_spaces(v_CICA_CTY),'N/A',
	--     rtrim(v_CICA_CTY)))
	IFF(rtrim(v_CICA_CTY
		) IS NULL,
		'N/A',
		IFF(LENGTH(v_CICA_CTY)>0 AND TRIM(v_CICA_CTY)='',
			'N/A',
			rtrim(v_CICA_CTY
			)
		)
	) AS CICA_CTY,
	-- *INF*: DECODE( v_ADR_TYP_CD,
	-- 'INHM',ST_CD_INHM,
	-- 'BSM',ST_CD_BSM,
	-- 'ALM',ST_CD_ALM ,
	-- 'ALL',ST_CD_ALL,
	-- 'BSL',ST_CD_BSL ,
	-- 'MAL',ST_CD_MAL,
	-- 'CLM',ST_CD_CLM,
	-- 'LOC',ST_CD_LOC,
	-- 'BLM',ST_CD_BLM,
	-- 'PPL',ST_CD_PPL,
	-- 'BLRT',ST_CD_BLRT,
	-- 'BSS',ST_CD_BSS,
	-- 'GL',ST_CD_GL,
	-- 'CLL',ST_CD_CLL,
	-- 'HHA',ST_CD_HHA,
	-- 'INHA',ST_CD_INHA,
	-- 'LPE',ST_CD_LPE,
	-- 'PMF',ST_CD_PMF,
	-- 'INHL',ST_CD_INHL,
	-- 'PLG',ST_CD_PLG,
	-- 'TMPM',ST_CD_TMPM,
	-- 'INWL',ST_CD_INWL,
	-- 'INWM',ST_CD_INWM,
	-- 'LPA',ST_CD_LPA,
	-- 'PLB',ST_CD_PLB,
	-- 'PLL',ST_CD_PLL,
	-- 'PLM',ST_CD_PLM,
	-- 'PRAD',ST_CD_PRAD,
	-- 'SPL',ST_CD_SPL,
	-- 'VCL',ST_CD_VCL,
	-- 'VCM',ST_CD_VCM,
	-- 'COM',ST_CD_COM)
	DECODE(v_ADR_TYP_CD,
		'INHM', ST_CD_INHM,
		'BSM', ST_CD_BSM,
		'ALM', ST_CD_ALM,
		'ALL', ST_CD_ALL,
		'BSL', ST_CD_BSL,
		'MAL', ST_CD_MAL,
		'CLM', ST_CD_CLM,
		'LOC', ST_CD_LOC,
		'BLM', ST_CD_BLM,
		'PPL', ST_CD_PPL,
		'BLRT', ST_CD_BLRT,
		'BSS', ST_CD_BSS,
		'GL', ST_CD_GL,
		'CLL', ST_CD_CLL,
		'HHA', ST_CD_HHA,
		'INHA', ST_CD_INHA,
		'LPE', ST_CD_LPE,
		'PMF', ST_CD_PMF,
		'INHL', ST_CD_INHL,
		'PLG', ST_CD_PLG,
		'TMPM', ST_CD_TMPM,
		'INWL', ST_CD_INWL,
		'INWM', ST_CD_INWM,
		'LPA', ST_CD_LPA,
		'PLB', ST_CD_PLB,
		'PLL', ST_CD_PLL,
		'PLM', ST_CD_PLM,
		'PRAD', ST_CD_PRAD,
		'SPL', ST_CD_SPL,
		'VCL', ST_CD_VCL,
		'VCM', ST_CD_VCM,
		'COM', ST_CD_COM
	) AS v_ST_CD,
	-- *INF*: iif(isnull(v_ST_CD),'N/A',
	--    iif(is_spaces(v_ST_CD),'N/A',
	--     rtrim(v_ST_CD)))
	IFF(v_ST_CD IS NULL,
		'N/A',
		IFF(LENGTH(v_ST_CD)>0 AND TRIM(v_ST_CD)='',
			'N/A',
			rtrim(v_ST_CD
			)
		)
	) AS ST_CD,
	-- *INF*: DECODE( v_ADR_TYP_CD,
	-- 'INHM',CICA_PST_CD_INHM,
	-- 'BSM',CICA_PST_CD_BSM,
	-- 'ALM',CICA_PST_CD_ALM ,
	-- 'ALL',CICA_PST_CD_ALL,
	-- 'BSL',CICA_PST_CD_BSL ,
	-- 'MAL',CICA_PST_CD_MAL,
	-- 'CLM',CICA_PST_CD_CLM,
	-- 'LOC',CICA_PST_CD_LOC,
	-- 'BLM',CICA_PST_CD_BLM,
	-- 'PPL',CICA_PST_CD_PPL,
	-- 'BLRT',CICA_PST_CD_BLRT,
	-- 'BSS',CICA_PST_CD_BSS,
	-- 'GL',CICA_PST_CD_GL,
	-- 'CLL',CICA_PST_CD_CLL,
	-- 'HHA',CICA_PST_CD_HHA,
	-- 'INHA',CICA_PST_CD_INHA,
	-- 'LPE',CICA_PST_CD_LPE,
	-- 'PMF',CICA_PST_CD_PMF,
	-- 'INHL',CICA_PST_CD_INHL,
	-- 'PLG',CICA_PST_CD_PLG,
	-- 'TMPM',CICA_PST_CD_TMPM,
	-- 'INWL',CICA_PST_CD_INWL,
	-- 'INWM',CICA_PST_CD_INWM,
	-- 'LPA',CICA_PST_CD_LPA,
	-- 'PLB',CICA_PST_CD_PLB,
	-- 'PLL',CICA_PST_CD_PLL,
	-- 'PLM',CICA_PST_CD_PLM,
	-- 'PRAD',CICA_PST_CD_PRAD,
	-- 'SPL',CICA_PST_CD_SPL,
	-- 'VCL',CICA_PST_CD_VCL,
	-- 'VCM',CICA_PST_CD_VCM,
	-- 'COM',CICA_PST_CD_COM)
	DECODE(v_ADR_TYP_CD,
		'INHM', CICA_PST_CD_INHM,
		'BSM', CICA_PST_CD_BSM,
		'ALM', CICA_PST_CD_ALM,
		'ALL', CICA_PST_CD_ALL,
		'BSL', CICA_PST_CD_BSL,
		'MAL', CICA_PST_CD_MAL,
		'CLM', CICA_PST_CD_CLM,
		'LOC', CICA_PST_CD_LOC,
		'BLM', CICA_PST_CD_BLM,
		'PPL', CICA_PST_CD_PPL,
		'BLRT', CICA_PST_CD_BLRT,
		'BSS', CICA_PST_CD_BSS,
		'GL', CICA_PST_CD_GL,
		'CLL', CICA_PST_CD_CLL,
		'HHA', CICA_PST_CD_HHA,
		'INHA', CICA_PST_CD_INHA,
		'LPE', CICA_PST_CD_LPE,
		'PMF', CICA_PST_CD_PMF,
		'INHL', CICA_PST_CD_INHL,
		'PLG', CICA_PST_CD_PLG,
		'TMPM', CICA_PST_CD_TMPM,
		'INWL', CICA_PST_CD_INWL,
		'INWM', CICA_PST_CD_INWM,
		'LPA', CICA_PST_CD_LPA,
		'PLB', CICA_PST_CD_PLB,
		'PLL', CICA_PST_CD_PLL,
		'PLM', CICA_PST_CD_PLM,
		'PRAD', CICA_PST_CD_PRAD,
		'SPL', CICA_PST_CD_SPL,
		'VCL', CICA_PST_CD_VCL,
		'VCM', CICA_PST_CD_VCM,
		'COM', CICA_PST_CD_COM
	) AS v_CICA_PST_CD,
	-- *INF*: iif(isnull(v_CICA_PST_CD),'N/A',
	--    iif(is_spaces(v_CICA_PST_CD),'N/A',
	--     rtrim(v_CICA_PST_CD)))
	IFF(v_CICA_PST_CD IS NULL,
		'N/A',
		IFF(LENGTH(v_CICA_PST_CD)>0 AND TRIM(v_CICA_PST_CD)='',
			'N/A',
			rtrim(v_CICA_PST_CD
			)
		)
	) AS CICA_PST_CD,
	-- *INF*: IIF(ISNULL(:LKP.LKP_CLIENT_TAX_STAGE(CLIENT_ID,'SSN')),
	-- 'N/A',
	-- ltrim(rtrim(:LKP.LKP_CLIENT_TAX_STAGE(CLIENT_ID,'SSN'))))
	-- 
	IFF(LKP_CLIENT_TAX_STAGE_CLIENT_ID_SSN.citx_tax_id IS NULL,
		'N/A',
		ltrim(rtrim(LKP_CLIENT_TAX_STAGE_CLIENT_ID_SSN.citx_tax_id
			)
		)
	) AS citx_tax_id_ssn,
	-- *INF*: IIF(ISNULL(:LKP.LKP_CLIENT_TAX_STAGE(CLIENT_ID,'FED')),
	-- 'N/A',
	-- :LKP.LKP_CLIENT_TAX_STAGE(CLIENT_ID,'FED'))
	IFF(LKP_CLIENT_TAX_STAGE_CLIENT_ID_FED.citx_tax_id IS NULL,
		'N/A',
		LKP_CLIENT_TAX_STAGE_CLIENT_ID_FED.citx_tax_id
	) AS citx_tax_id_fed,
	EXP_phone.Phone,
	EXP_phone.Phone_Extn,
	EXP_phone.Phone_Type,
	EXP_Values.LEG_ENT_CD AS in_LEG_ENT_CD,
	-- *INF*: iif(isnull(in_LEG_ENT_CD),'N/A',
	--    iif(is_spaces(in_LEG_ENT_CD),'N/A',
	--     rtrim(in_LEG_ENT_CD)))
	IFF(in_LEG_ENT_CD IS NULL,
		'N/A',
		IFF(LENGTH(in_LEG_ENT_CD)>0 AND TRIM(in_LEG_ENT_CD)='',
			'N/A',
			rtrim(in_LEG_ENT_CD
			)
		)
	) AS LEG_ENT_CD,
	EXP_Values.CICL_EFF_ACY_TS,
	-- *INF*: iif(isnull(CICL_EFF_ACY_TS),
	--    TO_DATE('01/01/1800','MM/DD/YYYY'),
	--     CICL_EFF_ACY_TS)
	IFF(CICL_EFF_ACY_TS IS NULL,
		TO_DATE('01/01/1800', 'MM/DD/YYYY'
		),
		CICL_EFF_ACY_TS
	) AS claim_party_ref_eff_from_date,
	mplt_split_client_tab_long_name.prefix AS mplt_prefix,
	-- *INF*: IIF(isnull(mplt_prefix) or length(mplt_prefix)=0,'N/A',mplt_prefix)
	IFF(mplt_prefix IS NULL 
		OR length(mplt_prefix
		) = 0,
		'N/A',
		mplt_prefix
	) AS mplt_prefix_out,
	mplt_split_client_tab_long_name.first_name AS mplt_first_name,
	-- *INF*: IIF(isnull(mplt_first_name) or length(mplt_first_name)=0,'N/A',mplt_first_name)
	IFF(mplt_first_name IS NULL 
		OR length(mplt_first_name
		) = 0,
		'N/A',
		mplt_first_name
	) AS mplt_first_name_out,
	mplt_split_client_tab_long_name.middle_name AS mplt_middle_name,
	-- *INF*: IIF(isnull(mplt_middle_name) or length(mplt_middle_name)=0,'N/A',mplt_middle_name)
	IFF(mplt_middle_name IS NULL 
		OR length(mplt_middle_name
		) = 0,
		'N/A',
		mplt_middle_name
	) AS mplt_middle_name_out,
	mplt_split_client_tab_long_name.last_name AS mplt_last_name,
	-- *INF*: IIF(isnull(mplt_last_name) or length(mplt_last_name)=0,'N/A',mplt_last_name)
	IFF(mplt_last_name IS NULL 
		OR length(mplt_last_name
		) = 0,
		'N/A',
		mplt_last_name
	) AS mplt_last_name_out,
	mplt_split_client_tab_long_name.suffix AS mplt_suffix,
	-- *INF*: IIF(isnull(mplt_suffix) or length(mplt_suffix)=0,'N/A',mplt_suffix)
	IFF(mplt_suffix IS NULL 
		OR length(mplt_suffix
		) = 0,
		'N/A',
		mplt_suffix
	) AS mplt_suffix_out,
	mplt_split_client_tab_long_name.full_name AS mplt_full_name,
	-- *INF*: IIF(isnull(mplt_full_name) or length(mplt_full_name)=0,'N/A',mplt_full_name)
	IFF(mplt_full_name IS NULL 
		OR length(mplt_full_name
		) = 0,
		'N/A',
		mplt_full_name
	) AS mplt_full_name_out,
	LKP_IndividualClientStage.CIID_DTH_DT,
	-- *INF*: IIF(ISNULL(CIID_DTH_DT) OR CIID_DTH_DT > TO_DATE('12/31/2999','MM/DD/YYYY'), 
	-- 		TO_DATE('12/31/2999','MM/DD/YYYY'), 
	-- 	CIID_DTH_DT)
	IFF(CIID_DTH_DT IS NULL 
		OR CIID_DTH_DT > TO_DATE('12/31/2999', 'MM/DD/YYYY'
		),
		TO_DATE('12/31/2999', 'MM/DD/YYYY'
		),
		CIID_DTH_DT
	) AS v_CIID_DTH_DT,
	v_CIID_DTH_DT AS o_CIID_DTH_DT
	FROM EXP_Values
	 -- Manually join with EXP_phone
	 -- Manually join with mplt_split_client_tab_long_name
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_ALL
	ON LKP_CLIENT_ADDRESS_STAGE_ALL.ADR_ID = EXP_Values.ADR_ID_ALL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_ALM
	ON LKP_CLIENT_ADDRESS_STAGE_ALM.ADR_ID = EXP_Values.ADR_ID_ALM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_BLM
	ON LKP_CLIENT_ADDRESS_STAGE_BLM.ADR_ID = EXP_Values.ADR_ID_BLM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_BLRT
	ON LKP_CLIENT_ADDRESS_STAGE_BLRT.ADR_ID = EXP_Values.ADR_ID_BLRT
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_BSL
	ON LKP_CLIENT_ADDRESS_STAGE_BSL.ADR_ID = EXP_Values.ADR_ID_BSL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_BSM
	ON LKP_CLIENT_ADDRESS_STAGE_BSM.ADR_ID = EXP_Values.ADR_ID_BSM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_BSS
	ON LKP_CLIENT_ADDRESS_STAGE_BSS.ADR_ID = EXP_Values.ADR_ID_BSS
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_CLL
	ON LKP_CLIENT_ADDRESS_STAGE_CLL.ADR_ID = EXP_Values.ADR_ID_CLL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_CLM
	ON LKP_CLIENT_ADDRESS_STAGE_CLM.ADR_ID = EXP_Values.ADR_ID_CLM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_COM
	ON LKP_CLIENT_ADDRESS_STAGE_COM.ADR_ID = EXP_Values.ADR_ID_COM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_GL
	ON LKP_CLIENT_ADDRESS_STAGE_GL.ADR_ID = EXP_Values.ADR_ID_GL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_HHA
	ON LKP_CLIENT_ADDRESS_STAGE_HHA.ADR_ID = EXP_Values.ADR_ID_HHA
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_INHA
	ON LKP_CLIENT_ADDRESS_STAGE_INHA.ADR_ID = EXP_Values.ADR_ID_INHA
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_INHL
	ON LKP_CLIENT_ADDRESS_STAGE_INHL.ADR_ID = EXP_Values.ADR_ID_INHL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_INHM
	ON LKP_CLIENT_ADDRESS_STAGE_INHM.ADR_ID = EXP_Values.ADR_ID_INHM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_INWL
	ON LKP_CLIENT_ADDRESS_STAGE_INWL.ADR_ID = EXP_Values.ADR_ID_INWL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_INWM
	ON LKP_CLIENT_ADDRESS_STAGE_INWM.ADR_ID = EXP_Values.ADR_ID_INWM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_LOC
	ON LKP_CLIENT_ADDRESS_STAGE_LOC.ADR_ID = EXP_Values.ADR_ID_LOC
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_LPA
	ON LKP_CLIENT_ADDRESS_STAGE_LPA.ADR_ID = EXP_Values.ADR_ID_LPA
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_LPE
	ON LKP_CLIENT_ADDRESS_STAGE_LPE.ADR_ID = EXP_Values.ADR_ID_LPE
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_MAL
	ON LKP_CLIENT_ADDRESS_STAGE_MAL.ADR_ID = EXP_Values.ADR_ID_MAL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PLB
	ON LKP_CLIENT_ADDRESS_STAGE_PLB.ADR_ID = EXP_Values.ADR_ID_PLB
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PLG
	ON LKP_CLIENT_ADDRESS_STAGE_PLG.ADR_ID = EXP_Values.ADR_ID_PLG
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PLL
	ON LKP_CLIENT_ADDRESS_STAGE_PLL.ADR_ID = EXP_Values.ADR_ID_PLL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PLM
	ON LKP_CLIENT_ADDRESS_STAGE_PLM.ADR_ID = EXP_Values.ADR_ID_PLM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PMF
	ON LKP_CLIENT_ADDRESS_STAGE_PMF.ADR_ID = EXP_Values.ADR_ID_PMF
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PPL
	ON LKP_CLIENT_ADDRESS_STAGE_PPL.ADR_ID = EXP_Values.ADR_ID_PPL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_PRAD
	ON LKP_CLIENT_ADDRESS_STAGE_PRAD.ADR_ID = EXP_Values.ADR_ID_PRAD
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_SPL
	ON LKP_CLIENT_ADDRESS_STAGE_SPL.ADR_ID = EXP_Values.ADR_ID_SPL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_TMPM
	ON LKP_CLIENT_ADDRESS_STAGE_TMPM.ADR_ID = EXP_Values.ADR_ID_TMPM
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_VCL
	ON LKP_CLIENT_ADDRESS_STAGE_VCL.ADR_ID = EXP_Values.ADR_ID_VCL
	LEFT JOIN LKP_CLIENT_ADDRESS_STAGE_VCM
	ON LKP_CLIENT_ADDRESS_STAGE_VCM.ADR_ID = EXP_Values.ADR_ID_VCM
	LEFT JOIN LKP_IndividualClientStage
	ON LKP_IndividualClientStage.CLIENT_ID = EXP_Values.CLIENT_ID
	LEFT JOIN LKP_CLIENT_TAX_STAGE LKP_CLIENT_TAX_STAGE_CLIENT_ID_SSN
	ON LKP_CLIENT_TAX_STAGE_CLIENT_ID_SSN.client_id = CLIENT_ID
	AND LKP_CLIENT_TAX_STAGE_CLIENT_ID_SSN.tax_type_cd = 'SSN'

	LEFT JOIN LKP_CLIENT_TAX_STAGE LKP_CLIENT_TAX_STAGE_CLIENT_ID_FED
	ON LKP_CLIENT_TAX_STAGE_CLIENT_ID_FED.client_id = CLIENT_ID
	AND LKP_CLIENT_TAX_STAGE_CLIENT_ID_FED.tax_type_cd = 'FED'

),
LKP_Claim_Party AS (
	SELECT
	claim_party_id,
	claim_party_ak_id,
	claim_party_full_name,
	claim_party_first_name,
	claim_party_last_name,
	claim_party_mid_name,
	claim_party_name_prfx,
	claim_party_name_sfx,
	claim_party_addr,
	claim_party_city,
	claim_party_county,
	claim_party_state,
	claim_party_zip,
	addr_type,
	tax_ssn_id,
	tax_fed_id,
	claim_party_birthdate,
	claim_party_gndr,
	ph_num,
	ph_extension,
	ph_type,
	lgl_ent_code,
	claim_party_ref_eff_from_date,
	claim_party_death_date,
	claim_party_key
	FROM (
		SELECT a.claim_party_id as claim_party_id, 
		a.claim_party_ak_id as claim_party_ak_id, 
		a.claim_party_full_name as claim_party_full_name, 
		a.claim_party_first_name as claim_party_first_name, 
		a.claim_party_last_name as claim_party_last_name, 
		a.claim_party_mid_name as claim_party_mid_name, 
		a.claim_party_name_prfx as claim_party_name_prfx, 
		a.claim_party_name_sfx as claim_party_name_sfx, 
		a.claim_party_addr as claim_party_addr, 
		a.claim_party_city as claim_party_city, 
		a.claim_party_county as claim_party_county, 
		a.claim_party_state as claim_party_state, 
		a.claim_party_zip as claim_party_zip, 
		a.addr_type as addr_type, 
		a.tax_ssn_id as tax_ssn_id, 
		a.tax_fed_id as tax_fed_id, 
		a.claim_party_birthdate as claim_party_birthdate, 
		a.claim_party_gndr as claim_party_gndr, 
		a.ph_num as ph_num, 
		a.ph_extension as ph_extension, 
		a.ph_type as ph_type, 
		a.lgl_ent_code as lgl_ent_code, 
		a.claim_party_ref_eff_from_date as claim_party_ref_eff_from_date, 
		a.claim_party_death_date as claim_party_death_date, 
		a.claim_party_key as claim_party_key 
		FROM @{pipeline().parameters.TARGET_TABLE_OWNER}.claim_party a
		INNER JOIN @{pipeline().parameters.STAGING_DATABASE}.@{pipeline().parameters.TARGET_TABLE_OWNER}.client_tab_stage b
		on a.claim_party_key = b.CLIENT_ID
		WHERE  a.source_sys_id = '@{pipeline().parameters.SOURCE_SYSTEM_ID}'  AND a.crrnt_snpsht_flag = 1
		ORDER BY claim_party_key --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY claim_party_key ORDER BY claim_party_id) = 1
),
EXP_Detect_Changes AS (
	SELECT
	EXP_Lkp_Values.CLIENT_ID,
	EXP_Lkp_Values.mplt_first_name_out AS CICL_FST_NM,
	EXP_Lkp_Values.mplt_last_name_out AS CICL_LST_NM,
	EXP_Lkp_Values.mplt_middle_name_out AS CICL_MDL_NM,
	EXP_Lkp_Values.mplt_prefix_out AS NM_PFX,
	EXP_Lkp_Values.mplt_suffix_out AS NM_SFX,
	EXP_Lkp_Values.CICL_LNG_NM,
	EXP_Lkp_Values.mplt_full_name_out AS FULL_NAME,
	EXP_Lkp_Values.ADR_TYP_CD,
	EXP_Lkp_Values.CICA_ADR,
	EXP_Lkp_Values.CICA_CIT_NM,
	EXP_Lkp_Values.CICA_CTY,
	EXP_Lkp_Values.ST_CD,
	EXP_Lkp_Values.CICA_PST_CD,
	EXP_Lkp_Values.citx_tax_id_ssn,
	EXP_Lkp_Values.citx_tax_id_fed,
	EXP_Lkp_Values.CICL_DOB_DT,
	EXP_Lkp_Values.GENDER_CD,
	EXP_Lkp_Values.Phone,
	EXP_Lkp_Values.Phone_Extn,
	EXP_Lkp_Values.Phone_Type,
	EXP_Lkp_Values.LEG_ENT_CD,
	EXP_Lkp_Values.claim_party_ref_eff_from_date,
	EXP_Lkp_Values.o_CIID_DTH_DT AS CIID_DTH_DT,
	LKP_Claim_Party.claim_party_id AS lkp_claim_party_id,
	LKP_Claim_Party.claim_party_ak_id AS lkp_claim_party_ak_id,
	LKP_Claim_Party.claim_party_full_name AS lkp_claim_party_full_name,
	LKP_Claim_Party.claim_party_first_name AS lkp_claim_party_first_name,
	LKP_Claim_Party.claim_party_last_name AS lkp_claim_party_last_name,
	LKP_Claim_Party.claim_party_mid_name AS lkp_claim_party_mid_name,
	LKP_Claim_Party.claim_party_name_prfx AS lkp_claim_party_name_prfx,
	LKP_Claim_Party.claim_party_name_sfx AS lkp_claim_party_name_sfx,
	LKP_Claim_Party.claim_party_addr AS lkp_claimant_addr,
	LKP_Claim_Party.claim_party_city AS lkp_claimant_city,
	LKP_Claim_Party.claim_party_county AS lkp_claimant_county,
	LKP_Claim_Party.claim_party_state AS lkp_claimant_state,
	LKP_Claim_Party.claim_party_zip AS lkp_claimant_zip,
	LKP_Claim_Party.addr_type AS lkp_addr_type,
	LKP_Claim_Party.tax_ssn_id AS lkp_tax_ssn_id,
	LKP_Claim_Party.tax_fed_id AS lkp_tax_fed_id,
	LKP_Claim_Party.claim_party_birthdate AS lkp_claim_party_birthdate,
	LKP_Claim_Party.claim_party_gndr AS lkp_claim_party_gndr,
	LKP_Claim_Party.ph_num AS lkp_ph_num,
	LKP_Claim_Party.ph_extension AS lkp_ph_extension,
	LKP_Claim_Party.ph_type AS lkp_ph_type,
	LKP_Claim_Party.lgl_ent_code AS lkp_lgl_ent_code,
	LKP_Claim_Party.claim_party_ref_eff_from_date AS lkp_claim_party_ref_eff_from_date,
	LKP_Claim_Party.claim_party_death_date AS lkp_claim_party_death_date,
	0 AS logical_flag,
	1 AS Crrnt_Snpsht_Flag,
	-- *INF*: iif(isnull(lkp_claim_party_id),'NEW',
	-- 	iif (
	-- 	(ltrim(rtrim(CICL_FST_NM)) <> ltrim(rtrim(lkp_claim_party_first_name))) or
	-- 	(ltrim(rtrim(CICL_LST_NM)) <> ltrim(rtrim(lkp_claim_party_last_name))) or
	-- 	(ltrim(rtrim(CICL_MDL_NM)) <> ltrim(rtrim(lkp_claim_party_mid_name))) or
	-- 	(ltrim(rtrim(NM_PFX)) <> ltrim(rtrim(lkp_claim_party_name_prfx))) or
	-- 	(ltrim(rtrim(NM_SFX)) <> ltrim(rtrim(lkp_claim_party_name_sfx))) or
	-- 	(ltrim(rtrim(CICA_ADR)) <> ltrim(rtrim(lkp_claimant_addr) )) or
	-- 	(ltrim(rtrim(CICA_CTY)) <> ltrim(rtrim(lkp_claimant_county) )) or
	-- 	(ltrim(rtrim(CICA_CIT_NM)) <>  ltrim(rtrim(lkp_claimant_city))) or
	-- 	(ltrim(rtrim(ST_CD)) <> ltrim(rtrim(lkp_claimant_state))) or
	-- 	(ltrim(rtrim(CICA_PST_CD)) <> ltrim(rtrim(lkp_claimant_zip))) or
	--       (ltrim(rtrim(citx_tax_id_ssn)) <>  ltrim(rtrim(lkp_tax_ssn_id))) or
	--       (ltrim(rtrim(citx_tax_id_fed)) <> ltrim(rtrim(lkp_tax_fed_id))) or
	--       (CICL_DOB_DT <>  lkp_claim_party_birthdate) or
	--       (ltrim(rtrim(GENDER_CD)) <> ltrim(rtrim(lkp_claim_party_gndr))) or
	--       (ltrim(rtrim(Phone)) <> ltrim(rtrim(lkp_ph_num))) or
	--       (ltrim(rtrim(Phone_Extn)) <> ltrim(rtrim(lkp_ph_extension))) or
	--       (ltrim(rtrim(Phone_Type)) <> ltrim(rtrim(lkp_ph_type))) or
	--       (ltrim(rtrim(LEG_ENT_CD)) <> ltrim(rtrim(lkp_lgl_ent_code))) or
	-- 	(ltrim(rtrim(ADR_TYP_CD)) <> ltrim(rtrim(lkp_addr_type)))  or
	-- 	claim_party_ref_eff_from_date <> lkp_claim_party_ref_eff_from_date
	-- or
	-- 	CIID_DTH_DT <> lkp_claim_party_death_date, 
	-- 	'UPDATE',
	-- 	'NOCHANGE'))
	IFF(lkp_claim_party_id IS NULL,
		'NEW',
		IFF(( ltrim(rtrim(CICL_FST_NM
					)
				) <> ltrim(rtrim(lkp_claim_party_first_name
					)
				) 
			) 
			OR ( ltrim(rtrim(CICL_LST_NM
					)
				) <> ltrim(rtrim(lkp_claim_party_last_name
					)
				) 
			) 
			OR ( ltrim(rtrim(CICL_MDL_NM
					)
				) <> ltrim(rtrim(lkp_claim_party_mid_name
					)
				) 
			) 
			OR ( ltrim(rtrim(NM_PFX
					)
				) <> ltrim(rtrim(lkp_claim_party_name_prfx
					)
				) 
			) 
			OR ( ltrim(rtrim(NM_SFX
					)
				) <> ltrim(rtrim(lkp_claim_party_name_sfx
					)
				) 
			) 
			OR ( ltrim(rtrim(CICA_ADR
					)
				) <> ltrim(rtrim(lkp_claimant_addr
					)
				) 
			) 
			OR ( ltrim(rtrim(CICA_CTY
					)
				) <> ltrim(rtrim(lkp_claimant_county
					)
				) 
			) 
			OR ( ltrim(rtrim(CICA_CIT_NM
					)
				) <> ltrim(rtrim(lkp_claimant_city
					)
				) 
			) 
			OR ( ltrim(rtrim(ST_CD
					)
				) <> ltrim(rtrim(lkp_claimant_state
					)
				) 
			) 
			OR ( ltrim(rtrim(CICA_PST_CD
					)
				) <> ltrim(rtrim(lkp_claimant_zip
					)
				) 
			) 
			OR ( ltrim(rtrim(citx_tax_id_ssn
					)
				) <> ltrim(rtrim(lkp_tax_ssn_id
					)
				) 
			) 
			OR ( ltrim(rtrim(citx_tax_id_fed
					)
				) <> ltrim(rtrim(lkp_tax_fed_id
					)
				) 
			) 
			OR ( CICL_DOB_DT <> lkp_claim_party_birthdate 
			) 
			OR ( ltrim(rtrim(GENDER_CD
					)
				) <> ltrim(rtrim(lkp_claim_party_gndr
					)
				) 
			) 
			OR ( ltrim(rtrim(Phone
					)
				) <> ltrim(rtrim(lkp_ph_num
					)
				) 
			) 
			OR ( ltrim(rtrim(Phone_Extn
					)
				) <> ltrim(rtrim(lkp_ph_extension
					)
				) 
			) 
			OR ( ltrim(rtrim(Phone_Type
					)
				) <> ltrim(rtrim(lkp_ph_type
					)
				) 
			) 
			OR ( ltrim(rtrim(LEG_ENT_CD
					)
				) <> ltrim(rtrim(lkp_lgl_ent_code
					)
				) 
			) 
			OR ( ltrim(rtrim(ADR_TYP_CD
					)
				) <> ltrim(rtrim(lkp_addr_type
					)
				) 
			) 
			OR claim_party_ref_eff_from_date <> lkp_claim_party_ref_eff_from_date 
			OR CIID_DTH_DT <> lkp_claim_party_death_date,
			'UPDATE',
			'NOCHANGE'
		)
	) AS v_Changed_Flag,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS Audit_Id,
	-- *INF*: IIF(v_Changed_Flag='NEW',
	-- 	TO_DATE('01/01/1800 01:00:00','MM/DD/YYYY HH24:MI:SS'),
	-- 	SYSDATE)
	IFF(v_Changed_Flag = 'NEW',
		TO_DATE('01/01/1800 01:00:00', 'MM/DD/YYYY HH24:MI:SS'
		),
		SYSDATE
	) AS Eff_From_Date,
	-- *INF*: TO_DATE('12/31/2100 23:59:59','MM/DD/YYYY HH24:MI:SS')
	TO_DATE('12/31/2100 23:59:59', 'MM/DD/YYYY HH24:MI:SS'
	) AS Eff_To_Date,
	v_Changed_Flag AS Changed_Flag,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS SOURCE_SYSTEM_ID,
	SYSDATE AS Created_Date,
	SYSDATE AS Modified_Date
	FROM EXP_Lkp_Values
	LEFT JOIN LKP_Claim_Party
	ON LKP_Claim_Party.claim_party_key = EXP_Lkp_Values.CLIENT_ID
),
FIL_Insert AS (
	SELECT
	lkp_claim_party_ak_id, 
	CLIENT_ID, 
	CICL_FST_NM, 
	CICL_LST_NM, 
	CICL_MDL_NM, 
	NM_PFX, 
	NM_SFX, 
	FULL_NAME, 
	ADR_TYP_CD, 
	CICA_ADR, 
	CICA_CIT_NM, 
	CICA_CTY, 
	ST_CD, 
	CICA_PST_CD, 
	citx_tax_id_ssn, 
	citx_tax_id_fed, 
	CICL_DOB_DT, 
	GENDER_CD, 
	logical_flag, 
	Crrnt_Snpsht_Flag, 
	Audit_Id, 
	Eff_From_Date, 
	Eff_To_Date, 
	SOURCE_SYSTEM_ID, 
	Created_Date, 
	Modified_Date, 
	Changed_Flag, 
	Phone, 
	Phone_Extn, 
	Phone_Type, 
	LEG_ENT_CD, 
	claim_party_ref_eff_from_date, 
	CIID_DTH_DT
	FROM EXP_Detect_Changes
	WHERE Changed_Flag='NEW'  OR Changed_Flag='UPDATE'
),
SEQ_claim_party AS (
	CREATE SEQUENCE SEQ_claim_party
	START = 0
	INCREMENT = 1;
),
EXP_Determine_AK AS (
	SELECT
	lkp_claim_party_ak_id,
	-- *INF*: IIF(Changed_Flag='NEW',
	-- NEXTVAL,
	-- lkp_claim_party_ak_id)
	IFF(Changed_Flag = 'NEW',
		NEXTVAL,
		lkp_claim_party_ak_id
	) AS claim_party_ak_id,
	CLIENT_ID,
	CICL_FST_NM,
	CICL_LST_NM,
	CICL_MDL_NM,
	NM_PFX,
	NM_SFX,
	FULL_NAME,
	ADR_TYP_CD,
	CICA_ADR,
	CICA_CIT_NM,
	CICA_CTY,
	ST_CD,
	CICA_PST_CD,
	citx_tax_id_ssn,
	citx_tax_id_fed,
	CICL_DOB_DT,
	GENDER_CD,
	logical_flag,
	Crrnt_Snpsht_Flag,
	Audit_Id,
	Eff_From_Date,
	Eff_To_Date,
	SOURCE_SYSTEM_ID,
	Created_Date,
	Modified_Date,
	Changed_Flag,
	Phone,
	Phone_Extn,
	Phone_Type,
	LEG_ENT_CD,
	claim_party_ref_eff_from_date,
	CIID_DTH_DT,
	SEQ_claim_party.NEXTVAL
	FROM FIL_Insert
),
claim_party_Insert AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.claim_party
	(claim_party_ak_id, claim_party_key, claim_party_full_name, claim_party_first_name, claim_party_last_name, claim_party_mid_name, claim_party_name_prfx, claim_party_name_sfx, claim_party_addr, claim_party_city, claim_party_county, claim_party_state, claim_party_zip, addr_type, tax_ssn_id, tax_fed_id, claim_party_birthdate, claim_party_gndr, logical_flag, crrnt_snpsht_flag, audit_id, eff_from_date, eff_to_date, source_sys_id, created_date, modified_date, ph_num, ph_extension, ph_type, lgl_ent_code, claim_party_ref_eff_from_date, claim_party_death_date)
	SELECT 
	CLAIM_PARTY_AK_ID, 
	CLIENT_ID AS CLAIM_PARTY_KEY, 
	FULL_NAME AS CLAIM_PARTY_FULL_NAME, 
	CICL_FST_NM AS CLAIM_PARTY_FIRST_NAME, 
	CICL_LST_NM AS CLAIM_PARTY_LAST_NAME, 
	CICL_MDL_NM AS CLAIM_PARTY_MID_NAME, 
	NM_PFX AS CLAIM_PARTY_NAME_PRFX, 
	NM_SFX AS CLAIM_PARTY_NAME_SFX, 
	CICA_ADR AS CLAIM_PARTY_ADDR, 
	CICA_CIT_NM AS CLAIM_PARTY_CITY, 
	CICA_CTY AS CLAIM_PARTY_COUNTY, 
	ST_CD AS CLAIM_PARTY_STATE, 
	CICA_PST_CD AS CLAIM_PARTY_ZIP, 
	ADR_TYP_CD AS ADDR_TYPE, 
	citx_tax_id_ssn AS TAX_SSN_ID, 
	citx_tax_id_fed AS TAX_FED_ID, 
	CICL_DOB_DT AS CLAIM_PARTY_BIRTHDATE, 
	GENDER_CD AS CLAIM_PARTY_GNDR, 
	LOGICAL_FLAG, 
	Crrnt_Snpsht_Flag AS CRRNT_SNPSHT_FLAG, 
	Audit_Id AS AUDIT_ID, 
	Eff_From_Date AS EFF_FROM_DATE, 
	Eff_To_Date AS EFF_TO_DATE, 
	SOURCE_SYSTEM_ID AS SOURCE_SYS_ID, 
	Created_Date AS CREATED_DATE, 
	Modified_Date AS MODIFIED_DATE, 
	Phone AS PH_NUM, 
	Phone_Extn AS PH_EXTENSION, 
	Phone_Type AS PH_TYPE, 
	LEG_ENT_CD AS LGL_ENT_CODE, 
	CLAIM_PARTY_REF_EFF_FROM_DATE, 
	CIID_DTH_DT AS CLAIM_PARTY_DEATH_DATE
	FROM EXP_Determine_AK
),
SQ_claim_party AS (
	SELECT 
	a.claim_party_id, 
	a.claim_party_key, 
	a.eff_from_date, 
	a.eff_to_date 
	FROM
	 @{pipeline().parameters.TARGET_TABLE_OWNER}.claim_party a
	WHERE 
	 a.source_sys_id = '@{pipeline().parameters.SOURCE_SYSTEM_ID}' and
	 EXISTS(SELECT 1			
			FROM  @{pipeline().parameters.TARGET_TABLE_OWNER}.claim_party b
			WHERE source_sys_id = '@{pipeline().parameters.SOURCE_SYSTEM_ID}'  AND crrnt_snpsht_flag = 1
			AND a.claim_party_key = b.claim_party_key
			GROUP BY claim_party_key
			HAVING COUNT(*) > 1)
	ORDER BY claim_party_key, eff_from_date  DESC--
),
EXP_Lag_eff_from_date AS (
	SELECT
	claim_party_id,
	claim_party_key,
	eff_from_date,
	eff_to_date AS orig_eff_to_date,
	-- *INF*: DECODE(TRUE,
	-- 	claim_party_key = v_PREV_ROW_party_key, ADD_TO_DATE(v_PREV_ROW_eff_from_date,'SS',-1),
	-- 	orig_eff_to_date)
	DECODE(TRUE,
		claim_party_key = v_PREV_ROW_party_key, DATEADD(SECOND,- 1,v_PREV_ROW_eff_from_date),
		orig_eff_to_date
	) AS v_eff_to_date,
	v_eff_to_date AS eff_to_date,
	eff_from_date AS v_PREV_ROW_eff_from_date,
	claim_party_key AS v_PREV_ROW_party_key,
	SYSDATE AS modified_date,
	0 AS crrnt_snpsht_flag
	FROM SQ_claim_party
),
FIL_FirstRowInAKGroup AS (
	SELECT
	claim_party_id, 
	orig_eff_to_date, 
	eff_to_date, 
	modified_date, 
	crrnt_snpsht_flag
	FROM EXP_Lag_eff_from_date
	WHERE orig_eff_to_date <> eff_to_date

--If these two dates equal each other we are dealing with the first row in an AK group.  This row
--does not need to be expired or updated for any reason thus it can be filtered out
-- but we must source it to capture the eff_from_date of this row 
--so that we can properly expire the subsequent row
),
UPD_Claim_Party AS (
	SELECT
	claim_party_id, 
	eff_to_date, 
	modified_date, 
	crrnt_snpsht_flag
	FROM FIL_FirstRowInAKGroup
),
claim_party_Update AS (
	MERGE INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.claim_party AS T
	USING UPD_Claim_Party AS S
	ON T.claim_party_id = S.claim_party_id
	WHEN MATCHED BY TARGET THEN
	UPDATE SET T.crrnt_snpsht_flag = S.crrnt_snpsht_flag, T.eff_to_date = S.eff_to_date, T.modified_date = S.modified_date
),