WITH
SQ_loss_master_fact_CurrentRunMonth AS (
	SELECT LMF.loss_master_fact_id,
	LMF.audit_id,
	LMF.edw_loss_master_calculation_pk_id,
	LMF.edw_claim_trans_pk_id,
	LMF.edw_claim_reins_trans_pk_id,
	LMF.wc_stage_loss_master_pk_id,
	LMF.loss_master_dim_id,
	LMF.claim_occurrence_dim_id,
	LMF.claimant_dim_id,
	LMF.claimant_cov_dim_id,
	LMF.cov_dim_id,
	LMF.claim_trans_type_dim_id,
	LMF.reins_cov_dim_id,
	LMF.claim_rep_dim_prim_claim_rep_id,
	LMF.claim_rep_dim_examiner_id,
	LMF.pol_dim_id,
	LMF.contract_cust_dim_id,
	LMF.agency_dim_id,
	LMF.claim_pay_dim_id,
	LMF.claim_pay_ctgry_type_dim_id,
	LMF.claim_case_dim_id,
	LMF.claim_trans_date_id,
	LMF.pol_eff_date_id,
	LMF.pol_exp_date_id,
	LMF.source_claim_rpted_date_id,
	LMF.claim_rpted_date_id,
	LMF.claim_loss_date_id,
	LMF.incptn_date_id,
	LMF.loss_master_run_date_id,
	LMF.claim_trans_amt,
	LMF.claim_trans_hist_amt,
	LMF.new_claim_count,
	LMF.outstanding_amt,
	LMF.paid_loss_amt,
	LMF.paid_exp_amt,
	LMF.eom_unpaid_loss_adjust_exp,
	LMF.orig_reserve,
	LMF.orig_reserve_extract,
	LMF.asl_dim_id,
	LMF.asl_prdct_code_dim_id,
	LMF.strtgc_bus_dvsn_dim_id,
	LMF.prdct_code_dim_id,
	LMF.InsuranceReferenceDimId,
	LMF.AgencyDimId,
	LMF.SalesDivisionDimId,
	LMF.InsuranceReferenceCoverageDimId,
	LMF.CoverageDetailDimId,
	CO.edw_claim_occurrence_ak_id,
	CC.edw_claimant_cov_det_ak_id,
	RC.edw_reins_cov_ak_id,
	C.clndr_date AS LossMasterRundate,
	case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end pms_trans_code,
	LMF.claimfinancialtypedimid,
	CTT.TRANS_KIND_CODE,
	CO.claim_loss_date,
	P.pol_key,
	CO.claim_cat_code
	FROM
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.loss_master_fact LMF,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claim_transaction_type_dim CTT,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.calendar_dim C,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claim_occurrence_dim CO,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claimant_coverage_dim CC,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.reinsurance_coverage_dim RC,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.Policy_Dim P
	where LMF.claim_trans_type_dim_id=CTT.claim_trans_type_dim_id
	and LMF.loss_master_run_date_id=C.clndr_id
	and LMF.claim_occurrence_dim_id=CO.claim_occurrence_dim_id
	and LMF.claimant_cov_dim_id=CC.claimant_cov_dim_id
	and CTT.pms_trans_code in ('90','92','95','97','98','99')
	and LMF.reins_cov_dim_id=RC.reins_cov_dim_id
	and LMF.pol_dim_id=P.pol_dim_id
	and C.clndr_date=dateadd(DD,-1,dateadd(MM,DATEDIFF(mm,0,getdate())-(@{pipeline().parameters.NO_OF_MONTHS_CR}),0))
	@{pipeline().parameters.WHERE_CLAUSE}
	order by CO.edw_claim_occurrence_ak_id,CC.edw_claimant_cov_det_ak_id,RC.edw_reins_cov_ak_id,C.clndr_date,case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end
),
SQ_loss_master_fact_PreviousRunMonth AS (
	SELECT LMF.loss_master_fact_id,
	LMF.audit_id,
	LMF.edw_loss_master_calculation_pk_id,
	LMF.edw_claim_trans_pk_id,
	LMF.edw_claim_reins_trans_pk_id,
	LMF.wc_stage_loss_master_pk_id,
	LMF.loss_master_dim_id,
	LMF.claim_occurrence_dim_id,
	LMF.claimant_dim_id,
	LMF.claimant_cov_dim_id,
	LMF.cov_dim_id,
	LMF.claim_trans_type_dim_id,
	LMF.reins_cov_dim_id,
	LMF.claim_rep_dim_prim_claim_rep_id,
	LMF.claim_rep_dim_examiner_id,
	LMF.pol_dim_id,
	LMF.contract_cust_dim_id,
	LMF.agency_dim_id,
	LMF.claim_pay_dim_id,
	LMF.claim_pay_ctgry_type_dim_id,
	LMF.claim_case_dim_id,
	LMF.claim_trans_date_id,
	LMF.pol_eff_date_id,
	LMF.pol_exp_date_id,
	LMF.source_claim_rpted_date_id,
	LMF.claim_rpted_date_id,
	LMF.claim_loss_date_id,
	LMF.incptn_date_id,
	LMF.loss_master_run_date_id,
	LMF.claim_trans_amt,
	LMF.claim_trans_hist_amt,
	LMF.new_claim_count,
	LMF.outstanding_amt,
	LMF.paid_loss_amt,
	LMF.paid_exp_amt,
	LMF.eom_unpaid_loss_adjust_exp,
	LMF.orig_reserve,
	LMF.orig_reserve_extract,
	LMF.asl_dim_id,
	LMF.asl_prdct_code_dim_id,
	LMF.strtgc_bus_dvsn_dim_id,
	LMF.prdct_code_dim_id,
	LMF.InsuranceReferenceDimId,
	LMF.AgencyDimId,
	LMF.SalesDivisionDimId,
	LMF.InsuranceReferenceCoverageDimId,
	LMF.CoverageDetailDimId,
	CO.edw_claim_occurrence_ak_id,
	CC.edw_claimant_cov_det_ak_id,
	RC.edw_reins_cov_ak_id,
	C.clndr_date AS LossMasterRundate,
	case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end pms_trans_code,
	LMF.claimfinancialtypedimid,
	CTT.TRANS_KIND_CODE,
	CO.claim_loss_date,
	P.pol_key,
	CO.claim_cat_code
	FROM
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.loss_master_fact LMF,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claim_transaction_type_dim CTT,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.calendar_dim C,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claim_occurrence_dim CO,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.claimant_coverage_dim CC,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.reinsurance_coverage_dim RC,
	@{pipeline().parameters.SOURCE_DATABASE_NAME}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.Policy_Dim P
	where LMF.claim_trans_type_dim_id=CTT.claim_trans_type_dim_id
	and LMF.loss_master_run_date_id=C.clndr_id
	and LMF.claim_occurrence_dim_id=CO.claim_occurrence_dim_id
	and LMF.claimant_cov_dim_id=CC.claimant_cov_dim_id
	and CTT.pms_trans_code in ('90','92','95','97','98','99')
	and LMF.reins_cov_dim_id=RC.reins_cov_dim_id
	and LMF.pol_dim_id=P.pol_dim_id
	and C.clndr_date=dateadd(DD,-1,dateadd(MM,DATEDIFF(mm,0,getdate())-(@{pipeline().parameters.NO_OF_MONTHS_PR}),0))
	and LMF.Audit_Id not in (-1000,-9)
	@{pipeline().parameters.WHERE_CLAUSE}
	order by CO.edw_claim_occurrence_ak_id,CC.edw_claimant_cov_det_ak_id,RC.edw_reins_cov_ak_id,C.clndr_date,case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end
),
JNR_Current_Previous AS (SELECT
	SQ_loss_master_fact_CurrentRunMonth.loss_master_fact_id AS CR_loss_master_fact_id, 
	SQ_loss_master_fact_CurrentRunMonth.audit_id AS CR_audit_id, 
	SQ_loss_master_fact_CurrentRunMonth.edw_loss_master_calculation_pk_id AS CR_edw_loss_master_calculation_pk_id, 
	SQ_loss_master_fact_CurrentRunMonth.edw_claim_trans_pk_id AS CR_edw_claim_trans_pk_id, 
	SQ_loss_master_fact_CurrentRunMonth.edw_claim_reins_trans_pk_id AS CR_edw_claim_reins_trans_pk_id, 
	SQ_loss_master_fact_CurrentRunMonth.wc_stage_loss_master_pk_id AS CR_wc_stage_loss_master_pk_id, 
	SQ_loss_master_fact_CurrentRunMonth.loss_master_dim_id AS CR_loss_master_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_occurrence_dim_id AS CR_claim_occurrence_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claimant_dim_id AS CR_claimant_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claimant_cov_dim_id AS CR_claimant_cov_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.cov_dim_id AS CR_cov_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_trans_type_dim_id AS CR_claim_trans_type_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.reins_cov_dim_id AS CR_reins_cov_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_rep_dim_prim_claim_rep_id AS CR_claim_rep_dim_prim_claim_rep_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_rep_dim_examiner_id AS CR_claim_rep_dim_examiner_id, 
	SQ_loss_master_fact_CurrentRunMonth.pol_dim_id AS CR_pol_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.contract_cust_dim_id AS CR_contract_cust_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.agency_dim_id AS CR_agency_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_pay_dim_id AS CR_claim_pay_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_pay_ctgry_type_dim_id AS CR_claim_pay_ctgry_type_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_case_dim_id AS CR_claim_case_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_trans_date_id AS CR_claim_trans_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.pol_eff_date_id AS CR_pol_eff_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.pol_exp_date_id AS CR_pol_exp_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.source_claim_rpted_date_id AS CR_source_claim_rpted_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_rpted_date_id AS CR_claim_rpted_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_loss_date_id AS CR_claim_loss_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.incptn_date_id AS CR_incptn_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.loss_master_run_date_id AS CR_loss_master_run_date_id, 
	SQ_loss_master_fact_CurrentRunMonth.claim_trans_amt AS CR_claim_trans_amt, 
	SQ_loss_master_fact_CurrentRunMonth.claim_trans_hist_amt AS CR_claim_trans_hist_amt, 
	SQ_loss_master_fact_CurrentRunMonth.new_claim_count AS CR_new_claim_count, 
	SQ_loss_master_fact_CurrentRunMonth.outstanding_amt AS CR_outstanding_amt, 
	SQ_loss_master_fact_CurrentRunMonth.paid_loss_amt AS CR_paid_loss_amt, 
	SQ_loss_master_fact_CurrentRunMonth.paid_exp_amt AS CR_paid_exp_amt, 
	SQ_loss_master_fact_CurrentRunMonth.eom_unpaid_loss_adjust_exp AS CR_eom_unpaid_loss_adjust_exp, 
	SQ_loss_master_fact_CurrentRunMonth.orig_reserve AS CR_orig_reserve, 
	SQ_loss_master_fact_CurrentRunMonth.orig_reserve_extract AS CR_orig_reserve_extract, 
	SQ_loss_master_fact_CurrentRunMonth.asl_dim_id AS CR_asl_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.asl_prdct_code_dim_id AS CR_asl_prdct_code_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.strtgc_bus_dvsn_dim_id AS CR_strtgc_bus_dvsn_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.prdct_code_dim_id AS CR_prdct_code_dim_id, 
	SQ_loss_master_fact_CurrentRunMonth.InsuranceReferenceDimId AS CR_InsuranceReferenceDimId, 
	SQ_loss_master_fact_CurrentRunMonth.AgencyDimId AS CR_AgencyDimId, 
	SQ_loss_master_fact_CurrentRunMonth.SalesDivisionDimId AS CR_SalesDivisionDimId, 
	SQ_loss_master_fact_CurrentRunMonth.InsuranceReferenceCoverageDimId AS CR_InsuranceReferenceCoverageDimId, 
	SQ_loss_master_fact_CurrentRunMonth.CoverageDetailDimId AS CR_CoverageDetailDimId, 
	SQ_loss_master_fact_CurrentRunMonth.edw_claim_occurrence_ak_id AS CR_edw_claim_occurrence_ak_id, 
	SQ_loss_master_fact_CurrentRunMonth.edw_claimant_cov_det_ak_id AS CR_edw_claimant_cov_det_ak_id, 
	SQ_loss_master_fact_CurrentRunMonth.edw_reins_cov_ak_id AS CR_edw_reins_cov_ak_id, 
	SQ_loss_master_fact_CurrentRunMonth.LossMasterRundate AS CR_LossMasterRundate, 
	SQ_loss_master_fact_CurrentRunMonth.pms_trans_code AS CR_pms_trans_code, 
	SQ_loss_master_fact_CurrentRunMonth.claimfinancialtypedimid AS CR_claimfinancialtypedimid, 
	SQ_loss_master_fact_CurrentRunMonth.trans_kind_code AS CR_Trans_kind_code, 
	SQ_loss_master_fact_CurrentRunMonth.claim_loss_date AS CR_Claim_Loss_date, 
	SQ_loss_master_fact_CurrentRunMonth.pol_key AS CR_Pol_key, 
	SQ_loss_master_fact_CurrentRunMonth.claim_cat_code AS CR_claim_cat_code, 
	SQ_loss_master_fact_PreviousRunMonth.loss_master_fact_id AS PR_loss_master_fact_id, 
	SQ_loss_master_fact_PreviousRunMonth.audit_id AS PR_audit_id, 
	SQ_loss_master_fact_PreviousRunMonth.edw_loss_master_calculation_pk_id AS PR_edw_loss_master_calculation_pk_id, 
	SQ_loss_master_fact_PreviousRunMonth.edw_claim_trans_pk_id AS PR_edw_claim_trans_pk_id, 
	SQ_loss_master_fact_PreviousRunMonth.edw_claim_reins_trans_pk_id AS PR_edw_claim_reins_trans_pk_id, 
	SQ_loss_master_fact_PreviousRunMonth.wc_stage_loss_master_pk_id AS PR_wc_stage_loss_master_pk_id, 
	SQ_loss_master_fact_PreviousRunMonth.loss_master_dim_id AS PR_loss_master_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_occurrence_dim_id AS PR_claim_occurrence_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claimant_dim_id AS PR_claimant_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claimant_cov_dim_id AS PR_claimant_cov_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.cov_dim_id AS PR_cov_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_trans_type_dim_id AS PR_claim_trans_type_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.reins_cov_dim_id AS PR_reins_cov_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_rep_dim_prim_claim_rep_id AS PR_claim_rep_dim_prim_claim_rep_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_rep_dim_examiner_id AS PR_claim_rep_dim_examiner_id, 
	SQ_loss_master_fact_PreviousRunMonth.pol_dim_id AS PR_pol_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.contract_cust_dim_id AS PR_contract_cust_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.agency_dim_id AS PR_agency_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_pay_dim_id AS PR_claim_pay_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_pay_ctgry_type_dim_id AS PR_claim_pay_ctgry_type_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_case_dim_id AS PR_claim_case_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_trans_date_id AS PR_claim_trans_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.pol_eff_date_id AS PR_pol_eff_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.pol_exp_date_id AS PR_pol_exp_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.source_claim_rpted_date_id AS PR_source_claim_rpted_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_rpted_date_id AS PR_claim_rpted_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_loss_date_id AS PR_claim_loss_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.incptn_date_id AS PR_incptn_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.loss_master_run_date_id AS PR_loss_master_run_date_id, 
	SQ_loss_master_fact_PreviousRunMonth.claim_trans_amt AS PR_claim_trans_amt, 
	SQ_loss_master_fact_PreviousRunMonth.claim_trans_hist_amt AS PR_claim_trans_hist_amt, 
	SQ_loss_master_fact_PreviousRunMonth.new_claim_count AS PR_new_claim_count, 
	SQ_loss_master_fact_PreviousRunMonth.outstanding_amt AS PR_outstanding_amt, 
	SQ_loss_master_fact_PreviousRunMonth.paid_loss_amt AS PR_paid_loss_amt, 
	SQ_loss_master_fact_PreviousRunMonth.paid_exp_amt AS PR_paid_exp_amt, 
	SQ_loss_master_fact_PreviousRunMonth.eom_unpaid_loss_adjust_exp AS PR_eom_unpaid_loss_adjust_exp, 
	SQ_loss_master_fact_PreviousRunMonth.orig_reserve AS PR_orig_reserve, 
	SQ_loss_master_fact_PreviousRunMonth.orig_reserve_extract AS PR_orig_reserve_extract, 
	SQ_loss_master_fact_PreviousRunMonth.asl_dim_id AS PR_asl_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.asl_prdct_code_dim_id AS PR_asl_prdct_code_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.strtgc_bus_dvsn_dim_id AS PR_strtgc_bus_dvsn_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.prdct_code_dim_id AS PR_prdct_code_dim_id, 
	SQ_loss_master_fact_PreviousRunMonth.InsuranceReferenceDimId AS PR_InsuranceReferenceDimId, 
	SQ_loss_master_fact_PreviousRunMonth.AgencyDimId AS PR_AgencyDimId, 
	SQ_loss_master_fact_PreviousRunMonth.SalesDivisionDimId AS PR_SalesDivisionDimId, 
	SQ_loss_master_fact_PreviousRunMonth.InsuranceReferenceCoverageDimId AS PR_InsuranceReferenceCoverageDimId, 
	SQ_loss_master_fact_PreviousRunMonth.CoverageDetailDimId AS PR_CoverageDetailDimId, 
	SQ_loss_master_fact_PreviousRunMonth.edw_claim_occurrence_ak_id AS PR_edw_claim_occurrence_ak_id, 
	SQ_loss_master_fact_PreviousRunMonth.edw_claimant_cov_det_ak_id AS PR_edw_claimant_cov_det_ak_id, 
	SQ_loss_master_fact_PreviousRunMonth.edw_reins_cov_ak_id AS PR_edw_reins_cov_ak_id, 
	SQ_loss_master_fact_PreviousRunMonth.LossMasterRundate AS PR_LossMasterRundate, 
	SQ_loss_master_fact_PreviousRunMonth.pms_trans_code AS PR_pms_trans_code, 
	SQ_loss_master_fact_PreviousRunMonth.claimfinancialtypedimid AS PR_claimfinancialtypedimid, 
	SQ_loss_master_fact_PreviousRunMonth.trans_kind_code AS PR_Trans_Kind_code, 
	SQ_loss_master_fact_PreviousRunMonth.claim_loss_date AS PR_Claim_Loss_date, 
	SQ_loss_master_fact_PreviousRunMonth.pol_key AS PR_Pol_key, 
	SQ_loss_master_fact_PreviousRunMonth.claim_cat_code AS PR_claim_cat_code
	FROM SQ_loss_master_fact_CurrentRunMonth
	FULL OUTER JOIN SQ_loss_master_fact_PreviousRunMonth
	ON SQ_loss_master_fact_PreviousRunMonth.edw_claim_occurrence_ak_id = SQ_loss_master_fact_CurrentRunMonth.edw_claim_occurrence_ak_id AND SQ_loss_master_fact_PreviousRunMonth.edw_claimant_cov_det_ak_id = SQ_loss_master_fact_CurrentRunMonth.edw_claimant_cov_det_ak_id AND SQ_loss_master_fact_PreviousRunMonth.edw_reins_cov_ak_id = SQ_loss_master_fact_CurrentRunMonth.edw_reins_cov_ak_id AND SQ_loss_master_fact_PreviousRunMonth.pms_trans_code = SQ_loss_master_fact_CurrentRunMonth.pms_trans_code AND SQ_loss_master_fact_PreviousRunMonth.trans_kind_code = SQ_loss_master_fact_CurrentRunMonth.trans_kind_code AND SQ_loss_master_fact_PreviousRunMonth.claim_loss_date = SQ_loss_master_fact_CurrentRunMonth.claim_loss_date AND SQ_loss_master_fact_PreviousRunMonth.pol_key = SQ_loss_master_fact_CurrentRunMonth.pol_key AND SQ_loss_master_fact_PreviousRunMonth.claim_cat_code = SQ_loss_master_fact_CurrentRunMonth.claim_cat_code
),
RTR_Split_Current_Previous AS (
	SELECT
	CR_loss_master_fact_id,
	CR_audit_id,
	CR_edw_loss_master_calculation_pk_id,
	CR_edw_claim_trans_pk_id,
	CR_edw_claim_reins_trans_pk_id,
	CR_wc_stage_loss_master_pk_id,
	CR_loss_master_dim_id,
	CR_claim_occurrence_dim_id,
	CR_claimant_dim_id,
	CR_claimant_cov_dim_id,
	CR_cov_dim_id,
	CR_claim_trans_type_dim_id,
	CR_reins_cov_dim_id,
	CR_claim_rep_dim_prim_claim_rep_id,
	CR_claim_rep_dim_examiner_id,
	CR_pol_dim_id,
	CR_contract_cust_dim_id,
	CR_agency_dim_id,
	CR_claim_pay_dim_id,
	CR_claim_pay_ctgry_type_dim_id,
	CR_claim_case_dim_id,
	CR_claim_trans_date_id,
	CR_pol_eff_date_id,
	CR_pol_exp_date_id,
	CR_source_claim_rpted_date_id,
	CR_claim_rpted_date_id,
	CR_claim_loss_date_id,
	CR_incptn_date_id,
	CR_loss_master_run_date_id,
	CR_claim_trans_amt,
	CR_claim_trans_hist_amt,
	CR_new_claim_count,
	CR_outstanding_amt,
	CR_paid_loss_amt,
	CR_paid_exp_amt,
	CR_eom_unpaid_loss_adjust_exp,
	CR_orig_reserve,
	CR_orig_reserve_extract,
	CR_asl_dim_id,
	CR_asl_prdct_code_dim_id,
	CR_strtgc_bus_dvsn_dim_id,
	CR_prdct_code_dim_id,
	CR_InsuranceReferenceDimId,
	CR_AgencyDimId,
	CR_SalesDivisionDimId,
	CR_InsuranceReferenceCoverageDimId,
	CR_CoverageDetailDimId,
	CR_edw_claim_occurrence_ak_id,
	CR_edw_claimant_cov_det_ak_id,
	CR_edw_reins_cov_ak_id,
	CR_LossMasterRundate,
	CR_pms_trans_code,
	CR_claimfinancialtypedimid,
	PR_loss_master_fact_id,
	PR_audit_id,
	PR_edw_loss_master_calculation_pk_id,
	PR_edw_claim_trans_pk_id,
	PR_edw_claim_reins_trans_pk_id,
	PR_wc_stage_loss_master_pk_id,
	PR_loss_master_dim_id,
	PR_claim_occurrence_dim_id,
	PR_claimant_dim_id,
	PR_claimant_cov_dim_id,
	PR_cov_dim_id,
	PR_claim_trans_type_dim_id,
	PR_reins_cov_dim_id,
	PR_claim_rep_dim_prim_claim_rep_id,
	PR_claim_rep_dim_examiner_id,
	PR_pol_dim_id,
	PR_contract_cust_dim_id,
	PR_agency_dim_id,
	PR_claim_pay_dim_id,
	PR_claim_pay_ctgry_type_dim_id,
	PR_claim_case_dim_id,
	PR_claim_trans_date_id,
	PR_pol_eff_date_id,
	PR_pol_exp_date_id,
	PR_source_claim_rpted_date_id,
	PR_claim_rpted_date_id,
	PR_claim_loss_date_id,
	PR_incptn_date_id,
	PR_loss_master_run_date_id,
	PR_claim_trans_amt,
	PR_claim_trans_hist_amt,
	PR_new_claim_count,
	PR_outstanding_amt,
	PR_paid_loss_amt,
	PR_paid_exp_amt,
	PR_eom_unpaid_loss_adjust_exp,
	PR_orig_reserve,
	PR_orig_reserve_extract,
	PR_asl_dim_id,
	PR_asl_prdct_code_dim_id,
	PR_strtgc_bus_dvsn_dim_id,
	PR_prdct_code_dim_id,
	PR_InsuranceReferenceDimId,
	PR_AgencyDimId,
	PR_SalesDivisionDimId,
	PR_InsuranceReferenceCoverageDimId,
	PR_CoverageDetailDimId,
	PR_edw_claim_occurrence_ak_id,
	PR_edw_claimant_cov_det_ak_id,
	PR_edw_reins_cov_ak_id,
	PR_LossMasterRundate,
	PR_pms_trans_code,
	PR_claimfinancialtypedimid,
	PR_Trans_Kind_code,
	PR_Claim_Loss_date,
	PR_Pol_key,
	PR_claim_cat_code
	FROM JNR_Current_Previous
),
RTR_Split_Current_Previous_Current_Month AS (SELECT * FROM RTR_Split_Current_Previous WHERE ISNULL(PR_loss_master_fact_id) AND (NOT ISNULL(CR_loss_master_fact_id))),
RTR_Split_Current_Previous_Previous_Month AS (SELECT * FROM RTR_Split_Current_Previous WHERE ISNULL(CR_loss_master_fact_id) AND (NOT ISNULL(PR_loss_master_fact_id))),
RTR_Split_Current_Previous_Current_Previous_Month AS (SELECT * FROM RTR_Split_Current_Previous WHERE (NOT ISNULL(CR_loss_master_fact_id)) AND (NOT ISNULL(PR_loss_master_fact_id))),
Exp_CurrentMonth AS (
	SELECT
	CR_loss_master_fact_id AS CR_loss_master_fact_id1,
	CR_outstanding_amt AS CR_outstanding_amt1,
	CR_eom_unpaid_loss_adjust_exp AS CR_eom_unpaid_loss_adjust_exp1
	FROM RTR_Split_Current_Previous_Current_Month
),
UPD_Current_ChangeAmt AS (
	SELECT
	CR_loss_master_fact_id1, 
	CR_outstanding_amt1, 
	CR_eom_unpaid_loss_adjust_exp1
	FROM Exp_CurrentMonth
),
loss_master_fact_Update_NewReserve AS (
	MERGE INTO @{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.loss_master_fact AS T
	USING UPD_Current_ChangeAmt AS S
	ON T.loss_master_fact_id = S.CR_loss_master_fact_id1
	WHEN MATCHED BY TARGET THEN
	UPDATE SET T.ChangeInOutstandingAmount = S.CR_outstanding_amt1, T.ChangeInEOMUnpaidLossAdjustmentExpense = S.CR_eom_unpaid_loss_adjust_exp1
),
Exp_PreviousMonth AS (
	SELECT
	PR_audit_id AS PR_audit_id3,
	PR_edw_loss_master_calculation_pk_id AS PR_edw_loss_master_calculation_pk_id3,
	PR_edw_claim_trans_pk_id AS PR_edw_claim_trans_pk_id3,
	PR_edw_claim_reins_trans_pk_id AS PR_edw_claim_reins_trans_pk_id3,
	PR_wc_stage_loss_master_pk_id AS PR_wc_stage_loss_master_pk_id3,
	PR_loss_master_dim_id AS PR_loss_master_dim_id3,
	PR_claim_occurrence_dim_id AS PR_claim_occurrence_dim_id3,
	PR_claimant_dim_id AS PR_claimant_dim_id3,
	PR_claimant_cov_dim_id AS PR_claimant_cov_dim_id3,
	PR_cov_dim_id AS PR_cov_dim_id3,
	PR_claim_trans_type_dim_id AS PR_claim_trans_type_dim_id3,
	PR_reins_cov_dim_id AS PR_reins_cov_dim_id3,
	PR_claim_rep_dim_prim_claim_rep_id AS PR_claim_rep_dim_prim_claim_rep_id3,
	PR_claim_rep_dim_examiner_id AS PR_claim_rep_dim_examiner_id3,
	PR_pol_dim_id AS PR_pol_dim_id3,
	PR_contract_cust_dim_id AS PR_contract_cust_dim_id3,
	PR_agency_dim_id AS PR_agency_dim_id3,
	PR_claim_pay_dim_id AS PR_claim_pay_dim_id3,
	PR_claim_pay_ctgry_type_dim_id AS PR_claim_pay_ctgry_type_dim_id3,
	PR_claim_case_dim_id AS PR_claim_case_dim_id3,
	PR_claim_trans_date_id AS PR_claim_trans_date_id3,
	PR_pol_eff_date_id AS PR_pol_eff_date_id3,
	PR_pol_exp_date_id AS PR_pol_exp_date_id3,
	PR_source_claim_rpted_date_id AS PR_source_claim_rpted_date_id3,
	PR_claim_rpted_date_id AS PR_claim_rpted_date_id3,
	PR_claim_loss_date_id AS PR_claim_loss_date_id3,
	PR_incptn_date_id AS PR_incptn_date_id3,
	PR_loss_master_run_date_id AS PR_loss_master_run_date_id3,
	PR_claim_trans_amt AS PR_claim_trans_amt3,
	PR_claim_trans_hist_amt AS PR_claim_trans_hist_amt3,
	PR_new_claim_count AS PR_new_claim_count3,
	PR_outstanding_amt AS PR_outstanding_amt3,
	PR_paid_loss_amt AS PR_paid_loss_amt3,
	PR_paid_exp_amt AS PR_paid_exp_amt3,
	PR_eom_unpaid_loss_adjust_exp AS PR_eom_unpaid_loss_adjust_exp3,
	PR_orig_reserve AS PR_orig_reserve3,
	PR_orig_reserve_extract AS PR_orig_reserve_extract3,
	PR_asl_dim_id AS PR_asl_dim_id3,
	PR_asl_prdct_code_dim_id AS PR_asl_prdct_code_dim_id3,
	PR_strtgc_bus_dvsn_dim_id AS PR_strtgc_bus_dvsn_dim_id3,
	PR_prdct_code_dim_id AS PR_prdct_code_dim_id3,
	PR_InsuranceReferenceDimId AS PR_InsuranceReferenceDimId3,
	PR_AgencyDimId AS PR_AgencyDimId3,
	PR_SalesDivisionDimId AS PR_SalesDivisionDimId3,
	PR_InsuranceReferenceCoverageDimId AS PR_InsuranceReferenceCoverageDimId3,
	PR_CoverageDetailDimId AS PR_CoverageDetailDimId3,
	PR_edw_claim_occurrence_ak_id AS PR_edw_claim_occurrence_ak_id3,
	PR_edw_claimant_cov_det_ak_id AS PR_edw_claimant_cov_det_ak_id3,
	PR_edw_reins_cov_ak_id AS PR_edw_reins_cov_ak_id3,
	PR_LossMasterRundate AS PR_LossMasterRundate3,
	-- *INF*: LAST_DAY(ADD_TO_DATE(PR_LossMasterRundate3,'MM',1))
	LAST_DAY(DATEADD(MONTH,1,PR_LossMasterRundate3)) AS Out_LossMasterRundate,
	PR_pms_trans_code AS PR_pms_trans_code3,
	-- *INF*: IIF(PR_pms_trans_code3='92','90',PR_pms_trans_code3)
	IFF(PR_pms_trans_code3 = '92', '90', PR_pms_trans_code3) AS Out_PR_pms_trans_code,
	PR_claimfinancialtypedimid AS PR_claimfinancialtypedimid3,
	PR_Trans_Kind_code AS PR_Trans_Kind_code3,
	PR_Claim_Loss_date AS PR_Claim_Loss_date3,
	PR_Pol_key AS PR_Pol_key3,
	PR_claim_cat_code AS PR_claim_cat_code3
	FROM RTR_Split_Current_Previous_Previous_Month
),
LKP_calender_dim AS (
	SELECT
	clndr_id,
	clndr_date
	FROM (
		SELECT 
			clndr_id,
			clndr_date
		FROM calendar_dim
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY clndr_date ORDER BY clndr_id) = 1
),
Lkp_Get_FinalAmtForBalance AS (
	SELECT
	ChangeinOutStandingAmount,
	ChangeInEomUnpaidLossAdjustExp,
	PR_Claim_Loss_date,
	PR_Pol_key,
	PR_claim_cat_code,
	edw_claim_occurrence_ak_id,
	edw_claimant_cov_det_ak_id,
	edw_reins_cov_ak_id,
	pms_trans_code,
	trans_kind_code,
	claim_loss_date,
	pol_key,
	claim_cat_code
	FROM (
		SELECT sum(ChangeinOutStandingAmount) AS ChangeinOutStandingAmount,
		SUM(ChangeInEOMUnpaidLossAdjustmentExpense) as ChangeInEomUnpaidLossAdjustExp,
		CO.edw_claim_occurrence_ak_id As edw_claim_occurrence_ak_id,
		CC.edw_claimant_cov_det_ak_id AS edw_claimant_cov_det_ak_id,
		RC.edw_reins_cov_ak_id AS edw_reins_cov_ak_id,
		case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end AS pms_trans_code,
		CTT.trans_kind_code AS trans_kind_code,
		CO.claim_loss_date AS claim_loss_date,
		POL.pol_key AS pol_key,
		CO.claim_cat_code AS claim_cat_code
		FROM
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.loss_master_fact LMF with(nolock),
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.claim_transaction_type_dim CTT,
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.calendar_dim C,
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.claim_occurrence_dim CO,
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.claimant_coverage_dim CC,
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.reinsurance_coverage_dim RC,
		@{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.policy_dim POL
		where LMF.claim_trans_type_dim_id=CTT.claim_trans_type_dim_id
		and LMF.loss_master_run_date_id=C.clndr_id
		and LMF.claim_occurrence_dim_id=CO.claim_occurrence_dim_id
		and LMF.claimant_cov_dim_id=CC.claimant_cov_dim_id
		and CTT.pms_trans_code in ('90','92','95','97','98','99')
		and LMF.reins_cov_dim_id=RC.reins_cov_dim_id
		and LMF.pol_dim_id=POL.pol_dim_id
		and C.clndr_date<=dateadd(DD,-1,dateadd(MM,DATEDIFF(mm,0,getdate())-@{pipeline().parameters.NO_OF_MONTHS_PR},0))
		group by CO.edw_claim_occurrence_ak_id,CC.edw_claimant_cov_det_ak_id,RC.edw_reins_cov_ak_id,case when CTT.pms_trans_code='92' then '90' else CTT.pms_trans_code end,CTT.trans_kind_code,CO.claim_loss_date,POL.pol_key,CO.claim_cat_code
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY edw_claim_occurrence_ak_id,edw_claimant_cov_det_ak_id,edw_reins_cov_ak_id,pms_trans_code,trans_kind_code,claim_loss_date,pol_key,claim_cat_code ORDER BY ChangeinOutStandingAmount) = 1
),
Exp_TgtCollect AS (
	SELECT
	-9 AS PR_audit_id3,
	Exp_PreviousMonth.PR_edw_loss_master_calculation_pk_id3,
	Exp_PreviousMonth.PR_edw_claim_trans_pk_id3,
	Exp_PreviousMonth.PR_edw_claim_reins_trans_pk_id3,
	Exp_PreviousMonth.PR_wc_stage_loss_master_pk_id3,
	Exp_PreviousMonth.PR_loss_master_dim_id3,
	Exp_PreviousMonth.PR_claim_occurrence_dim_id3,
	Exp_PreviousMonth.PR_claimant_dim_id3,
	Exp_PreviousMonth.PR_claimant_cov_dim_id3,
	Exp_PreviousMonth.PR_cov_dim_id3,
	Exp_PreviousMonth.PR_claim_trans_type_dim_id3,
	Exp_PreviousMonth.PR_reins_cov_dim_id3,
	Exp_PreviousMonth.PR_claim_rep_dim_prim_claim_rep_id3,
	Exp_PreviousMonth.PR_claim_rep_dim_examiner_id3,
	Exp_PreviousMonth.PR_pol_dim_id3,
	Exp_PreviousMonth.PR_contract_cust_dim_id3,
	Exp_PreviousMonth.PR_agency_dim_id3,
	Exp_PreviousMonth.PR_claim_pay_dim_id3,
	Exp_PreviousMonth.PR_claim_pay_ctgry_type_dim_id3,
	Exp_PreviousMonth.PR_claim_case_dim_id3,
	Exp_PreviousMonth.PR_claim_trans_date_id3,
	Exp_PreviousMonth.PR_pol_eff_date_id3,
	Exp_PreviousMonth.PR_pol_exp_date_id3,
	Exp_PreviousMonth.PR_source_claim_rpted_date_id3,
	Exp_PreviousMonth.PR_claim_rpted_date_id3,
	Exp_PreviousMonth.PR_claim_loss_date_id3,
	Exp_PreviousMonth.PR_incptn_date_id3,
	LKP_calender_dim.clndr_id AS PR_loss_master_run_date_id3,
	0 AS PR_claim_trans_amt3,
	0 AS PR_claim_trans_hist_amt3,
	0 AS PR_new_claim_count3,
	0 AS PR_outstanding_amt3,
	0 AS PR_paid_loss_amt3,
	0 AS PR_paid_exp_amt3,
	0 AS PR_eom_unpaid_loss_adjust_exp3,
	0 AS PR_orig_reserve3,
	0 AS PR_orig_reserve_extract3,
	Exp_PreviousMonth.PR_asl_dim_id3,
	Exp_PreviousMonth.PR_asl_prdct_code_dim_id3,
	Exp_PreviousMonth.PR_strtgc_bus_dvsn_dim_id3,
	Exp_PreviousMonth.PR_prdct_code_dim_id3,
	Exp_PreviousMonth.PR_InsuranceReferenceDimId3,
	Exp_PreviousMonth.PR_AgencyDimId3,
	Exp_PreviousMonth.PR_SalesDivisionDimId3,
	Exp_PreviousMonth.PR_InsuranceReferenceCoverageDimId3,
	Exp_PreviousMonth.PR_CoverageDetailDimId3,
	Lkp_Get_FinalAmtForBalance.ChangeinOutStandingAmount,
	0-ChangeinOutStandingAmount AS Out_ChangeinOutStandingAmount3,
	Lkp_Get_FinalAmtForBalance.ChangeInEomUnpaidLossAdjustExp,
	0-ChangeInEomUnpaidLossAdjustExp AS Out_ChangeInEomUnpaidLossAdjustExp3,
	Exp_PreviousMonth.PR_claimfinancialtypedimid3
	FROM Exp_PreviousMonth
	LEFT JOIN LKP_calender_dim
	ON LKP_calender_dim.clndr_date = Exp_PreviousMonth.Out_LossMasterRundate
	LEFT JOIN Lkp_Get_FinalAmtForBalance
	ON Lkp_Get_FinalAmtForBalance.edw_claim_occurrence_ak_id = Exp_PreviousMonth.PR_edw_claim_occurrence_ak_id3 AND Lkp_Get_FinalAmtForBalance.edw_claimant_cov_det_ak_id = Exp_PreviousMonth.PR_edw_claimant_cov_det_ak_id3 AND Lkp_Get_FinalAmtForBalance.edw_reins_cov_ak_id = Exp_PreviousMonth.PR_edw_reins_cov_ak_id3 AND Lkp_Get_FinalAmtForBalance.pms_trans_code = Exp_PreviousMonth.Out_PR_pms_trans_code AND Lkp_Get_FinalAmtForBalance.trans_kind_code = Exp_PreviousMonth.PR_Trans_Kind_code3 AND Lkp_Get_FinalAmtForBalance.claim_loss_date = Exp_PreviousMonth.PR_Claim_Loss_date3 AND Lkp_Get_FinalAmtForBalance.pol_key = Exp_PreviousMonth.PR_Pol_key3 AND Lkp_Get_FinalAmtForBalance.claim_cat_code = Exp_PreviousMonth.PR_claim_cat_code3
),
FIL_Exclude_PriorMonth_CloseOutTransactions AS (
	SELECT
	PR_audit_id3, 
	PR_edw_loss_master_calculation_pk_id3, 
	PR_edw_claim_trans_pk_id3, 
	PR_edw_claim_reins_trans_pk_id3, 
	PR_wc_stage_loss_master_pk_id3, 
	PR_loss_master_dim_id3, 
	PR_claim_occurrence_dim_id3, 
	PR_claimant_dim_id3, 
	PR_claimant_cov_dim_id3, 
	PR_cov_dim_id3, 
	PR_claim_trans_type_dim_id3, 
	PR_reins_cov_dim_id3, 
	PR_claim_rep_dim_prim_claim_rep_id3, 
	PR_claim_rep_dim_examiner_id3, 
	PR_pol_dim_id3, 
	PR_contract_cust_dim_id3, 
	PR_agency_dim_id3, 
	PR_claim_pay_dim_id3, 
	PR_claim_pay_ctgry_type_dim_id3, 
	PR_claim_case_dim_id3, 
	PR_claim_trans_date_id3, 
	PR_pol_eff_date_id3, 
	PR_pol_exp_date_id3, 
	PR_source_claim_rpted_date_id3, 
	PR_claim_rpted_date_id3, 
	PR_claim_loss_date_id3, 
	PR_incptn_date_id3, 
	PR_loss_master_run_date_id3, 
	PR_claim_trans_amt3, 
	PR_claim_trans_hist_amt3, 
	PR_new_claim_count3, 
	PR_outstanding_amt3, 
	PR_paid_loss_amt3, 
	PR_paid_exp_amt3, 
	PR_eom_unpaid_loss_adjust_exp3, 
	PR_orig_reserve3, 
	PR_orig_reserve_extract3, 
	PR_asl_dim_id3, 
	PR_asl_prdct_code_dim_id3, 
	PR_strtgc_bus_dvsn_dim_id3, 
	PR_prdct_code_dim_id3, 
	PR_InsuranceReferenceDimId3, 
	PR_AgencyDimId3, 
	PR_SalesDivisionDimId3, 
	PR_InsuranceReferenceCoverageDimId3, 
	PR_CoverageDetailDimId3, 
	Out_ChangeinOutStandingAmount3, 
	Out_ChangeInEomUnpaidLossAdjustExp3, 
	PR_claimfinancialtypedimid3
	FROM Exp_TgtCollect
	WHERE IIF(Out_ChangeinOutStandingAmount3=0.00 AND Out_ChangeInEomUnpaidLossAdjustExp3=0.00,'FALSE','TRUE')='TRUE'
),
loss_master_fact_ClosedReserve_BalanceEntry AS (
	INSERT INTO @{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.loss_master_fact
	(audit_id, edw_loss_master_calculation_pk_id, edw_claim_trans_pk_id, edw_claim_reins_trans_pk_id, wc_stage_loss_master_pk_id, loss_master_dim_id, claim_occurrence_dim_id, claimant_dim_id, claimant_cov_dim_id, cov_dim_id, claim_trans_type_dim_id, reins_cov_dim_id, claim_rep_dim_prim_claim_rep_id, claim_rep_dim_examiner_id, pol_dim_id, contract_cust_dim_id, agency_dim_id, claim_pay_dim_id, claim_pay_ctgry_type_dim_id, claim_case_dim_id, claim_trans_date_id, pol_eff_date_id, pol_exp_date_id, source_claim_rpted_date_id, claim_rpted_date_id, claim_loss_date_id, incptn_date_id, loss_master_run_date_id, claim_trans_amt, claim_trans_hist_amt, new_claim_count, outstanding_amt, paid_loss_amt, paid_exp_amt, eom_unpaid_loss_adjust_exp, orig_reserve, orig_reserve_extract, asl_dim_id, asl_prdct_code_dim_id, strtgc_bus_dvsn_dim_id, prdct_code_dim_id, InsuranceReferenceDimId, AgencyDimId, SalesDivisionDimId, InsuranceReferenceCoverageDimId, CoverageDetailDimId, ChangeInOutstandingAmount, ChangeInEOMUnpaidLossAdjustmentExpense, ClaimFinancialTypeDimId)
	SELECT 
	PR_audit_id3 AS AUDIT_ID, 
	PR_edw_loss_master_calculation_pk_id3 AS EDW_LOSS_MASTER_CALCULATION_PK_ID, 
	PR_edw_claim_trans_pk_id3 AS EDW_CLAIM_TRANS_PK_ID, 
	PR_edw_claim_reins_trans_pk_id3 AS EDW_CLAIM_REINS_TRANS_PK_ID, 
	PR_wc_stage_loss_master_pk_id3 AS WC_STAGE_LOSS_MASTER_PK_ID, 
	PR_loss_master_dim_id3 AS LOSS_MASTER_DIM_ID, 
	PR_claim_occurrence_dim_id3 AS CLAIM_OCCURRENCE_DIM_ID, 
	PR_claimant_dim_id3 AS CLAIMANT_DIM_ID, 
	PR_claimant_cov_dim_id3 AS CLAIMANT_COV_DIM_ID, 
	PR_cov_dim_id3 AS COV_DIM_ID, 
	PR_claim_trans_type_dim_id3 AS CLAIM_TRANS_TYPE_DIM_ID, 
	PR_reins_cov_dim_id3 AS REINS_COV_DIM_ID, 
	PR_claim_rep_dim_prim_claim_rep_id3 AS CLAIM_REP_DIM_PRIM_CLAIM_REP_ID, 
	PR_claim_rep_dim_examiner_id3 AS CLAIM_REP_DIM_EXAMINER_ID, 
	PR_pol_dim_id3 AS POL_DIM_ID, 
	PR_contract_cust_dim_id3 AS CONTRACT_CUST_DIM_ID, 
	PR_agency_dim_id3 AS AGENCY_DIM_ID, 
	PR_claim_pay_dim_id3 AS CLAIM_PAY_DIM_ID, 
	PR_claim_pay_ctgry_type_dim_id3 AS CLAIM_PAY_CTGRY_TYPE_DIM_ID, 
	PR_claim_case_dim_id3 AS CLAIM_CASE_DIM_ID, 
	PR_claim_trans_date_id3 AS CLAIM_TRANS_DATE_ID, 
	PR_pol_eff_date_id3 AS POL_EFF_DATE_ID, 
	PR_pol_exp_date_id3 AS POL_EXP_DATE_ID, 
	PR_source_claim_rpted_date_id3 AS SOURCE_CLAIM_RPTED_DATE_ID, 
	PR_claim_rpted_date_id3 AS CLAIM_RPTED_DATE_ID, 
	PR_claim_loss_date_id3 AS CLAIM_LOSS_DATE_ID, 
	PR_incptn_date_id3 AS INCPTN_DATE_ID, 
	PR_loss_master_run_date_id3 AS LOSS_MASTER_RUN_DATE_ID, 
	PR_claim_trans_amt3 AS CLAIM_TRANS_AMT, 
	PR_claim_trans_hist_amt3 AS CLAIM_TRANS_HIST_AMT, 
	PR_new_claim_count3 AS NEW_CLAIM_COUNT, 
	PR_outstanding_amt3 AS OUTSTANDING_AMT, 
	PR_paid_loss_amt3 AS PAID_LOSS_AMT, 
	PR_paid_exp_amt3 AS PAID_EXP_AMT, 
	PR_eom_unpaid_loss_adjust_exp3 AS EOM_UNPAID_LOSS_ADJUST_EXP, 
	PR_orig_reserve3 AS ORIG_RESERVE, 
	PR_orig_reserve_extract3 AS ORIG_RESERVE_EXTRACT, 
	PR_asl_dim_id3 AS ASL_DIM_ID, 
	PR_asl_prdct_code_dim_id3 AS ASL_PRDCT_CODE_DIM_ID, 
	PR_strtgc_bus_dvsn_dim_id3 AS STRTGC_BUS_DVSN_DIM_ID, 
	PR_prdct_code_dim_id3 AS PRDCT_CODE_DIM_ID, 
	PR_InsuranceReferenceDimId3 AS INSURANCEREFERENCEDIMID, 
	PR_AgencyDimId3 AS AGENCYDIMID, 
	PR_SalesDivisionDimId3 AS SALESDIVISIONDIMID, 
	PR_InsuranceReferenceCoverageDimId3 AS INSURANCEREFERENCECOVERAGEDIMID, 
	PR_CoverageDetailDimId3 AS COVERAGEDETAILDIMID, 
	Out_ChangeinOutStandingAmount3 AS CHANGEINOUTSTANDINGAMOUNT, 
	Out_ChangeInEomUnpaidLossAdjustExp3 AS CHANGEINEOMUNPAIDLOSSADJUSTMENTEXPENSE, 
	PR_claimfinancialtypedimid3 AS CLAIMFINANCIALTYPEDIMID
	FROM FIL_Exclude_PriorMonth_CloseOutTransactions
),
Exp_CurrentMonth_ChangeInAmt AS (
	SELECT
	CR_loss_master_fact_id AS CR_loss_master_fact_id4,
	CR_outstanding_amt AS CR_outstanding_amt4,
	PR_outstanding_amt AS PR_outstanding_amt4,
	CR_outstanding_amt4-PR_outstanding_amt4 AS ChangeInOutstandingAmt,
	CR_eom_unpaid_loss_adjust_exp AS CR_eom_unpaid_loss_adjust_exp4,
	PR_eom_unpaid_loss_adjust_exp AS PR_eom_unpaid_loss_adjust_exp4,
	CR_eom_unpaid_loss_adjust_exp4-PR_eom_unpaid_loss_adjust_exp4 AS ChangeINEomUnpaidLossAdjustExp
	FROM RTR_Split_Current_Previous_Current_Previous_Month
),
UPD_CurrentPrevious_ChangeAmt AS (
	SELECT
	CR_loss_master_fact_id4, 
	ChangeInOutstandingAmt, 
	ChangeINEomUnpaidLossAdjustExp
	FROM Exp_CurrentMonth_ChangeInAmt
),
loss_master_fact_Update_OngoingReserve AS (
	MERGE INTO @{pipeline().parameters.TARGET_DATABASE_NAME}.@{pipeline().parameters.TARGET_TABLE_OWNER}.loss_master_fact AS T
	USING UPD_CurrentPrevious_ChangeAmt AS S
	ON T.loss_master_fact_id = S.CR_loss_master_fact_id4
	WHEN MATCHED BY TARGET THEN
	UPDATE SET T.ChangeInOutstandingAmount = S.ChangeInOutstandingAmt, T.ChangeInEOMUnpaidLossAdjustmentExpense = S.ChangeINEomUnpaidLossAdjustExp
),