WITH
SQ_CLAIM_EMPLOYER_STAGE1 AS (
	SELECT CLAIM_EMPLOYER_STAGE.CLAIM_EMPLOYER_ID, CLAIM_EMPLOYER_STAGE.CEI_CLAIM_NBR, CLAIM_EMPLOYER_STAGE.CEI_EPR_SEQ_NBR, CLAIM_EMPLOYER_STAGE.CEI_EPR_CLT_ID, CLAIM_EMPLOYER_STAGE.CEI_PRI_EPR_CD, CLAIM_EMPLOYER_STAGE.CEI_JOB_TLE_ID, CLAIM_EMPLOYER_STAGE.CEI_TYPE_LABOR_CD, CLAIM_EMPLOYER_STAGE.CEI_WAGE_RT_AMT, CLAIM_EMPLOYER_STAGE.CEI_WAGE_BASIS_CD, CLAIM_EMPLOYER_STAGE.CEI_AVG_WKLY_AMT, CLAIM_EMPLOYER_STAGE.CEI_WKLY_CPS_AMT, CLAIM_EMPLOYER_STAGE.CEI_LOS_TM_JOB_IND, CLAIM_EMPLOYER_STAGE.CEI_WAGE_REQ_DT, CLAIM_EMPLOYER_STAGE.CEI_WAGE_REC_DT, CLAIM_EMPLOYER_STAGE.CEI_ENTRY_OPR_ID, CLAIM_EMPLOYER_STAGE.CEI_UPDATE_OPR_ID, CLAIM_EMPLOYER_STAGE.CEI_CREATE_TS, CLAIM_EMPLOYER_STAGE.CEI_UPD_TS, CLAIM_EMPLOYER_STAGE.CEI_PMSD_TS, CLAIM_EMPLOYER_STAGE.CEI_SPV_CLT_NM_TXT, CLAIM_EMPLOYER_STAGE.CEI_PREINJ_WAGE_CD, CLAIM_EMPLOYER_STAGE.CEI_OCCUPATION_CD, CLAIM_EMPLOYER_STAGE.CEI_EMP_ID_NBR, CLAIM_EMPLOYER_STAGE.CEI_EMP_ID_TYPE_CD, CLAIM_EMPLOYER_STAGE.CEI_FTEMP_SAME_JOB, CLAIM_EMPLOYER_STAGE.CEI_PTEMP_SAME_JOB, CLAIM_EMPLOYER_STAGE.CEI_AVG_FT_HOURS, CLAIM_EMPLOYER_STAGE.CEI_AVG_FT_HOUR_WK, CLAIM_EMPLOYER_STAGE.CEI_AVG_FT_DAY_WK, CLAIM_EMPLOYER_STAGE.CEI_CLIENT_ID, CLAIM_EMPLOYER_STAGE.EXTRACT_DATE, CLAIM_EMPLOYER_STAGE.AS_OF_DATE, CLAIM_EMPLOYER_STAGE.RECORD_COUNT, CLAIM_EMPLOYER_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLAIM_EMPLOYER_STAGE
	WHERE
	CLAIM_EMPLOYER_STAGE.CEI_CREATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	CLAIM_EMPLOYER_STAGE.CEI_UPD_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLAIM_EMPLOYER_STAGE AS (
	SELECT
	CLAIM_EMPLOYER_ID,
	CEI_CLAIM_NBR,
	CEI_EPR_SEQ_NBR,
	CEI_EPR_CLT_ID,
	CEI_PRI_EPR_CD,
	CEI_JOB_TLE_ID,
	CEI_TYPE_LABOR_CD,
	CEI_WAGE_RT_AMT,
	CEI_WAGE_BASIS_CD,
	CEI_AVG_WKLY_AMT,
	CEI_WKLY_CPS_AMT,
	CEI_LOS_TM_JOB_IND,
	CEI_WAGE_REQ_DT,
	CEI_WAGE_REC_DT,
	CEI_ENTRY_OPR_ID,
	CEI_UPDATE_OPR_ID,
	CEI_CREATE_TS,
	CEI_UPD_TS,
	CEI_PMSD_TS,
	CEI_SPV_CLT_NM_TXT,
	CEI_PREINJ_WAGE_CD,
	CEI_OCCUPATION_CD,
	CEI_EMP_ID_NBR,
	CEI_EMP_ID_TYPE_CD,
	CEI_FTEMP_SAME_JOB,
	CEI_PTEMP_SAME_JOB,
	CEI_AVG_FT_HOURS,
	CEI_AVG_FT_HOUR_WK,
	CEI_AVG_FT_DAY_WK,
	CEI_CLIENT_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_EMPLOYER_STAGE1
),
ARCH_CLAIM_EMPLOYER_STAGE AS (
	INSERT INTO ARCH_CLAIM_EMPLOYER_STAGE
	(CLAIM_EMPLOYER_ID, CEI_CLAIM_NBR, CEI_EPR_SEQ_NBR, CEI_EPR_CLT_ID, CEI_PRI_EPR_CD, CEI_JOB_TLE_ID, CEI_TYPE_LABOR_CD, CEI_WAGE_RT_AMT, CEI_WAGE_BASIS_CD, CEI_AVG_WKLY_AMT, CEI_WKLY_CPS_AMT, CEI_LOS_TM_JOB_IND, CEI_WAGE_REQ_DT, CEI_WAGE_REC_DT, CEI_ENTRY_OPR_ID, CEI_UPDATE_OPR_ID, CEI_CREATE_TS, CEI_UPD_TS, CEI_PMSD_TS, CEI_SPV_CLT_NM_TXT, CEI_PREINJ_WAGE_CD, CEI_OCCUPATION_CD, CEI_EMP_ID_NBR, CEI_EMP_ID_TYPE_CD, CEI_FTEMP_SAME_JOB, CEI_PTEMP_SAME_JOB, CEI_AVG_FT_HOURS, CEI_AVG_FT_HOUR_WK, CEI_AVG_FT_DAY_WK, CEI_CLIENT_ID, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	CLAIM_EMPLOYER_ID, 
	CEI_CLAIM_NBR, 
	CEI_EPR_SEQ_NBR, 
	CEI_EPR_CLT_ID, 
	CEI_PRI_EPR_CD, 
	CEI_JOB_TLE_ID, 
	CEI_TYPE_LABOR_CD, 
	CEI_WAGE_RT_AMT, 
	CEI_WAGE_BASIS_CD, 
	CEI_AVG_WKLY_AMT, 
	CEI_WKLY_CPS_AMT, 
	CEI_LOS_TM_JOB_IND, 
	CEI_WAGE_REQ_DT, 
	CEI_WAGE_REC_DT, 
	CEI_ENTRY_OPR_ID, 
	CEI_UPDATE_OPR_ID, 
	CEI_CREATE_TS, 
	CEI_UPD_TS, 
	CEI_PMSD_TS, 
	CEI_SPV_CLT_NM_TXT, 
	CEI_PREINJ_WAGE_CD, 
	CEI_OCCUPATION_CD, 
	CEI_EMP_ID_NBR, 
	CEI_EMP_ID_TYPE_CD, 
	CEI_FTEMP_SAME_JOB, 
	CEI_PTEMP_SAME_JOB, 
	CEI_AVG_FT_HOURS, 
	CEI_AVG_FT_HOUR_WK, 
	CEI_AVG_FT_DAY_WK, 
	CEI_CLIENT_ID, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLAIM_EMPLOYER_STAGE
),