WITH
SQ_CLAIM_TRANSACTION_STAGE AS (
	SELECT
		claim_transaction_id AS CLAIM_TRANSACTION_ID,
		ctx_claim_nbr AS CTX_CLAIM_NBR,
		ctx_client_id AS CTX_CLIENT_ID,
		ctx_object_type_cd AS CTX_OBJECT_TYPE_CD,
		ctx_object_seq_nbr AS CTX_OBJECT_SEQ_NBR,
		ctx_cov_type_cd AS CTX_COV_TYPE_CD,
		ctx_cov_seq_nbr AS CTX_COV_SEQ_NBR,
		ctx_bur_cause_loss AS CTX_BUR_CAUSE_LOSS,
		ctx_fin_type_cd AS CTX_FIN_TYPE_CD,
		ctx_sort_ts AS CTX_SORT_TS,
		ctx_trs_type_cd AS CTX_TRS_TYPE_CD,
		ctx_adjuster_nbr AS CTX_ADJUSTER_NBR,
		ctx_draft_nbr AS CTX_DRAFT_NBR,
		ctx_upd_ts AS CTX_UPD_TS,
		ctx_trs_cat_cd AS CTX_TRS_CAT_CD,
		ctx_trs_amt AS CTX_TRS_AMT,
		ctx_trs_dt AS CTX_TRS_DT,
		ctx_update_opr_id AS CTX_UPDATE_OPR_ID,
		ctx_pmsd_ts AS CTX_PMSD_TS,
		ctx_entry_opr_id AS CTX_ENTRY_OPR_ID,
		ctx_trs_hst_amt AS CTX_TRS_HST_AMT,
		ctx_ofs_trs_cat AS CTX_OFS_TRS_CAT,
		ctx_base_trs_type AS CTX_BASE_TRS_TYPE,
		ctx_mem_cd AS CTX_MEM_CD,
		ctx_type_dis_cd AS CTX_TYPE_DIS_CD,
		ctx_dis_cd AS CTX_DIS_CD,
		ctx_reissue_of_nbr AS CTX_REISSUE_OF_NBR,
		ctx_ofs_rei_ind AS CTX_OFS_REI_IND,
		ctx_avg_res_ind AS CTX_AVG_RES_IND,
		ctx_single_chk_ind AS CTX_SINGLE_CHK_IND,
		ctx_balance_dt AS CTX_BALANCE_DT,
		ctx_dsb_req_cd AS CTX_DSB_REQ_CD,
		ctx_bus_cls_cd AS CTX_BUS_CLS_CD,
		ctx_create_ts AS CTX_CREATE_TS,
		ctx_reserve_id AS CTX_RESERVE_ID,
		ctx_from_dt AS CTX_FROM_DT,
		ctx_thru_dt AS CTX_THRU_DT,
		ctx_memo_act_id AS CTX_MEMO_ACT_ID,
		ctx_inj_emp_id AS CTX_INJ_EMP_ID,
		ctx_weeks_nbr AS CTX_WEEKS_NBR,
		ctx_days_nbr AS CTX_DAYS_NBR,
		ctx_dup_pmt_ind AS CTX_DUP_PMT_IND,
		ctx_pool_ind AS CTX_POOL_IND,
		ctx_loan_nbr AS CTX_LOAN_NBR,
		ctx_prc_sta_ind AS CTX_PRC_STA_IND,
		ctx_trans_reason AS CTX_TRANS_REASON,
		ctx_paid_holiday AS CTX_PAID_HOLIDAY,
		ctx_hours_worked AS CTX_HOURS_WORKED,
		ctx_hourly_rate AS CTX_HOURLY_RATE,
		ctx_tpd_wkly_wage AS CTX_TPD_WKLY_WAGE,
		ctx_tpd_rate_fctr AS CTX_TPD_RATE_FCTR,
		ctx_invoice_nbr AS CTX_INVOICE_NBR,
		ctx_cost_cont_sav AS CTX_COST_CONT_SAV,
		ctx_billed_amt AS CTX_BILLED_AMT,
		ctx_cost_cont_ppo AS CTX_COST_CONT_PPO,
		ctx_cost_cont_red AS CTX_COST_CONT_RED,
		ctx_aty_file_num AS CTX_ATY_FILE_NUM,
		ctx_event_date AS CTX_EVENT_DATE,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		ctx_admin_override
	FROM CLAIM_TRANSACTION_STAGE
),
EXP_CLAIM_TRANSACTION_STAGE AS (
	SELECT
	CLAIM_TRANSACTION_ID,
	CTX_CLAIM_NBR,
	CTX_CLIENT_ID,
	CTX_OBJECT_TYPE_CD,
	CTX_OBJECT_SEQ_NBR,
	CTX_COV_TYPE_CD,
	CTX_COV_SEQ_NBR,
	CTX_BUR_CAUSE_LOSS,
	CTX_FIN_TYPE_CD,
	CTX_SORT_TS,
	CTX_TRS_TYPE_CD,
	CTX_ADJUSTER_NBR,
	CTX_DRAFT_NBR,
	CTX_UPD_TS,
	CTX_TRS_CAT_CD,
	CTX_TRS_AMT,
	CTX_TRS_DT,
	CTX_UPDATE_OPR_ID,
	CTX_PMSD_TS,
	CTX_ENTRY_OPR_ID,
	CTX_TRS_HST_AMT,
	CTX_OFS_TRS_CAT,
	CTX_BASE_TRS_TYPE,
	CTX_MEM_CD,
	CTX_TYPE_DIS_CD,
	CTX_DIS_CD,
	CTX_REISSUE_OF_NBR,
	CTX_OFS_REI_IND,
	CTX_AVG_RES_IND,
	CTX_SINGLE_CHK_IND,
	CTX_BALANCE_DT,
	CTX_DSB_REQ_CD,
	CTX_BUS_CLS_CD,
	CTX_CREATE_TS,
	CTX_RESERVE_ID,
	CTX_FROM_DT,
	CTX_THRU_DT,
	CTX_MEMO_ACT_ID,
	CTX_INJ_EMP_ID,
	CTX_WEEKS_NBR,
	CTX_DAYS_NBR,
	CTX_DUP_PMT_IND,
	CTX_POOL_IND,
	CTX_LOAN_NBR,
	CTX_PRC_STA_IND,
	CTX_TRANS_REASON,
	CTX_PAID_HOLIDAY,
	CTX_HOURS_WORKED,
	CTX_HOURLY_RATE,
	CTX_TPD_WKLY_WAGE,
	CTX_TPD_RATE_FCTR,
	CTX_INVOICE_NBR,
	CTX_COST_CONT_SAV,
	CTX_BILLED_AMT,
	CTX_COST_CONT_PPO,
	CTX_COST_CONT_RED,
	CTX_ATY_FILE_NUM,
	CTX_EVENT_DATE,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	ctx_admin_override,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_TRANSACTION_STAGE
),
ARCH_CLAIM_TRANSACTION_STAGE AS (
	INSERT INTO ARCH_CLAIM_TRANSACTION_STAGE
	(claim_transaction_id, ctx_claim_nbr, ctx_client_id, ctx_object_type_cd, ctx_object_seq_nbr, ctx_cov_type_cd, ctx_cov_seq_nbr, ctx_bur_cause_loss, ctx_fin_type_cd, ctx_sort_ts, ctx_trs_type_cd, ctx_adjuster_nbr, ctx_draft_nbr, ctx_upd_ts, ctx_trs_cat_cd, ctx_trs_amt, ctx_trs_dt, ctx_update_opr_id, ctx_pmsd_ts, ctx_entry_opr_id, ctx_trs_hst_amt, ctx_ofs_trs_cat, ctx_base_trs_type, ctx_mem_cd, ctx_type_dis_cd, ctx_dis_cd, ctx_reissue_of_nbr, ctx_ofs_rei_ind, ctx_avg_res_ind, ctx_single_chk_ind, ctx_balance_dt, ctx_dsb_req_cd, ctx_bus_cls_cd, ctx_create_ts, ctx_reserve_id, ctx_from_dt, ctx_thru_dt, ctx_memo_act_id, ctx_inj_emp_id, ctx_weeks_nbr, ctx_days_nbr, ctx_dup_pmt_ind, ctx_pool_ind, ctx_loan_nbr, ctx_prc_sta_ind, ctx_trans_reason, ctx_paid_holiday, ctx_hours_worked, ctx_hourly_rate, ctx_tpd_wkly_wage, ctx_tpd_rate_fctr, ctx_invoice_nbr, ctx_cost_cont_sav, ctx_billed_amt, ctx_cost_cont_ppo, ctx_cost_cont_red, ctx_aty_file_num, ctx_event_date, extract_date, as_of_date, record_count, source_system_id, audit_id, ctx_admin_override)
	SELECT 
	CLAIM_TRANSACTION_ID AS CLAIM_TRANSACTION_ID, 
	CTX_CLAIM_NBR AS CTX_CLAIM_NBR, 
	CTX_CLIENT_ID AS CTX_CLIENT_ID, 
	CTX_OBJECT_TYPE_CD AS CTX_OBJECT_TYPE_CD, 
	CTX_OBJECT_SEQ_NBR AS CTX_OBJECT_SEQ_NBR, 
	CTX_COV_TYPE_CD AS CTX_COV_TYPE_CD, 
	CTX_COV_SEQ_NBR AS CTX_COV_SEQ_NBR, 
	CTX_BUR_CAUSE_LOSS AS CTX_BUR_CAUSE_LOSS, 
	CTX_FIN_TYPE_CD AS CTX_FIN_TYPE_CD, 
	CTX_SORT_TS AS CTX_SORT_TS, 
	CTX_TRS_TYPE_CD AS CTX_TRS_TYPE_CD, 
	CTX_ADJUSTER_NBR AS CTX_ADJUSTER_NBR, 
	CTX_DRAFT_NBR AS CTX_DRAFT_NBR, 
	CTX_UPD_TS AS CTX_UPD_TS, 
	CTX_TRS_CAT_CD AS CTX_TRS_CAT_CD, 
	CTX_TRS_AMT AS CTX_TRS_AMT, 
	CTX_TRS_DT AS CTX_TRS_DT, 
	CTX_UPDATE_OPR_ID AS CTX_UPDATE_OPR_ID, 
	CTX_PMSD_TS AS CTX_PMSD_TS, 
	CTX_ENTRY_OPR_ID AS CTX_ENTRY_OPR_ID, 
	CTX_TRS_HST_AMT AS CTX_TRS_HST_AMT, 
	CTX_OFS_TRS_CAT AS CTX_OFS_TRS_CAT, 
	CTX_BASE_TRS_TYPE AS CTX_BASE_TRS_TYPE, 
	CTX_MEM_CD AS CTX_MEM_CD, 
	CTX_TYPE_DIS_CD AS CTX_TYPE_DIS_CD, 
	CTX_DIS_CD AS CTX_DIS_CD, 
	CTX_REISSUE_OF_NBR AS CTX_REISSUE_OF_NBR, 
	CTX_OFS_REI_IND AS CTX_OFS_REI_IND, 
	CTX_AVG_RES_IND AS CTX_AVG_RES_IND, 
	CTX_SINGLE_CHK_IND AS CTX_SINGLE_CHK_IND, 
	CTX_BALANCE_DT AS CTX_BALANCE_DT, 
	CTX_DSB_REQ_CD AS CTX_DSB_REQ_CD, 
	CTX_BUS_CLS_CD AS CTX_BUS_CLS_CD, 
	CTX_CREATE_TS AS CTX_CREATE_TS, 
	CTX_RESERVE_ID AS CTX_RESERVE_ID, 
	CTX_FROM_DT AS CTX_FROM_DT, 
	CTX_THRU_DT AS CTX_THRU_DT, 
	CTX_MEMO_ACT_ID AS CTX_MEMO_ACT_ID, 
	CTX_INJ_EMP_ID AS CTX_INJ_EMP_ID, 
	CTX_WEEKS_NBR AS CTX_WEEKS_NBR, 
	CTX_DAYS_NBR AS CTX_DAYS_NBR, 
	CTX_DUP_PMT_IND AS CTX_DUP_PMT_IND, 
	CTX_POOL_IND AS CTX_POOL_IND, 
	CTX_LOAN_NBR AS CTX_LOAN_NBR, 
	CTX_PRC_STA_IND AS CTX_PRC_STA_IND, 
	CTX_TRANS_REASON AS CTX_TRANS_REASON, 
	CTX_PAID_HOLIDAY AS CTX_PAID_HOLIDAY, 
	CTX_HOURS_WORKED AS CTX_HOURS_WORKED, 
	CTX_HOURLY_RATE AS CTX_HOURLY_RATE, 
	CTX_TPD_WKLY_WAGE AS CTX_TPD_WKLY_WAGE, 
	CTX_TPD_RATE_FCTR AS CTX_TPD_RATE_FCTR, 
	CTX_INVOICE_NBR AS CTX_INVOICE_NBR, 
	CTX_COST_CONT_SAV AS CTX_COST_CONT_SAV, 
	CTX_BILLED_AMT AS CTX_BILLED_AMT, 
	CTX_COST_CONT_PPO AS CTX_COST_CONT_PPO, 
	CTX_COST_CONT_RED AS CTX_COST_CONT_RED, 
	CTX_ATY_FILE_NUM AS CTX_ATY_FILE_NUM, 
	CTX_EVENT_DATE AS CTX_EVENT_DATE, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	CTX_ADMIN_OVERRIDE
	FROM EXP_CLAIM_TRANSACTION_STAGE
),