WITH
LKP_Record_Count AS (
	SELECT
	claim_med_ak_id,
	dummy_integer
	FROM (
		select (A.claim_med_ak_id + B.claim_med_ak_id) as claim_med_ak_id, 1 as dummy_integer 
		FROM
		(SELECT count(*) as claim_med_ak_id FROM dbo.work_claim_cms_detail_extract WHERE audit_id = @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}) A,
		(SELECT count(*) as claim_med_ak_id FROM dbo.work_claim_cms_auxiliary_extract WHERE audit_id = @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}) B
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY dummy_integer ORDER BY claim_med_ak_id) = 1
),
SQ_work_claim_cms_detail_extract AS (
	SELECT work_claim_cms_detail_extract.work_claim_cms_detail_extract_id,work_claim_cms_detail_extract.record_identifier,
	       work_claim_cms_detail_extract.dcn,
	       work_claim_cms_detail_extract.action_type,
	       work_claim_cms_detail_extract.injured_party_hicn,
	       work_claim_cms_detail_extract.injured_party_ssn,
	       work_claim_cms_detail_extract.injured_party_last_name,
	       work_claim_cms_detail_extract.injured_party_first_name,
	       work_claim_cms_detail_extract.injured_party_middle_ini,
	       work_claim_cms_detail_extract.injured_party_gender,
	       work_claim_cms_detail_extract.injured_party_dob,
	       work_claim_cms_detail_extract.reserved_11,
	       work_claim_cms_detail_extract.cms_date_of_incident,
	       work_claim_cms_detail_extract.industry_date_of_incident,
	       work_claim_cms_detail_extract.reserved_14,
	       work_claim_cms_detail_extract.alleged_cause_of_injury,
	       work_claim_cms_detail_extract.reserved_16,
	       work_claim_cms_detail_extract.state_of_venue,
	       work_claim_cms_detail_extract.icd_indicator,
	       work_claim_cms_detail_extract.diag_code_1,
	       work_claim_cms_detail_extract.reserved_20,
	       work_claim_cms_detail_extract.diag_code_2,
	       work_claim_cms_detail_extract.reserved_22,
	       work_claim_cms_detail_extract.diag_code_3,
	       work_claim_cms_detail_extract.reserved_24,
	       work_claim_cms_detail_extract.diag_code_4,
	       work_claim_cms_detail_extract.reserved_26,
	       work_claim_cms_detail_extract.diag_code_5,
	       work_claim_cms_detail_extract.reserved_28,
	       work_claim_cms_detail_extract.diag_code_6,
	       work_claim_cms_detail_extract.reserved_30,
	       work_claim_cms_detail_extract.diag_code_7,
	       work_claim_cms_detail_extract.reserved_32,
	       work_claim_cms_detail_extract.diag_code_8,
	       work_claim_cms_detail_extract.reserved_34,
	       work_claim_cms_detail_extract.diag_code_9,
	       work_claim_cms_detail_extract.reserved_36,
	       work_claim_cms_detail_extract.diag_code_10,
	       work_claim_cms_detail_extract.reserved_38,
	       work_claim_cms_detail_extract.diag_code_11,
	       work_claim_cms_detail_extract.reserved_40,
	       work_claim_cms_detail_extract.diag_code_12,
	       work_claim_cms_detail_extract.reserved_42,
	       work_claim_cms_detail_extract.diag_code_13,
	       work_claim_cms_detail_extract.reserved_44,
	       work_claim_cms_detail_extract.diag_code_14,
	       work_claim_cms_detail_extract.reserved_46,
	       work_claim_cms_detail_extract.diag_code_15,
	       work_claim_cms_detail_extract.reserved_48,
	       work_claim_cms_detail_extract.diag_code_16,
	       work_claim_cms_detail_extract.reserved_50,
	       work_claim_cms_detail_extract.diag_code_17,
	       work_claim_cms_detail_extract.reserved_52,
	       work_claim_cms_detail_extract.diag_code_18,
	       work_claim_cms_detail_extract.reserved_54,
	       work_claim_cms_detail_extract.diag_code_19,
	       work_claim_cms_detail_extract.reserved_56,
	       work_claim_cms_detail_extract.descript_of_illness,
	       work_claim_cms_detail_extract.product_liability_ind,
	       work_claim_cms_detail_extract.product_generic_name,
	       work_claim_cms_detail_extract.product_brand_name,
	       work_claim_cms_detail_extract.product_manufacturer,
	       work_claim_cms_detail_extract.product_alleged_harm,
	       work_claim_cms_detail_extract.reserved_63,
	       work_claim_cms_detail_extract.self_insured_ind,
	       work_claim_cms_detail_extract.self_insured_type,
	       work_claim_cms_detail_extract.policyholder_last_name,
	       work_claim_cms_detail_extract.policyholder_first_name,
	       work_claim_cms_detail_extract.dba_name,
	       work_claim_cms_detail_extract.legal_name,
	       work_claim_cms_detail_extract.reserved_70,
	       work_claim_cms_detail_extract.plan_insurance_type,
	       work_claim_cms_detail_extract.tin,
	       work_claim_cms_detail_extract.office_code,
	       work_claim_cms_detail_extract.policy_number,
	       work_claim_cms_detail_extract.claim_number,
	       work_claim_cms_detail_extract.plan_contact_department_name,
	       work_claim_cms_detail_extract.plan_contact_last_name,
	       work_claim_cms_detail_extract.plan_contact_first_name,
	       work_claim_cms_detail_extract.plan_contact_ph,
	       work_claim_cms_detail_extract.plan_contact_ph_extension,
	       work_claim_cms_detail_extract.no_fault_insurance_limit,
	       work_claim_cms_detail_extract.exhaust_date_for_dollar_limit,
	       work_claim_cms_detail_extract.reserved_83,
	       work_claim_cms_detail_extract.inj_party_rep_ind,
	       work_claim_cms_detail_extract.rep_last_name,
	       work_claim_cms_detail_extract.rep_first_name,
	       work_claim_cms_detail_extract.rep_firm_name,
	       work_claim_cms_detail_extract.rep_tin,
	       work_claim_cms_detail_extract.rep_mail_addr_1,
	       work_claim_cms_detail_extract.rep_mail_addr_2,
	       work_claim_cms_detail_extract.rep_city,
	       work_claim_cms_detail_extract.rep_state,
	       work_claim_cms_detail_extract.rep_mail_zip_code,
	       work_claim_cms_detail_extract.rep_mail_zip4,
	       work_claim_cms_detail_extract.rep_ph,
	       work_claim_cms_detail_extract.rep_ph_extension,
	       work_claim_cms_detail_extract.reserved_97,
	       work_claim_cms_detail_extract.orm_ind,
	       work_claim_cms_detail_extract.orm_termination_date,
	       work_claim_cms_detail_extract.tpoc_date,
	       work_claim_cms_detail_extract.tpoc_amount,
	       work_claim_cms_detail_extract.funding_delayed_beyond_tpoc_start_date,
	       work_claim_cms_detail_extract.reserved_103,
	       work_claim_cms_detail_extract.c1_relationship,
	       work_claim_cms_detail_extract.c1_tin,
	       work_claim_cms_detail_extract.c1_last_name,
	       work_claim_cms_detail_extract.c1_first_name,
	       work_claim_cms_detail_extract.c1_middle_initial,
	       work_claim_cms_detail_extract.c1_mail_addr_1,
	       work_claim_cms_detail_extract.c1_mail_addr_2,
	       work_claim_cms_detail_extract.c1_city,
	       work_claim_cms_detail_extract.c1_state,
	       work_claim_cms_detail_extract.c1_zip,
	       work_claim_cms_detail_extract.c1_zip4,
	       work_claim_cms_detail_extract.c1_ph,
	       work_claim_cms_detail_extract.c1_ph_extension,
	       work_claim_cms_detail_extract.reserved_117,
	       work_claim_cms_detail_extract.c1_rep_ind,
	       work_claim_cms_detail_extract.c1_rep_last_name,
	       work_claim_cms_detail_extract.c1_rep_first_name,
	       work_claim_cms_detail_extract.c1_rep_firm_name,
	       work_claim_cms_detail_extract.c1_rep_tin,
	       work_claim_cms_detail_extract.c1_rep_mail_addr_1,
	       work_claim_cms_detail_extract.c1_rep_mail_addr_2,
	       work_claim_cms_detail_extract.c1_rep_mail_city,
	       work_claim_cms_detail_extract.c1_rep_state,
	       work_claim_cms_detail_extract.c1_rep_zip,
	       work_claim_cms_detail_extract.c1_rep_zip4,
	       work_claim_cms_detail_extract.c1_rep_ph,
	       work_claim_cms_detail_extract.c1_rep_ph_extension,
	       work_claim_cms_detail_extract.reserved_131
	FROM   work_claim_cms_detail_extract
	WHERE 
	audit_id =@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
	ORDER  BY  work_claim_cms_detail_extract_id,
	work_claim_cms_detail_extract.dcn ASC,
	          work_claim_cms_detail_extract.action_type DESC
),
SQ_work_claim_cms_detail_extract_SSN AS (
	SELECT work_claim_cms_detail_extract.work_claim_cms_detail_extract_id, work_claim_cms_detail_extract.injured_party_ssn 
	FROM
	 work_claim_cms_detail_extract 
	WHERE
	 audit_id = @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
),
mplt_Detokinize_WebService_call_detail_extract_SSN AS (WITH
	INPUT AS (
		
	),
	EXP_SSN_FEIN_TAXID AS (
		SELECT
		IN_id AS id,
		IN_ssn_fein_taxid AS ssn_fein_taxid,
		-- *INF*: LTRIM(RTRIM(ssn_fein_taxid))
		LTRIM(RTRIM(ssn_fein_taxid)) AS V_ssn_fein_taxid,
		-- *INF*: IIF(LENGTH(V_ssn_fein_taxid)=0  or IS_NUMBER(V_ssn_fein_taxid),'FEIN','NONFEIN')
		-- --IIF(LENGTH(V_ssn_fein_taxid)=11 AND REG_MATCH(V_ssn_fein_taxid,'[\da-zA-Z]+'),'NONFEIN','FEIN')
		-- 
		-- 
		IFF(
		    LENGTH(V_ssn_fein_taxid) = 0 or REGEXP_LIKE(V_ssn_fein_taxid, '^[0-9]+$'), 'FEIN', 'NONFEIN'
		) AS V_flag,
		V_flag AS flag,
		V_ssn_fein_taxid AS o_ssn_fein_taxid
		FROM INPUT
	),
	RTR_SSN_FEIN_TAXID AS (
		SELECT
		id,
		flag,
		o_ssn_fein_taxid AS ssn_fein_taxid,
		o_ssn_fein_taxid AS ssn_fein
		FROM EXP_SSN_FEIN_TAXID
	),
	RTR_SSN_FEIN_TAXID_FEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag = 'FEIN'),
	RTR_SSN_FEIN_TAXID_NONFEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag='NONFEIN'),
	EXP_Values AS (
		SELECT
		id AS ID,
		'Detokenize' AS Function,
		'SSN' AS Scheme,
		ssn_fein_taxid AS SSN_FEIN_TAXID,
		'DATAFEED_JOBS' AS Requestedby,
		'Claims' AS Application,
		'DataFeeds' AS Caller,
		-- *INF*: 'https://intsvc.wbconnect.com/services/TokenService/Token.svc'
		-- 
		-- 
		-- 
		'https://intsvc.wbconnect.com/services/TokenService/Token.svc' AS URL,
		ssn_fein AS SSN_FEIN3
		FROM RTR_SSN_FEIN_TAXID_NONFEIN_VALUES
	),
	Token AS (-- Token
	
		##############################################
	
		# TODO: Place holder for Custom transformation
	
		##############################################
	),
	EXP_Response AS (
		SELECT
		REF_Id AS ID,
		tns_Data0 AS TokenResponse,
		REF_SSN_FEIN_TAXID,
		-- *INF*: ltrim(rtrim(REPLACECHR(0,TokenResponse,'-',NULL)))
		-- 
		ltrim(rtrim(REGEXP_REPLACE(TokenResponse,'-','','i'))) AS o_TokenResponse
		FROM Token
	),
	Union_SSN_FEIN_TAXID AS (
		SELECT id AS ID, ssn_fein_taxid AS TokenReponse, ssn_fein_taxid AS SSN_FEIN
		FROM RTR_SSN_FEIN_TAXID_FEIN_VALUES
		UNION
		SELECT ID, o_TokenResponse AS TokenReponse, REF_SSN_FEIN_TAXID AS SSN_FEIN
		FROM EXP_Response
	),
	OUTPUT AS (
		SELECT
		ID AS OUT_id, 
		TokenReponse AS OUT_TokenResponse, 
		SSN_FEIN AS OUT_IN_ssn_fein_taxid
		FROM Union_SSN_FEIN_TAXID
	),
),
JNR_work_claim_cms_detail_extract AS (SELECT
	SQ_work_claim_cms_detail_extract.work_claim_cms_detail_extract_id, 
	SQ_work_claim_cms_detail_extract.Record_Identifier, 
	SQ_work_claim_cms_detail_extract.DCN, 
	SQ_work_claim_cms_detail_extract.Action_Type, 
	SQ_work_claim_cms_detail_extract.injured_party_hicn, 
	SQ_work_claim_cms_detail_extract.injured_party_ssn, 
	SQ_work_claim_cms_detail_extract.injured_party_last_name, 
	SQ_work_claim_cms_detail_extract.injured_party_first_name, 
	SQ_work_claim_cms_detail_extract.injured_party_middle_ini, 
	SQ_work_claim_cms_detail_extract.injured_party_gender, 
	SQ_work_claim_cms_detail_extract.injured_party_dob, 
	SQ_work_claim_cms_detail_extract.Reserved_11, 
	SQ_work_claim_cms_detail_extract.CMS_Date_of_Incident, 
	SQ_work_claim_cms_detail_extract.Industry_Date_of_Incident, 
	SQ_work_claim_cms_detail_extract.Reserved_14, 
	SQ_work_claim_cms_detail_extract.Alleged_Cause_of_Injury, 
	SQ_work_claim_cms_detail_extract.Reserved_16, 
	SQ_work_claim_cms_detail_extract.State_of_Venue, 
	SQ_work_claim_cms_detail_extract.icd_indicator, 
	SQ_work_claim_cms_detail_extract.diag_code_1, 
	SQ_work_claim_cms_detail_extract.Reserved_20, 
	SQ_work_claim_cms_detail_extract.diag_code_2, 
	SQ_work_claim_cms_detail_extract.Reserved_22, 
	SQ_work_claim_cms_detail_extract.diag_code_3, 
	SQ_work_claim_cms_detail_extract.Reserved_24, 
	SQ_work_claim_cms_detail_extract.diag_code_4, 
	SQ_work_claim_cms_detail_extract.Reserved_26, 
	SQ_work_claim_cms_detail_extract.diag_code_5, 
	SQ_work_claim_cms_detail_extract.Reserved_28, 
	SQ_work_claim_cms_detail_extract.diag_code_6, 
	SQ_work_claim_cms_detail_extract.Reserved_30, 
	SQ_work_claim_cms_detail_extract.diag_code_7, 
	SQ_work_claim_cms_detail_extract.Reserved_32, 
	SQ_work_claim_cms_detail_extract.diag_code_8, 
	SQ_work_claim_cms_detail_extract.Reserved_34, 
	SQ_work_claim_cms_detail_extract.diag_code_9, 
	SQ_work_claim_cms_detail_extract.Reserved_36, 
	SQ_work_claim_cms_detail_extract.diag_code_10, 
	SQ_work_claim_cms_detail_extract.Reserved_38, 
	SQ_work_claim_cms_detail_extract.diag_code_11, 
	SQ_work_claim_cms_detail_extract.Reserved_40, 
	SQ_work_claim_cms_detail_extract.diag_code_12, 
	SQ_work_claim_cms_detail_extract.Reserved_42, 
	SQ_work_claim_cms_detail_extract.diag_code_13, 
	SQ_work_claim_cms_detail_extract.Reserved_44, 
	SQ_work_claim_cms_detail_extract.diag_code_14, 
	SQ_work_claim_cms_detail_extract.Reserved_46, 
	SQ_work_claim_cms_detail_extract.diag_code_15, 
	SQ_work_claim_cms_detail_extract.Reserved_48, 
	SQ_work_claim_cms_detail_extract.diag_code_16, 
	SQ_work_claim_cms_detail_extract.Reserved_50, 
	SQ_work_claim_cms_detail_extract.diag_code_17, 
	SQ_work_claim_cms_detail_extract.Reserved_52, 
	SQ_work_claim_cms_detail_extract.diag_code_18, 
	SQ_work_claim_cms_detail_extract.Reserved_54, 
	SQ_work_claim_cms_detail_extract.diag_code_19, 
	SQ_work_claim_cms_detail_extract.Reserved_56, 
	SQ_work_claim_cms_detail_extract.descript_of_illness, 
	SQ_work_claim_cms_detail_extract.Product_Liability_Ind, 
	SQ_work_claim_cms_detail_extract.Product_Generic_Name, 
	SQ_work_claim_cms_detail_extract.Product_Brand_Name, 
	SQ_work_claim_cms_detail_extract.Product_Manufacturer, 
	SQ_work_claim_cms_detail_extract.Product_Alleged_Harm, 
	SQ_work_claim_cms_detail_extract.Reserved_63, 
	SQ_work_claim_cms_detail_extract.Self_Insured_Ind, 
	SQ_work_claim_cms_detail_extract.Self_Insured_Type, 
	SQ_work_claim_cms_detail_extract.Policyholder_Last_Name, 
	SQ_work_claim_cms_detail_extract.Policyholder_First_Name, 
	SQ_work_claim_cms_detail_extract.DBA_Name, 
	SQ_work_claim_cms_detail_extract.Legal_Name, 
	SQ_work_claim_cms_detail_extract.Reserved_70, 
	SQ_work_claim_cms_detail_extract.Plan_Insurance_Type, 
	SQ_work_claim_cms_detail_extract.TIN, 
	SQ_work_claim_cms_detail_extract.Office_Code, 
	SQ_work_claim_cms_detail_extract.Policy_Number, 
	SQ_work_claim_cms_detail_extract.Claim_Number, 
	SQ_work_claim_cms_detail_extract.Plan_Contact_Department_Name, 
	SQ_work_claim_cms_detail_extract.Plan_Contact_Last_Name, 
	SQ_work_claim_cms_detail_extract.Plan_Contact_First_Name, 
	SQ_work_claim_cms_detail_extract.Plan_Contact_Ph, 
	SQ_work_claim_cms_detail_extract.Plan_Contact_Ph_Extension, 
	SQ_work_claim_cms_detail_extract.No_Fault_Insurance_Limit, 
	SQ_work_claim_cms_detail_extract.Exhaust_Date_for_Dollar_Limit, 
	SQ_work_claim_cms_detail_extract.Reserved_83, 
	SQ_work_claim_cms_detail_extract.Inj_Party_Rep_Ind, 
	SQ_work_claim_cms_detail_extract.Rep_Last_Name, 
	SQ_work_claim_cms_detail_extract.Rep_First_Name, 
	SQ_work_claim_cms_detail_extract.Rep_Firm_Name, 
	SQ_work_claim_cms_detail_extract.Rep_TIN, 
	SQ_work_claim_cms_detail_extract.Rep_Mail_Addr_1, 
	SQ_work_claim_cms_detail_extract.Rep_Mail_Addr_2, 
	SQ_work_claim_cms_detail_extract.Rep_City, 
	SQ_work_claim_cms_detail_extract.Rep_State, 
	SQ_work_claim_cms_detail_extract.Rep_Mail_Zip_Code, 
	SQ_work_claim_cms_detail_extract.Rep_Mail_Zip4, 
	SQ_work_claim_cms_detail_extract.Rep_Ph, 
	SQ_work_claim_cms_detail_extract.Rep_Ph_Extension, 
	SQ_work_claim_cms_detail_extract.Reserved_97, 
	SQ_work_claim_cms_detail_extract.ORM_Ind, 
	SQ_work_claim_cms_detail_extract.ORM_Termination_Date, 
	SQ_work_claim_cms_detail_extract.TPOC_Date, 
	SQ_work_claim_cms_detail_extract.TPOC_Amount, 
	SQ_work_claim_cms_detail_extract.Funding_Delayed_Beyond_TPOC_Start_Date, 
	SQ_work_claim_cms_detail_extract.Reserved_103, 
	SQ_work_claim_cms_detail_extract.c1_relationship, 
	SQ_work_claim_cms_detail_extract.c1_tin, 
	SQ_work_claim_cms_detail_extract.c1_last_name, 
	SQ_work_claim_cms_detail_extract.c1_first_name, 
	SQ_work_claim_cms_detail_extract.c1_middle_initial, 
	SQ_work_claim_cms_detail_extract.c1_mail_addr_1, 
	SQ_work_claim_cms_detail_extract.c1_mail_addr_2, 
	SQ_work_claim_cms_detail_extract.c1_city, 
	SQ_work_claim_cms_detail_extract.c1_state, 
	SQ_work_claim_cms_detail_extract.c1_zip, 
	SQ_work_claim_cms_detail_extract.c1_zip4, 
	SQ_work_claim_cms_detail_extract.c1_ph, 
	SQ_work_claim_cms_detail_extract.c1_ph_extension, 
	SQ_work_claim_cms_detail_extract.Reserved_117, 
	SQ_work_claim_cms_detail_extract.c1_rep_ind, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Last_Name, 
	SQ_work_claim_cms_detail_extract.C1_Rep_First_Name, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Firm_Name, 
	SQ_work_claim_cms_detail_extract.C1_Rep_TIN, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Mail_Addr_1, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Mail_Addr_2, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Mail_City, 
	SQ_work_claim_cms_detail_extract.C1_Rep_State, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Zip, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Zip4, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Ph, 
	SQ_work_claim_cms_detail_extract.C1_Rep_Ph_Extension, 
	SQ_work_claim_cms_detail_extract.Reserved_131, 
	mplt_Detokinize_WebService_call_detail_extract_SSN.OUT_id AS IN_mplt_id, 
	mplt_Detokinize_WebService_call_detail_extract_SSN.OUT_TokenResponse AS TokenResponse
	FROM SQ_work_claim_cms_detail_extract
	INNER JOIN mplt_Detokinize_WebService_call_detail_extract_SSN
	ON mplt_Detokinize_WebService_call_detail_extract_SSN.OUT_id = SQ_work_claim_cms_detail_extract.work_claim_cms_detail_extract_id
),
EXP_Detail AS (
	SELECT
	Record_Identifier,
	DCN,
	Action_Type,
	injured_party_hicn,
	TokenResponse AS injured_party_ssn,
	-- *INF*: REPLACECHR(0,injured_party_ssn,'-',NULL)
	REGEXP_REPLACE(injured_party_ssn,'-','','i') AS v_injured_party_ssn,
	v_injured_party_ssn AS o_injured_party_ssn,
	injured_party_last_name,
	injured_party_first_name,
	injured_party_middle_ini,
	injured_party_gender,
	injured_party_dob,
	Reserved_11,
	CMS_Date_of_Incident,
	Industry_Date_of_Incident,
	Reserved_14,
	Alleged_Cause_of_Injury,
	Reserved_16,
	State_of_Venue,
	icd_indicator,
	diag_code_1,
	Reserved_20,
	diag_code_2,
	Reserved_22,
	diag_code_3,
	Reserved_24,
	diag_code_4,
	Reserved_26,
	diag_code_5,
	Reserved_28,
	diag_code_6,
	Reserved_30,
	diag_code_7,
	Reserved_32,
	diag_code_8,
	Reserved_34,
	diag_code_9,
	Reserved_36,
	diag_code_10,
	Reserved_38,
	diag_code_11,
	Reserved_40,
	diag_code_12,
	Reserved_42,
	diag_code_13,
	Reserved_44,
	diag_code_14,
	Reserved_46,
	diag_code_15,
	Reserved_48,
	diag_code_16,
	Reserved_50,
	diag_code_17,
	Reserved_52,
	diag_code_18,
	Reserved_54,
	diag_code_19,
	Reserved_56,
	-- *INF*: substr(Reserved_56,1,57)
	substr(Reserved_56, 1, 57) AS Reserved_56_out,
	descript_of_illness,
	Product_Liability_Ind,
	Product_Generic_Name,
	Product_Brand_Name,
	Product_Manufacturer,
	Product_Alleged_Harm,
	Reserved_63,
	Self_Insured_Ind,
	Self_Insured_Type,
	Policyholder_Last_Name,
	Policyholder_First_Name,
	DBA_Name,
	Legal_Name,
	Reserved_70,
	Plan_Insurance_Type,
	TIN,
	Office_Code,
	Policy_Number,
	Claim_Number,
	Plan_Contact_Department_Name,
	Plan_Contact_Last_Name,
	Plan_Contact_First_Name,
	Plan_Contact_Ph,
	Plan_Contact_Ph_Extension,
	No_Fault_Insurance_Limit,
	Exhaust_Date_for_Dollar_Limit,
	Reserved_83,
	Inj_Party_Rep_Ind,
	Rep_Last_Name,
	Rep_First_Name,
	Rep_Firm_Name,
	Rep_TIN,
	Rep_Mail_Addr_1,
	Rep_Mail_Addr_2,
	Rep_City,
	Rep_State,
	Rep_Mail_Zip_Code,
	Rep_Mail_Zip4,
	Rep_Ph,
	Rep_Ph_Extension,
	Reserved_97,
	ORM_Ind,
	ORM_Termination_Date,
	TPOC_Date,
	TPOC_Amount,
	Funding_Delayed_Beyond_TPOC_Start_Date,
	Reserved_103,
	c1_relationship,
	c1_tin,
	c1_last_name,
	c1_first_name,
	c1_middle_initial,
	c1_mail_addr_1,
	c1_mail_addr_2,
	c1_city,
	c1_state,
	c1_zip,
	c1_zip4,
	c1_ph,
	c1_ph_extension,
	Reserved_117,
	c1_rep_ind,
	C1_Rep_Last_Name,
	C1_Rep_First_Name,
	C1_Rep_Firm_Name,
	C1_Rep_TIN,
	C1_Rep_Mail_Addr_1,
	C1_Rep_Mail_Addr_2,
	C1_Rep_Mail_City,
	C1_Rep_State,
	C1_Rep_Zip,
	C1_Rep_Zip4,
	C1_Rep_Ph,
	C1_Rep_Ph_Extension,
	Reserved_131,
	'' AS O_assign_null_values_to_TIN
	FROM JNR_work_claim_cms_detail_extract
),
CMS_Claims_Input_File_Detail AS (
	INSERT INTO CMS_Claims_Input_File_Detail
	(Record_Identifier, DCN, Action_Type, Inj_Party_HICN, Inj_Party_SSN, Inj_Party_Last_Name, Inj_Party_First_Name, Inj_Party_Middle_Ini, Inj_Party_Gender, Inj_Party_DOB, Reserved_11, CMS_Date_of_Incident, Industry_Date_of_Incident, Reserved_14, Alleged_Cause_of_Injury, State_of_Venue, ICD_Indicator, Diagnosis_Code_1, Diagnosis_Code_2, Diagnosis_Code_3, Diagnosis_Code_4, Diagnosis_Code_5, Diagnosis_Code_6, Diagnosis_Code_7, Diagnosis_Code_8, Diagnosis_Code_9, Diagnosis_Code_10, Diagnosis_Code_11, Diagnosis_Code_12, Diagnosis_Code_13, Diagnosis_Code_14, Diagnosis_Code_15, Diagnosis_Code_16, Diagnosis_Code_17, Diagnosis_Code_18, Diagnosis_Code_19, Reserved_56, Description_of_Illness, Product_Liability_Ind, Product_Generic_Name, Product_Brand_Name, Product_Manufacturer, Product_Alleged_Harm, Reserved_63, Self_Insured_Ind, Self_Insured_Type, Policyholder_Last_Name, Policyholder_First_Name, DBA_Name, Legal_Name, Reserved_70, Plan_Insurance_Type, TIN, Office_Code, Policy_Number, Claim_Number, Plan_Contact_Department_Name, Plan_Contact_Last_Name, Plan_Contact_First_Name, Plan_Contact_Ph, Plan_Contact_Ph_Extension, No_Fault_Insurance_Limit, Exhaust_Date_for_Dollar_Limit, Reserved_83, Inj_Party_Rep_Ind, Rep_Last_Name, Rep_First_Name, Rep_Firm_Name, Rep_TIN, Rep_Mail_Addr_1, Rep_Mail_Addr_2, Rep_City, Rep_State, Rep_Mail_Zip_Code, Rep_Mail_Zip4, Rep_Ph, Rep_Ph_Extension, Reserved_97, ORM_Ind, ORM_Termination_Date, TPOC_Date, TPOC_Amount, Funding_Delayed_Beyond_TPOC_Start_Date, Reserved_103, Claimant_1_Relationship, Claimant_1_TIN, Claimant_1_Last_Name, Claimant_1_First_Name, Claimant_1_Middle_Initial, Claimant_1_Mail_Addr_1, Claimant_1_Mail_Addr_2, Claimant_1City, Claimant_1_State, Claimant_1_Zip, Claimant_1_Zip4, Claimant_1_Ph, Claimant_1_Ph_Extension, Reserved_117, Claimant_1_Rep_Ind, C1_Rep_Last_Name, C1_Rep_First_Name, C1_Rep_Firm_Name, C1_Rep_TIN, C1_Rep_Mail_Addr_1, C1_Rep_Mail_Addr_2, C1_Rep_Mail_City, C1_Rep_State, C1_Rep_Zip, C1_Rep_Zip4, C1_Rep_Ph, C1_Rep_Ph_Extension, Reserved_131)
	SELECT 
	RECORD_IDENTIFIER, 
	DCN, 
	ACTION_TYPE, 
	injured_party_hicn AS INJ_PARTY_HICN, 
	o_injured_party_ssn AS INJ_PARTY_SSN, 
	injured_party_last_name AS INJ_PARTY_LAST_NAME, 
	injured_party_first_name AS INJ_PARTY_FIRST_NAME, 
	injured_party_middle_ini AS INJ_PARTY_MIDDLE_INI, 
	injured_party_gender AS INJ_PARTY_GENDER, 
	injured_party_dob AS INJ_PARTY_DOB, 
	RESERVED_11, 
	CMS_DATE_OF_INCIDENT, 
	INDUSTRY_DATE_OF_INCIDENT, 
	RESERVED_14, 
	ALLEGED_CAUSE_OF_INJURY, 
	STATE_OF_VENUE, 
	icd_indicator AS ICD_INDICATOR, 
	diag_code_1 AS DIAGNOSIS_CODE_1, 
	diag_code_2 AS DIAGNOSIS_CODE_2, 
	diag_code_3 AS DIAGNOSIS_CODE_3, 
	diag_code_4 AS DIAGNOSIS_CODE_4, 
	diag_code_5 AS DIAGNOSIS_CODE_5, 
	diag_code_6 AS DIAGNOSIS_CODE_6, 
	diag_code_7 AS DIAGNOSIS_CODE_7, 
	diag_code_8 AS DIAGNOSIS_CODE_8, 
	diag_code_9 AS DIAGNOSIS_CODE_9, 
	diag_code_10 AS DIAGNOSIS_CODE_10, 
	diag_code_11 AS DIAGNOSIS_CODE_11, 
	diag_code_12 AS DIAGNOSIS_CODE_12, 
	diag_code_13 AS DIAGNOSIS_CODE_13, 
	diag_code_14 AS DIAGNOSIS_CODE_14, 
	diag_code_15 AS DIAGNOSIS_CODE_15, 
	diag_code_16 AS DIAGNOSIS_CODE_16, 
	diag_code_17 AS DIAGNOSIS_CODE_17, 
	diag_code_18 AS DIAGNOSIS_CODE_18, 
	diag_code_19 AS DIAGNOSIS_CODE_19, 
	Reserved_56_out AS RESERVED_56, 
	descript_of_illness AS DESCRIPTION_OF_ILLNESS, 
	PRODUCT_LIABILITY_IND, 
	PRODUCT_GENERIC_NAME, 
	PRODUCT_BRAND_NAME, 
	PRODUCT_MANUFACTURER, 
	PRODUCT_ALLEGED_HARM, 
	RESERVED_63, 
	SELF_INSURED_IND, 
	SELF_INSURED_TYPE, 
	POLICYHOLDER_LAST_NAME, 
	POLICYHOLDER_FIRST_NAME, 
	DBA_NAME, 
	LEGAL_NAME, 
	RESERVED_70, 
	PLAN_INSURANCE_TYPE, 
	TIN, 
	OFFICE_CODE, 
	POLICY_NUMBER, 
	CLAIM_NUMBER, 
	PLAN_CONTACT_DEPARTMENT_NAME, 
	PLAN_CONTACT_LAST_NAME, 
	PLAN_CONTACT_FIRST_NAME, 
	PLAN_CONTACT_PH, 
	PLAN_CONTACT_PH_EXTENSION, 
	NO_FAULT_INSURANCE_LIMIT, 
	EXHAUST_DATE_FOR_DOLLAR_LIMIT, 
	RESERVED_83, 
	INJ_PARTY_REP_IND, 
	REP_LAST_NAME, 
	REP_FIRST_NAME, 
	REP_FIRM_NAME, 
	O_assign_null_values_to_TIN AS REP_TIN, 
	REP_MAIL_ADDR_1, 
	REP_MAIL_ADDR_2, 
	REP_CITY, 
	REP_STATE, 
	REP_MAIL_ZIP_CODE, 
	REP_MAIL_ZIP4, 
	REP_PH, 
	REP_PH_EXTENSION, 
	RESERVED_97, 
	ORM_IND, 
	ORM_TERMINATION_DATE, 
	TPOC_DATE, 
	TPOC_AMOUNT, 
	FUNDING_DELAYED_BEYOND_TPOC_START_DATE, 
	RESERVED_103, 
	c1_relationship AS CLAIMANT_1_RELATIONSHIP, 
	O_assign_null_values_to_TIN AS CLAIMANT_1_TIN, 
	c1_last_name AS CLAIMANT_1_LAST_NAME, 
	c1_first_name AS CLAIMANT_1_FIRST_NAME, 
	c1_middle_initial AS CLAIMANT_1_MIDDLE_INITIAL, 
	c1_mail_addr_1 AS CLAIMANT_1_MAIL_ADDR_1, 
	c1_mail_addr_2 AS CLAIMANT_1_MAIL_ADDR_2, 
	c1_city AS CLAIMANT_1CITY, 
	c1_state AS CLAIMANT_1_STATE, 
	c1_zip AS CLAIMANT_1_ZIP, 
	c1_zip4 AS CLAIMANT_1_ZIP4, 
	c1_ph AS CLAIMANT_1_PH, 
	c1_ph_extension AS CLAIMANT_1_PH_EXTENSION, 
	RESERVED_117, 
	c1_rep_ind AS CLAIMANT_1_REP_IND, 
	C1_REP_LAST_NAME, 
	C1_REP_FIRST_NAME, 
	C1_REP_FIRM_NAME, 
	O_assign_null_values_to_TIN AS C1_REP_TIN, 
	C1_REP_MAIL_ADDR_1, 
	C1_REP_MAIL_ADDR_2, 
	C1_REP_MAIL_CITY, 
	C1_REP_STATE, 
	C1_REP_ZIP, 
	C1_REP_ZIP4, 
	C1_REP_PH, 
	C1_REP_PH_EXTENSION, 
	RESERVED_131
	FROM EXP_Detail
),
SQ_work_claim_cms_auxiliary_extract AS (
	SELECT work_claim_cms_auxiliary_extract.work_claim_cms_auxiliary_extract_id, work_claim_cms_auxiliary_extract.claim_med_ak_id, work_claim_cms_auxiliary_extract.claim_party_occurrence_ak_id, work_claim_cms_auxiliary_extract.claim_med_plan_ak_id, work_claim_cms_auxiliary_extract.claim_occurrence_ak_id, work_claim_cms_auxiliary_extract.claim_party_ak_id, work_claim_cms_auxiliary_extract.record_identifier, work_claim_cms_auxiliary_extract.dcn, work_claim_cms_auxiliary_extract.injured_party_hicn, work_claim_cms_auxiliary_extract.injured_party_ssn, work_claim_cms_auxiliary_extract.injured_party_last_name, work_claim_cms_auxiliary_extract.injured_party_first_name, work_claim_cms_auxiliary_extract.c2_relationship, work_claim_cms_auxiliary_extract.c2_tin, work_claim_cms_auxiliary_extract.c2_last_name, work_claim_cms_auxiliary_extract.c2_first_name, work_claim_cms_auxiliary_extract.c2_middle_initial, work_claim_cms_auxiliary_extract.c2_mail_addr_1, work_claim_cms_auxiliary_extract.c2_mail_addr_2, work_claim_cms_auxiliary_extract.c2_city, work_claim_cms_auxiliary_extract.c2_state, work_claim_cms_auxiliary_extract.c2_zip, work_claim_cms_auxiliary_extract.c2_zip4, work_claim_cms_auxiliary_extract.c2_ph, work_claim_cms_auxiliary_extract.c2_ph_extension, work_claim_cms_auxiliary_extract.reserved_20, work_claim_cms_auxiliary_extract.c2_rep_ind, work_claim_cms_auxiliary_extract.c2_rep_last_name, work_claim_cms_auxiliary_extract.c2_rep_first_name, work_claim_cms_auxiliary_extract.c2_rep_firm_name, work_claim_cms_auxiliary_extract.c2_rep_tin, work_claim_cms_auxiliary_extract.c2_rep_mail_addr_1, work_claim_cms_auxiliary_extract.c2_rep_mail_addr_2, work_claim_cms_auxiliary_extract.c2_rep_city, work_claim_cms_auxiliary_extract.c2_rep_state, work_claim_cms_auxiliary_extract.c2_rep_zip, work_claim_cms_auxiliary_extract.c2_rep_zip4, work_claim_cms_auxiliary_extract.c2_rep_ph, work_claim_cms_auxiliary_extract.c2_rep_ph_extension, work_claim_cms_auxiliary_extract.reserved_34, work_claim_cms_auxiliary_extract.c3_relationship, work_claim_cms_auxiliary_extract.c3_tin, work_claim_cms_auxiliary_extract.c3_last_name, work_claim_cms_auxiliary_extract.c3_first_name, work_claim_cms_auxiliary_extract.c3_middle_initial, work_claim_cms_auxiliary_extract.c3_mail_addr_1, work_claim_cms_auxiliary_extract.c3_mail_addr_2, work_claim_cms_auxiliary_extract.c3_city, work_claim_cms_auxiliary_extract.c3_state, work_claim_cms_auxiliary_extract.c3_zip, work_claim_cms_auxiliary_extract.c3_zip4, work_claim_cms_auxiliary_extract.c3_ph, work_claim_cms_auxiliary_extract.c3_ph_extension, work_claim_cms_auxiliary_extract.reserved_48, work_claim_cms_auxiliary_extract.c3_rep_ind, work_claim_cms_auxiliary_extract.c3_rep_last_name, work_claim_cms_auxiliary_extract.c3_rep_first_name, work_claim_cms_auxiliary_extract.c3_rep_firm_name, work_claim_cms_auxiliary_extract.c3_rep_tin, work_claim_cms_auxiliary_extract.c3_rep_mail_addr_1, work_claim_cms_auxiliary_extract.c3_rep_mail_addr_2, work_claim_cms_auxiliary_extract.c3_rep_city, work_claim_cms_auxiliary_extract.c3_rep_state, work_claim_cms_auxiliary_extract.c3_rep_zip, work_claim_cms_auxiliary_extract.c3_rep_zip4, work_claim_cms_auxiliary_extract.c3_rep_ph, work_claim_cms_auxiliary_extract.c3_rep_ph_extension, work_claim_cms_auxiliary_extract.reserved_62, work_claim_cms_auxiliary_extract.c4_relationship, work_claim_cms_auxiliary_extract.c4_tin, work_claim_cms_auxiliary_extract.c4_last_name, work_claim_cms_auxiliary_extract.c4_first_name, work_claim_cms_auxiliary_extract.c4_middle_initial, work_claim_cms_auxiliary_extract.c4_mail_addr_1, work_claim_cms_auxiliary_extract.c4_mail_addr_2, work_claim_cms_auxiliary_extract.c4_city, work_claim_cms_auxiliary_extract.c4_state, work_claim_cms_auxiliary_extract.c4_zip, work_claim_cms_auxiliary_extract.c4_zip4, work_claim_cms_auxiliary_extract.c4_ph, work_claim_cms_auxiliary_extract.c4_ph_extension, work_claim_cms_auxiliary_extract.reserved_76, work_claim_cms_auxiliary_extract.c4_rep_ind, work_claim_cms_auxiliary_extract.c4_rep_last_name, work_claim_cms_auxiliary_extract.c4_rep_first_name, work_claim_cms_auxiliary_extract.c4_rep_firm_name, work_claim_cms_auxiliary_extract.c4_rep_tin, work_claim_cms_auxiliary_extract.c4_rep_mail_addr_1, work_claim_cms_auxiliary_extract.c4_rep_mail_addr_2, work_claim_cms_auxiliary_extract.c4_rep_city, work_claim_cms_auxiliary_extract.c4_rep_state, work_claim_cms_auxiliary_extract.c4_rep_zip, work_claim_cms_auxiliary_extract.c4_rep_zip4, work_claim_cms_auxiliary_extract.c4_rep_ph, work_claim_cms_auxiliary_extract.c4_rep_ph_extension, work_claim_cms_auxiliary_extract.tpoc_date_2, work_claim_cms_auxiliary_extract.tpoc_amount_2, work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_2, work_claim_cms_auxiliary_extract.tpoc_date_3, work_claim_cms_auxiliary_extract.tpoc_amount_3, work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_3, work_claim_cms_auxiliary_extract.tpoc_date_4, work_claim_cms_auxiliary_extract.tpoc_amount_4, work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_4, work_claim_cms_auxiliary_extract.tpoc_date_5, work_claim_cms_auxiliary_extract.tpoc_amount_5, work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_5, work_claim_cms_auxiliary_extract.reserved_102 
	FROM
	 work_claim_cms_auxiliary_extract 
	WHERE
	 audit_id =@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
),
SQ_work_claim_cms_auxiliary_extract_SSN AS (
	SELECT work_claim_cms_auxiliary_extract.work_claim_cms_auxiliary_extract_id, work_claim_cms_auxiliary_extract.injured_party_ssn 
	FROM
	 work_claim_cms_auxiliary_extract 
	WHERE
	 audit_id = @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
),
mplt_Detokinize_WebService_call_auxiliary_extract_SSN AS (WITH
	INPUT AS (
		
	),
	EXP_SSN_FEIN_TAXID AS (
		SELECT
		IN_id AS id,
		IN_ssn_fein_taxid AS ssn_fein_taxid,
		-- *INF*: LTRIM(RTRIM(ssn_fein_taxid))
		LTRIM(RTRIM(ssn_fein_taxid)) AS V_ssn_fein_taxid,
		-- *INF*: IIF(LENGTH(V_ssn_fein_taxid)=0  or IS_NUMBER(V_ssn_fein_taxid),'FEIN','NONFEIN')
		-- --IIF(LENGTH(V_ssn_fein_taxid)=11 AND REG_MATCH(V_ssn_fein_taxid,'[\da-zA-Z]+'),'NONFEIN','FEIN')
		-- 
		-- 
		IFF(
		    LENGTH(V_ssn_fein_taxid) = 0 or REGEXP_LIKE(V_ssn_fein_taxid, '^[0-9]+$'), 'FEIN', 'NONFEIN'
		) AS V_flag,
		V_flag AS flag,
		V_ssn_fein_taxid AS o_ssn_fein_taxid
		FROM INPUT
	),
	RTR_SSN_FEIN_TAXID AS (
		SELECT
		id,
		flag,
		o_ssn_fein_taxid AS ssn_fein_taxid,
		o_ssn_fein_taxid AS ssn_fein
		FROM EXP_SSN_FEIN_TAXID
	),
	RTR_SSN_FEIN_TAXID_FEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag = 'FEIN'),
	RTR_SSN_FEIN_TAXID_NONFEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag='NONFEIN'),
	EXP_Values AS (
		SELECT
		id AS ID,
		'Detokenize' AS Function,
		'SSN' AS Scheme,
		ssn_fein_taxid AS SSN_FEIN_TAXID,
		'DATAFEED_JOBS' AS Requestedby,
		'Claims' AS Application,
		'DataFeeds' AS Caller,
		-- *INF*: 'https://intsvc.wbconnect.com/services/TokenService/Token.svc'
		-- 
		-- 
		-- 
		'https://intsvc.wbconnect.com/services/TokenService/Token.svc' AS URL,
		ssn_fein AS SSN_FEIN3
		FROM RTR_SSN_FEIN_TAXID_NONFEIN_VALUES
	),
	Token AS (-- Token
	
		##############################################
	
		# TODO: Place holder for Custom transformation
	
		##############################################
	),
	EXP_Response AS (
		SELECT
		REF_Id AS ID,
		tns_Data0 AS TokenResponse,
		REF_SSN_FEIN_TAXID,
		-- *INF*: ltrim(rtrim(REPLACECHR(0,TokenResponse,'-',NULL)))
		-- 
		ltrim(rtrim(REGEXP_REPLACE(TokenResponse,'-','','i'))) AS o_TokenResponse
		FROM Token
	),
	Union_SSN_FEIN_TAXID AS (
		SELECT id AS ID, ssn_fein_taxid AS TokenReponse, ssn_fein_taxid AS SSN_FEIN
		FROM RTR_SSN_FEIN_TAXID_FEIN_VALUES
		UNION
		SELECT ID, o_TokenResponse AS TokenReponse, REF_SSN_FEIN_TAXID AS SSN_FEIN
		FROM EXP_Response
	),
	OUTPUT AS (
		SELECT
		ID AS OUT_id, 
		TokenReponse AS OUT_TokenResponse, 
		SSN_FEIN AS OUT_IN_ssn_fein_taxid
		FROM Union_SSN_FEIN_TAXID
	),
),
JNR_work_claim_cms_auxiliary_extract AS (SELECT
	SQ_work_claim_cms_auxiliary_extract.work_claim_cms_auxiliary_extract_id, 
	SQ_work_claim_cms_auxiliary_extract.claim_med_ak_id, 
	SQ_work_claim_cms_auxiliary_extract.claim_party_occurrence_ak_id, 
	SQ_work_claim_cms_auxiliary_extract.claim_med_plan_ak_id, 
	SQ_work_claim_cms_auxiliary_extract.claim_occurrence_ak_id, 
	SQ_work_claim_cms_auxiliary_extract.claim_party_ak_id, 
	SQ_work_claim_cms_auxiliary_extract.Record_Identifier, 
	SQ_work_claim_cms_auxiliary_extract.DCN, 
	SQ_work_claim_cms_auxiliary_extract.injured_party_hicn, 
	SQ_work_claim_cms_auxiliary_extract.injured_party_ssn, 
	SQ_work_claim_cms_auxiliary_extract.injured_party_last_name, 
	SQ_work_claim_cms_auxiliary_extract.injured_party_first_name, 
	SQ_work_claim_cms_auxiliary_extract.C2_Relationship, 
	SQ_work_claim_cms_auxiliary_extract.C2_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C2_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C2_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C2_Middle_Initial, 
	SQ_work_claim_cms_auxiliary_extract.C2_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C2_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C2_City, 
	SQ_work_claim_cms_auxiliary_extract.C2_State, 
	SQ_work_claim_cms_auxiliary_extract.C2_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C2_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C2_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C2_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_20, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Ind, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Firm_Name, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_City, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_State, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C2_Rep_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_34, 
	SQ_work_claim_cms_auxiliary_extract.C3_Relationship, 
	SQ_work_claim_cms_auxiliary_extract.C3_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C3_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C3_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C3_Middle_Initial, 
	SQ_work_claim_cms_auxiliary_extract.C3_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C3_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C3_City, 
	SQ_work_claim_cms_auxiliary_extract.C3_State, 
	SQ_work_claim_cms_auxiliary_extract.C3_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C3_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C3_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C3_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_48, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Ind, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Firm_Name, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_City, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_State, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C3_Rep_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_62, 
	SQ_work_claim_cms_auxiliary_extract.C4_Relationship, 
	SQ_work_claim_cms_auxiliary_extract.C4_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C4_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C4_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C4_Middle_Initial, 
	SQ_work_claim_cms_auxiliary_extract.C4_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C4_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C4_City, 
	SQ_work_claim_cms_auxiliary_extract.C4_State, 
	SQ_work_claim_cms_auxiliary_extract.C4_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C4_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C4_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C4_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_76, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Ind, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Last_Name, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_First_Name, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Firm_Name, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_TIN, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Mail_Addr_1, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Mail_Addr_2, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_City, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_State, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Zip, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Zip4, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Ph, 
	SQ_work_claim_cms_auxiliary_extract.C4_Rep_Ph_Extension, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Date_2, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Amount_2, 
	SQ_work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_2, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Date_3, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Amount_3, 
	SQ_work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_3, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Date_4, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Amount_4, 
	SQ_work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_4, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Date_5, 
	SQ_work_claim_cms_auxiliary_extract.TPOC_Amount_5, 
	SQ_work_claim_cms_auxiliary_extract.funding_dld_tpoc_st_date_5, 
	SQ_work_claim_cms_auxiliary_extract.Reserved_102, 
	mplt_Detokinize_WebService_call_auxiliary_extract_SSN.OUT_id AS IN_mplt_id, 
	mplt_Detokinize_WebService_call_auxiliary_extract_SSN.OUT_TokenResponse AS TokenResponse
	FROM SQ_work_claim_cms_auxiliary_extract
	INNER JOIN mplt_Detokinize_WebService_call_auxiliary_extract_SSN
	ON mplt_Detokinize_WebService_call_auxiliary_extract_SSN.OUT_id = SQ_work_claim_cms_auxiliary_extract.work_claim_cms_auxiliary_extract_id
),
EXP_Auxialiary AS (
	SELECT
	claim_med_ak_id,
	claim_party_occurrence_ak_id,
	claim_med_plan_ak_id,
	claim_occurrence_ak_id,
	claim_party_ak_id,
	Record_Identifier,
	DCN,
	injured_party_hicn,
	TokenResponse AS injured_party_ssn,
	injured_party_last_name,
	injured_party_first_name,
	C2_Relationship,
	C2_TIN,
	C2_Last_Name,
	C2_First_Name,
	C2_Middle_Initial,
	C2_Mail_Addr_1,
	C2_Mail_Addr_2,
	C2_City,
	C2_State,
	C2_Zip,
	C2_Zip4,
	C2_Ph,
	C2_Ph_Extension,
	Reserved_20,
	C2_Rep_Ind,
	C2_Rep_Last_Name,
	C2_Rep_First_Name,
	C2_Rep_Firm_Name,
	C2_Rep_TIN,
	C2_Rep_Mail_Addr_1,
	C2_Rep_Mail_Addr_2,
	C2_Rep_City,
	C2_Rep_State,
	C2_Rep_Zip,
	C2_Rep_Zip4,
	C2_Rep_Ph,
	C2_Rep_Ph_Extension,
	Reserved_34,
	C3_Relationship,
	C3_TIN,
	C3_Last_Name,
	C3_First_Name,
	C3_Middle_Initial,
	C3_Mail_Addr_1,
	C3_Mail_Addr_2,
	C3_City,
	C3_State,
	C3_Zip,
	C3_Zip4,
	C3_Ph,
	C3_Ph_Extension,
	Reserved_48,
	C3_Rep_Ind,
	C3_Rep_Last_Name,
	C3_Rep_First_Name,
	C3_Rep_Firm_Name,
	C3_Rep_TIN,
	C3_Rep_Mail_Addr_1,
	C3_Rep_Mail_Addr_2,
	C3_Rep_City,
	C3_Rep_State,
	C3_Rep_Zip,
	C3_Rep_Zip4,
	C3_Rep_Ph,
	C3_Rep_Ph_Extension,
	Reserved_62,
	C4_Relationship,
	C4_TIN,
	C4_Last_Name,
	C4_First_Name,
	C4_Middle_Initial,
	C4_Mail_Addr_1,
	C4_Mail_Addr_2,
	C4_City,
	C4_State,
	C4_Zip,
	C4_Zip4,
	C4_Ph,
	C4_Ph_Extension,
	Reserved_76,
	C4_Rep_Ind,
	C4_Rep_Last_Name,
	C4_Rep_First_Name,
	C4_Rep_Firm_Name,
	C4_Rep_TIN,
	C4_Rep_Mail_Addr_1,
	C4_Rep_Mail_Addr_2,
	C4_Rep_City,
	C4_Rep_State,
	C4_Rep_Zip,
	C4_Rep_Zip4,
	C4_Rep_Ph,
	C4_Rep_Ph_Extension,
	TPOC_Date_2,
	TPOC_Amount_2,
	funding_dld_tpoc_st_date_2,
	TPOC_Date_3,
	TPOC_Amount_3,
	funding_dld_tpoc_st_date_3,
	TPOC_Date_4,
	TPOC_Amount_4,
	funding_dld_tpoc_st_date_4,
	TPOC_Date_5,
	TPOC_Amount_5,
	funding_dld_tpoc_st_date_5,
	Reserved_102,
	'' AS O_Assing_null_val_to_TIN
	FROM JNR_work_claim_cms_auxiliary_extract
),
CMS_Claims_Input_File_auxiliary AS (
	INSERT INTO CMS_Claims_Input_File_auxiliary
	(Record_Identifier, DCN, Inj_Party_HICN, Inj_Party_SSN, Inj_Party_Last_Name, Inj_Party_First_Name, C2_Relationship, C2_TIN, C2_Last_Name, C2_First_Name, C2_Middle_Initial, C2_Mail_Addr_1, C2_Mail_Addr_2, C2_City, C2_State, C2_Zip, C2_Zip4, C2_Ph, C2_Ph_Extension, Reserved_20, C2_Rep_Ind, C2_Rep_Last_Name, C2_Rep_First_Name, C2_Rep_Firm_Name, C2_Rep_TIN, C2_Rep_Mail_Addr_1, C2_Rep_Mail_Addr_2, C2_Rep_City, C2_Rep_State, C2_Rep_Zip, C2_Rep_Zip4, C2_Rep_Ph, C2_Rep_Ph_Extension, Reserved_34, C3_Relationship, C3_TIN, C3_Last_Name, C3_First_Name, C3_Middle_Initial, C3_Mail_Addr_1, C3_Mail_Addr_2, C3_City, C3_State, C3_Zip, C3_Zip4, C3_Ph, C3_Ph_Extension, Reserved_48, C3_Rep_Ind, C3_Rep_Last_Name, C3_Rep_First_Name, C3_Rep_Firm_Name, C3_Rep_TIN, C3_Rep_Mail_Addr_1, C3_Rep_Mail_Addr_2, C3_Rep_City, C3_Rep_State, C3_Rep_Zip, C3_Rep_Zip4, C3_Rep_Ph, C3_Rep_Ph_Extension, Reserved_62, C4_Relationship, C4_TIN, C4_Last_Name, C4_First_Name, C4_Middle_Initial, C4_Mail_Addr_1, C4_Mail_Addr_2, C4_City, C4_State, C4_Zip, C4_Zip4, C4_Ph, C4_Ph_Extension, Reserved_76, C4_Rep_Ind, C4_Rep_Last_Name, C4_Rep_First_Name, C4_Rep_Firm_Name, C4_Rep_TIN, C4_Rep_Mail_Addr_1, C4_Rep_Mail_Addr_2, C4_Rep_City, C4_Rep_State, C4_Rep_Zip, C4_Rep_Zip4, C4_Rep_Ph, C4_Rep_Ph_Extension, TPOC_Date_2, TPOC_Amount_2, Funding_Dld_Beyond_TPOC_St_Date_2, TPOC_Date_3, TPOC_Amount_3, Funding_TPOC_St_Date_3, TPOC_Date_4, TPOC_Amount_4, Funding_TPOC_St_Date_4, TPOC_Date_5, TPOC_Amount_5, Funding_TPOC_St_Date_5, Reserved_102)
	SELECT 
	RECORD_IDENTIFIER, 
	DCN, 
	injured_party_hicn AS INJ_PARTY_HICN, 
	injured_party_ssn AS INJ_PARTY_SSN, 
	injured_party_last_name AS INJ_PARTY_LAST_NAME, 
	injured_party_first_name AS INJ_PARTY_FIRST_NAME, 
	C2_RELATIONSHIP, 
	O_Assing_null_val_to_TIN AS C2_TIN, 
	C2_LAST_NAME, 
	C2_FIRST_NAME, 
	C2_MIDDLE_INITIAL, 
	C2_MAIL_ADDR_1, 
	C2_MAIL_ADDR_2, 
	C2_CITY, 
	C2_STATE, 
	C2_ZIP, 
	C2_ZIP4, 
	C2_PH, 
	C2_PH_EXTENSION, 
	RESERVED_20, 
	C2_REP_IND, 
	C2_REP_LAST_NAME, 
	C2_REP_FIRST_NAME, 
	C2_REP_FIRM_NAME, 
	O_Assing_null_val_to_TIN AS C2_REP_TIN, 
	C2_REP_MAIL_ADDR_1, 
	C2_REP_MAIL_ADDR_2, 
	C2_REP_CITY, 
	C2_REP_STATE, 
	C2_REP_ZIP, 
	C2_REP_ZIP4, 
	C2_REP_PH, 
	C2_REP_PH_EXTENSION, 
	RESERVED_34, 
	C3_RELATIONSHIP, 
	O_Assing_null_val_to_TIN AS C3_TIN, 
	C3_LAST_NAME, 
	C3_FIRST_NAME, 
	C3_MIDDLE_INITIAL, 
	C3_MAIL_ADDR_1, 
	C3_MAIL_ADDR_2, 
	C3_CITY, 
	C3_STATE, 
	C3_ZIP, 
	C3_ZIP4, 
	C3_PH, 
	C3_PH_EXTENSION, 
	RESERVED_48, 
	C3_REP_IND, 
	C3_REP_LAST_NAME, 
	C3_REP_FIRST_NAME, 
	C3_REP_FIRM_NAME, 
	O_Assing_null_val_to_TIN AS C3_REP_TIN, 
	C3_REP_MAIL_ADDR_1, 
	C3_REP_MAIL_ADDR_2, 
	C3_REP_CITY, 
	C3_REP_STATE, 
	C3_REP_ZIP, 
	C3_REP_ZIP4, 
	C3_REP_PH, 
	C3_REP_PH_EXTENSION, 
	RESERVED_62, 
	C4_RELATIONSHIP, 
	O_Assing_null_val_to_TIN AS C4_TIN, 
	C4_LAST_NAME, 
	C4_FIRST_NAME, 
	C4_MIDDLE_INITIAL, 
	C4_MAIL_ADDR_1, 
	C4_MAIL_ADDR_2, 
	C4_CITY, 
	C4_STATE, 
	C4_ZIP, 
	C4_ZIP4, 
	C4_PH, 
	C4_PH_EXTENSION, 
	RESERVED_76, 
	C4_REP_IND, 
	C4_REP_LAST_NAME, 
	C4_REP_FIRST_NAME, 
	C4_REP_FIRM_NAME, 
	O_Assing_null_val_to_TIN AS C4_REP_TIN, 
	C4_REP_MAIL_ADDR_1, 
	C4_REP_MAIL_ADDR_2, 
	C4_REP_CITY, 
	C4_REP_STATE, 
	C4_REP_ZIP, 
	C4_REP_ZIP4, 
	C4_REP_PH, 
	C4_REP_PH_EXTENSION, 
	TPOC_DATE_2, 
	TPOC_AMOUNT_2, 
	funding_dld_tpoc_st_date_2 AS FUNDING_DLD_BEYOND_TPOC_ST_DATE_2, 
	TPOC_DATE_3, 
	TPOC_AMOUNT_3, 
	funding_dld_tpoc_st_date_3 AS FUNDING_TPOC_ST_DATE_3, 
	TPOC_DATE_4, 
	TPOC_AMOUNT_4, 
	funding_dld_tpoc_st_date_4 AS FUNDING_TPOC_ST_DATE_4, 
	TPOC_DATE_5, 
	TPOC_AMOUNT_5, 
	funding_dld_tpoc_st_date_5 AS FUNDING_TPOC_ST_DATE_5, 
	RESERVED_102
	FROM EXP_Auxialiary
),
SQ_Claim_File_Header AS (
	SELECT
		sup_cms_tin_office_id,
		crrnt_snpsht_flag,
		audit_id,
		eff_from_date,
		eff_to_date,
		source_sys_id,
		created_date,
		modified_date,
		cms_rre_id,
		office_tin_num,
		office_code,
		office_name,
		office_mail_address1,
		office_mail_address2,
		office_mail_city,
		office_mail_state,
		office_mail_zip,
		office_mail_zip4
	FROM sup_cms_tin_office
	WHERE crrnt_snpsht_flag=1
),
EXP_Header AS (
	SELECT
	'NGCH' AS Record_Identifier,
	cms_rre_id,
	-- *INF*: lpad(rtrim(cms_rre_id),9,'0')
	lpad(rtrim(cms_rre_id), 9, '0') AS cms_rre_id_out,
	'NGHPCLM' AS Reporting_File_Type,
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS File_Submission_date,
	'' AS Default_String
	FROM SQ_Claim_File_Header
),
CMS_Claims_Input_File_Header AS (
	INSERT INTO CMS_Claims_Input_File_HeaderTrailer
	(Record_Identifier, Reporter_Id, Reporting_File_Type, File_Submission_Date, File_Record_Count, Reserved)
	SELECT 
	RECORD_IDENTIFIER, 
	cms_rre_id_out AS REPORTER_ID, 
	REPORTING_FILE_TYPE, 
	File_Submission_date AS FILE_SUBMISSION_DATE, 
	Default_String AS FILE_RECORD_COUNT, 
	Default_String AS RESERVED
	FROM EXP_Header
),
SQ_CMS_Claim_Input_File AS (

-- TODO Manual --

),
EXP_1 AS (
	SELECT
	Record_Identifier,
	DCN,
	-- *INF*: rtrim(DCN)
	rtrim(DCN) AS DCN1,
	Other_values AS Other_Values
	FROM SQ_CMS_Claim_Input_File
),
SRT_1 AS (
	SELECT
	Record_Identifier, 
	DCN1 AS DCN, 
	Other_Values
	FROM EXP_1
	ORDER BY DCN ASC
),
CMS_Claim_Input_File AS (
	INSERT INTO CMS_Claim_Input_File
	(Record_Identifier, DCN, Other_values)
	SELECT 
	RECORD_IDENTIFIER, 
	DCN, 
	Other_Values AS OTHER_VALUES
	FROM SRT_1
),
SQ_Claim_File_Trailer AS (
	SELECT
		sup_cms_tin_office_id,
		crrnt_snpsht_flag,
		audit_id,
		eff_from_date,
		eff_to_date,
		source_sys_id,
		created_date,
		modified_date,
		cms_rre_id,
		office_tin_num,
		office_code,
		office_name,
		office_mail_address1,
		office_mail_address2,
		office_mail_city,
		office_mail_state,
		office_mail_zip,
		office_mail_zip4
	FROM sup_cms_tin_office1
	WHERE crrnt_snpsht_flag=1
),
EXP_Trailer AS (
	SELECT
	'NGCT' AS Record_Identifier,
	cms_rre_id,
	-- *INF*: lpad(rtrim(cms_rre_id),9,'0')
	lpad(rtrim(cms_rre_id), 9, '0') AS cms_rre_id_out,
	'NGHPCLM' AS Reporting_File_Type,
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS File_Submission_date,
	-- *INF*: :LKP.LKP_Record_Count (1)
	LKP_RECORD_COUNT_1.claim_med_ak_id AS v_File_Record_Count,
	-- *INF*: LPAD(to_char(v_File_Record_Count),7,'0')
	-- 
	LPAD(to_char(v_File_Record_Count), 7, '0') AS File_Record_Count,
	'' AS Default_String
	FROM SQ_Claim_File_Trailer
	LEFT JOIN LKP_RECORD_COUNT LKP_RECORD_COUNT_1
	ON LKP_RECORD_COUNT_1.dummy_integer = 1

),
CMS_Claims_Input_File_Trailer AS (
	INSERT INTO CMS_Claims_Input_File_HeaderTrailer
	(Record_Identifier, Reporter_Id, Reporting_File_Type, File_Submission_Date, File_Record_Count, Reserved)
	SELECT 
	RECORD_IDENTIFIER, 
	cms_rre_id_out AS REPORTER_ID, 
	REPORTING_FILE_TYPE, 
	File_Submission_date AS FILE_SUBMISSION_DATE, 
	FILE_RECORD_COUNT, 
	Default_String AS RESERVED
	FROM EXP_Trailer
),