WITH
SQ_SUP_CLAIM_DIVISION_STAGE AS (
	SELECT
		SUP_CLAIM_DIVISION_ID,
		DIVISION_CODE,
		DIVISION_DESC,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM SUP_CLAIM_DIVISION_STAGE
),
EXP_SUP_CLAIM_DIVISION_STAGE AS (
	SELECT
	SUP_CLAIM_DIVISION_ID,
	DIVISION_CODE,
	DIVISION_DESC,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_SUP_CLAIM_DIVISION_STAGE
),
ARCH_SUP_CLAIM_DIVISION_STAGE AS (
	INSERT INTO ARCH_SUP_CLAIM_DIVISION_STAGE
	(SUP_CLAIM_DIVISION_ID, DIVISION_CODE, DIVISION_DESC, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	SUP_CLAIM_DIVISION_ID, 
	DIVISION_CODE, 
	DIVISION_DESC, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_SUP_CLAIM_DIVISION_STAGE
),