WITH
SQ_SUP_CHANGE_REASON_STAGE AS (
	SELECT
		SUP_CHANGE_REASON_ID,
		REASON_CODE,
		REASON_DESC,
		MODIFIED_DATE,
		MODIFIED_USER_ID,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM SUP_CHANGE_REASON_STAGE
),
EXPTRANS AS (
	SELECT
	SUP_CHANGE_REASON_ID,
	REASON_CODE,
	REASON_DESC,
	MODIFIED_DATE,
	MODIFIED_USER_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_SUP_CHANGE_REASON_STAGE
),
ARCH_SUP_CHANGE_REASON_STAGE AS (
	INSERT INTO ARCH_SUP_CHANGE_REASON_STAGE
	(SUP_CHANGE_REASON_ID, REASON_CODE, REASON_DESC, MODIFIED_DATE, MODIFIED_USER_ID, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	SUP_CHANGE_REASON_ID, 
	REASON_CODE, 
	REASON_DESC, 
	MODIFIED_DATE, 
	MODIFIED_USER_ID, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXPTRANS
),