WITH
SQ_workers_cps_loss_stage AS (
	SELECT
		workers_cps_loss_id,
		cwc_claim_nbr,
		cwc_object_seq_nbr,
		cwc_commission_nbr,
		cwc_dpt_nm,
		cwc_employer_loc,
		cwc_employer_type,
		cwc_nature_bus_des,
		cwc_osha_cd,
		cwc_self_ins_ind,
		cwc_specific_prd,
		cwc_state_epr_nbr,
		cwc_state_fund_ind,
		cwc_cer_nbr,
		cwc_epr_not_dt,
		cwc_hired_dt,
		cwc_dpt_cd,
		cwc_acc_dpt_cd,
		cwc_epr_pms_ind,
		cwc_cmt_des_id,
		cwc_injured_acy_id,
		cwc_injury_des_id,
		cwc_ofc_ptn_ind,
		cwc_plant_cd,
		cwc_sfg_pvd_ind,
		cwc_sfg_used_ind,
		cwc_state_hired_cd,
		cwc_workday_beg_tm,
		cwc_works_from_tm,
		cwc_works_to_tm,
		cwc_avg_week_wage,
		cwc_days_per_week,
		cwc_full_pay_inj,
		cwc_hours_worked,
		cwc_lst_workday_dt,
		cwc_pay_kind_amt,
		cwc_salary_ctu_ind,
		cwc_wage_rt,
		cwc_weeks_worked,
		cwc_update_opr_id,
		cwc_pmsd_ts,
		cwc_upd_ts,
		cwc_med_ind,
		cwc_entry_opr_id,
		cwc_create_ts,
		cwc_jur_state_cd,
		cwc_light_duty_ind,
		cwc_disability_dt,
		cwc_ret_to_work_dt,
		cwc_rep_to_car_dt,
		cwc_max_med_imp_dt,
		cwc_dependents_nbr,
		cwc_pex_md_con_ind,
		cwc_prior_inj_ind,
		cwc_years_emp_id,
		cwc_time_pos_id,
		cwc_spm_amt,
		cwc_spm_fqy_cd,
		cwc_spm_des_id,
		cwc_cmb_avg_wk_amt,
		cwc_cmb_wk_cps_amt,
		cwc_body_part_cd,
		cwc_nature_inj_cd,
		cwc_cause_inj_cd,
		cwc_exposure_dt,
		cwc_scar_des_id,
		cwc_treatment_ind,
		cwc_surgery_ind,
		cwc_scarring_ind,
		cwc_impairment_ind,
		cwc_voc_reh_ind,
		cwc_location_nbr,
		cwc_loc_des_id,
		cwc_loc_clt_id,
		cwc_emp_class_cd,
		cwc_cov_state_cd,
		cwc_clsdes_seq_nbr,
		cwc_state_all_ind,
		cwc_class_sub_cd,
		cwc_loss_cov_cd,
		cwc_loss_cat_cd,
		cwc_employ_sta_cd,
		cwc_ss_ind,
		cwc_ump_ind,
		cwc_pension_ind,
		cwc_spe_fund_ind,
		cwc_other_ind,
		cwc_method_set_cd,
		cwc_mgr_care_cd,
		cwc_los_con_act_cd,
		cwc_type_loss_cd,
		cwc_type_rcv_cd,
		cwc_type_cov_cd,
		cwc_type_set_cd,
		cwc_cls_seq_nbr,
		cwc_chg_rpt_ind,
		cwc_epr_dif_loc_id,
		cwc_sbr_amt,
		cwc_fraud_amt,
		cwc_joint_cov_amt,
		cwc_compromise_amt,
		cwc_death_dt,
		cwc_fraud_cd,
		cwc_num_wk_off_wrk,
		cwc_marital_sta,
		cwc_tax_file_sta,
		cwc_num_dep_child,
		cwc_num_dep_other,
		cwc_num_exemp,
		cwc_exemp_type,
		cwc_emp_blind,
		cwc_emp_over_65,
		cwc_spouse_blind,
		cwc_spouse_over_65,
		cwc_man_class_cd,
		cwc_educate_level,
		cwc_rel_med_ind,
		cwc_rel_ssn_ind,
		cwc_piece_wrk_hrs,
		cwc_gross_amt_type,
		cwc_gross_wage_amt,
		cwc_emp_rcv_meals,
		cwc_emp_rcv_room,
		cwc_emp_rcv_tips,
		cwc_wkly_atty_fee,
		cwc_ttd_rate,
		cwc_ppd_rate,
		cwc_ptd_rate,
		cwc_dly_ttd_rate,
		cwc_overtime_amt,
		cwc_overtime_after,
		cwc_emp_hour_day,
		cwc_emp_hour_wk,
		cwc_emp_pt_hour_wk,
		cwc_wage_eff_dt,
		cwc_phys_rest_ind,
		cwc_premises_cd,
		cwc_inj_sub_abuse,
		cwc_inj_safe_dev,
		cwc_inj_obey_rule,
		cwc_result_occ_inj,
		cwc_death_result,
		cwc_drg_card_sta,
		cwc_drg_crd_act_dt,
		cwc_drg_crd_exp_dt,
		cwc_care_directed,
		cwc_care_by_whom,
		cwc_med_srv_rend,
		cwc_emerg_treat,
		cwc_hospitalized,
		cwc_length_disable,
		cwc_dis_perm_psble,
		cwc_unsafe_act,
		cwc_hazard_cond,
		cwc_rsp_for_injury,
		cwc_depart_num,
		cwc_shift_num,
		cwc_med_auth_dt,
		cwc_result_occ_dis,
		cwc_emplyr_type_cd,
		cwc_sub_sta_exp_dt,
		cwc_fringe_dis_amt,
		cwc_pt_hour_wk,
		cwc_client_id,
		cwc_claim_cat_cd,
		cwc_subro_ind,
		cwc_invest_ind,
		cwc_out_deduct_ind,
		cwc_subcont_ind,
		cwc_activity_sta,
		cwc_rei_notify_dt,
		cwc_emp_std_ind_cd,
		cwc_ot_aft_hrs_day,
		extract_date,
		as_of_date,
		record_count,
		source_system_id,
		cwc_init_treatment,
		cwc_send_to_state,
		cwc_state_send_ts,
		cwc_maint_type_cd,
		cwc_state_clm_nbr,
		cwc_send_sroi,
		cwc_send_sroi_ts,
		cwc_sroi_maint_typ,
		cwc_pts_rate,
		cwc_lgl_reprsnt_dt,
		cwc_sroi_st_trans,
		cwc_final_mtc_dt,
		cwc_sroi_start_dt,
		cwc_clt_claim_nbr,
		cwc_work_week_type,
		cwc_work_week_days,
		cwc_lost_time_on_doi,
		cwc_emp_security_id,
		cwc_epr_lost_time_notified_date,
		NaicsCode,
		cwc_full_denial_reason_cd,
		cwc_iaiabc_loss_type_cd,
		cwc_froi_late_reason_cd,
		cwc_froi_spec_late_reason_cd,
		froi_claim_type,
		cwc_auto_adj_ind,
		cwc_compensable_ind,
		cwc_body_part_location_cd,
		cwc_fingers_toes_location_code,
		cwc_froi_cancel_reason_cd,
		cwc_cancel_reason_cmt_id,
		cwc_deny_reason_cmt_id,
		cwc_disability_aft_wait_prd_dt,
		injury_severity_type,
		cwc_loec_paid_per,
		cwc_pre_disability_per,
		cwc_act_loss_cndtn_cd,
		cwc_temp_dbe_cd,
		cwc_curr_dt_disability_beg,
		cwc_emp_know_crr_dt_disability,
		cwc_wb_know_crr_dt_disability,
		cwc_met_rpt_rqmts_dt
	FROM workers_cps_loss_stage
),
EXP_WORKERS_CPS_LOSS_STAGE AS (
	SELECT
	workers_cps_loss_id AS WORKERS_CPS_LOSS_ID,
	cwc_claim_nbr AS CWC_CLAIM_NBR,
	cwc_object_seq_nbr AS CWC_OBJECT_SEQ_NBR,
	cwc_commission_nbr AS CWC_COMMISSION_NBR,
	cwc_dpt_nm AS CWC_DPT_NM,
	cwc_employer_loc AS CWC_EMPLOYER_LOC,
	cwc_employer_type AS CWC_EMPLOYER_TYPE,
	cwc_nature_bus_des AS CWC_NATURE_BUS_DES,
	cwc_osha_cd AS CWC_OSHA_CD,
	cwc_self_ins_ind AS CWC_SELF_INS_IND,
	cwc_specific_prd AS CWC_SPECIFIC_PRD,
	cwc_state_epr_nbr AS CWC_STATE_EPR_NBR,
	cwc_state_fund_ind AS CWC_STATE_FUND_IND,
	cwc_cer_nbr AS CWC_CER_NBR,
	cwc_epr_not_dt AS CWC_EPR_NOT_DT,
	cwc_hired_dt AS CWC_HIRED_DT,
	cwc_dpt_cd AS CWC_DPT_CD,
	cwc_acc_dpt_cd AS CWC_ACC_DPT_CD,
	cwc_epr_pms_ind AS CWC_EPR_PMS_IND,
	cwc_cmt_des_id AS CWC_CMT_DES_ID,
	cwc_injured_acy_id AS CWC_INJURED_ACY_ID,
	cwc_injury_des_id AS CWC_INJURY_DES_ID,
	cwc_ofc_ptn_ind AS CWC_OFC_PTN_IND,
	cwc_plant_cd AS CWC_PLANT_CD,
	cwc_sfg_pvd_ind AS CWC_SFG_PVD_IND,
	cwc_sfg_used_ind AS CWC_SFG_USED_IND,
	cwc_state_hired_cd AS CWC_STATE_HIRED_CD,
	cwc_workday_beg_tm AS CWC_WORKDAY_BEG_TM,
	cwc_works_from_tm AS CWC_WORKS_FROM_TM,
	cwc_works_to_tm AS CWC_WORKS_TO_TM,
	cwc_avg_week_wage AS CWC_AVG_WEEK_WAGE,
	cwc_days_per_week AS CWC_DAYS_PER_WEEK,
	cwc_full_pay_inj AS CWC_FULL_PAY_INJ,
	cwc_hours_worked AS CWC_HOURS_WORKED,
	cwc_lst_workday_dt AS CWC_LST_WORKDAY_DT,
	cwc_pay_kind_amt AS CWC_PAY_KIND_AMT,
	cwc_salary_ctu_ind AS CWC_SALARY_CTU_IND,
	cwc_wage_rt AS CWC_WAGE_RT,
	cwc_weeks_worked AS CWC_WEEKS_WORKED,
	cwc_update_opr_id AS CWC_UPDATE_OPR_ID,
	cwc_pmsd_ts AS CWC_PMSD_TS,
	cwc_upd_ts AS CWC_UPD_TS,
	cwc_med_ind AS CWC_MED_IND,
	cwc_entry_opr_id AS CWC_ENTRY_OPR_ID,
	cwc_create_ts AS CWC_CREATE_TS,
	cwc_jur_state_cd AS CWC_JUR_STATE_CD,
	cwc_light_duty_ind AS CWC_LIGHT_DUTY_IND,
	cwc_disability_dt AS CWC_DISABILITY_DT,
	cwc_ret_to_work_dt AS CWC_RET_TO_WORK_DT,
	cwc_rep_to_car_dt AS CWC_REP_TO_CAR_DT,
	cwc_max_med_imp_dt AS CWC_MAX_MED_IMP_DT,
	cwc_dependents_nbr AS CWC_DEPENDENTS_NBR,
	cwc_pex_md_con_ind AS CWC_PEX_MD_CON_IND,
	cwc_prior_inj_ind AS CWC_PRIOR_INJ_IND,
	cwc_years_emp_id AS CWC_YEARS_EMP_ID,
	cwc_time_pos_id AS CWC_TIME_POS_ID,
	cwc_spm_amt AS CWC_SPM_AMT,
	cwc_spm_fqy_cd AS CWC_SPM_FQY_CD,
	cwc_spm_des_id AS CWC_SPM_DES_ID,
	cwc_cmb_avg_wk_amt AS CWC_CMB_AVG_WK_AMT,
	cwc_cmb_wk_cps_amt AS CWC_CMB_WK_CPS_AMT,
	cwc_body_part_cd AS CWC_BODY_PART_CD,
	cwc_nature_inj_cd AS CWC_NATURE_INJ_CD,
	cwc_cause_inj_cd AS CWC_CAUSE_INJ_CD,
	cwc_exposure_dt AS CWC_EXPOSURE_DT,
	cwc_scar_des_id AS CWC_SCAR_DES_ID,
	cwc_treatment_ind AS CWC_TREATMENT_IND,
	cwc_surgery_ind AS CWC_SURGERY_IND,
	cwc_scarring_ind AS CWC_SCARRING_IND,
	cwc_impairment_ind AS CWC_IMPAIRMENT_IND,
	cwc_voc_reh_ind AS CWC_VOC_REH_IND,
	cwc_location_nbr AS CWC_LOCATION_NBR,
	cwc_loc_des_id AS CWC_LOC_DES_ID,
	cwc_loc_clt_id AS CWC_LOC_CLT_ID,
	cwc_emp_class_cd AS CWC_EMP_CLASS_CD,
	cwc_cov_state_cd AS CWC_COV_STATE_CD,
	cwc_clsdes_seq_nbr AS CWC_CLSDES_SEQ_NBR,
	cwc_state_all_ind AS CWC_STATE_ALL_IND,
	cwc_class_sub_cd AS CWC_CLASS_SUB_CD,
	cwc_loss_cov_cd AS CWC_LOSS_COV_CD,
	cwc_loss_cat_cd AS CWC_LOSS_CAT_CD,
	cwc_employ_sta_cd AS CWC_EMPLOY_STA_CD,
	cwc_ss_ind AS CWC_SS_IND,
	cwc_ump_ind AS CWC_UMP_IND,
	cwc_pension_ind AS CWC_PENSION_IND,
	cwc_spe_fund_ind AS CWC_SPE_FUND_IND,
	cwc_other_ind AS CWC_OTHER_IND,
	cwc_method_set_cd AS CWC_METHOD_SET_CD,
	cwc_mgr_care_cd AS CWC_MGR_CARE_CD,
	cwc_los_con_act_cd AS CWC_LOS_CON_ACT_CD,
	cwc_type_loss_cd AS CWC_TYPE_LOSS_CD,
	cwc_type_rcv_cd AS CWC_TYPE_RCV_CD,
	cwc_type_cov_cd AS CWC_TYPE_COV_CD,
	cwc_type_set_cd AS CWC_TYPE_SET_CD,
	cwc_cls_seq_nbr AS CWC_CLS_SEQ_NBR,
	cwc_chg_rpt_ind AS CWC_CHG_RPT_IND,
	cwc_epr_dif_loc_id AS CWC_EPR_DIF_LOC_ID,
	cwc_sbr_amt AS CWC_SBR_AMT,
	cwc_fraud_amt AS CWC_FRAUD_AMT,
	cwc_joint_cov_amt AS CWC_JOINT_COV_AMT,
	cwc_compromise_amt AS CWC_COMPROMISE_AMT,
	cwc_death_dt AS CWC_DEATH_DT,
	cwc_fraud_cd AS CWC_FRAUD_CD,
	cwc_num_wk_off_wrk AS CWC_NUM_WK_OFF_WRK,
	cwc_marital_sta AS CWC_MARITAL_STA,
	cwc_tax_file_sta AS CWC_TAX_FILE_STA,
	cwc_num_dep_child AS CWC_NUM_DEP_CHILD,
	cwc_num_dep_other AS CWC_NUM_DEP_OTHER,
	cwc_num_exemp AS CWC_NUM_EXEMP,
	cwc_exemp_type AS CWC_EXEMP_TYPE,
	cwc_emp_blind AS CWC_EMP_BLIND,
	cwc_emp_over_65 AS CWC_EMP_OVER_65,
	cwc_spouse_blind AS CWC_SPOUSE_BLIND,
	cwc_spouse_over_65 AS CWC_SPOUSE_OVER_65,
	cwc_man_class_cd AS CWC_MAN_CLASS_CD,
	cwc_educate_level AS CWC_EDUCATE_LEVEL,
	cwc_rel_med_ind AS CWC_REL_MED_IND,
	cwc_rel_ssn_ind AS CWC_REL_SSN_IND,
	cwc_piece_wrk_hrs AS CWC_PIECE_WRK_HRS,
	cwc_gross_amt_type AS CWC_GROSS_AMT_TYPE,
	cwc_gross_wage_amt AS CWC_GROSS_WAGE_AMT,
	cwc_emp_rcv_meals AS CWC_EMP_RCV_MEALS,
	cwc_emp_rcv_room AS CWC_EMP_RCV_ROOM,
	cwc_emp_rcv_tips AS CWC_EMP_RCV_TIPS,
	cwc_wkly_atty_fee AS CWC_WKLY_ATTY_FEE,
	cwc_ttd_rate AS CWC_TTD_RATE,
	cwc_ppd_rate AS CWC_PPD_RATE,
	cwc_ptd_rate AS CWC_PTD_RATE,
	cwc_dly_ttd_rate AS CWC_DLY_TTD_RATE,
	cwc_overtime_amt AS CWC_OVERTIME_AMT,
	cwc_overtime_after AS CWC_OVERTIME_AFTER,
	cwc_emp_hour_day AS CWC_EMP_HOUR_DAY,
	cwc_emp_hour_wk AS CWC_EMP_HOUR_WK,
	cwc_emp_pt_hour_wk AS CWC_EMP_PT_HOUR_WK,
	cwc_wage_eff_dt AS CWC_WAGE_EFF_DT,
	cwc_phys_rest_ind AS CWC_PHYS_REST_IND,
	cwc_premises_cd AS CWC_PREMISES_CD,
	cwc_inj_sub_abuse AS CWC_INJ_SUB_ABUSE,
	cwc_inj_safe_dev AS CWC_INJ_SAFE_DEV,
	cwc_inj_obey_rule AS CWC_INJ_OBEY_RULE,
	cwc_result_occ_inj AS CWC_RESULT_OCC_INJ,
	cwc_death_result AS CWC_DEATH_RESULT,
	cwc_drg_card_sta AS CWC_DRG_CARD_STA,
	cwc_drg_crd_act_dt AS CWC_DRG_CRD_ACT_DT,
	cwc_drg_crd_exp_dt AS CWC_DRG_CRD_EXP_DT,
	cwc_care_directed AS CWC_CARE_DIRECTED,
	cwc_care_by_whom AS CWC_CARE_BY_WHOM,
	cwc_med_srv_rend AS CWC_MED_SRV_REND,
	cwc_emerg_treat AS CWC_EMERG_TREAT,
	cwc_hospitalized AS CWC_HOSPITALIZED,
	cwc_length_disable AS CWC_LENGTH_DISABLE,
	cwc_dis_perm_psble AS CWC_DIS_PERM_PSBLE,
	cwc_unsafe_act AS CWC_UNSAFE_ACT,
	cwc_hazard_cond AS CWC_HAZARD_COND,
	cwc_rsp_for_injury AS CWC_RSP_FOR_INJURY,
	cwc_depart_num AS CWC_DEPART_NUM,
	cwc_shift_num AS CWC_SHIFT_NUM,
	cwc_med_auth_dt AS CWC_MED_AUTH_DT,
	cwc_result_occ_dis AS CWC_RESULT_OCC_DIS,
	cwc_emplyr_type_cd AS CWC_EMPLYR_TYPE_CD,
	cwc_sub_sta_exp_dt AS CWC_SUB_STA_EXP_DT,
	cwc_fringe_dis_amt AS CWC_FRINGE_DIS_AMT,
	cwc_pt_hour_wk AS CWC_PT_HOUR_WK,
	cwc_client_id AS CWC_CLIENT_ID,
	cwc_claim_cat_cd AS CWC_CLAIM_CAT_CD,
	cwc_subro_ind AS CWC_SUBRO_IND,
	cwc_invest_ind AS CWC_INVEST_IND,
	cwc_out_deduct_ind AS CWC_OUT_DEDUCT_IND,
	cwc_subcont_ind AS CWC_SUBCONT_IND,
	cwc_activity_sta AS CWC_ACTIVITY_STA,
	cwc_rei_notify_dt AS CWC_REI_NOTIFY_DT,
	cwc_emp_std_ind_cd AS CWC_EMP_STD_IND_CD,
	cwc_ot_aft_hrs_day AS CWC_OT_AFT_HRS_DAY,
	extract_date AS EXTRACT_DATE,
	as_of_date AS AS_OF_DATE,
	record_count AS RECORD_COUNT,
	source_system_id AS SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP,
	cwc_init_treatment,
	cwc_send_to_state,
	cwc_state_send_ts,
	cwc_maint_type_cd,
	cwc_state_clm_nbr,
	cwc_send_sroi,
	cwc_send_sroi_ts,
	cwc_sroi_maint_typ,
	cwc_pts_rate,
	cwc_lgl_reprsnt_dt,
	cwc_sroi_st_trans,
	cwc_final_mtc_dt,
	cwc_sroi_start_dt,
	cwc_clt_claim_nbr,
	cwc_work_week_type,
	cwc_work_week_days,
	cwc_lost_time_on_doi,
	cwc_emp_security_id,
	cwc_epr_lost_time_notified_date,
	NaicsCode,
	cwc_full_denial_reason_cd,
	cwc_iaiabc_loss_type_cd,
	cwc_froi_late_reason_cd,
	cwc_froi_spec_late_reason_cd,
	froi_claim_type,
	cwc_auto_adj_ind,
	cwc_compensable_ind,
	cwc_body_part_location_cd,
	cwc_fingers_toes_location_code,
	cwc_froi_cancel_reason_cd,
	cwc_cancel_reason_cmt_id,
	cwc_deny_reason_cmt_id,
	cwc_disability_aft_wait_prd_dt,
	injury_severity_type,
	cwc_loec_paid_per,
	cwc_pre_disability_per,
	cwc_act_loss_cndtn_cd,
	cwc_temp_dbe_cd,
	cwc_curr_dt_disability_beg,
	cwc_emp_know_crr_dt_disability,
	cwc_wb_know_crr_dt_disability,
	cwc_met_rpt_rqmts_dt
	FROM SQ_workers_cps_loss_stage
),
ARCH_WORKERS_CPS_LOSS_STAGE AS (
	INSERT INTO ARCH_WORKERS_CPS_LOSS_STAGE
	(workers_cps_loss_id, cwc_claim_nbr, cwc_object_seq_nbr, cwc_commission_nbr, cwc_dpt_nm, cwc_employer_loc, cwc_employer_type, cwc_nature_bus_des, cwc_osha_cd, cwc_self_ins_ind, cwc_specific_prd, cwc_state_epr_nbr, cwc_state_fund_ind, cwc_cer_nbr, cwc_epr_not_dt, cwc_hired_dt, cwc_dpt_cd, cwc_acc_dpt_cd, cwc_epr_pms_ind, cwc_cmt_des_id, cwc_injured_acy_id, cwc_injury_des_id, cwc_ofc_ptn_ind, cwc_plant_cd, cwc_sfg_pvd_ind, cwc_sfg_used_ind, cwc_state_hired_cd, cwc_workday_beg_tm, cwc_works_from_tm, cwc_works_to_tm, cwc_avg_week_wage, cwc_days_per_week, cwc_full_pay_inj, cwc_hours_worked, cwc_lst_workday_dt, cwc_pay_kind_amt, cwc_salary_ctu_ind, cwc_wage_rt, cwc_weeks_worked, cwc_update_opr_id, cwc_pmsd_ts, cwc_upd_ts, cwc_med_ind, cwc_entry_opr_id, cwc_create_ts, cwc_jur_state_cd, cwc_light_duty_ind, cwc_disability_dt, cwc_ret_to_work_dt, cwc_rep_to_car_dt, cwc_max_med_imp_dt, cwc_dependents_nbr, cwc_pex_md_con_ind, cwc_prior_inj_ind, cwc_years_emp_id, cwc_time_pos_id, cwc_spm_amt, cwc_spm_fqy_cd, cwc_spm_des_id, cwc_cmb_avg_wk_amt, cwc_cmb_wk_cps_amt, cwc_body_part_cd, cwc_nature_inj_cd, cwc_cause_inj_cd, cwc_exposure_dt, cwc_scar_des_id, cwc_treatment_ind, cwc_surgery_ind, cwc_scarring_ind, cwc_impairment_ind, cwc_voc_reh_ind, cwc_location_nbr, cwc_loc_des_id, cwc_loc_clt_id, cwc_emp_class_cd, cwc_cov_state_cd, cwc_clsdes_seq_nbr, cwc_state_all_ind, cwc_class_sub_cd, cwc_loss_cov_cd, cwc_loss_cat_cd, cwc_employ_sta_cd, cwc_ss_ind, cwc_ump_ind, cwc_pension_ind, cwc_spe_fund_ind, cwc_other_ind, cwc_method_set_cd, cwc_mgr_care_cd, cwc_los_con_act_cd, cwc_type_loss_cd, cwc_type_rcv_cd, cwc_type_cov_cd, cwc_type_set_cd, cwc_cls_seq_nbr, cwc_chg_rpt_ind, cwc_epr_dif_loc_id, cwc_sbr_amt, cwc_fraud_amt, cwc_joint_cov_amt, cwc_compromise_amt, cwc_death_dt, cwc_fraud_cd, cwc_num_wk_off_wrk, cwc_marital_sta, cwc_tax_file_sta, cwc_num_dep_child, cwc_num_dep_other, cwc_num_exemp, cwc_exemp_type, cwc_emp_blind, cwc_emp_over_65, cwc_spouse_blind, cwc_spouse_over_65, cwc_man_class_cd, cwc_educate_level, cwc_rel_med_ind, cwc_rel_ssn_ind, cwc_piece_wrk_hrs, cwc_gross_amt_type, cwc_gross_wage_amt, cwc_emp_rcv_meals, cwc_emp_rcv_room, cwc_emp_rcv_tips, cwc_wkly_atty_fee, cwc_ttd_rate, cwc_ppd_rate, cwc_ptd_rate, cwc_dly_ttd_rate, cwc_overtime_amt, cwc_overtime_after, cwc_emp_hour_day, cwc_emp_hour_wk, cwc_emp_pt_hour_wk, cwc_wage_eff_dt, cwc_phys_rest_ind, cwc_premises_cd, cwc_inj_sub_abuse, cwc_inj_safe_dev, cwc_inj_obey_rule, cwc_result_occ_inj, cwc_death_result, cwc_drg_card_sta, cwc_drg_crd_act_dt, cwc_drg_crd_exp_dt, cwc_care_directed, cwc_care_by_whom, cwc_med_srv_rend, cwc_emerg_treat, cwc_hospitalized, cwc_length_disable, cwc_dis_perm_psble, cwc_unsafe_act, cwc_hazard_cond, cwc_rsp_for_injury, cwc_depart_num, cwc_shift_num, cwc_med_auth_dt, cwc_result_occ_dis, cwc_emplyr_type_cd, cwc_sub_sta_exp_dt, cwc_fringe_dis_amt, cwc_pt_hour_wk, cwc_client_id, cwc_claim_cat_cd, cwc_subro_ind, cwc_invest_ind, cwc_out_deduct_ind, cwc_subcont_ind, cwc_activity_sta, cwc_rei_notify_dt, cwc_emp_std_ind_cd, cwc_ot_aft_hrs_day, extract_date, as_of_date, record_count, source_system_id, audit_id, cwc_init_treatment, cwc_send_to_state, cwc_state_send_ts, cwc_maint_type_cd, cwc_state_clm_nbr, cwc_send_sroi, cwc_send_sroi_ts, cwc_sroi_maint_typ, cwc_pts_rate, cwc_lgl_reprsnt_dt, cwc_sroi_st_trans, cwc_final_mtc_dt, cwc_sroi_start_dt, cwc_clt_claim_nbr, cwc_work_week_type, cwc_work_week_days, cwc_lost_time_on_doi, cwc_emp_security_id, cwc_epr_lost_time_notified_date, NaicsCode, cwc_full_denial_reason_cd, cwc_iaiabc_loss_type_cd, cwc_froi_late_reason_cd, cwc_froi_spec_late_reason_cd, froi_claim_type, cwc_auto_adj_ind, cwc_compensable_ind, cwc_body_part_location_cd, cwc_fingers_toes_location_code, cwc_froi_cancel_reason_cd, cwc_cancel_reason_cmt_id, cwc_deny_reason_cmt_id, cwc_disability_aft_wait_prd_dt, injury_severity_type, cwc_loec_paid_per, cwc_pre_disability_per, cwc_act_loss_cndtn_cd, cwc_temp_dbe_cd, cwc_curr_dt_disability_beg, cwc_emp_know_crr_dt_disability, cwc_wb_know_crr_dt_disability, cwc_met_rpt_rqmts_dt)
	SELECT 
	WORKERS_CPS_LOSS_ID AS WORKERS_CPS_LOSS_ID, 
	CWC_CLAIM_NBR AS CWC_CLAIM_NBR, 
	CWC_OBJECT_SEQ_NBR AS CWC_OBJECT_SEQ_NBR, 
	CWC_COMMISSION_NBR AS CWC_COMMISSION_NBR, 
	CWC_DPT_NM AS CWC_DPT_NM, 
	CWC_EMPLOYER_LOC AS CWC_EMPLOYER_LOC, 
	CWC_EMPLOYER_TYPE AS CWC_EMPLOYER_TYPE, 
	CWC_NATURE_BUS_DES AS CWC_NATURE_BUS_DES, 
	CWC_OSHA_CD AS CWC_OSHA_CD, 
	CWC_SELF_INS_IND AS CWC_SELF_INS_IND, 
	CWC_SPECIFIC_PRD AS CWC_SPECIFIC_PRD, 
	CWC_STATE_EPR_NBR AS CWC_STATE_EPR_NBR, 
	CWC_STATE_FUND_IND AS CWC_STATE_FUND_IND, 
	CWC_CER_NBR AS CWC_CER_NBR, 
	CWC_EPR_NOT_DT AS CWC_EPR_NOT_DT, 
	CWC_HIRED_DT AS CWC_HIRED_DT, 
	CWC_DPT_CD AS CWC_DPT_CD, 
	CWC_ACC_DPT_CD AS CWC_ACC_DPT_CD, 
	CWC_EPR_PMS_IND AS CWC_EPR_PMS_IND, 
	CWC_CMT_DES_ID AS CWC_CMT_DES_ID, 
	CWC_INJURED_ACY_ID AS CWC_INJURED_ACY_ID, 
	CWC_INJURY_DES_ID AS CWC_INJURY_DES_ID, 
	CWC_OFC_PTN_IND AS CWC_OFC_PTN_IND, 
	CWC_PLANT_CD AS CWC_PLANT_CD, 
	CWC_SFG_PVD_IND AS CWC_SFG_PVD_IND, 
	CWC_SFG_USED_IND AS CWC_SFG_USED_IND, 
	CWC_STATE_HIRED_CD AS CWC_STATE_HIRED_CD, 
	CWC_WORKDAY_BEG_TM AS CWC_WORKDAY_BEG_TM, 
	CWC_WORKS_FROM_TM AS CWC_WORKS_FROM_TM, 
	CWC_WORKS_TO_TM AS CWC_WORKS_TO_TM, 
	CWC_AVG_WEEK_WAGE AS CWC_AVG_WEEK_WAGE, 
	CWC_DAYS_PER_WEEK AS CWC_DAYS_PER_WEEK, 
	CWC_FULL_PAY_INJ AS CWC_FULL_PAY_INJ, 
	CWC_HOURS_WORKED AS CWC_HOURS_WORKED, 
	CWC_LST_WORKDAY_DT AS CWC_LST_WORKDAY_DT, 
	CWC_PAY_KIND_AMT AS CWC_PAY_KIND_AMT, 
	CWC_SALARY_CTU_IND AS CWC_SALARY_CTU_IND, 
	CWC_WAGE_RT AS CWC_WAGE_RT, 
	CWC_WEEKS_WORKED AS CWC_WEEKS_WORKED, 
	CWC_UPDATE_OPR_ID AS CWC_UPDATE_OPR_ID, 
	CWC_PMSD_TS AS CWC_PMSD_TS, 
	CWC_UPD_TS AS CWC_UPD_TS, 
	CWC_MED_IND AS CWC_MED_IND, 
	CWC_ENTRY_OPR_ID AS CWC_ENTRY_OPR_ID, 
	CWC_CREATE_TS AS CWC_CREATE_TS, 
	CWC_JUR_STATE_CD AS CWC_JUR_STATE_CD, 
	CWC_LIGHT_DUTY_IND AS CWC_LIGHT_DUTY_IND, 
	CWC_DISABILITY_DT AS CWC_DISABILITY_DT, 
	CWC_RET_TO_WORK_DT AS CWC_RET_TO_WORK_DT, 
	CWC_REP_TO_CAR_DT AS CWC_REP_TO_CAR_DT, 
	CWC_MAX_MED_IMP_DT AS CWC_MAX_MED_IMP_DT, 
	CWC_DEPENDENTS_NBR AS CWC_DEPENDENTS_NBR, 
	CWC_PEX_MD_CON_IND AS CWC_PEX_MD_CON_IND, 
	CWC_PRIOR_INJ_IND AS CWC_PRIOR_INJ_IND, 
	CWC_YEARS_EMP_ID AS CWC_YEARS_EMP_ID, 
	CWC_TIME_POS_ID AS CWC_TIME_POS_ID, 
	CWC_SPM_AMT AS CWC_SPM_AMT, 
	CWC_SPM_FQY_CD AS CWC_SPM_FQY_CD, 
	CWC_SPM_DES_ID AS CWC_SPM_DES_ID, 
	CWC_CMB_AVG_WK_AMT AS CWC_CMB_AVG_WK_AMT, 
	CWC_CMB_WK_CPS_AMT AS CWC_CMB_WK_CPS_AMT, 
	CWC_BODY_PART_CD AS CWC_BODY_PART_CD, 
	CWC_NATURE_INJ_CD AS CWC_NATURE_INJ_CD, 
	CWC_CAUSE_INJ_CD AS CWC_CAUSE_INJ_CD, 
	CWC_EXPOSURE_DT AS CWC_EXPOSURE_DT, 
	CWC_SCAR_DES_ID AS CWC_SCAR_DES_ID, 
	CWC_TREATMENT_IND AS CWC_TREATMENT_IND, 
	CWC_SURGERY_IND AS CWC_SURGERY_IND, 
	CWC_SCARRING_IND AS CWC_SCARRING_IND, 
	CWC_IMPAIRMENT_IND AS CWC_IMPAIRMENT_IND, 
	CWC_VOC_REH_IND AS CWC_VOC_REH_IND, 
	CWC_LOCATION_NBR AS CWC_LOCATION_NBR, 
	CWC_LOC_DES_ID AS CWC_LOC_DES_ID, 
	CWC_LOC_CLT_ID AS CWC_LOC_CLT_ID, 
	CWC_EMP_CLASS_CD AS CWC_EMP_CLASS_CD, 
	CWC_COV_STATE_CD AS CWC_COV_STATE_CD, 
	CWC_CLSDES_SEQ_NBR AS CWC_CLSDES_SEQ_NBR, 
	CWC_STATE_ALL_IND AS CWC_STATE_ALL_IND, 
	CWC_CLASS_SUB_CD AS CWC_CLASS_SUB_CD, 
	CWC_LOSS_COV_CD AS CWC_LOSS_COV_CD, 
	CWC_LOSS_CAT_CD AS CWC_LOSS_CAT_CD, 
	CWC_EMPLOY_STA_CD AS CWC_EMPLOY_STA_CD, 
	CWC_SS_IND AS CWC_SS_IND, 
	CWC_UMP_IND AS CWC_UMP_IND, 
	CWC_PENSION_IND AS CWC_PENSION_IND, 
	CWC_SPE_FUND_IND AS CWC_SPE_FUND_IND, 
	CWC_OTHER_IND AS CWC_OTHER_IND, 
	CWC_METHOD_SET_CD AS CWC_METHOD_SET_CD, 
	CWC_MGR_CARE_CD AS CWC_MGR_CARE_CD, 
	CWC_LOS_CON_ACT_CD AS CWC_LOS_CON_ACT_CD, 
	CWC_TYPE_LOSS_CD AS CWC_TYPE_LOSS_CD, 
	CWC_TYPE_RCV_CD AS CWC_TYPE_RCV_CD, 
	CWC_TYPE_COV_CD AS CWC_TYPE_COV_CD, 
	CWC_TYPE_SET_CD AS CWC_TYPE_SET_CD, 
	CWC_CLS_SEQ_NBR AS CWC_CLS_SEQ_NBR, 
	CWC_CHG_RPT_IND AS CWC_CHG_RPT_IND, 
	CWC_EPR_DIF_LOC_ID AS CWC_EPR_DIF_LOC_ID, 
	CWC_SBR_AMT AS CWC_SBR_AMT, 
	CWC_FRAUD_AMT AS CWC_FRAUD_AMT, 
	CWC_JOINT_COV_AMT AS CWC_JOINT_COV_AMT, 
	CWC_COMPROMISE_AMT AS CWC_COMPROMISE_AMT, 
	CWC_DEATH_DT AS CWC_DEATH_DT, 
	CWC_FRAUD_CD AS CWC_FRAUD_CD, 
	CWC_NUM_WK_OFF_WRK AS CWC_NUM_WK_OFF_WRK, 
	CWC_MARITAL_STA AS CWC_MARITAL_STA, 
	CWC_TAX_FILE_STA AS CWC_TAX_FILE_STA, 
	CWC_NUM_DEP_CHILD AS CWC_NUM_DEP_CHILD, 
	CWC_NUM_DEP_OTHER AS CWC_NUM_DEP_OTHER, 
	CWC_NUM_EXEMP AS CWC_NUM_EXEMP, 
	CWC_EXEMP_TYPE AS CWC_EXEMP_TYPE, 
	CWC_EMP_BLIND AS CWC_EMP_BLIND, 
	CWC_EMP_OVER_65 AS CWC_EMP_OVER_65, 
	CWC_SPOUSE_BLIND AS CWC_SPOUSE_BLIND, 
	CWC_SPOUSE_OVER_65 AS CWC_SPOUSE_OVER_65, 
	CWC_MAN_CLASS_CD AS CWC_MAN_CLASS_CD, 
	CWC_EDUCATE_LEVEL AS CWC_EDUCATE_LEVEL, 
	CWC_REL_MED_IND AS CWC_REL_MED_IND, 
	CWC_REL_SSN_IND AS CWC_REL_SSN_IND, 
	CWC_PIECE_WRK_HRS AS CWC_PIECE_WRK_HRS, 
	CWC_GROSS_AMT_TYPE AS CWC_GROSS_AMT_TYPE, 
	CWC_GROSS_WAGE_AMT AS CWC_GROSS_WAGE_AMT, 
	CWC_EMP_RCV_MEALS AS CWC_EMP_RCV_MEALS, 
	CWC_EMP_RCV_ROOM AS CWC_EMP_RCV_ROOM, 
	CWC_EMP_RCV_TIPS AS CWC_EMP_RCV_TIPS, 
	CWC_WKLY_ATTY_FEE AS CWC_WKLY_ATTY_FEE, 
	CWC_TTD_RATE AS CWC_TTD_RATE, 
	CWC_PPD_RATE AS CWC_PPD_RATE, 
	CWC_PTD_RATE AS CWC_PTD_RATE, 
	CWC_DLY_TTD_RATE AS CWC_DLY_TTD_RATE, 
	CWC_OVERTIME_AMT AS CWC_OVERTIME_AMT, 
	CWC_OVERTIME_AFTER AS CWC_OVERTIME_AFTER, 
	CWC_EMP_HOUR_DAY AS CWC_EMP_HOUR_DAY, 
	CWC_EMP_HOUR_WK AS CWC_EMP_HOUR_WK, 
	CWC_EMP_PT_HOUR_WK AS CWC_EMP_PT_HOUR_WK, 
	CWC_WAGE_EFF_DT AS CWC_WAGE_EFF_DT, 
	CWC_PHYS_REST_IND AS CWC_PHYS_REST_IND, 
	CWC_PREMISES_CD AS CWC_PREMISES_CD, 
	CWC_INJ_SUB_ABUSE AS CWC_INJ_SUB_ABUSE, 
	CWC_INJ_SAFE_DEV AS CWC_INJ_SAFE_DEV, 
	CWC_INJ_OBEY_RULE AS CWC_INJ_OBEY_RULE, 
	CWC_RESULT_OCC_INJ AS CWC_RESULT_OCC_INJ, 
	CWC_DEATH_RESULT AS CWC_DEATH_RESULT, 
	CWC_DRG_CARD_STA AS CWC_DRG_CARD_STA, 
	CWC_DRG_CRD_ACT_DT AS CWC_DRG_CRD_ACT_DT, 
	CWC_DRG_CRD_EXP_DT AS CWC_DRG_CRD_EXP_DT, 
	CWC_CARE_DIRECTED AS CWC_CARE_DIRECTED, 
	CWC_CARE_BY_WHOM AS CWC_CARE_BY_WHOM, 
	CWC_MED_SRV_REND AS CWC_MED_SRV_REND, 
	CWC_EMERG_TREAT AS CWC_EMERG_TREAT, 
	CWC_HOSPITALIZED AS CWC_HOSPITALIZED, 
	CWC_LENGTH_DISABLE AS CWC_LENGTH_DISABLE, 
	CWC_DIS_PERM_PSBLE AS CWC_DIS_PERM_PSBLE, 
	CWC_UNSAFE_ACT AS CWC_UNSAFE_ACT, 
	CWC_HAZARD_COND AS CWC_HAZARD_COND, 
	CWC_RSP_FOR_INJURY AS CWC_RSP_FOR_INJURY, 
	CWC_DEPART_NUM AS CWC_DEPART_NUM, 
	CWC_SHIFT_NUM AS CWC_SHIFT_NUM, 
	CWC_MED_AUTH_DT AS CWC_MED_AUTH_DT, 
	CWC_RESULT_OCC_DIS AS CWC_RESULT_OCC_DIS, 
	CWC_EMPLYR_TYPE_CD AS CWC_EMPLYR_TYPE_CD, 
	CWC_SUB_STA_EXP_DT AS CWC_SUB_STA_EXP_DT, 
	CWC_FRINGE_DIS_AMT AS CWC_FRINGE_DIS_AMT, 
	CWC_PT_HOUR_WK AS CWC_PT_HOUR_WK, 
	CWC_CLIENT_ID AS CWC_CLIENT_ID, 
	CWC_CLAIM_CAT_CD AS CWC_CLAIM_CAT_CD, 
	CWC_SUBRO_IND AS CWC_SUBRO_IND, 
	CWC_INVEST_IND AS CWC_INVEST_IND, 
	CWC_OUT_DEDUCT_IND AS CWC_OUT_DEDUCT_IND, 
	CWC_SUBCONT_IND AS CWC_SUBCONT_IND, 
	CWC_ACTIVITY_STA AS CWC_ACTIVITY_STA, 
	CWC_REI_NOTIFY_DT AS CWC_REI_NOTIFY_DT, 
	CWC_EMP_STD_IND_CD AS CWC_EMP_STD_IND_CD, 
	CWC_OT_AFT_HRS_DAY AS CWC_OT_AFT_HRS_DAY, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	CWC_INIT_TREATMENT, 
	CWC_SEND_TO_STATE, 
	CWC_STATE_SEND_TS, 
	CWC_MAINT_TYPE_CD, 
	CWC_STATE_CLM_NBR, 
	CWC_SEND_SROI, 
	CWC_SEND_SROI_TS, 
	CWC_SROI_MAINT_TYP, 
	CWC_PTS_RATE, 
	CWC_LGL_REPRSNT_DT, 
	CWC_SROI_ST_TRANS, 
	CWC_FINAL_MTC_DT, 
	CWC_SROI_START_DT, 
	CWC_CLT_CLAIM_NBR, 
	CWC_WORK_WEEK_TYPE, 
	CWC_WORK_WEEK_DAYS, 
	CWC_LOST_TIME_ON_DOI, 
	CWC_EMP_SECURITY_ID, 
	CWC_EPR_LOST_TIME_NOTIFIED_DATE, 
	NAICSCODE, 
	CWC_FULL_DENIAL_REASON_CD, 
	CWC_IAIABC_LOSS_TYPE_CD, 
	CWC_FROI_LATE_REASON_CD, 
	CWC_FROI_SPEC_LATE_REASON_CD, 
	FROI_CLAIM_TYPE, 
	CWC_AUTO_ADJ_IND, 
	CWC_COMPENSABLE_IND, 
	CWC_BODY_PART_LOCATION_CD, 
	CWC_FINGERS_TOES_LOCATION_CODE, 
	CWC_FROI_CANCEL_REASON_CD, 
	CWC_CANCEL_REASON_CMT_ID, 
	CWC_DENY_REASON_CMT_ID, 
	CWC_DISABILITY_AFT_WAIT_PRD_DT, 
	INJURY_SEVERITY_TYPE, 
	CWC_LOEC_PAID_PER, 
	CWC_PRE_DISABILITY_PER, 
	CWC_ACT_LOSS_CNDTN_CD, 
	CWC_TEMP_DBE_CD, 
	CWC_CURR_DT_DISABILITY_BEG, 
	CWC_EMP_KNOW_CRR_DT_DISABILITY, 
	CWC_WB_KNOW_CRR_DT_DISABILITY, 
	CWC_MET_RPT_RQMTS_DT
	FROM EXP_WORKERS_CPS_LOSS_STAGE
),