WITH
SQ_loss_occurrence_S3P_STAGE AS (
	SELECT loss_occurrence_S3P_STAGE.loss_occurrence_S3P_ID, loss_occurrence_S3P_STAGE.COC_OCCURRENCE_ID, loss_occurrence_S3P_STAGE.COC_ENTRY_OPR_ID, loss_occurrence_S3P_STAGE.COC_OCCURRENCE_TYP, loss_occurrence_S3P_STAGE.COC_OCC_LOC_ID, loss_occurrence_S3P_STAGE.COC_OCC_DES_ID, loss_occurrence_S3P_STAGE.COC_OCC_CMT_ID, loss_occurrence_S3P_STAGE.COC_COUNTRY_CD, loss_occurrence_S3P_STAGE.COC_START_DT, loss_occurrence_S3P_STAGE.COC_END_DT, loss_occurrence_S3P_STAGE.COC_PMSD_TS, loss_occurrence_S3P_STAGE.COC_UPDATE_OPR_ID, loss_occurrence_S3P_STAGE.COC_CREATE_TS, loss_occurrence_S3P_STAGE.COC_UPD_TS, loss_occurrence_S3P_STAGE.COC_CATASTROPHE_CD, loss_occurrence_S3P_STAGE.COC_CSR_OCC_NBR, loss_occurrence_S3P_STAGE.EXTRACT_DATE, loss_occurrence_S3P_STAGE.AS_OF_DATE, loss_occurrence_S3P_STAGE.RECORD_COUNT, loss_occurrence_S3P_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 loss_occurrence_S3P_STAGE
	WHERE
	loss_occurrence_S3P_STAGE.COC_CREATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	loss_occurrence_S3P_STAGE.COC_UPD_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_LOSS_OCCURRENCE_STAGE AS (
	SELECT
	loss_occurrence_S3P_ID AS LOSS_OCCURRENCE_ID,
	COC_OCCURRENCE_ID,
	COC_ENTRY_OPR_ID,
	COC_OCCURRENCE_TYP,
	COC_OCC_LOC_ID,
	COC_OCC_DES_ID,
	COC_OCC_CMT_ID,
	COC_COUNTRY_CD,
	COC_START_DT,
	COC_END_DT,
	COC_PMSD_TS,
	COC_UPDATE_OPR_ID,
	COC_CREATE_TS,
	COC_UPD_TS,
	COC_CATASTROPHE_CD,
	COC_CSR_OCC_NBR,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_loss_occurrence_S3P_STAGE
),
ARCH_loss_occurrence_S3P_STAGE AS (
	INSERT INTO ARCH_loss_occurrence_S3P_STAGE
	(loss_occurrence_S3P_ID, COC_OCCURRENCE_ID, COC_ENTRY_OPR_ID, COC_OCCURRENCE_TYP, COC_OCC_LOC_ID, COC_OCC_DES_ID, COC_OCC_CMT_ID, COC_COUNTRY_CD, COC_START_DT, COC_END_DT, COC_PMSD_TS, COC_UPDATE_OPR_ID, COC_CREATE_TS, COC_UPD_TS, COC_CATASTROPHE_CD, COC_CSR_OCC_NBR, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	LOSS_OCCURRENCE_ID AS LOSS_OCCURRENCE_S3P_ID, 
	COC_OCCURRENCE_ID, 
	COC_ENTRY_OPR_ID, 
	COC_OCCURRENCE_TYP, 
	COC_OCC_LOC_ID, 
	COC_OCC_DES_ID, 
	COC_OCC_CMT_ID, 
	COC_COUNTRY_CD, 
	COC_START_DT, 
	COC_END_DT, 
	COC_PMSD_TS, 
	COC_UPDATE_OPR_ID, 
	COC_CREATE_TS, 
	COC_UPD_TS, 
	COC_CATASTROPHE_CD, 
	COC_CSR_OCC_NBR, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_LOSS_OCCURRENCE_STAGE
),