WITH
SQ_WC_REPORT_HISTORY_STAGE AS (
	SELECT WC_REPORT_HISTORY_STAGE.WC_REPORT_HISTORY_ID, WC_REPORT_HISTORY_STAGE.WRH_OBJECT_SEQ_NBR, WC_REPORT_HISTORY_STAGE.WRH_CLAIM_NBR, WC_REPORT_HISTORY_STAGE.WRH_CREATE_TS, WC_REPORT_HISTORY_STAGE.WRH_REPORT_TYPE, WC_REPORT_HISTORY_STAGE.WRH_REPORTED_DATE, WC_REPORT_HISTORY_STAGE.WRH_UPDATE_TS, WC_REPORT_HISTORY_STAGE.WRH_ENTRY_OPR_ID, WC_REPORT_HISTORY_STAGE.WRH_UPDATE_OPR_ID, WC_REPORT_HISTORY_STAGE.WRH_CLIENT_ID, WC_REPORT_HISTORY_STAGE.EXTRACT_DATE, WC_REPORT_HISTORY_STAGE.AS_OF_DATE, WC_REPORT_HISTORY_STAGE.RECORD_COUNT, WC_REPORT_HISTORY_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 WC_REPORT_HISTORY_STAGE
	WHERE
	WC_REPORT_HISTORY_STAGE.WRH_CREATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	WC_REPORT_HISTORY_STAGE.WRH_UPDATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXPTRANS AS (
	SELECT
	WC_REPORT_HISTORY_ID,
	WRH_OBJECT_SEQ_NBR,
	WRH_CLAIM_NBR,
	WRH_CREATE_TS,
	WRH_REPORT_TYPE,
	WRH_REPORTED_DATE,
	WRH_UPDATE_TS,
	WRH_ENTRY_OPR_ID,
	WRH_UPDATE_OPR_ID,
	WRH_CLIENT_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_WC_REPORT_HISTORY_STAGE
),
ARCH_WC_REPORT_HISTORY_STAGE AS (
	INSERT INTO ARCH_WC_REPORT_HISTORY_STAGE
	(wc_report_history_id, wrh_object_seq_nbr, wrh_claim_nbr, wrh_create_ts, wrh_report_type, wrh_reported_date, wrh_update_ts, wrh_entry_opr_id, wrh_update_opr_id, wrh_client_id, extract_date, as_of_date, record_count, source_system_id, audit_id)
	SELECT 
	WC_REPORT_HISTORY_ID AS WC_REPORT_HISTORY_ID, 
	WRH_OBJECT_SEQ_NBR AS WRH_OBJECT_SEQ_NBR, 
	WRH_CLAIM_NBR AS WRH_CLAIM_NBR, 
	WRH_CREATE_TS AS WRH_CREATE_TS, 
	WRH_REPORT_TYPE AS WRH_REPORT_TYPE, 
	WRH_REPORTED_DATE AS WRH_REPORTED_DATE, 
	WRH_UPDATE_TS AS WRH_UPDATE_TS, 
	WRH_ENTRY_OPR_ID AS WRH_ENTRY_OPR_ID, 
	WRH_UPDATE_OPR_ID AS WRH_UPDATE_OPR_ID, 
	WRH_CLIENT_ID AS WRH_CLIENT_ID, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXPTRANS
),