WITH
SQ_CLAIM_OBJECT_STAGE1 AS (
	SELECT
		claim_object_id AS CLAIM_OBJECT_ID,
		cob_claim_nbr AS COB_CLAIM_NBR,
		cob_object_type_cd AS COB_OBJECT_TYPE_CD,
		cob_object_seq_nbr AS COB_OBJECT_SEQ_NBR,
		cob_demand_amt AS COB_DEMAND_AMT,
		cob_bills_des_id AS COB_BILLS_DES_ID,
		cob_client_seq_nbr AS COB_CLIENT_SEQ_NBR,
		cob_cmt_dsc_id AS COB_CMT_DSC_ID,
		cob_create_ts AS COB_CREATE_TS,
		cob_dcs_bse_doc_cd AS COB_DCS_BSE_DOC_CD,
		cob_dsc_rea_cd AS COB_DSC_REA_CD,
		cob_entry_opr_id AS COB_ENTRY_OPR_ID,
		cob_pmsd_ts AS COB_PMSD_TS,
		cob_object_cmt_id AS COB_OBJECT_CMT_ID,
		cob_rea_for_los_id AS COB_REA_FOR_LOS_ID,
		cob_recovery_ind AS COB_RECOVERY_IND,
		cob_type_of_loss AS COB_TYPE_OF_LOSS,
		cob_update_opr_id AS COB_UPDATE_OPR_ID,
		cob_upd_ts AS COB_UPD_TS,
		cob_police_ivs_cd AS COB_POLICE_IVS_CD,
		cob_rsp_party_id AS COB_RSP_PARTY_ID,
		cob_lia_type_cd AS COB_LIA_TYPE_CD,
		cob_liability_ind AS COB_LIABILITY_IND,
		cob_injury_ind AS COB_INJURY_IND,
		cob_loss_place_id AS COB_LOSS_PLACE_ID,
		cob_notice_wch_ind AS COB_NOTICE_WCH_IND,
		cob_adjusted_ind AS COB_ADJUSTED_IND,
		cob_adjusted_dt AS COB_ADJUSTED_DT,
		cob_blood_test_tm AS COB_BLOOD_TEST_TM,
		cob_blood_test_dt AS COB_BLOOD_TEST_DT,
		cob_alcohol_pct AS COB_ALCOHOL_PCT,
		cob_alcohol_ifl_cd AS COB_ALCOHOL_IFL_CD,
		cob_alcohol_tm AS COB_ALCOHOL_TM,
		cob_blood_test_ind AS COB_BLOOD_TEST_IND,
		cob_alcohol_ind AS COB_ALCOHOL_IND,
		cob_cession_nbr AS COB_CESSION_NBR,
		cob_rin_ind AS COB_RIN_IND,
		cob_suit_ind AS COB_SUIT_IND,
		cob_other_cov_ind AS COB_OTHER_COV_IND,
		cob_leg_counsel_cd AS COB_LEG_COUNSEL_CD,
		cob_sport_cd AS COB_SPORT_CD,
		cob_report_nbr AS COB_REPORT_NBR,
		cob_isu_own_ind AS COB_ISU_OWN_IND,
		cob_isu_tnt_ind AS COB_ISU_TNT_IND,
		cob_isu_oth_ind AS COB_ISU_OTH_IND,
		cob_premise_des AS COB_PREMISE_DES,
		cob_isu_muf_ind AS COB_ISU_MUF_IND,
		cob_isu_ven_ind AS COB_ISU_VEN_IND,
		cob_prd_des_id AS COB_PRD_DES_ID,
		cob_lia_des_id AS COB_LIA_DES_ID,
		cob_offer_amt AS COB_OFFER_AMT,
		cob_offer_dt AS COB_OFFER_DT,
		cob_object_status AS COB_OBJECT_STATUS,
		cob_on_pms_ind AS COB_ON_PMS_IND,
		cob_unit_type_ind AS COB_UNIT_TYPE_IND,
		cob_unit_des_id AS COB_UNIT_DES_ID,
		cob_cov_unit_nbr AS COB_COV_UNIT_NBR,
		cob_ald_ind AS COB_ALD_IND,
		cob_cov_bld_nbr AS COB_COV_BLD_NBR,
		cob_total_loss_ind AS COB_TOTAL_LOSS_IND,
		cob_at_fault_cd AS COB_AT_FAULT_CD,
		cob_tty_unt_nbr AS COB_TTY_UNT_NBR,
		cob_unit_type_cd AS COB_UNIT_TYPE_CD,
		cob_spp_use_cd AS COB_SPP_USE_CD,
		cob_sar_id AS COB_SAR_ID,
		cob_ins_line AS COB_INS_LINE,
		cob_loc_unit_num AS COB_LOC_UNIT_NUM,
		cob_risk_unit_grp AS COB_RISK_UNIT_GRP,
		cob_rsk_unt_gr_seq AS COB_RSK_UNT_GR_SEQ,
		cob_risk_unit AS COB_RISK_UNIT,
		cob_risk_type_ind AS COB_RISK_TYPE_IND,
		cob_class_code AS COB_CLASS_CODE,
		cob_sub_loc_num AS COB_SUB_LOC_NUM,
		cob_seq_risk_unit AS COB_SEQ_RISK_UNIT,
		cob_sr_seq AS COB_SR_SEQ,
		cob_client_id AS COB_CLIENT_ID,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		cob_coverage_form,
		cob_coverage_type,
		cob_risk_type
	FROM CLAIM_OBJECT_STAGE
),
EXP_CLAIM_OBJECT_STAGE AS (
	SELECT
	CLAIM_OBJECT_ID,
	COB_CLAIM_NBR,
	COB_OBJECT_TYPE_CD,
	COB_OBJECT_SEQ_NBR,
	COB_DEMAND_AMT,
	COB_BILLS_DES_ID,
	COB_CLIENT_SEQ_NBR,
	COB_CMT_DSC_ID,
	COB_CREATE_TS,
	COB_DCS_BSE_DOC_CD,
	COB_DSC_REA_CD,
	COB_ENTRY_OPR_ID,
	COB_PMSD_TS,
	COB_OBJECT_CMT_ID,
	COB_REA_FOR_LOS_ID,
	COB_RECOVERY_IND,
	COB_TYPE_OF_LOSS,
	COB_UPDATE_OPR_ID,
	COB_UPD_TS,
	COB_POLICE_IVS_CD,
	COB_RSP_PARTY_ID,
	COB_LIA_TYPE_CD,
	COB_LIABILITY_IND,
	COB_INJURY_IND,
	COB_LOSS_PLACE_ID,
	COB_NOTICE_WCH_IND,
	COB_ADJUSTED_IND,
	COB_ADJUSTED_DT,
	COB_BLOOD_TEST_TM,
	COB_BLOOD_TEST_DT,
	COB_ALCOHOL_PCT,
	COB_ALCOHOL_IFL_CD,
	COB_ALCOHOL_TM,
	COB_BLOOD_TEST_IND,
	COB_ALCOHOL_IND,
	COB_CESSION_NBR,
	COB_RIN_IND,
	COB_SUIT_IND,
	COB_OTHER_COV_IND,
	COB_LEG_COUNSEL_CD,
	COB_SPORT_CD,
	COB_REPORT_NBR,
	COB_ISU_OWN_IND,
	COB_ISU_TNT_IND,
	COB_ISU_OTH_IND,
	COB_PREMISE_DES,
	COB_ISU_MUF_IND,
	COB_ISU_VEN_IND,
	COB_PRD_DES_ID,
	COB_LIA_DES_ID,
	COB_OFFER_AMT,
	COB_OFFER_DT,
	COB_OBJECT_STATUS,
	COB_ON_PMS_IND,
	COB_UNIT_TYPE_IND,
	COB_UNIT_DES_ID,
	COB_COV_UNIT_NBR,
	COB_ALD_IND,
	COB_COV_BLD_NBR,
	COB_TOTAL_LOSS_IND,
	COB_AT_FAULT_CD,
	COB_TTY_UNT_NBR,
	COB_UNIT_TYPE_CD,
	COB_SPP_USE_CD,
	COB_SAR_ID,
	COB_INS_LINE,
	COB_LOC_UNIT_NUM,
	COB_RISK_UNIT_GRP,
	COB_RSK_UNT_GR_SEQ,
	COB_RISK_UNIT,
	COB_RISK_TYPE_IND,
	COB_CLASS_CODE,
	COB_SUB_LOC_NUM,
	COB_SEQ_RISK_UNIT,
	COB_SR_SEQ,
	COB_CLIENT_ID,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	cob_coverage_form,
	cob_coverage_type,
	cob_risk_type,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_OBJECT_STAGE1
),
ARCH_CLAIM_OBJECT_STAGE AS (
	INSERT INTO ARCH_CLAIM_OBJECT_STAGE
	(claim_object_id, cob_claim_nbr, cob_object_type_cd, cob_object_seq_nbr, cob_demand_amt, cob_bills_des_id, cob_client_seq_nbr, cob_cmt_dsc_id, cob_create_ts, cob_dcs_bse_doc_cd, cob_dsc_rea_cd, cob_entry_opr_id, cob_pmsd_ts, cob_object_cmt_id, cob_rea_for_los_id, cob_recovery_ind, cob_type_of_loss, cob_update_opr_id, cob_upd_ts, cob_police_ivs_cd, cob_rsp_party_id, cob_lia_type_cd, cob_liability_ind, cob_injury_ind, cob_loss_place_id, cob_notice_wch_ind, cob_adjusted_ind, cob_adjusted_dt, cob_blood_test_tm, cob_blood_test_dt, cob_alcohol_pct, cob_alcohol_ifl_cd, cob_alcohol_tm, cob_blood_test_ind, cob_alcohol_ind, cob_cession_nbr, cob_rin_ind, cob_suit_ind, cob_other_cov_ind, cob_leg_counsel_cd, cob_sport_cd, cob_report_nbr, cob_isu_own_ind, cob_isu_tnt_ind, cob_isu_oth_ind, cob_premise_des, cob_isu_muf_ind, cob_isu_ven_ind, cob_prd_des_id, cob_lia_des_id, cob_offer_amt, cob_offer_dt, cob_object_status, cob_on_pms_ind, cob_unit_type_ind, cob_unit_des_id, cob_cov_unit_nbr, cob_ald_ind, cob_cov_bld_nbr, cob_total_loss_ind, cob_at_fault_cd, cob_tty_unt_nbr, cob_unit_type_cd, cob_spp_use_cd, cob_sar_id, cob_ins_line, cob_loc_unit_num, cob_risk_unit_grp, cob_rsk_unt_gr_seq, cob_risk_unit, cob_risk_type_ind, cob_class_code, cob_sub_loc_num, cob_seq_risk_unit, cob_sr_seq, cob_client_id, extract_date, as_of_date, record_count, source_system_id, audit_id, cob_coverage_form, cob_coverage_type, cob_risk_type)
	SELECT 
	CLAIM_OBJECT_ID AS CLAIM_OBJECT_ID, 
	COB_CLAIM_NBR AS COB_CLAIM_NBR, 
	COB_OBJECT_TYPE_CD AS COB_OBJECT_TYPE_CD, 
	COB_OBJECT_SEQ_NBR AS COB_OBJECT_SEQ_NBR, 
	COB_DEMAND_AMT AS COB_DEMAND_AMT, 
	COB_BILLS_DES_ID AS COB_BILLS_DES_ID, 
	COB_CLIENT_SEQ_NBR AS COB_CLIENT_SEQ_NBR, 
	COB_CMT_DSC_ID AS COB_CMT_DSC_ID, 
	COB_CREATE_TS AS COB_CREATE_TS, 
	COB_DCS_BSE_DOC_CD AS COB_DCS_BSE_DOC_CD, 
	COB_DSC_REA_CD AS COB_DSC_REA_CD, 
	COB_ENTRY_OPR_ID AS COB_ENTRY_OPR_ID, 
	COB_PMSD_TS AS COB_PMSD_TS, 
	COB_OBJECT_CMT_ID AS COB_OBJECT_CMT_ID, 
	COB_REA_FOR_LOS_ID AS COB_REA_FOR_LOS_ID, 
	COB_RECOVERY_IND AS COB_RECOVERY_IND, 
	COB_TYPE_OF_LOSS AS COB_TYPE_OF_LOSS, 
	COB_UPDATE_OPR_ID AS COB_UPDATE_OPR_ID, 
	COB_UPD_TS AS COB_UPD_TS, 
	COB_POLICE_IVS_CD AS COB_POLICE_IVS_CD, 
	COB_RSP_PARTY_ID AS COB_RSP_PARTY_ID, 
	COB_LIA_TYPE_CD AS COB_LIA_TYPE_CD, 
	COB_LIABILITY_IND AS COB_LIABILITY_IND, 
	COB_INJURY_IND AS COB_INJURY_IND, 
	COB_LOSS_PLACE_ID AS COB_LOSS_PLACE_ID, 
	COB_NOTICE_WCH_IND AS COB_NOTICE_WCH_IND, 
	COB_ADJUSTED_IND AS COB_ADJUSTED_IND, 
	COB_ADJUSTED_DT AS COB_ADJUSTED_DT, 
	COB_BLOOD_TEST_TM AS COB_BLOOD_TEST_TM, 
	COB_BLOOD_TEST_DT AS COB_BLOOD_TEST_DT, 
	COB_ALCOHOL_PCT AS COB_ALCOHOL_PCT, 
	COB_ALCOHOL_IFL_CD AS COB_ALCOHOL_IFL_CD, 
	COB_ALCOHOL_TM AS COB_ALCOHOL_TM, 
	COB_BLOOD_TEST_IND AS COB_BLOOD_TEST_IND, 
	COB_ALCOHOL_IND AS COB_ALCOHOL_IND, 
	COB_CESSION_NBR AS COB_CESSION_NBR, 
	COB_RIN_IND AS COB_RIN_IND, 
	COB_SUIT_IND AS COB_SUIT_IND, 
	COB_OTHER_COV_IND AS COB_OTHER_COV_IND, 
	COB_LEG_COUNSEL_CD AS COB_LEG_COUNSEL_CD, 
	COB_SPORT_CD AS COB_SPORT_CD, 
	COB_REPORT_NBR AS COB_REPORT_NBR, 
	COB_ISU_OWN_IND AS COB_ISU_OWN_IND, 
	COB_ISU_TNT_IND AS COB_ISU_TNT_IND, 
	COB_ISU_OTH_IND AS COB_ISU_OTH_IND, 
	COB_PREMISE_DES AS COB_PREMISE_DES, 
	COB_ISU_MUF_IND AS COB_ISU_MUF_IND, 
	COB_ISU_VEN_IND AS COB_ISU_VEN_IND, 
	COB_PRD_DES_ID AS COB_PRD_DES_ID, 
	COB_LIA_DES_ID AS COB_LIA_DES_ID, 
	COB_OFFER_AMT AS COB_OFFER_AMT, 
	COB_OFFER_DT AS COB_OFFER_DT, 
	COB_OBJECT_STATUS AS COB_OBJECT_STATUS, 
	COB_ON_PMS_IND AS COB_ON_PMS_IND, 
	COB_UNIT_TYPE_IND AS COB_UNIT_TYPE_IND, 
	COB_UNIT_DES_ID AS COB_UNIT_DES_ID, 
	COB_COV_UNIT_NBR AS COB_COV_UNIT_NBR, 
	COB_ALD_IND AS COB_ALD_IND, 
	COB_COV_BLD_NBR AS COB_COV_BLD_NBR, 
	COB_TOTAL_LOSS_IND AS COB_TOTAL_LOSS_IND, 
	COB_AT_FAULT_CD AS COB_AT_FAULT_CD, 
	COB_TTY_UNT_NBR AS COB_TTY_UNT_NBR, 
	COB_UNIT_TYPE_CD AS COB_UNIT_TYPE_CD, 
	COB_SPP_USE_CD AS COB_SPP_USE_CD, 
	COB_SAR_ID AS COB_SAR_ID, 
	COB_INS_LINE AS COB_INS_LINE, 
	COB_LOC_UNIT_NUM AS COB_LOC_UNIT_NUM, 
	COB_RISK_UNIT_GRP AS COB_RISK_UNIT_GRP, 
	COB_RSK_UNT_GR_SEQ AS COB_RSK_UNT_GR_SEQ, 
	COB_RISK_UNIT AS COB_RISK_UNIT, 
	COB_RISK_TYPE_IND AS COB_RISK_TYPE_IND, 
	COB_CLASS_CODE AS COB_CLASS_CODE, 
	COB_SUB_LOC_NUM AS COB_SUB_LOC_NUM, 
	COB_SEQ_RISK_UNIT AS COB_SEQ_RISK_UNIT, 
	COB_SR_SEQ AS COB_SR_SEQ, 
	COB_CLIENT_ID AS COB_CLIENT_ID, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	COB_COVERAGE_FORM, 
	COB_COVERAGE_TYPE, 
	COB_RISK_TYPE
	FROM EXP_CLAIM_OBJECT_STAGE
),