WITH
SQ_CLAIM_ADJUSTER_STAGE AS (
	SELECT
		CLAIM_ADJUSTER_ID,
		CAI_CLAIM_NBR,
		CAI_CLM_HDL_ID,
		CAI_ADJ_ROLE_CD,
		CAI_CREATE_TS,
		CAI_DATE_ASSIGNED,
		CAI_ENTRY_OPR_ID,
		CAI_PMSD_TS,
		CAI_UPDATE_OPR_ID,
		CAI_UPD_TS,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM CLAIM_ADJUSTER_STAGE
),
EXPTRANS AS (
	SELECT
	CLAIM_ADJUSTER_ID,
	CAI_CLAIM_NBR,
	CAI_CLM_HDL_ID,
	CAI_ADJ_ROLE_CD,
	CAI_CREATE_TS,
	CAI_DATE_ASSIGNED,
	CAI_ENTRY_OPR_ID,
	CAI_PMSD_TS,
	CAI_UPDATE_OPR_ID,
	CAI_UPD_TS,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_ADJUSTER_STAGE
),
ARCH_CLAIM_ADJUSTER_STAGE AS (
	INSERT INTO ARCH_CLAIM_ADJUSTER_STAGE
	(CLAIM_ADJUSTER_ID, CAI_CLAIM_NBR, CAI_CLM_HDL_ID, CAI_ADJ_ROLE_CD, CAI_CREATE_TS, CAI_DATE_ASSIGNED, CAI_ENTRY_OPR_ID, CAI_PMSD_TS, CAI_UPDATE_OPR_ID, CAI_UPD_TS, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	CLAIM_ADJUSTER_ID, 
	CAI_CLAIM_NBR, 
	CAI_CLM_HDL_ID, 
	CAI_ADJ_ROLE_CD, 
	CAI_CREATE_TS, 
	CAI_DATE_ASSIGNED, 
	CAI_ENTRY_OPR_ID, 
	CAI_PMSD_TS, 
	CAI_UPDATE_OPR_ID, 
	CAI_UPD_TS, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXPTRANS
),