WITH
SQ_clm_med_plan_type_stage AS (
	SELECT
		clm_med_plan_type_stage_id,
		cms_doc_cntl_num,
		injured_party_id,
		wbm_plan_ins_type,
		state_venue,
		med_oblig_to_clmt,
		orm_terminate_dt,
		no_fault_ins_limit,
		exhaust_limit_dt,
		tpoc_date1,
		tpoc_amount1,
		tpoc_fund_dlay_dt1,
		tpoc_date2,
		tpoc_amount2,
		tpoc_fund_dlay_dt2,
		tpoc_date3,
		tpoc_amount3,
		tpoc_fund_dlay_dt3,
		tpoc_date4,
		tpoc_amount4,
		tpoc_fund_dlay_dt4,
		tpoc_date5,
		tpoc_amount5,
		tpoc_fund_dlay_dt5,
		created_ts,
		created_user_id,
		modified_ts,
		modified_user_id,
		extract_date,
		as_of_date,
		record_count,
		source_system_id,
		plan_type_deleted
	FROM clm_med_plan_type_stage
	WHERE CREATED_TS >= '@{pipeline().parameters.SELECTION_START_TS}'  OR MODIFIED_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_values AS (
	SELECT
	clm_med_plan_type_stage_id,
	cms_doc_cntl_num,
	injured_party_id,
	wbm_plan_ins_type,
	state_venue,
	med_oblig_to_clmt,
	orm_terminate_dt,
	no_fault_ins_limit,
	exhaust_limit_dt,
	tpoc_date1,
	tpoc_amount1,
	tpoc_fund_dlay_dt1,
	tpoc_date2,
	tpoc_amount2,
	tpoc_fund_dlay_dt2,
	tpoc_date3,
	tpoc_amount3,
	tpoc_fund_dlay_dt3,
	tpoc_date4,
	tpoc_amount4,
	tpoc_fund_dlay_dt4,
	tpoc_date5,
	tpoc_amount5,
	tpoc_fund_dlay_dt5,
	created_ts,
	created_user_id,
	modified_ts,
	modified_user_id,
	extract_date,
	as_of_date,
	record_count,
	source_system_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID,
	plan_type_deleted
	FROM SQ_clm_med_plan_type_stage
),
arch_clm_med_plan_type_stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.arch_clm_med_plan_type_stage
	(clm_med_plan_type_stage_id, cms_doc_cntl_num, injured_party_id, wbm_plan_ins_type, state_venue, med_oblig_to_clmt, orm_terminate_dt, no_fault_ins_limit, exhaust_limit_dt, tpoc_date1, tpoc_amount1, tpoc_fund_dlay_dt1, tpoc_date2, tpoc_amount2, tpoc_fund_dlay_dt2, tpoc_date3, tpoc_amount3, tpoc_fund_dlay_dt3, tpoc_date4, tpoc_amount4, tpoc_fund_dlay_dt4, tpoc_date5, tpoc_amount5, tpoc_fund_dlay_dt5, created_ts, created_user_id, modified_ts, modified_user_id, extract_date, as_of_date, record_count, source_system_id, audit_id, plan_type_deleted)
	SELECT 
	CLM_MED_PLAN_TYPE_STAGE_ID, 
	CMS_DOC_CNTL_NUM, 
	INJURED_PARTY_ID, 
	WBM_PLAN_INS_TYPE, 
	STATE_VENUE, 
	MED_OBLIG_TO_CLMT, 
	ORM_TERMINATE_DT, 
	NO_FAULT_INS_LIMIT, 
	EXHAUST_LIMIT_DT, 
	TPOC_DATE1, 
	TPOC_AMOUNT1, 
	TPOC_FUND_DLAY_DT1, 
	TPOC_DATE2, 
	TPOC_AMOUNT2, 
	TPOC_FUND_DLAY_DT2, 
	TPOC_DATE3, 
	TPOC_AMOUNT3, 
	TPOC_FUND_DLAY_DT3, 
	TPOC_DATE4, 
	TPOC_AMOUNT4, 
	TPOC_FUND_DLAY_DT4, 
	TPOC_DATE5, 
	TPOC_AMOUNT5, 
	TPOC_FUND_DLAY_DT5, 
	CREATED_TS, 
	CREATED_USER_ID, 
	MODIFIED_TS, 
	MODIFIED_USER_ID, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID AS AUDIT_ID, 
	PLAN_TYPE_DELETED
	FROM EXP_values
),