WITH
SQ_CLM_COV_PKG_STAGE AS (
	SELECT
		clm_cov_pkg_id AS CLM_COV_PKG_ID,
		ccp_claim_nbr AS CCP_CLAIM_NBR,
		ccp_object_type_cd AS CCP_OBJECT_TYPE_CD,
		ccp_object_seq_nbr AS CCP_OBJECT_SEQ_NBR,
		ccp_pkg_type_cd AS CCP_PKG_TYPE_CD,
		ccp_pkg_seq_nbr AS CCP_PKG_SEQ_NBR,
		ccp_coi_pct AS CCP_COI_PCT,
		ccp_pkg_ded_amt AS CCP_PKG_DED_AMT,
		ccp_pkg_eff_dt AS CCP_PKG_EFF_DT,
		ccp_pkg_exp_dt AS CCP_PKG_EXP_DT,
		ccp_pkg_cnc_dt AS CCP_PKG_CNC_DT,
		ccp_item_des_id AS CCP_ITEM_DES_ID,
		ccp_pkg_limit_amt AS CCP_PKG_LIMIT_AMT,
		ccp_fin_ind AS CCP_FIN_IND,
		ccp_create_ts AS CCP_CREATE_TS,
		ccp_entry_opr_id AS CCP_ENTRY_OPR_ID,
		ccp_mnl_entry_ind AS CCP_MNL_ENTRY_IND,
		ccp_cov_seq_nbr AS CCP_COV_SEQ_NBR,
		ccp_update_opr_id AS CCP_UPDATE_OPR_ID,
		ccp_upd_ts AS CCP_UPD_TS,
		ccp_pmsd_ts AS CCP_PMSD_TS,
		ccp_ext_seq_nbr AS CCP_EXT_SEQ_NBR,
		ccp_lim_pps_amt AS CCP_LIM_PPS_AMT,
		ccp_lim_poc_amt AS CCP_LIM_POC_AMT,
		ccp_pd_lim_amt AS CCP_PD_LIM_AMT,
		ccp_class_cd AS CCP_CLASS_CD,
		ccp_ins_line_cd AS CCP_INS_LINE_CD,
		ccp_cov_cd AS CCP_COV_CD,
		ccp_bi_ded_amt AS CCP_BI_DED_AMT,
		ccp_pd_ded_amt AS CCP_PD_DED_AMT,
		ccp_ded_csl_ind AS CCP_DED_CSL_IND,
		ccp_ded_bi_ind AS CCP_DED_BI_IND,
		ccp_ded_pd_ind AS CCP_DED_PD_IND,
		ccp_cml_pkg_typ_cd AS CCP_CML_PKG_TYP_CD,
		ccp_pkg_ded_ind AS CCP_PKG_DED_IND,
		ccp_class_seq_nbr AS CCP_CLASS_SEQ_NBR,
		ccp_common_cov_ind AS CCP_COMMON_COV_IND,
		ccp_majr_peril_seq AS CCP_MAJR_PERIL_SEQ,
		ccp_sar_id AS CCP_SAR_ID,
		ccp_ins_line AS CCP_INS_LINE,
		ccp_loc_unit_num AS CCP_LOC_UNIT_NUM,
		ccp_risk_unit_grp AS CCP_RISK_UNIT_GRP,
		ccp_rsk_unt_gr_seq AS CCP_RSK_UNT_GR_SEQ,
		ccp_risk_unit AS CCP_RISK_UNIT,
		ccp_risk_type_ind AS CCP_RISK_TYPE_IND,
		ccp_sub_loc_num AS CCP_SUB_LOC_NUM,
		ccp_seq_risk_unit AS CCP_SEQ_RISK_UNIT,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		ccp_coverage_form,
		ccp_coverage_type,
		ccp_risk_type,
		ccp_pol_cov_id AS cpp_pol_cov_id
	FROM CLM_COV_PKG_STAGE
),
EXP_CLM_COV_PKG_STAGE AS (
	SELECT
	CLM_COV_PKG_ID,
	CCP_CLAIM_NBR,
	CCP_OBJECT_TYPE_CD,
	CCP_OBJECT_SEQ_NBR,
	CCP_PKG_TYPE_CD,
	CCP_PKG_SEQ_NBR,
	CCP_COI_PCT,
	CCP_PKG_DED_AMT,
	CCP_PKG_EFF_DT,
	CCP_PKG_EXP_DT,
	CCP_PKG_CNC_DT,
	CCP_ITEM_DES_ID,
	CCP_PKG_LIMIT_AMT,
	CCP_FIN_IND,
	CCP_CREATE_TS,
	CCP_ENTRY_OPR_ID,
	CCP_MNL_ENTRY_IND,
	CCP_COV_SEQ_NBR,
	CCP_UPDATE_OPR_ID,
	CCP_UPD_TS,
	CCP_PMSD_TS,
	CCP_EXT_SEQ_NBR,
	CCP_LIM_PPS_AMT,
	CCP_LIM_POC_AMT,
	CCP_PD_LIM_AMT,
	CCP_CLASS_CD,
	CCP_INS_LINE_CD,
	CCP_COV_CD,
	CCP_BI_DED_AMT,
	CCP_PD_DED_AMT,
	CCP_DED_CSL_IND,
	CCP_DED_BI_IND,
	CCP_DED_PD_IND,
	CCP_CML_PKG_TYP_CD,
	CCP_PKG_DED_IND,
	CCP_CLASS_SEQ_NBR,
	CCP_COMMON_COV_IND,
	CCP_MAJR_PERIL_SEQ,
	CCP_SAR_ID,
	CCP_INS_LINE,
	CCP_LOC_UNIT_NUM,
	CCP_RISK_UNIT_GRP,
	CCP_RSK_UNT_GR_SEQ,
	CCP_RISK_UNIT,
	CCP_RISK_TYPE_IND,
	CCP_SUB_LOC_NUM,
	CCP_SEQ_RISK_UNIT,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	ccp_coverage_form,
	ccp_coverage_type,
	ccp_risk_type,
	cpp_pol_cov_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AUDIT_ID_OP
	FROM SQ_CLM_COV_PKG_STAGE
),
ARCH_CLM_COV_PKG_STAGE AS (
	INSERT INTO ARCH_CLM_COV_PKG_STAGE
	(clm_cov_pkg_id, ccp_claim_nbr, ccp_object_type_cd, ccp_object_seq_nbr, ccp_pkg_type_cd, ccp_pkg_seq_nbr, ccp_coi_pct, ccp_pkg_ded_amt, ccp_pkg_eff_dt, ccp_pkg_exp_dt, ccp_pkg_cnc_dt, ccp_item_des_id, ccp_pkg_limit_amt, ccp_fin_ind, ccp_create_ts, ccp_entry_opr_id, ccp_mnl_entry_ind, ccp_cov_seq_nbr, ccp_update_opr_id, ccp_upd_ts, ccp_pmsd_ts, ccp_ext_seq_nbr, ccp_lim_pps_amt, ccp_lim_poc_amt, ccp_pd_lim_amt, ccp_class_cd, ccp_ins_line_cd, ccp_cov_cd, ccp_bi_ded_amt, ccp_pd_ded_amt, ccp_ded_csl_ind, ccp_ded_bi_ind, ccp_ded_pd_ind, ccp_cml_pkg_typ_cd, ccp_pkg_ded_ind, ccp_class_seq_nbr, ccp_common_cov_ind, ccp_majr_peril_seq, ccp_sar_id, ccp_ins_line, ccp_loc_unit_num, ccp_risk_unit_grp, ccp_rsk_unt_gr_seq, ccp_risk_unit, ccp_risk_type_ind, ccp_sub_loc_num, ccp_seq_risk_unit, extract_date, as_of_date, record_count, source_system_id, audit_id, ccp_coverage_form, ccp_coverage_type, ccp_risk_type, ccp_pol_cov_id)
	SELECT 
	CLM_COV_PKG_ID AS CLM_COV_PKG_ID, 
	CCP_CLAIM_NBR AS CCP_CLAIM_NBR, 
	CCP_OBJECT_TYPE_CD AS CCP_OBJECT_TYPE_CD, 
	CCP_OBJECT_SEQ_NBR AS CCP_OBJECT_SEQ_NBR, 
	CCP_PKG_TYPE_CD AS CCP_PKG_TYPE_CD, 
	CCP_PKG_SEQ_NBR AS CCP_PKG_SEQ_NBR, 
	CCP_COI_PCT AS CCP_COI_PCT, 
	CCP_PKG_DED_AMT AS CCP_PKG_DED_AMT, 
	CCP_PKG_EFF_DT AS CCP_PKG_EFF_DT, 
	CCP_PKG_EXP_DT AS CCP_PKG_EXP_DT, 
	CCP_PKG_CNC_DT AS CCP_PKG_CNC_DT, 
	CCP_ITEM_DES_ID AS CCP_ITEM_DES_ID, 
	CCP_PKG_LIMIT_AMT AS CCP_PKG_LIMIT_AMT, 
	CCP_FIN_IND AS CCP_FIN_IND, 
	CCP_CREATE_TS AS CCP_CREATE_TS, 
	CCP_ENTRY_OPR_ID AS CCP_ENTRY_OPR_ID, 
	CCP_MNL_ENTRY_IND AS CCP_MNL_ENTRY_IND, 
	CCP_COV_SEQ_NBR AS CCP_COV_SEQ_NBR, 
	CCP_UPDATE_OPR_ID AS CCP_UPDATE_OPR_ID, 
	CCP_UPD_TS AS CCP_UPD_TS, 
	CCP_PMSD_TS AS CCP_PMSD_TS, 
	CCP_EXT_SEQ_NBR AS CCP_EXT_SEQ_NBR, 
	CCP_LIM_PPS_AMT AS CCP_LIM_PPS_AMT, 
	CCP_LIM_POC_AMT AS CCP_LIM_POC_AMT, 
	CCP_PD_LIM_AMT AS CCP_PD_LIM_AMT, 
	CCP_CLASS_CD AS CCP_CLASS_CD, 
	CCP_INS_LINE_CD AS CCP_INS_LINE_CD, 
	CCP_COV_CD AS CCP_COV_CD, 
	CCP_BI_DED_AMT AS CCP_BI_DED_AMT, 
	CCP_PD_DED_AMT AS CCP_PD_DED_AMT, 
	CCP_DED_CSL_IND AS CCP_DED_CSL_IND, 
	CCP_DED_BI_IND AS CCP_DED_BI_IND, 
	CCP_DED_PD_IND AS CCP_DED_PD_IND, 
	CCP_CML_PKG_TYP_CD AS CCP_CML_PKG_TYP_CD, 
	CCP_PKG_DED_IND AS CCP_PKG_DED_IND, 
	CCP_CLASS_SEQ_NBR AS CCP_CLASS_SEQ_NBR, 
	CCP_COMMON_COV_IND AS CCP_COMMON_COV_IND, 
	CCP_MAJR_PERIL_SEQ AS CCP_MAJR_PERIL_SEQ, 
	CCP_SAR_ID AS CCP_SAR_ID, 
	CCP_INS_LINE AS CCP_INS_LINE, 
	CCP_LOC_UNIT_NUM AS CCP_LOC_UNIT_NUM, 
	CCP_RISK_UNIT_GRP AS CCP_RISK_UNIT_GRP, 
	CCP_RSK_UNT_GR_SEQ AS CCP_RSK_UNT_GR_SEQ, 
	CCP_RISK_UNIT AS CCP_RISK_UNIT, 
	CCP_RISK_TYPE_IND AS CCP_RISK_TYPE_IND, 
	CCP_SUB_LOC_NUM AS CCP_SUB_LOC_NUM, 
	CCP_SEQ_RISK_UNIT AS CCP_SEQ_RISK_UNIT, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	o_AUDIT_ID_OP AS AUDIT_ID, 
	CCP_COVERAGE_FORM, 
	CCP_COVERAGE_TYPE, 
	CCP_RISK_TYPE, 
	cpp_pol_cov_id AS CCP_POL_COV_ID
	FROM EXP_CLM_COV_PKG_STAGE
),