WITH
SQ_CLT_ADR_RELATION_STAGE AS (
	SELECT CLT_ADR_RELATION_STAGE.CLT_ADR_RELATION_stage_ID, CLT_ADR_RELATION_STAGE.CLIENT_ID, CLT_ADR_RELATION_STAGE.HISTORY_VLD_NBR, CLT_ADR_RELATION_STAGE.ADR_SEQ_NBR, CLT_ADR_RELATION_STAGE.CIAR_EFF_DT, CLT_ADR_RELATION_STAGE.ADR_ID, CLT_ADR_RELATION_STAGE.ADR_TYP_CD, CLT_ADR_RELATION_STAGE.TCH_OBJECT_KEY, CLT_ADR_RELATION_STAGE.CIAR_EXP_DT, CLT_ADR_RELATION_STAGE.CIAR_SER_ADR_1_TXT, CLT_ADR_RELATION_STAGE.CIAR_SER_CIT_NM, CLT_ADR_RELATION_STAGE.CIAR_SER_ST_CD, CLT_ADR_RELATION_STAGE.CIAR_SER_PST_CD, CLT_ADR_RELATION_STAGE.USER_ID, CLT_ADR_RELATION_STAGE.STATUS_CD, CLT_ADR_RELATION_STAGE.TERMINAL_ID, CLT_ADR_RELATION_STAGE.CIAR_EFF_ACY_TS, CLT_ADR_RELATION_STAGE.CIAR_EXP_ACY_TS, CLT_ADR_RELATION_STAGE.EXTRACT_DATE, CLT_ADR_RELATION_STAGE.AS_OF_DATE, CLT_ADR_RELATION_STAGE.RECORD_COUNT, CLT_ADR_RELATION_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLT_ADR_RELATION_STAGE
	WHERE
	CLT_ADR_RELATION_STAGE.CIAR_EFF_ACY_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLT_ADR_RELATION AS (
	SELECT
	CLT_ADR_RELATION_stage_ID,
	CLIENT_ID,
	HISTORY_VLD_NBR,
	ADR_SEQ_NBR,
	CIAR_EFF_DT,
	ADR_ID,
	ADR_TYP_CD,
	TCH_OBJECT_KEY,
	CIAR_EXP_DT,
	CIAR_SER_ADR_1_TXT,
	CIAR_SER_CIT_NM,
	CIAR_SER_ST_CD,
	CIAR_SER_PST_CD,
	USER_ID,
	STATUS_CD,
	TERMINAL_ID,
	CIAR_EFF_ACY_TS,
	CIAR_EXP_ACY_TS,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLT_ADR_RELATION_STAGE
),
arch_CLT_ADR_RELATION_STAGE AS (
	INSERT INTO arch_CLT_ADR_RELATION_STAGE
	(CLT_ADR_RELATION_stage_ID, CLIENT_ID, HISTORY_VLD_NBR, ADR_SEQ_NBR, CIAR_EFF_DT, ADR_ID, ADR_TYP_CD, TCH_OBJECT_KEY, CIAR_EXP_DT, CIAR_SER_ADR_1_TXT, CIAR_SER_CIT_NM, CIAR_SER_ST_CD, CIAR_SER_PST_CD, USER_ID, STATUS_CD, TERMINAL_ID, CIAR_EFF_ACY_TS, CIAR_EXP_ACY_TS, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, audit_id)
	SELECT 
	CLT_ADR_RELATION_STAGE_ID, 
	CLIENT_ID, 
	HISTORY_VLD_NBR, 
	ADR_SEQ_NBR, 
	CIAR_EFF_DT, 
	ADR_ID, 
	ADR_TYP_CD, 
	TCH_OBJECT_KEY, 
	CIAR_EXP_DT, 
	CIAR_SER_ADR_1_TXT, 
	CIAR_SER_CIT_NM, 
	CIAR_SER_ST_CD, 
	CIAR_SER_PST_CD, 
	USER_ID, 
	STATUS_CD, 
	TERMINAL_ID, 
	CIAR_EFF_ACY_TS, 
	CIAR_EXP_ACY_TS, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLT_ADR_RELATION
),