WITH
SQ_InsurPayPayment AS (
	select InsurPayPaymentId, 
		ExceedDraftNumber, 
		InsurPayBatchId, 
		InsurPayTrackingNumber, 
		InsurPayStatus, 
		PaymentCashedDate, 
		PaymentMethod, 
		OFACSubmittedTimestamp, 
		FlaggedByOFAC, 
		StopPayRequestedTime, 
		CreatedUserId, 
		CreatedDate, 
		ModifiedUserId, 
		ModifiedDate, 
		CheckNumber, 
		AccountNumberLast4Digit, 
		PaidDate, 
		PaymentType,
		StopPayRequestedUser,
		UploadAttemptCount,
		SupPaymentWorkflowId,
		LateInsurPayStatusNotifiedTimestamp,
		ExpediteRequested,
		CertifiedRequested,
		AdditionalDocumentsMessageRequested,
		MailTrackingNumber,
		LateExpeditedPaymentNotifiedTimestamp,
		LateExpeditedPaymentReceivedNotifiedTimestamp,
		 AttachedDocumentCount
	from dbo.InsurPayPayment 
	where (CreatedDate  >= '@{pipeline().parameters.SELECTION_START_TS}' 
	    or ModifiedDate  >= '@{pipeline().parameters.SELECTION_START_TS}')
	UNION 
	select p.InsurPayPaymentId, 
		p.ExceedDraftNumber, 
		p.InsurPayBatchId, 
		p.InsurPayTrackingNumber, 
		p.InsurPayStatus, 
		p.PaymentCashedDate, 
		p.PaymentMethod, 
		p.OFACSubmittedTimestamp, 
		p.FlaggedByOFAC, 
		p.StopPayRequestedTime, 
		p.CreatedUserId, 
		p.CreatedDate, 
		p.ModifiedUserId, 
		p.ModifiedDate, 
		p.CheckNumber, 
		p.AccountNumberLast4Digit, 
		p.PaidDate, 
		p.PaymentType,
		p.StopPayRequestedUser,
		p.UploadAttemptCount,
		p.SupPaymentWorkflowId,
		p.LateInsurPayStatusNotifiedTimestamp,
		p.ExpediteRequested,
		p.CertifiedRequested,
		p.AdditionalDocumentsMessageRequested,
		p.MailTrackingNumber,
		p.LateExpeditedPaymentNotifiedTimestamp,
		p.LateExpeditedPaymentReceivedNotifiedTimestamp,
	      p.AttachedDocumentCount
	from dbo.SupPaymentWorkflow w
	join dbo.InsurPayPayment p on p.SupPaymentWorkflowId = w.SupPaymentWorkflowId
	where (w.CreatedDate  >= '@{pipeline().parameters.SELECTION_START_TS}' 
	    or w.ModifiedDate  >= '@{pipeline().parameters.SELECTION_START_TS}')
),
EXPTRANS AS (
	SELECT
	InsurPayPaymentId,
	ExceedDraftNumber,
	InsurPayBatchId,
	InsurPayTrackingNumber,
	InsurPayStatus,
	PaymentCashedDate,
	PaymentMethod,
	OFACSubmittedTimestamp,
	FlaggedByOFAC,
	StopPayRequestedTime,
	CreatedUserId,
	CreatedDate,
	ModifiedUserId,
	ModifiedDate,
	CheckNumber,
	AccountNumberLast4Digit,
	PaidDate,
	PaymentType,
	StopPayRequestedUser,
	UploadAttemptCount,
	SupPaymentWorkflowId,
	LateInsurPayStatusNotifiedTimestamp,
	ExpediteRequested,
	CertifiedRequested,
	AdditionalDocumentsMessageRequested,
	MailTrackingNumber,
	LateExpeditedPaymentNotifiedTimestamp,
	LateExpeditedPaymentReceivedNotifiedTimestamp,
	AttachedDocumentCount,
	CURRENT_TIMESTAMP AS ExtractDate,
	'InsurPay' AS SourceSystemId
	FROM SQ_InsurPayPayment
),
InsurPayPaymentStage AS (
	TRUNCATE TABLE InsurPayPaymentStage;
	INSERT INTO InsurPayPaymentStage
	(ExtractDate, SourceSystemId, InsurPayPaymentId, ExceedDraftNumber, InsurPayBatchId, InsurPayTrackingNumber, InsurPayStatus, PaymentCashedDate, PaymentMethod, OFACSubmittedTimestamp, FlaggedByOFAC, StopPayRequestedTime, CreatedUserId, CreatedDate, ModifiedUserId, ModifiedDate, CheckNumber, AccountNumberLast4Digit, PaidDate, PaymentType, StopPayRequestedUser, UploadAttemptCount, SupPaymentWorkflowId, LateInsurPayStatusNotifiedTimestamp, ExpediteRequested, CertifiedRequested, AdditionalDocumentsMessageRequested, MailTrackingNumber, LateExpeditedPaymentNotifiedTimestamp, LateExpeditedPaymentReceivedNotifiedTimestamp, AttachedDocumentCount)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	INSURPAYPAYMENTID, 
	EXCEEDDRAFTNUMBER, 
	INSURPAYBATCHID, 
	INSURPAYTRACKINGNUMBER, 
	INSURPAYSTATUS, 
	PAYMENTCASHEDDATE, 
	PAYMENTMETHOD, 
	OFACSUBMITTEDTIMESTAMP, 
	FLAGGEDBYOFAC, 
	STOPPAYREQUESTEDTIME, 
	CREATEDUSERID, 
	CREATEDDATE, 
	MODIFIEDUSERID, 
	MODIFIEDDATE, 
	CHECKNUMBER, 
	ACCOUNTNUMBERLAST4DIGIT, 
	PAIDDATE, 
	PAYMENTTYPE, 
	STOPPAYREQUESTEDUSER, 
	UPLOADATTEMPTCOUNT, 
	SUPPAYMENTWORKFLOWID, 
	LATEINSURPAYSTATUSNOTIFIEDTIMESTAMP, 
	EXPEDITEREQUESTED, 
	CERTIFIEDREQUESTED, 
	ADDITIONALDOCUMENTSMESSAGEREQUESTED, 
	MAILTRACKINGNUMBER, 
	LATEEXPEDITEDPAYMENTNOTIFIEDTIMESTAMP, 
	LATEEXPEDITEDPAYMENTRECEIVEDNOTIFIEDTIMESTAMP, 
	ATTACHEDDOCUMENTCOUNT
	FROM EXPTRANS
),