WITH
SQ_CLM_COMMENTS_STAGE AS (
	SELECT CLM_COMMENTS_STAGE.CLM_COMMENTS_ID, CLM_COMMENTS_STAGE.COMMENT_ITEM_NBR, CLM_COMMENTS_STAGE.COMMENT_SEQ_NBR, CLM_COMMENTS_STAGE.FOLDER_KEY, CLM_COMMENTS_STAGE.COMMENT_TYPE, CLM_COMMENTS_STAGE.CLIENT_ID, CLM_COMMENTS_STAGE.AUTHOR_ID, CLM_COMMENTS_STAGE.ENTERED_DT, CLM_COMMENTS_STAGE.TCC_COMMENT_TXT, CLM_COMMENTS_STAGE.EXTRACT_DATE, CLM_COMMENTS_STAGE.AS_OF_DATE, CLM_COMMENTS_STAGE.RECORD_COUNT, CLM_COMMENTS_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLM_COMMENTS_STAGE
	WHERE
	CLM_COMMENTS_STAGE.ENTERED_DT >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLM_COMMENTS_STAGE AS (
	SELECT
	CLM_COMMENTS_ID,
	COMMENT_ITEM_NBR,
	COMMENT_SEQ_NBR,
	FOLDER_KEY,
	COMMENT_TYPE,
	CLIENT_ID,
	AUTHOR_ID,
	ENTERED_DT,
	TCC_COMMENT_TXT,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLM_COMMENTS_STAGE
),
ARCH_CLM_COMMENTS_STAGE AS (
	INSERT INTO ARCH_CLM_COMMENTS_STAGE
	(CLM_COMMENTS_ID, COMMENT_ITEM_NBR, COMMENT_SEQ_NBR, FOLDER_KEY, COMMENT_TYPE, CLIENT_ID, AUTHOR_ID, ENTERED_DT, TCC_COMMENT_TXT, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	CLM_COMMENTS_ID, 
	COMMENT_ITEM_NBR, 
	COMMENT_SEQ_NBR, 
	FOLDER_KEY, 
	COMMENT_TYPE, 
	CLIENT_ID, 
	AUTHOR_ID, 
	ENTERED_DT, 
	TCC_COMMENT_TXT, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLM_COMMENTS_STAGE
),