WITH
SQ_SUP_REPORT_OFFICE_STAGE AS (
	SELECT
		SUP_REPORT_OFFICE_ID,
		REPORT_OFFICE_CODE,
		EFF_DATE,
		CLAIM_MANAGER_CODE,
		REPORT_OFFICE_NAME,
		EXP_DATE,
		STAFWARE_TEAM_CODE,
		MODIFIED_DATE,
		MODIFIED_USER_ID,
		INSIDE_FIELD_IND,
		DIRECTOR_CODE,
		REPORT_OFFICE_NBR,
		DEPT_CODE,
		EXTRACT_DATE,
		AS_OF_DATE,
		RECORD_COUNT,
		SOURCE_SYSTEM_ID
	FROM SUP_REPORT_OFFICE_STAGE
),
EXP_SUP_REPORT_OFFICE_STAGE AS (
	SELECT
	SUP_REPORT_OFFICE_ID,
	REPORT_OFFICE_CODE,
	EFF_DATE,
	CLAIM_MANAGER_CODE,
	REPORT_OFFICE_NAME,
	EXP_DATE,
	STAFWARE_TEAM_CODE,
	MODIFIED_DATE,
	MODIFIED_USER_ID,
	INSIDE_FIELD_IND,
	DIRECTOR_CODE,
	REPORT_OFFICE_NBR,
	DEPT_CODE,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_SUP_REPORT_OFFICE_STAGE
),
ARCH_SUP_REPORT_OFFICE_STAGE AS (
	INSERT INTO ARCH_SUP_REPORT_OFFICE_STAGE
	(SUP_REPORT_OFFICE_ID, REPORT_OFFICE_CODE, EFF_DATE, CLAIM_MANAGER_CODE, REPORT_OFFICE_NAME, EXP_DATE, STAFWARE_TEAM_CODE, MODIFIED_DATE, MODIFIED_USER_ID, INSIDE_FIELD_IND, DIRECTOR_CODE, REPORT_OFFICE_NBR, DEPT_CODE, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	SUP_REPORT_OFFICE_ID, 
	REPORT_OFFICE_CODE, 
	EFF_DATE, 
	CLAIM_MANAGER_CODE, 
	REPORT_OFFICE_NAME, 
	EXP_DATE, 
	STAFWARE_TEAM_CODE, 
	MODIFIED_DATE, 
	MODIFIED_USER_ID, 
	INSIDE_FIELD_IND, 
	DIRECTOR_CODE, 
	REPORT_OFFICE_NBR, 
	DEPT_CODE, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_SUP_REPORT_OFFICE_STAGE
),