WITH
lkp_42gj_stage AS (
	SELECT
	pif_42gj_stage_id,
	IN_pif_symbol,
	IN_pif_policy_number,
	IN_pif_module,
	IN_ipfc4j_loss_year,
	IN_ipfc4j_loss_month,
	IN_ipfc4j_loss_day,
	IN_ipfc4j_loss_occurence,
	IN_ipfc4j_loss_claimant,
	IN_ipfc4j_use_code,
	pif_symbol,
	pif_policy_number,
	pif_module,
	ipfc4j_loss_year,
	ipfc4j_loss_month,
	ipfc4j_loss_day,
	ipfc4j_loss_occurence,
	ipfc4j_loss_claimant,
	ipfc4j_use_code
	FROM (
		SELECT 
			pif_42gj_stage_id,
			IN_pif_symbol,
			IN_pif_policy_number,
			IN_pif_module,
			IN_ipfc4j_loss_year,
			IN_ipfc4j_loss_month,
			IN_ipfc4j_loss_day,
			IN_ipfc4j_loss_occurence,
			IN_ipfc4j_loss_claimant,
			IN_ipfc4j_use_code,
			pif_symbol,
			pif_policy_number,
			pif_module,
			ipfc4j_loss_year,
			ipfc4j_loss_month,
			ipfc4j_loss_day,
			ipfc4j_loss_occurence,
			ipfc4j_loss_claimant,
			ipfc4j_use_code
		FROM pif_42gj_stage
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY pif_symbol,pif_policy_number,pif_module,ipfc4j_loss_year,ipfc4j_loss_month,ipfc4j_loss_day,ipfc4j_loss_occurence,ipfc4j_loss_claimant,ipfc4j_use_code ORDER BY pif_42gj_stage_id) = 1
),
SQ_PIF_42GQ_CMT_stage AS (
	SELECT
		pif_42gq_cmt_stage_id,
		pif_symbol,
		pif_policy_number,
		pif_module,
		ipfcgq_rec_length,
		ipfcgq_action_code,
		ipfcgq_file_id,
		ipfcgq_segment_id,
		ipfcgq_segment_level_code,
		ipfcgq_segment_part_code,
		ipfcgq_sub_part_code,
		ipfcgq_year_of_loss,
		ipfcgq_month_of_loss,
		ipfcgq_day_of_loss,
		ipfcgq_loss_occurence,
		ipfcgq_loss_claimant,
		ipfcgq_claimant_use_code,
		ipfcgq_claimant_use_seq,
		ipfcgq_year_process,
		ipfcgq_month_process,
		ipfcgq_day_process,
		ipfcgq_year_change_entry,
		ipfcgq_month_change_entry,
		ipfcgq_day_change_entry,
		ipfcgq_sequence_change_entry,
		ipfcgq_segment_status,
		ipfcgq_entry_operator,
		ipfcgq_loss_payee_num,
		ipfcgq_loss_payee_type,
		ipfcgq_reinsurance_indicator,
		ipfcgq_loss_adjustor_no,
		ipfcgq_loss_examiner,
		ipfcgq_other_assignment,
		ipfcgq_account_entered_date,
		ipfcgq_time_employed_years,
		ipfcgq_time_employed_months,
		ipfcgq_claim_number,
		ipfcgq_claim_filler,
		ipfcgq_claim_status,
		ipfcgq_loss_original_reserve,
		ipfcgq_os_loss_reserve,
		ipfcgq_os_expense_reserve,
		ipfcgq_total_loss,
		ipfcgq_total_expense,
		ipfcgq_total_recoveries,
		ipfcgq_beg_os_loss_reserve,
		ipfcgq_contact_year,
		ipfcgq_contact_month,
		ipfcgq_contact_day,
		ipfcgq_denial_year,
		ipfcgq_denial_month,
		ipfcgq_denial_day,
		ipfcgq_loss_handling_office,
		ipfcgq_loss_handling_branch,
		ipfcgq_loss_aia_codes_1_2,
		ipfcgq_loss_aia_codes_3_4,
		ipfcgq_loss_aia_codes_5_6,
		ipfcgq_aia_sub_code,
		ipfcgq_loss_age,
		ipfcgq_claimant_type,
		ipfcgq_loss_claimant_name,
		ipfcgq_claimant_birth_year,
		ipfcgq_claimant_birth_month,
		ipfcgq_claimant_birth_day,
		ipfcgq_loss_sex,
		ipfcgq_marital_status,
		ipfcgq_accident_cov_state,
		ipfcgq_cib_report_ind,
		ipfcgq_official_report_ind,
		ipfcgq_death_indicator,
		ipfcgq_excess_loss_ind,
		ipfcgq_loss_suit,
		ipfcgq_other_insurance,
		ipfcgq_recorded_statement,
		ipfcgq_loss_cause,
		ipfcgq_loss_coverage_code,
		ipfcgq_catastrophe_no,
		ipfcgq_excess_catastrophe_no,
		ipfcgq_type_disability,
		ipfcgq_liab_over_ind,
		ipfcgq_leg_exp_clmts,
		ipfcgq_percent_disability,
		ipfcgq_loss_cov_code_2,
		ipfcgq_event_cat_code,
		ipfcgq_claim_code_basis,
		ipfcgq_acct_state_only,
		ipfcgq_mngd_care_org,
		ipfcgq_number_of_part78,
		ipfcgq_offset_onset_ind,
		ipfcgq_date_hire,
		ipfcgq_pms_future_use_gq,
		ipfcgq_direct_reporting,
		ipfcgq_cust_spl_use_gq,
		ipfcgq_yr2000_cust_use,
		inf_action,
		inf_timestamp,
		logical_flag,
		extract_date,
		as_of_date,
		record_count,
		source_system_id
	FROM PIF_42GQ_CMT_stage
),
EXP_Update_STAGE_42GJ AS (
	SELECT
	pif_symbol,
	pif_policy_number,
	pif_module,
	ipfcgq_year_of_loss,
	ipfcgq_month_of_loss,
	ipfcgq_day_of_loss,
	ipfcgq_loss_occurence,
	ipfcgq_loss_claimant,
	ipfcgq_claimant_use_code,
	logical_flag,
	-- *INF*: DECODE(logical_flag,
	-- '0','5',
	-- '1','5',
	-- '-1','2',
	-- '-2','3',
	-- '-3','4',
	-- '6','6','9')
	DECODE(
	    logical_flag,
	    '0', '5',
	    '1', '5',
	    '-1', '2',
	    '-2', '3',
	    '-3', '4',
	    '6', '6',
	    '9'
	) AS logical_flag_insert,
	-- *INF*: :LKP.LKP_42GJ_STAGE(pif_symbol,pif_policy_number,pif_module,ipfcgq_year_of_loss,ipfcgq_month_of_loss,ipfcgq_day_of_loss,ipfcgq_loss_occurence,ipfcgq_loss_claimant,ipfcgq_claimant_use_code)
	LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.pif_42gj_stage_id AS pif_42gj_stage_id,
	SYSDATE AS extract_date,
	SYSDATE AS as_of_date,
	source_system_id
	FROM SQ_PIF_42GQ_CMT_stage
	LEFT JOIN LKP_42GJ_STAGE LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code
	ON LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.pif_symbol = pif_symbol
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.pif_policy_number = pif_policy_number
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.pif_module = pif_module
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_loss_year = ipfcgq_year_of_loss
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_loss_month = ipfcgq_month_of_loss
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_loss_day = ipfcgq_day_of_loss
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_loss_occurence = ipfcgq_loss_occurence
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_loss_claimant = ipfcgq_loss_claimant
	AND LKP_42GJ_STAGE_pif_symbol_pif_policy_number_pif_module_ipfcgq_year_of_loss_ipfcgq_month_of_loss_ipfcgq_day_of_loss_ipfcgq_loss_occurence_ipfcgq_loss_claimant_ipfcgq_claimant_use_code.ipfc4j_use_code = ipfcgq_claimant_use_code

),
fil_New_rows AS (
	SELECT
	pif_symbol, 
	pif_policy_number, 
	pif_module, 
	ipfcgq_year_of_loss, 
	ipfcgq_month_of_loss, 
	ipfcgq_day_of_loss, 
	ipfcgq_loss_occurence, 
	ipfcgq_loss_claimant, 
	ipfcgq_claimant_use_code, 
	logical_flag_insert, 
	pif_42gj_stage_id, 
	extract_date, 
	as_of_date, 
	source_system_id
	FROM EXP_Update_STAGE_42GJ
	WHERE ISNULL(pif_42gj_stage_id)
),
PIF_42GJ_stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.PIF_42GJ_stage
	(pif_symbol, pif_policy_number, pif_module, ipfc4j_loss_year, ipfc4j_loss_month, ipfc4j_loss_day, ipfc4j_loss_occurence, ipfc4j_loss_claimant, ipfc4j_use_code, logical_flag, extract_date, as_of_date, source_system_id)
	SELECT 
	PIF_SYMBOL, 
	PIF_POLICY_NUMBER, 
	PIF_MODULE, 
	ipfcgq_year_of_loss AS IPFC4J_LOSS_YEAR, 
	ipfcgq_month_of_loss AS IPFC4J_LOSS_MONTH, 
	ipfcgq_day_of_loss AS IPFC4J_LOSS_DAY, 
	ipfcgq_loss_occurence AS IPFC4J_LOSS_OCCURENCE, 
	ipfcgq_loss_claimant AS IPFC4J_LOSS_CLAIMANT, 
	ipfcgq_claimant_use_code AS IPFC4J_USE_CODE, 
	logical_flag_insert AS LOGICAL_FLAG, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	SOURCE_SYSTEM_ID
	FROM fil_New_rows
),