WITH
SQ_CLM_TRANS_BENEFIT_STAGE AS (
	SELECT
		clm_trans_benefit_id AS CLM_TRANS_BENEFIT_ID,
		ctb_claim_nbr AS CTB_CLAIM_NBR,
		ctb_draft_nbr AS CTB_DRAFT_NBR,
		ctb_benefit_type AS CTB_BENEFIT_TYPE,
		ctb_bene_seq_num AS CTB_BENE_SEQ_NUM,
		ctb_object_type_cd AS CTB_OBJECT_TYPE_CD,
		ctb_object_seq_nbr AS CTB_OBJECT_SEQ_NBR,
		ctb_cov_type_cd AS CTB_COV_TYPE_CD,
		ctb_cov_seq_nbr AS CTB_COV_SEQ_NBR,
		ctb_bur_cause_loss AS CTB_BUR_CAUSE_LOSS,
		ctb_fin_type_cd AS CTB_FIN_TYPE_CD,
		ctb_entry_opr_id AS CTB_ENTRY_OPR_ID,
		ctb_create_ts AS CTB_CREATE_TS,
		ctb_update_ts AS CTB_UPDATE_TS,
		ctb_update_opr_id AS CTB_UPDATE_OPR_ID,
		ctb_benefit_start AS CTB_BENEFIT_START,
		ctb_benefit_end AS CTB_BENEFIT_END,
		ctb_benefit_amt AS CTB_BENEFIT_AMT,
		ctb_num_weeks AS CTB_NUM_WEEKS,
		ctb_num_days AS CTB_NUM_DAYS,
		ctb_num_holiday AS CTB_NUM_HOLIDAY,
		ctb_hours_worked AS CTB_HOURS_WORKED,
		ctb_hourly_rate AS CTB_HOURLY_RATE,
		ctb_tpd_wkly_wage AS CTB_TPD_WKLY_WAGE,
		ctb_tpd_wage_loss AS CTB_TPD_WAGE_LOSS,
		ctb_tpd_rate_fctr AS CTB_TPD_RATE_FCTR,
		ctb_tpd_rate AS CTB_TPD_RATE,
		ctb_invoice_nbr AS CTB_INVOICE_NBR,
		ctb_cost_cont_sav AS CTB_COST_CONT_SAV,
		ctb_billed_amt AS CTB_BILLED_AMT,
		ctb_cost_cont_ppo AS CTB_COST_CONT_PPO,
		ctb_cost_cont_red AS CTB_COST_CONT_RED,
		ctb_aty_file_num AS CTB_ATY_FILE_NUM,
		ctb_aty_fee_amt AS CTB_ATY_FEE_AMT,
		ctb_aty_costs_amt AS CTB_ATY_COSTS_AMT,
		ctb_event_date AS CTB_EVENT_DATE,
		ctb_amt_earned AS CTB_AMT_EARNED,
		ctb_bene_mis_cmt AS CTB_BENE_MIS_CMT,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		ctb_bene_litigated,
		ctb_lump_sum_ind,
		ctb_benefit_offset_cd,
		ctb_benefit_offset_amt
	FROM CLM_TRANS_BENEFIT_STAGE
),
EXP_CLM_TRANS_BENEFIT_STAGE AS (
	SELECT
	CLM_TRANS_BENEFIT_ID,
	CTB_CLAIM_NBR,
	CTB_DRAFT_NBR,
	CTB_BENEFIT_TYPE,
	CTB_BENE_SEQ_NUM,
	CTB_OBJECT_TYPE_CD,
	CTB_OBJECT_SEQ_NBR,
	CTB_COV_TYPE_CD,
	CTB_COV_SEQ_NBR,
	CTB_BUR_CAUSE_LOSS,
	CTB_FIN_TYPE_CD,
	CTB_ENTRY_OPR_ID,
	CTB_CREATE_TS,
	CTB_UPDATE_TS,
	CTB_UPDATE_OPR_ID,
	CTB_BENEFIT_START,
	CTB_BENEFIT_END,
	CTB_BENEFIT_AMT,
	CTB_NUM_WEEKS,
	CTB_NUM_DAYS,
	CTB_NUM_HOLIDAY,
	CTB_HOURS_WORKED,
	CTB_HOURLY_RATE,
	CTB_TPD_WKLY_WAGE,
	CTB_TPD_WAGE_LOSS,
	CTB_TPD_RATE_FCTR,
	CTB_TPD_RATE,
	CTB_INVOICE_NBR,
	CTB_COST_CONT_SAV,
	CTB_BILLED_AMT,
	CTB_COST_CONT_PPO,
	CTB_COST_CONT_RED,
	CTB_ATY_FILE_NUM,
	CTB_ATY_FEE_AMT,
	CTB_ATY_COSTS_AMT,
	CTB_EVENT_DATE,
	CTB_AMT_EARNED,
	CTB_BENE_MIS_CMT,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP,
	ctb_bene_litigated,
	ctb_lump_sum_ind,
	ctb_benefit_offset_cd,
	ctb_benefit_offset_amt
	FROM SQ_CLM_TRANS_BENEFIT_STAGE
),
ARCH_CLM_TRANS_BENEFIT_STAGE AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ARCH_CLM_TRANS_BENEFIT_STAGE
	(clm_trans_benefit_id, ctb_claim_nbr, ctb_draft_nbr, ctb_benefit_type, ctb_bene_seq_num, ctb_object_type_cd, ctb_object_seq_nbr, ctb_cov_type_cd, ctb_cov_seq_nbr, ctb_bur_cause_loss, ctb_fin_type_cd, ctb_entry_opr_id, ctb_create_ts, ctb_update_ts, ctb_update_opr_id, ctb_benefit_start, ctb_benefit_end, ctb_benefit_amt, ctb_num_weeks, ctb_num_days, ctb_num_holiday, ctb_hours_worked, ctb_hourly_rate, ctb_tpd_wkly_wage, ctb_tpd_wage_loss, ctb_tpd_rate_fctr, ctb_tpd_rate, ctb_invoice_nbr, ctb_cost_cont_sav, ctb_billed_amt, ctb_cost_cont_ppo, ctb_cost_cont_red, ctb_aty_file_num, ctb_aty_fee_amt, ctb_aty_costs_amt, ctb_event_date, ctb_amt_earned, ctb_bene_mis_cmt, extract_date, as_of_date, record_count, source_system_id, audit_id, ctb_bene_litigated, ctb_lump_sum_ind, CTB_BENEFIT_OFFSET_CD, CTB_BENEFIT_OFFSET_AMT)
	SELECT 
	CLM_TRANS_BENEFIT_ID AS CLM_TRANS_BENEFIT_ID, 
	CTB_CLAIM_NBR AS CTB_CLAIM_NBR, 
	CTB_DRAFT_NBR AS CTB_DRAFT_NBR, 
	CTB_BENEFIT_TYPE AS CTB_BENEFIT_TYPE, 
	CTB_BENE_SEQ_NUM AS CTB_BENE_SEQ_NUM, 
	CTB_OBJECT_TYPE_CD AS CTB_OBJECT_TYPE_CD, 
	CTB_OBJECT_SEQ_NBR AS CTB_OBJECT_SEQ_NBR, 
	CTB_COV_TYPE_CD AS CTB_COV_TYPE_CD, 
	CTB_COV_SEQ_NBR AS CTB_COV_SEQ_NBR, 
	CTB_BUR_CAUSE_LOSS AS CTB_BUR_CAUSE_LOSS, 
	CTB_FIN_TYPE_CD AS CTB_FIN_TYPE_CD, 
	CTB_ENTRY_OPR_ID AS CTB_ENTRY_OPR_ID, 
	CTB_CREATE_TS AS CTB_CREATE_TS, 
	CTB_UPDATE_TS AS CTB_UPDATE_TS, 
	CTB_UPDATE_OPR_ID AS CTB_UPDATE_OPR_ID, 
	CTB_BENEFIT_START AS CTB_BENEFIT_START, 
	CTB_BENEFIT_END AS CTB_BENEFIT_END, 
	CTB_BENEFIT_AMT AS CTB_BENEFIT_AMT, 
	CTB_NUM_WEEKS AS CTB_NUM_WEEKS, 
	CTB_NUM_DAYS AS CTB_NUM_DAYS, 
	CTB_NUM_HOLIDAY AS CTB_NUM_HOLIDAY, 
	CTB_HOURS_WORKED AS CTB_HOURS_WORKED, 
	CTB_HOURLY_RATE AS CTB_HOURLY_RATE, 
	CTB_TPD_WKLY_WAGE AS CTB_TPD_WKLY_WAGE, 
	CTB_TPD_WAGE_LOSS AS CTB_TPD_WAGE_LOSS, 
	CTB_TPD_RATE_FCTR AS CTB_TPD_RATE_FCTR, 
	CTB_TPD_RATE AS CTB_TPD_RATE, 
	CTB_INVOICE_NBR AS CTB_INVOICE_NBR, 
	CTB_COST_CONT_SAV AS CTB_COST_CONT_SAV, 
	CTB_BILLED_AMT AS CTB_BILLED_AMT, 
	CTB_COST_CONT_PPO AS CTB_COST_CONT_PPO, 
	CTB_COST_CONT_RED AS CTB_COST_CONT_RED, 
	CTB_ATY_FILE_NUM AS CTB_ATY_FILE_NUM, 
	CTB_ATY_FEE_AMT AS CTB_ATY_FEE_AMT, 
	CTB_ATY_COSTS_AMT AS CTB_ATY_COSTS_AMT, 
	CTB_EVENT_DATE AS CTB_EVENT_DATE, 
	CTB_AMT_EARNED AS CTB_AMT_EARNED, 
	CTB_BENE_MIS_CMT AS CTB_BENE_MIS_CMT, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	CTB_BENE_LITIGATED, 
	CTB_LUMP_SUM_IND, 
	ctb_benefit_offset_cd AS CTB_BENEFIT_OFFSET_CD, 
	ctb_benefit_offset_amt AS CTB_BENEFIT_OFFSET_AMT
	FROM EXP_CLM_TRANS_BENEFIT_STAGE
),