WITH
SQ_question AS (
	SELECT
		ques.question_guid, 
		ques.parent_question_guid, 
		ques.optn_set_guid, 
		ques.applicability_filter_guid, 
		ques.app_context_guid, 
		ques.app_context_grp_guid, 
		ques.display_name, 
		ques.logical_name, 
		ques.published_to_prod_flag, 
		ques.enabled_flag, 
		ques.help_text, 
		ques.prompt, 
		ques.question_template_id, 
		ques.settings, 
		ques.traceability_id, 
		ques.triggers, 
		ques.sort_order, 
		ques.notes, 
		ques.surrogate_question_guid, 
		ques.created_user_id, 
		ques.created_date, 
		ques.modified_user_id, 
		ques.modified_date, 
		ques.eff_date, 
		ques.exp_date
	FROM @{pipeline().parameters.SOURCE_TABLE_OWNER}.question AS ques WITH (NOLOCK) 
	WHERE ques.created_date >= '@{pipeline().parameters.SELECTION_START_TS}'
	          OR ques.modified_date >= '@{pipeline().parameters.SELECTION_END_TS}'
),
EXP_SOURCE AS (
	SELECT
	question_guid,
	parent_question_guid,
	optn_set_guid,
	applicability_filter_guid,
	app_context_guid,
	app_context_grp_guid,
	display_name,
	logical_name,
	published_to_prod_flag,
	enabled_flag,
	help_text,
	prompt,
	question_template_id,
	settings,
	traceability_id,
	triggers,
	sort_order,
	notes,
	surrogate_question_guid,
	created_user_id,
	created_date,
	modified_user_id,
	modified_date,
	eff_date,
	exp_date,
	sysdate AS extract_date,
	sysdate AS as_of_date,
	'' AS record_count,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS source_system_id
	FROM SQ_question
),
question_stage_INS AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.question_stage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.question_stage
	(question_guid, parent_question_guid, optn_set_guid, applicability_filter_guid, app_context_guid, app_context_grp_guid, display_name, logical_name, published_to_prod_flag, enabled_flag, help_text, prompt, question_template_id, settings, traceability_id, triggers, sort_order, notes, surrogate_question_guid, created_user_id, created_date, modified_user_id, modified_date, eff_date, exp_date, extract_date, as_of_date, record_count, source_system_id)
	SELECT 
	QUESTION_GUID, 
	PARENT_QUESTION_GUID, 
	OPTN_SET_GUID, 
	APPLICABILITY_FILTER_GUID, 
	APP_CONTEXT_GUID, 
	APP_CONTEXT_GRP_GUID, 
	DISPLAY_NAME, 
	LOGICAL_NAME, 
	PUBLISHED_TO_PROD_FLAG, 
	ENABLED_FLAG, 
	HELP_TEXT, 
	PROMPT, 
	QUESTION_TEMPLATE_ID, 
	SETTINGS, 
	TRACEABILITY_ID, 
	TRIGGERS, 
	SORT_ORDER, 
	NOTES, 
	SURROGATE_QUESTION_GUID, 
	CREATED_USER_ID, 
	CREATED_DATE, 
	MODIFIED_USER_ID, 
	MODIFIED_DATE, 
	EFF_DATE, 
	EXP_DATE, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID
	FROM EXP_SOURCE
),