WITH
SQ_CMS_Claims_Response_File AS (

-- TODO Manual --

),
EXP_Default AS (
	SELECT
	Record_Identifier,
	Submitted_DCN,
	-- *INF*: ltrim(rtrim(Submitted_DCN))
	ltrim(rtrim(Submitted_DCN)) AS out_Submitted_DCN,
	Submitted_Action_Type,
	Injured_Party_HICN,
	Submitted_Injured_Party_SSN,
	Submitted_Injured_Party_Last_Name,
	Submitted_Injured_Party_First_Name,
	Submitted_Injured_Party_Middle_Initial,
	Submitted_Injured_Party_Gender,
	Submitted_Injured_Party_DOB,
	Submitted_Plan_TIN,
	Submitted_Plan_Office_Code,
	Submitted_Policy_Number,
	Submitted_Claim_Number,
	-- *INF*: LTRIM(RTRIM(Submitted_Claim_Number))
	LTRIM(RTRIM(Submitted_Claim_Number)) AS out_Submitted_Claim_Number,
	Reserved_For_Future_Use,
	Applied_Injured_Party_HICN,
	Reserved_For_Future_Use1,
	Applied_Injured_Party_Last_Name,
	Applied_Injured_Party_First_Name,
	Applied_Injured_Party_Middle_Initial,
	Applied_Injured_Party_Gender,
	Applied_Injured_Party_DOB,
	Applied_MSP_Effective_Date,
	Applied_MSP_Termination_Date,
	Applied_MSP_Type_Indicator,
	Reserved_For_Future_Use2,
	Applied_Disposition_Code,
	Applied_Error_Code1,
	Applied_Error_Code2,
	Applied_Error_Code3,
	Applied_Error_Code4,
	Applied_Error_Code5,
	Applied_Error_Code6,
	Applied_Error_Code7,
	Applied_Error_Code8,
	Applied_Error_Code9,
	Applied_Error_Code10,
	Applied_Compliance_Flag1,
	Applied_Compliance_Flag2,
	Applied_Compliance_Flag3,
	Applied_Compliance_Flag4,
	Applied_Compliance_Flag5,
	Applied_Compliance_Flag6,
	Applied_Compliance_Flag7,
	Applied_Compliance_Flag8,
	Applied_Compliance_Flag9,
	Applied_Compliance_Flag10,
	Reserved_For_Future_Use3,
	SYSDATE AS System_Date
	FROM SQ_CMS_Claims_Response_File
),
FIL_Header_Trailer AS (
	SELECT
	Record_Identifier, 
	out_Submitted_DCN AS Submitted_DCN, 
	Submitted_Action_Type, 
	Injured_Party_HICN, 
	Submitted_Injured_Party_SSN, 
	Submitted_Injured_Party_Last_Name, 
	Submitted_Injured_Party_First_Name, 
	Submitted_Injured_Party_Middle_Initial, 
	Submitted_Injured_Party_Gender, 
	Submitted_Injured_Party_DOB, 
	Submitted_Plan_TIN, 
	Submitted_Plan_Office_Code, 
	Submitted_Policy_Number, 
	out_Submitted_Claim_Number AS Submitted_Claim_Number, 
	Reserved_For_Future_Use, 
	Applied_Injured_Party_HICN, 
	Reserved_For_Future_Use1, 
	Applied_Injured_Party_Last_Name, 
	Applied_Injured_Party_First_Name, 
	Applied_Injured_Party_Middle_Initial, 
	Applied_Injured_Party_Gender, 
	Applied_Injured_Party_DOB, 
	Applied_MSP_Effective_Date, 
	Applied_MSP_Termination_Date, 
	Applied_MSP_Type_Indicator, 
	Reserved_For_Future_Use2, 
	Applied_Disposition_Code, 
	Applied_Error_Code1, 
	Applied_Error_Code2, 
	Applied_Error_Code3, 
	Applied_Error_Code4, 
	Applied_Error_Code5, 
	Applied_Error_Code6, 
	Applied_Error_Code7, 
	Applied_Error_Code8, 
	Applied_Error_Code9, 
	Applied_Error_Code10, 
	Applied_Compliance_Flag1, 
	Applied_Compliance_Flag2, 
	Applied_Compliance_Flag3, 
	Applied_Compliance_Flag4, 
	Applied_Compliance_Flag5, 
	Applied_Compliance_Flag6, 
	Applied_Compliance_Flag7, 
	Applied_Compliance_Flag8, 
	Applied_Compliance_Flag9, 
	Applied_Compliance_Flag10, 
	Reserved_For_Future_Use3, 
	System_Date
	FROM EXP_Default
	WHERE IIF(IN(Record_Identifier,'NGRH','NGRT'), FALSE,TRUE)
),
LKP_Claim_Source_Determine AS (
	SELECT
	claim_number,
	claim_rep_first_name,
	claim_rep_last_name,
	handling_office_mgr,
	source_sys_id,
	Submitted_Claim_Number
	FROM (
		SELECT CASE co.source_sys_id
		        WHEN 'PMS' THEN LTRIM(RTRIM(co.claim_occurrence_key))
		        ELSE LTRIM(RTRIM(co.s3p_claim_num))
		    END AS claim_number, 
		    cr.claim_rep_first_name AS claim_rep_first_name, 
		    cr.claim_rep_last_name AS claim_rep_last_name, 
		    cr.handling_office_mgr AS handling_office_mgr, 
		    co.source_sys_id AS source_sys_id
		FROM dbo.claim_occurrence co
		INNER JOIN dbo.claim_representative_occurrence cro ON cro.claim_occurrence_ak_id = co.claim_occurrence_ak_id
		    AND cro.crrnt_snpsht_flag = 1
		    AND cro.claim_rep_role_code = 'H'
		INNER JOIN dbo.claim_representative cr ON cr.claim_rep_ak_id = cro.claim_rep_ak_id
		    AND cr.crrnt_snpsht_flag = 1
		WHERE co.crrnt_snpsht_flag = 1 --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY claim_number ORDER BY claim_number) = 1
),
EXP_Post_LKP AS (
	SELECT
	FIL_Header_Trailer.Submitted_DCN,
	FIL_Header_Trailer.Submitted_Action_Type,
	FIL_Header_Trailer.Injured_Party_HICN,
	FIL_Header_Trailer.Submitted_Injured_Party_SSN,
	FIL_Header_Trailer.Submitted_Injured_Party_Last_Name,
	FIL_Header_Trailer.Submitted_Injured_Party_First_Name,
	FIL_Header_Trailer.Submitted_Injured_Party_Middle_Initial,
	FIL_Header_Trailer.Submitted_Injured_Party_Gender,
	FIL_Header_Trailer.Submitted_Injured_Party_DOB,
	FIL_Header_Trailer.Submitted_Plan_TIN,
	FIL_Header_Trailer.Submitted_Plan_Office_Code,
	FIL_Header_Trailer.Submitted_Policy_Number,
	FIL_Header_Trailer.Submitted_Claim_Number,
	FIL_Header_Trailer.Reserved_For_Future_Use,
	FIL_Header_Trailer.Applied_Injured_Party_HICN,
	FIL_Header_Trailer.Reserved_For_Future_Use1,
	FIL_Header_Trailer.Applied_Injured_Party_Last_Name,
	FIL_Header_Trailer.Applied_Injured_Party_First_Name,
	FIL_Header_Trailer.Applied_Injured_Party_Middle_Initial,
	FIL_Header_Trailer.Applied_Injured_Party_Gender,
	FIL_Header_Trailer.Applied_Injured_Party_DOB,
	FIL_Header_Trailer.Applied_MSP_Effective_Date,
	FIL_Header_Trailer.Applied_MSP_Termination_Date,
	FIL_Header_Trailer.Applied_MSP_Type_Indicator,
	FIL_Header_Trailer.Reserved_For_Future_Use2,
	FIL_Header_Trailer.Applied_Disposition_Code,
	FIL_Header_Trailer.Applied_Error_Code1,
	FIL_Header_Trailer.Applied_Error_Code2,
	FIL_Header_Trailer.Applied_Error_Code3,
	FIL_Header_Trailer.Applied_Error_Code4,
	FIL_Header_Trailer.Applied_Error_Code5,
	FIL_Header_Trailer.Applied_Error_Code6,
	FIL_Header_Trailer.Applied_Error_Code7,
	FIL_Header_Trailer.Applied_Error_Code8,
	FIL_Header_Trailer.Applied_Error_Code9,
	FIL_Header_Trailer.Applied_Error_Code10,
	FIL_Header_Trailer.Applied_Compliance_Flag1,
	FIL_Header_Trailer.Applied_Compliance_Flag2,
	FIL_Header_Trailer.Applied_Compliance_Flag3,
	FIL_Header_Trailer.Applied_Compliance_Flag4,
	FIL_Header_Trailer.Applied_Compliance_Flag5,
	FIL_Header_Trailer.Applied_Compliance_Flag6,
	FIL_Header_Trailer.Applied_Compliance_Flag7,
	FIL_Header_Trailer.Applied_Compliance_Flag8,
	FIL_Header_Trailer.Applied_Compliance_Flag9,
	FIL_Header_Trailer.Applied_Compliance_Flag10,
	FIL_Header_Trailer.Reserved_For_Future_Use3,
	FIL_Header_Trailer.System_Date,
	LKP_Claim_Source_Determine.claim_number,
	LKP_Claim_Source_Determine.claim_rep_first_name,
	LKP_Claim_Source_Determine.claim_rep_last_name,
	-- *INF*: CONCAT(CONCAT(claim_rep_first_name,' '),  claim_rep_last_name)
	CONCAT(CONCAT(claim_rep_first_name, ' '), claim_rep_last_name) AS claim_rep_full_name,
	LKP_Claim_Source_Determine.handling_office_mgr,
	LKP_Claim_Source_Determine.source_sys_id
	FROM FIL_Header_Trailer
	LEFT JOIN LKP_Claim_Source_Determine
	ON LKP_Claim_Source_Determine.claim_number = FIL_Header_Trailer.Submitted_Claim_Number
),
RTR_SPLIT_SOURCE AS (
	SELECT
	Submitted_DCN,
	Submitted_Action_Type,
	Injured_Party_HICN,
	Submitted_Injured_Party_SSN,
	Submitted_Injured_Party_Last_Name,
	Submitted_Injured_Party_First_Name,
	Submitted_Injured_Party_Middle_Initial,
	Submitted_Injured_Party_Gender,
	Submitted_Injured_Party_DOB,
	Submitted_Plan_TIN,
	Submitted_Plan_Office_Code,
	Submitted_Policy_Number,
	Submitted_Claim_Number,
	Reserved_For_Future_Use,
	Applied_Injured_Party_HICN,
	Reserved_For_Future_Use1 AS Reserved_For_Future_Use11,
	Applied_Injured_Party_Last_Name,
	Applied_Injured_Party_First_Name,
	Applied_Injured_Party_Middle_Initial,
	Applied_Injured_Party_Gender,
	Applied_Injured_Party_DOB,
	Applied_MSP_Effective_Date,
	Applied_MSP_Termination_Date,
	Applied_MSP_Type_Indicator,
	Reserved_For_Future_Use2 AS Reserved_For_Future_Use21,
	Applied_Disposition_Code,
	Applied_Error_Code1,
	Applied_Error_Code2,
	Applied_Error_Code3,
	Applied_Error_Code4,
	Applied_Error_Code5,
	Applied_Error_Code6,
	Applied_Error_Code7,
	Applied_Error_Code8,
	Applied_Error_Code9,
	Applied_Error_Code10,
	Applied_Compliance_Flag1,
	Applied_Compliance_Flag2,
	Applied_Compliance_Flag3,
	Applied_Compliance_Flag4,
	Applied_Compliance_Flag5,
	Applied_Compliance_Flag6,
	Applied_Compliance_Flag7,
	Applied_Compliance_Flag8,
	Applied_Compliance_Flag9,
	Applied_Compliance_Flag10,
	Reserved_For_Future_Use3 AS Reserved_For_Future_Use31,
	System_Date,
	claim_number,
	claim_rep_full_name,
	handling_office_mgr,
	source_sys_id
	FROM EXP_Post_LKP
),
RTR_SPLIT_SOURCE_EXCEED AS (SELECT * FROM RTR_SPLIT_SOURCE WHERE source_sys_id='EXCEED' OR source_sys_id='PMS'),
RTR_SPLIT_SOURCE_DCT AS (SELECT * FROM RTR_SPLIT_SOURCE WHERE source_sys_id='DCT'),
EXP_EXCEED_PMS AS (
	SELECT
	Submitted_DCN AS Submitted_DCN1,
	Submitted_Action_Type AS Submitted_Action_Type1,
	Injured_Party_HICN AS Injured_Party_HICN1,
	Submitted_Injured_Party_Last_Name AS Submitted_Injured_Party_Last_Name1,
	Submitted_Injured_Party_First_Name AS Submitted_Injured_Party_First_Name1,
	Submitted_Injured_Party_Middle_Initial AS Submitted_Injured_Party_Middle_Initial1,
	Submitted_Injured_Party_Gender AS Submitted_Injured_Party_Gender1,
	Submitted_Injured_Party_DOB AS Submitted_Injured_Party_DOB1,
	Submitted_Plan_TIN AS Submitted_Plan_TIN1,
	Submitted_Plan_Office_Code AS Submitted_Plan_Office_Code1,
	Submitted_Policy_Number AS Submitted_Policy_Number1,
	Submitted_Claim_Number AS Submitted_Claim_Number1,
	Reserved_For_Future_Use AS Reserved_For_Future_Use1,
	Applied_Injured_Party_HICN AS Applied_Injured_Party_HICN1,
	Reserved_For_Future_Use AS Reserved_For_Future_Use111,
	Applied_Injured_Party_Last_Name AS Applied_Injured_Party_Last_Name1,
	Applied_Injured_Party_First_Name AS Applied_Injured_Party_First_Name1,
	Applied_Injured_Party_Middle_Initial AS Applied_Injured_Party_Middle_Initial1,
	Applied_Injured_Party_Gender AS Applied_Injured_Party_Gender1,
	Applied_Injured_Party_DOB AS Applied_Injured_Party_DOB1,
	Applied_MSP_Effective_Date AS Applied_MSP_Effective_Date1,
	Applied_MSP_Termination_Date AS Applied_MSP_Termination_Date1,
	Applied_MSP_Type_Indicator AS Applied_MSP_Type_Indicator1,
	Reserved_For_Future_Use2 AS Reserved_For_Future_Use211,
	Applied_Disposition_Code AS Applied_Disposition_Code1,
	Applied_Error_Code AS Applied_Error_Code11,
	Applied_Error_Code2 AS Applied_Error_Code21,
	Applied_Error_Code3 AS Applied_Error_Code31,
	Applied_Error_Code4 AS Applied_Error_Code41,
	Applied_Error_Code5 AS Applied_Error_Code51,
	Applied_Error_Code6 AS Applied_Error_Code61,
	Applied_Error_Code7 AS Applied_Error_Code71,
	Applied_Error_Code8 AS Applied_Error_Code81,
	Applied_Error_Code9 AS Applied_Error_Code91,
	Applied_Error_Code10 AS Applied_Error_Code101,
	Applied_Compliance_Flag AS Applied_Compliance_Flag11,
	Applied_Compliance_Flag2 AS Applied_Compliance_Flag21,
	Applied_Compliance_Flag3 AS Applied_Compliance_Flag31,
	Applied_Compliance_Flag4 AS Applied_Compliance_Flag41,
	Applied_Compliance_Flag5 AS Applied_Compliance_Flag51,
	Applied_Compliance_Flag6 AS Applied_Compliance_Flag61,
	Applied_Compliance_Flag7 AS Applied_Compliance_Flag71,
	Applied_Compliance_Flag8 AS Applied_Compliance_Flag81,
	Applied_Compliance_Flag9 AS Applied_Compliance_Flag91,
	Applied_Compliance_Flag10 AS Applied_Compliance_Flag101,
	Reserved_For_Future_Use3 AS Reserved_For_Future_Use311,
	System_Date AS System_Date1
	FROM RTR_SPLIT_SOURCE_EXCEED
),
CMS_CLM_RESPONSE AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.CMS_CLM_RESPONSE
	(WBMI_RECEIVED_DT, SUBMITTED_DCN, SUBMITTED_ACT_TYPE, INJURED_PARTY_HICN, SUB_INJ_PRY_LST_NM, SUB_INJ_PRY_FST_NM, SUB_INJ_PR_MID_INT, SUB_INJ_PRY_GENDER, SUB_INJ_PRTY_DOB, SUB_PLAN_TIN, SUB_PLAN_OFF_CD, SUB_POLICY_NUM, SUB_CLAIM_NUM, APP_INJ_PRTY_HICN, APP_INJ_PRTY_LN, APP_INJ_PRTY_FN, APP_INJ_PRTY_MI, APP_INJ_PRTY_GNDR, APP_INJ_PRTY_DOB, APP_MSP_EFF_DATE, APP_MSP_TERM_DATE, APP_MSP_TYPE_IND, APP_DISPOSITION_CD, APP_ERROR_CODE_1, APP_ERROR_CODE_2, APP_ERROR_CODE_3, APP_ERROR_CODE_4, APP_ERROR_CODE_5, APP_ERROR_CODE_6, APP_ERROR_CODE_7, APP_ERROR_CODE_8, APP_ERROR_CODE_9, APP_ERROR_CODE_10, APP_COMPL_CODE_1, APP_COMPL_CODE_2, APP_COMPL_CODE_3, APP_COMPL_CODE_4, APP_COMPL_CODE_5, APP_COMPL_CODE_6, APP_COMPL_CODE_7, APP_COMPL_CODE_8, APP_COMPL_CODE_9, APP_COMPL_CODE_10)
	SELECT 
	System_Date1 AS WBMI_RECEIVED_DT, 
	Submitted_DCN1 AS SUBMITTED_DCN, 
	Submitted_Action_Type1 AS SUBMITTED_ACT_TYPE, 
	Injured_Party_HICN1 AS INJURED_PARTY_HICN, 
	Submitted_Injured_Party_Last_Name1 AS SUB_INJ_PRY_LST_NM, 
	Submitted_Injured_Party_First_Name1 AS SUB_INJ_PRY_FST_NM, 
	Submitted_Injured_Party_Middle_Initial1 AS SUB_INJ_PR_MID_INT, 
	Submitted_Injured_Party_Gender1 AS SUB_INJ_PRY_GENDER, 
	Submitted_Injured_Party_DOB1 AS SUB_INJ_PRTY_DOB, 
	Submitted_Plan_TIN1 AS SUB_PLAN_TIN, 
	Submitted_Plan_Office_Code1 AS SUB_PLAN_OFF_CD, 
	Submitted_Policy_Number1 AS SUB_POLICY_NUM, 
	Submitted_Claim_Number1 AS SUB_CLAIM_NUM, 
	Applied_Injured_Party_HICN1 AS APP_INJ_PRTY_HICN, 
	Applied_Injured_Party_Last_Name1 AS APP_INJ_PRTY_LN, 
	Applied_Injured_Party_First_Name1 AS APP_INJ_PRTY_FN, 
	Applied_Injured_Party_Middle_Initial1 AS APP_INJ_PRTY_MI, 
	Applied_Injured_Party_Gender1 AS APP_INJ_PRTY_GNDR, 
	Applied_Injured_Party_DOB1 AS APP_INJ_PRTY_DOB, 
	Applied_MSP_Effective_Date1 AS APP_MSP_EFF_DATE, 
	Applied_MSP_Termination_Date1 AS APP_MSP_TERM_DATE, 
	Applied_MSP_Type_Indicator1 AS APP_MSP_TYPE_IND, 
	Applied_Disposition_Code1 AS APP_DISPOSITION_CD, 
	Applied_Error_Code11 AS APP_ERROR_CODE_1, 
	Applied_Error_Code21 AS APP_ERROR_CODE_2, 
	Applied_Error_Code31 AS APP_ERROR_CODE_3, 
	Applied_Error_Code41 AS APP_ERROR_CODE_4, 
	Applied_Error_Code51 AS APP_ERROR_CODE_5, 
	Applied_Error_Code61 AS APP_ERROR_CODE_6, 
	Applied_Error_Code71 AS APP_ERROR_CODE_7, 
	Applied_Error_Code81 AS APP_ERROR_CODE_8, 
	Applied_Error_Code91 AS APP_ERROR_CODE_9, 
	Applied_Error_Code101 AS APP_ERROR_CODE_10, 
	Applied_Compliance_Flag11 AS APP_COMPL_CODE_1, 
	Applied_Compliance_Flag21 AS APP_COMPL_CODE_2, 
	Applied_Compliance_Flag31 AS APP_COMPL_CODE_3, 
	Applied_Compliance_Flag41 AS APP_COMPL_CODE_4, 
	Applied_Compliance_Flag51 AS APP_COMPL_CODE_5, 
	Applied_Compliance_Flag61 AS APP_COMPL_CODE_6, 
	Applied_Compliance_Flag71 AS APP_COMPL_CODE_7, 
	Applied_Compliance_Flag81 AS APP_COMPL_CODE_8, 
	Applied_Compliance_Flag91 AS APP_COMPL_CODE_9, 
	Applied_Compliance_Flag101 AS APP_COMPL_CODE_10
	FROM EXP_EXCEED_PMS
),
LKP_Claimant_name AS (
	SELECT
	claim_party_full_name,
	cms_document_cntl_num
	FROM (
		select CONVERT(varchar(15), P.cms_document_cntl_num) as cms_document_cntl_num,
		    cp.claim_party_full_name as claim_party_full_name
		from dbo.claim_medical_plan p
		join dbo.vw_claim_medical m on m.claim_med_ak_id = p.claim_med_ak_id and m.crrnt_snpsht_flag = 1
		join dbo.claim_party_occurrence cpo on cpo.claim_party_occurrence_ak_id = m.claim_party_occurrence_ak_id and cpo.crrnt_snpsht_flag = 1
		INNER JOIN dbo.vw_claim_party1 cp ON cp.claim_party_ak_id = cpo.claim_party_ak_id AND cp.crrnt_snpsht_flag = 1
		where p.crrnt_snpsht_flag = 1
		    and p.source_sys_id = 'DCT' --
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY cms_document_cntl_num ORDER BY claim_party_full_name) = 1
),
EXP_DCT AS (
	SELECT
	RTR_SPLIT_SOURCE_DCT.Submitted_DCN AS Submitted_DCN3,
	-- *INF*: TO_INTEGER(Submitted_DCN3)
	-- 
	CAST(Submitted_DCN3 AS INTEGER) AS out_Submitted_DCN3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Action_Type AS Submitted_Action_Type3,
	RTR_SPLIT_SOURCE_DCT.Injured_Party_HICN AS Injured_Party_HICN3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Injured_Party_Last_Name AS Submitted_Injured_Party_Last_Name3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Injured_Party_First_Name AS Submitted_Injured_Party_First_Name3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Injured_Party_Middle_Initial AS Submitted_Injured_Party_Middle_Initial3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Injured_Party_Gender AS Submitted_Injured_Party_Gender3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Injured_Party_DOB AS Submitted_Injured_Party_DOB3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Plan_TIN AS Submitted_Plan_TIN3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Plan_Office_Code AS Submitted_Plan_Office_Code3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Policy_Number AS Submitted_Policy_Number3,
	RTR_SPLIT_SOURCE_DCT.Submitted_Claim_Number AS Submitted_Claim_Number3,
	RTR_SPLIT_SOURCE_DCT.Reserved_For_Future_Use AS Reserved_For_Future_Use3,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_HICN AS Applied_Injured_Party_HICN3,
	RTR_SPLIT_SOURCE_DCT.Reserved_For_Future_Use11 AS Reserved_For_Future_Use113,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_Last_Name AS Applied_Injured_Party_Last_Name3,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_First_Name AS Applied_Injured_Party_First_Name3,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_Middle_Initial AS Applied_Injured_Party_Middle_Initial3,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_Gender AS Applied_Injured_Party_Gender3,
	RTR_SPLIT_SOURCE_DCT.Applied_Injured_Party_DOB AS Applied_Injured_Party_DOB3,
	RTR_SPLIT_SOURCE_DCT.Applied_MSP_Effective_Date AS Applied_MSP_Effective_Date3,
	RTR_SPLIT_SOURCE_DCT.Applied_MSP_Termination_Date AS Applied_MSP_Termination_Date3,
	RTR_SPLIT_SOURCE_DCT.Applied_MSP_Type_Indicator AS Applied_MSP_Type_Indicator3,
	RTR_SPLIT_SOURCE_DCT.Reserved_For_Future_Use21 AS Reserved_For_Future_Use213,
	RTR_SPLIT_SOURCE_DCT.Applied_Disposition_Code AS Applied_Disposition_Code3,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code1 AS Applied_Error_Code13,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code2 AS Applied_Error_Code23,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code AS Applied_Error_Code33,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code4 AS Applied_Error_Code43,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code5 AS Applied_Error_Code53,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code6 AS Applied_Error_Code63,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code7 AS Applied_Error_Code73,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code8 AS Applied_Error_Code83,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code9 AS Applied_Error_Code93,
	RTR_SPLIT_SOURCE_DCT.Applied_Error_Code10 AS Applied_Error_Code103,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag1 AS Applied_Compliance_Flag13,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag2 AS Applied_Compliance_Flag23,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag AS Applied_Compliance_Flag33,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag4 AS Applied_Compliance_Flag43,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag5 AS Applied_Compliance_Flag53,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag6 AS Applied_Compliance_Flag63,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag7 AS Applied_Compliance_Flag73,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag8 AS Applied_Compliance_Flag83,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag9 AS Applied_Compliance_Flag93,
	RTR_SPLIT_SOURCE_DCT.Applied_Compliance_Flag10 AS Applied_Compliance_Flag103,
	RTR_SPLIT_SOURCE_DCT.Reserved_For_Future_Use31 AS Reserved_For_Future_Use313,
	RTR_SPLIT_SOURCE_DCT.System_Date AS System_Date3,
	RTR_SPLIT_SOURCE_DCT.claim_number AS claim_number3,
	RTR_SPLIT_SOURCE_DCT.claim_rep_full_name AS claim_rep_full_name3,
	RTR_SPLIT_SOURCE_DCT.handling_office_mgr AS handling_office_mgr3,
	LKP_Claimant_name.claim_party_full_name AS ClaimantName,
	-- *INF*: :UDF.DEFAULT_VALUE_FOR_STRINGS(ClaimantName)
	UDF_DEFAULT_VALUE_FOR_STRINGS(ClaimantName) AS out_ClaimantName
	FROM RTR_SPLIT_SOURCE_DCT
	LEFT JOIN LKP_Claimant_name
	ON LKP_Claimant_name.cms_document_cntl_num = RTR_SPLIT_SOURCE.Submitted_DCN3
),
CmsClaimResponse AS (
	INSERT INTO CmsClaimResponse
	(WbmiReceivedDt, SubmittedDcn, SubmittedActionType, InjuredPartyHICN, SubInjuredPartyLastName, SubInjuredPartyFirstName, SubInjuredPartyMiddleInitial, SubInjuredPartyGender, SubInjuredPartyDob, SubPlanTin, SubPlanOfficeCd, SubPolicyNum, SubClaimNum, AppInjuredPartyHICN, AppInjuredPartyLastName, AppInjuredPartyFirstName, AppInjuredPartyMiddleInitial, AppInjuredPartyGender, AppInjuredPartyDob, AppMspEffDate, AppMspTermDate, AppMspTypeInd, AppDispositionCd, AppErrorCode1, AppErrorCode2, AppErrorCode3, AppErrorCode4, AppErrorCode5, AppErrorCode6, AppErrorCode7, AppErrorCode8, AppErrorCode9, AppErrorCode10, AppComplCode1, AppComplCode2, AppComplCode3, AppComplCode4, AppComplCode5, AppComplCode6, AppComplCode7, AppComplCode8, AppComplCode9, AppComplCode10, ClaimRepName, ClaimRepManagerName, ClaimNum, ClaimantName, WbmiPlanType)
	SELECT 
	System_Date3 AS WBMIRECEIVEDDT, 
	out_Submitted_DCN3 AS SUBMITTEDDCN, 
	Submitted_Action_Type3 AS SUBMITTEDACTIONTYPE, 
	Injured_Party_HICN3 AS INJUREDPARTYHICN, 
	Submitted_Injured_Party_Last_Name3 AS SUBINJUREDPARTYLASTNAME, 
	Submitted_Injured_Party_First_Name3 AS SUBINJUREDPARTYFIRSTNAME, 
	Submitted_Injured_Party_Middle_Initial3 AS SUBINJUREDPARTYMIDDLEINITIAL, 
	Submitted_Injured_Party_Gender3 AS SUBINJUREDPARTYGENDER, 
	Submitted_Injured_Party_DOB3 AS SUBINJUREDPARTYDOB, 
	Submitted_Plan_TIN3 AS SUBPLANTIN, 
	Submitted_Plan_Office_Code3 AS SUBPLANOFFICECD, 
	Submitted_Policy_Number3 AS SUBPOLICYNUM, 
	Submitted_Claim_Number3 AS SUBCLAIMNUM, 
	Applied_Injured_Party_HICN3 AS APPINJUREDPARTYHICN, 
	Applied_Injured_Party_Last_Name3 AS APPINJUREDPARTYLASTNAME, 
	Applied_Injured_Party_First_Name3 AS APPINJUREDPARTYFIRSTNAME, 
	Applied_Injured_Party_Middle_Initial3 AS APPINJUREDPARTYMIDDLEINITIAL, 
	Applied_Injured_Party_Gender3 AS APPINJUREDPARTYGENDER, 
	Applied_Injured_Party_DOB3 AS APPINJUREDPARTYDOB, 
	Applied_MSP_Effective_Date3 AS APPMSPEFFDATE, 
	Applied_MSP_Termination_Date3 AS APPMSPTERMDATE, 
	Applied_MSP_Type_Indicator3 AS APPMSPTYPEIND, 
	Applied_Disposition_Code3 AS APPDISPOSITIONCD, 
	Applied_Error_Code13 AS APPERRORCODE1, 
	Applied_Error_Code23 AS APPERRORCODE2, 
	Applied_Error_Code33 AS APPERRORCODE3, 
	Applied_Error_Code43 AS APPERRORCODE4, 
	Applied_Error_Code53 AS APPERRORCODE5, 
	Applied_Error_Code63 AS APPERRORCODE6, 
	Applied_Error_Code73 AS APPERRORCODE7, 
	Applied_Error_Code83 AS APPERRORCODE8, 
	Applied_Error_Code93 AS APPERRORCODE9, 
	Applied_Error_Code103 AS APPERRORCODE10, 
	Applied_Compliance_Flag13 AS APPCOMPLCODE1, 
	Applied_Compliance_Flag23 AS APPCOMPLCODE2, 
	Applied_Compliance_Flag33 AS APPCOMPLCODE3, 
	Applied_Compliance_Flag43 AS APPCOMPLCODE4, 
	Applied_Compliance_Flag53 AS APPCOMPLCODE5, 
	Applied_Compliance_Flag63 AS APPCOMPLCODE6, 
	Applied_Compliance_Flag73 AS APPCOMPLCODE7, 
	Applied_Compliance_Flag83 AS APPCOMPLCODE8, 
	Applied_Compliance_Flag93 AS APPCOMPLCODE9, 
	Applied_Compliance_Flag103 AS APPCOMPLCODE10, 
	claim_rep_full_name3 AS CLAIMREPNAME, 
	handling_office_mgr3 AS CLAIMREPMANAGERNAME, 
	claim_number3 AS CLAIMNUM, 
	out_ClaimantName AS CLAIMANTNAME, 
	Applied_MSP_Type_Indicator3 AS WBMIPLANTYPE
	FROM EXP_DCT
),