WITH
SQ_pms_adjuster_master_stage1 AS (
	SELECT
		adjuster_master_stage_id,
		adnm_adjustor_nbr,
		adnm_taxid_ssn,
		adnm_name,
		adnm_commnt1,
		adnm_address,
		adnm_commnt2,
		adnm_city_state,
		adnm_commnt3,
		adnm_police_charge,
		adnm_tax_indicator,
		adnm_zip_code,
		adnm_area_code,
		adnm_prefix,
		adnm_last_four,
		adnm_type_adjustor,
		adnm_adjustor_branch_number,
		adnm_adjustor_kind,
		adnm_fx_area_code,
		adnm_fx_prefix,
		adnm_fx_last_four,
		extract_date,
		as_of_date,
		record_count,
		source_system_id
	FROM pms_adjuster_master_stage
),
EXP_CLAIM_TAB_STAGE AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP,
	adjuster_master_stage_id,
	adnm_adjustor_nbr,
	adnm_taxid_ssn,
	adnm_name,
	adnm_commnt1,
	adnm_address,
	adnm_commnt2,
	adnm_city_state,
	adnm_commnt3,
	adnm_police_charge,
	adnm_tax_indicator,
	adnm_zip_code,
	adnm_area_code,
	adnm_prefix,
	adnm_last_four,
	adnm_type_adjustor,
	adnm_adjustor_branch_number,
	adnm_adjustor_kind,
	adnm_fx_area_code,
	adnm_fx_prefix,
	adnm_fx_last_four,
	extract_date,
	as_of_date,
	record_count,
	source_system_id
	FROM SQ_pms_adjuster_master_stage1
),
arch_pms_adjuster_master_stage AS (
	INSERT INTO arch_pms_adjuster_master_stage
	(adjuster_master_stage_id, adnm_adjustor_nbr, adnm_taxid_ssn, adnm_name, adnm_commnt1, adnm_address, adnm_commnt2, adnm_city_state, adnm_commnt3, adnm_police_charge, adnm_tax_indicator, adnm_zip_code, adnm_area_code, adnm_prefix, adnm_last_four, adnm_type_adjustor, adnm_adjustor_branch_number, adnm_adjustor_kind, adnm_fx_area_code, adnm_fx_prefix, adnm_fx_last_four, extract_date, as_of_date, record_count, source_system_id, audit_id)
	SELECT 
	ADJUSTER_MASTER_STAGE_ID, 
	ADNM_ADJUSTOR_NBR, 
	ADNM_TAXID_SSN, 
	ADNM_NAME, 
	ADNM_COMMNT1, 
	ADNM_ADDRESS, 
	ADNM_COMMNT2, 
	ADNM_CITY_STATE, 
	ADNM_COMMNT3, 
	ADNM_POLICE_CHARGE, 
	ADNM_TAX_INDICATOR, 
	ADNM_ZIP_CODE, 
	ADNM_AREA_CODE, 
	ADNM_PREFIX, 
	ADNM_LAST_FOUR, 
	ADNM_TYPE_ADJUSTOR, 
	ADNM_ADJUSTOR_BRANCH_NUMBER, 
	ADNM_ADJUSTOR_KIND, 
	ADNM_FX_AREA_CODE, 
	ADNM_FX_PREFIX, 
	ADNM_FX_LAST_FOUR, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLAIM_TAB_STAGE
),