WITH
SQ_CLIENT_ADDRESS_STAGE AS (
	SELECT CLIENT_ADDRESS_STAGE.CLIENT_ADDRESS_stage_ID, CLIENT_ADDRESS_STAGE.ADR_ID, CLIENT_ADDRESS_STAGE.ST_CD, CLIENT_ADDRESS_STAGE.CICA_PST_CD, CLIENT_ADDRESS_STAGE.CTR_CD, CLIENT_ADDRESS_STAGE.CICA_ADD_ADR_IND, CLIENT_ADDRESS_STAGE.USER_ID, CLIENT_ADDRESS_STAGE.STATUS_CD, CLIENT_ADDRESS_STAGE.TERMINAL_ID, CLIENT_ADDRESS_STAGE.CICA_EFF_ACY_TS, CLIENT_ADDRESS_STAGE.CICA_ADR_1, CLIENT_ADDRESS_STAGE.CICA_ADR_2, CLIENT_ADDRESS_STAGE.CICA_CIT_NM, CLIENT_ADDRESS_STAGE.CICA_CTY, CLIENT_ADDRESS_STAGE.EXTRACT_DATE, CLIENT_ADDRESS_STAGE.AS_OF_DATE, CLIENT_ADDRESS_STAGE.RECORD_COUNT, CLIENT_ADDRESS_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLIENT_ADDRESS_STAGE
	WHERE
	CLIENT_ADDRESS_STAGE.CICA_EFF_ACY_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLIENT_ADDRESS AS (
	SELECT
	CLIENT_ADDRESS_stage_ID,
	ADR_ID,
	ST_CD,
	CICA_PST_CD,
	CTR_CD,
	CICA_ADD_ADR_IND,
	USER_ID,
	STATUS_CD,
	TERMINAL_ID,
	CICA_EFF_ACY_TS,
	CICA_ADR_1,
	CICA_ADR_2,
	CICA_CIT_NM,
	CICA_CTY,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLIENT_ADDRESS_STAGE
),
arch_CLIENT_ADDRESS_STAGE AS (
	INSERT INTO arch_CLIENT_ADDRESS_STAGE
	(CLIENT_ADDRESS_stage_ID, ADR_ID, ST_CD, CICA_PST_CD, CTR_CD, CICA_ADD_ADR_IND, USER_ID, STATUS_CD, TERMINAL_ID, CICA_EFF_ACY_TS, CICA_ADR_1, CICA_ADR_2, CICA_CIT_NM, CICA_CTY, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, audit_id)
	SELECT 
	CLIENT_ADDRESS_STAGE_ID, 
	ADR_ID, 
	ST_CD, 
	CICA_PST_CD, 
	CTR_CD, 
	CICA_ADD_ADR_IND, 
	USER_ID, 
	STATUS_CD, 
	TERMINAL_ID, 
	CICA_EFF_ACY_TS, 
	CICA_ADR_1, 
	CICA_ADR_2, 
	CICA_CIT_NM, 
	CICA_CTY, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLIENT_ADDRESS
),