WITH
SQ_source AS (
	SELECT
		cms_pms_relation_stage_id,
		injured_party_id,
		cms_party_type,
		cms_relation_ind,
		is_individual,
		last_name,
		first_name,
		tin,
		address1,
		address2,
		city,
		state,
		zip_code,
		zip4,
		phone,
		phone_ext,
		created_ts,
		created_user_id,
		modified_ts,
		modified_user_id,
		extract_date,
		as_of_date,
		record_count,
		source_system_id
	FROM cms_pms_relation_stage
	WHERE CREATED_TS >= '@{pipeline().parameters.SELECTION_START_TS}'  OR MODIFIED_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_values AS (
	SELECT
	cms_pms_relation_stage_id,
	injured_party_id,
	cms_party_type,
	cms_relation_ind,
	is_individual,
	last_name,
	first_name,
	tin,
	address1,
	address2,
	city,
	state,
	zip_code,
	zip4,
	phone,
	phone_ext,
	created_ts,
	created_user_id,
	modified_ts,
	modified_user_id,
	extract_date,
	as_of_date,
	record_count,
	source_system_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID
	FROM SQ_source
),
arch_cms_pms_relation_stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.arch_cms_pms_relation_stage
	(cms_pms_relation_stage_id, injured_party_id, cms_party_type, cms_relation_ind, is_individual, last_name, first_name, tin, address1, address2, city, state, zip_code, zip4, phone, phone_ext, created_ts, created_user_id, modified_ts, modified_user_id, extract_date, as_of_date, record_count, source_system_id, audit_id)
	SELECT 
	CMS_PMS_RELATION_STAGE_ID, 
	INJURED_PARTY_ID, 
	CMS_PARTY_TYPE, 
	CMS_RELATION_IND, 
	IS_INDIVIDUAL, 
	LAST_NAME, 
	FIRST_NAME, 
	TIN, 
	ADDRESS1, 
	ADDRESS2, 
	CITY, 
	STATE, 
	ZIP_CODE, 
	ZIP4, 
	PHONE, 
	PHONE_EXT, 
	CREATED_TS, 
	CREATED_USER_ID, 
	MODIFIED_TS, 
	MODIFIED_USER_ID, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID AS AUDIT_ID
	FROM EXP_values
),