WITH
SQ_master_1099_list_stage AS (
	SELECT 
	master_1099_list_stage.master_1099_list_stage_id,
	master_1099_list_stage.tax_id, 
	master_1099_list_stage.reportable_ind, 
	master_1099_list_stage.tax_levy_ind, 
	master_1099_list_stage.irs_name, 
	master_1099_list_stage.address_line_1, 
	master_1099_list_stage.address_line_2, 
	master_1099_list_stage.city, 
	master_1099_list_stage.state_code, 
	master_1099_list_stage.zip_code, 
	master_1099_list_stage.country_code, 
	master_1099_list_stage.modified_ts,
	master_1099_list_stage.modified_user_id, 
	master_1099_list_stage.notes, 
	master_1099_list_stage.search_tax_id, 
	master_1099_list_stage.tax_id_type, 
	master_1099_list_stage.phone, 
	master_1099_list_stage.last_modified_dt, 
	master_1099_list_stage.irs_1099_type, 
	master_1099_list_stage.vendor_type_cd, 
	master_1099_list_stage.extract_date, 
	master_1099_list_stage.as_of_date, 
	master_1099_list_stage.record_count, 
	master_1099_list_stage.source_system_id,
	master_1099_list_stage.is_valid
	FROM
	@{pipeline().parameters.SOURCE_TABLE_OWNER}.master_1099_list_stage
),
EXP_Set_Metadata AS (
	SELECT
	master_1099_list_stage_id,
	tax_id,
	reportable_ind,
	tax_levy_ind,
	irs_name,
	address_line_1,
	address_line_2,
	city,
	state_code,
	zip_code,
	country_code,
	modified_ts,
	modified_user_id,
	notes,
	search_tax_id,
	tax_id_type,
	phone,
	last_modified_dt,
	irs_1099_type,
	vendor_type_cd,
	extract_date,
	as_of_date,
	record_count,
	source_system_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS out_audit_id,
	is_valid AS IsValidFlag
	FROM SQ_master_1099_list_stage
),
TGT_arch_master_1099_list_stage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.arch_master_1099_list_stage
	(master_1099_list_stage_id, tax_id, reportable_ind, tax_levy_ind, irs_name, address_line_1, address_line_2, city, state_code, zip_code, country_code, modified_ts, modified_user_id, notes, search_tax_id, tax_id_type, phone, last_modified_dt, irs_1099_type, vendor_type_cd, extract_date, as_of_date, record_count, source_system_id, audit_id, is_valid)
	SELECT 
	MASTER_1099_LIST_STAGE_ID, 
	TAX_ID, 
	REPORTABLE_IND, 
	TAX_LEVY_IND, 
	IRS_NAME, 
	ADDRESS_LINE_1, 
	ADDRESS_LINE_2, 
	CITY, 
	STATE_CODE, 
	ZIP_CODE, 
	COUNTRY_CODE, 
	MODIFIED_TS, 
	MODIFIED_USER_ID, 
	NOTES, 
	SEARCH_TAX_ID, 
	TAX_ID_TYPE, 
	PHONE, 
	LAST_MODIFIED_DT, 
	IRS_1099_TYPE, 
	VENDOR_TYPE_CD, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	out_audit_id AS AUDIT_ID, 
	IsValidFlag AS IS_VALID
	FROM EXP_Set_Metadata
),