WITH
SQ_CLAIM_COVERAGE_STAGE AS (
	SELECT
		claim_coverage_id AS CLAIM_COVERAGE_ID,
		cvr_claim_nbr AS CVR_CLAIM_NBR,
		cvr_cov_seq_nbr AS CVR_COV_SEQ_NBR,
		cvr_policy_key AS CVR_POLICY_KEY,
		cvr_policy_seq_nbr AS CVR_POLICY_SEQ_NBR,
		cvr_object_seq_nbr AS CVR_OBJECT_SEQ_NBR,
		cvr_object_type_cd AS CVR_OBJECT_TYPE_CD,
		cvr_policy_eff_dt AS CVR_POLICY_EFF_DT,
		cvr_polisy_exp_dt AS CVR_POLISY_EXP_DT,
		cvr_manual_ind AS CVR_MANUAL_IND,
		cvr_one_unit_ind AS CVR_ONE_UNIT_IND,
		cvr_create_ts AS CVR_CREATE_TS,
		cvr_entry_opr_id AS CVR_ENTRY_OPR_ID,
		cvr_pmsd_ts AS CVR_PMSD_TS,
		cvr_update_opr_id AS CVR_UPDATE_OPR_ID,
		cvr_upd_ts AS CVR_UPD_TS,
		cvr_pol_sys_cd AS CVR_POL_SYS_CD,
		cvr_pol_nbr AS CVR_POL_NBR,
		cvr_pol_branch_nbr AS CVR_POL_BRANCH_NBR,
		cvr_master_company AS CVR_MASTER_COMPANY,
		cvr_line_of_bus_cd AS CVR_LINE_OF_BUS_CD,
		cvr_bkr_ins_ref_cd AS CVR_BKR_INS_REF_CD,
		cvr_company_cd AS CVR_COMPANY_CD,
		cvr_permium_ind AS CVR_PERMIUM_IND,
		cvr_prm_ind_dt AS CVR_PRM_IND_DT,
		cvr_adjuster_nbr AS CVR_ADJUSTER_NBR,
		cvr_forms_ind AS CVR_FORMS_IND,
		cvr_prm_ind_adj_id AS CVR_PRM_IND_ADJ_ID,
		cvr_ins_line_cd AS CVR_INS_LINE_CD,
		cvr_rating_st_cd AS CVR_RATING_ST_CD,
		cvr_pri_rsk_st_cd AS CVR_PRI_RSK_ST_CD,
		cvr_pol_mod_nbr AS CVR_POL_MOD_NBR,
		cvr_insd_type_cd AS CVR_INSD_TYPE_CD,
		extract_date AS EXTRACT_DATE,
		as_of_date AS AS_OF_DATE,
		record_count AS RECORD_COUNT,
		source_system_id AS SOURCE_SYSTEM_ID,
		cvr_policy_src_id,
		cvr_agreement_div,
		cvr_policy_id
	FROM CLAIM_COVERAGE_STAGE
	WHERE CLAIM_COVERAGE_STAGE.CVR_CREATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	CLAIM_COVERAGE_STAGE.CVR_UPD_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLAIM_COVERAGE_STAGE AS (
	SELECT
	CLAIM_COVERAGE_ID,
	CVR_CLAIM_NBR,
	CVR_COV_SEQ_NBR,
	CVR_POLICY_KEY,
	CVR_POLICY_SEQ_NBR,
	CVR_OBJECT_SEQ_NBR,
	CVR_OBJECT_TYPE_CD,
	CVR_POLICY_EFF_DT,
	CVR_POLISY_EXP_DT,
	CVR_MANUAL_IND,
	CVR_ONE_UNIT_IND,
	CVR_CREATE_TS,
	CVR_ENTRY_OPR_ID,
	CVR_PMSD_TS,
	CVR_UPDATE_OPR_ID,
	CVR_UPD_TS,
	CVR_POL_SYS_CD,
	CVR_POL_NBR,
	CVR_POL_BRANCH_NBR,
	CVR_MASTER_COMPANY,
	CVR_LINE_OF_BUS_CD,
	CVR_BKR_INS_REF_CD,
	CVR_COMPANY_CD,
	CVR_PERMIUM_IND,
	CVR_PRM_IND_DT,
	CVR_ADJUSTER_NBR,
	CVR_FORMS_IND,
	CVR_PRM_IND_ADJ_ID,
	CVR_INS_LINE_CD,
	CVR_RATING_ST_CD,
	CVR_PRI_RSK_ST_CD,
	CVR_POL_MOD_NBR,
	CVR_INSD_TYPE_CD,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	cvr_policy_src_id,
	cvr_agreement_div,
	cvr_policy_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_COVERAGE_STAGE
),
ARCH_CLAIM_COVERAGE_STAGE AS (
	INSERT INTO ARCH_CLAIM_COVERAGE_STAGE
	(claim_coverage_id, cvr_claim_nbr, cvr_cov_seq_nbr, cvr_policy_key, cvr_policy_seq_nbr, cvr_object_seq_nbr, cvr_object_type_cd, cvr_policy_eff_dt, cvr_polisy_exp_dt, cvr_manual_ind, cvr_one_unit_ind, cvr_create_ts, cvr_entry_opr_id, cvr_pmsd_ts, cvr_update_opr_id, cvr_upd_ts, cvr_pol_sys_cd, cvr_pol_nbr, cvr_pol_branch_nbr, cvr_master_company, cvr_line_of_bus_cd, cvr_bkr_ins_ref_cd, cvr_company_cd, cvr_permium_ind, cvr_prm_ind_dt, cvr_adjuster_nbr, cvr_forms_ind, cvr_prm_ind_adj_id, cvr_ins_line_cd, cvr_rating_st_cd, cvr_pri_rsk_st_cd, cvr_pol_mod_nbr, cvr_insd_type_cd, extract_date, as_of_date, record_count, source_system_id, audit_id, cvr_policy_src_id, cvr_agreement_div, cvr_policy_id)
	SELECT 
	CLAIM_COVERAGE_ID AS CLAIM_COVERAGE_ID, 
	CVR_CLAIM_NBR AS CVR_CLAIM_NBR, 
	CVR_COV_SEQ_NBR AS CVR_COV_SEQ_NBR, 
	CVR_POLICY_KEY AS CVR_POLICY_KEY, 
	CVR_POLICY_SEQ_NBR AS CVR_POLICY_SEQ_NBR, 
	CVR_OBJECT_SEQ_NBR AS CVR_OBJECT_SEQ_NBR, 
	CVR_OBJECT_TYPE_CD AS CVR_OBJECT_TYPE_CD, 
	CVR_POLICY_EFF_DT AS CVR_POLICY_EFF_DT, 
	CVR_POLISY_EXP_DT AS CVR_POLISY_EXP_DT, 
	CVR_MANUAL_IND AS CVR_MANUAL_IND, 
	CVR_ONE_UNIT_IND AS CVR_ONE_UNIT_IND, 
	CVR_CREATE_TS AS CVR_CREATE_TS, 
	CVR_ENTRY_OPR_ID AS CVR_ENTRY_OPR_ID, 
	CVR_PMSD_TS AS CVR_PMSD_TS, 
	CVR_UPDATE_OPR_ID AS CVR_UPDATE_OPR_ID, 
	CVR_UPD_TS AS CVR_UPD_TS, 
	CVR_POL_SYS_CD AS CVR_POL_SYS_CD, 
	CVR_POL_NBR AS CVR_POL_NBR, 
	CVR_POL_BRANCH_NBR AS CVR_POL_BRANCH_NBR, 
	CVR_MASTER_COMPANY AS CVR_MASTER_COMPANY, 
	CVR_LINE_OF_BUS_CD AS CVR_LINE_OF_BUS_CD, 
	CVR_BKR_INS_REF_CD AS CVR_BKR_INS_REF_CD, 
	CVR_COMPANY_CD AS CVR_COMPANY_CD, 
	CVR_PERMIUM_IND AS CVR_PERMIUM_IND, 
	CVR_PRM_IND_DT AS CVR_PRM_IND_DT, 
	CVR_ADJUSTER_NBR AS CVR_ADJUSTER_NBR, 
	CVR_FORMS_IND AS CVR_FORMS_IND, 
	CVR_PRM_IND_ADJ_ID AS CVR_PRM_IND_ADJ_ID, 
	CVR_INS_LINE_CD AS CVR_INS_LINE_CD, 
	CVR_RATING_ST_CD AS CVR_RATING_ST_CD, 
	CVR_PRI_RSK_ST_CD AS CVR_PRI_RSK_ST_CD, 
	CVR_POL_MOD_NBR AS CVR_POL_MOD_NBR, 
	CVR_INSD_TYPE_CD AS CVR_INSD_TYPE_CD, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID, 
	CVR_POLICY_SRC_ID, 
	CVR_AGREEMENT_DIV, 
	CVR_POLICY_ID
	FROM EXP_CLAIM_COVERAGE_STAGE
),