WITH
SQ_CLAIM_OBJECT_CLT_STAGE1 AS (
	SELECT CLAIM_OBJECT_CLT_STAGE.CLAIM_OBJECT_CLT_ID, CLAIM_OBJECT_CLT_STAGE.CCT_CLAIM_NBR, CLAIM_OBJECT_CLT_STAGE.CCT_CLIENT_SEQ_NBR, CLAIM_OBJECT_CLT_STAGE.CCT_CLIENT_ID, CLAIM_OBJECT_CLT_STAGE.CCT_CLIENT_STA_CD, CLAIM_OBJECT_CLT_STAGE.CCT_CLIENT_ROLE_CD, CLAIM_OBJECT_CLT_STAGE.CCT_FIN_IND, CLAIM_OBJECT_CLT_STAGE.CCT_OBJECT_SEQ_NBR, CLAIM_OBJECT_CLT_STAGE.CCT_OBJECT_TYPE_CD, CLAIM_OBJECT_CLT_STAGE.CCT_ENTRY_OPR_ID, CLAIM_OBJECT_CLT_STAGE.CCT_UPDATE_OPR_ID, CLAIM_OBJECT_CLT_STAGE.CCT_CREATE_TS, CLAIM_OBJECT_CLT_STAGE.CCT_PMSD_TS, CLAIM_OBJECT_CLT_STAGE.CCT_UPD_TS, CLAIM_OBJECT_CLT_STAGE.CCT_ADR_SEQ_NBR, CLAIM_OBJECT_CLT_STAGE.EXTRACT_DATE, CLAIM_OBJECT_CLT_STAGE.AS_OF_DATE, CLAIM_OBJECT_CLT_STAGE.RECORD_COUNT, CLAIM_OBJECT_CLT_STAGE.SOURCE_SYSTEM_ID 
	FROM
	 CLAIM_OBJECT_CLT_STAGE
	WHERE
	CLAIM_OBJECT_CLT_STAGE.CCT_CREATE_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
	OR
	CLAIM_OBJECT_CLT_STAGE.CCT_UPD_TS >= '@{pipeline().parameters.SELECTION_START_TS}'
),
EXP_CLAIM_OBJECT_CLT_STAGE AS (
	SELECT
	CLAIM_OBJECT_CLT_ID,
	CCT_CLAIM_NBR,
	CCT_CLIENT_SEQ_NBR,
	CCT_CLIENT_ID,
	CCT_CLIENT_STA_CD,
	CCT_CLIENT_ROLE_CD,
	CCT_FIN_IND,
	CCT_OBJECT_SEQ_NBR,
	CCT_OBJECT_TYPE_CD,
	CCT_ENTRY_OPR_ID,
	CCT_UPDATE_OPR_ID,
	CCT_CREATE_TS,
	CCT_PMSD_TS,
	CCT_UPD_TS,
	CCT_ADR_SEQ_NBR,
	EXTRACT_DATE,
	AS_OF_DATE,
	RECORD_COUNT,
	SOURCE_SYSTEM_ID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP
	FROM SQ_CLAIM_OBJECT_CLT_STAGE1
),
ARCH_CLAIM_OBJECT_CLT_STAGE AS (
	INSERT INTO ARCH_CLAIM_OBJECT_CLT_STAGE
	(CLAIM_OBJECT_CLT_ID, CCT_CLAIM_NBR, CCT_CLIENT_SEQ_NBR, CCT_CLIENT_ID, CCT_CLIENT_STA_CD, CCT_CLIENT_ROLE_CD, CCT_FIN_IND, CCT_OBJECT_SEQ_NBR, CCT_OBJECT_TYPE_CD, CCT_ENTRY_OPR_ID, CCT_UPDATE_OPR_ID, CCT_CREATE_TS, CCT_PMSD_TS, CCT_UPD_TS, CCT_ADR_SEQ_NBR, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID, AUDIT_ID)
	SELECT 
	CLAIM_OBJECT_CLT_ID, 
	CCT_CLAIM_NBR, 
	CCT_CLIENT_SEQ_NBR, 
	CCT_CLIENT_ID, 
	CCT_CLIENT_STA_CD, 
	CCT_CLIENT_ROLE_CD, 
	CCT_FIN_IND, 
	CCT_OBJECT_SEQ_NBR, 
	CCT_OBJECT_TYPE_CD, 
	CCT_ENTRY_OPR_ID, 
	CCT_UPDATE_OPR_ID, 
	CCT_CREATE_TS, 
	CCT_PMSD_TS, 
	CCT_UPD_TS, 
	CCT_ADR_SEQ_NBR, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	AUDIT_ID_OP AS AUDIT_ID
	FROM EXP_CLAIM_OBJECT_CLT_STAGE
),