WITH
SQ_claims_survey_result_stage AS (
	SELECT
		claims_survey_result_stage_id,
		form_num,
		claim_rep_code,
		ques1_resp_val,
		ques2_resp_val,
		ques3_resp_val,
		ques4_resp_val,
		ques5_resp_val,
		ques6_resp_val,
		ques7_resp_val,
		ques8_resp_val,
		ques9_resp_val,
		ques10_resp_val,
		ques11_resp_val,
		ques12_resp_val,
		ques13_resp_val,
		ques14_resp_val,
		ques15_resp_val,
		ques16_resp_val,
		ques17_resp_val,
		ques18_resp_val,
		entry_date,
		claim_num,
		extract_date,
		source_system_id
	FROM claims_survey_result_stage
),
EXP_AUDIT_FIELDS AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AUDIT_ID_OP,
	claims_survey_result_stage_id,
	form_num,
	claim_rep_code,
	ques1_resp_val,
	ques2_resp_val,
	ques3_resp_val,
	ques4_resp_val,
	ques5_resp_val,
	ques6_resp_val,
	ques7_resp_val,
	ques8_resp_val,
	ques9_resp_val,
	ques10_resp_val,
	ques11_resp_val,
	ques12_resp_val,
	ques13_resp_val,
	ques14_resp_val,
	ques15_resp_val,
	ques16_resp_val,
	ques17_resp_val,
	ques18_resp_val,
	entry_date,
	claim_num,
	extract_date,
	source_system_id
	FROM SQ_claims_survey_result_stage
),
arch_claims_survey_result_stage AS (
	INSERT INTO arch_claims_survey_result_stage
	(claims_survey_result_stage_id, form_num, claim_rep_code, ques1_resp_val, ques2_resp_val, ques3_resp_val, ques4_resp_val, ques5_resp_val, ques6_resp_val, ques7_resp_val, ques8_resp_val, ques9_resp_val, ques10_resp_val, ques11_resp_val, ques12_resp_val, ques13_resp_val, ques14_resp_val, ques15_resp_val, ques16_resp_val, ques17_resp_val, ques18_resp_val, entry_date, claim_num, extract_date, source_system_id)
	SELECT 
	CLAIMS_SURVEY_RESULT_STAGE_ID, 
	FORM_NUM, 
	CLAIM_REP_CODE, 
	QUES1_RESP_VAL, 
	QUES2_RESP_VAL, 
	QUES3_RESP_VAL, 
	QUES4_RESP_VAL, 
	QUES5_RESP_VAL, 
	QUES6_RESP_VAL, 
	QUES7_RESP_VAL, 
	QUES8_RESP_VAL, 
	QUES9_RESP_VAL, 
	QUES10_RESP_VAL, 
	QUES11_RESP_VAL, 
	QUES12_RESP_VAL, 
	QUES13_RESP_VAL, 
	QUES14_RESP_VAL, 
	QUES15_RESP_VAL, 
	QUES16_RESP_VAL, 
	QUES17_RESP_VAL, 
	QUES18_RESP_VAL, 
	ENTRY_DATE, 
	CLAIM_NUM, 
	EXTRACT_DATE, 
	SOURCE_SYSTEM_ID
	FROM EXP_AUDIT_FIELDS
),