WITH
SQ_CLM_CASE_MANAGE_STAGE AS (
	SELECT
		clm_case_manage_stage_id,
		tch_claim_nbr,
		tch_client_id,
		case_name,
		case_number,
		suit_venue,
		suit_state,
		trial_date,
		policy_limit_id,
		case_desc_id,
		inj_dam_desc_id,
		pripst_inj_desc_id,
		subro_cont_id,
		first_not_law_suit,
		declaratory_act,
		suit_status,
		denial_date,
		prim_lit_handler,
		litigation_date,
		litigation_closed,
		create_ts,
		create_user_id,
		update_ts,
		update_user_id,
		liab_cmt_id,
		pros_cmt_id,
		cons_cmt_id,
		com_umb_res,
		how_clm_closed,
		payment_amt,
		reins_reported,
		extract_date,
		as_of_date,
		record_count,
		source_system_id,
		salvage_desc,
		subro_desc,
		iso_inj_dam_desc,
		demand_at_init_lit,
		object_type_cd,
		object_seq_nbr,
		cov_type_cd,
		cov_seq_nbr,
		bur_cause_loss,
		auto_pay_ind,
		legal_file_type,
		settlement_type_cd
	FROM CLM_CASE_MANAGE_STAGE
),
EXP_CLM_CASE_MANAGE_STAGE AS (
	SELECT
	clm_case_manage_stage_id,
	tch_claim_nbr,
	tch_client_id,
	case_name,
	case_number,
	suit_venue,
	suit_state,
	trial_date,
	policy_limit_id,
	case_desc_id,
	inj_dam_desc_id,
	pripst_inj_desc_id,
	subro_cont_id,
	first_not_law_suit,
	declaratory_act,
	suit_status,
	denial_date,
	prim_lit_handler,
	litigation_date,
	litigation_closed,
	create_ts,
	create_user_id,
	update_ts,
	update_user_id,
	liab_cmt_id,
	pros_cmt_id,
	cons_cmt_id,
	com_umb_res,
	how_clm_closed,
	payment_amt,
	reins_reported,
	extract_date,
	as_of_date,
	record_count,
	source_system_id,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS Audit_id_op,
	salvage_desc,
	subro_desc,
	iso_inj_dam_desc,
	demand_at_init_lit,
	object_type_cd,
	object_seq_nbr,
	cov_type_cd,
	cov_seq_nbr,
	bur_cause_loss,
	auto_pay_ind,
	legal_file_type,
	settlement_type_cd
	FROM SQ_CLM_CASE_MANAGE_STAGE
),
ARCH_CLM_CASE_MANAGE_STAGE AS (
	INSERT INTO arch_clm_case_manage_stage
	(clm_case_manage_stage_id, tch_claim_nbr, tch_client_id, case_name, case_number, suit_venue, suit_state, trial_date, policy_limit_id, case_desc_id, inj_dam_desc_id, pripst_inj_desc_id, subro_cont_id, first_not_law_suit, declaratory_act, suit_status, denial_date, prim_lit_handler, litigation_date, litigation_closed, create_ts, create_user_id, update_ts, update_user_id, liab_cmt_id, pros_cmt_id, cons_cmt_id, com_umb_res, how_clm_closed, payment_amt, reins_reported, extract_date, as_of_date, record_count, source_system_id, audit_id, salvage_desc, subro_desc, iso_inj_dam_desc, demand_at_init_lit, OBJECT_TYPE_CD, OBJECT_SEQ_NBR, COV_TYPE_CD, COV_SEQ_NBR, BUR_CAUSE_LOSS, AUTO_PAY_IND, LEGAL_FILE_TYPE, SETTLEMENT_TYPE_CD)
	SELECT 
	CLM_CASE_MANAGE_STAGE_ID, 
	TCH_CLAIM_NBR, 
	TCH_CLIENT_ID, 
	CASE_NAME, 
	CASE_NUMBER, 
	SUIT_VENUE, 
	SUIT_STATE, 
	TRIAL_DATE, 
	POLICY_LIMIT_ID, 
	CASE_DESC_ID, 
	INJ_DAM_DESC_ID, 
	PRIPST_INJ_DESC_ID, 
	SUBRO_CONT_ID, 
	FIRST_NOT_LAW_SUIT, 
	DECLARATORY_ACT, 
	SUIT_STATUS, 
	DENIAL_DATE, 
	PRIM_LIT_HANDLER, 
	LITIGATION_DATE, 
	LITIGATION_CLOSED, 
	CREATE_TS, 
	CREATE_USER_ID, 
	UPDATE_TS, 
	UPDATE_USER_ID, 
	LIAB_CMT_ID, 
	PROS_CMT_ID, 
	CONS_CMT_ID, 
	COM_UMB_RES, 
	HOW_CLM_CLOSED, 
	PAYMENT_AMT, 
	REINS_REPORTED, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT, 
	SOURCE_SYSTEM_ID, 
	Audit_id_op AS AUDIT_ID, 
	SALVAGE_DESC, 
	SUBRO_DESC, 
	ISO_INJ_DAM_DESC, 
	DEMAND_AT_INIT_LIT, 
	object_type_cd AS OBJECT_TYPE_CD, 
	object_seq_nbr AS OBJECT_SEQ_NBR, 
	cov_type_cd AS COV_TYPE_CD, 
	cov_seq_nbr AS COV_SEQ_NBR, 
	bur_cause_loss AS BUR_CAUSE_LOSS, 
	auto_pay_ind AS AUTO_PAY_IND, 
	legal_file_type AS LEGAL_FILE_TYPE, 
	settlement_type_cd AS SETTLEMENT_TYPE_CD
	FROM EXP_CLM_CASE_MANAGE_STAGE
),