WITH
SQ_Shortcut_to_WorkNcciMitchell AS (
	SELECT  WorkNcciMitchellID, CreatedDate, ModifiedDate, AuditID, WCClaimantDetailAKId, TransactionSetID, MaintenanceTypeCode, MaitenanceTypeCodeDate, JurisdictionStateCode, JurisdictionClaimNumber, InsurerFEIN, InsurerName, IsTPA, ClaimAdminAddress1, ClaimAdminAddress2, ClaimAdminCity, ClaimAdminStateCode, ClaimAdminPostalCode, ClaimAdminClaimNumber, EmployerFEIN, InsuredName, EmployerName, EmployerPhysicalAddress1, EmployerPhysicalAddress2, EmployerPhysicalCity, EmployerPhysicalStateCode, EmployerPhysicalPostalCode, IndustryCode, InsuredLocationIdentifier, PolicyNumberIdentifier, PolicyEffectiveDate, PolicyExpirationDate, DateOfInjury, TimeOfInjury, PostalCodeOfInjuryState, NatureOfInjuryCode, PartOfBodyInjuryCode, CauseOfInjuryCode, AccidentDescriptionCause, InitialTreatmentCode, DateReportedToEmployer, DateReportedToClaimAdmin, SocialSecurityNumber, EmployeeLastName, EmployeeFirstName, EmployeeMiddleInitial, EmployeeAddress1, EmployeeAddress2, EmployeeCity, EmployeeState, EmployeePostalCode, EmployeePhone, EmployeeDateOfBirth, GenderCode, MaritalStatusCode, NumberOfDependents, InitialDateDisabilityBegan, EmployeeDateOfDeath, EmploymentStatusCode, ClassCode, OccupationDescription, DateOfHire, Wage, WagePeriodCode, NumberOfDaysWorked, DateLastDayWorked, FullWagesPaidInd, DateOfReturnToWork, PreExistingDisability, DateOfMaxMedImprov, CurrentReturnToWorkDate, ClaimStatus, ClaimType, AgreeToCompensateCode, DateOfRepresentation, LateReasonCode, TestProductionInd, AccSiteCountyParish, AccSiteLocationNarrative, AccSiteOrganizationName, AccSiteCity, AccSiteStreet, AccSiteState, CalculatedWeeklyCompAmt, ClaimAdminMailInfoAttent, ClaimAdminMailingCountry, ClaimAdminClaimRepPhone, ClaimAdminClaimRepEmail, ClaimAdminClaimRepFax, ClaimAdminClaimRepName, CurrentDateDisBegan, CurrentDateLastDayWorked, DeathResultofInjuryCode, DiscFringeBenefits, EmpAuthReleaseMedInd, EmployeeEducationLevel, EmployeeEmploymentVisa, EmployeeGreenCard, EmployeeJurisdicationID, EmployeeMailingCountry, EmployeePassportNumber, EmpSSNReleaseInd, EmployeeTaxFilingStatus, EmployerContactBusPhone, EmployerContactName, EmployerContactEMail, EmployerContactFax, EmployerMailingInfo, EmployerPhysicalCountry, EmployerMailingCity, EmployerMailingCountry, EmployerMailingPostal, EmployerMailingAddress1, EmployerMailingAddress2, EmployerMailingState, EmployerTypeCode, EstGrossWeeklyAmtInd, InitMedProvName, InitMedProvPhysCity, InitMedProvPhysCountry, InitMedProvPhysPostal, InitMedProvPhysAddress1, InitMedProvPhysAddress2, InitMedProvPhysState, InsuredPostalCode, InsuredTypeCode, InsurerTypeCode, JurisdictionBranchOffice, ClaimAdministratorFEIN, ClaimAdministratorName, ReturnToWorkTypeCode, SuspensionEffectiveDate, FullDenialRescissionDate, FullDenialReasonNarrative, FullDenialEffectiveDate, ClaimAdminAlternatePostalCode, AnticipatedWageLossIndicator, EmployerPaidSalaryPriorToAcquisitionCode, WorkWeekTypeCode, WorkDaysScheduledCode, EmployeeSecurityID, EmployerNatureOfBusiness, NonConsecutivePeriod, EmpNumberEntitledExempt, EmpNumberWithholdingExempt, PIMinPaymentInd, PhysicalRestrictionsInd, SelfInsurerOrgTypeCode, SelfInsuranceLicCertNumber, AccidentPremisesCode, SelfInsurerAuthTypeCode, EmployeeLastNameSuffix, WageEffectiveDate, EmployeeIDTypeQualifier, EmployerPaidSalaryComp, AccidentSiteCountry, DateEmployerHadKnowledgeOfDisability, AverageWage, TypeOfLossCode, InsolventInsurerFEIN, PartialDenialCode, MaintenanceTypeCorrectionCode, MaintenanceTypeCorrectionCodeDate, InitialDateOfLostTime, DateClaimAdminKnewLostTime, AwardOrderDate, InsuredFEIN, EmployerUINumber, ICD9CMDiagnosisCode,
	FullDenialReasonCode, CancelReasonCode, CurrentReturnToWorkTypeCode, CurrentPhysicalRestrictionsInd, InitialReturnToWorkTypeCode, InitialPhysicalRestrictionsIndicator, 
	InitialReturnToWorkWithSameEmployerIndicator, 
	CurrentReturnToWorkWithSameEmployerIndicator, 
	PartOfBodyInjuredLocationCode, 
	PartOfBodyInjuredFingersToes, 
	VerIDReleaseNumber, 
	PartOfBodyInjuredLine, 
	FROICancelReasonNarrative, 
	InjurySeverityTypeCode,
	CurrentDateEmpKnowledgeofCurrentDateDisability, CurrentDateClaimAdminKnowledgeofCurrentDateDisability ,
	DateClaimAdminHadKnowledgeClaimMetReportingRequirements,EmployeeIndividualTaxpayerIdentificationNumber
	FROM WorkNcciMitchell 
	WHERE AuditID=@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} 
	ORDER BY ClaimAdminClaimNumber
),
SQ_WorkNcciMitchell_SSN AS (
	SELECT WorkNcciMitchell.WorkNcciMitchellID, WorkNcciMitchell.SocialSecurityNumber 
	FROM
	 WorkNcciMitchell
	 where WorkNcciMitchell.AuditID=@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} 
	@{pipeline().parameters.WHERE_CLAUSE}
),
mplt_Detokinize_WebService_call AS (WITH
	INPUT AS (
		
	),
	EXP_SSN_FEIN_TAXID AS (
		SELECT
		IN_id AS id,
		IN_ssn_fein_taxid AS ssn_fein_taxid,
		-- *INF*: LTRIM(RTRIM(ssn_fein_taxid))
		LTRIM(RTRIM(ssn_fein_taxid)) AS V_ssn_fein_taxid,
		-- *INF*: IIF(LENGTH(V_ssn_fein_taxid)=0  or IS_NUMBER(V_ssn_fein_taxid),'FEIN','NONFEIN')
		-- --IIF(LENGTH(V_ssn_fein_taxid)=11 AND REG_MATCH(V_ssn_fein_taxid,'[\da-zA-Z]+'),'NONFEIN','FEIN')
		-- 
		-- 
		IFF(
		    LENGTH(V_ssn_fein_taxid) = 0 or REGEXP_LIKE(V_ssn_fein_taxid, '^[0-9]+$'), 'FEIN', 'NONFEIN'
		) AS V_flag,
		V_flag AS flag,
		V_ssn_fein_taxid AS o_ssn_fein_taxid
		FROM INPUT
	),
	RTR_SSN_FEIN_TAXID AS (
		SELECT
		id,
		flag,
		o_ssn_fein_taxid AS ssn_fein_taxid,
		o_ssn_fein_taxid AS ssn_fein
		FROM EXP_SSN_FEIN_TAXID
	),
	RTR_SSN_FEIN_TAXID_FEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag = 'FEIN'),
	RTR_SSN_FEIN_TAXID_NONFEIN_VALUES AS (SELECT * FROM RTR_SSN_FEIN_TAXID WHERE flag='NONFEIN'),
	EXP_Values AS (
		SELECT
		id AS ID,
		'Detokenize' AS Function,
		'SSN' AS Scheme,
		ssn_fein_taxid AS SSN_FEIN_TAXID,
		'DATAFEED_JOBS' AS Requestedby,
		'Claims' AS Application,
		'DataFeeds' AS Caller,
		-- *INF*: 'https://intsvc.wbconnect.com/services/TokenService/Token.svc'
		-- 
		-- 
		-- 
		'https://intsvc.wbconnect.com/services/TokenService/Token.svc' AS URL,
		ssn_fein AS SSN_FEIN3
		FROM RTR_SSN_FEIN_TAXID_NONFEIN_VALUES
	),
	Token AS (-- Token
	
		##############################################
	
		# TODO: Place holder for Custom transformation
	
		##############################################
	),
	EXP_Response AS (
		SELECT
		REF_Id AS ID,
		tns_Data0 AS TokenResponse,
		REF_SSN_FEIN_TAXID,
		-- *INF*: ltrim(rtrim(REPLACECHR(0,TokenResponse,'-',NULL)))
		-- 
		ltrim(rtrim(REGEXP_REPLACE(TokenResponse,'-','','i'))) AS o_TokenResponse
		FROM Token
	),
	Union_SSN_FEIN_TAXID AS (
		SELECT id AS ID, ssn_fein_taxid AS TokenReponse, ssn_fein_taxid AS SSN_FEIN
		FROM RTR_SSN_FEIN_TAXID_FEIN_VALUES
		UNION
		SELECT ID, o_TokenResponse AS TokenReponse, REF_SSN_FEIN_TAXID AS SSN_FEIN
		FROM EXP_Response
	),
	OUTPUT AS (
		SELECT
		ID AS OUT_id, 
		TokenReponse AS OUT_TokenResponse, 
		SSN_FEIN AS OUT_IN_ssn_fein_taxid
		FROM Union_SSN_FEIN_TAXID
	),
),
JNR_WorkNcciMitchell AS (SELECT
	SQ_Shortcut_to_WorkNcciMitchell.WorkNcciMitchellID, 
	SQ_Shortcut_to_WorkNcciMitchell.CreatedDate, 
	SQ_Shortcut_to_WorkNcciMitchell.ModifiedDate, 
	SQ_Shortcut_to_WorkNcciMitchell.AuditID, 
	SQ_Shortcut_to_WorkNcciMitchell.WCClaimantDetailAKId, 
	SQ_Shortcut_to_WorkNcciMitchell.TransactionSetID, 
	SQ_Shortcut_to_WorkNcciMitchell.MaintenanceTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.MaitenanceTypeCodeDate, 
	SQ_Shortcut_to_WorkNcciMitchell.JurisdictionStateCode, 
	SQ_Shortcut_to_WorkNcciMitchell.JurisdictionClaimNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.InsurerFEIN, 
	SQ_Shortcut_to_WorkNcciMitchell.InsurerName, 
	SQ_Shortcut_to_WorkNcciMitchell.IsTPA, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminAddress1, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminAddress2, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminCity, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminStateCode, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminPostalCode, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminClaimNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerFEIN, 
	SQ_Shortcut_to_WorkNcciMitchell.InsuredName, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerName, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalAddress1, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalAddress2, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalCity, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalStateCode, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalPostalCode, 
	SQ_Shortcut_to_WorkNcciMitchell.IndustryCode, 
	SQ_Shortcut_to_WorkNcciMitchell.InsuredLocationIdentifier, 
	SQ_Shortcut_to_WorkNcciMitchell.PolicyNumberIdentifier, 
	SQ_Shortcut_to_WorkNcciMitchell.PolicyEffectiveDate, 
	SQ_Shortcut_to_WorkNcciMitchell.PolicyExpirationDate, 
	SQ_Shortcut_to_WorkNcciMitchell.DateOfInjury, 
	SQ_Shortcut_to_WorkNcciMitchell.TimeOfInjury, 
	SQ_Shortcut_to_WorkNcciMitchell.PostalCodeOfInjuryState, 
	SQ_Shortcut_to_WorkNcciMitchell.NatureOfInjuryCode, 
	SQ_Shortcut_to_WorkNcciMitchell.PartOfBodyInjuryCode, 
	SQ_Shortcut_to_WorkNcciMitchell.CauseOfInjuryCode, 
	SQ_Shortcut_to_WorkNcciMitchell.AccidentDescriptionCause, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialTreatmentCode, 
	SQ_Shortcut_to_WorkNcciMitchell.DateReportedToEmployer, 
	SQ_Shortcut_to_WorkNcciMitchell.DateReportedToClaimAdmin, 
	SQ_Shortcut_to_WorkNcciMitchell.SocialSecurityNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeLastName, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeFirstName, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeMiddleInitial, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeAddress1, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeAddress2, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeCity, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeState, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeePostalCode, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeePhone, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeDateOfBirth, 
	SQ_Shortcut_to_WorkNcciMitchell.GenderCode, 
	SQ_Shortcut_to_WorkNcciMitchell.MaritalStatusCode, 
	SQ_Shortcut_to_WorkNcciMitchell.NumberOfDependents, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialDateDisabilityBegan, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeDateOfDeath, 
	SQ_Shortcut_to_WorkNcciMitchell.EmploymentStatusCode, 
	SQ_Shortcut_to_WorkNcciMitchell.ClassCode, 
	SQ_Shortcut_to_WorkNcciMitchell.OccupationDescription, 
	SQ_Shortcut_to_WorkNcciMitchell.DateOfHire, 
	SQ_Shortcut_to_WorkNcciMitchell.Wage, 
	SQ_Shortcut_to_WorkNcciMitchell.WagePeriodCode, 
	SQ_Shortcut_to_WorkNcciMitchell.NumberOfDaysWorked, 
	SQ_Shortcut_to_WorkNcciMitchell.DateLastDayWorked, 
	SQ_Shortcut_to_WorkNcciMitchell.FullWagesPaidInd, 
	SQ_Shortcut_to_WorkNcciMitchell.DateOfReturnToWork, 
	SQ_Shortcut_to_WorkNcciMitchell.PreExistingDisability, 
	SQ_Shortcut_to_WorkNcciMitchell.DateOfMaxMedImprov, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentReturnToWorkDate, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimStatus, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimType, 
	SQ_Shortcut_to_WorkNcciMitchell.AgreeToCompensateCode, 
	SQ_Shortcut_to_WorkNcciMitchell.DateOfRepresentation, 
	SQ_Shortcut_to_WorkNcciMitchell.LateReasonCode, 
	SQ_Shortcut_to_WorkNcciMitchell.TestProductionInd, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteCountyParish, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteLocationNarrative, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteOrganizationName, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteCity, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteStreet, 
	SQ_Shortcut_to_WorkNcciMitchell.AccSiteState, 
	SQ_Shortcut_to_WorkNcciMitchell.CalculatedWeeklyCompAmt, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminMailInfoAttent, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminMailingCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminClaimRepPhone, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminClaimRepEmail, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminClaimRepFax, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminClaimRepName, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentDateDisBegan, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentDateLastDayWorked, 
	SQ_Shortcut_to_WorkNcciMitchell.DeathResultofInjuryCode, 
	SQ_Shortcut_to_WorkNcciMitchell.DiscFringeBenefits, 
	SQ_Shortcut_to_WorkNcciMitchell.EmpAuthReleaseMedInd, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeEducationLevel, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeEmploymentVisa, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeGreenCard, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeJurisdicationID, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeMailingCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeePassportNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.EmpSSNReleaseInd, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeTaxFilingStatus, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerContactBusPhone, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerContactName, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerContactEMail, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerContactFax, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingInfo, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPhysicalCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingCity, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingPostal, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingAddress1, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingAddress2, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerMailingState, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.EstGrossWeeklyAmtInd, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvName, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysCity, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysPostal, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysAddress1, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysAddress2, 
	SQ_Shortcut_to_WorkNcciMitchell.InitMedProvPhysState, 
	SQ_Shortcut_to_WorkNcciMitchell.InsuredPostalCode, 
	SQ_Shortcut_to_WorkNcciMitchell.InsuredTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.InsurerTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.JurisdictionBranchOffice, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdministratorFEIN, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdministratorName, 
	SQ_Shortcut_to_WorkNcciMitchell.ReturnToWorkTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.SuspensionEffectiveDate, 
	SQ_Shortcut_to_WorkNcciMitchell.FullDenialRescissionDate, 
	SQ_Shortcut_to_WorkNcciMitchell.FullDenialReasonNarrative, 
	SQ_Shortcut_to_WorkNcciMitchell.FullDenialEffectiveDate, 
	SQ_Shortcut_to_WorkNcciMitchell.ClaimAdminAlternatePostalCode, 
	SQ_Shortcut_to_WorkNcciMitchell.AnticipatedWageLossIndicator, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPaidSalaryPriorToAcquisitionCode, 
	SQ_Shortcut_to_WorkNcciMitchell.WorkWeekTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.WorkDaysScheduledCode, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeSecurityID, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerNatureOfBusiness, 
	SQ_Shortcut_to_WorkNcciMitchell.NonConsecutivePeriod, 
	SQ_Shortcut_to_WorkNcciMitchell.EmpNumberEntitledExempt, 
	SQ_Shortcut_to_WorkNcciMitchell.EmpNumberWithholdingExempt, 
	SQ_Shortcut_to_WorkNcciMitchell.PIMinPaymentInd, 
	SQ_Shortcut_to_WorkNcciMitchell.PhysicalRestrictionsInd, 
	SQ_Shortcut_to_WorkNcciMitchell.SelfInsurerOrgTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.SelfInsuranceLicCertNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.AccidentPremisesCode, 
	SQ_Shortcut_to_WorkNcciMitchell.SelfInsurerAuthTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeLastNameSuffix, 
	SQ_Shortcut_to_WorkNcciMitchell.WageEffectiveDate, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeIDTypeQualifier, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerPaidSalaryComp, 
	SQ_Shortcut_to_WorkNcciMitchell.AccidentSiteCountry, 
	SQ_Shortcut_to_WorkNcciMitchell.DateEmployerHadKnowledgeOfDisability, 
	SQ_Shortcut_to_WorkNcciMitchell.AverageWage, 
	SQ_Shortcut_to_WorkNcciMitchell.TypeOfLossCode, 
	SQ_Shortcut_to_WorkNcciMitchell.InsolventInsurerFEIN, 
	SQ_Shortcut_to_WorkNcciMitchell.PartialDenialCode, 
	SQ_Shortcut_to_WorkNcciMitchell.MaintenanceTypeCorrectionCode, 
	SQ_Shortcut_to_WorkNcciMitchell.MaintenanceTypeCorrectionCodeDate, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialDateOfLostTime, 
	SQ_Shortcut_to_WorkNcciMitchell.DateClaimAdminKnewLostTime, 
	SQ_Shortcut_to_WorkNcciMitchell.AwardOrderDate, 
	SQ_Shortcut_to_WorkNcciMitchell.InsuredFEIN, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployerUINumber, 
	SQ_Shortcut_to_WorkNcciMitchell.ICD9CMDiagnosisCode, 
	SQ_Shortcut_to_WorkNcciMitchell.FullDenialReasonCode, 
	SQ_Shortcut_to_WorkNcciMitchell.CancelReasonCode, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentReturnToWorkTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentPhysicalRestrictionsInd, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialReturnToWorkTypeCode, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialPhysicalRestrictionsIndicator, 
	SQ_Shortcut_to_WorkNcciMitchell.InitialReturnToWorkWithSameEmployerIndicator, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentReturnToWorkWithSameEmployerIndicator, 
	SQ_Shortcut_to_WorkNcciMitchell.VerIDReleaseNumber, 
	SQ_Shortcut_to_WorkNcciMitchell.FROICancelReasonNarrative, 
	SQ_Shortcut_to_WorkNcciMitchell.InjurySeverityTypeCode, 
	mplt_Detokinize_WebService_call.OUT_id AS IN_mplt_id, 
	mplt_Detokinize_WebService_call.OUT_TokenResponse AS TokenResponse, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentDateEmpKnowledgeofCurrentDateDisability, 
	SQ_Shortcut_to_WorkNcciMitchell.CurrentDateClaimAdminKnowledgeofCurrentDateDisability, 
	SQ_Shortcut_to_WorkNcciMitchell.DateClaimAdminHadKnowledgeClaimMetReportingRequirements, 
	SQ_Shortcut_to_WorkNcciMitchell.EmployeeIndividualTaxpayerIdentificationNumber
	FROM SQ_Shortcut_to_WorkNcciMitchell
	INNER JOIN mplt_Detokinize_WebService_call
	ON mplt_Detokinize_WebService_call.OUT_id = SQ_Shortcut_to_WorkNcciMitchell.WorkNcciMitchellID
),
EXPTRANS AS (
	SELECT
	1 AS XPK_VALUE,
	'X' AS RELEASE,
	'IAIABC' AS VERSION,
	'ALL' AS REPORT,
	'HD1' AS TransSetID_HD1,
	'390698170' AS SenderIDFEIN,
	'' AS SenderIDFiller,
	'530959791' AS SenderIDPostalCode,
	'' AS ReceiverIDFEIN,
	'' AS ReceiverIDFiller,
	'' AS ReceiverIDPostalCode,
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS DateTransmissionSent,
	-- *INF*: LPAD(GET_DATE_PART(SYSDATE,'HH24'),2,'0')||LPAD(GET_DATE_PART(SYSDATE,'MM'),2,'0')||LPAD(GET_DATE_PART(SYSDATE,'SS'),2,'0')
	LPAD(DATE_PART(CURRENT_TIMESTAMP, 'HH24'), 2, '0') || LPAD(DATE_PART(CURRENT_TIMESTAMP, 'MM'), 2, '0') || LPAD(DATE_PART(CURRENT_TIMESTAMP, 'SS'), 2, '0') AS TimeTransmissionSent,
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS OriginalTransmissionDate,
	-- *INF*: LPAD(GET_DATE_PART(SYSDATE,'HH24'),2,'0')||LPAD(GET_DATE_PART(SYSDATE,'MM'),2,'0')||LPAD(GET_DATE_PART(SYSDATE,'SS'),2,'0')
	LPAD(DATE_PART(CURRENT_TIMESTAMP, 'HH24'), 2, '0') || LPAD(DATE_PART(CURRENT_TIMESTAMP, 'MM'), 2, '0') || LPAD(DATE_PART(CURRENT_TIMESTAMP, 'SS'), 2, '0') AS OriginalTransmissionTime,
	@{pipeline().parameters.TEST_PRODUCTION_INDICATOR} AS TestProductionInd_H,
	-- *INF*: DECODE(TRUE,
	-- IN(LTRIM(RTRIM(JurisdictionStateCode)),'MN','IN','KS','IA','TN','KY','NE','NC','VA'),'148',
	-- '' )
	DECODE(
	    TRUE,
	    LTRIM(RTRIM(JurisdictionStateCode)) IN ('MN','IN','KS','IA','TN','KY','NE','NC','VA'), '148',
	    ''
	) AS VerIDTransmissionTypeCode,
	VerIDReleaseNumber,
	WorkNcciMitchellID,
	CreatedDate,
	ModifiedDate,
	AuditID,
	WCClaimantDetailAKId,
	TransactionSetID,
	MaintenanceTypeCode,
	MaitenanceTypeCodeDate,
	JurisdictionStateCode,
	JurisdictionClaimNumber,
	InsurerFEIN,
	InsurerName,
	IsTPA,
	ClaimAdminAddress1,
	ClaimAdminAddress2,
	ClaimAdminCity,
	ClaimAdminStateCode,
	ClaimAdminPostalCode,
	ClaimAdminClaimNumber,
	EmployerFEIN,
	InsuredName,
	EmployerName,
	EmployerPhysicalAddress1,
	EmployerPhysicalAddress2,
	EmployerPhysicalCity,
	EmployerPhysicalStateCode,
	EmployerPhysicalPostalCode,
	IndustryCode,
	InsuredLocationIdentifier,
	PolicyNumberIdentifier,
	PolicyEffectiveDate,
	PolicyExpirationDate,
	DateOfInjury,
	TimeOfInjury,
	PostalCodeOfInjuryState,
	NatureOfInjuryCode,
	PartOfBodyInjuryCode,
	CauseOfInjuryCode,
	AccidentDescriptionCause,
	InitialTreatmentCode,
	DateReportedToEmployer,
	DateReportedToClaimAdmin,
	TokenResponse AS IN_SocialSecurityNumber,
	-- *INF*: IIF(((SUBSTR(IN_SocialSecurityNumber,4,1)='-')  AND  (LENGTH(IN_SocialSecurityNumber) = 11 )), REPLACECHR(0,LTRIM(RTRIM(IN_SocialSecurityNumber)),'-',''),IN_SocialSecurityNumber)
	IFF(
	    ((SUBSTR(IN_SocialSecurityNumber, 4, 1) = '-') AND (LENGTH(IN_SocialSecurityNumber) = 11)),
	    REGEXP_REPLACE(LTRIM(RTRIM(IN_SocialSecurityNumber)),'-','','i'),
	    IN_SocialSecurityNumber
	) AS VAR_SocialSecurityNumber,
	VAR_SocialSecurityNumber AS OUT_SocialSecurityNumber,
	EmployeeLastName,
	EmployeeFirstName,
	EmployeeMiddleInitial,
	EmployeeAddress1,
	EmployeeAddress2,
	EmployeeCity,
	EmployeeState,
	EmployeePostalCode,
	EmployeePhone,
	EmployeeDateOfBirth,
	GenderCode,
	MaritalStatusCode,
	NumberOfDependents,
	InitialDateDisabilityBegan,
	EmployeeDateOfDeath,
	EmploymentStatusCode,
	ClassCode,
	OccupationDescription,
	DateOfHire,
	Wage,
	WagePeriodCode,
	NumberOfDaysWorked,
	DateLastDayWorked,
	FullWagesPaidInd,
	DateOfReturnToWork,
	PreExistingDisability,
	DateOfMaxMedImprov,
	CurrentReturnToWorkDate,
	ClaimStatus,
	ClaimType,
	AgreeToCompensateCode,
	DateOfRepresentation,
	LateReasonCode,
	TestProductionInd,
	AccSiteCountyParish,
	AccSiteLocationNarrative,
	AccSiteOrganizationName,
	AccSiteCity,
	AccSiteStreet,
	AccSiteState,
	CalculatedWeeklyCompAmt,
	ClaimAdminMailInfoAttent,
	ClaimAdminMailingCountry,
	ClaimAdminClaimRepPhone,
	ClaimAdminClaimRepEmail,
	ClaimAdminClaimRepFax,
	ClaimAdminClaimRepName,
	CurrentDateDisBegan,
	CurrentDateLastDayWorked,
	DeathResultofInjuryCode,
	DiscFringeBenefits,
	EmpAuthReleaseMedInd,
	EmployeeEducationLevel,
	EmployeeEmploymentVisa,
	EmployeeGreenCard,
	EmployeeJurisdicationID,
	EmployeeMailingCountry,
	EmployeePassportNumber,
	EmpSSNReleaseInd,
	EmployeeTaxFilingStatus,
	EmployerContactBusPhone,
	EmployerContactName,
	EmployerContactEMail,
	EmployerContactFax,
	EmployerMailingInfo,
	EmployerPhysicalCountry,
	EmployerMailingCity,
	EmployerMailingCountry,
	EmployerMailingPostal,
	EmployerMailingAddress1,
	EmployerMailingAddress2,
	EmployerMailingState,
	EmployerTypeCode,
	EstGrossWeeklyAmtInd,
	InitMedProvName,
	InitMedProvPhysCity,
	InitMedProvPhysCountry,
	InitMedProvPhysPostal,
	InitMedProvPhysAddress1,
	InitMedProvPhysAddress2,
	InitMedProvPhysState,
	InsuredPostalCode,
	InsuredTypeCode,
	InsurerTypeCode,
	JurisdictionBranchOffice,
	ClaimAdministratorFEIN,
	ClaimAdministratorName,
	ReturnToWorkTypeCode,
	SuspensionEffectiveDate,
	FullDenialRescissionDate,
	FullDenialReasonNarrative,
	FullDenialEffectiveDate,
	ClaimAdminAlternatePostalCode,
	AnticipatedWageLossIndicator,
	EmployerPaidSalaryPriorToAcquisitionCode,
	WorkWeekTypeCode,
	WorkDaysScheduledCode,
	EmployeeSecurityID,
	EmployerNatureOfBusiness,
	NonConsecutivePeriod,
	EmpNumberEntitledExempt,
	EmpNumberWithholdingExempt,
	PIMinPaymentInd,
	PhysicalRestrictionsInd,
	SelfInsurerOrgTypeCode,
	SelfInsuranceLicCertNumber,
	AccidentPremisesCode,
	SelfInsurerAuthTypeCode,
	EmployeeLastNameSuffix,
	WageEffectiveDate,
	EmployeeIDTypeQualifier,
	EmployerPaidSalaryComp,
	AccidentSiteCountry,
	DateEmployerHadKnowledgeOfDisability,
	AverageWage,
	TypeOfLossCode,
	InsolventInsurerFEIN,
	PartialDenialCode,
	MaintenanceTypeCorrectionCode,
	MaintenanceTypeCorrectionCodeDate,
	InitialDateOfLostTime,
	DateClaimAdminKnewLostTime,
	AwardOrderDate,
	InsuredFEIN,
	EmployerUINumber,
	ICD9CMDiagnosisCode,
	CancelReasonCode,
	CurrentReturnToWorkTypeCode,
	CurrentPhysicalRestrictionsInd,
	InitialReturnToWorkTypeCode,
	InitialPhysicalRestrictionsIndicator,
	InitialReturnToWorkWithSameEmployerIndicator AS i_InitialReturnToWorkWithSameEmployerIndicator,
	-- *INF*: i_InitialReturnToWorkWithSameEmployerIndicator
	-- 
	-- 
	-- --DECODE(TRUE,
	-- --	IN-----(JurisdictionStateCode,'NC'),i_InitialReturnToWorkWithSameEmployerIndicator,NULL)
	i_InitialReturnToWorkWithSameEmployerIndicator AS o_InitialReturnToWorkWithSameEmployerIndicator,
	-- *INF*: DECODE(TRUE,
	-- 	IN(LTRIM(RTRIM(JurisdictionStateCode)),'NC'),
	-- 		i_InitialReturnToWorkWithSameEmployerIndicator,
	-- 	NULL)
	DECODE(
	    TRUE,
	    LTRIM(RTRIM(JurisdictionStateCode)) IN ('NC'), i_InitialReturnToWorkWithSameEmployerIndicator,
	    NULL
	) AS o_RTWSameEmpInd,
	CurrentReturnToWorkWithSameEmployerIndicator,
	FROICancelReasonNarrative,
	InjurySeverityTypeCode,
	CurrentDateEmpKnowledgeofCurrentDateDisability,
	CurrentDateClaimAdminKnowledgeofCurrentDateDisability,
	DateClaimAdminHadKnowledgeClaimMetReportingRequirements,
	EmployeeIndividualTaxpayerIdentificationNumber
	FROM JNR_WorkNcciMitchell
),
AGGTRANS AS (
	SELECT
	XPK_VALUE
	FROM EXPTRANS
	QUALIFY ROW_NUMBER() OVER (PARTITION BY XPK_VALUE ORDER BY NULL) = 1
),
EXP_DenialReasonCode AS (
	SELECT
	JurisdictionStateCode,
	WCClaimantDetailAKId,
	'denialreasoncode' AS LiID,
	-- *INF*: TO_CHAR(WCClaimantDetailAKId)||'3'
	TO_CHAR(WCClaimantDetailAKId) || '3' AS v_XPK_LI,
	v_XPK_LI AS o_XPK_wcn_LineItems,
	FullDenialReasonCode,
	-- *INF*: DECODE(TRUE,
	-- 	IN(LTRIM(RTRIM(JurisdictionStateCode)),'KS','IA','IN','KY','NE','IL','VA'),
	-- 		LTRIM(RTRIM(FullDenialReasonCode)),
	-- 	NULL)
	DECODE(
	    TRUE,
	    LTRIM(RTRIM(JurisdictionStateCode)) IN ('KS','IA','IN','KY','NE','IL','VA'), LTRIM(RTRIM(FullDenialReasonCode)),
	    NULL
	) AS o_FullDenialReasonCode
	FROM SQ_Shortcut_to_WorkNcciMitchell
),
EXP_MCO AS (
	SELECT
	JurisdictionStateCode,
	'' AS MCOCode,
	'' AS MCOIDNumber,
	'' AS MCOName,
	'MCO' AS LiID,
	WCClaimantDetailAKId,
	-- *INF*: TO_CHAR(WCClaimantDetailAKId)||'2'
	TO_CHAR(WCClaimantDetailAKId) || '2' AS v_XPK_LI,
	v_XPK_LI AS o_XPK_wcn_LineItems
	FROM SQ_Shortcut_to_WorkNcciMitchell
),
SQ_Shortcut_to_WorkNcciMitchellWitness AS (
	SELECT a.WCClaimantDetailAKId
	,a.WitnessFullName
	,a.WitnessBusinessPhone1 
	,b.JurisdictionStateCode
	FROM
	WorkNcciMitchellWitness a 
	inner join WorkNcciMitchell b ON
	a.WCClaimantDetailAKId = b.WCClaimantDetailAKId and a.AuditID=b.AuditID
	where a.AuditID=@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
),
EXP_Witness AS (
	SELECT
	-- *INF*: TO_CHAR(WCClaimantDetailAKId) || '1'
	-- 
	-- 
	TO_CHAR(WCClaimantDetailAKId) || '1' AS v_XPK_LI,
	v_XPK_LI AS o_XPK_wcn_LineItems,
	WCClaimantDetailAKId,
	WitnessFullName,
	WitnessBusinessPhone1,
	JurisdictionStateCode,
	'witness' AS LiID
	FROM SQ_Shortcut_to_WorkNcciMitchellWitness
),
EXP_partofbody AS (
	SELECT
	WCClaimantDetailAKId,
	-- *INF*: TO_CHAR(WCClaimantDetailAKId)||'4'
	TO_CHAR(WCClaimantDetailAKId) || '4' AS v_XPK_LI,
	v_XPK_LI AS o_XPK_wcn_LineItems,
	'partofbody' AS LiID,
	PartOfBodyInjuredLocationCode,
	PartOfBodyInjuredFingersToes,
	PartOfBodyInjuredLine
	FROM SQ_Shortcut_to_WorkNcciMitchell
),
Union AS (
	SELECT o_XPK_wcn_LineItems, WCClaimantDetailAKId, WitnessFullName, WitnessBusinessPhone1, JurisdictionStateCode, LiID
	FROM EXP_Witness
	UNION
	SELECT o_XPK_wcn_LineItems, WCClaimantDetailAKId, LiID, MCOCode, MCOIDNumber, MCOName
	FROM EXP_MCO
	UNION
	SELECT o_XPK_wcn_LineItems, WCClaimantDetailAKId, JurisdictionStateCode, LiID, o_FullDenialReasonCode AS FullDenialReasonCode
	FROM EXP_DenialReasonCode
	UNION
	SELECT o_XPK_wcn_LineItems, WCClaimantDetailAKId, LiID, PartOfBodyInjuredLocationCode, PartOfBodyInjuredFingersToes, PartOfBodyInjuredLine
	FROM EXP_partofbody
),
EXP_Union AS (
	SELECT
	o_XPK_wcn_LineItems AS XPK_wcn_LineItems,
	-- *INF*: TO_INTEGER(XPK_wcn_LineItems)
	CAST(XPK_wcn_LineItems AS INTEGER) AS o_XPK_wcn_LineItems,
	-- *INF*: LENGTH(XPK_wcn_LineItems)
	LENGTH(XPK_wcn_LineItems) AS Length_WCCD_ID,
	-- *INF*: SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)),Length_WCCD_ID)
	-- 
	-- --SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)),8)
	SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)), Length_WCCD_ID) AS v_ChildType,
	v_PK+1 AS v_PK,
	v_PK AS PK,
	-- *INF*: --DECODE(TRUE,
	-- --SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)),8)--='1','WITNESS',
	-- --SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)),8)--='2','PAYMENT',
	-- --'')
	-- DECODE(TRUE,
	-- LTRIM(RTRIM(v_ChildType))='1','WITNESS',
	-- LTRIM(RTRIM(v_ChildType))='2','MCO' ,
	-- LTRIM(RTRIM(v_ChildType))='3','denialreasoncode' )
	DECODE(
	    TRUE,
	    LTRIM(RTRIM(v_ChildType)) = '1', 'WITNESS',
	    LTRIM(RTRIM(v_ChildType)) = '2', 'MCO',
	    LTRIM(RTRIM(v_ChildType)) = '3', 'denialreasoncode'
	) AS v_liid,
	v_liid AS o_liid,
	WCClaimantDetailAKId,
	WitnessFullName,
	WitnessBusinessPhone1,
	JurisdictionStateCode,
	-- *INF*: --DECODE(TRUE,
	-- --LTRIM(RTRIM(JurisdictionStateCode))='MN',
	-- --DECODE(SUBSTR(ltrim(rtrim(XPK_wcn_LineItems)),8),
	-- --'1',3,
	-- --'2',5)-- , NULL)
	-- 
	-- DECODE(LTRIM(RTRIM(v_ChildType)),
	-- '1',5,
	-- '2',2 ,
	-- '3',5,
	-- '4',10)
	DECODE(
	    LTRIM(RTRIM(v_ChildType)),
	    '1', 5,
	    '2', 2,
	    '3', 5,
	    '4', 10
	) AS v_MaxCount,
	v_MaxCount AS MaxCount,
	LiID,
	MCOCode,
	MCOIDNumber,
	MCOName,
	FullDenialReasonCode,
	PartOfBodyInjuredLocationCode,
	PartOfBodyInjuredFingersToes,
	PartOfBodyInjuredLine
	FROM Union
),
AGG_LineItems AS (
	SELECT
	o_XPK_wcn_LineItems AS XPK_wcn_LineItems,
	WCClaimantDetailAKId,
	MaxCount,
	LiID AS liid
	FROM EXP_Union
	QUALIFY ROW_NUMBER() OVER (PARTITION BY XPK_wcn_LineItems ORDER BY NULL) = 1
),
AGG_WorkMitchell AS (
	SELECT
	WorkNcciMitchellID,
	XPK_VALUE,
	RELEASE,
	VERSION,
	REPORT,
	TransSetID_HD1,
	SenderIDFEIN,
	SenderIDFiller,
	SenderIDPostalCode,
	ReceiverIDFEIN,
	ReceiverIDFiller,
	ReceiverIDPostalCode,
	DateTransmissionSent,
	TimeTransmissionSent,
	OriginalTransmissionDate,
	OriginalTransmissionTime,
	TestProductionInd_H,
	VerIDTransmissionTypeCode,
	VerIDReleaseNumber,
	CreatedDate,
	ModifiedDate,
	AuditID,
	WCClaimantDetailAKId,
	TransactionSetID,
	MaintenanceTypeCode,
	MaitenanceTypeCodeDate,
	JurisdictionStateCode,
	JurisdictionClaimNumber,
	InsurerFEIN,
	InsurerName,
	IsTPA,
	ClaimAdminAddress1,
	ClaimAdminAddress2,
	ClaimAdminCity,
	ClaimAdminStateCode,
	ClaimAdminPostalCode,
	ClaimAdminClaimNumber,
	EmployerFEIN,
	InsuredName,
	EmployerName,
	EmployerPhysicalAddress1,
	EmployerPhysicalAddress2,
	EmployerPhysicalCity,
	EmployerPhysicalStateCode,
	EmployerPhysicalPostalCode,
	IndustryCode,
	InsuredLocationIdentifier,
	PolicyNumberIdentifier,
	PolicyEffectiveDate,
	PolicyExpirationDate,
	DateOfInjury,
	TimeOfInjury,
	PostalCodeOfInjuryState,
	NatureOfInjuryCode,
	PartOfBodyInjuryCode,
	CauseOfInjuryCode,
	AccidentDescriptionCause,
	InitialTreatmentCode,
	DateReportedToEmployer,
	DateReportedToClaimAdmin,
	OUT_SocialSecurityNumber AS SocialSecurityNumber,
	EmployeeLastName,
	EmployeeFirstName,
	EmployeeMiddleInitial,
	EmployeeAddress1,
	EmployeeAddress2,
	EmployeeCity,
	EmployeeState,
	EmployeePostalCode,
	EmployeePhone,
	EmployeeDateOfBirth,
	GenderCode,
	MaritalStatusCode,
	NumberOfDependents,
	InitialDateDisabilityBegan,
	EmployeeDateOfDeath,
	EmploymentStatusCode,
	ClassCode,
	OccupationDescription,
	DateOfHire,
	Wage,
	WagePeriodCode,
	NumberOfDaysWorked,
	DateLastDayWorked,
	FullWagesPaidInd,
	DateOfReturnToWork,
	PreExistingDisability,
	DateOfMaxMedImprov,
	CurrentReturnToWorkDate,
	ClaimStatus,
	ClaimType,
	AgreeToCompensateCode,
	DateOfRepresentation,
	LateReasonCode,
	TestProductionInd,
	AccSiteCountyParish,
	AccSiteLocationNarrative,
	AccSiteOrganizationName,
	AccSiteCity,
	AccSiteStreet,
	AccSiteState,
	CalculatedWeeklyCompAmt,
	ClaimAdminMailInfoAttent,
	ClaimAdminMailingCountry,
	ClaimAdminClaimRepPhone,
	ClaimAdminClaimRepEmail,
	ClaimAdminClaimRepFax,
	ClaimAdminClaimRepName,
	CurrentDateDisBegan,
	CurrentDateLastDayWorked,
	DeathResultofInjuryCode,
	DiscFringeBenefits,
	EmpAuthReleaseMedInd,
	EmployeeEducationLevel,
	EmployeeEmploymentVisa,
	EmployeeGreenCard,
	EmployeeJurisdicationID,
	EmployeeMailingCountry,
	EmployeePassportNumber,
	EmpSSNReleaseInd,
	EmployeeTaxFilingStatus,
	EmployerContactBusPhone,
	EmployerContactName,
	EmployerContactEMail,
	EmployerContactFax,
	EmployerMailingInfo,
	EmployerPhysicalCountry,
	EmployerMailingCity,
	EmployerMailingCountry,
	EmployerMailingPostal,
	EmployerMailingAddress1,
	EmployerMailingAddress2,
	EmployerMailingState,
	EmployerTypeCode,
	EstGrossWeeklyAmtInd,
	InitMedProvName,
	InitMedProvPhysCity,
	InitMedProvPhysCountry,
	InitMedProvPhysPostal,
	InitMedProvPhysAddress1,
	InitMedProvPhysAddress2,
	InitMedProvPhysState,
	InsuredPostalCode,
	InsuredTypeCode,
	InsurerTypeCode,
	JurisdictionBranchOffice,
	ClaimAdministratorFEIN,
	ClaimAdministratorName,
	ReturnToWorkTypeCode,
	SuspensionEffectiveDate,
	FullDenialRescissionDate,
	FullDenialReasonNarrative,
	FullDenialEffectiveDate,
	ClaimAdminAlternatePostalCode,
	AnticipatedWageLossIndicator,
	EmployerPaidSalaryPriorToAcquisitionCode,
	WorkWeekTypeCode,
	WorkDaysScheduledCode,
	EmployeeSecurityID,
	EmployerNatureOfBusiness,
	NonConsecutivePeriod,
	EmpNumberEntitledExempt,
	EmpNumberWithholdingExempt,
	PIMinPaymentInd,
	PhysicalRestrictionsInd,
	SelfInsurerOrgTypeCode,
	SelfInsuranceLicCertNumber,
	AccidentPremisesCode,
	SelfInsurerAuthTypeCode,
	EmployeeLastNameSuffix,
	WageEffectiveDate,
	EmployeeIDTypeQualifier,
	EmployerPaidSalaryComp,
	AccidentSiteCountry,
	DateEmployerHadKnowledgeOfDisability,
	AverageWage,
	TypeOfLossCode,
	InsolventInsurerFEIN,
	PartialDenialCode,
	MaintenanceTypeCorrectionCode,
	MaintenanceTypeCorrectionCodeDate,
	InitialDateOfLostTime,
	DateClaimAdminKnewLostTime,
	AwardOrderDate,
	InsuredFEIN,
	EmployerUINumber,
	ICD9CMDiagnosisCode,
	CancelReasonCode,
	CurrentReturnToWorkTypeCode,
	CurrentPhysicalRestrictionsInd,
	InitialReturnToWorkTypeCode,
	InitialPhysicalRestrictionsIndicator,
	o_InitialReturnToWorkWithSameEmployerIndicator AS InitialReturnToWorkWithSameEmployerIndicator,
	o_RTWSameEmpInd AS RTWSameEmpInd,
	CurrentReturnToWorkWithSameEmployerIndicator,
	FROICancelReasonNarrative,
	InjurySeverityTypeCode,
	CurrentDateEmpKnowledgeofCurrentDateDisability,
	CurrentDateClaimAdminKnowledgeofCurrentDateDisability,
	DateClaimAdminHadKnowledgeClaimMetReportingRequirements,
	EmployeeIndividualTaxpayerIdentificationNumber
	FROM EXPTRANS
	QUALIFY ROW_NUMBER() OVER (PARTITION BY WorkNcciMitchellID, XPK_VALUE ORDER BY NULL) = 1
),
FroiSroiSchema AS (
	INSERT INTO FroiSroiSchema
	(XPK_fro_WCNRequest, XPK_fro_ROI, FK_fro_WCNRequest, report, release, version0, fro_R99001_TransSetID_HD1, fro_R99098_SenderIDFEIN, fro_R98098_SenderIDFiller, fro_R97098_SenderIDPostalCode, fro_R99099_ReceiverIDFEIN, fro_R98099_ReceiverIDFiller, fro_R97099_ReceiverIDPostalCode, fro_R00100_DateTransmissionSent, fro_R00101_TimeTransmissionSent, fro_R00102_OriginalTransmissionDate, fro_R00103_OriginalTransmissionTime, fro_R99104_TestProductionInd, fro_R99105_VerIDTransmissionTypeCode, fro_R98105_VerIDReleaseNumber, fro_R00001_TransSetID, fro_R00002_MaintTypeCode, fro_R00003_MaintTypeCodeDate, fro_R00004_Jurisdiction, fro_R00005_AgencyClaimNumber, fro_R00006_InsurerFEIN, fro_R00007_InsurerName, fro_R90007_IsTPA, fro_R00010_ClaimAdminAddress1, fro_R00011_ClaimAdminAddress2, fro_R00012_ClaimAdminCity, fro_R00013_ClaimAdminState, fro_R00014_ClaimAdminPostalCode, fro_R00015_ClaimAdminClaimNumber, fro_R00016_EmployerFEIN, fro_R00017_InsuredName, fro_R00018_EmployerName, fro_R00019_EmployerPhysicalAddress1, fro_R00020_EmployerPhysicalAddress2, fro_R00021_EmployerPhysicalCity, fro_R00022_EmployerPhysicalState, fro_R00023_EmployerPhysicalPostal, fro_R00025_IndustryCode, fro_R00027_InsuredLocationNumber, fro_R00028_PolicyNumber, fro_R00029_PolicyEffectiveDate, fro_R00030_PolicyExpirationDate, fro_R00031_DateOfInjury, fro_R00032_TimeOfInjury, fro_R00033_PostalCodeOfInjurySite, fro_R00035_NatureOfInjuryCode, fro_R00036_PartOfBodyInjuredCode, fro_R00037_CauseOfInjuryCode, fro_R00038_AccidentDescriptionCause, fro_R00039_InitialTreatmentCode, fro_R00040_DateReportedToEmployer, fro_R00041_DateReportedToClaimAdmin, fro_R00042_SocialSecurityNumber, fro_R00043_EmployeeLastName, fro_R00044_EmployeeFirstName, fro_R00045_EmployeeMiddleInitial, fro_R00046_EmployeeAddress1, fro_R00047_EmployeeAddress2, fro_R00048_EmployeeCity, fro_R00049_EmployeeState, fro_R00050_EmployeePostalCode, fro_R00051_EmployeePhone, fro_R00052_EmployeeDateOfBirth, fro_R00053_GenderCode, fro_R00054_MaritalStatusCode, fro_R00055_NumberOfDependents, fro_R00056_InitialDateDisBegan, fro_R00057_EmployeeDateOfDeath, fro_R00058_EmploymentStatusCode, fro_R00059_ClassCode, fro_R00060_OccupationDescription, fro_R00061_DateOfHire, fro_R00063_WagePeriodCode, fro_R00064_NumberOfDaysWorked, fro_R00065_DateLastDayWorked, fro_R00066_FullWagesPaidInd, fro_R00068_DateOfRTW, fro_R00069_PreExistingDisability, fro_R00070_DateOfMaxMedImprov, fro_R00072_CurrentRTWDate, fro_R00073_ClaimStatus, fro_R00074_ClaimType, fro_R00075_AgreeToCompensateCode, fro_R00076_DateOfRepresentation, fro_R00077_LateReasonCode, fro_R00104_TestProductionInd, fro_R00118_AccSiteCountyParish, fro_R00119_AccSiteLocationNarrative, fro_R00120_AccSiteOrganizationName, fro_R00121_AccSiteCity, fro_R00122_AccSiteStreet, fro_R00123_AccSiteState, fro_R00134_CalculatedWeeklyCompAmt, fro_R00135_ClaimAdminMailInfoAttent, fro_R00136_ClaimAdminMailingCountry, fro_R00137_ClaimAdminClaimRepPhone, fro_R00138_ClaimAdminClaimRepEmail, fro_R00139_ClaimAdminClaimRepFax, fro_R00140_ClaimAdminClaimRepName, fro_R00144_CurrentDateDisBegan, fro_R00145_CurrentDateLastDayWorked, fro_R00146_DeathResultofInjuryCode, fro_R00149_DiscFringeBenefits, fro_R00150_EmpAuthReleaseMedInd, fro_R00151_EmployeeEducationLevel, fro_R00152_EmployeeEmploymentVisa, fro_R00153_EmployeeGreenCard, fro_R00154_EmployeeJurisdictionID, fro_R00155_EmployeeMailingCountry, fro_R00156_EmployeePassportNumber, fro_R00157_EmpSSNReleaseInd, fro_R00158_EmployeeTaxFilingStatus, fro_R00159_EmployerContactBusPhone, fro_R00160_EmployerContactName, fro_R00161_EmployerContactEMail, fro_R00162_EmployerContactFax, fro_R00163_EmployerMailingInfo, fro_R00164_EmployerPhysicalCountry, fro_R00165_EmployerMailingCity, fro_R00166_EmployerMailingCountry, fro_R00167_EmployerMailingPostal, fro_R00168_EmployerMailingAddress1, fro_R00169_EmployerMailingAddress2, fro_R00170_EmployerMailingState, fro_R00171_EmployerTypeCode, fro_R00172_EstGrossWeeklyAmtInd, fro_R00176_InitMedProvName, fro_R00177_InitMedProvPhysCity, fro_R00178_InitMedProvPhysCountry, fro_R00179_InitMedProvPhysPostal, fro_R00180_InitMedProvPhysAddress1, fro_R00181_InitMedProvPhysAddress2, fro_R00182_InitMedProvPhysState, fro_R00183_InsuredPostalCode, fro_R00184_InsuredTypeCode, fro_R00185_InsurerTypeCode, fro_R00186_JurisdictionBranchOffice, fro_R00187_ClaimAdministratorFEIN, fro_R00188_ClaimAdministratorName, fro_R00189_RTWTypeCode, fro_R00193_SuspensionEffectiveDate, fro_R00196_FullDenialRescissionDate, fro_R00197_FullDenialReasonNarrative, fro_R00199_FullDenialEffectiveDate, fro_R00200_ClaimAdminAlternatePostalCode, fro_R00201_AnticipatedWageLossIndicator, fro_R00203_EmployerPaidSalaryPriorToAcquisitionCode, fro_R00204_WorkWeekTypeCode, fro_R00205_WorkDaysScheduledCode, fro_R00206_EmployeeSecurityID, fro_R00210_EmployerNatureOfBusiness, fro_R00212_NonConsecutivePeriod, fro_R00213_EmpNumberEntitledExempt, fro_R00214_EmpNumberWithholdingExempt, fro_R00223_PIMinPaymentInd, fro_R00224_PhysicalRestrictionsInd, fro_R00228_RTWSameEmpInd, fro_R00229_InjurySeverityTypeCode, fro_R00232_SelfInsurerOrgTypeCode, fro_R00239_SelfInsuranceLicCertNumber, fro_R00249_AccidentPremisesCode, fro_R00250_SelfInsurerAuthTypeCode, fro_R00255_EmployeeLastNameSuffix, fro_R00256_WageEffectiveDate, fro_R00270_EmployeeIDTypeQualifier, fro_R00273_EmployerPaidSalaryComp, fro_R00280_AccidentSiteCountry, fro_R00281_DateEmployerHadKnowledge, fro_R00286_AverageWage, fro_R00290_TypeOfLossCode, fro_R00292_InsolventInsurerFEIN, fro_R00294_PartialDenialCode, fro_R00295_MaintenanceTypeCorrectionCode, fro_R00296_MaintenanceTypeCorrectionCodeDate, fro_R00297_InitialDateOfLostTime, fro_R00298_DateClaimAdminKnewLostTime, fro_R00299_AwardOrderDate, fro_R00314_InsuredFEIN, fro_R00329_EmployerUINumber, fro_R00400_CancelReasonCode, fro_R00402_CancelReasonNarrative, fro_R00403_InitialRTWTypeCode, fro_R00404_InitialRTWPhysicalRestrictionsIndicator, fro_R00405_InitialRTWWithSameEmployer, fro_R00406_LatestRTWTypeCode, fro_R00407_LatestRTWPhysicalRestrictionsIndicator, fro_R00408_LatestRTWWithSameEmployerIndicator, fro_R00416_CurrentDateEmpKnowledgeofCurrentDateDisability, fro_R00417_CurrentDateClaimAdminKnowledgeofCurrentDateDisability, fro_R00437_EmployeeIndividualTaxpayerIdentificationNumber, fro_R00441_DateClaimAdminKnewClaimMetRequirements, fro_R00522_ICD9CMDiagnosisCode, XPK_fro_lineitems, FK_fro_ROI, maxcount, liid, XPK_fro_li, FK_fro_lineitems, fro_R00207_MCOCode, fro_R00208_MCOIDNumber, fro_R00209_MCOName, fro_R00036_PartofBodyInjuredLine, fro_R00421_PartofBodyInjuredLocation, fro_R00422_PartofBodyInjuredFingersLocation, fro_R00198_FullDenialReasonCode, fro_R00237_WitnessBusinessPhone, fro_R00238_WitnessName)
	SELECT 
	AGGTRANS.XPK_VALUE AS XPK_FRO_WCNREQUEST, 
	AGG_WorkMitchell.WCClaimantDetailAKId AS XPK_FRO_ROI, 
	AGG_WorkMitchell.XPK_VALUE AS FK_FRO_WCNREQUEST, 
	AGG_WorkMitchell.REPORT AS REPORT, 
	AGG_WorkMitchell.RELEASE AS RELEASE, 
	AGG_WorkMitchell.VERSION AS VERSION0, 
	AGG_WorkMitchell.TransSetID_HD1 AS FRO_R99001_TRANSSETID_HD1, 
	AGG_WorkMitchell.SenderIDFEIN AS FRO_R99098_SENDERIDFEIN, 
	AGG_WorkMitchell.SenderIDFiller AS FRO_R98098_SENDERIDFILLER, 
	AGG_WorkMitchell.SenderIDPostalCode AS FRO_R97098_SENDERIDPOSTALCODE, 
	AGG_WorkMitchell.ReceiverIDFEIN AS FRO_R99099_RECEIVERIDFEIN, 
	AGG_WorkMitchell.ReceiverIDFiller AS FRO_R98099_RECEIVERIDFILLER, 
	AGG_WorkMitchell.ReceiverIDPostalCode AS FRO_R97099_RECEIVERIDPOSTALCODE, 
	AGG_WorkMitchell.DateTransmissionSent AS FRO_R00100_DATETRANSMISSIONSENT, 
	AGG_WorkMitchell.TimeTransmissionSent AS FRO_R00101_TIMETRANSMISSIONSENT, 
	AGG_WorkMitchell.OriginalTransmissionDate AS FRO_R00102_ORIGINALTRANSMISSIONDATE, 
	AGG_WorkMitchell.OriginalTransmissionTime AS FRO_R00103_ORIGINALTRANSMISSIONTIME, 
	AGG_WorkMitchell.TestProductionInd_H AS FRO_R99104_TESTPRODUCTIONIND, 
	AGG_WorkMitchell.VerIDTransmissionTypeCode AS FRO_R99105_VERIDTRANSMISSIONTYPECODE, 
	AGG_WorkMitchell.VerIDReleaseNumber AS FRO_R98105_VERIDRELEASENUMBER, 
	AGG_WorkMitchell.TransactionSetID AS FRO_R00001_TRANSSETID, 
	AGG_WorkMitchell.MaintenanceTypeCode AS FRO_R00002_MAINTTYPECODE, 
	AGG_WorkMitchell.MaitenanceTypeCodeDate AS FRO_R00003_MAINTTYPECODEDATE, 
	AGG_WorkMitchell.JurisdictionStateCode AS FRO_R00004_JURISDICTION, 
	AGG_WorkMitchell.JurisdictionClaimNumber AS FRO_R00005_AGENCYCLAIMNUMBER, 
	AGG_WorkMitchell.InsurerFEIN AS FRO_R00006_INSURERFEIN, 
	AGG_WorkMitchell.InsurerName AS FRO_R00007_INSURERNAME, 
	AGG_WorkMitchell.IsTPA AS FRO_R90007_ISTPA, 
	AGG_WorkMitchell.ClaimAdminAddress1 AS FRO_R00010_CLAIMADMINADDRESS1, 
	AGG_WorkMitchell.ClaimAdminAddress2 AS FRO_R00011_CLAIMADMINADDRESS2, 
	AGG_WorkMitchell.ClaimAdminCity AS FRO_R00012_CLAIMADMINCITY, 
	AGG_WorkMitchell.ClaimAdminStateCode AS FRO_R00013_CLAIMADMINSTATE, 
	AGG_WorkMitchell.ClaimAdminPostalCode AS FRO_R00014_CLAIMADMINPOSTALCODE, 
	AGG_WorkMitchell.ClaimAdminClaimNumber AS FRO_R00015_CLAIMADMINCLAIMNUMBER, 
	AGG_WorkMitchell.EmployerFEIN AS FRO_R00016_EMPLOYERFEIN, 
	AGG_WorkMitchell.InsuredName AS FRO_R00017_INSUREDNAME, 
	AGG_WorkMitchell.EmployerName AS FRO_R00018_EMPLOYERNAME, 
	AGG_WorkMitchell.EmployerPhysicalAddress1 AS FRO_R00019_EMPLOYERPHYSICALADDRESS1, 
	AGG_WorkMitchell.EmployerPhysicalAddress2 AS FRO_R00020_EMPLOYERPHYSICALADDRESS2, 
	AGG_WorkMitchell.EmployerPhysicalCity AS FRO_R00021_EMPLOYERPHYSICALCITY, 
	AGG_WorkMitchell.EmployerPhysicalStateCode AS FRO_R00022_EMPLOYERPHYSICALSTATE, 
	AGG_WorkMitchell.EmployerPhysicalPostalCode AS FRO_R00023_EMPLOYERPHYSICALPOSTAL, 
	AGG_WorkMitchell.IndustryCode AS FRO_R00025_INDUSTRYCODE, 
	AGG_WorkMitchell.InsuredLocationIdentifier AS FRO_R00027_INSUREDLOCATIONNUMBER, 
	AGG_WorkMitchell.PolicyNumberIdentifier AS FRO_R00028_POLICYNUMBER, 
	AGG_WorkMitchell.PolicyEffectiveDate AS FRO_R00029_POLICYEFFECTIVEDATE, 
	AGG_WorkMitchell.PolicyExpirationDate AS FRO_R00030_POLICYEXPIRATIONDATE, 
	AGG_WorkMitchell.DateOfInjury AS FRO_R00031_DATEOFINJURY, 
	AGG_WorkMitchell.TimeOfInjury AS FRO_R00032_TIMEOFINJURY, 
	AGG_WorkMitchell.PostalCodeOfInjuryState AS FRO_R00033_POSTALCODEOFINJURYSITE, 
	AGG_WorkMitchell.NatureOfInjuryCode AS FRO_R00035_NATUREOFINJURYCODE, 
	AGG_WorkMitchell.PartOfBodyInjuryCode AS FRO_R00036_PARTOFBODYINJUREDCODE, 
	AGG_WorkMitchell.CauseOfInjuryCode AS FRO_R00037_CAUSEOFINJURYCODE, 
	AGG_WorkMitchell.AccidentDescriptionCause AS FRO_R00038_ACCIDENTDESCRIPTIONCAUSE, 
	AGG_WorkMitchell.InitialTreatmentCode AS FRO_R00039_INITIALTREATMENTCODE, 
	AGG_WorkMitchell.DateReportedToEmployer AS FRO_R00040_DATEREPORTEDTOEMPLOYER, 
	AGG_WorkMitchell.DateReportedToClaimAdmin AS FRO_R00041_DATEREPORTEDTOCLAIMADMIN, 
	AGG_WorkMitchell.SocialSecurityNumber AS FRO_R00042_SOCIALSECURITYNUMBER, 
	AGG_WorkMitchell.EmployeeLastName AS FRO_R00043_EMPLOYEELASTNAME, 
	AGG_WorkMitchell.EmployeeFirstName AS FRO_R00044_EMPLOYEEFIRSTNAME, 
	AGG_WorkMitchell.EmployeeMiddleInitial AS FRO_R00045_EMPLOYEEMIDDLEINITIAL, 
	AGG_WorkMitchell.EmployeeAddress1 AS FRO_R00046_EMPLOYEEADDRESS1, 
	AGG_WorkMitchell.EmployeeAddress2 AS FRO_R00047_EMPLOYEEADDRESS2, 
	AGG_WorkMitchell.EmployeeCity AS FRO_R00048_EMPLOYEECITY, 
	AGG_WorkMitchell.EmployeeState AS FRO_R00049_EMPLOYEESTATE, 
	AGG_WorkMitchell.EmployeePostalCode AS FRO_R00050_EMPLOYEEPOSTALCODE, 
	AGG_WorkMitchell.EmployeePhone AS FRO_R00051_EMPLOYEEPHONE, 
	AGG_WorkMitchell.EmployeeDateOfBirth AS FRO_R00052_EMPLOYEEDATEOFBIRTH, 
	AGG_WorkMitchell.GenderCode AS FRO_R00053_GENDERCODE, 
	AGG_WorkMitchell.MaritalStatusCode AS FRO_R00054_MARITALSTATUSCODE, 
	AGG_WorkMitchell.NumberOfDependents AS FRO_R00055_NUMBEROFDEPENDENTS, 
	AGG_WorkMitchell.InitialDateDisabilityBegan AS FRO_R00056_INITIALDATEDISBEGAN, 
	AGG_WorkMitchell.EmployeeDateOfDeath AS FRO_R00057_EMPLOYEEDATEOFDEATH, 
	AGG_WorkMitchell.EmploymentStatusCode AS FRO_R00058_EMPLOYMENTSTATUSCODE, 
	AGG_WorkMitchell.ClassCode AS FRO_R00059_CLASSCODE, 
	AGG_WorkMitchell.OccupationDescription AS FRO_R00060_OCCUPATIONDESCRIPTION, 
	AGG_WorkMitchell.DateOfHire AS FRO_R00061_DATEOFHIRE, 
	AGG_WorkMitchell.WagePeriodCode AS FRO_R00063_WAGEPERIODCODE, 
	AGG_WorkMitchell.NumberOfDaysWorked AS FRO_R00064_NUMBEROFDAYSWORKED, 
	AGG_WorkMitchell.DateLastDayWorked AS FRO_R00065_DATELASTDAYWORKED, 
	AGG_WorkMitchell.FullWagesPaidInd AS FRO_R00066_FULLWAGESPAIDIND, 
	AGG_WorkMitchell.DateOfReturnToWork AS FRO_R00068_DATEOFRTW, 
	AGG_WorkMitchell.PreExistingDisability AS FRO_R00069_PREEXISTINGDISABILITY, 
	AGG_WorkMitchell.DateOfMaxMedImprov AS FRO_R00070_DATEOFMAXMEDIMPROV, 
	AGG_WorkMitchell.CurrentReturnToWorkDate AS FRO_R00072_CURRENTRTWDATE, 
	AGG_WorkMitchell.ClaimStatus AS FRO_R00073_CLAIMSTATUS, 
	AGG_WorkMitchell.ClaimType AS FRO_R00074_CLAIMTYPE, 
	AGG_WorkMitchell.AgreeToCompensateCode AS FRO_R00075_AGREETOCOMPENSATECODE, 
	AGG_WorkMitchell.DateOfRepresentation AS FRO_R00076_DATEOFREPRESENTATION, 
	AGG_WorkMitchell.LateReasonCode AS FRO_R00077_LATEREASONCODE, 
	AGG_WorkMitchell.TestProductionInd AS FRO_R00104_TESTPRODUCTIONIND, 
	AGG_WorkMitchell.AccSiteCountyParish AS FRO_R00118_ACCSITECOUNTYPARISH, 
	AGG_WorkMitchell.AccSiteLocationNarrative AS FRO_R00119_ACCSITELOCATIONNARRATIVE, 
	AGG_WorkMitchell.AccSiteOrganizationName AS FRO_R00120_ACCSITEORGANIZATIONNAME, 
	AGG_WorkMitchell.AccSiteCity AS FRO_R00121_ACCSITECITY, 
	AGG_WorkMitchell.AccSiteStreet AS FRO_R00122_ACCSITESTREET, 
	AGG_WorkMitchell.AccSiteState AS FRO_R00123_ACCSITESTATE, 
	AGG_WorkMitchell.CalculatedWeeklyCompAmt AS FRO_R00134_CALCULATEDWEEKLYCOMPAMT, 
	AGG_WorkMitchell.ClaimAdminMailInfoAttent AS FRO_R00135_CLAIMADMINMAILINFOATTENT, 
	AGG_WorkMitchell.ClaimAdminMailingCountry AS FRO_R00136_CLAIMADMINMAILINGCOUNTRY, 
	AGG_WorkMitchell.ClaimAdminClaimRepPhone AS FRO_R00137_CLAIMADMINCLAIMREPPHONE, 
	AGG_WorkMitchell.ClaimAdminClaimRepEmail AS FRO_R00138_CLAIMADMINCLAIMREPEMAIL, 
	AGG_WorkMitchell.ClaimAdminClaimRepFax AS FRO_R00139_CLAIMADMINCLAIMREPFAX, 
	AGG_WorkMitchell.ClaimAdminClaimRepName AS FRO_R00140_CLAIMADMINCLAIMREPNAME, 
	AGG_WorkMitchell.CurrentDateDisBegan AS FRO_R00144_CURRENTDATEDISBEGAN, 
	AGG_WorkMitchell.CurrentDateLastDayWorked AS FRO_R00145_CURRENTDATELASTDAYWORKED, 
	AGG_WorkMitchell.DeathResultofInjuryCode AS FRO_R00146_DEATHRESULTOFINJURYCODE, 
	AGG_WorkMitchell.DiscFringeBenefits AS FRO_R00149_DISCFRINGEBENEFITS, 
	AGG_WorkMitchell.EmpAuthReleaseMedInd AS FRO_R00150_EMPAUTHRELEASEMEDIND, 
	AGG_WorkMitchell.EmployeeEducationLevel AS FRO_R00151_EMPLOYEEEDUCATIONLEVEL, 
	AGG_WorkMitchell.EmployeeEmploymentVisa AS FRO_R00152_EMPLOYEEEMPLOYMENTVISA, 
	AGG_WorkMitchell.EmployeeGreenCard AS FRO_R00153_EMPLOYEEGREENCARD, 
	AGG_WorkMitchell.EmployeeJurisdicationID AS FRO_R00154_EMPLOYEEJURISDICTIONID, 
	AGG_WorkMitchell.EmployeeMailingCountry AS FRO_R00155_EMPLOYEEMAILINGCOUNTRY, 
	AGG_WorkMitchell.EmployeePassportNumber AS FRO_R00156_EMPLOYEEPASSPORTNUMBER, 
	AGG_WorkMitchell.EmpSSNReleaseInd AS FRO_R00157_EMPSSNRELEASEIND, 
	AGG_WorkMitchell.EmployeeTaxFilingStatus AS FRO_R00158_EMPLOYEETAXFILINGSTATUS, 
	AGG_WorkMitchell.EmployerContactBusPhone AS FRO_R00159_EMPLOYERCONTACTBUSPHONE, 
	AGG_WorkMitchell.EmployerContactName AS FRO_R00160_EMPLOYERCONTACTNAME, 
	AGG_WorkMitchell.EmployerContactEMail AS FRO_R00161_EMPLOYERCONTACTEMAIL, 
	AGG_WorkMitchell.EmployerContactFax AS FRO_R00162_EMPLOYERCONTACTFAX, 
	AGG_WorkMitchell.EmployerMailingInfo AS FRO_R00163_EMPLOYERMAILINGINFO, 
	AGG_WorkMitchell.EmployerPhysicalCountry AS FRO_R00164_EMPLOYERPHYSICALCOUNTRY, 
	AGG_WorkMitchell.EmployerMailingCity AS FRO_R00165_EMPLOYERMAILINGCITY, 
	AGG_WorkMitchell.EmployerMailingCountry AS FRO_R00166_EMPLOYERMAILINGCOUNTRY, 
	AGG_WorkMitchell.EmployerMailingPostal AS FRO_R00167_EMPLOYERMAILINGPOSTAL, 
	AGG_WorkMitchell.EmployerMailingAddress1 AS FRO_R00168_EMPLOYERMAILINGADDRESS1, 
	AGG_WorkMitchell.EmployerMailingAddress2 AS FRO_R00169_EMPLOYERMAILINGADDRESS2, 
	AGG_WorkMitchell.EmployerMailingState AS FRO_R00170_EMPLOYERMAILINGSTATE, 
	AGG_WorkMitchell.EmployerTypeCode AS FRO_R00171_EMPLOYERTYPECODE, 
	AGG_WorkMitchell.EstGrossWeeklyAmtInd AS FRO_R00172_ESTGROSSWEEKLYAMTIND, 
	AGG_WorkMitchell.InitMedProvName AS FRO_R00176_INITMEDPROVNAME, 
	AGG_WorkMitchell.InitMedProvPhysCity AS FRO_R00177_INITMEDPROVPHYSCITY, 
	AGG_WorkMitchell.InitMedProvPhysCountry AS FRO_R00178_INITMEDPROVPHYSCOUNTRY, 
	AGG_WorkMitchell.InitMedProvPhysPostal AS FRO_R00179_INITMEDPROVPHYSPOSTAL, 
	AGG_WorkMitchell.InitMedProvPhysAddress1 AS FRO_R00180_INITMEDPROVPHYSADDRESS1, 
	AGG_WorkMitchell.InitMedProvPhysAddress2 AS FRO_R00181_INITMEDPROVPHYSADDRESS2, 
	AGG_WorkMitchell.InitMedProvPhysState AS FRO_R00182_INITMEDPROVPHYSSTATE, 
	AGG_WorkMitchell.InsuredPostalCode AS FRO_R00183_INSUREDPOSTALCODE, 
	AGG_WorkMitchell.InsuredTypeCode AS FRO_R00184_INSUREDTYPECODE, 
	AGG_WorkMitchell.InsurerTypeCode AS FRO_R00185_INSURERTYPECODE, 
	AGG_WorkMitchell.JurisdictionBranchOffice AS FRO_R00186_JURISDICTIONBRANCHOFFICE, 
	AGG_WorkMitchell.ClaimAdministratorFEIN AS FRO_R00187_CLAIMADMINISTRATORFEIN, 
	AGG_WorkMitchell.ClaimAdministratorName AS FRO_R00188_CLAIMADMINISTRATORNAME, 
	AGG_WorkMitchell.ReturnToWorkTypeCode AS FRO_R00189_RTWTYPECODE, 
	AGG_WorkMitchell.SuspensionEffectiveDate AS FRO_R00193_SUSPENSIONEFFECTIVEDATE, 
	AGG_WorkMitchell.FullDenialRescissionDate AS FRO_R00196_FULLDENIALRESCISSIONDATE, 
	AGG_WorkMitchell.FullDenialReasonNarrative AS FRO_R00197_FULLDENIALREASONNARRATIVE, 
	AGG_WorkMitchell.FullDenialEffectiveDate AS FRO_R00199_FULLDENIALEFFECTIVEDATE, 
	AGG_WorkMitchell.ClaimAdminAlternatePostalCode AS FRO_R00200_CLAIMADMINALTERNATEPOSTALCODE, 
	AGG_WorkMitchell.AnticipatedWageLossIndicator AS FRO_R00201_ANTICIPATEDWAGELOSSINDICATOR, 
	AGG_WorkMitchell.EmployerPaidSalaryPriorToAcquisitionCode AS FRO_R00203_EMPLOYERPAIDSALARYPRIORTOACQUISITIONCODE, 
	AGG_WorkMitchell.WorkWeekTypeCode AS FRO_R00204_WORKWEEKTYPECODE, 
	AGG_WorkMitchell.WorkDaysScheduledCode AS FRO_R00205_WORKDAYSSCHEDULEDCODE, 
	AGG_WorkMitchell.EmployeeSecurityID AS FRO_R00206_EMPLOYEESECURITYID, 
	AGG_WorkMitchell.EmployerNatureOfBusiness AS FRO_R00210_EMPLOYERNATUREOFBUSINESS, 
	AGG_WorkMitchell.NonConsecutivePeriod AS FRO_R00212_NONCONSECUTIVEPERIOD, 
	AGG_WorkMitchell.EmpNumberEntitledExempt AS FRO_R00213_EMPNUMBERENTITLEDEXEMPT, 
	AGG_WorkMitchell.EmpNumberWithholdingExempt AS FRO_R00214_EMPNUMBERWITHHOLDINGEXEMPT, 
	AGG_WorkMitchell.PIMinPaymentInd AS FRO_R00223_PIMINPAYMENTIND, 
	AGG_WorkMitchell.PhysicalRestrictionsInd AS FRO_R00224_PHYSICALRESTRICTIONSIND, 
	AGG_WorkMitchell.RTWSameEmpInd AS FRO_R00228_RTWSAMEEMPIND, 
	AGG_WorkMitchell.InjurySeverityTypeCode AS FRO_R00229_INJURYSEVERITYTYPECODE, 
	AGG_WorkMitchell.SelfInsurerOrgTypeCode AS FRO_R00232_SELFINSURERORGTYPECODE, 
	AGG_WorkMitchell.SelfInsuranceLicCertNumber AS FRO_R00239_SELFINSURANCELICCERTNUMBER, 
	AGG_WorkMitchell.AccidentPremisesCode AS FRO_R00249_ACCIDENTPREMISESCODE, 
	AGG_WorkMitchell.SelfInsurerAuthTypeCode AS FRO_R00250_SELFINSURERAUTHTYPECODE, 
	AGG_WorkMitchell.EmployeeLastNameSuffix AS FRO_R00255_EMPLOYEELASTNAMESUFFIX, 
	AGG_WorkMitchell.WageEffectiveDate AS FRO_R00256_WAGEEFFECTIVEDATE, 
	AGG_WorkMitchell.EmployeeIDTypeQualifier AS FRO_R00270_EMPLOYEEIDTYPEQUALIFIER, 
	AGG_WorkMitchell.EmployerPaidSalaryComp AS FRO_R00273_EMPLOYERPAIDSALARYCOMP, 
	AGG_WorkMitchell.AccidentSiteCountry AS FRO_R00280_ACCIDENTSITECOUNTRY, 
	AGG_WorkMitchell.DateEmployerHadKnowledgeOfDisability AS FRO_R00281_DATEEMPLOYERHADKNOWLEDGE, 
	AGG_WorkMitchell.AverageWage AS FRO_R00286_AVERAGEWAGE, 
	AGG_WorkMitchell.TypeOfLossCode AS FRO_R00290_TYPEOFLOSSCODE, 
	AGG_WorkMitchell.InsolventInsurerFEIN AS FRO_R00292_INSOLVENTINSURERFEIN, 
	AGG_WorkMitchell.PartialDenialCode AS FRO_R00294_PARTIALDENIALCODE, 
	AGG_WorkMitchell.MaintenanceTypeCorrectionCode AS FRO_R00295_MAINTENANCETYPECORRECTIONCODE, 
	AGG_WorkMitchell.MaintenanceTypeCorrectionCodeDate AS FRO_R00296_MAINTENANCETYPECORRECTIONCODEDATE, 
	AGG_WorkMitchell.InitialDateOfLostTime AS FRO_R00297_INITIALDATEOFLOSTTIME, 
	AGG_WorkMitchell.DateClaimAdminKnewLostTime AS FRO_R00298_DATECLAIMADMINKNEWLOSTTIME, 
	AGG_WorkMitchell.AwardOrderDate AS FRO_R00299_AWARDORDERDATE, 
	AGG_WorkMitchell.InsuredFEIN AS FRO_R00314_INSUREDFEIN, 
	AGG_WorkMitchell.EmployerUINumber AS FRO_R00329_EMPLOYERUINUMBER, 
	AGG_WorkMitchell.CancelReasonCode AS FRO_R00400_CANCELREASONCODE, 
	AGG_WorkMitchell.FROICancelReasonNarrative AS FRO_R00402_CANCELREASONNARRATIVE, 
	AGG_WorkMitchell.InitialReturnToWorkTypeCode AS FRO_R00403_INITIALRTWTYPECODE, 
	AGG_WorkMitchell.InitialPhysicalRestrictionsIndicator AS FRO_R00404_INITIALRTWPHYSICALRESTRICTIONSINDICATOR, 
	AGG_WorkMitchell.InitialReturnToWorkWithSameEmployerIndicator AS FRO_R00405_INITIALRTWWITHSAMEEMPLOYER, 
	AGG_WorkMitchell.CurrentReturnToWorkTypeCode AS FRO_R00406_LATESTRTWTYPECODE, 
	AGG_WorkMitchell.CurrentPhysicalRestrictionsInd AS FRO_R00407_LATESTRTWPHYSICALRESTRICTIONSINDICATOR, 
	AGG_WorkMitchell.CurrentReturnToWorkWithSameEmployerIndicator AS FRO_R00408_LATESTRTWWITHSAMEEMPLOYERINDICATOR, 
	AGG_WorkMitchell.CurrentDateEmpKnowledgeofCurrentDateDisability AS FRO_R00416_CURRENTDATEEMPKNOWLEDGEOFCURRENTDATEDISABILITY, 
	AGG_WorkMitchell.CurrentDateClaimAdminKnowledgeofCurrentDateDisability AS FRO_R00417_CURRENTDATECLAIMADMINKNOWLEDGEOFCURRENTDATEDISABILITY, 
	AGG_WorkMitchell.EmployeeIndividualTaxpayerIdentificationNumber AS FRO_R00437_EMPLOYEEINDIVIDUALTAXPAYERIDENTIFICATIONNUMBER, 
	AGG_WorkMitchell.DateClaimAdminHadKnowledgeClaimMetReportingRequirements AS FRO_R00441_DATECLAIMADMINKNEWCLAIMMETREQUIREMENTS, 
	AGG_WorkMitchell.ICD9CMDiagnosisCode AS FRO_R00522_ICD9CMDIAGNOSISCODE, 
	AGG_LineItems.XPK_wcn_LineItems AS XPK_FRO_LINEITEMS, 
	AGG_LineItems.WCClaimantDetailAKId AS FK_FRO_ROI, 
	AGG_LineItems.MaxCount AS MAXCOUNT, 
	AGG_LineItems.LIID, 
	EXP_Union.PK AS XPK_FRO_LI, 
	EXP_Union.o_XPK_wcn_LineItems AS FK_FRO_LINEITEMS, 
	EXP_Union.MCOCode AS FRO_R00207_MCOCODE, 
	EXP_Union.MCOIDNumber AS FRO_R00208_MCOIDNUMBER, 
	EXP_Union.MCOName AS FRO_R00209_MCONAME, 
	EXP_Union.PartOfBodyInjuredLine AS FRO_R00036_PARTOFBODYINJUREDLINE, 
	EXP_Union.PartOfBodyInjuredLocationCode AS FRO_R00421_PARTOFBODYINJUREDLOCATION, 
	EXP_Union.PartOfBodyInjuredFingersToes AS FRO_R00422_PARTOFBODYINJUREDFINGERSLOCATION, 
	EXP_Union.FullDenialReasonCode AS FRO_R00198_FULLDENIALREASONCODE, 
	EXP_Union.WitnessBusinessPhone1 AS FRO_R00237_WITNESSBUSINESSPHONE, 
	EXP_Union.WitnessFullName AS FRO_R00238_WITNESSNAME
	FROM EXP_Union
),