WITH
SQ_WB_Policy AS (
	SELECT WB_Policy.PolicyId, WB_Policy.WB_PolicyId, WB_Policy.SessionId, WB_Policy.PolicyCoverage, WB_Policy.PurePremium, WB_Policy.CustomerCare, WB_Policy.Division, WB_Policy.Terrorism, WB_Policy.IsPreliminaryAuditRequired, WB_Policy.IsMidTermAuditRequired, WB_Policy.PolicyProgram, WB_Policy.Association, WB_Policy.ReceivedAMPM, WB_Policy.ReceivedDate, WB_Policy.ReceivedTimeHour, WB_Policy.ReceivedTimeMinute, WB_Policy.BCCCode, WB_Policy.PlusPak, WB_Policy.PolicyNumber, WB_Policy.IsRollover, WB_Policy.PriorCarrierNameOther, WB_Policy.PremiumMining, WB_Policy.QuoteType, WB_Policy.BCCCodeDesc, WB_Policy.DescriptionOfChildCarePremises, WB_Policy.ConsentToRate, WB_Policy.MultipleLocationCredit, WB_Policy.WBProduct, WB_Policy.WBProductType, WB_Policy.RequestingEntity, WB_Policy.PolicyVersion, WB_Policy.PolicyVersionFormatted, WB_Policy.AssociationDiscount, WB_Policy.AssociationDiscountFactor, WB_Policy.AssociationMessages, WB_Policy.AssociationMessagesMCRA, WB_Policy.RiskGrade, WB_Policy.ProgramFactor, WB_Policy.ClearedIdentification, WB_Policy.ClearedIdentificationDateTimeStamp, WB_Policy.LegalNoticeRequired, WB_Policy.AutomaticRenewalIndicator, WB_Policy.IsBindableFlag, WB_Policy.AssignedUnderwriterFirstName, WB_Policy.AssignedUnderwriterLastName, WB_Policy.PreviousPolicyVersion, WB_Policy.Code, WB_Policy.Comments, WB_Policy.Decision, WB_Policy.Message, WB_Policy.RuleType, WB_Policy.Program, WB_Policy.StatusCode, WB_Policy.ReinsuranceIndicator, WB_Policy.OriginalBillingAccountNumber, WB_Policy.OriginalPayPlan, WB_Policy.OriginalTargetDueDate, WB_Policy.EndorseProcessedBy, WB_Policy.Deleted 
	FROM
	WB_Policy
	INNER JOIN @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session on
	@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_Policy.SessionId=@{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session.SessionId
	WHERE
	DC_Session.CreateDateTime >=  '@{pipeline().parameters.SELECTION_START_TS}' 
	and
	DC_Session.CreateDateTime <  '@{pipeline().parameters.SELECTION_END_TS}' 
	ORDER BY
	WB_Policy.SessionId
),
Exp_WB_Policy AS (
	SELECT
	PolicyId,
	WB_PolicyId,
	SessionId,
	PolicyCoverage,
	PurePremium,
	CustomerCare,
	Division,
	Terrorism,
	IsPreliminaryAuditRequired,
	IsMidTermAuditRequired,
	PolicyProgram,
	Association,
	ReceivedAMPM,
	ReceivedDate,
	ReceivedTimeHour,
	ReceivedTimeMinute,
	BCCCode,
	PlusPak,
	PolicyNumber,
	IsRollover,
	PriorCarrierNameOther,
	PremiumMining,
	QuoteType,
	BCCCodeDesc,
	DescriptionOfChildCarePremises,
	ConsentToRate,
	MultipleLocationCredit,
	WBProduct,
	WBProductType,
	RequestingEntity,
	PolicyVersion,
	PolicyVersionFormatted,
	AssociationDiscount,
	AssociationDiscountFactor,
	AssociationMessages,
	AssociationMessagesMCRA,
	RiskGrade,
	ProgramFactor,
	ClearedIdentification,
	ClearedIdentificationDateTimeStamp,
	LegalNoticeRequired,
	AutomaticRenewalIndicator,
	IsBindableFlag,
	AssignedUnderwriterFirstName,
	AssignedUnderwriterLastName,
	PreviousPolicyVersion,
	Code,
	Comments,
	Decision,
	Message,
	RuleType,
	Program,
	StatusCode,
	ReinsuranceIndicator,
	OriginalBillingAccountNumber,
	OriginalPayPlan,
	OriginalTargetDueDate,
	EndorseProcessedBy,
	Deleted,
	Sysdate AS ExtractDate,
	'DCT' AS SourceSystemID
	FROM SQ_WB_Policy
),
WBPolicyStage AS (
	INSERT INTO Shortcut_to_WBPolicyStage
	(ExtractDate, SourceSystemid, PolicyId, WB_PolicyId, SessionId, Division, Program, PolicyVersion, ReceivedDate, CustomerCare, Terrorism, IsPreliminaryAuditRequired, IsMidTermAuditRequired, PlusPak, PolicyNumber, IsRollover, PriorCarrierNameOther, Association, PremiumMining, QuoteType, ReceivedAMPM, ReceivedTimeHour, ReceivedTimeMinute, BCCCode, DescriptionOfChildCarePremises, AssociationMessages, AssociationMessagesMCRA, AssociationDiscount, RiskGrade, AssociationDiscountFactor, ProgramFactor, ClearedIdentification, ClearedIdentificationDateTimeStamp, LegalNoticeRequired, PolicyVersionFormatted, AssignedUnderwriterFirstName, AssignedUnderwriterLastName, StatusCode, Code, BCCCodeDesc, ConsentToRate, MultipleLocationCredit, Comments, Decision, Message, AutomaticRenewalIndicator, WBProduct, WBProductType, PolicyCoverage, IsBindableFlag, PurePremium, RuleType, RequestingEntity, PolicyProgram, PreviousPolicyVersion, ReinsuranceIndicator, OriginalBillingAccountNumber, OriginalPayPlan, OriginalTargetDueDate, EndorseProcessedBy, Deleted)
	SELECT 
	EXTRACTDATE, 
	SourceSystemID AS SOURCESYSTEMID, 
	POLICYID, 
	WB_POLICYID, 
	SESSIONID, 
	DIVISION, 
	PROGRAM, 
	POLICYVERSION, 
	RECEIVEDDATE, 
	CUSTOMERCARE, 
	TERRORISM, 
	ISPRELIMINARYAUDITREQUIRED, 
	ISMIDTERMAUDITREQUIRED, 
	PLUSPAK, 
	POLICYNUMBER, 
	ISROLLOVER, 
	PRIORCARRIERNAMEOTHER, 
	ASSOCIATION, 
	PREMIUMMINING, 
	QUOTETYPE, 
	RECEIVEDAMPM, 
	RECEIVEDTIMEHOUR, 
	RECEIVEDTIMEMINUTE, 
	BCCCODE, 
	DESCRIPTIONOFCHILDCAREPREMISES, 
	ASSOCIATIONMESSAGES, 
	ASSOCIATIONMESSAGESMCRA, 
	ASSOCIATIONDISCOUNT, 
	RISKGRADE, 
	ASSOCIATIONDISCOUNTFACTOR, 
	PROGRAMFACTOR, 
	CLEAREDIDENTIFICATION, 
	CLEAREDIDENTIFICATIONDATETIMESTAMP, 
	LEGALNOTICEREQUIRED, 
	POLICYVERSIONFORMATTED, 
	ASSIGNEDUNDERWRITERFIRSTNAME, 
	ASSIGNEDUNDERWRITERLASTNAME, 
	STATUSCODE, 
	CODE, 
	BCCCODEDESC, 
	CONSENTTORATE, 
	MULTIPLELOCATIONCREDIT, 
	COMMENTS, 
	DECISION, 
	MESSAGE, 
	AUTOMATICRENEWALINDICATOR, 
	WBPRODUCT, 
	WBPRODUCTTYPE, 
	POLICYCOVERAGE, 
	ISBINDABLEFLAG, 
	PUREPREMIUM, 
	RULETYPE, 
	REQUESTINGENTITY, 
	POLICYPROGRAM, 
	PREVIOUSPOLICYVERSION, 
	REINSURANCEINDICATOR, 
	ORIGINALBILLINGACCOUNTNUMBER, 
	ORIGINALPAYPLAN, 
	ORIGINALTARGETDUEDATE, 
	ENDORSEPROCESSEDBY, 
	DELETED
	FROM Exp_WB_Policy
),