WITH
SQ_ADJUSTER_MASTER AS (

-- TODO Manual --

),
EXP_Input AS (
	SELECT
	ADNM_TAXID_SSN AS IN_ADNM_TAXID_SSN,
	-- *INF*: (LTRIM(RTRIM(IN_ADNM_TAXID_SSN)))
	(LTRIM(RTRIM(IN_ADNM_TAXID_SSN))) AS OUT_ADNM_TAXID_SSN
	FROM SQ_ADJUSTER_MASTER
),
LKP_cus_stg_insert_pms_adjuster_master_stage_tokens_file AS (
),
EXP_ADJSTR_MSTR AS (
	SELECT
	SYSDATE AS EXTRACT_DATE,
	SYSDATE AS AS_OF_DATE,
	'' AS RECORD_COUNT_OP,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS SOURCE_SYSTEM_ID,
	SQ_ADJUSTER_MASTER.ADNM_ADJUSTOR_NBR,
	SQ_ADJUSTER_MASTER.ADNM_TAXID_SSN,
	SQ_ADJUSTER_MASTER.ADNM_NAME,
	SQ_ADJUSTER_MASTER.ADNM_COMMNT1,
	SQ_ADJUSTER_MASTER.ADNM_ADDRESS,
	SQ_ADJUSTER_MASTER.ADNM_COMMNT2,
	SQ_ADJUSTER_MASTER.ADNM_CITY_STATE,
	SQ_ADJUSTER_MASTER.ADNM_COMMNT3,
	SQ_ADJUSTER_MASTER.ADNM_POLICE_CHARGE,
	SQ_ADJUSTER_MASTER.ADNM_TAX_INDICATOR,
	SQ_ADJUSTER_MASTER.ADNM_ZIP_CODE,
	SQ_ADJUSTER_MASTER.ADNM_AREA_CODE,
	SQ_ADJUSTER_MASTER.ADNM_PREFIX,
	SQ_ADJUSTER_MASTER.ADNM_LAST_FOUR,
	SQ_ADJUSTER_MASTER.ADNM_TYPE_ADJUSTOR,
	SQ_ADJUSTER_MASTER.ADNM_ADJUSTOR_BRANCH_NUMBER,
	SQ_ADJUSTER_MASTER.ADNM_ADJUSTOR_KIND,
	SQ_ADJUSTER_MASTER.ADNM_FX_AREA_CODE,
	SQ_ADJUSTER_MASTER.ADNM_FX_PREFIX,
	SQ_ADJUSTER_MASTER.ADNM_FX_LAST_FOUR,
	LKP_cus_stg_insert_pms_adjuster_master_stage_tokens_file.lkp_ADNM_TAXID_SSN_ID AS ADNM_TAXID_SSN_ID,
	LKP_cus_stg_insert_pms_adjuster_master_stage_tokens_file.ADNM_TAXID_SSN_Token AS ADNM_TAXID_SSN_Tokens,
	-- *INF*: IIF(ISNULL(LTRIM(RTRIM(ADNM_TAXID_SSN_ID))),ADNM_TAXID_SSN,ADNM_TAXID_SSN_Tokens)
	IFF(LTRIM(RTRIM(ADNM_TAXID_SSN_ID)) IS NULL, ADNM_TAXID_SSN, ADNM_TAXID_SSN_Tokens) AS V_ADNM_TAXID_SSN,
	V_ADNM_TAXID_SSN AS OUT_ADNM_TAXID_SSN
	FROM SQ_ADJUSTER_MASTER
	LEFT JOIN LKP_cus_stg_insert_pms_adjuster_master_stage_tokens_file
	ON LKP_cus_stg_insert_pms_adjuster_master_stage_tokens_file.lkp_ADNM_TAXID_SSN_ID = EXP_Input.OUT_ADNM_TAXID_SSN
),
PMS_ADJUSTER_MASTER_STAGE AS (
	TRUNCATE TABLE PMS_ADJUSTER_MASTER_STAGE;
	INSERT INTO PMS_ADJUSTER_MASTER_STAGE
	(ADNM_ADJUSTOR_NBR, ADNM_TAXID_SSN, ADNM_NAME, ADNM_COMMNT1, ADNM_ADDRESS, ADNM_COMMNT2, ADNM_CITY_STATE, ADNM_COMMNT3, ADNM_POLICE_CHARGE, ADNM_TAX_INDICATOR, ADNM_ZIP_CODE, ADNM_AREA_CODE, ADNM_PREFIX, ADNM_LAST_FOUR, ADNM_TYPE_ADJUSTOR, ADNM_ADJUSTOR_BRANCH_NUMBER, ADNM_ADJUSTOR_KIND, ADNM_FX_AREA_CODE, ADNM_FX_PREFIX, ADNM_FX_LAST_FOUR, EXTRACT_DATE, AS_OF_DATE, RECORD_COUNT, SOURCE_SYSTEM_ID)
	SELECT 
	ADNM_ADJUSTOR_NBR, 
	OUT_ADNM_TAXID_SSN AS ADNM_TAXID_SSN, 
	ADNM_NAME, 
	ADNM_COMMNT1, 
	ADNM_ADDRESS, 
	ADNM_COMMNT2, 
	ADNM_CITY_STATE, 
	ADNM_COMMNT3, 
	ADNM_POLICE_CHARGE, 
	ADNM_TAX_INDICATOR, 
	ADNM_ZIP_CODE, 
	ADNM_AREA_CODE, 
	ADNM_PREFIX, 
	ADNM_LAST_FOUR, 
	ADNM_TYPE_ADJUSTOR, 
	ADNM_ADJUSTOR_BRANCH_NUMBER, 
	ADNM_ADJUSTOR_KIND, 
	ADNM_FX_AREA_CODE, 
	ADNM_FX_PREFIX, 
	ADNM_FX_LAST_FOUR, 
	EXTRACT_DATE, 
	AS_OF_DATE, 
	RECORD_COUNT_OP AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID
	FROM EXP_ADJSTR_MSTR
),