WITH
SQ_UserInfo AS (
	SELECT
		UserId,
		UserPassword,
		UserAgencyCode,
		UserNum,
		UserLName,
		UserFName,
		UserPermission,
		UserPosition,
		UserSubCode,
		UserEmail,
		UserLogonSwitch,
		UserUpdated,
		TimeStamp,
		VerifySwitch,
		UserAppsSwitch,
		UserCommercialSwitch,
		CommercialVisits,
		UserBillClaimSwitch,
		UserNSISwitch,
		rough_notes_flag,
		clines_promoter,
		nsi_bond_flag,
		log_notes_flag,
		modified_date,
		modified_user_id,
		password_exp_date,
		fail_login_attempt,
		locked_date_time,
		bond_appr_flag,
		last_activity_date,
		Dflt_Portal_View_Id
	FROM UserInfo
),
EXP_Values AS (
	SELECT
	SYSDATE AS EXTRACT_DATE,
	SYSDATE AS AS_OF_DATE,
	'' AS RECORD_COUNT,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS SOURCE_SYSTEM_ID,
	UserId,
	UserPassword,
	UserAgencyCode,
	UserNum,
	UserLName,
	UserFName,
	UserPermission,
	UserPosition,
	UserSubCode,
	UserEmail,
	UserLogonSwitch,
	UserUpdated,
	TimeStamp,
	VerifySwitch,
	UserAppsSwitch,
	UserCommercialSwitch,
	CommercialVisits,
	UserBillClaimSwitch,
	UserNSISwitch,
	rough_notes_flag,
	clines_promoter,
	nsi_bond_flag,
	log_notes_flag,
	modified_date,
	modified_user_id,
	password_exp_date,
	fail_login_attempt,
	locked_date_time,
	bond_appr_flag,
	last_activity_date,
	Dflt_Portal_View_Id
	FROM SQ_UserInfo
),
UserInfo_stage AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.UserInfo_stage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.UserInfo_stage
	(UserId, UserAgencyCode, UserNum, UserLName, UserFName, UserPermission, UserPosition, UserSubCode, UserEmail, UserLogonSwitch, UserUpdated, TimeStamp, VerifySwitch, UserAppsSwitch, UserCommercialSwitch, CommercialVisits, UserBillClaimSwitch, UserNSISwitch, rough_notes_flag, clines_promoter, nsi_bond_flag, log_notes_flag, modified_date, modified_user_id, password_exp_date, fail_login_attempt, locked_date_time, bond_appr_flag, last_activity_date, Dflt_Portal_View_Id, extract_date, as_of_date, record_count, source_system_id)
	SELECT 
	USERID, 
	USERAGENCYCODE, 
	USERNUM, 
	USERLNAME, 
	USERFNAME, 
	USERPERMISSION, 
	USERPOSITION, 
	USERSUBCODE, 
	USEREMAIL, 
	USERLOGONSWITCH, 
	USERUPDATED, 
	TIMESTAMP, 
	VERIFYSWITCH, 
	USERAPPSSWITCH, 
	USERCOMMERCIALSWITCH, 
	COMMERCIALVISITS, 
	USERBILLCLAIMSWITCH, 
	USERNSISWITCH, 
	ROUGH_NOTES_FLAG, 
	CLINES_PROMOTER, 
	NSI_BOND_FLAG, 
	LOG_NOTES_FLAG, 
	MODIFIED_DATE, 
	MODIFIED_USER_ID, 
	PASSWORD_EXP_DATE, 
	FAIL_LOGIN_ATTEMPT, 
	LOCKED_DATE_TIME, 
	BOND_APPR_FLAG, 
	LAST_ACTIVITY_DATE, 
	DFLT_PORTAL_VIEW_ID, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID
	FROM EXP_Values
),