WITH
SEQTRANS AS (
	CREATE SEQUENCE SEQTRANS
	START = 0
	INCREMENT = 1;
),
WorkWCSTATAggregatedPremium AS (
	SELECT
		WorkWCSTATAggregatedPremiumId,
		AuditId,
		CreatedDate,
		ModifiedDate,
		SourceSystemId,
		EDWPremiumMasterCalculationPKId,
		EDWLossMasterCalculationPKId,
		TypeBureauCode,
		PremiumMasterRunDate,
		LossMasterRunDate,
		BureauCompanyCode,
		PolicyKey,
		StateProvinceCode,
		PolicyEffectiveDate,
		PolicyEndDate,
		InterstateRiskId,
		EmployeeLeasingCode,
		StateRatingEffectiveDate,
		FederalTaxId,
		ThreeYearFixedRatePolicyIndicator,
		MultistatePolicyIndicator,
		InterstateRatedPolicyIndicator,
		RetrospectiveratedPolicyIndicator,
		CancelledMidTermPolicyIndicator,
		ManagedCareOrganizationPolicyIndicator,
		TypeOfCoverageIdCode,
		TypeOfPlan,
		DeductibleAmountPerClaimAccident,
		InsuredName,
		WCSTATAddress,
		PremiumMasterClassCode,
		ExperienceModificationFactor,
		ExperienceModificationEffectiveDate,
		Exposure,
		PremiumMasterDirectWrittenPremiumAmount,
		ManualChargedRate,
		LossMasterClassCode,
		ClaimLossDate,
		ClaimOccurrenceStatusCode,
		InjuryTypeCode,
		CatastropheCode,
		IncurredIndemnityAmount,
		IncurredMedicalAmount,
		CauseOfLoss,
		TypeOfRecoveryCode,
		JurisdictionStateCode,
		BodyPartCode,
		NatureOfInjuryCode,
		CauseOfInjuryCode,
		PaidIndemnityAmount,
		PaidMedicalAmount,
		DeductibleReimbursementAmount,
		PaidAllocatedLossAdjustmentExpenseAmount,
		IncurredAllocatedLossAdjustmentExpenseAmount,
		LossCondition,
		TypeOfSettlement,
		ManagedCareOrganizationType,
		LumpSumIndicator,
		EstimatedAuditCode,
		CorrectionSeqNumber,
		ClaimNumber,
		RunMonthAuditPremium,
		AgeOfPolicy,
		PolicyPremiumTotal,
		ManualPremiumIndicator,
		PolicyStateManualPremiumTotal,
		BalMinPremiumTotal,
		RateEffectiveDate,
		AnyARDIndicator,
		ExperienceRated,
		TermType,
		ARDPassFlag,
		SplitPeriodCode,
		LossesSubjectToDeductibleCode,
		BasisOfDeductibleCalculationCode
	FROM WorkWCSTATAggregatedPremium
	INNER JOIN WorkWCSTATAggregatedPremium
	WHERE AuditId=@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}  @{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Extract AS (
	SELECT
	SourceSystemId,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	LossCondition AS loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RunMonthAuditPremium,
	AgeOfPolicy,
	PolicyPremiumTotal,
	ManualPremiumIndicator AS ManualPremiumInd,
	PolicyStateManualPremiumTotal,
	BalMinPremiumTotal,
	RateEffectiveDate,
	CreatedDate,
	ARDPassFlag AS ARD_Pass_Flag,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM WorkWCSTATAggregatedPremium
),
RTR_PremTrans AS (
	SELECT
	SourceSystemId,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RunMonthAuditPremium,
	AgeOfPolicy,
	PolicyPremiumTotal,
	ManualPremiumInd,
	PolicyStateManualPremiumTotal,
	BalMinPremiumTotal,
	RateEffectiveDate,
	ARD_Pass_Flag AS ARDPassFlag,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM EXP_Extract
),
RTR_PremTrans_PolicyClassCodesWithPremium AS (SELECT * FROM RTR_PremTrans WHERE --PolicyClassCodesWithPremium
--Fix PROD-8663
--Source File
--we do not report class codes with @{pipeline().parameters.0} premium (w/exception of 0174-MN only) in the source file. 
--- Class code -0012/1212 (covid class code) with zero rate and zero premium should be send to output file US-194087/US-183058

(AgeOfPolicy=18 AND (
PremiumMasterDirectWrittenPremiumAmount != 0 OR ARDPassFlag='1' OR (PremiumMasterClassCode='0174' AND StateProvinceCode='22')
OR (PremiumMasterClassCode='0012' AND NOT IN(StateProvinceCode,'07','37'))
OR (PremiumMasterClassCode='1212' AND IN(StateProvinceCode,'07','37'))
)
)
OR
--Correction File
--However, if we have a code in source file and it changes to @{pipeline().parameters.0} premium in correction report, we need to show. 
(AgeOfPolicy<>18  AND (PremiumMasterDirectWrittenPremiumAmount != 0 OR ARDPassFlag='1'
OR RunMonthAuditPremium !=0))
AND
StateProvinceCode <> '29'),
RTR_PremTrans_PolicyClassCode1111Processing AS (SELECT * FROM RTR_PremTrans WHERE --PolicyClassCode1111Processing
--Filter the Policy records that qualify for generating 1111 class code record
--For WI 0990 class code (balance to minimum) premium should be 0
-- US 448022 : NCCI states only: If Class Code 0012 is reported then we CAN'T report code 1111 for that state. Added logic - AND (PremiumMasterClassCode<>'0012' AND NOT IN(StateProvinceCode,  '04','07','20','21','29','31', '32','37','48'))

PolicyPremiumTotal !=0 AND 
ManualPremiumInd != 0 AND 
PolicyStateManualPremiumTotal = 0 AND 
StateProvinceCode != '29' AND
(PremiumMasterClassCode<>'0012' AND NOT IN(StateProvinceCode,  '04','07','20','21','29','31', '32','37','48'))

--Removed below logic as part of US-118475
--AND (StateProvinceCode = '48' AND BalMinPremiumTotal = 0 OR StateProvinceCode <> '48' )),
RTR_PremTrans_PolicyClassCodeNewJersey AS (SELECT * FROM RTR_PremTrans WHERE -- This group of the router is to bring only NJ records through
StateProvinceCode = '29'),
SRT_PolState AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate AS RateEffectiveDate3, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM RTR_PremTrans_PolicyClassCode1111Processing
	ORDER BY PolicyKey ASC, StateProvinceCode ASC
),
agg_PolState AS (
	SELECT
	SourceSystemId,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RateEffectiveDate3,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM SRT_PolState
	QUALIFY ROW_NUMBER() OVER (PARTITION BY PolicyKey, StateProvinceCode ORDER BY NULL) = 1
),
EXP_1111ClassCode AS (
	SELECT
	SourceSystemId,
	-1 AS o_EDWPremiumMasterCalculationPKId,
	-1 AS o_EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	'1111' AS o_PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate AS i_ExperienceModificationEffectiveDate,
	-- *INF*: -- Code that was here previously
	-- --TO_DATE('2100-12-31', 'YYYY-MM-DD')
	-- -- force exp mod date to default 12/31/2100 as we do for all exp mod factor of 0
	-- 
	-- -- ExpModEffDate needs to be the same as the PolicyEffectiveDate when the ClassCode is 1111
	-- IIF(MultistatePolicyIndicator='1' AND NOT IN(StateProvinceCode,'04','07','20','21','29','31','37','48'), PolicyEffectiveDate, TO_DATE('2100-12-31', 'YYYY-MM-DD'))
	IFF(
	    MultistatePolicyIndicator = '1'
	    and NOT StateProvinceCode IN ('04','07','20','21','29','31','37','48'),
	    PolicyEffectiveDate,
	    TO_TIMESTAMP('2100-12-31', 'YYYY-MM-DD')
	) AS o_ExperienceModificationEffectiveDate,
	0 AS o_Exposure,
	0 AS o_PremiumMasterDirectWrittenPremiumAmount,
	0 AS o_ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RateEffectiveDate3 AS RateEffectiveDate,
	0 AS Split_Period_Code,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM agg_PolState
),
srt_Policy_key AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate AS RateEffectiveDate1, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM RTR_PremTrans_PolicyClassCodesWithPremium
	ORDER BY PolicyKey ASC
),
Agg_Policy_Count AS (
	SELECT
	PolicyKey,
	-- *INF*: Count( PolicyKey)
	Count(PolicyKey) AS Rec_Count
	FROM srt_Policy_key
	GROUP BY PolicyKey
),
Jnr_Premium_Policy_Count AS (SELECT
	srt_Policy_key.SourceSystemId, 
	srt_Policy_key.EDWPremiumMasterCalculationPKId, 
	srt_Policy_key.EDWLossMasterCalculationPKId, 
	srt_Policy_key.TypeBureauCode, 
	srt_Policy_key.PremiumMasterRunDate, 
	srt_Policy_key.LossMasterRunDate, 
	srt_Policy_key.BureauCompanyCode, 
	srt_Policy_key.PolicyKey, 
	srt_Policy_key.StateProvinceCode, 
	srt_Policy_key.PolicyEffectiveDate, 
	srt_Policy_key.PolicyEndDate, 
	srt_Policy_key.InterstateRiskId, 
	srt_Policy_key.EmployeeLeasingCode, 
	srt_Policy_key.StateRatingEffectiveDate, 
	srt_Policy_key.FederalTaxId, 
	srt_Policy_key.ThreeYearFixedRatePolicyIndicator, 
	srt_Policy_key.MultistatePolicyIndicator, 
	srt_Policy_key.InterstateRatedPolicyIndicator, 
	srt_Policy_key.RetrospectiveratedPolicyIndicator, 
	srt_Policy_key.CancelledMidTermPolicyIndicator, 
	srt_Policy_key.ManagedCareOrganizationPolicyIndicator, 
	srt_Policy_key.TypeOfCoverageIdCode, 
	srt_Policy_key.TypeOfPlan, 
	srt_Policy_key.DeductibleAmountPerClaimAccident, 
	srt_Policy_key.InsuredName, 
	srt_Policy_key.WCSTATAddress, 
	srt_Policy_key.PremiumMasterClassCode, 
	srt_Policy_key.ExperienceModificationFactor, 
	srt_Policy_key.ExperienceModificationEffectiveDate, 
	srt_Policy_key.Exposure, 
	srt_Policy_key.PremiumMasterDirectWrittenPremiumAmount, 
	srt_Policy_key.ManualChargedRate, 
	srt_Policy_key.LossMasterClassCode, 
	srt_Policy_key.ClaimLossDate, 
	srt_Policy_key.ClaimOccurrenceStatusCode, 
	srt_Policy_key.InjuryTypeCode, 
	srt_Policy_key.CatastropheCode, 
	srt_Policy_key.IncurredIndemnityAmount, 
	srt_Policy_key.IncurredMedicalAmount, 
	srt_Policy_key.CauseOfLoss, 
	srt_Policy_key.TypeOfRecoveryCode, 
	srt_Policy_key.JurisdictionStateCode, 
	srt_Policy_key.BodyPartCode, 
	srt_Policy_key.NatureOfInjuryCode, 
	srt_Policy_key.CauseOfInjuryCode, 
	srt_Policy_key.PaidIndemnityAmount, 
	srt_Policy_key.PaidMedicalAmount, 
	srt_Policy_key.DeductibleReimbursementAmount, 
	srt_Policy_key.PaidAllocatedLossAdjustmentExpenseAmount, 
	srt_Policy_key.IncurredAllocatedLossAdjustmentExpenseAmount, 
	srt_Policy_key.loss_condition, 
	srt_Policy_key.TypeOfSettlement, 
	srt_Policy_key.ManagedCareOrganizationType, 
	srt_Policy_key.LumpSumIndicator, 
	srt_Policy_key.EstimatedAuditCode, 
	srt_Policy_key.CorrectionSeqNumber, 
	srt_Policy_key.ClaimNumber, 
	srt_Policy_key.RateEffectiveDate1, 
	Agg_Policy_Count.PolicyKey AS PolicyKey1, 
	Agg_Policy_Count.Rec_Count AS Count, 
	srt_Policy_key.LossesSubjectToDeductibleCode, 
	srt_Policy_key.BasisOfDeductibleCalculationCode
	FROM srt_Policy_key
	INNER JOIN Agg_Policy_Count
	ON Agg_Policy_Count.PolicyKey = srt_Policy_key.PolicyKey
),
Fil_Class_CD_0174_ZeroValuePremiumPolicy AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate1, 
	Count AS Rec_Count, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM Jnr_Premium_Policy_Count
	WHERE -- This condition is being used to filter out the transaction (PremiumMasterClassCode ='0174') from Minnesota state if Policy has been cancelled flat and there is no premium available
IIF(PremiumMasterClassCode='0174'  AND  StateProvinceCode = '22'  AND Rec_Count  =1, FALSE,TRUE)
),
sort_split_period_code AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate1, 
	ExperienceModificationEffectiveDate, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM Fil_Class_CD_0174_ZeroValuePremiumPolicy
	ORDER BY TypeBureauCode ASC, BureauCompanyCode ASC, PolicyKey ASC, StateProvinceCode ASC, PolicyEffectiveDate ASC, PolicyEndDate ASC, PremiumMasterClassCode ASC, RateEffectiveDate1 ASC, ExperienceModificationEffectiveDate ASC
),
Exp_SPlitPeriodCode AS (
	SELECT
	SourceSystemId,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	PremiumMasterClassCode,
	ExperienceModificationFactor,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RateEffectiveDate1,
	ExperienceModificationEffectiveDate,
	-- *INF*: IIF(TypeBureauCode=V_Prev_TypeBureauCode and BureauCompanyCode=V_Prev_BureauCompanyCode and PolicyKey=V_Prev_PolicyKey and StateProvinceCode=V_Prev_StateProvinceCode and PolicyEffectiveDate=V_Prev_PolicyEffectiveDate and PolicyEndDate=V_Prev_PolicyEndDate and PremiumMasterClassCode=V_Prev_PremiumMasterClassCode  and SourceSystemId='DCT' and (RateEffectiveDate1>V_Prev_RateEffectiveDate OR ExperienceModificationEffectiveDate>V_Prev_ExperienceModificationEffectiveDate),V_SplitPeriodCode+1,0)
	IFF(
	    TypeBureauCode = V_Prev_TypeBureauCode
	    and BureauCompanyCode = V_Prev_BureauCompanyCode
	    and PolicyKey = V_Prev_PolicyKey
	    and StateProvinceCode = V_Prev_StateProvinceCode
	    and PolicyEffectiveDate = V_Prev_PolicyEffectiveDate
	    and PolicyEndDate = V_Prev_PolicyEndDate
	    and PremiumMasterClassCode = V_Prev_PremiumMasterClassCode
	    and SourceSystemId = 'DCT'
	    and (RateEffectiveDate1 > V_Prev_RateEffectiveDate
	    or ExperienceModificationEffectiveDate > V_Prev_ExperienceModificationEffectiveDate),
	    V_SplitPeriodCode + 1,
	    0
	) AS V_SplitPeriodCode,
	V_SplitPeriodCode AS O_SplitPeriodCode,
	TypeBureauCode AS V_Prev_TypeBureauCode,
	BureauCompanyCode AS V_Prev_BureauCompanyCode,
	PolicyKey AS V_Prev_PolicyKey,
	StateProvinceCode AS V_Prev_StateProvinceCode,
	PolicyEffectiveDate AS V_Prev_PolicyEffectiveDate,
	PolicyEndDate AS V_Prev_PolicyEndDate,
	PremiumMasterClassCode AS V_Prev_PremiumMasterClassCode,
	RateEffectiveDate1 AS V_Prev_RateEffectiveDate,
	ExperienceModificationEffectiveDate AS V_Prev_ExperienceModificationEffectiveDate,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM sort_split_period_code
),
srt_Policy_Key_NJ AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate AS RateEffectiveDate1, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM RTR_PremTrans_PolicyClassCodeNewJersey
	ORDER BY PolicyKey ASC
),
Agg_Policy_ManualChargedRate_NJ AS (
	SELECT
	PolicyKey,
	ManualChargedRate,
	-- *INF*: MAX(ManualChargedRate)
	MAX(ManualChargedRate) AS MaxManualChargedRate
	FROM srt_Policy_Key_NJ
	GROUP BY PolicyKey
),
Jnr_Premium_Policy_Count1 AS (SELECT
	srt_Policy_Key_NJ.SourceSystemId, 
	srt_Policy_Key_NJ.EDWPremiumMasterCalculationPKId, 
	srt_Policy_Key_NJ.EDWLossMasterCalculationPKId, 
	srt_Policy_Key_NJ.TypeBureauCode, 
	srt_Policy_Key_NJ.PremiumMasterRunDate, 
	srt_Policy_Key_NJ.LossMasterRunDate, 
	srt_Policy_Key_NJ.BureauCompanyCode, 
	srt_Policy_Key_NJ.PolicyKey, 
	srt_Policy_Key_NJ.StateProvinceCode, 
	srt_Policy_Key_NJ.PolicyEffectiveDate, 
	srt_Policy_Key_NJ.PolicyEndDate, 
	srt_Policy_Key_NJ.InterstateRiskId, 
	srt_Policy_Key_NJ.EmployeeLeasingCode, 
	srt_Policy_Key_NJ.StateRatingEffectiveDate, 
	srt_Policy_Key_NJ.FederalTaxId, 
	srt_Policy_Key_NJ.ThreeYearFixedRatePolicyIndicator, 
	srt_Policy_Key_NJ.MultistatePolicyIndicator, 
	srt_Policy_Key_NJ.InterstateRatedPolicyIndicator, 
	srt_Policy_Key_NJ.RetrospectiveratedPolicyIndicator, 
	srt_Policy_Key_NJ.CancelledMidTermPolicyIndicator, 
	srt_Policy_Key_NJ.ManagedCareOrganizationPolicyIndicator, 
	srt_Policy_Key_NJ.TypeOfCoverageIdCode, 
	srt_Policy_Key_NJ.TypeOfPlan, 
	srt_Policy_Key_NJ.DeductibleAmountPerClaimAccident, 
	srt_Policy_Key_NJ.InsuredName, 
	srt_Policy_Key_NJ.WCSTATAddress, 
	srt_Policy_Key_NJ.PremiumMasterClassCode, 
	srt_Policy_Key_NJ.ExperienceModificationFactor, 
	srt_Policy_Key_NJ.ExperienceModificationEffectiveDate, 
	srt_Policy_Key_NJ.Exposure, 
	srt_Policy_Key_NJ.PremiumMasterDirectWrittenPremiumAmount, 
	srt_Policy_Key_NJ.ManualChargedRate, 
	srt_Policy_Key_NJ.LossMasterClassCode, 
	srt_Policy_Key_NJ.ClaimLossDate, 
	srt_Policy_Key_NJ.ClaimOccurrenceStatusCode, 
	srt_Policy_Key_NJ.InjuryTypeCode, 
	srt_Policy_Key_NJ.CatastropheCode, 
	srt_Policy_Key_NJ.IncurredIndemnityAmount, 
	srt_Policy_Key_NJ.IncurredMedicalAmount, 
	srt_Policy_Key_NJ.CauseOfLoss, 
	srt_Policy_Key_NJ.TypeOfRecoveryCode, 
	srt_Policy_Key_NJ.JurisdictionStateCode, 
	srt_Policy_Key_NJ.BodyPartCode, 
	srt_Policy_Key_NJ.NatureOfInjuryCode, 
	srt_Policy_Key_NJ.CauseOfInjuryCode, 
	srt_Policy_Key_NJ.PaidIndemnityAmount, 
	srt_Policy_Key_NJ.PaidMedicalAmount, 
	srt_Policy_Key_NJ.DeductibleReimbursementAmount, 
	srt_Policy_Key_NJ.PaidAllocatedLossAdjustmentExpenseAmount, 
	srt_Policy_Key_NJ.IncurredAllocatedLossAdjustmentExpenseAmount, 
	srt_Policy_Key_NJ.loss_condition, 
	srt_Policy_Key_NJ.TypeOfSettlement, 
	srt_Policy_Key_NJ.ManagedCareOrganizationType, 
	srt_Policy_Key_NJ.LumpSumIndicator, 
	srt_Policy_Key_NJ.EstimatedAuditCode, 
	srt_Policy_Key_NJ.CorrectionSeqNumber, 
	srt_Policy_Key_NJ.ClaimNumber, 
	srt_Policy_Key_NJ.RateEffectiveDate1, 
	Agg_Policy_ManualChargedRate_NJ.PolicyKey AS PolicyKey1, 
	Agg_Policy_ManualChargedRate_NJ.MaxManualChargedRate, 
	srt_Policy_Key_NJ.LossesSubjectToDeductibleCode, 
	srt_Policy_Key_NJ.BasisOfDeductibleCalculationCode
	FROM srt_Policy_Key_NJ
	INNER JOIN Agg_Policy_ManualChargedRate_NJ
	ON Agg_Policy_ManualChargedRate_NJ.PolicyKey = srt_Policy_Key_NJ.PolicyKey
),
Fil_NewJersey AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate1, 
	MaxManualChargedRate, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM Jnr_Premium_Policy_Count1
	WHERE -- This condition is being used to allow only the transactions that have a ClassCode of 0936 or the Max ManualCharge
IIF(PremiumMasterClassCode='0936' OR ManualChargedRate=MaxManualChargedRate, TRUE, FALSE)
),
sort_split_period_code_NJ AS (
	SELECT
	SourceSystemId, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	CorrectionSeqNumber, 
	ClaimNumber, 
	RateEffectiveDate1, 
	ExperienceModificationEffectiveDate, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM Fil_NewJersey
	ORDER BY TypeBureauCode ASC, BureauCompanyCode ASC, PolicyKey ASC, StateProvinceCode ASC, PolicyEffectiveDate ASC, PolicyEndDate ASC, PremiumMasterClassCode ASC, RateEffectiveDate1 ASC, ExperienceModificationEffectiveDate ASC
),
Exp_SPlitPeriodCode_NJ AS (
	SELECT
	SourceSystemId,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	DeductibleAmountPerClaimAccident,
	InsuredName,
	WCSTATAddress,
	PremiumMasterClassCode,
	ExperienceModificationFactor,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	loss_condition,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	LumpSumIndicator,
	EstimatedAuditCode,
	CorrectionSeqNumber,
	ClaimNumber,
	RateEffectiveDate1,
	ExperienceModificationEffectiveDate,
	-- *INF*: IIF(TypeBureauCode=V_Prev_TypeBureauCode and BureauCompanyCode=V_Prev_BureauCompanyCode and PolicyKey=V_Prev_PolicyKey and StateProvinceCode=V_Prev_StateProvinceCode and PolicyEffectiveDate=V_Prev_PolicyEffectiveDate and PolicyEndDate=V_Prev_PolicyEndDate and PremiumMasterClassCode=V_Prev_PremiumMasterClassCode  and SourceSystemId='DCT' and (RateEffectiveDate1>V_Prev_RateEffectiveDate OR ExperienceModificationEffectiveDate>V_Prev_ExperienceModificationEffectiveDate),V_SplitPeriodCode+1,0)
	IFF(
	    TypeBureauCode = V_Prev_TypeBureauCode
	    and BureauCompanyCode = V_Prev_BureauCompanyCode
	    and PolicyKey = V_Prev_PolicyKey
	    and StateProvinceCode = V_Prev_StateProvinceCode
	    and PolicyEffectiveDate = V_Prev_PolicyEffectiveDate
	    and PolicyEndDate = V_Prev_PolicyEndDate
	    and PremiumMasterClassCode = V_Prev_PremiumMasterClassCode
	    and SourceSystemId = 'DCT'
	    and (RateEffectiveDate1 > V_Prev_RateEffectiveDate
	    or ExperienceModificationEffectiveDate > V_Prev_ExperienceModificationEffectiveDate),
	    V_SplitPeriodCode + 1,
	    0
	) AS V_SplitPeriodCode,
	V_SplitPeriodCode AS O_SplitPeriodCode,
	TypeBureauCode AS V_Prev_TypeBureauCode,
	BureauCompanyCode AS V_Prev_BureauCompanyCode,
	PolicyKey AS V_Prev_PolicyKey,
	StateProvinceCode AS V_Prev_StateProvinceCode,
	PolicyEffectiveDate AS V_Prev_PolicyEffectiveDate,
	PolicyEndDate AS V_Prev_PolicyEndDate,
	PremiumMasterClassCode AS V_Prev_PremiumMasterClassCode,
	RateEffectiveDate1 AS V_Prev_RateEffectiveDate,
	ExperienceModificationEffectiveDate AS V_Prev_ExperienceModificationEffectiveDate,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode
	FROM sort_split_period_code_NJ
),
UN_ALL_Premium_Loss AS (
	SELECT EDWPremiumMasterCalculationPKId, EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, PremiumMasterClassCode, ExperienceModificationFactor, ExperienceModificationEffectiveDate, Exposure, PremiumMasterDirectWrittenPremiumAmount, ManualChargedRate, LossMasterClassCode, ClaimLossDate, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, CauseOfLoss, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, loss_condition, TypeOfSettlement, ManagedCareOrganizationType, LumpSumIndicator, EstimatedAuditCode, CorrectionSeqNumber, ClaimNumber, RateEffectiveDate1 AS RateEffectiveDate, O_SplitPeriodCode AS Split_Period_Code, LossesSubjectToDeductibleCode, BasisOfDeductibleCalculationCode
	FROM Exp_SPlitPeriodCode
	UNION
	SELECT o_EDWPremiumMasterCalculationPKId AS EDWPremiumMasterCalculationPKId, o_EDWLossMasterCalculationPKId AS EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, o_PremiumMasterClassCode AS PremiumMasterClassCode, ExperienceModificationFactor, o_ExperienceModificationEffectiveDate AS ExperienceModificationEffectiveDate, o_Exposure AS Exposure, o_PremiumMasterDirectWrittenPremiumAmount AS PremiumMasterDirectWrittenPremiumAmount, o_ManualChargedRate AS ManualChargedRate, LossMasterClassCode, ClaimLossDate, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, CauseOfLoss, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, loss_condition, TypeOfSettlement, ManagedCareOrganizationType, LumpSumIndicator, EstimatedAuditCode, CorrectionSeqNumber, ClaimNumber, RateEffectiveDate, Split_Period_Code, LossesSubjectToDeductibleCode, BasisOfDeductibleCalculationCode
	FROM EXP_1111ClassCode
	UNION
	SELECT EDWPremiumMasterCalculationPKId, EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, PremiumMasterClassCode, ExperienceModificationFactor, ExperienceModificationEffectiveDate, Exposure, PremiumMasterDirectWrittenPremiumAmount, ManualChargedRate, LossMasterClassCode, ClaimLossDate, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, CauseOfLoss, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, loss_condition, TypeOfSettlement, ManagedCareOrganizationType, LumpSumIndicator, EstimatedAuditCode, CorrectionSeqNumber, ClaimNumber, RateEffectiveDate1 AS RateEffectiveDate, O_SplitPeriodCode AS Split_Period_Code, LossesSubjectToDeductibleCode, BasisOfDeductibleCalculationCode
	FROM Exp_SPlitPeriodCode_NJ
),
SRT_AllRecords AS (
	SELECT
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	CauseOfLoss, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	loss_condition, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	LumpSumIndicator, 
	EstimatedAuditCode, 
	ClaimNumber, 
	ClaimPayCategoryCode, 
	claimant_num, 
	RateEffectiveDate, 
	Split_Period_Code, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode
	FROM UN_ALL_Premium_Loss
	ORDER BY PolicyKey ASC
),
AGG_MaxExperienceModificationFactor AS (
	SELECT
	PolicyKey,
	ExperienceModificationFactor,
	Split_Period_Code,
	-- *INF*: MAX(ExperienceModificationFactor)
	MAX(ExperienceModificationFactor) AS o_MaxExperienceModificationFactor,
	-- *INF*: IIF(MAX(Split_Period_Code)<>'0', '1', '0')
	IFF(MAX(Split_Period_Code) <> '0', '1', '0') AS o_SplitPeriodCodeIndicator
	FROM SRT_AllRecords
	GROUP BY PolicyKey
),
FIL_SplitPeriodCode AS (
	SELECT
	PolicyKey, 
	Split_Period_Code, 
	ExperienceModificationFactor
	FROM SRT_AllRecords
	WHERE IIF(Split_Period_Code='0', TRUE, FALSE)
),
AGG_MaxModFactorSplitPolicyCode AS (
	SELECT
	PolicyKey,
	Split_Period_Code,
	ExperienceModificationFactor,
	-- *INF*: MAX(ExperienceModificationFactor)
	MAX(ExperienceModificationFactor) AS o_MaxModFactorSplitPolicyCode
	FROM FIL_SplitPeriodCode
	GROUP BY PolicyKey
),
JNR_AllRecordsAndAggregates AS (SELECT
	AGG_MaxExperienceModificationFactor.PolicyKey, 
	AGG_MaxExperienceModificationFactor.o_MaxExperienceModificationFactor, 
	AGG_MaxExperienceModificationFactor.o_SplitPeriodCodeIndicator, 
	AGG_MaxModFactorSplitPolicyCode.PolicyKey AS PolicyKey1, 
	AGG_MaxModFactorSplitPolicyCode.o_MaxModFactorSplitPolicyCode
	FROM AGG_MaxExperienceModificationFactor
	RIGHT OUTER JOIN AGG_MaxModFactorSplitPolicyCode
	ON AGG_MaxModFactorSplitPolicyCode.PolicyKey = AGG_MaxExperienceModificationFactor.PolicyKey
),
JNRTRANS_AllRecordsAndMaxModFactor AS (SELECT
	SRT_AllRecords.EDWPremiumMasterCalculationPKId, 
	SRT_AllRecords.EDWLossMasterCalculationPKId, 
	SRT_AllRecords.TypeBureauCode, 
	SRT_AllRecords.PremiumMasterRunDate, 
	SRT_AllRecords.LossMasterRunDate, 
	SRT_AllRecords.BureauCompanyCode, 
	SRT_AllRecords.PolicyKey, 
	SRT_AllRecords.StateProvinceCode, 
	SRT_AllRecords.PolicyEffectiveDate, 
	SRT_AllRecords.PolicyEndDate, 
	SRT_AllRecords.InterstateRiskId, 
	SRT_AllRecords.EmployeeLeasingCode, 
	SRT_AllRecords.StateRatingEffectiveDate, 
	SRT_AllRecords.FederalTaxId, 
	SRT_AllRecords.ThreeYearFixedRatePolicyIndicator, 
	SRT_AllRecords.MultistatePolicyIndicator, 
	SRT_AllRecords.InterstateRatedPolicyIndicator, 
	SRT_AllRecords.RetrospectiveratedPolicyIndicator, 
	SRT_AllRecords.CancelledMidTermPolicyIndicator, 
	SRT_AllRecords.ManagedCareOrganizationPolicyIndicator, 
	SRT_AllRecords.TypeOfCoverageIdCode, 
	SRT_AllRecords.TypeOfPlan, 
	SRT_AllRecords.DeductibleAmountPerClaimAccident, 
	SRT_AllRecords.InsuredName, 
	SRT_AllRecords.WCSTATAddress, 
	SRT_AllRecords.PremiumMasterClassCode, 
	SRT_AllRecords.ExperienceModificationFactor, 
	SRT_AllRecords.ExperienceModificationEffectiveDate, 
	SRT_AllRecords.Exposure, 
	SRT_AllRecords.PremiumMasterDirectWrittenPremiumAmount, 
	SRT_AllRecords.ManualChargedRate, 
	SRT_AllRecords.LossMasterClassCode, 
	SRT_AllRecords.ClaimLossDate, 
	SRT_AllRecords.ClaimOccurrenceStatusCode, 
	SRT_AllRecords.InjuryTypeCode, 
	SRT_AllRecords.CatastropheCode, 
	SRT_AllRecords.IncurredIndemnityAmount, 
	SRT_AllRecords.IncurredMedicalAmount, 
	SRT_AllRecords.CauseOfLoss, 
	SRT_AllRecords.TypeOfRecoveryCode, 
	SRT_AllRecords.JurisdictionStateCode, 
	SRT_AllRecords.BodyPartCode, 
	SRT_AllRecords.NatureOfInjuryCode, 
	SRT_AllRecords.CauseOfInjuryCode, 
	SRT_AllRecords.PaidIndemnityAmount, 
	SRT_AllRecords.PaidMedicalAmount, 
	SRT_AllRecords.DeductibleReimbursementAmount, 
	SRT_AllRecords.PaidAllocatedLossAdjustmentExpenseAmount, 
	SRT_AllRecords.IncurredAllocatedLossAdjustmentExpenseAmount, 
	SRT_AllRecords.loss_condition, 
	SRT_AllRecords.TypeOfSettlement, 
	SRT_AllRecords.ManagedCareOrganizationType, 
	SRT_AllRecords.LumpSumIndicator, 
	SRT_AllRecords.EstimatedAuditCode, 
	SRT_AllRecords.ClaimNumber, 
	SRT_AllRecords.ClaimPayCategoryCode, 
	SRT_AllRecords.claimant_num, 
	SRT_AllRecords.RateEffectiveDate, 
	SRT_AllRecords.Split_Period_Code, 
	SRT_AllRecords.LossesSubjectToDeductibleCode, 
	SRT_AllRecords.BasisOfDeductibleCalculationCode, 
	JNR_AllRecordsAndAggregates.PolicyKey AS PolicyKey1, 
	JNR_AllRecordsAndAggregates.o_MaxExperienceModificationFactor AS MaxExperienceModificationFactor, 
	JNR_AllRecordsAndAggregates.o_SplitPeriodCodeIndicator, 
	JNR_AllRecordsAndAggregates.o_MaxModFactorSplitPolicyCode
	FROM SRT_AllRecords
	INNER JOIN JNR_AllRecordsAndAggregates
	ON JNR_AllRecordsAndAggregates.PolicyKey = SRT_AllRecords.PolicyKey
),
EXP_Prem AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditID,
	-- *INF*: TRUNC(SESSSTARTTIME,'D')
	CAST(TRUNC(SESSSTARTTIME, 'DAY') AS TIMESTAMP_NTZ(0)) AS o_CreateDate,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode,
	PolicyKey,
	StateProvinceCode,
	PolicyEffectiveDate AS i_PolicyEffectiveDate,
	i_PolicyEffectiveDate AS PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId,
	EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId,
	ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator,
	EstimatedAuditCode,
	RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode,
	TypeOfPlan,
	ClaimPayCategoryCode AS ClaimPayCategoryType,
	LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode,
	DeductibleAmountPerClaimAccident,
	InsuredName AS i_InsuredName,
	-- *INF*: REPLACECHR(0,i_InsuredName,CHR(34),'')
	REGEXP_REPLACE(i_InsuredName,CHR(34),'','i') AS o_InsuredName,
	WCSTATAddress,
	PremiumMasterDirectWrittenPremiumAmount AS i_PremiumMasterDirectWrittenPremiumAmount,
	-- *INF*: ROUND(i_PremiumMasterDirectWrittenPremiumAmount)
	ROUND(i_PremiumMasterDirectWrittenPremiumAmount) AS o_PremiumMasterDirectWrittenPremiumAmount,
	PremiumMasterClassCode,
	ExperienceModificationFactor AS i_ExperienceModificationFactor,
	-- *INF*: -- This was the code here before the changes for US 448020
	-- --iif(i_PremiumMasterDirectWrittenPremiumAmount=0 AND i_ExperienceModificationFactor!=0 AND PremiumMasterClassCode <> '1111',
	-- --0,
	-- --i_ExperienceModificationFactor) 
	-- 
	-- 
	-- -- The decode and logic was added for US 448020
	-- DECODE(TRUE,
	-- MultistatePolicyIndicator='0' AND StateProvinceCode='22' AND PremiumMasterClassCode='1111', 0,
	-- i_PremiumMasterDirectWrittenPremiumAmount=0 AND i_ExperienceModificationFactor!=0 AND PremiumMasterClassCode <> '1111',0,
	-- i_ExperienceModificationFactor<>0 AND PremiumMasterClassCode='1111' AND MultistatePolicyIndicator='1' AND IN(StateProvinceCode, '20'), 0,
	-- i_ExperienceModificationFactor=0 AND PremiumMasterClassCode='1111' AND MultistatePolicyIndicator='1' AND NOT IN(StateProvinceCode,'04','07','20','21','29','31','37','48') AND o_SplitPeriodCodeIndicator='1', MaxExpModFactorForSplitPeriodCode,
	-- i_ExperienceModificationFactor=0 AND PremiumMasterClassCode='1111' AND MultistatePolicyIndicator='1' AND NOT IN(StateProvinceCode,'04','07','20','21','29','31','37','48'),MaxExperienceModificationFactor,
	-- i_ExperienceModificationFactor)
	DECODE(
	    TRUE,
	    MultistatePolicyIndicator = '0' AND StateProvinceCode = '22' AND PremiumMasterClassCode = '1111', 0,
	    i_PremiumMasterDirectWrittenPremiumAmount = 0 AND i_ExperienceModificationFactor != 0 AND PremiumMasterClassCode <> '1111', 0,
	    i_ExperienceModificationFactor <> 0 AND PremiumMasterClassCode = '1111' AND MultistatePolicyIndicator = '1' AND StateProvinceCode IN ('20'), 0,
	    i_ExperienceModificationFactor = 0 AND PremiumMasterClassCode = '1111' AND MultistatePolicyIndicator = '1' AND NOT StateProvinceCode IN ('04','07','20','21','29','31','37','48') AND o_SplitPeriodCodeIndicator = '1', MaxExpModFactorForSplitPeriodCode,
	    i_ExperienceModificationFactor = 0 AND PremiumMasterClassCode = '1111' AND MultistatePolicyIndicator = '1' AND NOT StateProvinceCode IN ('04','07','20','21','29','31','37','48'), MaxExperienceModificationFactor,
	    i_ExperienceModificationFactor
	) AS v_ExperienceModificationFactor,
	v_ExperienceModificationFactor AS o_ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure AS i_Exposure,
	-- *INF*: IIF(IN(SUBSTR(PremiumMasterClassCode,1,4) ,'0908','0913','9108'),(i_Exposure*10),i_Exposure)
	IFF(
	    SUBSTR(PremiumMasterClassCode, 1, 4) IN ('0908','0913','9108'), (i_Exposure * 10),
	    i_Exposure
	) AS v_Exposure,
	-- *INF*: ROUND(IIF(ISNULL(v_Exposure),0,v_Exposure))
	ROUND(
	    IFF(
	        v_Exposure IS NULL, 0, v_Exposure
	    )) AS o_Exposure,
	ManualChargedRate,
	LossMasterClassCode,
	ClaimLossDate,
	ClaimNumber,
	ClaimOccurrenceStatusCode,
	InjuryTypeCode,
	CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	CauseOfLoss,
	TypeOfRecoveryCode,
	JurisdictionStateCode,
	BodyPartCode,
	NatureOfInjuryCode,
	CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	'N/A' AS SubjectPremiumTotal,
	'N/A' AS StandarPremiumTotal,
	'0' AS CorrectionSeqNumber,
	'N' AS ReplacementReportCode,
	'' AS CorrectionTypeCode,
	'01' AS TypeOfNonStandardIdCode,
	-- *INF*: TO_INTEGER(DATE_DIFF(TRUNC(SYSDATE,'MM'),TRUNC(i_PolicyEffectiveDate,'MM'),'MM'),TRUE)
	CAST(DATEDIFF(MONTH,CAST(TRUNC(CURRENT_TIMESTAMP, 'MONTH') AS TIMESTAMP_NTZ(0)),CAST(TRUNC(i_PolicyEffectiveDate, 'MONTH') AS TIMESTAMP_NTZ(0))) AS INTEGER) AS v_AfterEffDate,
	-- *INF*: DECODE(v_AfterEffDate,
	-- 18,'1',
	-- 30,'2',
	-- 42,'3',
	-- 54,'4',
	-- 66,'5',
	-- 78,'6',
	-- 90,'7',
	-- 102,'8',
	-- 114,'9',
	-- 126,'A',
	-- '0')
	DECODE(
	    v_AfterEffDate,
	    18, '1',
	    30, '2',
	    42, '3',
	    54, '4',
	    66, '5',
	    78, '6',
	    90, '7',
	    102, '8',
	    114, '9',
	    126, 'A',
	    '0'
	) AS v_PreviousReportLevelCodeReportNumber,
	v_PreviousReportLevelCodeReportNumber AS PreviousReportLevelCodeReportNumber,
	'P' AS UpdateTypeCode,
	loss_condition AS TypeOfLoss,
	'01' AS TypeOfClaim,
	TypeOfSettlement,
	ManagedCareOrganizationType,
	'N' AS VocationalRehabIndicator,
	LumpSumIndicator,
	'00' AS FraudulentClaimCode,
	-- *INF*: DECODE(TRUE, 
	-- EDWPremiumMasterCalculationPKId != -1,'',
	-- IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'DT'),'01',
	-- IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PT'),'02',
	-- StateProvinceCode = '21' AND IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PP','DF'),'03',
	-- StateProvinceCode <> '21' AND IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PP','DF','PB'),'09',
	-- StateProvinceCode = '21' AND IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PB'),'04',
	-- IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PD','TD','VR','SI','1B') AND IN(RTRIM(LTRIM(StateProvinceCode)), '22','48') AND DATE_DIFF(SYSDATE,i_PolicyEffectiveDate,'MM')  <= 30  AND  IncurredIndemnityAmount >  0 ,'05',
	-- IN(RTRIM(LTRIM(ClaimPayCategoryType)), 'PD','TD','VR') AND IN(RTRIM(LTRIM(StateProvinceCode)), '22','48') AND DATE_DIFF(SYSDATE,i_PolicyEffectiveDate,'MM')  > 30  and  IncurredIndemnityAmount  >  0,'09',
	-- IncurredMedicalAmount+IncurredIndemnityAmount = 0  and  IncurredAllocatedLossAdjustmentExpenseAmount > 0,'06',
	--  IncurredMedicalAmount>0 and   IncurredIndemnityAmount = 0,'06',
	-- IncurredIndemnityAmount>0,'05',
	-- '00'
	-- )
	-- 
	-- 
	DECODE(
	    TRUE,
	    EDWPremiumMasterCalculationPKId != - 1, '',
	    RTRIM(LTRIM(ClaimPayCategoryType)) IN ('DT'), '01',
	    RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PT'), '02',
	    StateProvinceCode = '21' AND RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PP','DF'), '03',
	    StateProvinceCode <> '21' AND RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PP','DF','PB'), '09',
	    StateProvinceCode = '21' AND RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PB'), '04',
	    RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PD','TD','VR','SI','1B') AND RTRIM(LTRIM(StateProvinceCode)) IN ('22','48') AND DATEDIFF(MONTH,CURRENT_TIMESTAMP,i_PolicyEffectiveDate) <= 30 AND IncurredIndemnityAmount > 0, '05',
	    RTRIM(LTRIM(ClaimPayCategoryType)) IN ('PD','TD','VR') AND RTRIM(LTRIM(StateProvinceCode)) IN ('22','48') AND DATEDIFF(MONTH,CURRENT_TIMESTAMP,i_PolicyEffectiveDate) > 30 and IncurredIndemnityAmount > 0, '09',
	    IncurredMedicalAmount + IncurredIndemnityAmount = 0 and IncurredAllocatedLossAdjustmentExpenseAmount > 0, '06',
	    IncurredMedicalAmount > 0 and IncurredIndemnityAmount = 0, '06',
	    IncurredIndemnityAmount > 0, '05',
	    '00'
	) AS o_InjuryTypecode,
	claimant_num AS i_claimant_num,
	-- *INF*: :UDF.DEFAULT_VALUE_FOR_STRINGS(i_claimant_num)
	UDF_DEFAULT_VALUE_FOR_STRINGS(i_claimant_num) AS claimant_num,
	RateEffectiveDate,
	-- *INF*: iif(i_ExperienceModificationFactor=0 and Split_Period_Code='0',i_PolicyEffectiveDate,RateEffectiveDate)
	IFF(
	    i_ExperienceModificationFactor = 0 and Split_Period_Code = '0', i_PolicyEffectiveDate,
	    RateEffectiveDate
	) AS o_RateEffectiveDate,
	Split_Period_Code,
	-- *INF*: iif(isnull(in_OccupationDescription),'N/A',in_OccupationDescription)
	IFF(in_OccupationDescription IS NULL, 'N/A', in_OccupationDescription) AS OccupationDescription,
	-- *INF*: iif(isnull(in_WeeklyWageAmount),0,in_WeeklyWageAmount)
	IFF(in_WeeklyWageAmount IS NULL, 0, in_WeeklyWageAmount) AS WeeklyWageAmount,
	-- *INF*: iif(isnull(in_EmployerAttorneyFees),0,in_EmployerAttorneyFees)
	IFF(in_EmployerAttorneyFees IS NULL, 0, in_EmployerAttorneyFees) AS EmployerAttorneyFees,
	MaxExperienceModificationFactor,
	o_SplitPeriodCodeIndicator,
	o_MaxModFactorSplitPolicyCode AS MaxExpModFactorForSplitPeriodCode
	FROM JNRTRANS_AllRecordsAndMaxModFactor
),
WorkWCSTATExtract AS (

	------------ PRE SQL ----------
	@{pipeline().parameters.DELETE_PRESQL}
	-------------------------------


	INSERT INTO WorkWCSTATExtract
	(AuditId, CreatedDate, EDWPremiumMasterCalculationPKId, EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, EstimatedAuditCode, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, LossSubjectToDeductibleCode, BasisOfDeductibleCalculationCode, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, PremiumMasterClassCode, ExperienceModificationFactor, ExperienceModificationEffectiveDate, Exposure, PremiumMasterDirectWrittenPremiumAmount, ManualChargedRate, LossMasterClassCode, ClaimLossDate, ClaimNumber, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, CauseOfLoss, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, SubjectPremiumTotal, StandarPremiumTotal, CorrectionSeqNumber, ReplacementReportCode, CorrectionTypeCode, TypeOfNonStandardIdCode, PreviousReportLevelCodeReportNumber, UpdateTypeCode, TypeOfLoss, TypeOfClaim, TypeOfSettlement, ManagedCareOrganizationType, VocationalRehabIndicator, LumpSumIndicator, FraudulentClaimCode, ClaimantNumber, RateEffectiveDate, SplitPeriodCode, OccupationDescription, WeeklyWageAmount, EmployerAttorneyFees)
	SELECT 
	o_AuditID AS AUDITID, 
	o_CreateDate AS CREATEDDATE, 
	EDWPREMIUMMASTERCALCULATIONPKID, 
	EDWLOSSMASTERCALCULATIONPKID, 
	TYPEBUREAUCODE, 
	PREMIUMMASTERRUNDATE, 
	LOSSMASTERRUNDATE, 
	BUREAUCOMPANYCODE, 
	POLICYKEY, 
	STATEPROVINCECODE, 
	POLICYEFFECTIVEDATE, 
	POLICYENDDATE, 
	INTERSTATERISKID, 
	EMPLOYEELEASINGCODE, 
	STATERATINGEFFECTIVEDATE, 
	FEDERALTAXID, 
	THREEYEARFIXEDRATEPOLICYINDICATOR, 
	MULTISTATEPOLICYINDICATOR, 
	INTERSTATERATEDPOLICYINDICATOR, 
	ESTIMATEDAUDITCODE, 
	RETROSPECTIVERATEDPOLICYINDICATOR, 
	CANCELLEDMIDTERMPOLICYINDICATOR, 
	MANAGEDCAREORGANIZATIONPOLICYINDICATOR, 
	TYPEOFCOVERAGEIDCODE, 
	TYPEOFPLAN, 
	LossesSubjectToDeductibleCode AS LOSSSUBJECTTODEDUCTIBLECODE, 
	BASISOFDEDUCTIBLECALCULATIONCODE, 
	DEDUCTIBLEAMOUNTPERCLAIMACCIDENT, 
	o_InsuredName AS INSUREDNAME, 
	WCSTATADDRESS, 
	PREMIUMMASTERCLASSCODE, 
	o_ExperienceModificationFactor AS EXPERIENCEMODIFICATIONFACTOR, 
	EXPERIENCEMODIFICATIONEFFECTIVEDATE, 
	o_Exposure AS EXPOSURE, 
	o_PremiumMasterDirectWrittenPremiumAmount AS PREMIUMMASTERDIRECTWRITTENPREMIUMAMOUNT, 
	MANUALCHARGEDRATE, 
	LOSSMASTERCLASSCODE, 
	CLAIMLOSSDATE, 
	CLAIMNUMBER, 
	CLAIMOCCURRENCESTATUSCODE, 
	o_InjuryTypecode AS INJURYTYPECODE, 
	CATASTROPHECODE, 
	INCURREDINDEMNITYAMOUNT, 
	INCURREDMEDICALAMOUNT, 
	CAUSEOFLOSS, 
	TYPEOFRECOVERYCODE, 
	JURISDICTIONSTATECODE, 
	BODYPARTCODE, 
	NATUREOFINJURYCODE, 
	CAUSEOFINJURYCODE, 
	PAIDINDEMNITYAMOUNT, 
	PAIDMEDICALAMOUNT, 
	DEDUCTIBLEREIMBURSEMENTAMOUNT, 
	PAIDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	INCURREDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	SUBJECTPREMIUMTOTAL, 
	STANDARPREMIUMTOTAL, 
	CORRECTIONSEQNUMBER, 
	REPLACEMENTREPORTCODE, 
	CORRECTIONTYPECODE, 
	TYPEOFNONSTANDARDIDCODE, 
	PREVIOUSREPORTLEVELCODEREPORTNUMBER, 
	UPDATETYPECODE, 
	TYPEOFLOSS, 
	TYPEOFCLAIM, 
	TYPEOFSETTLEMENT, 
	MANAGEDCAREORGANIZATIONTYPE, 
	VOCATIONALREHABINDICATOR, 
	LUMPSUMINDICATOR, 
	FRAUDULENTCLAIMCODE, 
	claimant_num AS CLAIMANTNUMBER, 
	o_RateEffectiveDate AS RATEEFFECTIVEDATE, 
	Split_Period_Code AS SPLITPERIODCODE, 
	OCCUPATIONDESCRIPTION, 
	WEEKLYWAGEAMOUNT, 
	EMPLOYERATTORNEYFEES
	FROM EXP_Prem
),