WITH
SQ_WorkWCSTATExtract AS (
	SELECT
		WorkWCSTATExtractId,
		AuditId,
		CreatedDate,
		EDWPremiumMasterCalculationPKId,
		EDWLossMasterCalculationPKId,
		TypeBureauCode,
		PremiumMasterRunDate,
		LossMasterRunDate,
		BureauCompanyCode,
		PolicyKey,
		StateProvinceCode,
		PolicyEffectiveDate,
		PolicyEndDate,
		InterstateRiskId,
		EmployeeLeasingCode,
		StateRatingEffectiveDate,
		FederalTaxId,
		ThreeYearFixedRatePolicyIndicator,
		MultistatePolicyIndicator,
		InterstateRatedPolicyIndicator,
		EstimatedAuditCode,
		RetrospectiveratedPolicyIndicator,
		CancelledMidTermPolicyIndicator,
		ManagedCareOrganizationPolicyIndicator,
		TypeOfCoverageIdCode,
		TypeOfPlan,
		LossSubjectToDeductibleCode,
		BasisOfDeductibleCalculationCode,
		DeductibleAmountPerClaimAccident,
		InsuredName,
		WCSTATAddress,
		PremiumMasterClassCode,
		ExperienceModificationFactor,
		ExperienceModificationEffectiveDate,
		Exposure,
		PremiumMasterDirectWrittenPremiumAmount,
		ManualChargedRate,
		LossMasterClassCode,
		ClaimLossDate,
		ClaimNumber,
		ClaimOccurrenceStatusCode,
		InjuryTypeCode,
		CatastropheCode,
		IncurredIndemnityAmount,
		IncurredMedicalAmount,
		CauseOfLoss,
		TypeOfRecoveryCode,
		JurisdictionStateCode,
		BodyPartCode,
		NatureOfInjuryCode,
		CauseOfInjuryCode,
		PaidIndemnityAmount,
		PaidMedicalAmount,
		DeductibleReimbursementAmount,
		PaidAllocatedLossAdjustmentExpenseAmount,
		IncurredAllocatedLossAdjustmentExpenseAmount,
		SubjectPremiumTotal,
		StandarPremiumTotal,
		CorrectionSeqNumber,
		ReplacementReportCode,
		CorrectionTypeCode,
		TypeOfNonStandardIdCode,
		PreviousReportLevelCodeReportNumber,
		UpdateTypeCode,
		TypeOfLoss,
		TypeOfClaim,
		TypeOfSettlement,
		ManagedCareOrganizationType,
		VocationalRehabIndicator,
		LumpSumIndicator,
		FraudulentClaimCode,
		ClaimantNumber,
		RateEffectiveDate,
		SplitPeriodCode,
		OccupationDescription,
		WeeklyWageAmount,
		EmployerAttorneyFees AS EmployersAttorneyFees
	FROM WorkWCSTATExtract
	WHERE ((WorkWCSTATExtract.EDWLossMasterCalculationPKId = -1 and (DATEDIFF(MM,WorkWCSTATExtract.PolicyEffectiveDate, DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) +@{pipeline().parameters.NUM_OF_MONTHS}, 0) ) = 18))
	OR WorkWCSTATExtract.EDWLossMasterCalculationPKId != -1)
	AND WorkWCSTATExtract.AuditId= @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Cleansing AS (
	SELECT
	WorkWCSTATExtractId,
	AuditId,
	CreatedDate,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode AS i_TypeBureauCode,
	-- *INF*: RTRIM(LTRIM(i_TypeBureauCode))
	RTRIM(LTRIM(i_TypeBureauCode)) AS o_TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode AS i_BureauCompanyCode,
	-- *INF*: RTRIM(LTRIM(i_BureauCompanyCode))
	RTRIM(LTRIM(i_BureauCompanyCode)) AS o_BureauCompanyCode,
	PolicyKey AS i_PolicyKey,
	-- *INF*: RTRIM(LTRIM(i_PolicyKey))
	RTRIM(LTRIM(i_PolicyKey)) AS o_PolicyKey,
	StateProvinceCode AS i_StateProvinceCode,
	-- *INF*: RTRIM(LTRIM(i_StateProvinceCode))
	RTRIM(LTRIM(i_StateProvinceCode)) AS o_StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId AS i_InterstateRiskId,
	-- *INF*: RTRIM(LTRIM(i_InterstateRiskId))
	RTRIM(LTRIM(i_InterstateRiskId)) AS o_InterstateRiskId,
	EmployeeLeasingCode AS i_EmployeeLeasingCode,
	-- *INF*: RTRIM(LTRIM(i_EmployeeLeasingCode))
	RTRIM(LTRIM(i_EmployeeLeasingCode)) AS o_EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId AS i_FederalTaxId,
	-- *INF*: RTRIM(LTRIM(i_FederalTaxId))
	RTRIM(LTRIM(i_FederalTaxId)) AS o_FederalTaxId,
	ThreeYearFixedRatePolicyIndicator AS i_ThreeYearFixedRatePolicyIndicator,
	-- *INF*: IIF(i_ThreeYearFixedRatePolicyIndicator='T',1,0)
	IFF(i_ThreeYearFixedRatePolicyIndicator = 'T', 1, 0) AS o_ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator AS i_MultistatePolicyIndicator,
	-- *INF*: IIF(i_MultistatePolicyIndicator='T',1,0)
	IFF(i_MultistatePolicyIndicator = 'T', 1, 0) AS o_MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator AS i_InterstateRatedPolicyIndicator,
	-- *INF*: IIF(i_InterstateRatedPolicyIndicator='T',1,0)
	IFF(i_InterstateRatedPolicyIndicator = 'T', 1, 0) AS o_InterstateRatedPolicyIndicator,
	EstimatedAuditCode,
	RetrospectiveratedPolicyIndicator AS i_RetrospectiveratedPolicyIndicator,
	-- *INF*: IIF(i_RetrospectiveratedPolicyIndicator='T',1,0)
	IFF(i_RetrospectiveratedPolicyIndicator = 'T', 1, 0) AS o_RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator AS i_CancelledMidTermPolicyIndicator,
	-- *INF*: IIF(i_CancelledMidTermPolicyIndicator='T',1,0)
	IFF(i_CancelledMidTermPolicyIndicator = 'T', 1, 0) AS o_CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator AS i_ManagedCareOrganizationPolicyIndicator,
	-- *INF*: IIF(i_ManagedCareOrganizationPolicyIndicator='T',1,0)
	IFF(i_ManagedCareOrganizationPolicyIndicator = 'T', 1, 0) AS o_ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode AS i_TypeOfCoverageIdCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfCoverageIdCode))
	RTRIM(LTRIM(i_TypeOfCoverageIdCode)) AS o_TypeOfCoverageIdCode,
	TypeOfPlan AS i_TypeOfPlan,
	-- *INF*: RTRIM(LTRIM(i_TypeOfPlan))
	RTRIM(LTRIM(i_TypeOfPlan)) AS o_TypeOfPlan,
	LossSubjectToDeductibleCode AS i_LossSubjectToDeductibleCode,
	-- *INF*: RTRIM(LTRIM(i_LossSubjectToDeductibleCode))
	RTRIM(LTRIM(i_LossSubjectToDeductibleCode)) AS o_LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode AS i_BasisOfDeductibleCalculationCode,
	-- *INF*: RTRIM(LTRIM(i_BasisOfDeductibleCalculationCode))
	RTRIM(LTRIM(i_BasisOfDeductibleCalculationCode)) AS o_BasisOfDeductibleCalculationCode,
	DeductibleAmountPerClaimAccident AS i_DeductibleAmountPerClaimAccident,
	-- *INF*: RTRIM(LTRIM(i_DeductibleAmountPerClaimAccident))
	RTRIM(LTRIM(i_DeductibleAmountPerClaimAccident)) AS o_DeductibleAmountPerClaimAccident,
	InsuredName AS i_InsuredName,
	-- *INF*: RTRIM(LTRIM(i_InsuredName))
	RTRIM(LTRIM(i_InsuredName)) AS o_InsuredName,
	WCSTATAddress AS i_WCSTATAddress,
	-- *INF*: RTRIM(LTRIM(i_WCSTATAddress))
	RTRIM(LTRIM(i_WCSTATAddress)) AS o_WCSTATAddress,
	PremiumMasterClassCode AS i_PremiumMasterClassCode,
	-- *INF*: RTRIM(LTRIM(i_PremiumMasterClassCode))
	RTRIM(LTRIM(i_PremiumMasterClassCode)) AS o_PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode AS i_LossMasterClassCode,
	-- *INF*: RTRIM(LTRIM(i_LossMasterClassCode))
	RTRIM(LTRIM(i_LossMasterClassCode)) AS o_LossMasterClassCode,
	ClaimLossDate,
	ClaimNumber AS i_ClaimNumber,
	-- *INF*: RTRIM(LTRIM(i_ClaimNumber))
	RTRIM(LTRIM(i_ClaimNumber)) AS o_ClaimNumber,
	ClaimOccurrenceStatusCode AS i_ClaimOccurrenceStatusCode,
	-- *INF*: RTRIM(LTRIM(i_ClaimOccurrenceStatusCode))
	RTRIM(LTRIM(i_ClaimOccurrenceStatusCode)) AS o_ClaimOccurrenceStatusCode,
	InjuryTypeCode AS i_InjuryTypeCode,
	-- *INF*: RTRIM(LTRIM(i_InjuryTypeCode))
	RTRIM(LTRIM(i_InjuryTypeCode)) AS o_InjuryTypeCode,
	CatastropheCode AS i_CatastropheCode,
	-- *INF*: RTRIM(LTRIM(i_CatastropheCode))
	RTRIM(LTRIM(i_CatastropheCode)) AS o_CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	TypeOfRecoveryCode AS i_TypeOfRecoveryCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfRecoveryCode))
	RTRIM(LTRIM(i_TypeOfRecoveryCode)) AS o_TypeOfRecoveryCode,
	JurisdictionStateCode AS i_JurisdictionStateCode,
	-- *INF*: RTRIM(LTRIM(i_JurisdictionStateCode))
	RTRIM(LTRIM(i_JurisdictionStateCode)) AS o_JurisdictionStateCode,
	BodyPartCode AS i_BodyPartCode,
	-- *INF*: RTRIM(LTRIM(i_BodyPartCode))
	RTRIM(LTRIM(i_BodyPartCode)) AS o_BodyPartCode,
	NatureOfInjuryCode AS i_NatureOfInjuryCode,
	-- *INF*: RTRIM(LTRIM(i_NatureOfInjuryCode))
	RTRIM(LTRIM(i_NatureOfInjuryCode)) AS o_NatureOfInjuryCode,
	CauseOfInjuryCode AS i_CauseOfInjuryCode,
	-- *INF*: RTRIM(LTRIM(i_CauseOfInjuryCode))
	RTRIM(LTRIM(i_CauseOfInjuryCode)) AS o_CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	CorrectionSeqNumber,
	TypeOfNonStandardIdCode AS i_TypeOfNonStandardIdCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfNonStandardIdCode))
	RTRIM(LTRIM(i_TypeOfNonStandardIdCode)) AS o_TypeOfNonStandardIdCode,
	PreviousReportLevelCodeReportNumber AS i_PreviousReportLevelCodeReportNumber,
	-- *INF*: RTRIM(LTRIM(i_PreviousReportLevelCodeReportNumber))
	RTRIM(LTRIM(i_PreviousReportLevelCodeReportNumber)) AS o_PreviousReportLevelCodeReportNumber,
	TypeOfLoss AS i_TypeOfLoss,
	-- *INF*: RTRIM(LTRIM(i_TypeOfLoss))
	RTRIM(LTRIM(i_TypeOfLoss)) AS o_TypeOfLoss,
	TypeOfClaim AS i_TypeOfClaim,
	-- *INF*: RTRIM(LTRIM(i_TypeOfClaim))
	RTRIM(LTRIM(i_TypeOfClaim)) AS o_TypeOfClaim,
	TypeOfSettlement AS i_TypeOfSettlement,
	-- *INF*: RTRIM(LTRIM(i_TypeOfSettlement))
	RTRIM(LTRIM(i_TypeOfSettlement)) AS o_TypeOfSettlement,
	ManagedCareOrganizationType AS i_ManagedCareOrganizationType,
	-- *INF*: RTRIM(LTRIM(i_ManagedCareOrganizationType))
	RTRIM(LTRIM(i_ManagedCareOrganizationType)) AS o_ManagedCareOrganizationType,
	VocationalRehabIndicator,
	LumpSumIndicator AS i_LumpSumIndicator,
	-- *INF*: RTRIM(LTRIM(i_LumpSumIndicator))
	RTRIM(LTRIM(i_LumpSumIndicator)) AS o_LumpSumIndicator,
	FraudulentClaimCode AS i_FraudulentClaimCode,
	-- *INF*: RTRIM(LTRIM(i_FraudulentClaimCode))
	RTRIM(LTRIM(i_FraudulentClaimCode)) AS o_FraudulentClaimCode,
	ClaimantNumber AS i_ClaimantNumber,
	-- *INF*: RTRIM(LTRIM(i_ClaimantNumber))
	RTRIM(LTRIM(i_ClaimantNumber)) AS o_ClaimantNumber,
	RateEffectiveDate,
	SplitPeriodCode,
	OccupationDescription,
	WeeklyWageAmount,
	EmployersAttorneyFees
	FROM SQ_WorkWCSTATExtract
),
EXP_Append_FileName AS (
	SELECT
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS v_RunDate,
	'WCSTAT_' || v_RunDate || '.CSV' AS FileName,
	WorkWCSTATExtractId,
	AuditId,
	CreatedDate,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	o_TypeBureauCode AS TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	o_BureauCompanyCode AS BureauCompanyCode,
	o_PolicyKey AS PolicyKey,
	o_StateProvinceCode AS StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	o_InterstateRiskId AS InterstateRiskId,
	o_EmployeeLeasingCode AS EmployeeLeasingCode,
	StateRatingEffectiveDate,
	o_FederalTaxId AS FederalTaxId,
	o_ThreeYearFixedRatePolicyIndicator AS ThreeYearFixedRatePolicyIndicator,
	o_MultistatePolicyIndicator AS MultistatePolicyIndicator,
	o_InterstateRatedPolicyIndicator AS InterstateRatedPolicyIndicator,
	EstimatedAuditCode,
	o_RetrospectiveratedPolicyIndicator AS RetrospectiveratedPolicyIndicator,
	o_CancelledMidTermPolicyIndicator AS CancelledMidTermPolicyIndicator,
	o_ManagedCareOrganizationPolicyIndicator AS ManagedCareOrganizationPolicyIndicator,
	o_TypeOfCoverageIdCode AS TypeOfCoverageIdCode,
	o_TypeOfPlan AS TypeOfPlan,
	o_LossesSubjectToDeductibleCode AS LossesSubjectToDeductibleCode,
	o_BasisOfDeductibleCalculationCode AS BasisOfDeductibleCalculationCode,
	o_DeductibleAmountPerClaimAccident AS DeductibleAmountPerClaimAccident,
	o_InsuredName AS InsuredName,
	o_WCSTATAddress AS WCSTATAddress,
	o_PremiumMasterClassCode AS PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	o_LossMasterClassCode AS LossMasterClassCode,
	ClaimLossDate,
	o_ClaimNumber AS ClaimNumber,
	o_ClaimantNumber AS ClaimantNumber,
	o_ClaimOccurrenceStatusCode AS ClaimOccurrenceStatusCode,
	o_InjuryTypeCode AS InjuryTypeCode,
	o_CatastropheCode AS CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	o_TypeOfRecoveryCode AS TypeOfRecoveryCode,
	o_JurisdictionStateCode AS JurisdictionStateCode,
	o_BodyPartCode AS BodyPartCode,
	o_NatureOfInjuryCode AS NatureOfInjuryCode,
	o_CauseOfInjuryCode AS CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	CorrectionSeqNumber,
	o_TypeOfNonStandardIdCode AS TypeOfNonStandardIdCode,
	o_PreviousReportLevelCodeReportNumber AS PreviousReportLevelCodeReportNumber,
	o_TypeOfLoss AS TypeOfLoss,
	o_TypeOfClaim AS TypeOfClaim,
	o_TypeOfSettlement AS TypeOfSettlement,
	o_ManagedCareOrganizationType AS ManagedCareOrganizationType,
	VocationalRehabIndicator,
	o_LumpSumIndicator AS LumpSumIndicator,
	o_FraudulentClaimCode AS FraudulentClaimCode,
	RateEffectiveDate,
	SplitPeriodCode,
	OccupationDescription,
	WeeklyWageAmount,
	EmployersAttorneyFees
	FROM EXP_Cleansing
),
SRT_MainFile AS (
	SELECT
	FileName, 
	WorkWCSTATExtractId, 
	AuditId, 
	CreatedDate, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	EstimatedAuditCode, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimNumber, 
	ClaimantNumber, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	CorrectionSeqNumber, 
	TypeOfNonStandardIdCode, 
	PreviousReportLevelCodeReportNumber, 
	TypeOfLoss, 
	TypeOfClaim, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	VocationalRehabIndicator, 
	LumpSumIndicator, 
	FraudulentClaimCode, 
	RateEffectiveDate, 
	SplitPeriodCode, 
	OccupationDescription, 
	WeeklyWageAmount, 
	EmployersAttorneyFees
	FROM EXP_Append_FileName
	ORDER BY PolicyKey ASC, ClaimLossDate ASC
),
WCSTATFlatFile AS (
	INSERT INTO WCSTATFlatFile
	(FileName, WorkWCSTATExtractId, AuditId, CreatedDate, EDWPremiumMasterCalculationPKId, EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, EstimatedAuditCode, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, LossesSubjectToDeductibleCode, BasisOfDeductibleCalculationCode, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, PremiumMasterClassCode, ExperienceModificationFactor, ExperienceModificationEffectiveDate, RateEffectiveDate, Exposure, PremiumMasterDirectWrittenPremiumAmount, ManualChargedRate, SplitPeriodCode, LossMasterClassCode, ClaimLossDate, ClaimNumber, ClaimantNumber, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, CorrectionSeqNumber, TypeOfNonStandardIdCode, PreviousReportLevelCodeReportNumber, TypeOfLoss, TypeOfClaim, TypeOfSettlement, ManagedCareOrganizationType, VocationalRehabIndicator, LumpSumIndicator, FraudulentClaimCode, OccupationDescription, WeeklyWageAmount, EmployersAttorneyFees)
	SELECT 
	FILENAME, 
	WORKWCSTATEXTRACTID, 
	AUDITID, 
	CREATEDDATE, 
	EDWPREMIUMMASTERCALCULATIONPKID, 
	EDWLOSSMASTERCALCULATIONPKID, 
	TYPEBUREAUCODE, 
	PREMIUMMASTERRUNDATE, 
	LOSSMASTERRUNDATE, 
	BUREAUCOMPANYCODE, 
	POLICYKEY, 
	STATEPROVINCECODE, 
	POLICYEFFECTIVEDATE, 
	POLICYENDDATE, 
	INTERSTATERISKID, 
	EMPLOYEELEASINGCODE, 
	STATERATINGEFFECTIVEDATE, 
	FEDERALTAXID, 
	THREEYEARFIXEDRATEPOLICYINDICATOR, 
	MULTISTATEPOLICYINDICATOR, 
	INTERSTATERATEDPOLICYINDICATOR, 
	ESTIMATEDAUDITCODE, 
	RETROSPECTIVERATEDPOLICYINDICATOR, 
	CANCELLEDMIDTERMPOLICYINDICATOR, 
	MANAGEDCAREORGANIZATIONPOLICYINDICATOR, 
	TYPEOFCOVERAGEIDCODE, 
	TYPEOFPLAN, 
	LOSSESSUBJECTTODEDUCTIBLECODE, 
	BASISOFDEDUCTIBLECALCULATIONCODE, 
	DEDUCTIBLEAMOUNTPERCLAIMACCIDENT, 
	INSUREDNAME, 
	WCSTATADDRESS, 
	PREMIUMMASTERCLASSCODE, 
	EXPERIENCEMODIFICATIONFACTOR, 
	EXPERIENCEMODIFICATIONEFFECTIVEDATE, 
	RATEEFFECTIVEDATE, 
	EXPOSURE, 
	PREMIUMMASTERDIRECTWRITTENPREMIUMAMOUNT, 
	MANUALCHARGEDRATE, 
	SPLITPERIODCODE, 
	LOSSMASTERCLASSCODE, 
	CLAIMLOSSDATE, 
	CLAIMNUMBER, 
	CLAIMANTNUMBER, 
	CLAIMOCCURRENCESTATUSCODE, 
	INJURYTYPECODE, 
	CATASTROPHECODE, 
	INCURREDINDEMNITYAMOUNT, 
	INCURREDMEDICALAMOUNT, 
	TYPEOFRECOVERYCODE, 
	JURISDICTIONSTATECODE, 
	BODYPARTCODE, 
	NATUREOFINJURYCODE, 
	CAUSEOFINJURYCODE, 
	PAIDINDEMNITYAMOUNT, 
	PAIDMEDICALAMOUNT, 
	DEDUCTIBLEREIMBURSEMENTAMOUNT, 
	PAIDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	INCURREDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	CORRECTIONSEQNUMBER, 
	TYPEOFNONSTANDARDIDCODE, 
	PREVIOUSREPORTLEVELCODEREPORTNUMBER, 
	TYPEOFLOSS, 
	TYPEOFCLAIM, 
	TYPEOFSETTLEMENT, 
	MANAGEDCAREORGANIZATIONTYPE, 
	VOCATIONALREHABINDICATOR, 
	LUMPSUMINDICATOR, 
	FRAUDULENTCLAIMCODE, 
	OCCUPATIONDESCRIPTION, 
	WEEKLYWAGEAMOUNT, 
	EMPLOYERSATTORNEYFEES
	FROM SRT_MainFile
),
SQ_WorkWCSTATExtractCorrectionFile AS (
	SELECT
		WorkWCSTATExtractId,
		AuditId,
		CreatedDate,
		EDWPremiumMasterCalculationPKId,
		EDWLossMasterCalculationPKId,
		TypeBureauCode,
		PremiumMasterRunDate,
		LossMasterRunDate,
		BureauCompanyCode,
		PolicyKey,
		StateProvinceCode,
		PolicyEffectiveDate,
		PolicyEndDate,
		InterstateRiskId,
		EmployeeLeasingCode,
		StateRatingEffectiveDate,
		FederalTaxId,
		ThreeYearFixedRatePolicyIndicator,
		MultistatePolicyIndicator,
		InterstateRatedPolicyIndicator,
		EstimatedAuditCode,
		RetrospectiveratedPolicyIndicator,
		CancelledMidTermPolicyIndicator,
		ManagedCareOrganizationPolicyIndicator,
		TypeOfCoverageIdCode,
		TypeOfPlan,
		LossSubjectToDeductibleCode,
		BasisOfDeductibleCalculationCode,
		DeductibleAmountPerClaimAccident,
		InsuredName,
		WCSTATAddress,
		PremiumMasterClassCode,
		ExperienceModificationFactor,
		ExperienceModificationEffectiveDate,
		Exposure,
		PremiumMasterDirectWrittenPremiumAmount,
		ManualChargedRate,
		LossMasterClassCode,
		ClaimLossDate,
		ClaimNumber,
		ClaimOccurrenceStatusCode,
		InjuryTypeCode,
		CatastropheCode,
		IncurredIndemnityAmount,
		IncurredMedicalAmount,
		CauseOfLoss,
		TypeOfRecoveryCode,
		JurisdictionStateCode,
		BodyPartCode,
		NatureOfInjuryCode,
		CauseOfInjuryCode,
		PaidIndemnityAmount,
		PaidMedicalAmount,
		DeductibleReimbursementAmount,
		PaidAllocatedLossAdjustmentExpenseAmount,
		IncurredAllocatedLossAdjustmentExpenseAmount,
		SubjectPremiumTotal,
		StandarPremiumTotal,
		CorrectionSeqNumber,
		ReplacementReportCode,
		CorrectionTypeCode,
		TypeOfNonStandardIdCode,
		PreviousReportLevelCodeReportNumber,
		UpdateTypeCode,
		TypeOfLoss,
		TypeOfClaim,
		TypeOfSettlement,
		ManagedCareOrganizationType,
		VocationalRehabIndicator,
		LumpSumIndicator,
		FraudulentClaimCode,
		ClaimantNumber,
		RateEffectiveDate,
		SplitPeriodCode,
		OccupationDescription,
		WeeklyWageAmount,
		EmployerAttorneyFees AS EmployersAttorneyFees
	FROM WorkWCSTATExtract1
	WHERE (WorkWCSTATExtract.EDWPremiumMasterCalculationPKId != -1 and  ((DATEDIFF(MM,WorkWCSTATExtract.PolicyEffectiveDate, 
	DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) + @{pipeline().parameters.NUM_OF_MONTHS}, 0) )) > 18
	))
	AND WorkWCSTATExtract.AuditId= @{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID}
	@{pipeline().parameters.WHERE_CLAUSE_CORRECTION_FILE}
),
EXP_Cleansing1 AS (
	SELECT
	WorkWCSTATExtractId,
	AuditId,
	CreatedDate,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	TypeBureauCode AS i_TypeBureauCode,
	-- *INF*: RTRIM(LTRIM(i_TypeBureauCode))
	RTRIM(LTRIM(i_TypeBureauCode)) AS o_TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	BureauCompanyCode AS i_BureauCompanyCode,
	-- *INF*: RTRIM(LTRIM(i_BureauCompanyCode))
	RTRIM(LTRIM(i_BureauCompanyCode)) AS o_BureauCompanyCode,
	PolicyKey AS i_PolicyKey,
	-- *INF*: RTRIM(LTRIM(i_PolicyKey))
	RTRIM(LTRIM(i_PolicyKey)) AS o_PolicyKey,
	StateProvinceCode AS i_StateProvinceCode,
	-- *INF*: RTRIM(LTRIM(i_StateProvinceCode))
	RTRIM(LTRIM(i_StateProvinceCode)) AS o_StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	InterstateRiskId AS i_InterstateRiskId,
	-- *INF*: RTRIM(LTRIM(i_InterstateRiskId))
	RTRIM(LTRIM(i_InterstateRiskId)) AS o_InterstateRiskId,
	EmployeeLeasingCode AS i_EmployeeLeasingCode,
	-- *INF*: RTRIM(LTRIM(i_EmployeeLeasingCode))
	RTRIM(LTRIM(i_EmployeeLeasingCode)) AS o_EmployeeLeasingCode,
	StateRatingEffectiveDate,
	FederalTaxId AS i_FederalTaxId,
	-- *INF*: RTRIM(LTRIM(i_FederalTaxId))
	RTRIM(LTRIM(i_FederalTaxId)) AS o_FederalTaxId,
	ThreeYearFixedRatePolicyIndicator AS i_ThreeYearFixedRatePolicyIndicator,
	-- *INF*: IIF(i_ThreeYearFixedRatePolicyIndicator='T',1,0)
	IFF(i_ThreeYearFixedRatePolicyIndicator = 'T', 1, 0) AS o_ThreeYearFixedRatePolicyIndicator,
	MultistatePolicyIndicator AS i_MultistatePolicyIndicator,
	-- *INF*: IIF(i_MultistatePolicyIndicator='T',1,0)
	IFF(i_MultistatePolicyIndicator = 'T', 1, 0) AS o_MultistatePolicyIndicator,
	InterstateRatedPolicyIndicator AS i_InterstateRatedPolicyIndicator,
	-- *INF*: IIF(i_InterstateRatedPolicyIndicator='T',1,0)
	IFF(i_InterstateRatedPolicyIndicator = 'T', 1, 0) AS o_InterstateRatedPolicyIndicator,
	EstimatedAuditCode,
	RetrospectiveratedPolicyIndicator AS i_RetrospectiveratedPolicyIndicator,
	-- *INF*: IIF(i_RetrospectiveratedPolicyIndicator='T',1,0)
	IFF(i_RetrospectiveratedPolicyIndicator = 'T', 1, 0) AS o_RetrospectiveratedPolicyIndicator,
	CancelledMidTermPolicyIndicator AS i_CancelledMidTermPolicyIndicator,
	-- *INF*: IIF(i_CancelledMidTermPolicyIndicator='T',1,0)
	IFF(i_CancelledMidTermPolicyIndicator = 'T', 1, 0) AS o_CancelledMidTermPolicyIndicator,
	ManagedCareOrganizationPolicyIndicator AS i_ManagedCareOrganizationPolicyIndicator,
	-- *INF*: IIF(i_ManagedCareOrganizationPolicyIndicator='T',1,0)
	IFF(i_ManagedCareOrganizationPolicyIndicator = 'T', 1, 0) AS o_ManagedCareOrganizationPolicyIndicator,
	TypeOfCoverageIdCode AS i_TypeOfCoverageIdCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfCoverageIdCode))
	RTRIM(LTRIM(i_TypeOfCoverageIdCode)) AS o_TypeOfCoverageIdCode,
	TypeOfPlan AS i_TypeOfPlan,
	-- *INF*: RTRIM(LTRIM(i_TypeOfPlan))
	RTRIM(LTRIM(i_TypeOfPlan)) AS o_TypeOfPlan,
	LossSubjectToDeductibleCode AS i_LossSubjectToDeductibleCode,
	-- *INF*: RTRIM(LTRIM(i_LossSubjectToDeductibleCode))
	RTRIM(LTRIM(i_LossSubjectToDeductibleCode)) AS o_LossesSubjectToDeductibleCode,
	BasisOfDeductibleCalculationCode AS i_BasisOfDeductibleCalculationCode,
	-- *INF*: RTRIM(LTRIM(i_BasisOfDeductibleCalculationCode))
	RTRIM(LTRIM(i_BasisOfDeductibleCalculationCode)) AS o_BasisOfDeductibleCalculationCode,
	DeductibleAmountPerClaimAccident AS i_DeductibleAmountPerClaimAccident,
	-- *INF*: RTRIM(LTRIM(i_DeductibleAmountPerClaimAccident))
	RTRIM(LTRIM(i_DeductibleAmountPerClaimAccident)) AS o_DeductibleAmountPerClaimAccident,
	InsuredName AS i_InsuredName,
	-- *INF*: RTRIM(LTRIM(i_InsuredName))
	RTRIM(LTRIM(i_InsuredName)) AS o_InsuredName,
	WCSTATAddress AS i_WCSTATAddress,
	-- *INF*: RTRIM(LTRIM(i_WCSTATAddress))
	RTRIM(LTRIM(i_WCSTATAddress)) AS o_WCSTATAddress,
	PremiumMasterClassCode AS i_PremiumMasterClassCode,
	-- *INF*: RTRIM(LTRIM(i_PremiumMasterClassCode))
	RTRIM(LTRIM(i_PremiumMasterClassCode)) AS o_PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	LossMasterClassCode AS i_LossMasterClassCode,
	-- *INF*: RTRIM(LTRIM(i_LossMasterClassCode))
	RTRIM(LTRIM(i_LossMasterClassCode)) AS o_LossMasterClassCode,
	ClaimLossDate,
	ClaimNumber AS i_ClaimNumber,
	-- *INF*: RTRIM(LTRIM(i_ClaimNumber))
	RTRIM(LTRIM(i_ClaimNumber)) AS o_ClaimNumber,
	ClaimOccurrenceStatusCode AS i_ClaimOccurrenceStatusCode,
	-- *INF*: RTRIM(LTRIM(i_ClaimOccurrenceStatusCode))
	RTRIM(LTRIM(i_ClaimOccurrenceStatusCode)) AS o_ClaimOccurrenceStatusCode,
	InjuryTypeCode AS i_InjuryTypeCode,
	-- *INF*: RTRIM(LTRIM(i_InjuryTypeCode))
	RTRIM(LTRIM(i_InjuryTypeCode)) AS o_InjuryTypeCode,
	CatastropheCode AS i_CatastropheCode,
	-- *INF*: RTRIM(LTRIM(i_CatastropheCode))
	RTRIM(LTRIM(i_CatastropheCode)) AS o_CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	TypeOfRecoveryCode AS i_TypeOfRecoveryCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfRecoveryCode))
	RTRIM(LTRIM(i_TypeOfRecoveryCode)) AS o_TypeOfRecoveryCode,
	JurisdictionStateCode AS i_JurisdictionStateCode,
	-- *INF*: RTRIM(LTRIM(i_JurisdictionStateCode))
	RTRIM(LTRIM(i_JurisdictionStateCode)) AS o_JurisdictionStateCode,
	BodyPartCode AS i_BodyPartCode,
	-- *INF*: RTRIM(LTRIM(i_BodyPartCode))
	RTRIM(LTRIM(i_BodyPartCode)) AS o_BodyPartCode,
	NatureOfInjuryCode AS i_NatureOfInjuryCode,
	-- *INF*: RTRIM(LTRIM(i_NatureOfInjuryCode))
	RTRIM(LTRIM(i_NatureOfInjuryCode)) AS o_NatureOfInjuryCode,
	CauseOfInjuryCode AS i_CauseOfInjuryCode,
	-- *INF*: RTRIM(LTRIM(i_CauseOfInjuryCode))
	RTRIM(LTRIM(i_CauseOfInjuryCode)) AS o_CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	CorrectionSeqNumber,
	TypeOfNonStandardIdCode AS i_TypeOfNonStandardIdCode,
	-- *INF*: RTRIM(LTRIM(i_TypeOfNonStandardIdCode))
	RTRIM(LTRIM(i_TypeOfNonStandardIdCode)) AS o_TypeOfNonStandardIdCode,
	PreviousReportLevelCodeReportNumber AS i_PreviousReportLevelCodeReportNumber,
	-- *INF*: RTRIM(LTRIM(i_PreviousReportLevelCodeReportNumber))
	RTRIM(LTRIM(i_PreviousReportLevelCodeReportNumber)) AS o_PreviousReportLevelCodeReportNumber,
	TypeOfLoss AS i_TypeOfLoss,
	-- *INF*: RTRIM(LTRIM(i_TypeOfLoss))
	RTRIM(LTRIM(i_TypeOfLoss)) AS o_TypeOfLoss,
	TypeOfClaim AS i_TypeOfClaim,
	-- *INF*: RTRIM(LTRIM(i_TypeOfClaim))
	RTRIM(LTRIM(i_TypeOfClaim)) AS o_TypeOfClaim,
	TypeOfSettlement AS i_TypeOfSettlement,
	-- *INF*: RTRIM(LTRIM(i_TypeOfSettlement))
	RTRIM(LTRIM(i_TypeOfSettlement)) AS o_TypeOfSettlement,
	ManagedCareOrganizationType AS i_ManagedCareOrganizationType,
	-- *INF*: RTRIM(LTRIM(i_ManagedCareOrganizationType))
	RTRIM(LTRIM(i_ManagedCareOrganizationType)) AS o_ManagedCareOrganizationType,
	VocationalRehabIndicator,
	LumpSumIndicator AS i_LumpSumIndicator,
	-- *INF*: RTRIM(LTRIM(i_LumpSumIndicator))
	RTRIM(LTRIM(i_LumpSumIndicator)) AS o_LumpSumIndicator,
	FraudulentClaimCode AS i_FraudulentClaimCode,
	-- *INF*: RTRIM(LTRIM(i_FraudulentClaimCode))
	RTRIM(LTRIM(i_FraudulentClaimCode)) AS o_FraudulentClaimCode,
	ClaimantNumber AS i_ClaimantNumber,
	-- *INF*: RTRIM(LTRIM(i_ClaimantNumber))
	RTRIM(LTRIM(i_ClaimantNumber)) AS o_ClaimantNumber,
	RateEffectiveDate,
	SplitPeriodCode,
	OccupationDescription,
	WeeklyWageAmount,
	EmployersAttorneyFees
	FROM SQ_WorkWCSTATExtractCorrectionFile
),
EXP_Append_FileName1 AS (
	SELECT
	-- *INF*: TO_CHAR(SYSDATE,'YYYYMMDD')
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS v_RunDate,
	'WCSTATCorrectionFile_' || v_RunDate || '.CSV' AS FileName,
	WorkWCSTATExtractId,
	AuditId,
	CreatedDate,
	EDWPremiumMasterCalculationPKId,
	EDWLossMasterCalculationPKId,
	o_TypeBureauCode AS TypeBureauCode,
	PremiumMasterRunDate,
	LossMasterRunDate,
	o_BureauCompanyCode AS BureauCompanyCode,
	o_PolicyKey AS PolicyKey,
	o_StateProvinceCode AS StateProvinceCode,
	PolicyEffectiveDate,
	PolicyEndDate,
	o_InterstateRiskId AS InterstateRiskId,
	o_EmployeeLeasingCode AS EmployeeLeasingCode,
	StateRatingEffectiveDate,
	o_FederalTaxId AS FederalTaxId,
	o_ThreeYearFixedRatePolicyIndicator AS ThreeYearFixedRatePolicyIndicator,
	o_MultistatePolicyIndicator AS MultistatePolicyIndicator,
	o_InterstateRatedPolicyIndicator AS InterstateRatedPolicyIndicator,
	EstimatedAuditCode,
	o_RetrospectiveratedPolicyIndicator AS RetrospectiveratedPolicyIndicator,
	o_CancelledMidTermPolicyIndicator AS CancelledMidTermPolicyIndicator,
	o_ManagedCareOrganizationPolicyIndicator AS ManagedCareOrganizationPolicyIndicator,
	o_TypeOfCoverageIdCode AS TypeOfCoverageIdCode,
	o_TypeOfPlan AS TypeOfPlan,
	o_LossesSubjectToDeductibleCode AS LossesSubjectToDeductibleCode,
	o_BasisOfDeductibleCalculationCode AS BasisOfDeductibleCalculationCode,
	o_DeductibleAmountPerClaimAccident AS DeductibleAmountPerClaimAccident,
	o_InsuredName AS InsuredName,
	o_WCSTATAddress AS WCSTATAddress,
	o_PremiumMasterClassCode AS PremiumMasterClassCode,
	ExperienceModificationFactor,
	ExperienceModificationEffectiveDate,
	Exposure,
	PremiumMasterDirectWrittenPremiumAmount,
	ManualChargedRate,
	o_LossMasterClassCode AS LossMasterClassCode,
	ClaimLossDate,
	o_ClaimNumber AS ClaimNumber,
	o_ClaimantNumber AS ClaimantNumber,
	o_ClaimOccurrenceStatusCode AS ClaimOccurrenceStatusCode,
	o_InjuryTypeCode AS InjuryTypeCode,
	o_CatastropheCode AS CatastropheCode,
	IncurredIndemnityAmount,
	IncurredMedicalAmount,
	o_TypeOfRecoveryCode AS TypeOfRecoveryCode,
	o_JurisdictionStateCode AS JurisdictionStateCode,
	o_BodyPartCode AS BodyPartCode,
	o_NatureOfInjuryCode AS NatureOfInjuryCode,
	o_CauseOfInjuryCode AS CauseOfInjuryCode,
	PaidIndemnityAmount,
	PaidMedicalAmount,
	DeductibleReimbursementAmount,
	PaidAllocatedLossAdjustmentExpenseAmount,
	IncurredAllocatedLossAdjustmentExpenseAmount,
	CorrectionSeqNumber,
	o_TypeOfNonStandardIdCode AS TypeOfNonStandardIdCode,
	o_PreviousReportLevelCodeReportNumber AS PreviousReportLevelCodeReportNumber,
	o_TypeOfLoss AS TypeOfLoss,
	o_TypeOfClaim AS TypeOfClaim,
	o_TypeOfSettlement AS TypeOfSettlement,
	o_ManagedCareOrganizationType AS ManagedCareOrganizationType,
	VocationalRehabIndicator,
	o_LumpSumIndicator AS LumpSumIndicator,
	o_FraudulentClaimCode AS FraudulentClaimCode,
	RateEffectiveDate,
	SplitPeriodCode,
	OccupationDescription,
	WeeklyWageAmount,
	EmployersAttorneyFees
	FROM EXP_Cleansing1
),
SRT_CorrectionFile AS (
	SELECT
	FileName, 
	WorkWCSTATExtractId, 
	AuditId, 
	CreatedDate, 
	EDWPremiumMasterCalculationPKId, 
	EDWLossMasterCalculationPKId, 
	TypeBureauCode, 
	PremiumMasterRunDate, 
	LossMasterRunDate, 
	BureauCompanyCode, 
	PolicyKey, 
	StateProvinceCode, 
	PolicyEffectiveDate, 
	PolicyEndDate, 
	InterstateRiskId, 
	EmployeeLeasingCode, 
	StateRatingEffectiveDate, 
	FederalTaxId, 
	ThreeYearFixedRatePolicyIndicator, 
	MultistatePolicyIndicator, 
	InterstateRatedPolicyIndicator, 
	EstimatedAuditCode, 
	RetrospectiveratedPolicyIndicator, 
	CancelledMidTermPolicyIndicator, 
	ManagedCareOrganizationPolicyIndicator, 
	TypeOfCoverageIdCode, 
	TypeOfPlan, 
	LossesSubjectToDeductibleCode, 
	BasisOfDeductibleCalculationCode, 
	DeductibleAmountPerClaimAccident, 
	InsuredName, 
	WCSTATAddress, 
	PremiumMasterClassCode, 
	ExperienceModificationFactor, 
	ExperienceModificationEffectiveDate, 
	Exposure, 
	PremiumMasterDirectWrittenPremiumAmount, 
	ManualChargedRate, 
	LossMasterClassCode, 
	ClaimLossDate, 
	ClaimNumber, 
	ClaimantNumber, 
	ClaimOccurrenceStatusCode, 
	InjuryTypeCode, 
	CatastropheCode, 
	IncurredIndemnityAmount, 
	IncurredMedicalAmount, 
	TypeOfRecoveryCode, 
	JurisdictionStateCode, 
	BodyPartCode, 
	NatureOfInjuryCode, 
	CauseOfInjuryCode, 
	PaidIndemnityAmount, 
	PaidMedicalAmount, 
	DeductibleReimbursementAmount, 
	PaidAllocatedLossAdjustmentExpenseAmount, 
	IncurredAllocatedLossAdjustmentExpenseAmount, 
	CorrectionSeqNumber, 
	TypeOfNonStandardIdCode, 
	PreviousReportLevelCodeReportNumber, 
	TypeOfLoss, 
	TypeOfClaim, 
	TypeOfSettlement, 
	ManagedCareOrganizationType, 
	VocationalRehabIndicator, 
	LumpSumIndicator, 
	FraudulentClaimCode, 
	RateEffectiveDate, 
	SplitPeriodCode, 
	OccupationDescription, 
	WeeklyWageAmount, 
	EmployersAttorneyFees
	FROM EXP_Append_FileName1
	ORDER BY PolicyKey ASC, ClaimLossDate ASC
),
WCSTATCorrectionFlatFile AS (
	INSERT INTO WCSTATFlatFile
	(FileName, WorkWCSTATExtractId, AuditId, CreatedDate, EDWPremiumMasterCalculationPKId, EDWLossMasterCalculationPKId, TypeBureauCode, PremiumMasterRunDate, LossMasterRunDate, BureauCompanyCode, PolicyKey, StateProvinceCode, PolicyEffectiveDate, PolicyEndDate, InterstateRiskId, EmployeeLeasingCode, StateRatingEffectiveDate, FederalTaxId, ThreeYearFixedRatePolicyIndicator, MultistatePolicyIndicator, InterstateRatedPolicyIndicator, EstimatedAuditCode, RetrospectiveratedPolicyIndicator, CancelledMidTermPolicyIndicator, ManagedCareOrganizationPolicyIndicator, TypeOfCoverageIdCode, TypeOfPlan, LossesSubjectToDeductibleCode, BasisOfDeductibleCalculationCode, DeductibleAmountPerClaimAccident, InsuredName, WCSTATAddress, PremiumMasterClassCode, ExperienceModificationFactor, ExperienceModificationEffectiveDate, RateEffectiveDate, Exposure, PremiumMasterDirectWrittenPremiumAmount, ManualChargedRate, SplitPeriodCode, LossMasterClassCode, ClaimLossDate, ClaimNumber, ClaimantNumber, ClaimOccurrenceStatusCode, InjuryTypeCode, CatastropheCode, IncurredIndemnityAmount, IncurredMedicalAmount, TypeOfRecoveryCode, JurisdictionStateCode, BodyPartCode, NatureOfInjuryCode, CauseOfInjuryCode, PaidIndemnityAmount, PaidMedicalAmount, DeductibleReimbursementAmount, PaidAllocatedLossAdjustmentExpenseAmount, IncurredAllocatedLossAdjustmentExpenseAmount, CorrectionSeqNumber, TypeOfNonStandardIdCode, PreviousReportLevelCodeReportNumber, TypeOfLoss, TypeOfClaim, TypeOfSettlement, ManagedCareOrganizationType, VocationalRehabIndicator, LumpSumIndicator, FraudulentClaimCode, OccupationDescription, WeeklyWageAmount, EmployersAttorneyFees)
	SELECT 
	FILENAME, 
	WORKWCSTATEXTRACTID, 
	AUDITID, 
	CREATEDDATE, 
	EDWPREMIUMMASTERCALCULATIONPKID, 
	EDWLOSSMASTERCALCULATIONPKID, 
	TYPEBUREAUCODE, 
	PREMIUMMASTERRUNDATE, 
	LOSSMASTERRUNDATE, 
	BUREAUCOMPANYCODE, 
	POLICYKEY, 
	STATEPROVINCECODE, 
	POLICYEFFECTIVEDATE, 
	POLICYENDDATE, 
	INTERSTATERISKID, 
	EMPLOYEELEASINGCODE, 
	STATERATINGEFFECTIVEDATE, 
	FEDERALTAXID, 
	THREEYEARFIXEDRATEPOLICYINDICATOR, 
	MULTISTATEPOLICYINDICATOR, 
	INTERSTATERATEDPOLICYINDICATOR, 
	ESTIMATEDAUDITCODE, 
	RETROSPECTIVERATEDPOLICYINDICATOR, 
	CANCELLEDMIDTERMPOLICYINDICATOR, 
	MANAGEDCAREORGANIZATIONPOLICYINDICATOR, 
	TYPEOFCOVERAGEIDCODE, 
	TYPEOFPLAN, 
	LOSSESSUBJECTTODEDUCTIBLECODE, 
	BASISOFDEDUCTIBLECALCULATIONCODE, 
	DEDUCTIBLEAMOUNTPERCLAIMACCIDENT, 
	INSUREDNAME, 
	WCSTATADDRESS, 
	PREMIUMMASTERCLASSCODE, 
	EXPERIENCEMODIFICATIONFACTOR, 
	EXPERIENCEMODIFICATIONEFFECTIVEDATE, 
	RATEEFFECTIVEDATE, 
	EXPOSURE, 
	PREMIUMMASTERDIRECTWRITTENPREMIUMAMOUNT, 
	MANUALCHARGEDRATE, 
	SPLITPERIODCODE, 
	LOSSMASTERCLASSCODE, 
	CLAIMLOSSDATE, 
	CLAIMNUMBER, 
	CLAIMANTNUMBER, 
	CLAIMOCCURRENCESTATUSCODE, 
	INJURYTYPECODE, 
	CATASTROPHECODE, 
	INCURREDINDEMNITYAMOUNT, 
	INCURREDMEDICALAMOUNT, 
	TYPEOFRECOVERYCODE, 
	JURISDICTIONSTATECODE, 
	BODYPARTCODE, 
	NATUREOFINJURYCODE, 
	CAUSEOFINJURYCODE, 
	PAIDINDEMNITYAMOUNT, 
	PAIDMEDICALAMOUNT, 
	DEDUCTIBLEREIMBURSEMENTAMOUNT, 
	PAIDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	INCURREDALLOCATEDLOSSADJUSTMENTEXPENSEAMOUNT, 
	CORRECTIONSEQNUMBER, 
	TYPEOFNONSTANDARDIDCODE, 
	PREVIOUSREPORTLEVELCODEREPORTNUMBER, 
	TYPEOFLOSS, 
	TYPEOFCLAIM, 
	TYPEOFSETTLEMENT, 
	MANAGEDCAREORGANIZATIONTYPE, 
	VOCATIONALREHABINDICATOR, 
	LUMPSUMINDICATOR, 
	FRAUDULENTCLAIMCODE, 
	OCCUPATIONDESCRIPTION, 
	WEEKLYWAGEAMOUNT, 
	EMPLOYERSATTORNEYFEES
	FROM SRT_CorrectionFile
),