WITH
SQ_umbrella AS (
	SELECT
		umb_seq,
		policy_num,
		policy_sym,
		policy_mod,
		policy_mco,
		umb_amt_type_code,
		um_include_flag,
		uim_include_flag,
		credit_exist_ins_exp_date,
		underlying_cov_include_flag,
		other_prim_ins_flag,
		acc_violation_flag,
		acc_violation_descript,
		non_compensate_pos_flag,
		non_compensate_pos_descript,
		non_own_prop_flag,
		non_own_prop_descript,
		bus_act_include_flag,
		bus_act_include_descript,
		libel_slander_flag,
		item_not_covered_flag,
		item_not_covered_descript,
		add_int_na_flag,
		modified_date,
		modified_user_id,
		signed_rejection_flag,
		occupation_flag,
		um_limit_type_code,
		uim_limit_type_code
	FROM umbrella
),
EXP_UMBRELLA AS (
	SELECT
	umb_seq,
	policy_num,
	policy_sym,
	policy_mod,
	policy_mco,
	umb_amt_type_code,
	um_include_flag,
	uim_include_flag,
	credit_exist_ins_exp_date,
	underlying_cov_include_flag,
	other_prim_ins_flag,
	acc_violation_flag,
	acc_violation_descript,
	non_compensate_pos_flag,
	non_compensate_pos_descript,
	non_own_prop_flag,
	non_own_prop_descript,
	bus_act_include_flag,
	bus_act_include_descript,
	libel_slander_flag,
	item_not_covered_flag,
	item_not_covered_descript,
	add_int_na_flag,
	modified_date,
	modified_user_id,
	signed_rejection_flag,
	occupation_flag,
	um_limit_type_code,
	uim_limit_type_code,
	SYSDATE AS EXTRACT_DATE,
	SYSDATE AS AS_OF_DATE,
	'' AS RECORD_COUNT,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS SOURCE_SYSTEM_ID
	FROM SQ_umbrella
),
umbrella_stage AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.umbrella_stage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.umbrella_stage
	(umb_seq, policy_num, policy_sym, policy_mod, policy_mco, umb_amt_type_code, um_include_flag, uim_include_flag, credit_exist_ins_exp_date, underlying_cov_include_flag, other_prim_ins_flag, acc_violation_flag, acc_violation_descript, non_compensate_pos_flag, non_compensate_pos_descript, non_own_prop_flag, non_own_prop_descript, bus_act_include_flag, bus_act_include_descript, libel_slander_flag, item_not_covered_flag, item_not_covered_descript, add_int_na_flag, modified_date, modified_user_id, signed_rejection_flag, occupation_flag, um_limit_type_code, uim_limit_type_code, extract_date, as_of_date, record_count, source_system_id)
	SELECT 
	UMB_SEQ, 
	POLICY_NUM, 
	POLICY_SYM, 
	POLICY_MOD, 
	POLICY_MCO, 
	UMB_AMT_TYPE_CODE, 
	UM_INCLUDE_FLAG, 
	UIM_INCLUDE_FLAG, 
	CREDIT_EXIST_INS_EXP_DATE, 
	UNDERLYING_COV_INCLUDE_FLAG, 
	OTHER_PRIM_INS_FLAG, 
	ACC_VIOLATION_FLAG, 
	ACC_VIOLATION_DESCRIPT, 
	NON_COMPENSATE_POS_FLAG, 
	NON_COMPENSATE_POS_DESCRIPT, 
	NON_OWN_PROP_FLAG, 
	NON_OWN_PROP_DESCRIPT, 
	BUS_ACT_INCLUDE_FLAG, 
	BUS_ACT_INCLUDE_DESCRIPT, 
	LIBEL_SLANDER_FLAG, 
	ITEM_NOT_COVERED_FLAG, 
	ITEM_NOT_COVERED_DESCRIPT, 
	ADD_INT_NA_FLAG, 
	MODIFIED_DATE, 
	MODIFIED_USER_ID, 
	SIGNED_REJECTION_FLAG, 
	OCCUPATION_FLAG, 
	UM_LIMIT_TYPE_CODE, 
	UIM_LIMIT_TYPE_CODE, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID
	FROM EXP_UMBRELLA
),