WITH
SQ_vehicle_policy_info AS (
	SELECT
		policy_num,
		policy_sym,
		policy_mod,
		policy_mco,
		loss_flag,
		acc_violation_flag,
		bridge_flag,
		trans_ins_within_agency_flag,
		eno_prim_ins_flag,
		rollover_flag,
		eno_extend_flag,
		eno_connect_garage_bus_flag,
		hm_own_disc_flag,
		transfer_disc_flag,
		res_driver_disc_flag,
		veh_cotitle_flag,
		multi_car_flag,
		auto_cov_decline_flag,
		veh_home_own_disc,
		own_personal_auto_flag,
		car_dealer_flag,
		insd_elsewhere_flag,
		licensed_driver_no_auto_ins_flag,
		specialty_veh_flag,
		modified_date,
		modified_user_id,
		corp_own_flag,
		four_or_less_flag,
		corp_own_veh_pers_use_flag,
		public_or_livery_convey_flag,
		perm_assign_to_insd_flag,
		corp_own_veh_oper_by_insd_flag,
		used_for_insd_occupation_flag,
		kept_at_school_flag,
		signed_auto_supp_flag,
		corp_own_descript,
		kept_at_school_descript,
		signed_reject_auto_supp_flag,
		manually_rated_code
	FROM vehicle_policy_info
),
EXP_VEHICLE_POLICY_INFO AS (
	SELECT
	policy_num,
	policy_sym,
	policy_mod,
	policy_mco,
	loss_flag,
	acc_violation_flag,
	bridge_flag,
	trans_ins_within_agency_flag,
	eno_prim_ins_flag,
	rollover_flag,
	eno_extend_flag,
	eno_connect_garage_bus_flag,
	hm_own_disc_flag,
	transfer_disc_flag,
	res_driver_disc_flag,
	veh_cotitle_flag,
	multi_car_flag,
	auto_cov_decline_flag,
	veh_home_own_disc,
	own_personal_auto_flag,
	car_dealer_flag,
	insd_elsewhere_flag,
	licensed_driver_no_auto_ins_flag,
	specialty_veh_flag,
	modified_date,
	modified_user_id,
	corp_own_flag,
	four_or_less_flag,
	corp_own_veh_pers_use_flag,
	public_or_livery_convey_flag,
	perm_assign_to_insd_flag,
	corp_own_veh_oper_by_insd_flag,
	used_for_insd_occupation_flag,
	kept_at_school_flag,
	signed_auto_supp_flag,
	corp_own_descript,
	kept_at_school_descript,
	signed_reject_auto_supp_flag,
	manually_rated_code,
	SYSDATE AS EXTRACT_DATE,
	SYSDATE AS AS_OF_DATE,
	'' AS RECORD_COUNT,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS SOURCE_SYSTEM_ID
	FROM SQ_vehicle_policy_info
),
vehicle_policy_info_stage AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.vehicle_policy_info_stage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.vehicle_policy_info_stage
	(policy_num, policy_sym, policy_mod, policy_mco, loss_flag, acc_violation_flag, bridge_flag, trans_ins_within_agency_flag, eno_prim_ins_flag, rollover_flag, eno_extend_flag, eno_connect_garage_bus_flag, hm_own_disc_flag, transfer_disc_flag, res_driver_disc_flag, veh_cotitle_flag, multi_car_flag, auto_cov_decline_flag, veh_home_own_disc, own_personal_auto_flag, car_dealer_flag, insd_elsewhere_flag, licensed_driver_no_auto_ins_flag, specialty_veh_flag, modified_date, modified_user_id, corp_own_flag, four_or_less_flag, corp_own_veh_pers_use_flag, public_or_livery_convey_flag, perm_assign_to_insd_flag, corp_own_veh_oper_by_insd_flag, used_for_insd_occupation_flag, kept_at_school_flag, signed_auto_supp_flag, corp_own_descript, kept_at_school_descript, signed_reject_auto_supp_flag, manually_rated_code, extract_date, as_of_date, record_count, source_system_id)
	SELECT 
	POLICY_NUM, 
	POLICY_SYM, 
	POLICY_MOD, 
	POLICY_MCO, 
	LOSS_FLAG, 
	ACC_VIOLATION_FLAG, 
	BRIDGE_FLAG, 
	TRANS_INS_WITHIN_AGENCY_FLAG, 
	ENO_PRIM_INS_FLAG, 
	ROLLOVER_FLAG, 
	ENO_EXTEND_FLAG, 
	ENO_CONNECT_GARAGE_BUS_FLAG, 
	HM_OWN_DISC_FLAG, 
	TRANSFER_DISC_FLAG, 
	RES_DRIVER_DISC_FLAG, 
	VEH_COTITLE_FLAG, 
	MULTI_CAR_FLAG, 
	AUTO_COV_DECLINE_FLAG, 
	VEH_HOME_OWN_DISC, 
	OWN_PERSONAL_AUTO_FLAG, 
	CAR_DEALER_FLAG, 
	INSD_ELSEWHERE_FLAG, 
	LICENSED_DRIVER_NO_AUTO_INS_FLAG, 
	SPECIALTY_VEH_FLAG, 
	MODIFIED_DATE, 
	MODIFIED_USER_ID, 
	CORP_OWN_FLAG, 
	FOUR_OR_LESS_FLAG, 
	CORP_OWN_VEH_PERS_USE_FLAG, 
	PUBLIC_OR_LIVERY_CONVEY_FLAG, 
	PERM_ASSIGN_TO_INSD_FLAG, 
	CORP_OWN_VEH_OPER_BY_INSD_FLAG, 
	USED_FOR_INSD_OCCUPATION_FLAG, 
	KEPT_AT_SCHOOL_FLAG, 
	SIGNED_AUTO_SUPP_FLAG, 
	CORP_OWN_DESCRIPT, 
	KEPT_AT_SCHOOL_DESCRIPT, 
	SIGNED_REJECT_AUTO_SUPP_FLAG, 
	MANUALLY_RATED_CODE, 
	EXTRACT_DATE AS EXTRACT_DATE, 
	AS_OF_DATE AS AS_OF_DATE, 
	RECORD_COUNT AS RECORD_COUNT, 
	SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID
	FROM EXP_VEHICLE_POLICY_INFO
),