WITH
SQ_WBWCDividendStage AS (
	SELECT
		WBWCDividendStageId AS WBWCDividendStageID,
		ExtractDate,
		SourceSystemId,
		WBWCDividendId,
		SessionId,
		DividendType,
		ManualDividendCalculation,
		DividendOptions,
		ManualIncurredLossRatio,
		ManualDividendPercentagePaid,
		ManualGrossVariableDividendPercentage,
		ManualTotalEarnedPremium,
		ManualPreviouslyPaidDividentPercentage,
		ManualNetVariableDividendPercentage,
		ManualNetDividendAmount,
		ManualPreviouslyNetVariableDividendPercentage,
		ManualPreviouslyPaidNetVariableDividend,
		State,
		ProjectedDividendDate,
		DividendPaid,
		DividendPaidDate,
		InDividendSelectEditMode,
		DividendSoftMessage,
		DividendMultiStateSoftMessage,
		ArgentCappedFlatDividendPremium,
		ArgentFlatDividendPremium,
		ArgentFlatVariableDividendPremium,
		ArgentVariableDividendPremium,
		CLNSICappedFlatDividendPremium,
		CLNSIFlatDividendPremium,
		CLNSIFlatVariableDividendPremium,
		CLNSIVariableDividendPremium,
		DividendIncurredLossRatio,
		Premium,
		Percentage,
		WCLineId
	FROM WBWCDividendStage
),
EXP_Values AS (
	SELECT
	InDividendSelectEditMode AS i_InDividendSelectEditMode,
	ManualDividendCalculation AS i_ManualDividendCalculation,
	WBWCDividendStageID,
	ExtractDate,
	SourceSystemId,
	WBWCDividendId,
	SessionId,
	DividendType,
	DividendOptions,
	ManualIncurredLossRatio,
	ManualDividendPercentagePaid,
	ManualGrossVariableDividendPercentage,
	ManualTotalEarnedPremium,
	ManualPreviouslyPaidDividentPercentage,
	ManualNetVariableDividendPercentage,
	ManualNetDividendAmount,
	ManualPreviouslyNetVariableDividendPercentage,
	ManualPreviouslyPaidNetVariableDividend,
	State,
	ProjectedDividendDate,
	DividendPaid,
	DividendPaidDate,
	DividendSoftMessage,
	DividendMultiStateSoftMessage,
	ArgentCappedFlatDividendPremium,
	ArgentFlatDividendPremium,
	ArgentFlatVariableDividendPremium,
	ArgentVariableDividendPremium,
	CLNSICappedFlatDividendPremium,
	CLNSIFlatDividendPremium,
	CLNSIFlatVariableDividendPremium,
	CLNSIVariableDividendPremium,
	DividendIncurredLossRatio,
	Premium,
	Percentage,
	-- *INF*: DECODE(i_InDividendSelectEditMode,'T','1','F','0')
	DECODE(
	    i_InDividendSelectEditMode,
	    'T', '1',
	    'F', '0'
	) AS o_InDividendSelectEditMode,
	-- *INF*: DECODE(i_ManualDividendCalculation,'T','1','F','0')
	DECODE(
	    i_ManualDividendCalculation,
	    'T', '1',
	    'F', '0'
	) AS o_ManualDividendCalculation,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	WCLineId
	FROM SQ_WBWCDividendStage
),
ArchWBWCDividendStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBWCDividendStage
	(ExtractDate, SourceSystemId, AuditId, WBWCDividendStageId, WBWCDividendId, SessionId, DividendType, ManualDividendCalculation, DividendOptions, ManualIncurredLossRatio, ManualDividendPercentagePaid, ManualGrossVariableDividendPercentage, ManualTotalEarnedPremium, ManualPreviouslyPaidDividentPercentage, ManualNetVariableDividendPercentage, ManualNetDividendAmount, ManualPreviouslyNetVariableDividendPercentage, ManualPreviouslyPaidNetVariableDividend, State, ProjectedDividendDate, DividendPaid, DividendPaidDate, InDividendSelectEditMode, DividendSoftMessage, DividendMultiStateSoftMessage, ArgentCappedFlatDividendPremium, ArgentFlatDividendPremium, ArgentFlatVariableDividendPremium, ArgentVariableDividendPremium, CLNSICappedFlatDividendPremium, CLNSIFlatDividendPremium, CLNSIFlatVariableDividendPremium, CLNSIVariableDividendPremium, DividendIncurredLossRatio, Premium, Percentage, WCLineId)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBWCDividendStageID AS WBWCDIVIDENDSTAGEID, 
	WBWCDIVIDENDID, 
	SESSIONID, 
	DIVIDENDTYPE, 
	o_ManualDividendCalculation AS MANUALDIVIDENDCALCULATION, 
	DIVIDENDOPTIONS, 
	MANUALINCURREDLOSSRATIO, 
	MANUALDIVIDENDPERCENTAGEPAID, 
	MANUALGROSSVARIABLEDIVIDENDPERCENTAGE, 
	MANUALTOTALEARNEDPREMIUM, 
	MANUALPREVIOUSLYPAIDDIVIDENTPERCENTAGE, 
	MANUALNETVARIABLEDIVIDENDPERCENTAGE, 
	MANUALNETDIVIDENDAMOUNT, 
	MANUALPREVIOUSLYNETVARIABLEDIVIDENDPERCENTAGE, 
	MANUALPREVIOUSLYPAIDNETVARIABLEDIVIDEND, 
	STATE, 
	PROJECTEDDIVIDENDDATE, 
	DIVIDENDPAID, 
	DIVIDENDPAIDDATE, 
	o_InDividendSelectEditMode AS INDIVIDENDSELECTEDITMODE, 
	DIVIDENDSOFTMESSAGE, 
	DIVIDENDMULTISTATESOFTMESSAGE, 
	ARGENTCAPPEDFLATDIVIDENDPREMIUM, 
	ARGENTFLATDIVIDENDPREMIUM, 
	ARGENTFLATVARIABLEDIVIDENDPREMIUM, 
	ARGENTVARIABLEDIVIDENDPREMIUM, 
	CLNSICAPPEDFLATDIVIDENDPREMIUM, 
	CLNSIFLATDIVIDENDPREMIUM, 
	CLNSIFLATVARIABLEDIVIDENDPREMIUM, 
	CLNSIVARIABLEDIVIDENDPREMIUM, 
	DIVIDENDINCURREDLOSSRATIO, 
	PREMIUM, 
	PERCENTAGE, 
	WCLINEID
	FROM EXP_Values
),