WITH
SQ_DCBILGeneralJounalStage AS (
	SELECT
		DCBILGeneralJounalStageId,
		ExtractDate,
		SourceSystemId,
		JournalId,
		AccountId,
		PolicyTermId,
		ActivityTypeCode,
		AccountTypeCode,
		BookingClassificationCode,
		CurrencyCulture,
		MasterCompanyCode,
		ProcessingOrgUnitCode,
		JournalTypeCode,
		JournalSubTypeCode,
		TransactionTypeCode,
		ActivityEffectiveDate,
		TransactionDate,
		AccountingClassCode,
		TransactionGrossAmount,
		TransactionNetAmount,
		PolicyIssueSystemCode,
		PolicyLineOfBusinessCode,
		PolicyStateCode,
		PolicyCountryCode,
		LastUpdatedTimestamp,
		LastUpdatedUserId,
		TransactionGUID,
		TargetMasterCompanyCode
	FROM DCBILGeneralJounalStage
),
EXP_Metadata AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	DCBILGeneralJounalStageId,
	ExtractDate,
	SourceSystemId,
	JournalId,
	AccountId,
	PolicyTermId,
	ActivityTypeCode,
	AccountTypeCode,
	BookingClassificationCode,
	CurrencyCulture,
	MasterCompanyCode,
	ProcessingOrgUnitCode,
	JournalTypeCode,
	JournalSubTypeCode,
	TransactionTypeCode,
	ActivityEffectiveDate,
	TransactionDate,
	AccountingClassCode,
	TransactionGrossAmount,
	TransactionNetAmount,
	PolicyIssueSystemCode,
	PolicyLineOfBusinessCode,
	PolicyStateCode,
	PolicyCountryCode,
	LastUpdatedTimestamp,
	LastUpdatedUserId,
	TransactionGUID,
	TargetMasterCompanyCode
	FROM SQ_DCBILGeneralJounalStage
),
ArchDCBILGeneralJounalStage AS (
	INSERT INTO ArchDCBILGeneralJounalStage
	(ExtractDate, SourceSystemId, AuditId, DCBILGeneralJounalStageId, JournalId, AccountId, PolicyTermId, ActivityTypeCode, AccountTypeCode, BookingClassificationCode, CurrencyCulture, MasterCompanyCode, ProcessingOrgUnitCode, JournalTypeCode, JournalSubTypeCode, TransactionTypeCode, ActivityEffectiveDate, TransactionDate, AccountingClassCode, TransactionGrossAmount, TransactionNetAmount, PolicyIssueSystemCode, PolicyLineOfBusinessCode, PolicyStateCode, PolicyCountryCode, LastUpdatedTimestamp, LastUpdatedUserId, TransactionGUID, TargetMasterCompanyCode)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	DCBILGENERALJOUNALSTAGEID, 
	JOURNALID, 
	ACCOUNTID, 
	POLICYTERMID, 
	ACTIVITYTYPECODE, 
	ACCOUNTTYPECODE, 
	BOOKINGCLASSIFICATIONCODE, 
	CURRENCYCULTURE, 
	MASTERCOMPANYCODE, 
	PROCESSINGORGUNITCODE, 
	JOURNALTYPECODE, 
	JOURNALSUBTYPECODE, 
	TRANSACTIONTYPECODE, 
	ACTIVITYEFFECTIVEDATE, 
	TRANSACTIONDATE, 
	ACCOUNTINGCLASSCODE, 
	TRANSACTIONGROSSAMOUNT, 
	TRANSACTIONNETAMOUNT, 
	POLICYISSUESYSTEMCODE, 
	POLICYLINEOFBUSINESSCODE, 
	POLICYSTATECODE, 
	POLICYCOUNTRYCODE, 
	LASTUPDATEDTIMESTAMP, 
	LASTUPDATEDUSERID, 
	TRANSACTIONGUID, 
	TARGETMASTERCOMPANYCODE
	FROM EXP_Metadata
),