WITH
SQ_WB_CF_CoverageEquipmentBreakdown AS (
	WITH cte_WBCFCoverageEquipmentBreakdown (Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.CoverageId, 
	X.WB_CF_CoverageEquipmentBreakdownId, 
	X.SessionId, 
	X.ARate, 
	X.Blanket, 
	X.BlanketNOCDescription, 
	X.Coinsurance, 
	X.Deductible, 
	X.InceptionDate, 
	X.Indicator, 
	X.OtherFlood, 
	X.OtherFloodOther, 
	X.OtherFloodPrimary, 
	X.Specific, 
	X.SpecificNOCDescription, 
	X.WaiveUnderlyingInsurance, 
	X.EquipmentBreakdownPremiumOverride, 
	X.PriorTermEquipmentBreakdownPremium, 
	X.PerishableGoodsPolicyPremium, 
	X.AlgorithmPart2Display, 
	X.AlgorithmPart1Display, 
	X.AlgorithmPart3Effective2013Display, 
	X.AlgorithmPart3Effective2014Display, 
	X.PremiumDisplay, 
	X.BillingLOB, 
	X.ParentBillingLOB, 
	X.CommissionPlanId, 
	X.TransactionCommissionType, 
	X.TransactionCommissionValue, 
	X.PurePremium, 
	X.TransactionFinalCommissionValue, 
	X.IsBillingSubline, 
	X.AlgorithmPart3Year1TransitionDisplay, 
	X.AlgorithmPart3Year2TransitionDisplay, 
	X.AlgorithmPart3Year1TransitionAdjustmentPremiumDisplay, 
	X.AlgorithmPart3Year2TransitionAdjustmentPremiumDisplay, 
	X.AlgorithmPart3EquipmentBreakdownPremiumDisplay 
	FROM 
	WB_CF_CoverageEquipmentBreakdown X
	inner join cte_WBCFCoverageEquipmentBreakdown Y
	on X.SessionId = Y.SessionId
),
EXP_Metadata AS (
	SELECT
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	CoverageId,
	WB_CF_CoverageEquipmentBreakdownId,
	SessionId,
	ARate,
	Blanket,
	BlanketNOCDescription,
	Coinsurance,
	Deductible,
	InceptionDate,
	Indicator,
	OtherFlood,
	OtherFloodOther,
	OtherFloodPrimary,
	Specific,
	SpecificNOCDescription,
	WaiveUnderlyingInsurance,
	EquipmentBreakdownPremiumOverride,
	PriorTermEquipmentBreakdownPremium,
	PerishableGoodsPolicyPremium,
	AlgorithmPart2Display,
	AlgorithmPart1Display,
	AlgorithmPart3Effective2013Display,
	AlgorithmPart3Effective2014Display,
	PremiumDisplay,
	BillingLOB,
	ParentBillingLOB,
	CommissionPlanId,
	TransactionCommissionType,
	TransactionCommissionValue,
	PurePremium,
	TransactionFinalCommissionValue,
	IsBillingSubline,
	AlgorithmPart3Year1TransitionDisplay,
	AlgorithmPart3Year2TransitionDisplay,
	AlgorithmPart3Year1TransitionAdjustmentPremiumDisplay,
	AlgorithmPart3Year2TransitionAdjustmentPremiumDisplay,
	AlgorithmPart3EquipmentBreakdownPremiumDisplay
	FROM SQ_WB_CF_CoverageEquipmentBreakdown
),
WBCFCoverageEquipmentBreakdownStage AS (
	TRUNCATE TABLE WBCFCoverageEquipmentBreakdownStage;
	INSERT INTO WBCFCoverageEquipmentBreakdownStage
	(ExtractDate, SourceSystemId, CoverageId, WB_CF_CoverageEquipmentBreakdownId, SessionId, ARate, Blanket, BlanketNOCDescription, Coinsurance, Deductible, InceptionDate, Indicator, OtherFlood, OtherFloodOther, OtherFloodPrimary, Specific, SpecificNOCDescription, WaiveUnderlyingInsurance, EquipmentBreakdownPremiumOverride, PriorTermEquipmentBreakdownPremium, PerishableGoodsPolicyPremium, AlgorithmPart2Display, AlgorithmPart1Display, AlgorithmPart3Effective2013Display, AlgorithmPart3Effective2014Display, PremiumDisplay, BillingLOB, ParentBillingLOB, CommissionPlanId, TransactionCommissionType, TransactionCommissionValue, PurePremium, TransactionFinalCommissionValue, IsBillingSubline, AlgorithmPart3Year1TransitionDisplay, AlgorithmPart3Year2TransitionDisplay, AlgorithmPart3Year1TransitionAdjustmentPremiumDisplay, AlgorithmPart3Year2TransitionAdjustmentPremiumDisplay, AlgorithmPart3EquipmentBreakdownPremiumDisplay)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	COVERAGEID, 
	WB_CF_COVERAGEEQUIPMENTBREAKDOWNID, 
	SESSIONID, 
	ARATE, 
	BLANKET, 
	BLANKETNOCDESCRIPTION, 
	COINSURANCE, 
	DEDUCTIBLE, 
	INCEPTIONDATE, 
	INDICATOR, 
	OTHERFLOOD, 
	OTHERFLOODOTHER, 
	OTHERFLOODPRIMARY, 
	SPECIFIC, 
	SPECIFICNOCDESCRIPTION, 
	WAIVEUNDERLYINGINSURANCE, 
	EQUIPMENTBREAKDOWNPREMIUMOVERRIDE, 
	PRIORTERMEQUIPMENTBREAKDOWNPREMIUM, 
	PERISHABLEGOODSPOLICYPREMIUM, 
	ALGORITHMPART2DISPLAY, 
	ALGORITHMPART1DISPLAY, 
	ALGORITHMPART3EFFECTIVE2013DISPLAY, 
	ALGORITHMPART3EFFECTIVE2014DISPLAY, 
	PREMIUMDISPLAY, 
	BILLINGLOB, 
	PARENTBILLINGLOB, 
	COMMISSIONPLANID, 
	TRANSACTIONCOMMISSIONTYPE, 
	TRANSACTIONCOMMISSIONVALUE, 
	PUREPREMIUM, 
	TRANSACTIONFINALCOMMISSIONVALUE, 
	ISBILLINGSUBLINE, 
	ALGORITHMPART3YEAR1TRANSITIONDISPLAY, 
	ALGORITHMPART3YEAR2TRANSITIONDISPLAY, 
	ALGORITHMPART3YEAR1TRANSITIONADJUSTMENTPREMIUMDISPLAY, 
	ALGORITHMPART3YEAR2TRANSITIONADJUSTMENTPREMIUMDISPLAY, 
	ALGORITHMPART3EQUIPMENTBREAKDOWNPREMIUMDISPLAY
	FROM EXP_Metadata
),