WITH
SQ_DCPolicyStaging AS (
	SELECT
		PolicyId,
		SessionId,
		Id,
		EffectiveDate,
		ExpirationDate,
		LineOfBusiness,
		Term,
		PrimaryRatingState,
		Product,
		HonorRates,
		AuditPeriod,
		SICCode,
		SICCodeDesc,
		NAICSCode,
		NAICSCodeDesc,
		QuoteNumber,
		TermFactor,
		CancellationDate,
		Description,
		PolicyNumber,
		Status,
		TransactionDate,
		TransactionDateTime,
		PreviousPolicyNumber,
		InceptionDate,
		PolicyTermID,
		AccountID,
		TaxesSurcharges,
		Auditable,
		ExtractDate,
		SourceSystemId
	FROM DCPolicyStaging
),
EXP_Metadata AS (
	SELECT
	PolicyId,
	SessionId,
	Id,
	EffectiveDate,
	ExpirationDate,
	LineOfBusiness,
	Term,
	PrimaryRatingState,
	Product,
	HonorRates,
	AuditPeriod,
	SICCode,
	SICCodeDesc,
	NAICSCode,
	NAICSCodeDesc,
	QuoteNumber,
	TermFactor,
	CancellationDate,
	Description,
	PolicyNumber,
	Status,
	TransactionDate,
	TransactionDateTime,
	PreviousPolicyNumber,
	InceptionDate,
	PolicyTermID,
	AccountID,
	TaxesSurcharges,
	Auditable,
	ExtractDate,
	SourceSystemId,
	-- *INF*: DECODE(HonorRates,'T',1,'F',0,NULL)
	DECODE(
	    HonorRates,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_HonorRates,
	-- *INF*: DECODE(Auditable,'T',1,'F',0,NULL)
	DECODE(
	    Auditable,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_Auditable,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_DCPolicyStaging
),
archDCPolicyStaging AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.archDCPolicyStaging
	(PolicyId, SessionId, Id, EffectiveDate, ExpirationDate, LineOfBusiness, Term, PrimaryRatingState, Product, HonorRates, AuditPeriod, SICCode, SICCodeDesc, NAICSCode, NAICSCodeDesc, QuoteNumber, TermFactor, CancellationDate, Description, PolicyNumber, Status, TransactionDate, TransactionDateTime, PreviousPolicyNumber, InceptionDate, PolicyTermID, AccountID, TaxesSurcharges, Auditable, ExtractDate, SourceSystemId, AuditId)
	SELECT 
	POLICYID, 
	SESSIONID, 
	ID, 
	EFFECTIVEDATE, 
	EXPIRATIONDATE, 
	LINEOFBUSINESS, 
	TERM, 
	PRIMARYRATINGSTATE, 
	PRODUCT, 
	o_HonorRates AS HONORRATES, 
	AUDITPERIOD, 
	SICCODE, 
	SICCODEDESC, 
	NAICSCODE, 
	NAICSCODEDESC, 
	QUOTENUMBER, 
	TERMFACTOR, 
	CANCELLATIONDATE, 
	DESCRIPTION, 
	POLICYNUMBER, 
	STATUS, 
	TRANSACTIONDATE, 
	TRANSACTIONDATETIME, 
	PREVIOUSPOLICYNUMBER, 
	INCEPTIONDATE, 
	POLICYTERMID, 
	ACCOUNTID, 
	TAXESSURCHARGES, 
	o_Auditable AS AUDITABLE, 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID
	FROM EXP_Metadata
),