WITH
SQ_DC_BP_Occupancy AS (
	WITH cte_DCBPOccupancy(Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.BP_RiskId, 
	X.BP_OccupancyId, 
	X.SessionId, 
	X.Id, 
	X.AssociationUnitOwners, 
	X.BOP_New_EQ, 
	X.BOP_New_EQ_Override, 
	X.BOP_New_EQSL, 
	X.BOP_New_EQSL_Override, 
	X.BOP_New_LiabClassGroup, 
	X.BOP_New_LiabClassGroup_Override, 
	X.BOP_New_LiabExpBase, 
	X.BOP_New_LiabExpBase_Override, 
	X.BOP_New_NAICS, 
	X.BOP_New_NAICS_Override, 
	X.BOP_New_PropRateNo, 
	X.BOP_New_PropRateNo_Override, 
	X.BOP_New_SIC, 
	X.BOP_New_SIC_Override, 
	X.BOP_PMA, 
	X.BOP_PMA_Override, 
	X.BOP_RateGroup, 
	X.BOP_RateGroup_Override, 
	X.BOP_RateNumber, 
	X.BOP_RateNumber_Override, 
	X.BOP_SquareFootage, 
	X.BuildingPropertyOwnership, 
	X.CSP, 
	X.CSPOverride, 
	X.Description, 
	X.DescriptionBOP, 
	X.Eligible, 
	X.FloorAreaComputation, 
	X.OccupancyType, 
	X.OccupancyTypeMonoline, 
	X.OccupancyTypeOverride, 
	X.RateGroup, 
	X.RateGroupOverride, 
	X.RateNumberRelativity 
	FROM
	DC_BP_Occupancy X
	inner join
	cte_DCBPOccupancy Y on X.Sessionid = Y.Sessionid
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Metadata AS (
	SELECT
	BP_RiskId,
	BP_OccupancyId,
	SessionId,
	Id,
	AssociationUnitOwners,
	BOP_New_EQ,
	BOP_New_EQ_Override,
	BOP_New_EQSL,
	BOP_New_EQSL_Override,
	BOP_New_LiabClassGroup,
	BOP_New_LiabClassGroup_Override,
	BOP_New_LiabExpBase,
	BOP_New_LiabExpBase_Override,
	BOP_New_NAICS,
	BOP_New_NAICS_Override,
	BOP_New_PropRateNo,
	BOP_New_PropRateNo_Override,
	BOP_New_SIC,
	BOP_New_SIC_Override,
	BOP_PMA,
	BOP_PMA_Override,
	BOP_RateGroup,
	BOP_RateGroup_Override,
	BOP_RateNumber,
	BOP_RateNumber_Override,
	BOP_SquareFootage,
	BuildingPropertyOwnership,
	CSP,
	CSPOverride,
	Description,
	DescriptionBOP,
	Eligible,
	FloorAreaComputation,
	OccupancyType,
	OccupancyTypeMonoline,
	OccupancyTypeOverride,
	RateGroup,
	RateGroupOverride,
	RateNumberRelativity,
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId
	FROM SQ_DC_BP_Occupancy
),
DCBPOccupancyStage2 AS (
	TRUNCATE TABLE DCBPOccupancyStage;
	INSERT INTO DCBPOccupancyStage
	(BPRiskId, BPOccupancyId, SessionId, Id, AssociationUnitOwners, BOPNewEQ, BOPNewEQOverride, BOPNewEQSL, BOPNewEQSLOverride, BOPNewLiabClassGroup, BOPNewLiabClassGroupOverride, BOPNewLiabExpBase, BOPNewLiabExpBaseOverride, BOPNewNAICS, BOPNewNAICSOverride, BOPNewPropRateNo, BOPNewPropRateNoOverride, BOPNewSIC, BOPNewSICOverride, BOPPMA, BOPPMAOverride, BOPRateGroup, BOPRateGroupOverride, BOPRateNumber, BOPRateNumberOverride, BOPSquareFootage, BuildingPropertyOwnership, CSP, CSPOverride, Description, DescriptionBOP, Eligible, FloorAreaComputation, OccupancyType, OccupancyTypeMonoline, OccupancyTypeOverride, RateGroup, RateGroupOverride, RateNumberRelativity, ExtractDate, SourceSystemId)
	SELECT 
	BP_RiskId AS BPRISKID, 
	BP_OccupancyId AS BPOCCUPANCYID, 
	SESSIONID, 
	ID, 
	ASSOCIATIONUNITOWNERS, 
	BOP_New_EQ AS BOPNEWEQ, 
	BOP_New_EQ_Override AS BOPNEWEQOVERRIDE, 
	BOP_New_EQSL AS BOPNEWEQSL, 
	BOP_New_EQSL_Override AS BOPNEWEQSLOVERRIDE, 
	BOP_New_LiabClassGroup AS BOPNEWLIABCLASSGROUP, 
	BOP_New_LiabClassGroup_Override AS BOPNEWLIABCLASSGROUPOVERRIDE, 
	BOP_New_LiabExpBase AS BOPNEWLIABEXPBASE, 
	BOP_New_LiabExpBase_Override AS BOPNEWLIABEXPBASEOVERRIDE, 
	BOP_New_NAICS AS BOPNEWNAICS, 
	BOP_New_NAICS_Override AS BOPNEWNAICSOVERRIDE, 
	BOP_New_PropRateNo AS BOPNEWPROPRATENO, 
	BOP_New_PropRateNo_Override AS BOPNEWPROPRATENOOVERRIDE, 
	BOP_New_SIC AS BOPNEWSIC, 
	BOP_New_SIC_Override AS BOPNEWSICOVERRIDE, 
	BOP_PMA AS BOPPMA, 
	BOP_PMA_Override AS BOPPMAOVERRIDE, 
	BOP_RateGroup AS BOPRATEGROUP, 
	BOP_RateGroup_Override AS BOPRATEGROUPOVERRIDE, 
	BOP_RateNumber AS BOPRATENUMBER, 
	BOP_RateNumber_Override AS BOPRATENUMBEROVERRIDE, 
	BOP_SquareFootage AS BOPSQUAREFOOTAGE, 
	BUILDINGPROPERTYOWNERSHIP, 
	CSP, 
	CSPOVERRIDE, 
	DESCRIPTION, 
	DESCRIPTIONBOP, 
	ELIGIBLE, 
	FLOORAREACOMPUTATION, 
	OCCUPANCYTYPE, 
	OCCUPANCYTYPEMONOLINE, 
	OCCUPANCYTYPEOVERRIDE, 
	RATEGROUP, 
	RATEGROUPOVERRIDE, 
	RATENUMBERRELATIVITY, 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID
	FROM EXP_Metadata
),