WITH
SQ_DC_BIL_PolicyTerm AS (
	Set QUOTED_IDENTIFIER on
	SELECT DC_BIL_PolicyTerm.PolicyTermId,
	       DC_BIL_PolicyTerm.PolicyTermEffectiveDate,
	       DC_BIL_PolicyTerm.PolicyTermExpirationDate,
	       DC_BIL_PolicyTerm.PolicyReference,
	       DC_BIL_PolicyTerm.PolicyTermGroupReference,
	       DC_BIL_PolicyTerm.PrimaryAccountId,
	       DC_BIL_PolicyTerm.PolicyTermConfigTemplate,
	       NULL AS PolicyTermConfig,
	       DC_BIL_PolicyTerm.PolicyAggregationReference,
	       DC_BIL_PolicyTerm.SplitBillIndicator,
	       DC_BIL_PolicyTerm.PolicyTermStatusCode,
	       DC_BIL_PolicyTerm.AutoRescindEquityDate,
	       DC_BIL_PolicyTerm.PolicyIssueSystemCode,
	       DC_BIL_PolicyTerm.PolicyMasterCompanyCode,
	       DC_BIL_PolicyTerm.PolicyLineOfBusinessCode,
	       DC_BIL_PolicyTerm.PolicyProductCode,
	       DC_BIL_PolicyTerm.PolicyStateCode,
	       DC_BIL_PolicyTerm.PolicyCountryCode,
	       DC_BIL_PolicyTerm.IssueSystemPolicyId,
	       DC_BIL_PolicyTerm.RenewalConfigTemplate,
	       DC_BIL_PolicyTerm.RenewalConfig,
	       DC_BIL_PolicyTerm.RenewalAccountId,
	       DC_BIL_PolicyTerm.HoldTypeCode,
	       DC_BIL_PolicyTerm.HoldReasonCode,
	       DC_BIL_PolicyTerm.HoldStartDate,
	       DC_BIL_PolicyTerm.HoldEndDate,
	       DC_BIL_PolicyTerm.OutstandingBalance,
	       DC_BIL_PolicyTerm.ExpirationActivityDate,
	       DC_BIL_PolicyTerm.LastUpdatedTimestamp,
	       DC_BIL_PolicyTerm.LastUpdatedUserId,
	       DC_BIL_PolicyTerm.PolicyTermLockingTS,
	       NULL AS PolicyTermExtendedData,
	       DC_BIL_PolicyTerm.ProcessingOrgUnitCode,
	       DC_BIL_PolicyTerm.TransactionGUID,
	       ( PolicyTermConfig.value('(PolicyTermConfig/Commission/@Scheme)[1]', 'nvarchar(4)') ) AS PolicyTermConfigCommissionScheme
	FROM   DC_BIL_PolicyTerm
	WHERE  DC_BIL_PolicyTerm.LastUpdatedTimestamp >= Dateadd(DD, @{pipeline().parameters.NO_OF_DAYS}, '@{pipeline().parameters.SELECTION_START_TS}')
),
EXP_Metadata AS (
	SELECT
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	PolicyTermId,
	PolicyTermEffectiveDate,
	PolicyTermExpirationDate,
	PolicyReference,
	PolicyTermGroupReference,
	PrimaryAccountId,
	PolicyTermConfigTemplate,
	PolicyTermConfig,
	PolicyAggregationReference,
	SplitBillIndicator,
	PolicyTermStatusCode,
	AutoRescindEquityDate,
	PolicyIssueSystemCode,
	PolicyMasterCompanyCode,
	PolicyLineOfBusinessCode,
	PolicyProductCode,
	PolicyStateCode,
	PolicyCountryCode,
	IssueSystemPolicyId,
	RenewalConfigTemplate,
	RenewalConfig,
	RenewalAccountId,
	HoldTypeCode,
	HoldReasonCode,
	HoldStartDate,
	HoldEndDate,
	OutstandingBalance,
	ExpirationActivityDate,
	LastUpdatedTimestamp,
	LastUpdatedUserId,
	PolicyTermLockingTS,
	PolicyTermExtendedData,
	ProcessingOrgUnitCode,
	TransactionGUID,
	PolicyTermConfigCommissionScheme
	FROM SQ_DC_BIL_PolicyTerm
),
DCBILPolicyTermStage AS (
	TRUNCATE TABLE DCBILPolicyTermStage;
	INSERT INTO DCBILPolicyTermStage
	(ExtractDate, SourceSystemId, PolicyTermId, PolicyTermEffectiveDate, PolicyTermExpirationDate, PolicyReference, PolicyTermGroupReference, PrimaryAccountId, PolicyTermConfigTemplate, PolicyTermConfig, PolicyAggregationReference, SplitBillIndicator, PolicyTermStatusCode, AutoRescindEquityDate, PolicyIssueSystemCode, PolicyMasterCompanyCode, PolicyLineOfBusinessCode, PolicyProductCode, PolicyStateCode, PolicyCountryCode, IssueSystemPolicyId, RenewalConfigTemplate, RenewalConfig, RenewalAccountId, HoldTypeCode, HoldReasonCode, HoldStartDate, HoldEndDate, OutstandingBalance, ExpirationActivityDate, LastUpdatedTimestamp, LastUpdatedUserId, PolicyTermLockingTS, PolicyTermExtendedData, ProcessingOrgUnitCode, TransactionGUID, PolicyTermConfigCommissionScheme)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	POLICYTERMID, 
	POLICYTERMEFFECTIVEDATE, 
	POLICYTERMEXPIRATIONDATE, 
	POLICYREFERENCE, 
	POLICYTERMGROUPREFERENCE, 
	PRIMARYACCOUNTID, 
	POLICYTERMCONFIGTEMPLATE, 
	POLICYTERMCONFIG, 
	POLICYAGGREGATIONREFERENCE, 
	SPLITBILLINDICATOR, 
	POLICYTERMSTATUSCODE, 
	AUTORESCINDEQUITYDATE, 
	POLICYISSUESYSTEMCODE, 
	POLICYMASTERCOMPANYCODE, 
	POLICYLINEOFBUSINESSCODE, 
	POLICYPRODUCTCODE, 
	POLICYSTATECODE, 
	POLICYCOUNTRYCODE, 
	ISSUESYSTEMPOLICYID, 
	RENEWALCONFIGTEMPLATE, 
	RENEWALCONFIG, 
	RENEWALACCOUNTID, 
	HOLDTYPECODE, 
	HOLDREASONCODE, 
	HOLDSTARTDATE, 
	HOLDENDDATE, 
	OUTSTANDINGBALANCE, 
	EXPIRATIONACTIVITYDATE, 
	LASTUPDATEDTIMESTAMP, 
	LASTUPDATEDUSERID, 
	POLICYTERMLOCKINGTS, 
	POLICYTERMEXTENDEDDATA, 
	PROCESSINGORGUNITCODE, 
	TRANSACTIONGUID, 
	POLICYTERMCONFIGCOMMISSIONSCHEME
	FROM EXP_Metadata
),