WITH
SQ_WBBPCoverageEquipBreakdownStage AS (
	SELECT
		WBBPCoverageEquipBreakdownStageId,
		ExtractDate,
		SourceSystemId,
		CoverageId,
		WB_BP_CoverageEquipBreakdownId,
		SessionId,
		CovEquipmentBreakdownIndicator,
		PrintingPresses,
		SheetFedFiveColorAgeOfOldestPress,
		SheetFedFiveColorCaption,
		SheetFedFiveColorNumberOfPresses,
		SheetFedFourColorAgeOfOldestPress,
		SheetFedFourColorCaption,
		SheetFedFourColorNumberOfPresses,
		SheetFedMoreThanFiveColorAgeOfOldestPress,
		SheetFedMoreThanFiveColorCaption,
		SheetFedMoreThanFiveColorNumberOfPresses,
		SheetFedThreeColorAgeOfOldestPress,
		SheetFedThreeColorCaption,
		SheetFedThreeColorNumberOfPresses,
		SheetFedTwoColorAgeOfOldestPress,
		SheetFedTwoColorCaption,
		SheetFedTwoColorNumberOfPresses,
		SheetFedOneColorAgeOfOldestPress,
		SheetFedOneColorCaption,
		SheetFedOneColorNumberOfPresses,
		WebFedAgeOfOldestPress,
		WebFedCaption,
		WebFedNumberOfPresses,
		TypeOfPress,
		NumberOfPresses,
		AgeOfOldestPressInYears,
		MedicalEquipment,
		MinimumDeductibleDirectCoveragesMedical,
		MinimumDeductibleIndirectCoveragesMedical,
		MedicalEquipmentGreaterThanOneMillion,
		EquipBreakdownSetPrintingProcessValue,
		BillingLOB,
		CommissionPlanID,
		IsBillingSubline,
		ParentBillingLOB,
		PurePremium,
		TransactionCommissionType,
		TransactionCommissionValue,
		TransactionFinalCommissionValue
	FROM WBBPCoverageEquipBreakdownStage
),
EXP_Metadata AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	WBBPCoverageEquipBreakdownStageId,
	ExtractDate,
	SourceSystemId,
	CoverageId,
	WB_BP_CoverageEquipBreakdownId,
	SessionId,
	CovEquipmentBreakdownIndicator,
	-- *INF*: DECODE(CovEquipmentBreakdownIndicator,'T',1,'F',0,NULL)
	DECODE(
	    CovEquipmentBreakdownIndicator,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_CovEquipmentBreakdownIndicator,
	PrintingPresses,
	-- *INF*: DECODE(PrintingPresses,'T',1,'F',0,NULL)
	DECODE(
	    PrintingPresses,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PrintingPresses,
	SheetFedFiveColorAgeOfOldestPress,
	SheetFedFiveColorCaption,
	SheetFedFiveColorNumberOfPresses,
	SheetFedFourColorAgeOfOldestPress,
	SheetFedFourColorCaption,
	SheetFedFourColorNumberOfPresses,
	SheetFedMoreThanFiveColorAgeOfOldestPress,
	SheetFedMoreThanFiveColorCaption,
	SheetFedMoreThanFiveColorNumberOfPresses,
	SheetFedThreeColorAgeOfOldestPress,
	SheetFedThreeColorCaption,
	SheetFedThreeColorNumberOfPresses,
	SheetFedTwoColorAgeOfOldestPress,
	SheetFedTwoColorCaption,
	SheetFedTwoColorNumberOfPresses,
	SheetFedOneColorAgeOfOldestPress,
	SheetFedOneColorCaption,
	SheetFedOneColorNumberOfPresses,
	WebFedAgeOfOldestPress,
	WebFedCaption,
	WebFedNumberOfPresses,
	TypeOfPress,
	NumberOfPresses,
	AgeOfOldestPressInYears,
	MedicalEquipment,
	-- *INF*: DECODE(MedicalEquipment,'T',1,'F',0,NULL)
	DECODE(
	    MedicalEquipment,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_MedicalEquipment,
	MinimumDeductibleDirectCoveragesMedical,
	MinimumDeductibleIndirectCoveragesMedical,
	MedicalEquipmentGreaterThanOneMillion,
	-- *INF*: DECODE(MedicalEquipmentGreaterThanOneMillion,'T',1,'F',0,NULL)
	DECODE(
	    MedicalEquipmentGreaterThanOneMillion,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_MedicalEquipmentGreaterThanOneMillion,
	EquipBreakdownSetPrintingProcessValue,
	-- *INF*: DECODE(EquipBreakdownSetPrintingProcessValue,'T',1,'F',0,NULL)
	DECODE(
	    EquipBreakdownSetPrintingProcessValue,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_EquipBreakdownSetPrintingProcessValue,
	BillingLOB,
	CommissionPlanID,
	IsBillingSubline,
	-- *INF*: DECODE(IsBillingSubline,'T',1,'F',0,NULL)
	DECODE(
	    IsBillingSubline,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_IsBillingSubline,
	ParentBillingLOB,
	PurePremium,
	TransactionCommissionType,
	TransactionCommissionValue,
	TransactionFinalCommissionValue
	FROM SQ_WBBPCoverageEquipBreakdownStage
),
ArchWBBPCoverageEquipBreakdownStage AS (
	INSERT INTO ArchWBBPCoverageEquipBreakdownStage
	(ExtractDate, SourceSystemId, AuditId, WBBPCoverageEquipBreakdownStageId, CoverageId, WB_BP_CoverageEquipBreakdownId, SessionId, CovEquipmentBreakdownIndicator, PrintingPresses, SheetFedFiveColorAgeOfOldestPress, SheetFedFiveColorCaption, SheetFedFiveColorNumberOfPresses, SheetFedFourColorAgeOfOldestPress, SheetFedFourColorCaption, SheetFedFourColorNumberOfPresses, SheetFedMoreThanFiveColorAgeOfOldestPress, SheetFedMoreThanFiveColorCaption, SheetFedMoreThanFiveColorNumberOfPresses, SheetFedThreeColorAgeOfOldestPress, SheetFedThreeColorCaption, SheetFedThreeColorNumberOfPresses, SheetFedTwoColorAgeOfOldestPress, SheetFedTwoColorCaption, SheetFedTwoColorNumberOfPresses, SheetFedOneColorAgeOfOldestPress, SheetFedOneColorCaption, SheetFedOneColorNumberOfPresses, WebFedAgeOfOldestPress, WebFedCaption, WebFedNumberOfPresses, TypeOfPress, NumberOfPresses, AgeOfOldestPressInYears, MedicalEquipment, MinimumDeductibleDirectCoveragesMedical, MinimumDeductibleIndirectCoveragesMedical, MedicalEquipmentGreaterThanOneMillion, EquipBreakdownSetPrintingProcessValue, BillingLOB, CommissionPlanID, IsBillingSubline, ParentBillingLOB, PurePremium, TransactionCommissionType, TransactionCommissionValue, TransactionFinalCommissionValue)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBBPCOVERAGEEQUIPBREAKDOWNSTAGEID, 
	COVERAGEID, 
	WB_BP_COVERAGEEQUIPBREAKDOWNID, 
	SESSIONID, 
	o_CovEquipmentBreakdownIndicator AS COVEQUIPMENTBREAKDOWNINDICATOR, 
	o_PrintingPresses AS PRINTINGPRESSES, 
	SHEETFEDFIVECOLORAGEOFOLDESTPRESS, 
	SHEETFEDFIVECOLORCAPTION, 
	SHEETFEDFIVECOLORNUMBEROFPRESSES, 
	SHEETFEDFOURCOLORAGEOFOLDESTPRESS, 
	SHEETFEDFOURCOLORCAPTION, 
	SHEETFEDFOURCOLORNUMBEROFPRESSES, 
	SHEETFEDMORETHANFIVECOLORAGEOFOLDESTPRESS, 
	SHEETFEDMORETHANFIVECOLORCAPTION, 
	SHEETFEDMORETHANFIVECOLORNUMBEROFPRESSES, 
	SHEETFEDTHREECOLORAGEOFOLDESTPRESS, 
	SHEETFEDTHREECOLORCAPTION, 
	SHEETFEDTHREECOLORNUMBEROFPRESSES, 
	SHEETFEDTWOCOLORAGEOFOLDESTPRESS, 
	SHEETFEDTWOCOLORCAPTION, 
	SHEETFEDTWOCOLORNUMBEROFPRESSES, 
	SHEETFEDONECOLORAGEOFOLDESTPRESS, 
	SHEETFEDONECOLORCAPTION, 
	SHEETFEDONECOLORNUMBEROFPRESSES, 
	WEBFEDAGEOFOLDESTPRESS, 
	WEBFEDCAPTION, 
	WEBFEDNUMBEROFPRESSES, 
	TYPEOFPRESS, 
	NUMBEROFPRESSES, 
	AGEOFOLDESTPRESSINYEARS, 
	o_MedicalEquipment AS MEDICALEQUIPMENT, 
	MINIMUMDEDUCTIBLEDIRECTCOVERAGESMEDICAL, 
	MINIMUMDEDUCTIBLEINDIRECTCOVERAGESMEDICAL, 
	o_MedicalEquipmentGreaterThanOneMillion AS MEDICALEQUIPMENTGREATERTHANONEMILLION, 
	o_EquipBreakdownSetPrintingProcessValue AS EQUIPBREAKDOWNSETPRINTINGPROCESSVALUE, 
	BILLINGLOB, 
	COMMISSIONPLANID, 
	o_IsBillingSubline AS ISBILLINGSUBLINE, 
	PARENTBILLINGLOB, 
	PUREPREMIUM, 
	TRANSACTIONCOMMISSIONTYPE, 
	TRANSACTIONCOMMISSIONVALUE, 
	TRANSACTIONFINALCOMMISSIONVALUE
	FROM EXP_Metadata
),