WITH
SQ_DC_BIL_GeneralJournal AS (
	SELECT
		JournalId,
		AccountId,
		PolicyTermId,
		ActivityTypeCode,
		AccountTypeCode,
		BookingClassificationCode,
		CurrencyCulture,
		MasterCompanyCode,
		ProcessingOrgUnitCode,
		JournalTypeCode,
		JournalSubTypeCode,
		TransactionTypeCode,
		ActivityEffectiveDate,
		TransactionDate,
		AccountingClassCode,
		TransactionGrossAmount,
		TransactionNetAmount,
		PolicyIssueSystemCode,
		PolicyLineOfBusinessCode,
		PolicyStateCode,
		PolicyCountryCode,
		LastUpdatedTimestamp,
		LastUpdatedUserId,
		TargetMasterCompanyCode,
		TransactionGUID
	FROM DC_BIL_GeneralJournal
	WHERE ActivityTypeCode in ('WO', 'RCWR') and AccountingClassCode in ('AR0','AR1')
),
EXP_Metadata AS (
	SELECT
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	JournalId,
	AccountId,
	PolicyTermId,
	ActivityTypeCode,
	AccountTypeCode,
	BookingClassificationCode,
	CurrencyCulture,
	MasterCompanyCode,
	ProcessingOrgUnitCode,
	JournalTypeCode,
	JournalSubTypeCode,
	TransactionTypeCode,
	ActivityEffectiveDate,
	TransactionDate,
	AccountingClassCode,
	TransactionGrossAmount,
	TransactionNetAmount,
	PolicyIssueSystemCode,
	PolicyLineOfBusinessCode,
	PolicyStateCode,
	PolicyCountryCode,
	LastUpdatedTimestamp,
	LastUpdatedUserId,
	TargetMasterCompanyCode,
	TransactionGUID
	FROM SQ_DC_BIL_GeneralJournal
),
DCBILGeneralJounalStage AS (
	TRUNCATE TABLE DCBILGeneralJounalStage;
	INSERT INTO DCBILGeneralJounalStage
	(ExtractDate, SourceSystemId, JournalId, AccountId, PolicyTermId, ActivityTypeCode, AccountTypeCode, BookingClassificationCode, CurrencyCulture, MasterCompanyCode, ProcessingOrgUnitCode, JournalTypeCode, JournalSubTypeCode, TransactionTypeCode, ActivityEffectiveDate, TransactionDate, AccountingClassCode, TransactionGrossAmount, TransactionNetAmount, PolicyIssueSystemCode, PolicyLineOfBusinessCode, PolicyStateCode, PolicyCountryCode, LastUpdatedTimestamp, LastUpdatedUserId, TransactionGUID, TargetMasterCompanyCode)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	JOURNALID, 
	ACCOUNTID, 
	POLICYTERMID, 
	ACTIVITYTYPECODE, 
	ACCOUNTTYPECODE, 
	BOOKINGCLASSIFICATIONCODE, 
	CURRENCYCULTURE, 
	MASTERCOMPANYCODE, 
	PROCESSINGORGUNITCODE, 
	JOURNALTYPECODE, 
	JOURNALSUBTYPECODE, 
	TRANSACTIONTYPECODE, 
	ACTIVITYEFFECTIVEDATE, 
	TRANSACTIONDATE, 
	ACCOUNTINGCLASSCODE, 
	TRANSACTIONGROSSAMOUNT, 
	TRANSACTIONNETAMOUNT, 
	POLICYISSUESYSTEMCODE, 
	POLICYLINEOFBUSINESSCODE, 
	POLICYSTATECODE, 
	POLICYCOUNTRYCODE, 
	LASTUPDATEDTIMESTAMP, 
	LASTUPDATEDUSERID, 
	TRANSACTIONGUID, 
	TARGETMASTERCOMPANYCODE
	FROM EXP_Metadata
),