WITH
SQ_WorkDCTPolicy AS (
	SELECT
		WorkDCTPolicyId,
		ExtractDate,
		SourceSystemId,
		SessionId,
		PolicyId,
		PartyId,
		Name,
		FirstName,
		LastName,
		MiddleName,
		EntityType,
		FederalEmployeeIDNumber,
		SICCode,
		NAICSCode,
		Program,
		PolicyGUId,
		CustomerNum,
		PolicyNumber,
		PolicyVersion,
		PolicyVersionFormatted,
		PolicyEffectiveDate,
		PolicyExpirationDate,
		LineOfBusiness,
		Term,
		PrimaryRatingState,
		Product,
		AuditPeriod,
		CancellationDate,
		TransactionDate,
		PreviousPolicyNumber,
		InceptionDate,
		TransactionType,
		Division,
		Terrorism,
		WBProduct,
		WBProductType,
		RiskGrade,
		BCCCode,
		WBPolicyId,
		AutomaticRenewalIndicator,
		Association,
		AssociationDiscountFactor,
		LineType,
		PolicyProgram,
		PriorPolicyKey,
		RenewalPolicySymbol,
		RenewalPolicyNumber,
		RenewalPolicyMod,
		PolicyStatus,
		TransactionCreatedDate,
		TransactionEffectiveDate,
		TransactionExpirationDate,
		TransactionCancellationDate,
		ReasonCode,
		ReasonCodeCaption,
		TransactionState,
		TransactionPurpose,
		SICCodeDesc,
		NAICSCodeDesc,
		Title,
		DoingBusinessAs,
		QuoteActionTimeStamp,
		QuoteActionStatus,
		QuoteActionUserClassification,
		QuoteActionUserName,
		AgencyCode,
		IsApplicant,
		RejectedReason,
		RejectedReasonDetails,
		ProducerName,
		PhoneNumber,
		CustomerCare,
		BusinessSegmentCode,
		TransactionCreatedUserId,
		EndorsedProcessedBy AS EndorsedProcessedby,
		EstimatedQuotePremium,
		IsRollover,
		PriorCarrierName,
		PirorCarrierNameOther,
		MailPolicyToInsured,
		DataFix,
		DataFixDate,
		DataFixType,
		PolicyIssueCodeDesc,
		PolicyIssueCodeOverride,
		DeclaredEvent,
		IssuedUWID,
		IssuedUnderwriter,
		ExternalQuoteSource,
		TurnstileGenerated,
		PenguinTechGenerated,
		LCSurveyOrderedIndicator,
		LCSurveyOrderedDate,
		ExpiredReason,
		ExpiredReasonDetails
	FROM WorkDCTPolicy
),
EXp_Default AS (
	SELECT
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS audit_id,
	WorkDCTPolicyId,
	SessionId,
	PolicyId,
	PartyId,
	Name,
	FirstName,
	LastName,
	MiddleName,
	EntityType,
	FederalEmployeeIDNumber,
	SICCode,
	NAICSCode,
	Program,
	PolicyGUId,
	CustomerNum,
	PolicyNumber,
	PolicyVersion,
	PolicyVersionFormatted,
	PolicyEffectiveDate,
	PolicyExpirationDate,
	LineOfBusiness,
	Term,
	PrimaryRatingState,
	Product,
	AuditPeriod,
	CancellationDate,
	TransactionDate,
	PreviousPolicyNumber,
	InceptionDate,
	TransactionType,
	Division,
	Terrorism,
	WBProduct,
	WBProductType,
	RiskGrade,
	BCCCode,
	WBPolicyId,
	AutomaticRenewalIndicator,
	-- *INF*: DECODE(AutomaticRenewalIndicator, 'T', 1, 'F', 0, NULL)
	DECODE(
	    AutomaticRenewalIndicator,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_AutomaticRenewalIndicator,
	Association,
	AssociationDiscountFactor,
	LineType,
	PolicyProgram,
	PriorPolicyKey,
	RenewalPolicySymbol,
	RenewalPolicyNumber,
	RenewalPolicyMod,
	PolicyStatus,
	TransactionCreatedDate,
	TransactionEffectiveDate,
	TransactionExpirationDate,
	TransactionCancellationDate,
	ReasonCode,
	ReasonCodeCaption,
	TransactionState,
	TransactionPurpose,
	SICCodeDesc,
	NAICSCodeDesc,
	Title,
	DoingBusinessAs,
	QuoteActionTimeStamp,
	QuoteActionStatus,
	QuoteActionUserClassification,
	QuoteActionUserName,
	AgencyCode,
	IsApplicant,
	RejectedReason,
	RejectedReasonDetails,
	ProducerName,
	PhoneNumber,
	CustomerCare,
	BusinessSegmentCode,
	TransactionCreatedUserId,
	EndorsedProcessedby,
	EstimatedQuotePremium,
	IsRollover AS i_IsRollover,
	-- *INF*: IIF(i_IsRollover='T','1','0')
	IFF(i_IsRollover = 'T', '1', '0') AS o_IsRollover,
	PriorCarrierName,
	PirorCarrierNameOther,
	MailPolicyToInsured AS i_MailPolicyToInsured,
	-- *INF*: IIF(i_MailPolicyToInsured='T','1','0')
	IFF(i_MailPolicyToInsured = 'T', '1', '0') AS o_MailPolicyToInsured,
	DataFix,
	DataFixDate,
	DataFixType,
	PolicyIssueCodeDesc,
	PolicyIssueCodeOverride AS i_PolicyIssueCodeOverride,
	-- *INF*: DECODE(i_PolicyIssueCodeOverride, 'T', 1, 'F', 0)
	DECODE(
	    i_PolicyIssueCodeOverride,
	    'T', 1,
	    'F', 0
	) AS o_PolicyIssueCodeOverride,
	DeclaredEvent AS i_DeclaredEvent,
	-- *INF*: DECODE(i_DeclaredEvent, 'T', 1, 'F', 0,Null)
	DECODE(
	    i_DeclaredEvent,
	    'T', 1,
	    'F', 0,
	    Null
	) AS o_DeclaredEvent,
	IssuedUWID,
	IssuedUnderwriter,
	ExternalQuoteSource,
	TurnstileGenerated AS i_TurnstileGenerated,
	-- *INF*: DECODE(i_TurnstileGenerated, 'T', 1, 'F', 0)
	DECODE(
	    i_TurnstileGenerated,
	    'T', 1,
	    'F', 0
	) AS o_TurnstileGenerated,
	PenguinTechGenerated AS i_PenguinTechGenerated,
	-- *INF*: DECODE(i_PenguinTechGenerated, 'T', 1, 'F', 0)
	DECODE(
	    i_PenguinTechGenerated,
	    'T', 1,
	    'F', 0
	) AS o_PenguinTechGenerated,
	LCSurveyOrderedIndicator,
	-- *INF*: DECODE(LCSurveyOrderedIndicator, 'T', '1', 'F', '0',Null)
	DECODE(
	    LCSurveyOrderedIndicator,
	    'T', '1',
	    'F', '0',
	    Null
	) AS o_LCSurveyOrderedIndicator,
	LCSurveyOrderedDate,
	ExpiredReason,
	ExpiredReasonDetails
	FROM SQ_WorkDCTPolicy
),
ArchWorkDCTPolicy AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWorkDCTPolicy
	(ExtractDate, SourceSystemId, AuditId, WorkDCTPolicyId, SessionId, PolicyId, PartyId, Name, FirstName, LastName, MiddleName, EntityType, FederalEmployeeIDNumber, SICCode, NAICSCode, Program, PolicyGUId, CustomerNum, PolicyNumber, PolicyVersion, PolicyVersionFormatted, PolicyEffectiveDate, PolicyExpirationDate, LineOfBusiness, Term, PrimaryRatingState, Product, AuditPeriod, CancellationDate, TransactionDate, PreviousPolicyNumber, InceptionDate, TransactionType, Division, Terrorism, WBProduct, WBProductType, RiskGrade, BCCCode, WBPolicyId, AutomaticRenewalIndicator, Association, AssociationDiscountFactor, LineType, PolicyProgram, PriorPolicyKey, RenewalPolicySymbol, RenewalPolicyNumber, RenewalPolicyMod, PolicyStatus, TransactionCreatedDate, TransactionEffectiveDate, TransactionExpirationDate, TransactionCancellationDate, ReasonCode, ReasonCodeCaption, TransactionState, TransactionPurpose, SICCodeDesc, NAICSCodeDesc, Title, DoingBusinessAs, QuoteActionTimeStamp, QuoteActionStatus, QuoteActionUserClassification, QuoteActionUserName, AgencyCode, IsApplicant, RejectedReason, RejectedReasonDetails, ProducerName, PhoneNumber, CustomerCare, BusinessSegmentCode, TransactionCreatedUserId, EndorsedProcessedBy, EstimatedQuotePremium, IsRollover, PriorCarrierName, PirorCarrierNameOther, MailPolicyToInsured, DataFix, DataFixDate, DataFixType, PolicyIssueCodeDesc, PolicyIssueCodeOverride, DeclaredEvent, IssuedUWID, IssuedUnderwriter, ExternalQuoteSource, TurnstileGenerated, PenguinTechGenerated, LCSurveyOrderedIndicator, LCSurveyOrderedDate, ExpiredReason, ExpiredReasonDetails)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	audit_id AS AUDITID, 
	WORKDCTPOLICYID, 
	SESSIONID, 
	POLICYID, 
	PARTYID, 
	NAME, 
	FIRSTNAME, 
	LASTNAME, 
	MIDDLENAME, 
	ENTITYTYPE, 
	FEDERALEMPLOYEEIDNUMBER, 
	SICCODE, 
	NAICSCODE, 
	PROGRAM, 
	POLICYGUID, 
	CUSTOMERNUM, 
	POLICYNUMBER, 
	POLICYVERSION, 
	POLICYVERSIONFORMATTED, 
	POLICYEFFECTIVEDATE, 
	POLICYEXPIRATIONDATE, 
	LINEOFBUSINESS, 
	TERM, 
	PRIMARYRATINGSTATE, 
	PRODUCT, 
	AUDITPERIOD, 
	CANCELLATIONDATE, 
	TRANSACTIONDATE, 
	PREVIOUSPOLICYNUMBER, 
	INCEPTIONDATE, 
	TRANSACTIONTYPE, 
	DIVISION, 
	TERRORISM, 
	WBPRODUCT, 
	WBPRODUCTTYPE, 
	RISKGRADE, 
	BCCCODE, 
	WBPOLICYID, 
	o_AutomaticRenewalIndicator AS AUTOMATICRENEWALINDICATOR, 
	ASSOCIATION, 
	ASSOCIATIONDISCOUNTFACTOR, 
	LINETYPE, 
	POLICYPROGRAM, 
	PRIORPOLICYKEY, 
	RENEWALPOLICYSYMBOL, 
	RENEWALPOLICYNUMBER, 
	RENEWALPOLICYMOD, 
	POLICYSTATUS, 
	TRANSACTIONCREATEDDATE, 
	TRANSACTIONEFFECTIVEDATE, 
	TRANSACTIONEXPIRATIONDATE, 
	TRANSACTIONCANCELLATIONDATE, 
	REASONCODE, 
	REASONCODECAPTION, 
	TRANSACTIONSTATE, 
	TRANSACTIONPURPOSE, 
	SICCODEDESC, 
	NAICSCODEDESC, 
	TITLE, 
	DOINGBUSINESSAS, 
	QUOTEACTIONTIMESTAMP, 
	QUOTEACTIONSTATUS, 
	QUOTEACTIONUSERCLASSIFICATION, 
	QUOTEACTIONUSERNAME, 
	AGENCYCODE, 
	ISAPPLICANT, 
	REJECTEDREASON, 
	REJECTEDREASONDETAILS, 
	PRODUCERNAME, 
	PHONENUMBER, 
	CUSTOMERCARE, 
	BUSINESSSEGMENTCODE, 
	TRANSACTIONCREATEDUSERID, 
	EndorsedProcessedby AS ENDORSEDPROCESSEDBY, 
	ESTIMATEDQUOTEPREMIUM, 
	o_IsRollover AS ISROLLOVER, 
	PRIORCARRIERNAME, 
	PIRORCARRIERNAMEOTHER, 
	o_MailPolicyToInsured AS MAILPOLICYTOINSURED, 
	DATAFIX, 
	DATAFIXDATE, 
	DATAFIXTYPE, 
	POLICYISSUECODEDESC, 
	o_PolicyIssueCodeOverride AS POLICYISSUECODEOVERRIDE, 
	o_DeclaredEvent AS DECLAREDEVENT, 
	ISSUEDUWID, 
	ISSUEDUNDERWRITER, 
	EXTERNALQUOTESOURCE, 
	o_TurnstileGenerated AS TURNSTILEGENERATED, 
	o_PenguinTechGenerated AS PENGUINTECHGENERATED, 
	o_LCSurveyOrderedIndicator AS LCSURVEYORDEREDINDICATOR, 
	LCSURVEYORDEREDDATE, 
	EXPIREDREASON, 
	EXPIREDREASONDETAILS
	FROM EXp_Default
),