WITH
SQ_WB_CU_UmbrellaCommercialAuto AS (
	WITH cte_WBCUUmbrellaCommercialAuto(Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.CU_UmbrellaCommercialAutoId, 
	X.WB_CU_UmbrellaCommercialAutoId, 
	X.SessionId, 
	X.Deleted, 
	X.AggregateLimit, 
	X.LiabilityLimitEachAccidentGarageOperationsAutoOnly, 
	X.LiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly, 
	X.PersonalInjury, 
	X.OtherDescription, 
	X.HiredNonOwnedOnlyPremium, 
	X.HiredNonOwnedOnlyPremiumAudited, 
	X.LocalOwnerOperatorPremium, 
	X.LocalOwnerOperatorPremiumAudited, 
	X.IntermediateOwnerOperatorPremium, 
	X.IntermediateOwnerOperatorPremiumAudited, 
	X.LongHaulOwnerOperatorPremium, 
	X.LongHaulOwnerOperatorPremiumAudited, 
	X.GarageLiabilityPremium, 
	X.GarageLiabilityPremiumAudited, 
	X.FirstMillionBasePremium, 
	X.ExtraHeavyTruckTractorPremiumAudited, 
	X.ExtraHeavyTruckTractorPremium, 
	X.ReinsurancePremium, 
	X.FirstMillionBasePremiumForGarage, 
	X.FirstMillionBasePremiumForRatingWorksheetModifiedPremium, 
	X.BusCount, 
	X.BusCountAudited, 
	X.LocalOwnerOperatorCount, 
	X.LocalOwnerOperatorCountAudited, 
	X.IntermediateOwnerOperatorCount, 
	X.IntermediateOwnerOperatorCountAudited, 
	X.LongHaulOwnerOperatorCount, 
	X.LongHaulOwnerOperatorCountAudited, 
	X.ExtraHeavyTruckTractorCountAudited, 
	X.ExtraHeavyTruckTractorCount, 
	X.PrivatePassengerPremiumOverride, 
	X.LightVehiclePremiumOverride, 
	X.MediumVehiclePremiumOverride, 
	X.HeavyVehiclePremiumOverride, 
	X.ExtraHeavyVehiclePremiumOverride, 
	X.BusPremiumOverride, 
	X.HiredNonOwnedOnlyPremiumOverride, 
	X.GarageLiabilityPremiumOverride, 
	X.AllOtherPremiumOverride, 
	X.ExtraHeavyTruckTractorPremiumOverride, 
	X.PrivatePassengerRevisedPremium, 
	X.LightVehicleRevisedPremium, 
	X.MediumVehicleRevisedPremium, 
	X.HeavyVehicleRevisedPremium, 
	X.ExtraHeavyVehicleRevisedPremium, 
	X.BusRevisedPremium, 
	X.HiredNonOwnedOnlyRevisedPremium, 
	X.AllOtherRevisedPremium, 
	X.GarageLiabilityRevisedPremium, 
	X.ExtraHeavyTruckTractorRevisedPremium, 
	X.ScheduledModification, 
	X.FirstMillionModifiedPremium, 
	X.ReinsuranceFactor, 
	X.OriginalLiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly, 
	X.OriginalLiabilityLimitEachAccidentGarageOperationsAutoOnly, 
	X.GarageLiabilityLimitsHeader, 
	X.IDField, 
	X.AutoLocationScheduleModDispersionComment, 
	X.AutoLocationScheduleModDispersionModification, 
	X.AutoLocationScheduleModEmployeesComment, 
	X.AutoLocationScheduleModEmployeesModification, 
	X.AutoLocationScheduleModEquipmentComment, 
	X.AutoLocationScheduleModEquipmentModification, 
	X.AutoLocationScheduleModManagementComment, 
	X.AutoLocationScheduleModManagementModification, 
	X.AutoLocationScheduleModProtectionComment, 
	X.AutoLocationScheduleModProtectionModification, 
	X.AutoLocationScheduleModSafetyComment, 
	X.AutoLocationScheduleModSafetyModification, 
	X.ModificationTotal, 
	X.ModificationTotalForAutoDetailPage 
	FROM
	WB_CU_UmbrellaCommercialAuto X
	inner join
	cte_WBCUUmbrellaCommercialAuto Y on X.Sessionid = Y.Sessionid
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Metadata AS (
	SELECT
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	CU_UmbrellaCommercialAutoId,
	WB_CU_UmbrellaCommercialAutoId,
	SessionId,
	Deleted,
	-- *INF*: DECODE(Deleted,'T',1,'F',0,NULL)
	DECODE(
	    Deleted,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS Deleted_out,
	AggregateLimit,
	LiabilityLimitEachAccidentGarageOperationsAutoOnly,
	LiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly,
	PersonalInjury,
	OtherDescription,
	HiredNonOwnedOnlyPremium,
	HiredNonOwnedOnlyPremiumAudited,
	LocalOwnerOperatorPremium,
	LocalOwnerOperatorPremiumAudited,
	IntermediateOwnerOperatorPremium,
	IntermediateOwnerOperatorPremiumAudited,
	LongHaulOwnerOperatorPremium,
	LongHaulOwnerOperatorPremiumAudited,
	GarageLiabilityPremium,
	GarageLiabilityPremiumAudited,
	FirstMillionBasePremium,
	ExtraHeavyTruckTractorPremiumAudited,
	ExtraHeavyTruckTractorPremium,
	ReinsurancePremium,
	FirstMillionBasePremiumForGarage,
	FirstMillionBasePremiumForRatingWorksheetModifiedPremium,
	BusCount,
	BusCountAudited,
	LocalOwnerOperatorCount,
	LocalOwnerOperatorCountAudited,
	IntermediateOwnerOperatorCount,
	IntermediateOwnerOperatorCountAudited,
	LongHaulOwnerOperatorCount,
	LongHaulOwnerOperatorCountAudited,
	ExtraHeavyTruckTractorCountAudited,
	ExtraHeavyTruckTractorCount,
	PrivatePassengerPremiumOverride,
	-- *INF*: DECODE(PrivatePassengerPremiumOverride,'T','1','F','0',NULL)
	DECODE(
	    PrivatePassengerPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS PrivatePassengerPremiumOverride_out,
	LightVehiclePremiumOverride,
	-- *INF*: DECODE(LightVehiclePremiumOverride,'T','1','F','0',NULL)
	DECODE(
	    LightVehiclePremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS LightVehiclePremiumOverride_out,
	MediumVehiclePremiumOverride,
	-- *INF*: decode(MediumVehiclePremiumOverride,'T','1','F','0',NULL)
	decode(
	    MediumVehiclePremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS MediumVehiclePremiumOverride_out,
	HeavyVehiclePremiumOverride,
	-- *INF*: decode(HeavyVehiclePremiumOverride,'T','1','F','0',NULL)
	decode(
	    HeavyVehiclePremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS HeavyVehiclePremiumOverride_out,
	ExtraHeavyVehiclePremiumOverride,
	-- *INF*: decode(ExtraHeavyVehiclePremiumOverride,'T','1','F','0',NULL)
	decode(
	    ExtraHeavyVehiclePremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS ExtraHeavyVehiclePremiumOverride_out,
	BusPremiumOverride,
	-- *INF*: decode(BusPremiumOverride,'T','1','F','0',NULL)
	decode(
	    BusPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS BusPremiumOverride_out,
	HiredNonOwnedOnlyPremiumOverride,
	-- *INF*: decode(HiredNonOwnedOnlyPremiumOverride,'T','1','F','0',NULL)
	decode(
	    HiredNonOwnedOnlyPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS HiredNonOwnedOnlyPremiumOverride_out,
	GarageLiabilityPremiumOverride,
	-- *INF*: decode(GarageLiabilityPremiumOverride,'T','1','F','0',NULL)
	decode(
	    GarageLiabilityPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS GarageLiabilityPremiumOverride_out,
	AllOtherPremiumOverride,
	-- *INF*: decode(AllOtherPremiumOverride,'T','1','F','0',NULL)
	decode(
	    AllOtherPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS AllOtherPremiumOverride_out,
	ExtraHeavyTruckTractorPremiumOverride,
	-- *INF*: decode(ExtraHeavyTruckTractorPremiumOverride,'T','1','F','0',NULL)
	decode(
	    ExtraHeavyTruckTractorPremiumOverride,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS ExtraHeavyTruckTractorPremiumOverride_out,
	PrivatePassengerRevisedPremium,
	LightVehicleRevisedPremium,
	MediumVehicleRevisedPremium,
	HeavyVehicleRevisedPremium,
	ExtraHeavyVehicleRevisedPremium,
	BusRevisedPremium,
	HiredNonOwnedOnlyRevisedPremium,
	AllOtherRevisedPremium,
	GarageLiabilityRevisedPremium,
	ExtraHeavyTruckTractorRevisedPremium,
	ScheduledModification,
	FirstMillionModifiedPremium,
	ReinsuranceFactor,
	OriginalLiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly,
	OriginalLiabilityLimitEachAccidentGarageOperationsAutoOnly,
	GarageLiabilityLimitsHeader,
	IDField,
	AutoLocationScheduleModDispersionComment,
	AutoLocationScheduleModDispersionModification,
	AutoLocationScheduleModEmployeesComment,
	AutoLocationScheduleModEmployeesModification,
	AutoLocationScheduleModEquipmentComment,
	AutoLocationScheduleModEquipmentModification,
	AutoLocationScheduleModManagementComment,
	AutoLocationScheduleModManagementModification,
	AutoLocationScheduleModProtectionComment,
	AutoLocationScheduleModProtectionModification,
	AutoLocationScheduleModSafetyComment,
	AutoLocationScheduleModSafetyModification,
	ModificationTotal,
	ModificationTotalForAutoDetailPage
	FROM SQ_WB_CU_UmbrellaCommercialAuto
),
WBCUUmbrellaCommercialAutoStaging AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCUUmbrellaCommercialAutoStaging;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCUUmbrellaCommercialAutoStaging
	(ExtractDate, SourceSystemId, CU_UmbrellaCommercialAutoId, WB_CU_UmbrellaCommercialAutoId, SessionId, Deleted, AggregateLimit, LiabilityLimitEachAccidentGarageOperationsAutoOnly, LiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly, PersonalInjury, OtherDescription, HiredNonOwnedOnlyPremium, HiredNonOwnedOnlyPremiumAudited, LocalOwnerOperatorPremium, LocalOwnerOperatorPremiumAudited, IntermediateOwnerOperatorPremium, IntermediateOwnerOperatorPremiumAudited, LongHaulOwnerOperatorPremium, LongHaulOwnerOperatorPremiumAudited, GarageLiabilityPremium, GarageLiabilityPremiumAudited, FirstMillionBasePremium, ExtraHeavyTruckTractorPremiumAudited, ExtraHeavyTruckTractorPremium, ReinsurancePremium, FirstMillionBasePremiumForGarage, FirstMillionBasePremiumForRatingWorksheetModifiedPremium, BusCount, BusCountAudited, LocalOwnerOperatorCount, LocalOwnerOperatorCountAudited, IntermediateOwnerOperatorCount, IntermediateOwnerOperatorCountAudited, LongHaulOwnerOperatorCount, LongHaulOwnerOperatorCountAudited, ExtraHeavyTruckTractorCountAudited, ExtraHeavyTruckTractorCount, PrivatePassengerPremiumOverride, LightVehiclePremiumOverride, MediumVehiclePremiumOverride, HeavyVehiclePremiumOverride, ExtraHeavyVehiclePremiumOverride, BusPremiumOverride, HiredNonOwnedOnlyPremiumOverride, GarageLiabilityPremiumOverride, AllOtherPremiumOverride, ExtraHeavyTruckTractorPremiumOverride, PrivatePassengerRevisedPremium, LightVehicleRevisedPremium, MediumVehicleRevisedPremium, HeavyVehicleRevisedPremium, ExtraHeavyVehicleRevisedPremium, BusRevisedPremium, HiredNonOwnedOnlyRevisedPremium, AllOtherRevisedPremium, GarageLiabilityRevisedPremium, ExtraHeavyTruckTractorRevisedPremium, ScheduledModification, FirstMillionModifiedPremium, ReinsuranceFactor, OriginalLiabilityLimitEachAccidentGarageOperationsOtherThanAutoOnly, OriginalLiabilityLimitEachAccidentGarageOperationsAutoOnly, GarageLiabilityLimitsHeader, IDField, AutoLocationScheduleModDispersionComment, AutoLocationScheduleModDispersionModification, AutoLocationScheduleModEmployeesComment, AutoLocationScheduleModEmployeesModification, AutoLocationScheduleModEquipmentComment, AutoLocationScheduleModEquipmentModification, AutoLocationScheduleModManagementComment, AutoLocationScheduleModManagementModification, AutoLocationScheduleModProtectionComment, AutoLocationScheduleModProtectionModification, AutoLocationScheduleModSafetyComment, AutoLocationScheduleModSafetyModification, ModificationTotal, ModificationTotalForAutoDetailPage)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	CU_UMBRELLACOMMERCIALAUTOID, 
	WB_CU_UMBRELLACOMMERCIALAUTOID, 
	SESSIONID, 
	Deleted_out AS DELETED, 
	AGGREGATELIMIT, 
	LIABILITYLIMITEACHACCIDENTGARAGEOPERATIONSAUTOONLY, 
	LIABILITYLIMITEACHACCIDENTGARAGEOPERATIONSOTHERTHANAUTOONLY, 
	PERSONALINJURY, 
	OTHERDESCRIPTION, 
	HIREDNONOWNEDONLYPREMIUM, 
	HIREDNONOWNEDONLYPREMIUMAUDITED, 
	LOCALOWNEROPERATORPREMIUM, 
	LOCALOWNEROPERATORPREMIUMAUDITED, 
	INTERMEDIATEOWNEROPERATORPREMIUM, 
	INTERMEDIATEOWNEROPERATORPREMIUMAUDITED, 
	LONGHAULOWNEROPERATORPREMIUM, 
	LONGHAULOWNEROPERATORPREMIUMAUDITED, 
	GARAGELIABILITYPREMIUM, 
	GARAGELIABILITYPREMIUMAUDITED, 
	FIRSTMILLIONBASEPREMIUM, 
	EXTRAHEAVYTRUCKTRACTORPREMIUMAUDITED, 
	EXTRAHEAVYTRUCKTRACTORPREMIUM, 
	REINSURANCEPREMIUM, 
	FIRSTMILLIONBASEPREMIUMFORGARAGE, 
	FIRSTMILLIONBASEPREMIUMFORRATINGWORKSHEETMODIFIEDPREMIUM, 
	BUSCOUNT, 
	BUSCOUNTAUDITED, 
	LOCALOWNEROPERATORCOUNT, 
	LOCALOWNEROPERATORCOUNTAUDITED, 
	INTERMEDIATEOWNEROPERATORCOUNT, 
	INTERMEDIATEOWNEROPERATORCOUNTAUDITED, 
	LONGHAULOWNEROPERATORCOUNT, 
	LONGHAULOWNEROPERATORCOUNTAUDITED, 
	EXTRAHEAVYTRUCKTRACTORCOUNTAUDITED, 
	EXTRAHEAVYTRUCKTRACTORCOUNT, 
	PrivatePassengerPremiumOverride_out AS PRIVATEPASSENGERPREMIUMOVERRIDE, 
	LightVehiclePremiumOverride_out AS LIGHTVEHICLEPREMIUMOVERRIDE, 
	MediumVehiclePremiumOverride_out AS MEDIUMVEHICLEPREMIUMOVERRIDE, 
	HeavyVehiclePremiumOverride_out AS HEAVYVEHICLEPREMIUMOVERRIDE, 
	ExtraHeavyVehiclePremiumOverride_out AS EXTRAHEAVYVEHICLEPREMIUMOVERRIDE, 
	BusPremiumOverride_out AS BUSPREMIUMOVERRIDE, 
	HiredNonOwnedOnlyPremiumOverride_out AS HIREDNONOWNEDONLYPREMIUMOVERRIDE, 
	GarageLiabilityPremiumOverride_out AS GARAGELIABILITYPREMIUMOVERRIDE, 
	AllOtherPremiumOverride_out AS ALLOTHERPREMIUMOVERRIDE, 
	ExtraHeavyTruckTractorPremiumOverride_out AS EXTRAHEAVYTRUCKTRACTORPREMIUMOVERRIDE, 
	PRIVATEPASSENGERREVISEDPREMIUM, 
	LIGHTVEHICLEREVISEDPREMIUM, 
	MEDIUMVEHICLEREVISEDPREMIUM, 
	HEAVYVEHICLEREVISEDPREMIUM, 
	EXTRAHEAVYVEHICLEREVISEDPREMIUM, 
	BUSREVISEDPREMIUM, 
	HIREDNONOWNEDONLYREVISEDPREMIUM, 
	ALLOTHERREVISEDPREMIUM, 
	GARAGELIABILITYREVISEDPREMIUM, 
	EXTRAHEAVYTRUCKTRACTORREVISEDPREMIUM, 
	SCHEDULEDMODIFICATION, 
	FIRSTMILLIONMODIFIEDPREMIUM, 
	REINSURANCEFACTOR, 
	ORIGINALLIABILITYLIMITEACHACCIDENTGARAGEOPERATIONSOTHERTHANAUTOONLY, 
	ORIGINALLIABILITYLIMITEACHACCIDENTGARAGEOPERATIONSAUTOONLY, 
	GARAGELIABILITYLIMITSHEADER, 
	IDFIELD, 
	AUTOLOCATIONSCHEDULEMODDISPERSIONCOMMENT, 
	AUTOLOCATIONSCHEDULEMODDISPERSIONMODIFICATION, 
	AUTOLOCATIONSCHEDULEMODEMPLOYEESCOMMENT, 
	AUTOLOCATIONSCHEDULEMODEMPLOYEESMODIFICATION, 
	AUTOLOCATIONSCHEDULEMODEQUIPMENTCOMMENT, 
	AUTOLOCATIONSCHEDULEMODEQUIPMENTMODIFICATION, 
	AUTOLOCATIONSCHEDULEMODMANAGEMENTCOMMENT, 
	AUTOLOCATIONSCHEDULEMODMANAGEMENTMODIFICATION, 
	AUTOLOCATIONSCHEDULEMODPROTECTIONCOMMENT, 
	AUTOLOCATIONSCHEDULEMODPROTECTIONMODIFICATION, 
	AUTOLOCATIONSCHEDULEMODSAFETYCOMMENT, 
	AUTOLOCATIONSCHEDULEMODSAFETYMODIFICATION, 
	MODIFICATIONTOTAL, 
	MODIFICATIONTOTALFORAUTODETAILPAGE
	FROM EXP_Metadata
),