WITH
SQ_WorkDCTTransactionInsuranceLineLocationBridge AS (
	SELECT
		WorkDCTTransactionInsuranceLineLocationBridgeId,
		ExtractDate,
		SourceSystemId,
		LocationAssociationId,
		SessionId,
		LineId,
		IndividualRiskPremiumModification,
		CoverageId,
		CoverageRiskType,
		CoverageForm,
		RiskId,
		RiskType,
		Exposure,
		CommissionPercentage,
		CoverageVersion,
		SpecialClassLevel1,
		BuildingNumber,
		PolicyCoverage,
		CauseOfLoss,
		ILFTableAssignmentCode,
		OccupancyType,
		RetroactiveDate,
		OrginalPackageModifier,
		YearBuilt,
		ExperienceModEffectiveDate,
		ConstructionCode,
		RateEffectiveDate,
		RatingPlan,
		ProtectionClass,
		MultipleLocationCreditFactor,
		PreferredPropertyCreditFactor,
		PerilGroup,
		WindCoverageIndicator,
		VehicleNumber,
		PredominantPersonalPropertyRateNumber,
		PredominantLiabilityLiabClassGroup,
		ExposureBasis,
		SprinkerFlag AS SprinklerFlag,
		FullCoverageGlass,
		ISOOccupancyType,
		OccupancyClassDescription,
		ActiveBuildingFlag,
		RateType,
		PropertyType,
		OccupancyCategory,
		CensusBlockGroup,
		Latitude,
		Longitude,
		RatingTerritoryCode,
		PredominantBuildingBCCCode,
		PredominantBuildingClassCodeDescription
	FROM WorkDCTTransactionInsuranceLineLocationBridge
),
EXp_Default AS (
	SELECT
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS audit_id,
	WorkDCTTransactionInsuranceLineLocationBridgeId,
	LocationAssociationId,
	SessionId,
	LineId,
	IndividualRiskPremiumModification,
	CoverageId,
	CoverageRiskType,
	CoverageForm,
	RiskId,
	RiskType,
	Exposure,
	CommissionPercentage,
	CoverageVersion,
	SpecialClassLevel1,
	BuildingNumber,
	PolicyCoverage,
	CauseOfLoss,
	ILFTableAssignmentCode,
	OccupancyType,
	RetroactiveDate,
	OrginalPackageModifier,
	YearBuilt,
	ExperienceModEffectiveDate,
	ConstructionCode,
	RateEffectiveDate,
	RatingPlan,
	ProtectionClass,
	MultipleLocationCreditFactor,
	PreferredPropertyCreditFactor,
	PerilGroup,
	WindCoverageIndicator,
	-- *INF*: DECODE(WindCoverageIndicator, 'T', 1, 'F', 0, NULL)
	DECODE(
	    WindCoverageIndicator,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_WindCoverageIndicator,
	VehicleNumber,
	PredominantPersonalPropertyRateNumber,
	PredominantLiabilityLiabClassGroup,
	ExposureBasis,
	SprinklerFlag,
	-- *INF*: DECODE(SprinklerFlag,'T', 1, 'F', 0, NULL)
	DECODE(
	    SprinklerFlag,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_SprinklerFlag,
	FullCoverageGlass AS i_FullCoverageGlass,
	-- *INF*: DECODE(i_FullCoverageGlass,'T','1','F','0',NULL)
	DECODE(
	    i_FullCoverageGlass,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_FullCoverageGlass,
	ISOOccupancyType,
	OccupancyClassDescription,
	ActiveBuildingFlag AS i_ActiveBuildingFlag,
	-- *INF*: DECODE(i_ActiveBuildingFlag,'T', '1', 'F', '0', NULL)
	DECODE(
	    i_ActiveBuildingFlag,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_ActiveBuildingFlag,
	RateType,
	PropertyType,
	OccupancyCategory,
	CensusBlockGroup,
	Latitude,
	Longitude,
	RatingTerritoryCode,
	PredominantBuildingBCCCode,
	PredominantBuildingClassCodeDescription
	FROM SQ_WorkDCTTransactionInsuranceLineLocationBridge
),
ArchWorkDCTTransactionInsuranceLineLocationBridge AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWorkDCTTransactionInsuranceLineLocationBridge
	(ExtractDate, SourceSystemId, AuditId, WorkDCTTransactionInsuranceLineLocationBridgeId, LocationAssociationId, SessionId, LineId, IndividualRiskPremiumModification, CoverageId, CoverageRiskType, CoverageForm, RiskId, RiskType, Exposure, CommissionPercentage, CoverageVersion, SpecialClassLevel1, BuildingNumber, PolicyCoverage, CauseOfLoss, ILFTableAssignmentCode, OccupancyType, RetroactiveDate, OrginalPackageModifier, YearBuilt, ExperienceModEffectiveDate, ConstructionCode, RateEffectiveDate, RatingPlan, ProtectionClass, MultipleLocationCreditFactor, PreferredPropertyCreditFactor, PerilGroup, WindCoverageIndicator, VehicleNumber, ExposureBasis, SprinkerFlag, PredominantPersonalPropertyRateNumber, PredominantLiabilityLiabClassGroup, FullCoverageGlass, ISOOccupancyType, OccupancyClassDescription, ActiveBuildingFlag, RateType, PropertyType, OccupancyCategory, CensusBlockGroup, Latitude, Longitude, RatingTerritoryCode, PredominantBuildingBCCCode, PredominantBuildingClassCodeDescription)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	audit_id AS AUDITID, 
	WORKDCTTRANSACTIONINSURANCELINELOCATIONBRIDGEID, 
	LOCATIONASSOCIATIONID, 
	SESSIONID, 
	LINEID, 
	INDIVIDUALRISKPREMIUMMODIFICATION, 
	COVERAGEID, 
	COVERAGERISKTYPE, 
	COVERAGEFORM, 
	RISKID, 
	RISKTYPE, 
	EXPOSURE, 
	COMMISSIONPERCENTAGE, 
	COVERAGEVERSION, 
	SPECIALCLASSLEVEL1, 
	BUILDINGNUMBER, 
	POLICYCOVERAGE, 
	CAUSEOFLOSS, 
	ILFTABLEASSIGNMENTCODE, 
	OCCUPANCYTYPE, 
	RETROACTIVEDATE, 
	ORGINALPACKAGEMODIFIER, 
	YEARBUILT, 
	EXPERIENCEMODEFFECTIVEDATE, 
	CONSTRUCTIONCODE, 
	RATEEFFECTIVEDATE, 
	RATINGPLAN, 
	PROTECTIONCLASS, 
	MULTIPLELOCATIONCREDITFACTOR, 
	PREFERREDPROPERTYCREDITFACTOR, 
	PERILGROUP, 
	o_WindCoverageIndicator AS WINDCOVERAGEINDICATOR, 
	VEHICLENUMBER, 
	EXPOSUREBASIS, 
	o_SprinklerFlag AS SPRINKERFLAG, 
	PREDOMINANTPERSONALPROPERTYRATENUMBER, 
	PREDOMINANTLIABILITYLIABCLASSGROUP, 
	o_FullCoverageGlass AS FULLCOVERAGEGLASS, 
	ISOOCCUPANCYTYPE, 
	OCCUPANCYCLASSDESCRIPTION, 
	o_ActiveBuildingFlag AS ACTIVEBUILDINGFLAG, 
	RATETYPE, 
	PROPERTYTYPE, 
	OCCUPANCYCATEGORY, 
	CENSUSBLOCKGROUP, 
	LATITUDE, 
	LONGITUDE, 
	RATINGTERRITORYCODE, 
	PREDOMINANTBUILDINGBCCCODE, 
	PREDOMINANTBUILDINGCLASSCODEDESCRIPTION
	FROM EXp_Default
),