WITH
SQ_DCCAPublicStage AS (
	SELECT
		DCCAPublicStageId,
		ExtractDate,
		SourceSystemid,
		CA_RiskId,
		CA_PublicId,
		SessionId,
		Id,
		Auditable,
		CharterRegPlates,
		IndividuallyOwnedLimousine,
		Jitneys,
		MigrantFarmWorkersTransportation,
		MileageAudit,
		MileageEstimate,
		MileageTotal,
		MileageTotalAudit,
		MileageTotalEstimate,
		PublicGroupType,
		PublicType,
		RideSharing,
		RiskPublicInputNYBlackCar,
		SeatingCapacity,
		MechanicalLift
	FROM DCCAPublicStage
),
EXP_TRANS AS (
	SELECT
	DCCAPublicStageId,
	ExtractDate,
	SourceSystemid,
	CA_RiskId,
	CA_PublicId,
	SessionId,
	Id,
	Auditable,
	CharterRegPlates,
	IndividuallyOwnedLimousine,
	Jitneys,
	MigrantFarmWorkersTransportation,
	MileageAudit,
	MileageEstimate,
	MileageTotal,
	MileageTotalAudit,
	MileageTotalEstimate,
	PublicGroupType,
	PublicType,
	RideSharing,
	RiskPublicInputNYBlackCar,
	SeatingCapacity,
	MechanicalLift,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_DCCAPublicStage
),
ArchDCCAPublicStage AS (
	INSERT INTO ArchDCCAPublicStage
	(ExtractDate, SourceSystemId, AuditId, DCCAPublicStageId, CA_RiskId, CA_PublicId, SessionId, Id, Auditable, CharterRegPlates, IndividuallyOwnedLimousine, Jitneys, MigrantFarmWorkersTransportation, MileageAudit, MileageEstimate, MileageTotal, MileageTotalAudit, MileageTotalEstimate, PublicGroupType, PublicType, RideSharing, RiskPublicInputNYBlackCar, SeatingCapacity, MechanicalLift)
	SELECT 
	EXTRACTDATE, 
	SourceSystemid AS SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	DCCAPUBLICSTAGEID, 
	CA_RISKID, 
	CA_PUBLICID, 
	SESSIONID, 
	ID, 
	AUDITABLE, 
	CHARTERREGPLATES, 
	INDIVIDUALLYOWNEDLIMOUSINE, 
	JITNEYS, 
	MIGRANTFARMWORKERSTRANSPORTATION, 
	MILEAGEAUDIT, 
	MILEAGEESTIMATE, 
	MILEAGETOTAL, 
	MILEAGETOTALAUDIT, 
	MILEAGETOTALESTIMATE, 
	PUBLICGROUPTYPE, 
	PUBLICTYPE, 
	RIDESHARING, 
	RISKPUBLICINPUTNYBLACKCAR, 
	SEATINGCAPACITY, 
	MECHANICALLIFT
	FROM EXP_TRANS
),