WITH
SQ_WBCFRiskStage AS (
	SELECT
		WBCFRiskStageId,
		ExtractDate,
		SourceSystemId,
		CF_RiskId,
		WB_CF_RiskId,
		SessionId,
		PurePremium,
		OriginalPackageModifier,
		CurrentFiledRatesBG1,
		CurrentFiledRatesBG2,
		CurrentFiledRatesAllOther,
		Selected,
		ExpiringRatesBG1,
		ExpiringRatesBG2,
		ExpiringRatesAllOther,
		DifferenceBG1,
		DifferenceBG2,
		DifferenceAllOther,
		AdjustmentBG1,
		One,
		AdjustmentBG2,
		AdjustmentAllOther,
		LastExpiringRatesBG1,
		LastExpiringRatesBG2,
		LastExpiringRatesAllOther,
		Year1Adj,
		Year2Adj,
		Year3Adj,
		Year1AdjBG2,
		Year2AdjBG2,
		Year3AdjBG2,
		Year1AdjAllOther,
		Year2AdjAllOther,
		Year3AdjAllOther,
		ExpiringRatesCaption,
		CurrentFiledRatesCaption,
		DifferenceCaption,
		AdjustmentFactorCaption,
		HeaderExpiringRates,
		HeaderCurrentFiledRates,
		HeaderDifference,
		HeaderAdjustmentFactor,
		RiskID,
		BuildingID
	FROM WBCFRiskStage
),
EXP_Metadata AS (
	SELECT
	WBCFRiskStageId,
	ExtractDate,
	SourceSystemId,
	CF_RiskId,
	WB_CF_RiskId,
	SessionId,
	PurePremium,
	OriginalPackageModifier,
	CurrentFiledRatesBG1,
	CurrentFiledRatesBG2,
	CurrentFiledRatesAllOther,
	Selected AS i_Selected,
	-- *INF*: DECODE(i_Selected, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_Selected,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_Selected,
	ExpiringRatesBG1,
	ExpiringRatesBG2,
	ExpiringRatesAllOther,
	DifferenceBG1,
	DifferenceBG2,
	DifferenceAllOther,
	AdjustmentBG1,
	One,
	AdjustmentBG2,
	AdjustmentAllOther,
	LastExpiringRatesBG1,
	LastExpiringRatesBG2,
	LastExpiringRatesAllOther,
	Year1Adj,
	Year2Adj,
	Year3Adj,
	Year1AdjBG2,
	Year2AdjBG2,
	Year3AdjBG2,
	Year1AdjAllOther,
	Year2AdjAllOther,
	Year3AdjAllOther,
	ExpiringRatesCaption,
	CurrentFiledRatesCaption,
	DifferenceCaption,
	AdjustmentFactorCaption,
	HeaderExpiringRates,
	HeaderCurrentFiledRates,
	HeaderDifference,
	HeaderAdjustmentFactor,
	RiskID,
	BuildingID,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_WBCFRiskStage
),
ArchWBCFRiskStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBCFRiskStage
	(ExtractDate, SourceSystemId, AuditId, WBCFRiskStageId, CF_RiskId, WB_CF_RiskId, SessionId, PurePremium, OriginalPackageModifier, CurrentFiledRatesBG1, CurrentFiledRatesBG2, CurrentFiledRatesAllOther, Selected, ExpiringRatesBG1, ExpiringRatesBG2, ExpiringRatesAllOther, DifferenceBG1, DifferenceBG2, DifferenceAllOther, AdjustmentBG1, One, AdjustmentBG2, AdjustmentAllOther, LastExpiringRatesBG1, LastExpiringRatesBG2, LastExpiringRatesAllOther, Year1Adj, Year2Adj, Year3Adj, Year1AdjBG2, Year2AdjBG2, Year3AdjBG2, Year1AdjAllOther, Year2AdjAllOther, Year3AdjAllOther, ExpiringRatesCaption, CurrentFiledRatesCaption, DifferenceCaption, AdjustmentFactorCaption, HeaderExpiringRates, HeaderCurrentFiledRates, HeaderDifference, HeaderAdjustmentFactor, RiskID, BuildingID)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBCFRISKSTAGEID, 
	CF_RISKID, 
	WB_CF_RISKID, 
	SESSIONID, 
	PUREPREMIUM, 
	ORIGINALPACKAGEMODIFIER, 
	CURRENTFILEDRATESBG1, 
	CURRENTFILEDRATESBG2, 
	CURRENTFILEDRATESALLOTHER, 
	o_Selected AS SELECTED, 
	EXPIRINGRATESBG1, 
	EXPIRINGRATESBG2, 
	EXPIRINGRATESALLOTHER, 
	DIFFERENCEBG1, 
	DIFFERENCEBG2, 
	DIFFERENCEALLOTHER, 
	ADJUSTMENTBG1, 
	ONE, 
	ADJUSTMENTBG2, 
	ADJUSTMENTALLOTHER, 
	LASTEXPIRINGRATESBG1, 
	LASTEXPIRINGRATESBG2, 
	LASTEXPIRINGRATESALLOTHER, 
	YEAR1ADJ, 
	YEAR2ADJ, 
	YEAR3ADJ, 
	YEAR1ADJBG2, 
	YEAR2ADJBG2, 
	YEAR3ADJBG2, 
	YEAR1ADJALLOTHER, 
	YEAR2ADJALLOTHER, 
	YEAR3ADJALLOTHER, 
	EXPIRINGRATESCAPTION, 
	CURRENTFILEDRATESCAPTION, 
	DIFFERENCECAPTION, 
	ADJUSTMENTFACTORCAPTION, 
	HEADEREXPIRINGRATES, 
	HEADERCURRENTFILEDRATES, 
	HEADERDIFFERENCE, 
	HEADERADJUSTMENTFACTOR, 
	RISKID, 
	BUILDINGID
	FROM EXP_Metadata
),