WITH
SQ_WBPolicyStaging AS (
	SELECT
		WBPolicyStagingId,
		PolicyId,
		WB_PolicyId,
		SessionId,
		CustomerCare,
		Division,
		Terrorism,
		Program,
		Association,
		ReceivedAMPM,
		ReceivedDate,
		ReceivedTimeHour,
		ReceivedTimeMinute,
		PolicyVersion,
		PolicyVersionFormatted,
		IsPreliminaryAuditRequired,
		IsMidTermAuditRequired,
		ExtractDate,
		SourceSystemId,
		WBProduct,
		WBProductType,
		RiskGrade,
		BCCCode,
		PlusPak,
		PolicyNumber,
		IsRollover,
		PriorCarrierNameOther,
		PremiumMining,
		QuoteType,
		DescriptionOfChildCarePremises,
		AssociationMessages,
		AssociationMessagesMCRA,
		AssociationDiscount,
		AssociationDiscountFactor,
		ProgramFactor,
		ClearedIdentification,
		ClearedIdentificationDateTimeStamp,
		LegalNoticeRequired,
		AssignedUnderwriterFirstName,
		AssignedUnderwriterLastName,
		StatusCode,
		Code,
		BCCCodeDesc,
		ConsentToRate,
		MultipleLocationCredit,
		Comments,
		Decision,
		Message,
		AutomaticRenewalIndicator,
		PolicyCoverage,
		IsBindableFlag,
		PurePremium,
		RuleType,
		PolicyProgram,
		ReinsuranceIndicator,
		RequestingEntity,
		OriginalBillingAccountNumber,
		OriginalPayPlan,
		OriginalTargetDueDate,
		PreviousPolicyVersion,
		EndorseProcessedBy,
		PriorCarrierName,
		PolicyIssueCodeDesc,
		PolicyIssueCodeOverride,
		PenguinTechGenerated,
		TotalFloodLimit,
		TotalFloodDeductible,
		PoolCode,
		IssuedUWID,
		IssuedUnderwriter,
		ExternalQuoteSource,
		TurnstileGenerated,
		LCSurveyOrderedIndicator,
		LCSurveyOrderedDate
	FROM WBPolicyStaging
),
EXP_Metadata AS (
	SELECT
	WBPolicyStagingId,
	PolicyId,
	WB_PolicyId,
	SessionId,
	CustomerCare,
	Division,
	Terrorism,
	Program,
	Association,
	ReceivedAMPM,
	ReceivedDate,
	ReceivedTimeHour,
	ReceivedTimeMinute,
	PolicyVersion,
	PolicyVersionFormatted,
	IsPreliminaryAuditRequired AS i_IsPreliminaryAuditRequired,
	-- *INF*: DECODE(i_IsPreliminaryAuditRequired, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_IsPreliminaryAuditRequired,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IsPreliminaryAuditRequired,
	IsMidTermAuditRequired AS i_IsMidTermAuditRequired,
	-- *INF*: DECODE(i_IsMidTermAuditRequired, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_IsMidTermAuditRequired,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IsMidTermAuditRequired,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	WBProduct,
	WBProductType,
	RiskGrade,
	BCCCode,
	PlusPak AS i_PlusPak,
	-- *INF*: DECODE(i_PlusPak, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_PlusPak,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_PlusPak,
	PolicyNumber,
	IsRollover AS i_IsRollover,
	-- *INF*: DECODE(i_IsRollover, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_IsRollover,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IsRollover,
	PriorCarrierNameOther,
	PremiumMining,
	QuoteType,
	DescriptionOfChildCarePremises,
	AssociationMessages,
	AssociationMessagesMCRA,
	AssociationDiscount,
	AssociationDiscountFactor,
	ProgramFactor,
	ClearedIdentification AS i_ClearedIdentification,
	-- *INF*: DECODE(i_ClearedIdentification, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_ClearedIdentification,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_ClearedIdentification,
	ClearedIdentificationDateTimeStamp,
	LegalNoticeRequired,
	AssignedUnderwriterFirstName,
	AssignedUnderwriterLastName,
	StatusCode,
	Code,
	BCCCodeDesc,
	ConsentToRate AS i_ConsentToRate,
	-- *INF*: DECODE(i_ConsentToRate, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_ConsentToRate,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_ConsentToRate,
	MultipleLocationCredit AS i_MultipleLocationCredit,
	-- *INF*: DECODE(i_MultipleLocationCredit, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_MultipleLocationCredit,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_MultipleLocationCredit,
	Comments,
	Decision,
	Message,
	AutomaticRenewalIndicator AS i_AutomaticRenewalIndicator,
	-- *INF*: DECODE(i_AutomaticRenewalIndicator, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_AutomaticRenewalIndicator,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_AutomaticRenewalIndicator,
	PolicyCoverage,
	IsBindableFlag AS i_IsBindableFlag,
	-- *INF*: DECODE(i_IsBindableFlag, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_IsBindableFlag,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IsBindableFlag,
	PurePremium,
	RuleType,
	PolicyProgram,
	ReinsuranceIndicator AS i_ReinsuranceIndicator,
	-- *INF*: DECODE(i_ReinsuranceIndicator,'T','1','F','0')
	DECODE(
	    i_ReinsuranceIndicator,
	    'T', '1',
	    'F', '0'
	) AS o_ReinsuranceIndicator,
	RequestingEntity,
	OriginalBillingAccountNumber,
	OriginalPayPlan,
	OriginalTargetDueDate,
	PreviousPolicyVersion,
	EndorseProcessedBy,
	PriorCarrierName,
	PolicyIssueCodeDesc,
	PolicyIssueCodeOverride AS i_PolicyIssueCodeOverride,
	-- *INF*: DECODE(i_PolicyIssueCodeOverride, 'T', 1, 'F', 0)
	DECODE(
	    i_PolicyIssueCodeOverride,
	    'T', 1,
	    'F', 0
	) AS o_PolicyIssueCodeOverride,
	PenguinTechGenerated AS i_PenguinTechGenerated,
	-- *INF*: DECODE(i_PenguinTechGenerated, 'T', 1, 'F', 0,0)
	DECODE(
	    i_PenguinTechGenerated,
	    'T', 1,
	    'F', 0,
	    0
	) AS o_PenguinTechGenerated,
	TotalFloodLimit,
	TotalFloodDeductible,
	PoolCode,
	IssuedUWID,
	IssuedUnderwriter,
	ExternalQuoteSource,
	TurnstileGenerated AS i_TurnstileGenerated,
	-- *INF*: DECODE(i_TurnstileGenerated, 'T', 1, 'F', 0,0)
	DECODE(
	    i_TurnstileGenerated,
	    'T', 1,
	    'F', 0,
	    0
	) AS o_TurnstileGenerated,
	LCSurveyOrderedIndicator,
	-- *INF*: DECODE(LCSurveyOrderedIndicator, 'T', '1', 'F', '0',null)
	DECODE(
	    LCSurveyOrderedIndicator,
	    'T', '1',
	    'F', '0',
	    null
	) AS o_LCSurveyOrderedIndicator,
	LCSurveyOrderedDate
	FROM SQ_WBPolicyStaging
),
archWBPolicyStaging AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.archWBPolicyStaging
	(ExtractDate, SourceSystemId, AuditId, WBPolicyStagingId, PolicyId, WB_PolicyId, SessionId, PolicyCoverage, PurePremium, ReinsuranceIndicator, CustomerCare, Division, Terrorism, IsPreliminaryAuditRequired, IsMidTermAuditRequired, PolicyProgram, Association, ReceivedAMPM, ReceivedDate, ReceivedTimeHour, ReceivedTimeMinute, BCCCode, PlusPak, PolicyNumber, IsRollover, PriorCarrierNameOther, PremiumMining, QuoteType, BCCCodeDesc, DescriptionOfChildCarePremises, ConsentToRate, MultipleLocationCredit, WBProduct, WBProductType, RequestingEntity, OriginalBillingAccountNumber, OriginalPayPlan, OriginalTargetDueDate, PolicyVersion, PolicyVersionFormatted, AssociationDiscount, AssociationDiscountFactor, AssociationMessages, AssociationMessagesMCRA, RiskGrade, ProgramFactor, ClearedIdentification, ClearedIdentificationDateTimeStamp, LegalNoticeRequired, AutomaticRenewalIndicator, IsBindableFlag, AssignedUnderwriterFirstName, AssignedUnderwriterLastName, PreviousPolicyVersion, Code, Comments, Decision, Message, RuleType, Program, StatusCode, EndorseProcessedBy, PriorCarrierName, PolicyIssueCodeDesc, PolicyIssueCodeOverride, PenguinTechGenerated, TotalFloodLimit, TotalFloodDeductible, PoolCode, IssuedUWID, IssuedUnderwriter, ExternalQuoteSource, TurnstileGenerated, LCSurveyOrderedIndicator, LCSurveyOrderedDate)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBPOLICYSTAGINGID, 
	POLICYID, 
	WB_POLICYID, 
	SESSIONID, 
	POLICYCOVERAGE, 
	PUREPREMIUM, 
	o_ReinsuranceIndicator AS REINSURANCEINDICATOR, 
	CUSTOMERCARE, 
	DIVISION, 
	TERRORISM, 
	o_IsPreliminaryAuditRequired AS ISPRELIMINARYAUDITREQUIRED, 
	o_IsMidTermAuditRequired AS ISMIDTERMAUDITREQUIRED, 
	POLICYPROGRAM, 
	ASSOCIATION, 
	RECEIVEDAMPM, 
	RECEIVEDDATE, 
	RECEIVEDTIMEHOUR, 
	RECEIVEDTIMEMINUTE, 
	BCCCODE, 
	o_PlusPak AS PLUSPAK, 
	POLICYNUMBER, 
	o_IsRollover AS ISROLLOVER, 
	PRIORCARRIERNAMEOTHER, 
	PREMIUMMINING, 
	QUOTETYPE, 
	BCCCODEDESC, 
	DESCRIPTIONOFCHILDCAREPREMISES, 
	o_ConsentToRate AS CONSENTTORATE, 
	o_MultipleLocationCredit AS MULTIPLELOCATIONCREDIT, 
	WBPRODUCT, 
	WBPRODUCTTYPE, 
	REQUESTINGENTITY, 
	ORIGINALBILLINGACCOUNTNUMBER, 
	ORIGINALPAYPLAN, 
	ORIGINALTARGETDUEDATE, 
	POLICYVERSION, 
	POLICYVERSIONFORMATTED, 
	ASSOCIATIONDISCOUNT, 
	ASSOCIATIONDISCOUNTFACTOR, 
	ASSOCIATIONMESSAGES, 
	ASSOCIATIONMESSAGESMCRA, 
	RISKGRADE, 
	PROGRAMFACTOR, 
	o_ClearedIdentification AS CLEAREDIDENTIFICATION, 
	CLEAREDIDENTIFICATIONDATETIMESTAMP, 
	LEGALNOTICEREQUIRED, 
	o_AutomaticRenewalIndicator AS AUTOMATICRENEWALINDICATOR, 
	o_IsBindableFlag AS ISBINDABLEFLAG, 
	ASSIGNEDUNDERWRITERFIRSTNAME, 
	ASSIGNEDUNDERWRITERLASTNAME, 
	PREVIOUSPOLICYVERSION, 
	CODE, 
	COMMENTS, 
	DECISION, 
	MESSAGE, 
	RULETYPE, 
	PROGRAM, 
	STATUSCODE, 
	ENDORSEPROCESSEDBY, 
	PRIORCARRIERNAME, 
	POLICYISSUECODEDESC, 
	o_PolicyIssueCodeOverride AS POLICYISSUECODEOVERRIDE, 
	o_PenguinTechGenerated AS PENGUINTECHGENERATED, 
	TOTALFLOODLIMIT, 
	TOTALFLOODDEDUCTIBLE, 
	POOLCODE, 
	ISSUEDUWID, 
	ISSUEDUNDERWRITER, 
	EXTERNALQUOTESOURCE, 
	o_TurnstileGenerated AS TURNSTILEGENERATED, 
	o_LCSurveyOrderedIndicator AS LCSURVEYORDEREDINDICATOR, 
	LCSURVEYORDEREDDATE
	FROM EXP_Metadata
),