WITH
SQ_WB_CU_UmbrellaGeneralLiability AS (
	WITH cte_WBCUUmbrellaGeneralLiability(Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.CU_UmbrellaGeneralLiabilityId, 
	X.WB_CU_UmbrellaGeneralLiabilityId, 
	X.SessionId, X.OtherDescription, 
	X.IncludeProfessionalLiability, 
	X.IncludeOhioStopGapLiability, 
	X.OtherProfessionalLiabilityEachOccurrenceClaimLimit, 
	X.OtherProfessionalLiabilityAggregate, 
	X.AggregateNotApplicableForIowa, 
	X.OtherAggregateNotApplicableForIowa, 
	X.EachOccurrenceNotApplicableForIowa, 
	X.OtherEachOccurrenceNotApplicableForIowa, 
	X.EachCommonCauseNotApplicableForIowa, 
	X.OtherEachCommonCauseNotApplicableForIowa, 
	X.EachPersonBodilyInjury, 
	X.OtherEachPersonBodilyInjury, 
	X.EachPersonPropertyDamage, 
	X.LossOfMeansOfSupportOrLossOfSociety, 
	X.OtherOccurrenceClaimLimit, 
	X.OtherProductsAggregate, 
	X.OtherPolicyAggregate, 
	X.OtherPersonalAndAdvertisingInjury, 
	X.PremOpsTotalPremiumTable1PremiumOverride, 
	X.PremOpsTotalPremiumTable2PremiumOverride, 
	X.PremOpsTotalPremiumTable3PremiumOverride, 
	X.AllOtherPremiumOverride, 
	X.ProductsTotalPremiumTableAPremiumOverride, 
	X.ProductsTotalPremiumTableBPremiumOverride, 
	X.ProductsTotalPremiumTableCPremiumOverride, 
	X.PremOpsTotalPremiumTable1RevisedPremium, 
	X.PremOpsTotalPremiumTable2RevisedPremium, 
	X.PremOpsTotalPremiumTable3RevisedPremium, 
	X.AllOtherRevisedPremium, 
	X.ProductsTotalPremiumTableARevisedPremium, 
	X.ProductsTotalPremiumTableBRevisedPremium, 
	X.ProductsTotalPremiumTableCRevisedPremium, 
	X.FirstMillionModifiedPremium, 
	X.FirstMillionBasePremium, 
	X.FirstMillionBasePremiumForLiquorLiability, 
	X.FirstMillionModifiedPremiumForLiquorLiability, 
	X.ScheduledModification, 
	X.ReinsuranceFactor, 
	X.IDField, 
	X.ScheduledModificationLocationInComment, 
	X.ScheduledModificationLocationInModification, 
	X.ScheduledModificationLocationOutComment, 
	X.ScheduledModificationLocationOutModification, 
	X.ScheduledModificationPremisesComment, 
	X.ScheduledModificationPremisesModification, 
	X.ScheduledModificationEquipmentComment, 
	X.ScheduledModificationEquipmentModification, 
	X.ScheduledModificationManagementComment, 
	X.ScheduledModificationManagementModification, 
	X.ScheduledModificationEmployeesComment, 
	X.ScheduledModificationEmployeesModification, 
	X.ScheduledModificationCooperationMedicalComment, 
	X.ScheduledModificationCooperationMedicalModification, 
	X.ScheduledModificationCooperationSafetyComment, 
	X.ScheduledModificationCooperationSafetyModification, 
	X.ModificationTotal, X.ModificationTotalForGLDetailPage, 
	X.Indicator, 
	X.Premium, 
	X.PremiumChange, 
	X.PremiumWritten, 
	X.Scope, 
	X.Deleted, 
	X.RetroDate 
	FROM
	WB_CU_UmbrellaGeneralLiability X
	inner join
	cte_WBCUUmbrellaGeneralLiability Y on X.Sessionid = Y.Sessionid
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Metadata AS (
	SELECT
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	CU_UmbrellaGeneralLiabilityId,
	WB_CU_UmbrellaGeneralLiabilityId,
	SessionId,
	OtherDescription,
	IncludeProfessionalLiability,
	-- *INF*: DECODE(IncludeProfessionalLiability,'T',1,'F',0,NULL)
	DECODE(
	    IncludeProfessionalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS IncludeProfessionalLiability_out,
	IncludeOhioStopGapLiability,
	-- *INF*: DECODE(IncludeOhioStopGapLiability,'T',1,'F',0,NULL)
	DECODE(
	    IncludeOhioStopGapLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS IncludeOhioStopGapLiability_out,
	OtherProfessionalLiabilityEachOccurrenceClaimLimit,
	OtherProfessionalLiabilityAggregate,
	AggregateNotApplicableForIowa,
	OtherAggregateNotApplicableForIowa,
	EachOccurrenceNotApplicableForIowa,
	OtherEachOccurrenceNotApplicableForIowa,
	EachCommonCauseNotApplicableForIowa,
	OtherEachCommonCauseNotApplicableForIowa,
	EachPersonBodilyInjury,
	OtherEachPersonBodilyInjury,
	EachPersonPropertyDamage,
	LossOfMeansOfSupportOrLossOfSociety,
	OtherOccurrenceClaimLimit,
	OtherProductsAggregate,
	OtherPolicyAggregate,
	OtherPersonalAndAdvertisingInjury,
	PremOpsTotalPremiumTable1PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable1PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable1PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable1PremiumOverride_out,
	PremOpsTotalPremiumTable2PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable2PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable2PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable2PremiumOverride_out,
	PremOpsTotalPremiumTable3PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable3PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable3PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable3PremiumOverride_out,
	AllOtherPremiumOverride,
	-- *INF*: DECODE(AllOtherPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    AllOtherPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS AllOtherPremiumOverride_out,
	ProductsTotalPremiumTableAPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableAPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableAPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableAPremiumOverride_out,
	ProductsTotalPremiumTableBPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableBPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableBPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableBPremiumOverride_out,
	ProductsTotalPremiumTableCPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableCPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableCPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableCPremiumOverride_out,
	PremOpsTotalPremiumTable1RevisedPremium,
	PremOpsTotalPremiumTable2RevisedPremium,
	PremOpsTotalPremiumTable3RevisedPremium,
	AllOtherRevisedPremium,
	ProductsTotalPremiumTableARevisedPremium,
	ProductsTotalPremiumTableBRevisedPremium,
	ProductsTotalPremiumTableCRevisedPremium,
	FirstMillionModifiedPremium,
	FirstMillionBasePremium,
	FirstMillionBasePremiumForLiquorLiability,
	FirstMillionModifiedPremiumForLiquorLiability,
	ScheduledModification,
	ReinsuranceFactor,
	IDField,
	ScheduledModificationLocationInComment,
	ScheduledModificationLocationInModification,
	ScheduledModificationLocationOutComment,
	ScheduledModificationLocationOutModification,
	ScheduledModificationPremisesComment,
	ScheduledModificationPremisesModification,
	ScheduledModificationEquipmentComment,
	ScheduledModificationEquipmentModification,
	ScheduledModificationManagementComment,
	ScheduledModificationManagementModification,
	ScheduledModificationEmployeesComment,
	ScheduledModificationEmployeesModification,
	ScheduledModificationCooperationMedicalComment,
	ScheduledModificationCooperationMedicalModification,
	ScheduledModificationCooperationSafetyComment,
	ScheduledModificationCooperationSafetyModification,
	ModificationTotal,
	ModificationTotalForGLDetailPage,
	Indicator,
	-- *INF*: DECODE(Indicator,'T',1,'F',0,NULL)
	DECODE(
	    Indicator,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS Indicator_out,
	Premium,
	PremiumChange,
	PremiumWritten,
	Scope,
	Deleted,
	-- *INF*: DECODE(Deleted,'T',1,'F',0,NULL)
	DECODE(
	    Deleted,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS Deleted_out,
	RetroDate
	FROM SQ_WB_CU_UmbrellaGeneralLiability
),
WBCUUmbrellaGeneralLiabilityStaging AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCUUmbrellaGeneralLiabilityStaging;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCUUmbrellaGeneralLiabilityStaging
	(ExtractDate, SourceSystemId, CU_UmbrellaGeneralLiabilityId, WB_CU_UmbrellaGeneralLiabilityId, SessionId, OtherDescription, OtherProfessionalLiabilityEachOccurrenceClaimLimit, OtherProfessionalLiabilityAggregate, AggregateNotApplicableForIowa, OtherAggregateNotApplicableForIowa, EachOccurrenceNotApplicableForIowa, OtherEachOccurrenceNotApplicableForIowa, EachCommonCauseNotApplicableForIowa, OtherEachCommonCauseNotApplicableForIowa, EachPersonBodilyInjury, OtherEachPersonBodilyInjury, EachPersonPropertyDamage, LossOfMeansOfSupportOrLossOfSociety, OtherOccurrenceClaimLimit, OtherProductsAggregate, OtherPolicyAggregate, OtherPersonalAndAdvertisingInjury, PremOpsTotalPremiumTable1PremiumOverride, PremOpsTotalPremiumTable2PremiumOverride, PremOpsTotalPremiumTable3PremiumOverride, AllOtherPremiumOverride, ProductsTotalPremiumTableAPremiumOverride, ProductsTotalPremiumTableBPremiumOverride, ProductsTotalPremiumTableCPremiumOverride, PremOpsTotalPremiumTable1RevisedPremium, PremOpsTotalPremiumTable2RevisedPremium, PremOpsTotalPremiumTable3RevisedPremium, AllOtherRevisedPremium, ProductsTotalPremiumTableARevisedPremium, ProductsTotalPremiumTableBRevisedPremium, ProductsTotalPremiumTableCRevisedPremium, FirstMillionModifiedPremium, FirstMillionBasePremium, FirstMillionBasePremiumForLiquorLiability, FirstMillionModifiedPremiumForLiquorLiability, ScheduledModification, ReinsuranceFactor, IDField, ScheduledModificationLocationInComment, ScheduledModificationLocationInModification, ScheduledModificationLocationOutComment, ScheduledModificationLocationOutModification, ScheduledModificationPremisesComment, ScheduledModificationPremisesModification, ScheduledModificationEquipmentComment, ScheduledModificationEquipmentModification, ScheduledModificationManagementComment, ScheduledModificationManagementModification, ScheduledModificationEmployeesComment, ScheduledModificationEmployeesModification, ScheduledModificationCooperationMedicalComment, ScheduledModificationCooperationMedicalModification, ScheduledModificationCooperationSafetyComment, ScheduledModificationCooperationSafetyModification, ModificationTotal, ModificationTotalForGLDetailPage, IncludeProfessionalLiability, IncludeOhioStopGapLiability, Indicator, Premium, PremiumChange, PremiumWritten, Scope, Deleted, RetroDate)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	CU_UMBRELLAGENERALLIABILITYID, 
	WB_CU_UMBRELLAGENERALLIABILITYID, 
	SESSIONID, 
	OTHERDESCRIPTION, 
	OTHERPROFESSIONALLIABILITYEACHOCCURRENCECLAIMLIMIT, 
	OTHERPROFESSIONALLIABILITYAGGREGATE, 
	AGGREGATENOTAPPLICABLEFORIOWA, 
	OTHERAGGREGATENOTAPPLICABLEFORIOWA, 
	EACHOCCURRENCENOTAPPLICABLEFORIOWA, 
	OTHEREACHOCCURRENCENOTAPPLICABLEFORIOWA, 
	EACHCOMMONCAUSENOTAPPLICABLEFORIOWA, 
	OTHEREACHCOMMONCAUSENOTAPPLICABLEFORIOWA, 
	EACHPERSONBODILYINJURY, 
	OTHEREACHPERSONBODILYINJURY, 
	EACHPERSONPROPERTYDAMAGE, 
	LOSSOFMEANSOFSUPPORTORLOSSOFSOCIETY, 
	OTHEROCCURRENCECLAIMLIMIT, 
	OTHERPRODUCTSAGGREGATE, 
	OTHERPOLICYAGGREGATE, 
	OTHERPERSONALANDADVERTISINGINJURY, 
	PremOpsTotalPremiumTable1PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE1PREMIUMOVERRIDE, 
	PremOpsTotalPremiumTable2PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE2PREMIUMOVERRIDE, 
	PremOpsTotalPremiumTable3PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE3PREMIUMOVERRIDE, 
	AllOtherPremiumOverride_out AS ALLOTHERPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableAPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLEAPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableBPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLEBPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableCPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLECPREMIUMOVERRIDE, 
	PREMOPSTOTALPREMIUMTABLE1REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE2REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE3REVISEDPREMIUM, 
	ALLOTHERREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEAREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEBREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLECREVISEDPREMIUM, 
	FIRSTMILLIONMODIFIEDPREMIUM, 
	FIRSTMILLIONBASEPREMIUM, 
	FIRSTMILLIONBASEPREMIUMFORLIQUORLIABILITY, 
	FIRSTMILLIONMODIFIEDPREMIUMFORLIQUORLIABILITY, 
	SCHEDULEDMODIFICATION, 
	REINSURANCEFACTOR, 
	IDFIELD, 
	SCHEDULEDMODIFICATIONLOCATIONINCOMMENT, 
	SCHEDULEDMODIFICATIONLOCATIONINMODIFICATION, 
	SCHEDULEDMODIFICATIONLOCATIONOUTCOMMENT, 
	SCHEDULEDMODIFICATIONLOCATIONOUTMODIFICATION, 
	SCHEDULEDMODIFICATIONPREMISESCOMMENT, 
	SCHEDULEDMODIFICATIONPREMISESMODIFICATION, 
	SCHEDULEDMODIFICATIONEQUIPMENTCOMMENT, 
	SCHEDULEDMODIFICATIONEQUIPMENTMODIFICATION, 
	SCHEDULEDMODIFICATIONMANAGEMENTCOMMENT, 
	SCHEDULEDMODIFICATIONMANAGEMENTMODIFICATION, 
	SCHEDULEDMODIFICATIONEMPLOYEESCOMMENT, 
	SCHEDULEDMODIFICATIONEMPLOYEESMODIFICATION, 
	SCHEDULEDMODIFICATIONCOOPERATIONMEDICALCOMMENT, 
	SCHEDULEDMODIFICATIONCOOPERATIONMEDICALMODIFICATION, 
	SCHEDULEDMODIFICATIONCOOPERATIONSAFETYCOMMENT, 
	SCHEDULEDMODIFICATIONCOOPERATIONSAFETYMODIFICATION, 
	MODIFICATIONTOTAL, 
	MODIFICATIONTOTALFORGLDETAILPAGE, 
	IncludeProfessionalLiability_out AS INCLUDEPROFESSIONALLIABILITY, 
	IncludeOhioStopGapLiability_out AS INCLUDEOHIOSTOPGAPLIABILITY, 
	Indicator_out AS INDICATOR, 
	PREMIUM, 
	PREMIUMCHANGE, 
	PREMIUMWRITTEN, 
	SCOPE, 
	Deleted_out AS DELETED, 
	RETRODATE
	FROM EXP_Metadata
),