WITH
SQ_WBCFLocationPropertyStage AS (
	SELECT
		WBCFLocationPropertyStageId,
		ExtractDate,
		SourceSystemId,
		CFLocationPropertyId AS CfLocationPropertyId,
		WBCFLocationPropertyId AS WbCfLocationPropertyId,
		SessionId,
		ProtectionClassOverride,
		IncreasePersonalComputersCoverageEDP,
		ExcessPersonalComputersEDPLimit,
		IncreaseMoneyAndSecurities,
		ExcessMoneyAndSecuritiesOutsideLimit,
		IncreaseOutdoorDetachedSigns,
		ExcessOutdoorDetachedSignsLimit,
		ExcessMoneyAndSecuritiesInsideLimit,
		LocationIRPMManagementSetCommentValue,
		LocationIRPMManagementSetValueValue,
		SetCommentValue,
		SetValueValue,
		LocationIRPMEmployeesSetCommentValue,
		LocationIRPMEmployeesSetValueValue,
		LocationIRPMLocationSetCommentValue,
		LocationIRPMLocationSetValueValue,
		LocationIRPMPremisesSetCommentValue,
		LocationIRPMPremisesSetValueValue,
		LocationIRPMProtectionSetCommentValue,
		LocationIRPMProtectionSetValueValue,
		MultipleLocationCreditFactor,
		IncreasePersonalComputersCoverageEDPText,
		IncreaseMoneyAndSecuritiesText,
		IncreaseOutdoorDetachedSignsText,
		ExcessPersonalComputersEDPPremium,
		OutdoorDetachedSignsPremium,
		MoneyAndSecuritiesInsidePremium,
		MoneyAndSecuritiesOutsidePremium
	FROM WBCFLocationPropertyStage
),
EXP_Metadata AS (
	SELECT
	WBCFLocationPropertyStageId,
	ExtractDate,
	SourceSystemId,
	CfLocationPropertyId,
	WbCfLocationPropertyId,
	SessionId,
	ProtectionClassOverride,
	IncreasePersonalComputersCoverageEDP AS i_IncreasePersonalComputersCoverageEDP,
	-- *INF*: DECODE(i_IncreasePersonalComputersCoverageEDP,
	-- 'T',
	-- '1',
	-- 'F',
	-- '0',
	-- NULL
	-- )
	DECODE(
	    i_IncreasePersonalComputersCoverageEDP,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IncreasePersonalComputersCoverageEDP,
	ExcessPersonalComputersEDPLimit,
	IncreaseMoneyAndSecurities AS i_IncreaseMoneyAndSecurities,
	-- *INF*: DECODE(i_IncreaseMoneyAndSecurities,
	-- 'T',
	-- '1',
	-- 'F',
	-- '0',
	-- NULL
	-- )
	DECODE(
	    i_IncreaseMoneyAndSecurities,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IncreaseMoneyAndSecurities,
	ExcessMoneyAndSecuritiesOutsideLimit,
	IncreaseOutdoorDetachedSigns AS i_IncreaseOutdoorDetachedSigns,
	-- *INF*: DECODE(i_IncreaseOutdoorDetachedSigns,
	-- 'T',
	-- '1',
	-- 'F',
	-- '0',
	-- NULL
	-- )
	DECODE(
	    i_IncreaseOutdoorDetachedSigns,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_IncreaseOutdoorDetachedSigns,
	ExcessOutdoorDetachedSignsLimit,
	ExcessMoneyAndSecuritiesInsideLimit,
	LocationIRPMManagementSetCommentValue,
	LocationIRPMManagementSetValueValue,
	SetCommentValue,
	SetValueValue,
	LocationIRPMEmployeesSetCommentValue,
	LocationIRPMEmployeesSetValueValue,
	LocationIRPMLocationSetCommentValue,
	LocationIRPMLocationSetValueValue,
	LocationIRPMPremisesSetCommentValue,
	LocationIRPMPremisesSetValueValue,
	LocationIRPMProtectionSetCommentValue,
	LocationIRPMProtectionSetValueValue,
	MultipleLocationCreditFactor,
	IncreasePersonalComputersCoverageEDPText,
	IncreaseMoneyAndSecuritiesText,
	IncreaseOutdoorDetachedSignsText,
	ExcessPersonalComputersEDPPremium,
	OutdoorDetachedSignsPremium,
	MoneyAndSecuritiesInsidePremium,
	MoneyAndSecuritiesOutsidePremium,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_WBCFLocationPropertyStage
),
ArchWBCFLocationPropertyStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBCFLocationPropertyStage
	(ExtractDate, SourceSystemId, AuditId, WBCFLocationPropertyStageId, CFLocationPropertyId, WBCFLocationPropertyId, SessionId, ProtectionClassOverride, IncreasePersonalComputersCoverageEDP, ExcessPersonalComputersEDPLimit, IncreaseMoneyAndSecurities, ExcessMoneyAndSecuritiesOutsideLimit, IncreaseOutdoorDetachedSigns, ExcessOutdoorDetachedSignsLimit, ExcessMoneyAndSecuritiesInsideLimit, LocationIRPMManagementSetCommentValue, LocationIRPMManagementSetValueValue, SetCommentValue, SetValueValue, LocationIRPMEmployeesSetCommentValue, LocationIRPMEmployeesSetValueValue, LocationIRPMLocationSetCommentValue, LocationIRPMLocationSetValueValue, LocationIRPMPremisesSetCommentValue, LocationIRPMPremisesSetValueValue, LocationIRPMProtectionSetCommentValue, LocationIRPMProtectionSetValueValue, MultipleLocationCreditFactor, IncreasePersonalComputersCoverageEDPText, IncreaseMoneyAndSecuritiesText, IncreaseOutdoorDetachedSignsText, ExcessPersonalComputersEDPPremium, OutdoorDetachedSignsPremium, MoneyAndSecuritiesInsidePremium, MoneyAndSecuritiesOutsidePremium)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBCFLOCATIONPROPERTYSTAGEID, 
	CfLocationPropertyId AS CFLOCATIONPROPERTYID, 
	WbCfLocationPropertyId AS WBCFLOCATIONPROPERTYID, 
	SESSIONID, 
	PROTECTIONCLASSOVERRIDE, 
	o_IncreasePersonalComputersCoverageEDP AS INCREASEPERSONALCOMPUTERSCOVERAGEEDP, 
	EXCESSPERSONALCOMPUTERSEDPLIMIT, 
	o_IncreaseMoneyAndSecurities AS INCREASEMONEYANDSECURITIES, 
	EXCESSMONEYANDSECURITIESOUTSIDELIMIT, 
	o_IncreaseOutdoorDetachedSigns AS INCREASEOUTDOORDETACHEDSIGNS, 
	EXCESSOUTDOORDETACHEDSIGNSLIMIT, 
	EXCESSMONEYANDSECURITIESINSIDELIMIT, 
	LOCATIONIRPMMANAGEMENTSETCOMMENTVALUE, 
	LOCATIONIRPMMANAGEMENTSETVALUEVALUE, 
	SETCOMMENTVALUE, 
	SETVALUEVALUE, 
	LOCATIONIRPMEMPLOYEESSETCOMMENTVALUE, 
	LOCATIONIRPMEMPLOYEESSETVALUEVALUE, 
	LOCATIONIRPMLOCATIONSETCOMMENTVALUE, 
	LOCATIONIRPMLOCATIONSETVALUEVALUE, 
	LOCATIONIRPMPREMISESSETCOMMENTVALUE, 
	LOCATIONIRPMPREMISESSETVALUEVALUE, 
	LOCATIONIRPMPROTECTIONSETCOMMENTVALUE, 
	LOCATIONIRPMPROTECTIONSETVALUEVALUE, 
	MULTIPLELOCATIONCREDITFACTOR, 
	INCREASEPERSONALCOMPUTERSCOVERAGEEDPTEXT, 
	INCREASEMONEYANDSECURITIESTEXT, 
	INCREASEOUTDOORDETACHEDSIGNSTEXT, 
	EXCESSPERSONALCOMPUTERSEDPPREMIUM, 
	OUTDOORDETACHEDSIGNSPREMIUM, 
	MONEYANDSECURITIESINSIDEPREMIUM, 
	MONEYANDSECURITIESOUTSIDEPREMIUM
	FROM EXP_Metadata
),