WITH
SQ_WBCUUmbrellaGeneralLiabilityStaging AS (
	SELECT
		WBCUUmbrellaGeneralLiabilityStagingId,
		ExtractDate,
		SourceSystemId,
		CU_UmbrellaGeneralLiabilityId,
		WB_CU_UmbrellaGeneralLiabilityId,
		SessionId,
		OtherDescription,
		OtherProfessionalLiabilityEachOccurrenceClaimLimit,
		OtherProfessionalLiabilityAggregate,
		AggregateNotApplicableForIowa,
		OtherAggregateNotApplicableForIowa,
		EachOccurrenceNotApplicableForIowa,
		OtherEachOccurrenceNotApplicableForIowa,
		EachCommonCauseNotApplicableForIowa,
		OtherEachCommonCauseNotApplicableForIowa,
		EachPersonBodilyInjury,
		OtherEachPersonBodilyInjury,
		EachPersonPropertyDamage,
		LossOfMeansOfSupportOrLossOfSociety,
		OtherOccurrenceClaimLimit,
		OtherProductsAggregate,
		OtherPolicyAggregate,
		OtherPersonalAndAdvertisingInjury,
		PremOpsTotalPremiumTable1PremiumOverride,
		PremOpsTotalPremiumTable2PremiumOverride,
		PremOpsTotalPremiumTable3PremiumOverride,
		AllOtherPremiumOverride,
		ProductsTotalPremiumTableAPremiumOverride,
		ProductsTotalPremiumTableBPremiumOverride,
		ProductsTotalPremiumTableCPremiumOverride,
		PremOpsTotalPremiumTable1RevisedPremium,
		PremOpsTotalPremiumTable2RevisedPremium,
		PremOpsTotalPremiumTable3RevisedPremium,
		AllOtherRevisedPremium,
		ProductsTotalPremiumTableARevisedPremium,
		ProductsTotalPremiumTableBRevisedPremium,
		ProductsTotalPremiumTableCRevisedPremium,
		FirstMillionModifiedPremium,
		FirstMillionBasePremium,
		FirstMillionBasePremiumForLiquorLiability,
		FirstMillionModifiedPremiumForLiquorLiability,
		ScheduledModification,
		ReinsuranceFactor,
		IDField,
		ScheduledModificationLocationInComment,
		ScheduledModificationLocationInModification,
		ScheduledModificationLocationOutComment,
		ScheduledModificationLocationOutModification,
		ScheduledModificationPremisesComment,
		ScheduledModificationPremisesModification,
		ScheduledModificationEquipmentComment,
		ScheduledModificationEquipmentModification,
		ScheduledModificationManagementComment,
		ScheduledModificationManagementModification,
		ScheduledModificationEmployeesComment,
		ScheduledModificationEmployeesModification,
		ScheduledModificationCooperationMedicalComment,
		ScheduledModificationCooperationMedicalModification,
		ScheduledModificationCooperationSafetyComment,
		ScheduledModificationCooperationSafetyModification,
		ModificationTotal,
		ModificationTotalForGLDetailPage,
		IncludeProfessionalLiability,
		IncludeOhioStopGapLiability,
		Indicator,
		Premium,
		PremiumChange,
		PremiumWritten,
		Scope,
		Deleted,
		RetroDate
	FROM WBCUUmbrellaGeneralLiabilityStaging
),
EXP_Metadata AS (
	SELECT
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS AuditId,
	CU_UmbrellaGeneralLiabilityId,
	WB_CU_UmbrellaGeneralLiabilityId,
	SessionId,
	OtherDescription,
	OtherProfessionalLiabilityEachOccurrenceClaimLimit,
	OtherProfessionalLiabilityAggregate,
	AggregateNotApplicableForIowa,
	OtherAggregateNotApplicableForIowa,
	EachOccurrenceNotApplicableForIowa,
	OtherEachOccurrenceNotApplicableForIowa,
	EachCommonCauseNotApplicableForIowa,
	OtherEachCommonCauseNotApplicableForIowa,
	EachPersonBodilyInjury,
	OtherEachPersonBodilyInjury,
	EachPersonPropertyDamage,
	LossOfMeansOfSupportOrLossOfSociety,
	OtherOccurrenceClaimLimit,
	OtherProductsAggregate,
	OtherPolicyAggregate,
	OtherPersonalAndAdvertisingInjury,
	PremOpsTotalPremiumTable1PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable1PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable1PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable1PremiumOverride_out,
	PremOpsTotalPremiumTable2PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable2PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable2PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable2PremiumOverride_out,
	PremOpsTotalPremiumTable3PremiumOverride,
	-- *INF*: DECODE(PremOpsTotalPremiumTable3PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    PremOpsTotalPremiumTable3PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS PremOpsTotalPremiumTable3PremiumOverride_out,
	AllOtherPremiumOverride,
	-- *INF*: DECODE(AllOtherPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    AllOtherPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS AllOtherPremiumOverride_out,
	ProductsTotalPremiumTableAPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableAPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableAPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableAPremiumOverride_out,
	ProductsTotalPremiumTableBPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableBPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableBPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableBPremiumOverride_out,
	ProductsTotalPremiumTableCPremiumOverride,
	-- *INF*: DECODE(ProductsTotalPremiumTableCPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    ProductsTotalPremiumTableCPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS ProductsTotalPremiumTableCPremiumOverride_out,
	PremOpsTotalPremiumTable1RevisedPremium,
	PremOpsTotalPremiumTable2RevisedPremium,
	PremOpsTotalPremiumTable3RevisedPremium,
	AllOtherRevisedPremium,
	ProductsTotalPremiumTableARevisedPremium,
	ProductsTotalPremiumTableBRevisedPremium,
	ProductsTotalPremiumTableCRevisedPremium,
	FirstMillionModifiedPremium,
	FirstMillionBasePremium,
	FirstMillionBasePremiumForLiquorLiability,
	FirstMillionModifiedPremiumForLiquorLiability,
	ScheduledModification,
	ReinsuranceFactor,
	IDField,
	ScheduledModificationLocationInComment,
	ScheduledModificationLocationInModification,
	ScheduledModificationLocationOutComment,
	ScheduledModificationLocationOutModification,
	ScheduledModificationPremisesComment,
	ScheduledModificationPremisesModification,
	ScheduledModificationEquipmentComment,
	ScheduledModificationEquipmentModification,
	ScheduledModificationManagementComment,
	ScheduledModificationManagementModification,
	ScheduledModificationEmployeesComment,
	ScheduledModificationEmployeesModification,
	ScheduledModificationCooperationMedicalComment,
	ScheduledModificationCooperationMedicalModification,
	ScheduledModificationCooperationSafetyComment,
	ScheduledModificationCooperationSafetyModification,
	ModificationTotal,
	ModificationTotalForGLDetailPage,
	IncludeProfessionalLiability,
	-- *INF*: DECODE(IncludeProfessionalLiability,'T',1,'F',0,NULL)
	DECODE(
	    IncludeProfessionalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS IncludeProfessionalLiability_out,
	IncludeOhioStopGapLiability,
	-- *INF*: DECODE(IncludeOhioStopGapLiability,'T',1,'F',0,NULL)
	DECODE(
	    IncludeOhioStopGapLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS IncludeOhioStopGapLiability_out,
	Indicator,
	-- *INF*: DECODE(Indicator,'T',1,'F',0,NULL)
	DECODE(
	    Indicator,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS Indicator_out,
	Premium,
	PremiumChange,
	PremiumWritten,
	Scope,
	Deleted,
	-- *INF*: DECODE(Deleted,'T',1,'F',0,NULL)
	DECODE(
	    Deleted,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS Deleted_Out,
	RetroDate
	FROM SQ_WBCUUmbrellaGeneralLiabilityStaging
),
archWBCUUmbrellaGeneralLiabilityStaging AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.archWBCUUmbrellaGeneralLiabilityStaging
	(ExtractDate, SourceSystemId, AuditId, CU_UmbrellaGeneralLiabilityId, WB_CU_UmbrellaGeneralLiabilityId, SessionId, OtherDescription, OtherProfessionalLiabilityEachOccurrenceClaimLimit, OtherProfessionalLiabilityAggregate, AggregateNotApplicableForIowa, OtherAggregateNotApplicableForIowa, EachOccurrenceNotApplicableForIowa, OtherEachOccurrenceNotApplicableForIowa, EachCommonCauseNotApplicableForIowa, OtherEachCommonCauseNotApplicableForIowa, EachPersonBodilyInjury, OtherEachPersonBodilyInjury, EachPersonPropertyDamage, LossOfMeansOfSupportOrLossOfSociety, OtherOccurrenceClaimLimit, OtherProductsAggregate, OtherPolicyAggregate, OtherPersonalAndAdvertisingInjury, PremOpsTotalPremiumTable1PremiumOverride, PremOpsTotalPremiumTable2PremiumOverride, PremOpsTotalPremiumTable3PremiumOverride, AllOtherPremiumOverride, ProductsTotalPremiumTableAPremiumOverride, ProductsTotalPremiumTableBPremiumOverride, ProductsTotalPremiumTableCPremiumOverride, PremOpsTotalPremiumTable1RevisedPremium, PremOpsTotalPremiumTable2RevisedPremium, PremOpsTotalPremiumTable3RevisedPremium, AllOtherRevisedPremium, ProductsTotalPremiumTableARevisedPremium, ProductsTotalPremiumTableBRevisedPremium, ProductsTotalPremiumTableCRevisedPremium, FirstMillionModifiedPremium, FirstMillionBasePremium, FirstMillionBasePremiumForLiquorLiability, FirstMillionModifiedPremiumForLiquorLiability, ScheduledModification, ReinsuranceFactor, IDField, ScheduledModificationLocationInComment, ScheduledModificationLocationInModification, ScheduledModificationLocationOutComment, ScheduledModificationLocationOutModification, ScheduledModificationPremisesComment, ScheduledModificationPremisesModification, ScheduledModificationEquipmentComment, ScheduledModificationEquipmentModification, ScheduledModificationManagementComment, ScheduledModificationManagementModification, ScheduledModificationEmployeesComment, ScheduledModificationEmployeesModification, ScheduledModificationCooperationMedicalComment, ScheduledModificationCooperationMedicalModification, ScheduledModificationCooperationSafetyComment, ScheduledModificationCooperationSafetyModification, ModificationTotal, ModificationTotalForGLDetailPage, IncludeProfessionalLiability, IncludeOhioStopGapLiability, Indicator, Premium, PremiumChange, PremiumWritten, Scope, Deleted, RetroDate)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	AUDITID, 
	CU_UMBRELLAGENERALLIABILITYID, 
	WB_CU_UMBRELLAGENERALLIABILITYID, 
	SESSIONID, 
	OTHERDESCRIPTION, 
	OTHERPROFESSIONALLIABILITYEACHOCCURRENCECLAIMLIMIT, 
	OTHERPROFESSIONALLIABILITYAGGREGATE, 
	AGGREGATENOTAPPLICABLEFORIOWA, 
	OTHERAGGREGATENOTAPPLICABLEFORIOWA, 
	EACHOCCURRENCENOTAPPLICABLEFORIOWA, 
	OTHEREACHOCCURRENCENOTAPPLICABLEFORIOWA, 
	EACHCOMMONCAUSENOTAPPLICABLEFORIOWA, 
	OTHEREACHCOMMONCAUSENOTAPPLICABLEFORIOWA, 
	EACHPERSONBODILYINJURY, 
	OTHEREACHPERSONBODILYINJURY, 
	EACHPERSONPROPERTYDAMAGE, 
	LOSSOFMEANSOFSUPPORTORLOSSOFSOCIETY, 
	OTHEROCCURRENCECLAIMLIMIT, 
	OTHERPRODUCTSAGGREGATE, 
	OTHERPOLICYAGGREGATE, 
	OTHERPERSONALANDADVERTISINGINJURY, 
	PremOpsTotalPremiumTable1PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE1PREMIUMOVERRIDE, 
	PremOpsTotalPremiumTable2PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE2PREMIUMOVERRIDE, 
	PremOpsTotalPremiumTable3PremiumOverride_out AS PREMOPSTOTALPREMIUMTABLE3PREMIUMOVERRIDE, 
	AllOtherPremiumOverride_out AS ALLOTHERPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableAPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLEAPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableBPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLEBPREMIUMOVERRIDE, 
	ProductsTotalPremiumTableCPremiumOverride_out AS PRODUCTSTOTALPREMIUMTABLECPREMIUMOVERRIDE, 
	PREMOPSTOTALPREMIUMTABLE1REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE2REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE3REVISEDPREMIUM, 
	ALLOTHERREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEAREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEBREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLECREVISEDPREMIUM, 
	FIRSTMILLIONMODIFIEDPREMIUM, 
	FIRSTMILLIONBASEPREMIUM, 
	FIRSTMILLIONBASEPREMIUMFORLIQUORLIABILITY, 
	FIRSTMILLIONMODIFIEDPREMIUMFORLIQUORLIABILITY, 
	SCHEDULEDMODIFICATION, 
	REINSURANCEFACTOR, 
	IDFIELD, 
	SCHEDULEDMODIFICATIONLOCATIONINCOMMENT, 
	SCHEDULEDMODIFICATIONLOCATIONINMODIFICATION, 
	SCHEDULEDMODIFICATIONLOCATIONOUTCOMMENT, 
	SCHEDULEDMODIFICATIONLOCATIONOUTMODIFICATION, 
	SCHEDULEDMODIFICATIONPREMISESCOMMENT, 
	SCHEDULEDMODIFICATIONPREMISESMODIFICATION, 
	SCHEDULEDMODIFICATIONEQUIPMENTCOMMENT, 
	SCHEDULEDMODIFICATIONEQUIPMENTMODIFICATION, 
	SCHEDULEDMODIFICATIONMANAGEMENTCOMMENT, 
	SCHEDULEDMODIFICATIONMANAGEMENTMODIFICATION, 
	SCHEDULEDMODIFICATIONEMPLOYEESCOMMENT, 
	SCHEDULEDMODIFICATIONEMPLOYEESMODIFICATION, 
	SCHEDULEDMODIFICATIONCOOPERATIONMEDICALCOMMENT, 
	SCHEDULEDMODIFICATIONCOOPERATIONMEDICALMODIFICATION, 
	SCHEDULEDMODIFICATIONCOOPERATIONSAFETYCOMMENT, 
	SCHEDULEDMODIFICATIONCOOPERATIONSAFETYMODIFICATION, 
	MODIFICATIONTOTAL, 
	MODIFICATIONTOTALFORGLDETAILPAGE, 
	IncludeProfessionalLiability_out AS INCLUDEPROFESSIONALLIABILITY, 
	IncludeOhioStopGapLiability_out AS INCLUDEOHIOSTOPGAPLIABILITY, 
	Indicator_out AS INDICATOR, 
	PREMIUM, 
	PREMIUMCHANGE, 
	PREMIUMWRITTEN, 
	SCOPE, 
	Deleted_Out AS DELETED, 
	RETRODATE
	FROM EXP_Metadata
),