WITH
SQ_DCBILPolicyTermStage AS (
	SELECT
		DCBILPolicyTermStageId,
		ExtractDate,
		SourceSystemId,
		PolicyTermId,
		PolicyTermEffectiveDate,
		PolicyTermExpirationDate,
		PolicyReference,
		PolicyTermGroupReference,
		PrimaryAccountId,
		PolicyTermConfigTemplate,
		PolicyTermConfig,
		PolicyAggregationReference,
		SplitBillIndicator,
		PolicyTermStatusCode,
		AutoRescindEquityDate,
		PolicyIssueSystemCode,
		PolicyMasterCompanyCode,
		PolicyLineOfBusinessCode,
		PolicyProductCode,
		PolicyStateCode,
		PolicyCountryCode,
		IssueSystemPolicyId,
		RenewalConfigTemplate,
		RenewalConfig,
		RenewalAccountId,
		HoldTypeCode,
		HoldReasonCode,
		HoldStartDate,
		HoldEndDate,
		OutstandingBalance,
		ExpirationActivityDate,
		LastUpdatedTimestamp,
		LastUpdatedUserId,
		PolicyTermLockingTS,
		PolicyTermExtendedData,
		ProcessingOrgUnitCode,
		TransactionGUID,
		PolicyTermConfigCommissionScheme
	FROM DCBILPolicyTermStage
),
EXP_Metadata AS (
	SELECT
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	DCBILPolicyTermStageId,
	ExtractDate,
	SourceSystemId,
	PolicyTermId,
	PolicyTermEffectiveDate,
	PolicyTermExpirationDate,
	PolicyReference,
	PolicyTermGroupReference,
	PrimaryAccountId,
	PolicyTermConfigTemplate,
	PolicyTermConfig,
	PolicyAggregationReference,
	SplitBillIndicator,
	PolicyTermStatusCode,
	AutoRescindEquityDate,
	PolicyIssueSystemCode,
	PolicyMasterCompanyCode,
	PolicyLineOfBusinessCode,
	PolicyProductCode,
	PolicyStateCode,
	PolicyCountryCode,
	IssueSystemPolicyId,
	RenewalConfigTemplate,
	RenewalConfig,
	RenewalAccountId,
	HoldTypeCode,
	HoldReasonCode,
	HoldStartDate,
	HoldEndDate,
	OutstandingBalance,
	ExpirationActivityDate,
	LastUpdatedTimestamp,
	LastUpdatedUserId,
	PolicyTermLockingTS,
	PolicyTermExtendedData,
	ProcessingOrgUnitCode,
	TransactionGUID,
	PolicyTermConfigCommissionScheme
	FROM SQ_DCBILPolicyTermStage
),
LKP_ArchExist AS (
	SELECT
	ArchDCBILPolicyTermStageId,
	PolicyTermId
	FROM (
		SELECT 
			ArchDCBILPolicyTermStageId,
			PolicyTermId
		FROM ArchDCBILPolicyTermStage
	)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY PolicyTermId ORDER BY ArchDCBILPolicyTermStageId) = 1
),
FIL_Exist AS (
	SELECT
	LKP_ArchExist.ArchDCBILPolicyTermStageId AS lkp_ArchDCBILPolicyTermStageId, 
	EXP_Metadata.o_AuditId AS AuditId, 
	EXP_Metadata.DCBILPolicyTermStageId, 
	EXP_Metadata.ExtractDate, 
	EXP_Metadata.SourceSystemId, 
	EXP_Metadata.PolicyTermId, 
	EXP_Metadata.PolicyTermEffectiveDate, 
	EXP_Metadata.PolicyTermExpirationDate, 
	EXP_Metadata.PolicyReference, 
	EXP_Metadata.PolicyTermGroupReference, 
	EXP_Metadata.PrimaryAccountId, 
	EXP_Metadata.PolicyTermConfigTemplate, 
	EXP_Metadata.PolicyTermConfig, 
	EXP_Metadata.PolicyAggregationReference, 
	EXP_Metadata.SplitBillIndicator, 
	EXP_Metadata.PolicyTermStatusCode, 
	EXP_Metadata.AutoRescindEquityDate, 
	EXP_Metadata.PolicyIssueSystemCode, 
	EXP_Metadata.PolicyMasterCompanyCode, 
	EXP_Metadata.PolicyLineOfBusinessCode, 
	EXP_Metadata.PolicyProductCode, 
	EXP_Metadata.PolicyStateCode, 
	EXP_Metadata.PolicyCountryCode, 
	EXP_Metadata.IssueSystemPolicyId, 
	EXP_Metadata.RenewalConfigTemplate, 
	EXP_Metadata.RenewalConfig, 
	EXP_Metadata.RenewalAccountId, 
	EXP_Metadata.HoldTypeCode, 
	EXP_Metadata.HoldReasonCode, 
	EXP_Metadata.HoldStartDate, 
	EXP_Metadata.HoldEndDate, 
	EXP_Metadata.OutstandingBalance, 
	EXP_Metadata.ExpirationActivityDate, 
	EXP_Metadata.LastUpdatedTimestamp, 
	EXP_Metadata.LastUpdatedUserId, 
	EXP_Metadata.PolicyTermLockingTS, 
	EXP_Metadata.PolicyTermExtendedData, 
	EXP_Metadata.ProcessingOrgUnitCode, 
	EXP_Metadata.TransactionGUID, 
	EXP_Metadata.PolicyTermConfigCommissionScheme
	FROM EXP_Metadata
	LEFT JOIN LKP_ArchExist
	ON LKP_ArchExist.PolicyTermId = EXP_Metadata.PolicyTermId
	WHERE ISNULL(lkp_ArchDCBILPolicyTermStageId)
),
ArchDCBILPolicyTermStage AS (
	INSERT INTO ArchDCBILPolicyTermStage
	(ExtractDate, SourceSystemId, AuditId, DCBILPolicyTermStageId, PolicyTermId, PolicyTermEffectiveDate, PolicyTermExpirationDate, PolicyReference, PolicyTermGroupReference, PrimaryAccountId, PolicyTermConfigTemplate, PolicyTermConfig, PolicyAggregationReference, SplitBillIndicator, PolicyTermStatusCode, AutoRescindEquityDate, PolicyIssueSystemCode, PolicyMasterCompanyCode, PolicyLineOfBusinessCode, PolicyProductCode, PolicyStateCode, PolicyCountryCode, IssueSystemPolicyId, RenewalConfigTemplate, RenewalConfig, RenewalAccountId, HoldTypeCode, HoldReasonCode, HoldStartDate, HoldEndDate, OutstandingBalance, ExpirationActivityDate, LastUpdatedTimestamp, LastUpdatedUserId, PolicyTermLockingTS, PolicyTermExtendedData, ProcessingOrgUnitCode, TransactionGUID, PolicyTermConfigCommissionScheme)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	AUDITID, 
	DCBILPOLICYTERMSTAGEID, 
	POLICYTERMID, 
	POLICYTERMEFFECTIVEDATE, 
	POLICYTERMEXPIRATIONDATE, 
	POLICYREFERENCE, 
	POLICYTERMGROUPREFERENCE, 
	PRIMARYACCOUNTID, 
	POLICYTERMCONFIGTEMPLATE, 
	POLICYTERMCONFIG, 
	POLICYAGGREGATIONREFERENCE, 
	SPLITBILLINDICATOR, 
	POLICYTERMSTATUSCODE, 
	AUTORESCINDEQUITYDATE, 
	POLICYISSUESYSTEMCODE, 
	POLICYMASTERCOMPANYCODE, 
	POLICYLINEOFBUSINESSCODE, 
	POLICYPRODUCTCODE, 
	POLICYSTATECODE, 
	POLICYCOUNTRYCODE, 
	ISSUESYSTEMPOLICYID, 
	RENEWALCONFIGTEMPLATE, 
	RENEWALCONFIG, 
	RENEWALACCOUNTID, 
	HOLDTYPECODE, 
	HOLDREASONCODE, 
	HOLDSTARTDATE, 
	HOLDENDDATE, 
	OUTSTANDINGBALANCE, 
	EXPIRATIONACTIVITYDATE, 
	LASTUPDATEDTIMESTAMP, 
	LASTUPDATEDUSERID, 
	POLICYTERMLOCKINGTS, 
	POLICYTERMEXTENDEDDATA, 
	PROCESSINGORGUNITCODE, 
	TRANSACTIONGUID, 
	POLICYTERMCONFIGCOMMISSIONSCHEME
	FROM FIL_Exist
),