WITH
SQ_History AS (
	SELECT
		HistoryID,
		QuoteID,
		ChangeDate,
		Change,
		PreviousPremium,
		Comment,
		Deleted,
		ManuScriptID,
		XMLData,
		FormsXML,
		FormsTempXML,
		TransACTVersion,
		PolicyNumber,
		CancellationDate,
		PolicyEffectiveDate,
		ExpirationDate,
		PolicyStatus,
		State,
		TransactionStatus,
		TransactionEffectiveDate,
		Type,
		ScheduleDate,
		DeprecatedBy,
		UserID,
		TransactionDate,
		DuplicateRow,
		OffsetDate,
		HasPremiumImpact,
		WrittenPremium,
		ChangePremium,
		ZippedXML,
		BillingStatus,
		InforceStatus,
		RenewStatus
	FROM History
	WHERE upper(History.Type) ='NEW'
),
EXP_Default1 AS (
	SELECT
	SYSDATE AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	HistoryID,
	QuoteID,
	ChangeDate,
	Change,
	PreviousPremium,
	Comment,
	Deleted,
	ManuScriptID,
	TransACTVersion,
	PolicyNumber,
	CancellationDate,
	PolicyEffectiveDate,
	ExpirationDate,
	PolicyStatus,
	State,
	TransactionStatus,
	TransactionEffectiveDate,
	Type,
	ScheduleDate,
	DeprecatedBy,
	UserID,
	TransactionDate,
	DuplicateRow,
	OffsetDate,
	HasPremiumImpact,
	WrittenPremium,
	ChangePremium,
	BillingStatus,
	InforceStatus,
	RenewStatus
	FROM SQ_History
),
HistoryStage AS (
	TRUNCATE TABLE HistoryStage;
	INSERT INTO HistoryStage
	(ExtractDate, SourceSystemId, HistoryID, QuoteID, ChangeDate, Change, PreviousPremium, Comment, Deleted, ManuScriptID, TransACTVersion, PolicyNumber, CancellationDate, PolicyEffectiveDate, ExpirationDate, PolicyStatus, State, TransactionStatus, TransactionEffectiveDate, Type, ScheduleDate, DeprecatedBy, UserID, TransactionDate, DuplicateRow, OffsetDate, HasPremiumImpact, WrittenPremium, ChangePremium, BillingStatus, InforceStatus, RenewStatus)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	HISTORYID, 
	QUOTEID, 
	CHANGEDATE, 
	CHANGE, 
	PREVIOUSPREMIUM, 
	COMMENT, 
	DELETED, 
	MANUSCRIPTID, 
	TRANSACTVERSION, 
	POLICYNUMBER, 
	CANCELLATIONDATE, 
	POLICYEFFECTIVEDATE, 
	EXPIRATIONDATE, 
	POLICYSTATUS, 
	STATE, 
	TRANSACTIONSTATUS, 
	TRANSACTIONEFFECTIVEDATE, 
	TYPE, 
	SCHEDULEDATE, 
	DEPRECATEDBY, 
	USERID, 
	TRANSACTIONDATE, 
	DUPLICATEROW, 
	OFFSETDATE, 
	HASPREMIUMIMPACT, 
	WRITTENPREMIUM, 
	CHANGEPREMIUM, 
	BILLINGSTATUS, 
	INFORCESTATUS, 
	RENEWSTATUS
	FROM EXP_Default1
),