WITH
SQ_WBCfBuildingStage AS (
	SELECT
		WBCFBuildingStageId AS WbCfBuildingStageId,
		CFBuildingId,
		WBCFBuildingId AS WbCfBuildingId,
		SessionId,
		BuildingNumber,
		ExtractDate,
		SourceSystemId,
		FirstTimeOnBuildingScreen,
		SprinkleredBuildingStoredValue,
		UtilityServicesARateStoredValue,
		UtilityServicesCommunicationSupplyStoredValue,
		UtilityServicesDirectDamageIndicatorStoredValue,
		UtilityServicesDirectDamagePropertyDescriptionStoredValue,
		UtilityServicesIndicatorStoredValue,
		UtilityServicesLimitStoredValue,
		GolfCourseCoverageStoredValue,
		GolfCourseDeductibleStoredValue,
		GolfCourseLimitStoredValue,
		SpecificRatedBG1RateStoredValue,
		SpecificRatedBG2RateStoredValue,
		SpecificRatedEffectiveDateStoredValue,
		UtilityServicesPowerSupplyStoredValue,
		UtilityServicesProviderTypeStoredValue,
		UtilityServicesWaterSupplyStoredValue,
		SpecificRatedStoredValue,
		SprinklerPercentageStoredValue,
		SprinklerProtectionDeviceStoredValue,
		SpecificRatedRCPStoredValue,
		SpecificRatedRateStatusStoredValue,
		SpecificRatedRiskIDStoredValue,
		OtherSprinklerProtectionDeviceStoredValue
	FROM WbCfBuildingStage
),
EXP_Metadata AS (
	SELECT
	WbCfBuildingStageId,
	CFBuildingId,
	WbCfBuildingId,
	SessionId,
	BuildingNumber,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	FirstTimeOnBuildingScreen,
	-- *INF*: DECODE(FirstTimeOnBuildingScreen,'T',1,'F',0,NULL)
	DECODE(
	    FirstTimeOnBuildingScreen,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_FirstTimeOnBuildingScreen,
	SprinkleredBuildingStoredValue,
	UtilityServicesARateStoredValue,
	UtilityServicesCommunicationSupplyStoredValue,
	UtilityServicesDirectDamageIndicatorStoredValue,
	UtilityServicesDirectDamagePropertyDescriptionStoredValue,
	UtilityServicesIndicatorStoredValue,
	UtilityServicesLimitStoredValue,
	GolfCourseCoverageStoredValue,
	GolfCourseDeductibleStoredValue,
	GolfCourseLimitStoredValue,
	SpecificRatedBG1RateStoredValue,
	SpecificRatedBG2RateStoredValue,
	SpecificRatedEffectiveDateStoredValue,
	UtilityServicesPowerSupplyStoredValue,
	UtilityServicesProviderTypeStoredValue,
	UtilityServicesWaterSupplyStoredValue,
	SpecificRatedStoredValue,
	SprinklerPercentageStoredValue,
	SprinklerProtectionDeviceStoredValue,
	SpecificRatedRCPStoredValue,
	SpecificRatedRateStatusStoredValue,
	SpecificRatedRiskIDStoredValue,
	OtherSprinklerProtectionDeviceStoredValue
	FROM SQ_WBCfBuildingStage
),
ArchWBCfBuildingStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBCfBuildingStage
	(ExtractDate, SourceSystemId, AuditId, WBCFBuildingStageId, CFBuildingId, WBCFBuildingId, SessionId, BuildingNumber, FirstTimeOnBuildingScreen, SprinkleredBuildingStoredValue, UtilityServicesARateStoredValue, UtilityServicesCommunicationSupplyStoredValue, UtilityServicesDirectDamageIndicatorStoredValue, UtilityServicesDirectDamagePropertyDescriptionStoredValue, UtilityServicesIndicatorStoredValue, UtilityServicesLimitStoredValue, GolfCourseCoverageStoredValue, GolfCourseDeductibleStoredValue, GolfCourseLimitStoredValue, SpecificRatedBG1RateStoredValue, SpecificRatedBG2RateStoredValue, SpecificRatedEffectiveDateStoredValue, UtilityServicesPowerSupplyStoredValue, UtilityServicesProviderTypeStoredValue, UtilityServicesWaterSupplyStoredValue, SpecificRatedStoredValue, SprinklerPercentageStoredValue, SprinklerProtectionDeviceStoredValue, SpecificRatedRCPStoredValue, SpecificRatedRateStatusStoredValue, SpecificRatedRiskIDStoredValue, OtherSprinklerProtectionDeviceStoredValue)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WbCfBuildingStageId AS WBCFBUILDINGSTAGEID, 
	CFBUILDINGID, 
	WbCfBuildingId AS WBCFBUILDINGID, 
	SESSIONID, 
	BUILDINGNUMBER, 
	o_FirstTimeOnBuildingScreen AS FIRSTTIMEONBUILDINGSCREEN, 
	SPRINKLEREDBUILDINGSTOREDVALUE, 
	UTILITYSERVICESARATESTOREDVALUE, 
	UTILITYSERVICESCOMMUNICATIONSUPPLYSTOREDVALUE, 
	UTILITYSERVICESDIRECTDAMAGEINDICATORSTOREDVALUE, 
	UTILITYSERVICESDIRECTDAMAGEPROPERTYDESCRIPTIONSTOREDVALUE, 
	UTILITYSERVICESINDICATORSTOREDVALUE, 
	UTILITYSERVICESLIMITSTOREDVALUE, 
	GOLFCOURSECOVERAGESTOREDVALUE, 
	GOLFCOURSEDEDUCTIBLESTOREDVALUE, 
	GOLFCOURSELIMITSTOREDVALUE, 
	SPECIFICRATEDBG1RATESTOREDVALUE, 
	SPECIFICRATEDBG2RATESTOREDVALUE, 
	SPECIFICRATEDEFFECTIVEDATESTOREDVALUE, 
	UTILITYSERVICESPOWERSUPPLYSTOREDVALUE, 
	UTILITYSERVICESPROVIDERTYPESTOREDVALUE, 
	UTILITYSERVICESWATERSUPPLYSTOREDVALUE, 
	SPECIFICRATEDSTOREDVALUE, 
	SPRINKLERPERCENTAGESTOREDVALUE, 
	SPRINKLERPROTECTIONDEVICESTOREDVALUE, 
	SPECIFICRATEDRCPSTOREDVALUE, 
	SPECIFICRATEDRATESTATUSSTOREDVALUE, 
	SPECIFICRATEDRISKIDSTOREDVALUE, 
	OTHERSPRINKLERPROTECTIONDEVICESTOREDVALUE
	FROM EXP_Metadata
),