WITH
SQ_WBCUUmbrellaSMARTbusinessStage AS (
	SELECT
		WBCUUmbrellaSMARTBusinessStageId,
		LineId,
		WBCUUmbrellaSMARTbusinessId,
		SessionId,
		Deleted,
		Description,
		EffectiveDate,
		ExpirationDate,
		PersonalLiability,
		PolicyNumber,
		ProfessionalLiabilityAggregateLimit,
		SMARTbusinessPremium,
		FirstMillionBasePremium,
		FirstMillionModifiedPremium,
		RevisedPremium,
		CoverageForm,
		IncludeProfessionalLiability,
		ScheduledModification,
		Override,
		Premium,
		PremiumChange,
		PremiumWritten,
		IDField,
		UmbrellaSMARTBusinessScheduledModificationLocationInComment,
		UmbrellaSMARTBusinessScheduledModificationLocationInModification,
		UmbrellaSMARTBusinessScheduledModificationLocationOutComment,
		UmbrellaSMARTBusinessScheduledModificationLocationOutModification,
		UmbrellaSMARTBusinessScheduledModificationPremisesComment,
		UmbrellaSMARTBusinessScheduledModificationPremisesModification,
		UmbrellaSMARTBusinessScheduledModificationEquipmentComment,
		UmbrellaSMARTBusinessScheduledModificationEquipmentModification,
		UmbrellaSMARTBusinessScheduledModificationManagementComment,
		UmbrellaSMARTBusinessScheduledModificationManagementModification,
		UmbrellaSMARTBusinessScheduledModificationEmployeesComment,
		UmbrellaSMARTBusinessScheduledModificationEmployeesModification,
		UmbrellaSMARTBusinessScheduledModificationCooperationMedicalComment,
		UmbrellaSMARTBusinessScheduledModificationCooperationMedicalModification,
		UmbrellaSMARTBusinessScheduledModificationCooperationSafetyComment,
		UmbrellaSMARTBusinessScheduledModificationCooperationSafetyModification,
		ModificationTotal,
		ModificationTotalForSMARTBusinessDetailPage,
		ExtractDate,
		SourceSystemId
	FROM WBCUUmbrellaSMARTBusinessStage
),
EXP_Metadata AS (
	SELECT
	WBCUUmbrellaSMARTBusinessStageId,
	LineId,
	WBCUUmbrellaSMARTbusinessId,
	SessionId,
	Deleted AS i_Deleted,
	-- *INF*: DECODE(i_Deleted,'T',1,'F',0,NULL)
	DECODE(
	    i_Deleted,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_Deleted,
	Description,
	EffectiveDate,
	ExpirationDate,
	PersonalLiability AS i_PersonalLiability,
	-- *INF*: DECODE(i_PersonalLiability,'T',1,'F',0,NULL)
	DECODE(
	    i_PersonalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PersonalLiability,
	PolicyNumber,
	ProfessionalLiabilityAggregateLimit,
	SMARTbusinessPremium,
	FirstMillionBasePremium,
	FirstMillionModifiedPremium,
	RevisedPremium,
	CoverageForm,
	IncludeProfessionalLiability AS i_IncludeProfessionalLiability,
	-- *INF*: DECODE(i_IncludeProfessionalLiability,'T',1,'F',0,NULL)
	DECODE(
	    i_IncludeProfessionalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_IncludeProfessionalLiability,
	ScheduledModification,
	Override AS i_Override,
	-- *INF*: DECODE(i_Override,'T',1,'F',0,NULL)
	DECODE(
	    i_Override,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_Override,
	Premium,
	PremiumChange,
	PremiumWritten,
	IDField,
	UmbrellaSMARTBusinessScheduledModificationLocationInComment,
	UmbrellaSMARTBusinessScheduledModificationLocationInModification,
	UmbrellaSMARTBusinessScheduledModificationLocationOutComment,
	UmbrellaSMARTBusinessScheduledModificationLocationOutModification,
	UmbrellaSMARTBusinessScheduledModificationPremisesComment,
	UmbrellaSMARTBusinessScheduledModificationPremisesModification,
	UmbrellaSMARTBusinessScheduledModificationEquipmentComment,
	UmbrellaSMARTBusinessScheduledModificationEquipmentModification,
	UmbrellaSMARTBusinessScheduledModificationManagementComment,
	UmbrellaSMARTBusinessScheduledModificationManagementModification,
	UmbrellaSMARTBusinessScheduledModificationEmployeesComment,
	UmbrellaSMARTBusinessScheduledModificationEmployeesModification,
	UmbrellaSMARTBusinessScheduledModificationCooperationMedicalComment,
	UmbrellaSMARTBusinessScheduledModificationCooperationMedicalModification,
	UmbrellaSMARTBusinessScheduledModificationCooperationSafetyComment,
	UmbrellaSMARTBusinessScheduledModificationCooperationSafetyModification,
	ModificationTotal,
	ModificationTotalForSMARTBusinessDetailPage,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_WBCUUmbrellaSMARTbusinessStage
),
ArchWBCUUmbrellaSMARTBusinessStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBCUUmbrellaSMARTBusinessStage
	(WBCUUmbrellaSMARTBusinessStageId, LineId, WBCUUmbrellaSMARTbusinessId, SessionId, Deleted, Description, EffectiveDate, ExpirationDate, PersonalLiability, PolicyNumber, ProfessionalLiabilityAggregateLimit, SMARTbusinessPremium, FirstMillionBasePremium, FirstMillionModifiedPremium, RevisedPremium, CoverageForm, IncludeProfessionalLiability, ScheduledModification, Override, Premium, PremiumChange, PremiumWritten, IDField, UmbrellaSMARTBusinessScheduledModificationLocationInComment, UmbrellaSMARTBusinessScheduledModificationLocationInModification, UmbrellaSMARTBusinessScheduledModificationLocationOutComment, UmbrellaSMARTBusinessScheduledModificationLocationOutModification, UmbrellaSMARTBusinessScheduledModificationPremisesComment, UmbrellaSMARTBusinessScheduledModificationPremisesModification, UmbrellaSMARTBusinessScheduledModificationEquipmentComment, UmbrellaSMARTBusinessScheduledModificationEquipmentModification, UmbrellaSMARTBusinessScheduledModificationManagementComment, UmbrellaSMARTBusinessScheduledModificationManagementModification, UmbrellaSMARTBusinessScheduledModificationEmployeesComment, UmbrellaSMARTBusinessScheduledModificationEmployeesModification, UmbrellaSMARTBusinessScheduledModificationCooperationMedicalComment, UmbrellaSMARTBusinessScheduledModificationCooperationMedicalModification, UmbrellaSMARTBusinessScheduledModificationCooperationSafetyComment, UmbrellaSMARTBusinessScheduledModificationCooperationSafetyModification, ModificationTotal, ModificationTotalForSMARTBusinessDetailPage, ExtractDate, SourceSystemId, AuditId)
	SELECT 
	WBCUUMBRELLASMARTBUSINESSSTAGEID, 
	LINEID, 
	WBCUUMBRELLASMARTBUSINESSID, 
	SESSIONID, 
	o_Deleted AS DELETED, 
	DESCRIPTION, 
	EFFECTIVEDATE, 
	EXPIRATIONDATE, 
	o_PersonalLiability AS PERSONALLIABILITY, 
	POLICYNUMBER, 
	PROFESSIONALLIABILITYAGGREGATELIMIT, 
	SMARTBUSINESSPREMIUM, 
	FIRSTMILLIONBASEPREMIUM, 
	FIRSTMILLIONMODIFIEDPREMIUM, 
	REVISEDPREMIUM, 
	COVERAGEFORM, 
	o_IncludeProfessionalLiability AS INCLUDEPROFESSIONALLIABILITY, 
	SCHEDULEDMODIFICATION, 
	o_Override AS OVERRIDE, 
	PREMIUM, 
	PREMIUMCHANGE, 
	PREMIUMWRITTEN, 
	IDFIELD, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONLOCATIONINCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONLOCATIONINMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONLOCATIONOUTCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONLOCATIONOUTMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONPREMISESCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONPREMISESMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONEQUIPMENTCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONEQUIPMENTMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONMANAGEMENTCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONMANAGEMENTMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONEMPLOYEESCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONEMPLOYEESMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONCOOPERATIONMEDICALCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONCOOPERATIONMEDICALMODIFICATION, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONCOOPERATIONSAFETYCOMMENT, 
	UMBRELLASMARTBUSINESSSCHEDULEDMODIFICATIONCOOPERATIONSAFETYMODIFICATION, 
	MODIFICATIONTOTAL, 
	MODIFICATIONTOTALFORSMARTBUSINESSDETAILPAGE, 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID
	FROM EXP_Metadata
),