WITH
SQ_WB_CF_Risk AS (
	WITH cte_WBCFRisk(Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.CF_RiskId, 
	X.WB_CF_RiskId, 
	X.SessionId, 
	X.PurePremium, 
	X.OriginalPackageModifier, 
	X.CurrentFiledRatesBG1, 
	X.CurrentFiledRatesBG2, 
	X.CurrentFiledRatesAllOther, 
	X.ExpiringRatesBG1, 
	X.ExpiringRatesBG2, 
	X.ExpiringRatesAllOther, 
	X.DifferenceBG1, 
	X.DifferenceBG2, 
	X.DifferenceAllOther, 
	X.AdjustmentBG1, 
	X.One, 
	X.AdjustmentBG2, 
	X.AdjustmentAllOther, 
	X.Selected, 
	X.LastExpiringRatesBG1, 
	X.LastExpiringRatesBG2, 
	X.LastExpiringRatesAllOther, 
	X.Year1Adj, 
	X.Year2Adj, 
	X.Year3Adj, 
	X.Year1AdjBG2, 
	X.Year2AdjBG2, 
	X.Year3AdjBG2, 
	X.Year1AdjAllOther, 
	X.Year2AdjAllOther, 
	X.Year3AdjAllOther, 
	X.ExpiringRatesCaption, 
	X.CurrentFiledRatesCaption, 
	X.DifferenceCaption, 
	X.AdjustmentFactorCaption, 
	X.HeaderExpiringRates, 
	X.HeaderCurrentFiledRates, 
	X.HeaderDifference, 
	X.HeaderAdjustmentFactor, 
	X.RiskID, 
	X.BuildingID 
	FROM
	WB_CF_Risk X
	inner join
	cte_WBCFRisk Y on X.Sessionid = Y.Sessionid
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Metadata AS (
	SELECT
	CF_RiskId,
	WB_CF_RiskId,
	SessionId,
	PurePremium,
	OriginalPackageModifier,
	CurrentFiledRatesBG1,
	CurrentFiledRatesBG2,
	CurrentFiledRatesAllOther,
	ExpiringRatesBG1,
	ExpiringRatesBG2,
	ExpiringRatesAllOther,
	DifferenceBG1,
	DifferenceBG2,
	DifferenceAllOther,
	AdjustmentBG1,
	One,
	AdjustmentBG2,
	AdjustmentAllOther,
	Selected AS i_Selected,
	-- *INF*: DECODE(i_Selected, 'T', '1', 'F', '0', NULL)
	DECODE(
	    i_Selected,
	    'T', '1',
	    'F', '0',
	    NULL
	) AS o_Selected,
	LastExpiringRatesBG1,
	LastExpiringRatesBG2,
	LastExpiringRatesAllOther,
	Year1Adj,
	Year2Adj,
	Year3Adj,
	Year1AdjBG2,
	Year2AdjBG2,
	Year3AdjBG2,
	Year1AdjAllOther,
	Year2AdjAllOther,
	Year3AdjAllOther,
	ExpiringRatesCaption,
	CurrentFiledRatesCaption,
	DifferenceCaption,
	AdjustmentFactorCaption,
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	HeaderExpiringRates,
	HeaderCurrentFiledRates,
	HeaderDifference,
	HeaderAdjustmentFactor,
	RiskID,
	BuildingID
	FROM SQ_WB_CF_Risk
),
WBCFRiskStage AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCFRiskStage;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.WBCFRiskStage
	(ExtractDate, SourceSystemId, CF_RiskId, WB_CF_RiskId, SessionId, PurePremium, OriginalPackageModifier, CurrentFiledRatesBG1, CurrentFiledRatesBG2, CurrentFiledRatesAllOther, Selected, ExpiringRatesBG1, ExpiringRatesBG2, ExpiringRatesAllOther, DifferenceBG1, DifferenceBG2, DifferenceAllOther, AdjustmentBG1, One, AdjustmentBG2, AdjustmentAllOther, LastExpiringRatesBG1, LastExpiringRatesBG2, LastExpiringRatesAllOther, Year1Adj, Year2Adj, Year3Adj, Year1AdjBG2, Year2AdjBG2, Year3AdjBG2, Year1AdjAllOther, Year2AdjAllOther, Year3AdjAllOther, ExpiringRatesCaption, CurrentFiledRatesCaption, DifferenceCaption, AdjustmentFactorCaption, HeaderExpiringRates, HeaderCurrentFiledRates, HeaderDifference, HeaderAdjustmentFactor, RiskID, BuildingID)
	SELECT 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	CF_RISKID, 
	WB_CF_RISKID, 
	SESSIONID, 
	PUREPREMIUM, 
	ORIGINALPACKAGEMODIFIER, 
	CURRENTFILEDRATESBG1, 
	CURRENTFILEDRATESBG2, 
	CURRENTFILEDRATESALLOTHER, 
	o_Selected AS SELECTED, 
	EXPIRINGRATESBG1, 
	EXPIRINGRATESBG2, 
	EXPIRINGRATESALLOTHER, 
	DIFFERENCEBG1, 
	DIFFERENCEBG2, 
	DIFFERENCEALLOTHER, 
	ADJUSTMENTBG1, 
	ONE, 
	ADJUSTMENTBG2, 
	ADJUSTMENTALLOTHER, 
	LASTEXPIRINGRATESBG1, 
	LASTEXPIRINGRATESBG2, 
	LASTEXPIRINGRATESALLOTHER, 
	YEAR1ADJ, 
	YEAR2ADJ, 
	YEAR3ADJ, 
	YEAR1ADJBG2, 
	YEAR2ADJBG2, 
	YEAR3ADJBG2, 
	YEAR1ADJALLOTHER, 
	YEAR2ADJALLOTHER, 
	YEAR3ADJALLOTHER, 
	EXPIRINGRATESCAPTION, 
	CURRENTFILEDRATESCAPTION, 
	DIFFERENCECAPTION, 
	ADJUSTMENTFACTORCAPTION, 
	HEADEREXPIRINGRATES, 
	HEADERCURRENTFILEDRATES, 
	HEADERDIFFERENCE, 
	HEADERADJUSTMENTFACTOR, 
	RISKID, 
	BUILDINGID
	FROM EXP_Metadata
),