WITH
SQ_WBGLLocationAccountStage AS (
	SELECT
		WBGLLocationAccountStageId,
		ExtractDate,
		SourceSystemId,
		WB_CL_LocationAccountId,
		WB_GL_LocationAccountId,
		SessionId,
		LiabScheduleModCooperationMedicalSetLiabilityValue,
		LiabScheduleModCooperationMedicalSetCommentValue,
		SetCommentValue,
		LiabScheduleModClassificationSetLiabilityValue,
		LiabScheduleModCooperationSafetySetLiabilityValue,
		LiabScheduleModCooperationSafetySetCommentValue,
		LiabScheduleModEmployeesSetCommentValue,
		LiabScheduleModEmployeesSetLiabilityValue,
		LiabScheduleModEquipmentSetCommentValue,
		LiabScheduleModEquipmentSetLiabilityValue,
		LiabScheduleModLocationInsideSetCommentValue,
		LiabScheduleModLocationInsideSetLiabilityValue,
		LiabScheduleModLocationOutsideSetCommentValue,
		LiabScheduleModLocationOutsideSetLiabilityValue,
		LiabScheduleModPremisesSetCommentValue,
		LiabScheduleModPremisesSetLiabilityValue,
		LiquorPermitNumber,
		MunicipalAutoRate,
		MunicipalLiabilityRate,
		MunicipalMarineRate,
		MunicipalMinimumRate,
		MunicipalOtherRate,
		MunicipalPropertyRate,
		CountyAutoRate,
		CountyLiabilityRate,
		CountyMarineRate,
		CountyMinimumRate,
		CountyOtherRate,
		CountyPropertyRate,
		GeoTaxConfidence,
		CertifiedOperationsFactor,
		NighttimeOperationsFactor,
		ProgramFactor,
		AssociationFactor,
		MaximumNumberOfChildren,
		HoursOpen,
		OnlyBeforeAndAfterSchoolCare,
		DogCatCoverage,
		DogBreedsPresent,
		OwnAnyBuildings,
		LeaseAnyBuildingsToOthers,
		TotalSquareFeetLeasedToOthers,
		TotalNumberApartments,
		IndependentContractors,
		NumberFullTimeBeauticians,
		NumberPartTimeBeauticians,
		NumberFullTimeElectrologists,
		NumberPartTimeElectrologists,
		NumberFullTimeMassageTherapists,
		NumberPartTimeMassageTherapists,
		NumberBeautyInstructors,
		NumberAquaMassageBeds,
		NumberSuntanBeds,
		NumberAirBrushOrSprayOnBooths,
		NumberHotTubs,
		NumberCircuitWorkout,
		OutdoorServiceArea
	FROM WBGLLocationAccountStage
),
EXPTRANS AS (
	SELECT
	WBGLLocationAccountStageId,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId,
	WB_CL_LocationAccountId,
	WB_GL_LocationAccountId,
	SessionId,
	LiabScheduleModCooperationMedicalSetLiabilityValue,
	LiabScheduleModCooperationMedicalSetCommentValue,
	SetCommentValue,
	LiabScheduleModClassificationSetLiabilityValue,
	LiabScheduleModCooperationSafetySetLiabilityValue,
	LiabScheduleModCooperationSafetySetCommentValue,
	LiabScheduleModEmployeesSetCommentValue,
	LiabScheduleModEmployeesSetLiabilityValue,
	LiabScheduleModEquipmentSetCommentValue,
	LiabScheduleModEquipmentSetLiabilityValue,
	LiabScheduleModLocationInsideSetCommentValue,
	LiabScheduleModLocationInsideSetLiabilityValue,
	LiabScheduleModLocationOutsideSetCommentValue,
	LiabScheduleModLocationOutsideSetLiabilityValue,
	LiabScheduleModPremisesSetCommentValue,
	LiabScheduleModPremisesSetLiabilityValue,
	LiquorPermitNumber,
	MunicipalAutoRate,
	MunicipalLiabilityRate,
	MunicipalMarineRate,
	MunicipalMinimumRate,
	MunicipalOtherRate,
	MunicipalPropertyRate,
	CountyAutoRate,
	CountyLiabilityRate,
	CountyMarineRate,
	CountyMinimumRate,
	CountyOtherRate,
	CountyPropertyRate,
	GeoTaxConfidence,
	CertifiedOperationsFactor,
	NighttimeOperationsFactor,
	ProgramFactor,
	AssociationFactor,
	MaximumNumberOfChildren,
	HoursOpen,
	OnlyBeforeAndAfterSchoolCare AS i_OnlyBeforeAndAfterSchoolCare,
	-- *INF*: IIF(i_OnlyBeforeAndAfterSchoolCare='T','1','0')
	IFF(i_OnlyBeforeAndAfterSchoolCare = 'T', '1', '0') AS o_OnlyBeforeAndAfterSchoolCare1,
	DogCatCoverage,
	DogBreedsPresent AS i_DogBreedsPresent,
	-- *INF*: IIF(i_DogBreedsPresent='T','1','0')
	IFF(i_DogBreedsPresent = 'T', '1', '0') AS o_DogBreedsPresent,
	OwnAnyBuildings AS i_OwnAnyBuildings,
	-- *INF*: IIF(i_OwnAnyBuildings='T','1','0')
	IFF(i_OwnAnyBuildings = 'T', '1', '0') AS o_OwnAnyBuildings,
	LeaseAnyBuildingsToOthers AS i_LeaseAnyBuildingsToOthers,
	-- *INF*: IIF(i_LeaseAnyBuildingsToOthers='T','1','0')
	IFF(i_LeaseAnyBuildingsToOthers = 'T', '1', '0') AS o_LeaseAnyBuildingsToOthers,
	TotalSquareFeetLeasedToOthers,
	TotalNumberApartments,
	IndependentContractors AS i_IndependentContractors,
	-- *INF*: IIF(i_IndependentContractors='T','1','0')
	IFF(i_IndependentContractors = 'T', '1', '0') AS o_IndependentContractors,
	NumberFullTimeBeauticians,
	NumberPartTimeBeauticians,
	NumberFullTimeElectrologists,
	NumberPartTimeElectrologists,
	NumberFullTimeMassageTherapists,
	NumberPartTimeMassageTherapists,
	NumberBeautyInstructors,
	NumberAquaMassageBeds,
	NumberSuntanBeds,
	NumberAirBrushOrSprayOnBooths,
	NumberHotTubs,
	NumberCircuitWorkout,
	OutdoorServiceArea
	FROM SQ_WBGLLocationAccountStage
),
ArchWBGLLocationAccountStage AS (
	INSERT INTO ArchWBGLLocationAccountStage
	(ExtractDate, SourceSystemId, AuditId, WBGLLocationAccountStageId, WB_CL_LocationAccountId, WB_GL_LocationAccountId, SessionId, LiabScheduleModCooperationMedicalSetLiabilityValue, LiabScheduleModCooperationMedicalSetCommentValue, SetCommentValue, LiabScheduleModClassificationSetLiabilityValue, LiabScheduleModCooperationSafetySetLiabilityValue, LiabScheduleModCooperationSafetySetCommentValue, LiabScheduleModEmployeesSetCommentValue, LiabScheduleModEmployeesSetLiabilityValue, LiabScheduleModEquipmentSetCommentValue, LiabScheduleModEquipmentSetLiabilityValue, LiabScheduleModLocationInsideSetCommentValue, LiabScheduleModLocationInsideSetLiabilityValue, LiabScheduleModLocationOutsideSetCommentValue, LiabScheduleModLocationOutsideSetLiabilityValue, LiabScheduleModPremisesSetCommentValue, LiabScheduleModPremisesSetLiabilityValue, LiquorPermitNumber, MunicipalAutoRate, MunicipalLiabilityRate, MunicipalMarineRate, MunicipalMinimumRate, MunicipalOtherRate, MunicipalPropertyRate, CountyAutoRate, CountyLiabilityRate, CountyMarineRate, CountyMinimumRate, CountyOtherRate, CountyPropertyRate, GeoTaxConfidence, CertifiedOperationsFactor, NighttimeOperationsFactor, ProgramFactor, AssociationFactor, MaximumNumberOfChildren, HoursOpen, OnlyBeforeAndAfterSchoolCare, DogCatCoverage, DogBreedsPresent, OwnAnyBuildings, LeaseAnyBuildingsToOthers, TotalSquareFeetLeasedToOthers, TotalNumberApartments, IndependentContractors, NumberFullTimeBeauticians, NumberPartTimeBeauticians, NumberFullTimeElectrologists, NumberPartTimeElectrologists, NumberFullTimeMassageTherapists, NumberPartTimeMassageTherapists, NumberBeautyInstructors, NumberAquaMassageBeds, NumberSuntanBeds, NumberAirBrushOrSprayOnBooths, NumberHotTubs, NumberCircuitWorkout, OutdoorServiceArea)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBGLLOCATIONACCOUNTSTAGEID, 
	WB_CL_LOCATIONACCOUNTID, 
	WB_GL_LOCATIONACCOUNTID, 
	SESSIONID, 
	LIABSCHEDULEMODCOOPERATIONMEDICALSETLIABILITYVALUE, 
	LIABSCHEDULEMODCOOPERATIONMEDICALSETCOMMENTVALUE, 
	SETCOMMENTVALUE, 
	LIABSCHEDULEMODCLASSIFICATIONSETLIABILITYVALUE, 
	LIABSCHEDULEMODCOOPERATIONSAFETYSETLIABILITYVALUE, 
	LIABSCHEDULEMODCOOPERATIONSAFETYSETCOMMENTVALUE, 
	LIABSCHEDULEMODEMPLOYEESSETCOMMENTVALUE, 
	LIABSCHEDULEMODEMPLOYEESSETLIABILITYVALUE, 
	LIABSCHEDULEMODEQUIPMENTSETCOMMENTVALUE, 
	LIABSCHEDULEMODEQUIPMENTSETLIABILITYVALUE, 
	LIABSCHEDULEMODLOCATIONINSIDESETCOMMENTVALUE, 
	LIABSCHEDULEMODLOCATIONINSIDESETLIABILITYVALUE, 
	LIABSCHEDULEMODLOCATIONOUTSIDESETCOMMENTVALUE, 
	LIABSCHEDULEMODLOCATIONOUTSIDESETLIABILITYVALUE, 
	LIABSCHEDULEMODPREMISESSETCOMMENTVALUE, 
	LIABSCHEDULEMODPREMISESSETLIABILITYVALUE, 
	LIQUORPERMITNUMBER, 
	MUNICIPALAUTORATE, 
	MUNICIPALLIABILITYRATE, 
	MUNICIPALMARINERATE, 
	MUNICIPALMINIMUMRATE, 
	MUNICIPALOTHERRATE, 
	MUNICIPALPROPERTYRATE, 
	COUNTYAUTORATE, 
	COUNTYLIABILITYRATE, 
	COUNTYMARINERATE, 
	COUNTYMINIMUMRATE, 
	COUNTYOTHERRATE, 
	COUNTYPROPERTYRATE, 
	GEOTAXCONFIDENCE, 
	CERTIFIEDOPERATIONSFACTOR, 
	NIGHTTIMEOPERATIONSFACTOR, 
	PROGRAMFACTOR, 
	ASSOCIATIONFACTOR, 
	MAXIMUMNUMBEROFCHILDREN, 
	HOURSOPEN, 
	o_OnlyBeforeAndAfterSchoolCare1 AS ONLYBEFOREANDAFTERSCHOOLCARE, 
	DOGCATCOVERAGE, 
	o_DogBreedsPresent AS DOGBREEDSPRESENT, 
	o_OwnAnyBuildings AS OWNANYBUILDINGS, 
	o_LeaseAnyBuildingsToOthers AS LEASEANYBUILDINGSTOOTHERS, 
	TOTALSQUAREFEETLEASEDTOOTHERS, 
	TOTALNUMBERAPARTMENTS, 
	o_IndependentContractors AS INDEPENDENTCONTRACTORS, 
	NUMBERFULLTIMEBEAUTICIANS, 
	NUMBERPARTTIMEBEAUTICIANS, 
	NUMBERFULLTIMEELECTROLOGISTS, 
	NUMBERPARTTIMEELECTROLOGISTS, 
	NUMBERFULLTIMEMASSAGETHERAPISTS, 
	NUMBERPARTTIMEMASSAGETHERAPISTS, 
	NUMBERBEAUTYINSTRUCTORS, 
	NUMBERAQUAMASSAGEBEDS, 
	NUMBERSUNTANBEDS, 
	NUMBERAIRBRUSHORSPRAYONBOOTHS, 
	NUMBERHOTTUBS, 
	NUMBERCIRCUITWORKOUT, 
	OUTDOORSERVICEAREA
	FROM EXPTRANS
),