WITH
SQ_WBCUUmbrellaSBOPStage AS (
	SELECT
		WBCUUmbrellaSBOPStageId,
		LineId,
		WBCUUmbrellaSBOPId,
		SessionId,
		Deleted,
		CoverageForm,
		Description,
		EffectiveDate,
		ExpirationDate,
		PersonalLiability,
		PolicyNumber,
		ProfessionalLiabilityEachOccurrenceClaimLimit,
		ProfessionalLiabilityAggregate,
		BodilyInjuryByAccidentEachAccident,
		BodilyInjuryByDiseaseEachEmployee,
		BodilyInjuryByDiseaseAggregate,
		FirstMillionBasePremium,
		FirstMillionModifiedPremium,
		PremOpsTotalPremiumTable1,
		PremOpsTotalPremiumTable2,
		PremOpsTotalPremiumTable3,
		AllOtherPremium,
		ProductsTotalPremiumTableA,
		ProductsTotalPremiumTableB,
		ProductsTotalPremiumTableC,
		IncludeProfessionalLiability,
		AllOtherPremiumOverride,
		PremOpsTotalPremiumTable1PremiumOverride,
		PremOpsTotalPremiumTable2PremiumOverride,
		PremOpsTotalPremiumTable3PremiumOverride,
		ProductsTotalPremiumTableAPremiumOverride,
		ProductsTotalPremiumTableBPremiumOverride,
		ProductsTotalPremiumTableCPremiumOverride,
		AllOtherRevisedPremium,
		PremOpsTotalPremiumTable1RevisedPremium,
		PremOpsTotalPremiumTable2RevisedPremium,
		PremOpsTotalPremiumTable3RevisedPremium,
		ProductsTotalPremiumTableARevisedPremium,
		ProductsTotalPremiumTableBRevisedPremium,
		ProductsTotalPremiumTableCRevisedPremium,
		ScheduledModification,
		IncludeCGL,
		IncludeOhioStopGapLiability,
		Premium,
		PremiumChange,
		PremiumWritten,
		IDField,
		UmbrellaSBOPScheduledModificationLocationInComment,
		UmbrellaSBOPScheduledModificationLocationInModification,
		UmbrellaSBOPScheduledModificationLocationOutComment,
		UmbrellaSBOPScheduledModificationLocationOutModification,
		UmbrellaSBOPScheduledModificationPremisesComment,
		UmbrellaSBOPScheduledModificationPremisesModification,
		UmbrellaSBOPScheduledModificationEquipmentComment,
		UmbrellaSBOPScheduledModificationEquipmentModification,
		UmbrellaSBOPScheduledModificationManagementComment,
		UmbrellaSBOPScheduledModificationManagementModification,
		UmbrellaSBOPScheduledModificationEmployeesComment,
		UmbrellaSBOPScheduledModificationEmployeesModification,
		UmbrellaSBOPScheduledModificationCooperationMedicalComment,
		UmbrellaSBOPScheduledModificationCooperationMedicalModification,
		UmbrellaSBOPScheduledModificationCooperationSafetyComment,
		UmbrellaSBOPScheduledModificationCooperationSafetyModification,
		ModificationTotal,
		ModificationTotalForSBOPBusinessDetailPage,
		ExtractDate,
		SourceSystemId
	FROM WBCUUmbrellaSBOPStage
),
EXP_Metadata AS (
	SELECT
	WBCUUmbrellaSBOPStageId,
	LineId,
	WBCUUmbrellaSBOPId,
	SessionId,
	Deleted AS i_Deleted,
	-- *INF*: DECODE(i_Deleted,'T',1,'F',0,NULL)
	DECODE(
	    i_Deleted,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_Deleted,
	CoverageForm,
	Description,
	EffectiveDate,
	ExpirationDate,
	PersonalLiability AS i_PersonalLiability,
	-- *INF*: DECODE(i_PersonalLiability,'T',1,'F',0,NULL)
	DECODE(
	    i_PersonalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PersonalLiability,
	PolicyNumber,
	ProfessionalLiabilityEachOccurrenceClaimLimit,
	ProfessionalLiabilityAggregate,
	BodilyInjuryByAccidentEachAccident,
	BodilyInjuryByDiseaseEachEmployee,
	BodilyInjuryByDiseaseAggregate,
	FirstMillionBasePremium,
	FirstMillionModifiedPremium,
	PremOpsTotalPremiumTable1,
	PremOpsTotalPremiumTable2,
	PremOpsTotalPremiumTable3,
	AllOtherPremium,
	ProductsTotalPremiumTableA,
	ProductsTotalPremiumTableB,
	ProductsTotalPremiumTableC,
	IncludeProfessionalLiability AS i_IncludeProfessionalLiability,
	AllOtherPremiumOverride AS i_AllOtherPremiumOverride,
	PremOpsTotalPremiumTable1PremiumOverride AS i_PremOpsTotalPremiumTable1PremiumOverride,
	PremOpsTotalPremiumTable2PremiumOverride AS i_PremOpsTotalPremiumTable2PremiumOverride,
	PremOpsTotalPremiumTable3PremiumOverride AS i_PremOpsTotalPremiumTable3PremiumOverride,
	ProductsTotalPremiumTableAPremiumOverride AS i_ProductsTotalPremiumTableAPremiumOverride,
	ProductsTotalPremiumTableBPremiumOverride AS i_ProductsTotalPremiumTableBPremiumOverride,
	ProductsTotalPremiumTableCPremiumOverride AS i_ProductsTotalPremiumTableCPremiumOverride,
	-- *INF*: DECODE(i_IncludeProfessionalLiability,'T',1,'F',0,NULL)
	DECODE(
	    i_IncludeProfessionalLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_IncludeProfessionalLiability,
	-- *INF*: DECODE(i_AllOtherPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_AllOtherPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_AllOtherPremiumOverride,
	-- *INF*: DECODE(i_PremOpsTotalPremiumTable1PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_PremOpsTotalPremiumTable1PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PremOpsTotalPremiumTable1PremiumOverride,
	-- *INF*: DECODE(i_PremOpsTotalPremiumTable2PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_PremOpsTotalPremiumTable2PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PremOpsTotalPremiumTable2PremiumOverride,
	-- *INF*: DECODE(i_PremOpsTotalPremiumTable3PremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_PremOpsTotalPremiumTable3PremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_PremOpsTotalPremiumTable3PremiumOverride,
	-- *INF*: DECODE(i_ProductsTotalPremiumTableAPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_ProductsTotalPremiumTableAPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_ProductsTotalPremiumTableAPremiumOverride,
	-- *INF*: DECODE(i_ProductsTotalPremiumTableBPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_ProductsTotalPremiumTableBPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_ProductsTotalPremiumTableBPremiumOverride,
	-- *INF*: DECODE(i_ProductsTotalPremiumTableCPremiumOverride,'T',1,'F',0,NULL)
	DECODE(
	    i_ProductsTotalPremiumTableCPremiumOverride,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_ProductsTotalPremiumTableCPremiumOverride,
	AllOtherRevisedPremium,
	PremOpsTotalPremiumTable1RevisedPremium,
	PremOpsTotalPremiumTable2RevisedPremium,
	PremOpsTotalPremiumTable3RevisedPremium,
	ProductsTotalPremiumTableARevisedPremium,
	ProductsTotalPremiumTableBRevisedPremium,
	ProductsTotalPremiumTableCRevisedPremium,
	ScheduledModification,
	IncludeCGL AS i_IncludeCGL,
	IncludeOhioStopGapLiability AS i_IncludeOhioStopGapLiability,
	-- *INF*: DECODE(i_IncludeCGL,'T',1,'F',0,NULL)
	DECODE(
	    i_IncludeCGL,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_IncludeCGL,
	-- *INF*: DECODE(i_IncludeOhioStopGapLiability,'T',1,'F',0,NULL)
	DECODE(
	    i_IncludeOhioStopGapLiability,
	    'T', 1,
	    'F', 0,
	    NULL
	) AS o_IncludeOhioStopGapLiability,
	Premium,
	PremiumChange,
	PremiumWritten,
	IDField,
	UmbrellaSBOPScheduledModificationLocationInComment,
	UmbrellaSBOPScheduledModificationLocationInModification,
	UmbrellaSBOPScheduledModificationLocationOutComment,
	UmbrellaSBOPScheduledModificationLocationOutModification,
	UmbrellaSBOPScheduledModificationPremisesComment,
	UmbrellaSBOPScheduledModificationPremisesModification,
	UmbrellaSBOPScheduledModificationEquipmentComment,
	UmbrellaSBOPScheduledModificationEquipmentModification,
	UmbrellaSBOPScheduledModificationManagementComment,
	UmbrellaSBOPScheduledModificationManagementModification,
	UmbrellaSBOPScheduledModificationEmployeesComment,
	UmbrellaSBOPScheduledModificationEmployeesModification,
	UmbrellaSBOPScheduledModificationCooperationMedicalComment,
	UmbrellaSBOPScheduledModificationCooperationMedicalModification,
	UmbrellaSBOPScheduledModificationCooperationSafetyComment,
	UmbrellaSBOPScheduledModificationCooperationSafetyModification,
	ModificationTotal,
	ModificationTotalForSBOPBusinessDetailPage,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_WBCUUmbrellaSBOPStage
),
ArchWBCUUmbrellaSBOPStage AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBCUUmbrellaSBOPStage
	(WBCUUmbrellaSBOPStageId, LineId, WBCUUmbrellaSBOPId, SessionId, Deleted, CoverageForm, Description, EffectiveDate, ExpirationDate, PersonalLiability, PolicyNumber, ProfessionalLiabilityEachOccurrenceClaimLimit, ProfessionalLiabilityAggregate, BodilyInjuryByAccidentEachAccident, BodilyInjuryByDiseaseEachEmployee, BodilyInjuryByDiseaseAggregate, FirstMillionBasePremium, FirstMillionModifiedPremium, PremOpsTotalPremiumTable1, PremOpsTotalPremiumTable2, PremOpsTotalPremiumTable3, AllOtherPremium, ProductsTotalPremiumTableA, ProductsTotalPremiumTableB, ProductsTotalPremiumTableC, IncludeProfessionalLiability, AllOtherPremiumOverride, PremOpsTotalPremiumTable1PremiumOverride, PremOpsTotalPremiumTable2PremiumOverride, PremOpsTotalPremiumTable3PremiumOverride, ProductsTotalPremiumTableAPremiumOverride, ProductsTotalPremiumTableBPremiumOverride, ProductsTotalPremiumTableCPremiumOverride, AllOtherRevisedPremium, PremOpsTotalPremiumTable1RevisedPremium, PremOpsTotalPremiumTable2RevisedPremium, PremOpsTotalPremiumTable3RevisedPremium, ProductsTotalPremiumTableARevisedPremium, ProductsTotalPremiumTableBRevisedPremium, ProductsTotalPremiumTableCRevisedPremium, ScheduledModification, IncludeCGL, IncludeOhioStopGapLiability, Premium, PremiumChange, PremiumWritten, IDField, UmbrellaSBOPScheduledModificationLocationInComment, UmbrellaSBOPScheduledModificationLocationInModification, UmbrellaSBOPScheduledModificationLocationOutComment, UmbrellaSBOPScheduledModificationLocationOutModification, UmbrellaSBOPScheduledModificationPremisesComment, UmbrellaSBOPScheduledModificationPremisesModification, UmbrellaSBOPScheduledModificationEquipmentComment, UmbrellaSBOPScheduledModificationEquipmentModification, UmbrellaSBOPScheduledModificationManagementComment, UmbrellaSBOPScheduledModificationManagementModification, UmbrellaSBOPScheduledModificationEmployeesComment, UmbrellaSBOPScheduledModificationEmployeesModification, UmbrellaSBOPScheduledModificationCooperationMedicalComment, UmbrellaSBOPScheduledModificationCooperationMedicalModification, UmbrellaSBOPScheduledModificationCooperationSafetyComment, UmbrellaSBOPScheduledModificationCooperationSafetyModification, ModificationTotal, ModificationTotalForSBOPBusinessDetailPage, ExtractDate, SourceSystemId, AuditId)
	SELECT 
	WBCUUMBRELLASBOPSTAGEID, 
	LINEID, 
	WBCUUMBRELLASBOPID, 
	SESSIONID, 
	o_Deleted AS DELETED, 
	COVERAGEFORM, 
	DESCRIPTION, 
	EFFECTIVEDATE, 
	EXPIRATIONDATE, 
	o_PersonalLiability AS PERSONALLIABILITY, 
	POLICYNUMBER, 
	PROFESSIONALLIABILITYEACHOCCURRENCECLAIMLIMIT, 
	PROFESSIONALLIABILITYAGGREGATE, 
	BODILYINJURYBYACCIDENTEACHACCIDENT, 
	BODILYINJURYBYDISEASEEACHEMPLOYEE, 
	BODILYINJURYBYDISEASEAGGREGATE, 
	FIRSTMILLIONBASEPREMIUM, 
	FIRSTMILLIONMODIFIEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE1, 
	PREMOPSTOTALPREMIUMTABLE2, 
	PREMOPSTOTALPREMIUMTABLE3, 
	ALLOTHERPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEA, 
	PRODUCTSTOTALPREMIUMTABLEB, 
	PRODUCTSTOTALPREMIUMTABLEC, 
	o_IncludeProfessionalLiability AS INCLUDEPROFESSIONALLIABILITY, 
	o_AllOtherPremiumOverride AS ALLOTHERPREMIUMOVERRIDE, 
	o_PremOpsTotalPremiumTable1PremiumOverride AS PREMOPSTOTALPREMIUMTABLE1PREMIUMOVERRIDE, 
	o_PremOpsTotalPremiumTable2PremiumOverride AS PREMOPSTOTALPREMIUMTABLE2PREMIUMOVERRIDE, 
	o_PremOpsTotalPremiumTable3PremiumOverride AS PREMOPSTOTALPREMIUMTABLE3PREMIUMOVERRIDE, 
	o_ProductsTotalPremiumTableAPremiumOverride AS PRODUCTSTOTALPREMIUMTABLEAPREMIUMOVERRIDE, 
	o_ProductsTotalPremiumTableBPremiumOverride AS PRODUCTSTOTALPREMIUMTABLEBPREMIUMOVERRIDE, 
	o_ProductsTotalPremiumTableCPremiumOverride AS PRODUCTSTOTALPREMIUMTABLECPREMIUMOVERRIDE, 
	ALLOTHERREVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE1REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE2REVISEDPREMIUM, 
	PREMOPSTOTALPREMIUMTABLE3REVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEAREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLEBREVISEDPREMIUM, 
	PRODUCTSTOTALPREMIUMTABLECREVISEDPREMIUM, 
	SCHEDULEDMODIFICATION, 
	o_IncludeCGL AS INCLUDECGL, 
	o_IncludeOhioStopGapLiability AS INCLUDEOHIOSTOPGAPLIABILITY, 
	PREMIUM, 
	PREMIUMCHANGE, 
	PREMIUMWRITTEN, 
	IDFIELD, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONLOCATIONINCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONLOCATIONINMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONLOCATIONOUTCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONLOCATIONOUTMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONPREMISESCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONPREMISESMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONEQUIPMENTCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONEQUIPMENTMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONMANAGEMENTCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONMANAGEMENTMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONEMPLOYEESCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONEMPLOYEESMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONCOOPERATIONMEDICALCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONCOOPERATIONMEDICALMODIFICATION, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONCOOPERATIONSAFETYCOMMENT, 
	UMBRELLASBOPSCHEDULEDMODIFICATIONCOOPERATIONSAFETYMODIFICATION, 
	MODIFICATIONTOTAL, 
	MODIFICATIONTOTALFORSBOPBUSINESSDETAILPAGE, 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID
	FROM EXP_Metadata
),