WITH
SQ_DC_WC_StateTerm AS (
	WITH cte_DCWCStateTerm(Sessionid) as
	(select sessionid from @{pipeline().parameters.SOURCE_DATABASE_WB}.@{pipeline().parameters.SOURCE_TABLE_OWNER}.WB_EDWIncrementalDataQualitySessions where ModifiedDate between '@{pipeline().parameters.SELECTION_START_TS}' and '@{pipeline().parameters.SELECTION_END_TS}' 
	AND Autoshred<> '1' 
	 UNION 
	 select distinct A.sessionid from @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Session A Inner join @{pipeline().parameters.SOURCE_TABLE_OWNER}.DC_Transaction B on A.SessionID=B.SessionID where B.State<> 'committed' and A.CreateDateTime>='@{pipeline().parameters.SELECTION_START_TS}')
	SELECT 
	X.WC_StateId, 
	X.WC_StateTermId, 
	X.SessionId, 
	X.Id, 
	X.AlternatePreferredPlanClaimsInfo, 
	X.AlternatePreferredPlanEmployerType, 
	X.AtomicRadiationUnitsOfExposure, 
	X.BuildGroup, 
	X.CoinsuranceSelection, 
	X.DeductibleSelection, 
	X.DeductibleType, 
	X.EmployingPreviouslyInjuredEmployeesFactorDisplay, 
	X.ExperienceModEffectiveDate, 
	X.ExperienceModType, 
	X.ExperienceRatingOptions, 
	X.ManagedCareFactorDisplay, 
	X.NumberOfStrikeDutyDays, 
	X.NumberOfStrikeDutyEmployeeDays, 
	X.NumberOfStrikeDutyEmployees, 
	X.PeriodEndDate, 
	X.PeriodStartDate, 
	X.PeriodTerm, 
	X.PolicyType, 
	X.RateEffectiveDate, 
	X.SafetyCertificationFactorDisplay, 
	X.ScheduleRatingChoice, 
	X.SmallDeductibleSelection, 
	X.TermType, 
	X.Type, 
	X.TypeOfEmployer, 
	X.WaiverOfSubrogationFactorDisplay, 
	X.WorkplaceSafetyProgramFactorDisplay,
	X.CombinedPolicyPremium,
	X.ManualPremium,
	X.MinimumPremium,
	X.ModifiedPremium,
	X.SubjectPremium,
	X.TotalStandardPremium   
	FROM
	DC_WC_StateTerm X
	inner join
	cte_DCWCStateTerm Y on X.Sessionid = Y.Sessionid
	@{pipeline().parameters.WHERE_CLAUSE}
),
EXP_Metadata AS (
	SELECT
	WC_StateId AS i_WC_StateId,
	WC_StateTermId AS i_WC_StateTermId,
	SessionId AS i_SessionId,
	Id AS i_Id,
	AlternatePreferredPlanClaimsInfo AS i_AlternatePreferredPlanClaimsInfo,
	AlternatePreferredPlanEmployerType AS i_AlternatePreferredPlanEmployerType,
	AtomicRadiationUnitsOfExposure AS i_AtomicRadiationUnitsOfExposure,
	BuildGroup AS i_BuildGroup,
	CoinsuranceSelection AS i_CoinsuranceSelection,
	DeductibleSelection AS i_DeductibleSelection,
	DeductibleType AS i_DeductibleType,
	EmployingPreviouslyInjuredEmployeesFactorDisplay AS i_EmployingPreviouslyInjuredEmployeesFactorDisplay,
	ExperienceModEffectiveDate AS i_ExperienceModEffectiveDate,
	ExperienceModType AS i_ExperienceModType,
	ExperienceRatingOptions AS i_ExperienceRatingOptions,
	ManagedCareFactorDisplay AS i_ManagedCareFactorDisplay,
	NumberOfStrikeDutyDays AS i_NumberOfStrikeDutyDays,
	NumberOfStrikeDutyEmployeeDays AS i_NumberOfStrikeDutyEmployeeDays,
	NumberOfStrikeDutyEmployees AS i_NumberOfStrikeDutyEmployees,
	PeriodEndDate AS i_PeriodEndDate,
	PeriodStartDate AS i_PeriodStartDate,
	PeriodTerm AS i_PeriodTerm,
	PolicyType AS i_PolicyType,
	RateEffectiveDate AS i_RateEffectiveDate,
	SafetyCertificationFactorDisplay AS i_SafetyCertificationFactorDisplay,
	ScheduleRatingChoice AS i_ScheduleRatingChoice,
	SmallDeductibleSelection AS i_SmallDeductibleSelection,
	TermType AS i_TermType,
	Type AS i_Type,
	TypeOfEmployer AS i_TypeOfEmployer,
	WaiverOfSubrogationFactorDisplay AS i_WaiverOfSubrogationFactorDisplay,
	WorkplaceSafetyProgramFactorDisplay AS i_WorkplaceSafetyProgramFactorDisplay,
	i_WC_StateTermId AS o_WC_StateTermId,
	i_SessionId AS o_SessionId,
	i_WC_StateId AS o_WC_StateId,
	i_Id AS o_Id,
	i_AlternatePreferredPlanClaimsInfo AS o_AlternatePreferredPlanClaimsInfo,
	i_AlternatePreferredPlanEmployerType AS o_AlternatePreferredPlanEmployerType,
	i_AtomicRadiationUnitsOfExposure AS o_AtomicRadiationUnitsOfExposure,
	i_BuildGroup AS o_BuildGroup,
	i_CoinsuranceSelection AS o_CoinsuranceSelection,
	i_DeductibleSelection AS o_DeductibleSelection,
	i_DeductibleType AS o_DeductibleType,
	i_EmployingPreviouslyInjuredEmployeesFactorDisplay AS o_EmployingPreviouslyInjuredEmployeesFactorDisplay,
	i_ExperienceModEffectiveDate AS o_ExperienceModEffectiveDate,
	i_ExperienceModType AS o_ExperienceModType,
	i_ExperienceRatingOptions AS o_ExperienceRatingOptions,
	i_ManagedCareFactorDisplay AS o_ManagedCareFactorDisplay,
	i_NumberOfStrikeDutyDays AS o_NumberOfStrikeDutyDays,
	i_NumberOfStrikeDutyEmployeeDays AS o_NumberOfStrikeDutyEmployeeDays,
	i_NumberOfStrikeDutyEmployees AS o_NumberOfStrikeDutyEmployees,
	i_PeriodEndDate AS o_PeriodEndDate,
	i_PeriodStartDate AS o_PeriodStartDate,
	i_PeriodTerm AS o_PeriodTerm,
	i_PolicyType AS o_PolicyType,
	i_RateEffectiveDate AS o_RateEffectiveDate,
	i_SafetyCertificationFactorDisplay AS o_SafetyCertificationFactorDisplay,
	i_ScheduleRatingChoice AS o_ScheduleRatingChoice,
	i_SmallDeductibleSelection AS o_SmallDeductibleSelection,
	i_TermType AS o_TermType,
	i_Type AS o_Type,
	i_TypeOfEmployer AS o_TypeOfEmployer,
	i_WaiverOfSubrogationFactorDisplay AS o_WaiverOfSubrogationFactorDisplay,
	i_WorkplaceSafetyProgramFactorDisplay AS o_WorkplaceSafetyProgramFactorDisplay,
	sysdate AS o_ExtractDate,
	@{pipeline().parameters.SOURCE_SYSTEM_ID} AS o_SourceSystemId,
	CombinedPolicyPremium,
	ManualPremium,
	MinimumPremium,
	ModifiedPremium,
	SubjectPremium,
	TotalStandardPremium
	FROM SQ_DC_WC_StateTerm
),
DCWCStateTermStaging AS (
	TRUNCATE TABLE @{pipeline().parameters.TARGET_TABLE_OWNER}.DCWCStateTermStaging;
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.DCWCStateTermStaging
	(WC_StateTermId, SessionId, WC_StateId, Id, AlternatePreferredPlanClaimsInfo, AlternatePreferredPlanEmployerType, AtomicRadiationUnitsOfExposure, BuildGroup, CoinsuranceSelection, DeductibleSelection, DeductibleType, EmployingPreviouslyInjuredEmployeesFactorDisplay, ExperienceModEffectiveDate, ExperienceModType, ExperienceRatingOptions, ManagedCareFactorDisplay, NumberOfStrikeDutyDays, NumberOfStrikeDutyEmployeeDays, NumberOfStrikeDutyEmployees, PeriodEndDate, PeriodStartDate, PeriodTerm, PolicyType, RateEffectiveDate, SafetyCertificationFactorDisplay, ScheduleRatingChoice, SmallDeductibleSelection, TermType, Type, TypeOfEmployer, WaiverOfSubrogationFactorDisplay, WorkplaceSafetyProgramFactorDisplay, ExtractDate, SourceSystemId, CombinedPolicyPremium, ManualPremium, MinimumPremium, ModifiedPremium, SubjectPremium, TotalStandardPremium)
	SELECT 
	o_WC_StateTermId AS WC_STATETERMID, 
	o_SessionId AS SESSIONID, 
	o_WC_StateId AS WC_STATEID, 
	o_Id AS ID, 
	o_AlternatePreferredPlanClaimsInfo AS ALTERNATEPREFERREDPLANCLAIMSINFO, 
	o_AlternatePreferredPlanEmployerType AS ALTERNATEPREFERREDPLANEMPLOYERTYPE, 
	o_AtomicRadiationUnitsOfExposure AS ATOMICRADIATIONUNITSOFEXPOSURE, 
	o_BuildGroup AS BUILDGROUP, 
	o_CoinsuranceSelection AS COINSURANCESELECTION, 
	o_DeductibleSelection AS DEDUCTIBLESELECTION, 
	o_DeductibleType AS DEDUCTIBLETYPE, 
	o_EmployingPreviouslyInjuredEmployeesFactorDisplay AS EMPLOYINGPREVIOUSLYINJUREDEMPLOYEESFACTORDISPLAY, 
	o_ExperienceModEffectiveDate AS EXPERIENCEMODEFFECTIVEDATE, 
	o_ExperienceModType AS EXPERIENCEMODTYPE, 
	o_ExperienceRatingOptions AS EXPERIENCERATINGOPTIONS, 
	o_ManagedCareFactorDisplay AS MANAGEDCAREFACTORDISPLAY, 
	o_NumberOfStrikeDutyDays AS NUMBEROFSTRIKEDUTYDAYS, 
	o_NumberOfStrikeDutyEmployeeDays AS NUMBEROFSTRIKEDUTYEMPLOYEEDAYS, 
	o_NumberOfStrikeDutyEmployees AS NUMBEROFSTRIKEDUTYEMPLOYEES, 
	o_PeriodEndDate AS PERIODENDDATE, 
	o_PeriodStartDate AS PERIODSTARTDATE, 
	o_PeriodTerm AS PERIODTERM, 
	o_PolicyType AS POLICYTYPE, 
	o_RateEffectiveDate AS RATEEFFECTIVEDATE, 
	o_SafetyCertificationFactorDisplay AS SAFETYCERTIFICATIONFACTORDISPLAY, 
	o_ScheduleRatingChoice AS SCHEDULERATINGCHOICE, 
	o_SmallDeductibleSelection AS SMALLDEDUCTIBLESELECTION, 
	o_TermType AS TERMTYPE, 
	o_Type AS TYPE, 
	o_TypeOfEmployer AS TYPEOFEMPLOYER, 
	o_WaiverOfSubrogationFactorDisplay AS WAIVEROFSUBROGATIONFACTORDISPLAY, 
	o_WorkplaceSafetyProgramFactorDisplay AS WORKPLACESAFETYPROGRAMFACTORDISPLAY, 
	o_ExtractDate AS EXTRACTDATE, 
	o_SourceSystemId AS SOURCESYSTEMID, 
	COMBINEDPOLICYPREMIUM, 
	MANUALPREMIUM, 
	MINIMUMPREMIUM, 
	MODIFIEDPREMIUM, 
	SUBJECTPREMIUM, 
	TOTALSTANDARDPREMIUM
	FROM EXP_Metadata
),