WITH
SQ_WBWCLineStage AS (
	SELECT
		WBWCLineStageId,
		WCLineId,
		WBWCLineId,
		SessionId,
		InterstateRiskID,
		CurrentIteration,
		Space,
		Selected,
		ClaimsInExcessOf,
		RetrieveExperienceModifier,
		AddState,
		ManuallyCalculate,
		OtherStatesInsuranceConditional,
		OtherStatesInsuranceIterator,
		OtherStatesInsuranceCalculation,
		OtherStatesInsuranceSumIterator,
		MinimumPremiumMaximum,
		ExpenseConstantMaximum,
		TotalClaimsIncurred,
		TotalStatePremiumForDividend,
		DividendAmount,
		DividendPrior,
		DividendChange,
		DividendWritten,
		DividendPremium,
		TotalDividendIncurredLossRatio,
		DividendPercentage,
		DividendPercentagePrior,
		DividendAmountFinal,
		DividendProjectedDate,
		DividendPaidDate,
		TotalClaimsAmountPaid,
		TotalClaimsOutstanding,
		TotalClaimsExpense,
		DividendWrittenDuplicatePath,
		DividendCharge,
		OtherPoliciesWC000503,
		PriorCountForRetrospectiveCalculation,
		AnyContractorClassCode,
		PreviousFinalCommission,
		ExperienceModMessage,
		ExperienceModIndicator,
		Value,
		RetrieveExperienceMod,
		ExtractDate,
		SourceSystemId
	FROM WBWCLineStage
),
EXP_Metadata AS (
	SELECT
	WBWCLineStageId,
	WCLineId,
	WBWCLineId,
	SessionId,
	InterstateRiskID,
	CurrentIteration,
	Space,
	Selected,
	-- *INF*: IIF(Selected='T', '1','0')
	IFF(Selected = 'T', '1', '0') AS o_Selected,
	ClaimsInExcessOf,
	RetrieveExperienceModifier,
	AddState,
	ManuallyCalculate,
	-- *INF*: IIF(ManuallyCalculate='T','1','0')
	IFF(ManuallyCalculate = 'T', '1', '0') AS o_ManuallyCalculate,
	OtherStatesInsuranceConditional,
	OtherStatesInsuranceIterator,
	-- *INF*: IIF(OtherStatesInsuranceIterator='T', '1', '0')
	IFF(OtherStatesInsuranceIterator = 'T', '1', '0') AS o_OtherStatesInsuranceIterator,
	OtherStatesInsuranceCalculation,
	OtherStatesInsuranceSumIterator,
	MinimumPremiumMaximum,
	ExpenseConstantMaximum,
	TotalClaimsIncurred,
	TotalStatePremiumForDividend,
	DividendAmount,
	DividendPrior,
	DividendChange,
	DividendWritten,
	DividendPremium,
	TotalDividendIncurredLossRatio,
	DividendPercentage,
	DividendPercentagePrior,
	DividendAmountFinal,
	DividendProjectedDate,
	DividendPaidDate,
	TotalClaimsAmountPaid,
	TotalClaimsOutstanding,
	TotalClaimsExpense,
	DividendWrittenDuplicatePath,
	DividendCharge,
	OtherPoliciesWC000503,
	PriorCountForRetrospectiveCalculation,
	AnyContractorClassCode,
	-- *INF*: IIF(AnyContractorClassCode='T','1','0')
	IFF(AnyContractorClassCode = 'T', '1', '0') AS o_AnyContractorClassCode,
	PreviousFinalCommission,
	ExperienceModMessage,
	ExperienceModIndicator,
	Value,
	RetrieveExperienceMod,
	ExtractDate,
	SourceSystemId,
	@{pipeline().parameters.WBMI_AUDIT_CONTROL_RUN_ID} AS o_AuditId
	FROM SQ_WBWCLineStage
),
TGT_ArchWBWCLineStage_Insert AS (
	INSERT INTO @{pipeline().parameters.TARGET_TABLE_OWNER}.ArchWBWCLineStage
	(ExtractDate, SourceSystemId, AuditId, WBWCLineStageId, WCLineId, WBWCLineId, SessionId, InterstateRiskID, CurrentIteration, Space, Selected, ClaimsInExcessOf, RetrieveExperienceModifier, AddState, ManuallyCalculate, OtherStatesInsuranceConditional, OtherStatesInsuranceIterator, OtherStatesInsuranceCalculation, OtherStatesInsuranceSumIterator, MinimumPremiumMaximum, ExpenseConstantMaximum, TotalClaimsIncurred, TotalStatePremiumForDividend, DividendAmount, DividendPrior, DividendChange, DividendWritten, DividendPremium, TotalDividendIncurredLossRatio, DividendPercentage, DividendPercentagePrior, DividendAmountFinal, DividendProjectedDate, DividendPaidDate, TotalClaimsAmountPaid, TotalClaimsOutstanding, TotalClaimsExpense, DividendWrittenDuplicatePath, DividendCharge, OtherPoliciesWC000503, PriorCountForRetrospectiveCalculation, AnyContractorClassCode, PreviousFinalCommission, ExperienceModMessage, ExperienceModIndicator, Value, RetrieveExperienceMod)
	SELECT 
	EXTRACTDATE, 
	SOURCESYSTEMID, 
	o_AuditId AS AUDITID, 
	WBWCLINESTAGEID, 
	WCLINEID, 
	WBWCLINEID, 
	SESSIONID, 
	INTERSTATERISKID, 
	CURRENTITERATION, 
	SPACE, 
	o_Selected AS SELECTED, 
	CLAIMSINEXCESSOF, 
	RETRIEVEEXPERIENCEMODIFIER, 
	ADDSTATE, 
	o_ManuallyCalculate AS MANUALLYCALCULATE, 
	OTHERSTATESINSURANCECONDITIONAL, 
	o_OtherStatesInsuranceIterator AS OTHERSTATESINSURANCEITERATOR, 
	OTHERSTATESINSURANCECALCULATION, 
	OTHERSTATESINSURANCESUMITERATOR, 
	MINIMUMPREMIUMMAXIMUM, 
	EXPENSECONSTANTMAXIMUM, 
	TOTALCLAIMSINCURRED, 
	TOTALSTATEPREMIUMFORDIVIDEND, 
	DIVIDENDAMOUNT, 
	DIVIDENDPRIOR, 
	DIVIDENDCHANGE, 
	DIVIDENDWRITTEN, 
	DIVIDENDPREMIUM, 
	TOTALDIVIDENDINCURREDLOSSRATIO, 
	DIVIDENDPERCENTAGE, 
	DIVIDENDPERCENTAGEPRIOR, 
	DIVIDENDAMOUNTFINAL, 
	DIVIDENDPROJECTEDDATE, 
	DIVIDENDPAIDDATE, 
	TOTALCLAIMSAMOUNTPAID, 
	TOTALCLAIMSOUTSTANDING, 
	TOTALCLAIMSEXPENSE, 
	DIVIDENDWRITTENDUPLICATEPATH, 
	DIVIDENDCHARGE, 
	OTHERPOLICIESWC000503, 
	PRIORCOUNTFORRETROSPECTIVECALCULATION, 
	o_AnyContractorClassCode AS ANYCONTRACTORCLASSCODE, 
	PREVIOUSFINALCOMMISSION, 
	EXPERIENCEMODMESSAGE, 
	EXPERIENCEMODINDICATOR, 
	VALUE, 
	RETRIEVEEXPERIENCEMOD
	FROM EXP_Metadata
),